'use strict';
// ══════════════════════════════════════════════════════════════════════════
//  Grade 9 Physics - Scientific Inquiry, depth pass   (chapter examWeight 2)
//
//  ⚠ THE SPLIT LEFT PHYSICS WITH 12 INQUIRY/STS ITEMS IN TWO SUBSECTIONS.
//    g9s-inquiry and g9s-sts are cross-cutting and were divided between the
//    three science packs by subject affinity rather than duplicated, so
//    Biology kept hypothesis_testing / recording_data / interpreting_results,
//    Chemistry kept lab_safety / reporting_findings / research_and_ict, and
//    Physics was left holding formula_rearrangement alone. A child practising
//    Physics could not reach the inquiry skills at all. This file declares and
//    fills five of those subsections again IN A PHYSICS CONTEXT - the same
//    skill, examined on the apparatus this paper actually uses.
//
//  ⚠ EVERY ITEM IS SET ON PHYSICS APPARATUS, DELIBERATELY. The blueprint
//    (§X.6) measures practical work at 8-12 marks per paper and finds it
//    ATTACHED to a subject-matter question, never asked on its own: the
//    variable is a pendulum length, the anomaly is a stopwatch reading, the
//    safety precaution is about a hot ray-box lamp. An inquiry item set in a
//    vacuum teaches a vocabulary, not the mark.
//
//  ⚠ TIMING IS THE PHYSICS-SPECIFIC ERROR and it recurs: reaction time on a
//    stopwatch, timing 20 oscillations and dividing, parallax on a ruler or a
//    measuring cylinder. Physics 2021 Q3(b) turns a set-square arrangement
//    into a parallax question and Physics 2023 Q5(b) times a pendulum.
//
//  ⚠ <i> IS AN HTML BREAKOUT TAG AND MUST NEVER APPEAR INSIDE AN <svg>.
//
//  Source: NCE Science (Physics) 2021, 2022, 2023, 2025; NCF Grades 7-9
//  §Scientific Inquiry (printed 70 / PDF 76).
// ══════════════════════════════════════════════════════════════════════════

(function () {

const CH = 'g9s-inquiry';

// ── A results table in the shape the papers print one: independent quantity
//    in the left column, both headings carrying a unit. Built the same way as
//    the table in inquiry.js so the two figures cannot drift apart.
const resultsTable = (title, h1, h2, rows) => {
  const W = 250, X0 = 26, RH = 19, top = 24, c1 = X0 + 100;
  const H = top + RH * (rows.length + 1) + 10;
  let g = '<svg viewBox="0 0 ' + W + ' ' + H + '" width="260" role="img" aria-label="a table of results">';
  g += '<text x="' + (W / 2) + '" y="15" font-size="10" text-anchor="middle" fill="#0f172a">' + title + '</text>';
  g += '<rect x="' + X0 + '" y="' + top + '" width="' + (W - 2 * X0) + '" height="' + (RH * (rows.length + 1)) + '" fill="none" stroke="#0f172a" stroke-width="1.5"/>';
  g += '<line x1="' + c1 + '" y1="' + top + '" x2="' + c1 + '" y2="' + (top + RH * (rows.length + 1)) + '" stroke="#0f172a" stroke-width="1.5"/>';
  g += '<line x1="' + X0 + '" y1="' + (top + RH) + '" x2="' + (W - X0) + '" y2="' + (top + RH) + '" stroke="#0f172a" stroke-width="1.5"/>';
  g += '<text x="' + (X0 + 5) + '" y="' + (top + 13) + '" font-size="9" fill="#0f172a">' + h1 + '</text>';
  g += '<text x="' + (c1 + 5) + '" y="' + (top + 13) + '" font-size="9" fill="#0f172a">' + h2 + '</text>';
  rows.forEach((r, i) => {
    const y = top + RH * (i + 1);
    if (i) g += '<line x1="' + X0 + '" y1="' + y + '" x2="' + (W - X0) + '" y2="' + y + '" stroke="#cbd5e1" stroke-width="1"/>';
    g += '<text x="' + (X0 + 5) + '" y="' + (y + 13) + '" font-size="9" fill="#334155">' + r[0] + '</text>';
    g += '<text x="' + (c1 + 5) + '" y="' + (y + 13) + '" font-size="9" fill="#334155">' + r[1] + '</text>';
  });
  return g + '</svg>';
};

const RAMP = resultsTable('Trolley released down a ramp', 'Height / cm', 'Speed / m/s',
  [['10', '1.4'], ['20', '2.0'], ['30', '2.4'], ['40', '2.8'], ['50', '3.2']]);

const CELLS = resultsTable('Cells added to a series circuit', 'Cells', 'Current / A',
  [['1', '0.2'], ['2', '0.4'], ['3', '0.6'], ['4', '1.5'], ['5', '1.0']]);

const NUM = [
  ['g9s-inq-301', 'formula_rearrangement', 2,
   'Speed = distance &divide; time. A trolley runs 2.4 m down a ramp in 0.8 s. Calculate its speed, in m/s.',
   3, 'Substitute straight into the relationship.', '2.4 / 0.8 = 3 m/s.'],
  ['g9s-inq-302', 'formula_rearrangement', 3,
   'Acceleration = change in speed &divide; time. A trolley speeds up from 4 m/s to 20 m/s in 4 s. Calculate its acceleration, in m/s&sup2;.',
   4, 'Find the change in speed first, then divide by the time.', '(20 &minus; 4) / 4 = 16 / 4 = 4 m/s&sup2;.'],
  ['g9s-inq-303', 'formula_rearrangement', 3,
   'Acceleration = change in speed &divide; time. A car accelerates at 3 m/s&sup2; for 6 s. Calculate the change in speed, in m/s.',
   18, 'Rearrange to change in speed = acceleration &times; time.', '3 &times; 6 = 18 m/s.'],
  ['g9s-inq-304', 'formula_rearrangement', 2,
   'V = IR. A current of 2 A flows through a resistor of 6 &#8486;. Calculate the voltage across it, in volts.',
   12, 'Substitute straight into the relationship.', '2 &times; 6 = 12 V.'],
  ['g9s-inq-305', 'formula_rearrangement', 3,
   'V = IR. A voltage of 12 V is applied across a resistor of 4 &#8486;. Calculate the current, in amperes.',
   3, 'Rearrange to I = V &divide; R.', '12 / 4 = 3 A.'],
  ['g9s-inq-306', 'formula_rearrangement', 3,
   'V = IR. A current of 3 A flows when the voltage is 9 V. Calculate the resistance, in ohms.',
   3, 'Rearrange to R = V &divide; I.', '9 / 3 = 3 &#8486;.'],
  ['g9s-inq-307', 'formula_rearrangement', 2,
   'In series, R = R&#8321; + R&#8322;. Two resistors of 5 &#8486; and 7 &#8486; are joined in series. Calculate the total resistance, in ohms.',
   12, 'Series resistances simply add.', '5 + 7 = 12 &#8486;.'],
  ['g9s-inq-308', 'formula_rearrangement', 3,
   'Q = It. A current of 4 A flows for 15 s. Calculate the charge that passes, in coulombs.',
   60, 'Substitute straight into the relationship.', '4 &times; 15 = 60 C.'],
  ['g9s-inq-309', 'formula_rearrangement', 3,
   'Q = It. A charge of 30 C passes when the current is 5 A. Calculate the time taken, in seconds.',
   6, 'Rearrange to t = Q &divide; I.', '30 / 5 = 6 s.'],
  ['g9s-inq-310', 'formula_rearrangement', 3,
   'W = QV. A charge of 6 C moves through a potential difference of 4 V. Calculate the work done, in joules.',
   24, 'Substitute straight into the relationship.', '6 &times; 4 = 24 J.'],
  ['g9s-inq-311', 'formula_rearrangement', 3,
   'Time for one swing = total time &divide; number of swings. A pendulum makes 20 swings in 30 s. Calculate the time for one swing, in seconds.',
   1.5, 'Divide the total time by how many swings were counted.', '30 / 20 = 1.5 s.'],
  ['g9s-inq-312', 'formula_rearrangement', 4,
   'Time for one swing = total time &divide; number of swings. One swing of a pendulum takes 0.8 s. Calculate how many swings it makes in 24 s.',
   30, 'Rearrange to number of swings = total time &divide; time for one swing.', '24 / 0.8 = 30 swings.'],
  ['g9s-inq-313', 'formula_rearrangement', 4,
   'Speed = distance &divide; time. A cyclist covers 90 m at a steady 6 m/s. Calculate the time taken, in seconds.',
   15, 'Rearrange to time = distance &divide; speed.', '90 / 6 = 15 s.'],
  ['g9s-inq-314', 'formula_rearrangement', 4,
   'Density = mass &divide; volume. A metal block of mass 84 g has a density of 4 g/cm&#179;. Calculate its volume, in cm&#179;.',
   21, 'Rearrange to volume = mass &divide; density.', '84 / 4 = 21 cm&#179;.'],

  ['g9s-inq-343', 'recording_data', 3,
   'A pupil times twenty swings of a pendulum three times and records 12.4 s, 12.6 s and 12.5 s. Calculate the mean, in seconds.',
   12.5, 'Add the three readings, then divide by how many there are.', '(12.4 + 12.6 + 12.5) / 3 = 37.5 / 3 = 12.5 s.'],
  ['g9s-inq-344', 'recording_data', 3,
   'A pupil measures the same length of wire three times and records 4.2 cm, 4.4 cm and 4.3 cm. Calculate the mean, in cm.',
   4.3, 'Add the three readings, then divide by how many there are.', '(4.2 + 4.4 + 4.3) / 3 = 12.9 / 3 = 4.3 cm.'],

  ['g9s-inq-361', 'interpreting_results', 4,
   'A car moves at a steady 8 m/s for 5 s. The distance is the area under the speed&ndash;time graph. Calculate that distance, in metres.',
   40, 'The area under a straight flat line is a rectangle.', 'Area = 8 &times; 5 = 40 m, so the car travels 40 m.'],
  ['g9s-inq-362', 'interpreting_results', 4,
   'On a speed&ndash;time graph a trolley speeds up from 0 to 12 m/s in 4 s. The gradient gives the acceleration. Calculate it, in m/s&sup2;.',
   3, 'Gradient is the change up divided by the change along.', '12 / 4 = 3 m/s&sup2;.'],
];

NUM.forEach(([id, subsection, difficulty, question, answer, hint, explanation]) => {
  STATIC_QUESTIONS.push(makeNum({ id, chapterId: CH, subsection, difficulty,
    question, answer, hint, explanation }));
});

const MCQ = [
  // ── hypothesis_testing ────────────────────────────────────────────────
  ['g9s-inq-315', 'hypothesis_testing', 1,
   'What is a <b>hypothesis</b> in an investigation?',
   ['A prediction that can be tested by an experiment',
    'A reading that has already been taken from a meter',
    'A conclusion written at the very end of a report',
    'A neat table of the results collected in a lesson'],
   'A prediction that can be tested by an experiment',
   'Think about when it is written: before or after the readings?',
   'A hypothesis is a prediction made <b>before</b> the experiment, worded so that measurements can support it or go against it. A conclusion comes afterwards.'],

  ['g9s-inq-316', 'hypothesis_testing', 2,
   'A pupil predicts that a longer pendulum takes longer to swing. Which is the <b>independent</b> variable?',
   ['The length of the pendulum', 'The time taken for one swing',
    'The mass of the metal bob', 'The height of the clamp stand'],
   'The length of the pendulum',
   'The independent variable is the one the pupil chooses to change.',
   'The pupil deliberately changes the <b>length</b>, so length is the independent variable. The swing time is what is measured because of it.'],

  ['g9s-inq-317', 'hypothesis_testing', 2,
   'In the same pendulum test, which is the <b>dependent</b> variable?',
   ['The time taken for one swing', 'The length of the string',
    'The mass of the metal bob', 'The colour of the string'],
   'The time taken for one swing',
   'The dependent variable is the one that is measured each time.',
   'The swing time is measured to see what the change in length does to it, so it is the dependent variable.'],

  ['g9s-inq-318', 'hypothesis_testing', 2,
   'In the pendulum test, which should be <b>kept the same</b> each time?',
   ['The mass of the metal bob', 'The length of the string',
    'The time for one swing', 'The number of swings timed'],
   'The mass of the metal bob',
   'One of these is being changed on purpose and one is being measured.',
   'Length is changed and swing time is measured, so everything else &mdash; including the mass of the bob &mdash; is kept the same. That is what makes it a fair test.'],

  ['g9s-inq-319', 'hypothesis_testing', 3,
   'Why is an investigation <b>not</b> a fair test if two variables are changed at once?',
   ['You cannot tell which change caused the result',
    'The readings always come out far too large',
    'The apparatus would take much longer to set up',
    'The results table needs one more column'],
   'You cannot tell which change caused the result',
   'Think about what the result would be evidence for.',
   'If both the ramp height and the trolley mass change, a faster trolley could be caused by either one. Only one variable may change at a time.'],

  ['g9s-inq-320', 'hypothesis_testing', 2,
   'A pupil predicts that a steeper ramp makes a trolley run faster. What should be changed each time?',
   ['The height of the raised end of the ramp',
    'The speed of the trolley at the bottom',
    'The mass of the trolley on the ramp',
    'The length of the ramp used in the test'],
   'The height of the raised end of the ramp',
   'What does the word "steeper" describe?',
   'Steepness is set by the height of the raised end, so that is the variable to change. The speed is the measurement, not the change.'],

  ['g9s-inq-321', 'hypothesis_testing', 3,
   'In the ramp test, which of these must be kept the same for a fair test?',
   ['The trolley used and its total mass',
    'The height of the end of the ramp',
    'The speed reached at the bottom',
    'The time taken to run down it'],
   'The trolley used and its total mass',
   'Two of these change on their own once the ramp is made steeper.',
   'Only the ramp height should change. Using the same trolley keeps the mass constant, so any change in speed can be blamed on the slope.'],

  ['g9s-inq-322', 'hypothesis_testing', 2,
   'To test "more cells make a lamp brighter", what should the pupil <b>measure</b> each time?',
   ['The current flowing in the circuit', 'The number of cells connected up',
    'The length of the wires used', 'The colour of the lamp holder'],
   'The current flowing in the circuit',
   'Brightness needs a number, and an ammeter gives one.',
   'Counting cells is the change; brightness has to be turned into a measurement, and the current read on the ammeter does that.'],

  ['g9s-inq-323', 'hypothesis_testing', 3,
   'Which statement is a <b>testable</b> hypothesis?',
   ['A longer wire will let a smaller current flow',
    'Circuits are the best topic in all of physics',
    'Electricity is a very interesting thing to study',
    'Physics lessons should be longer than they are'],
   'A longer wire will let a smaller current flow',
   'Which one could be shown to be wrong by taking readings?',
   'A hypothesis has to be something an experiment can support or contradict. The other three are opinions, and no ammeter can settle them.'],

  ['g9s-inq-324', 'hypothesis_testing', 2,
   'Which sentence is written as a <b>prediction</b> for an investigation?',
   ['If the ramp is steeper, the trolley will go faster',
    'The trolley ran down the ramp and hit the block',
    'The ramp was raised on three wooden blocks',
    'The trolley is made of metal and has wheels'],
   'If the ramp is steeper, the trolley will go faster',
   'A prediction says what <em>will</em> happen, not what did.',
   'A prediction is usually an "if &hellip; then &hellip;" sentence about a result not yet measured. The others describe apparatus or report what happened.'],

  ['g9s-inq-325', 'hypothesis_testing', 3,
   'The results do not support a pupil&rsquo;s hypothesis. What should the pupil do?',
   ['Report the results and say the prediction was wrong',
    'Change a few of the readings so the pattern is clearer',
    'Leave out the readings that spoil the pattern',
    'Write the prediction again after the experiment'],
   'Report the results and say the prediction was wrong',
   'Which choice keeps the evidence honest?',
   'A hypothesis that fails is a real result, and reporting it is good science. Altering or hiding readings destroys the evidence.'],

  ['g9s-inq-326', 'hypothesis_testing', 4,
   'A pupil uses a ray box and a plane mirror to test whether the angle of reflection equals the angle of incidence. What is changed each time?',
   ['The angle at which the ray strikes the mirror',
    'The angle at which the ray leaves the mirror',
    'The brightness of the lamp inside the ray box',
    'The thickness of the plane mirror on the bench'],
   'The angle at which the ray strikes the mirror',
   'One angle is set by the pupil; the other is the result.',
   'The incident ray is aimed at chosen angles, and the reflected angle is measured with a protractor to see whether it matches.'],

  ['g9s-inq-327', 'hypothesis_testing', 3,
   'Why does a pupil time the pendulum three times at each length?',
   ['To reduce the effect of random errors on the result',
    'To make the pendulum bob swing much more steadily',
    'To use up the whole of the practical lesson',
    'To fill in every one of the table columns'],
   'To reduce the effect of random errors on the result',
   'Think about what a mean of three readings does that one reading cannot.',
   'Repeat readings let a mean be taken, so a slightly early or late stopwatch press matters less. It also shows up any reading that does not fit.'],

  ['g9s-inq-328', 'hypothesis_testing', 4,
   'A pupil raises the ramp <b>and</b> adds a mass to the trolley for each run. Why is this poor design?',
   ['Two variables changed, so neither can be blamed',
    'The trolley will then be far too heavy to move',
    'A ramp cannot be raised more than once',
    'The stopwatch cannot time two things'],
   'Two variables changed, so neither can be blamed',
   'What would the pupil be able to conclude at the end?',
   'With height and mass both changing, a faster run could be caused by either. Change one variable at a time and the evidence means something.'],

  ['g9s-inq-329', 'hypothesis_testing', 1,
   'What is a <b>variable</b> in an investigation?',
   ['Anything that can change or be changed in the test',
    'A number that is written down in the results table',
    'A piece of apparatus used on the bench',
    'A conclusion drawn from the readings'],
   'Anything that can change or be changed in the test',
   'The word itself is a clue.',
   'A variable is any quantity that can vary &mdash; length, mass, current, time. Investigations sort them into independent, dependent and controlled.'],

  ['g9s-inq-330', 'hypothesis_testing', 3,
   'A pupil predicts that a longer wire lets less current flow. What must stay the same?',
   ['The number of cells in the circuit',
    'The length of the wire being tested',
    'The current read from the ammeter',
    'The reading shown on the voltmeter'],
   'The number of cells in the circuit',
   'Two of these are the change and the measurement.',
   'Wire length is changed and current is measured, so the supply must be kept the same. More cells would raise the current whatever the wire did.'],

  // ── recording_data ────────────────────────────────────────────────────
  ['g9s-inq-335', 'recording_data', 1,
   'What must the heading of each column in a results table show?',
   ['The quantity being measured and its unit',
    'The name of the pupil taking the readings',
    'The date on which the readings were taken',
    'The number of pupils working at the bench'],
   'The quantity being measured and its unit',
   'Look at how the papers print a heading such as "Current / A".',
   'A heading such as <b>Time / s</b> names the quantity and gives the unit once, so the unit need not be written beside every reading.'],

  ['g9s-inq-336', 'recording_data', 2,
   'Which quantity belongs in the <b>first</b> column of a results table?',
   ['The variable the pupil chose to change',
    'The variable the pupil measured each time',
    'The variable that was kept the same',
    'The mean worked out at the very end'],
   'The variable the pupil chose to change',
   'Tables are read from left to right, like the graph axes.',
   'The independent variable goes in the left-hand column and the measured values beside it, matching the x and y axes of the graph that follows.'],

  ['g9s-inq-337', 'recording_data', 2,
   'On a graph, which axis carries the variable the pupil changed?',
   ['The horizontal axis along the bottom',
    'The vertical axis up the left side',
    'Either axis, whichever suits better',
    'Neither axis, it goes in the title'],
   'The horizontal axis along the bottom',
   'Think of a speed&ndash;time graph: which quantity runs along the bottom?',
   'The independent variable goes on the horizontal axis. On a speed&ndash;time graph time runs along the bottom and speed up the side.'],

  ['g9s-inq-338', 'recording_data', 1,
   'Where should the unit of a measurement be written in a results table?',
   ['In the column heading, once, at the top',
    'Beside every single reading in that column',
    'In the title written above the whole table',
    'In the conclusion at the bottom of the page'],
   'In the column heading, once, at the top',
   'How do the real papers print "Height / cm"?',
   'The unit belongs in the heading, written once as <b>Height / cm</b>. Repeating it beside every reading is untidy and gains no marks.'],

  ['g9s-inq-339', 'recording_data', 3,
   'How should a pupil choose the scale for the axes of a graph?',
   ['So the plotted points fill most of the grid',
    'So all the points sit in one small corner',
    'So the numbers rise in awkward steps of 3',
    'So the axes both start at the same number'],
   'So the plotted points fill most of the grid',
   'Think about how easy the graph will be to read afterwards.',
   'A scale should use more than half of the grid and rise in easy steps such as 1, 2, 5 or 10. Points squashed into a corner cannot be read accurately.'],

  ['g9s-inq-340', 'recording_data', 3,
   'A pupil measures the current for several different voltages. Which chart should be drawn?',
   ['A line graph, because both quantities are measured',
    'A bar chart, because there are several readings',
    'A pie chart, because the parts make up a whole',
    'A tally chart, because the readings are counted'],
   'A line graph, because both quantities are measured',
   'Are the values counted in categories, or measured on a scale?',
   'Both current and voltage are measured on continuous scales, so a line graph is right. Bar charts are for separate categories.'],

  ['g9s-inq-341', 'recording_data', 2,
   'Which chart best compares the electricity produced by four different fuels?',
   ['A bar chart, one bar for each of the fuels',
    'A line graph joining up all four of the fuels',
    'A speed&ndash;time graph of the four fuels',
    'A ray diagram drawn for each of them'],
   'A bar chart, one bar for each of the fuels',
   'The fuels are separate named categories, not a scale.',
   'Coal, wind, solar and bagasse are categories with nothing in between, so a bar chart is right. Joining them with a line would suggest values between them.'],

  ['g9s-inq-342', 'recording_data', 2,
   'How many times should a pupil normally repeat each timing before finding a mean?',
   ['At least three times at every setting',
    'Once only, to save time in the lesson',
    'Twice, and then take the larger value',
    'Ten times for each of the settings'],
   'At least three times at every setting',
   'Enough to spot a reading that does not fit, without wasting the lesson.',
   'Three repeats is the usual school standard: it allows a mean and makes an odd reading obvious. One reading gives neither.'],

  ['g9s-inq-345', 'recording_data', 2,
   'A stopwatch reads 12.4 s, 12.63 s and 12.5 s. What is wrong with how they are recorded?',
   ['They are not all to the same number of decimals',
    'They are far too close together to be useful',
    'They should have been added, not listed',
    'They are missing the name of the pupil'],
   'They are not all to the same number of decimals',
   'Compare the digits after the point in each reading.',
   'Every reading from one instrument is recorded to the same precision, here one decimal place: 12.4 s, 12.6 s, 12.5 s.'],

  ['g9s-inq-346', 'recording_data', 3,
   'A ruler is marked in millimetres. Which is the better way to record a length?',
   ['12.0 cm, because the ruler reads to a millimetre',
    '12 cm, because the extra zero adds no meaning',
    '12.000 cm, because more digits are more exact',
    'About 12 cm, because rulers are never exact'],
   '12.0 cm, because the ruler reads to a millimetre',
   'How small is the smallest division on the ruler?',
   'A millimetre scale reads to 0.1 cm, so 12.0 cm shows the precision honestly. Extra zeros beyond what the instrument can read claim precision it does not have.'],

  ['g9s-inq-347', 'recording_data', 3,
   'When should the results table be drawn?',
   ['Before the readings, so each one is written in',
    'After the readings, from notes on rough paper',
    'After the graph has been plotted and drawn',
    'At home, once the whole report is finished'],
   'Before the readings, so each one is written in',
   'Where does a reading go the moment it is taken?',
   'A table drawn first gives every reading a place at the moment it is taken. Copying up later is how readings get lost or mixed up.'],

  ['g9s-inq-348', 'recording_data', 2,
   'How should each point be marked when a graph is plotted?',
   ['With a small neat cross or dot, using a pencil',
    'With a large blob of ink so it is easy to see',
    'With the reading written out beside the point',
    'With a small circle drawn round in dark pen'],
   'With a small neat cross or dot, using a pencil',
   'The mark has to show exactly where the reading falls.',
   'A small pencil cross shows the exact position and can be corrected. A large blob covers several values and loses accuracy.'],

  ['g9s-inq-349', 'recording_data', 3,
   'What is the right way to draw the line on a graph of measured points?',
   ['A single best-fit line through the trend of them',
    'A straight line joining each point to the next',
    'A line drawn through the first and last points',
    'A curve looped so it touches all of the points'],
   'A single best-fit line through the trend of them',
   'The readings each carry a small error, so what should the line follow?',
   'A best-fit line follows the overall trend with points scattered on both sides. Dot-to-dot lines follow the errors instead of the pattern.'],

  ['g9s-inq-350', 'recording_data', 4,
   'A pupil records ammeter readings in amperes. Which column heading is correct?',
   ['Current / A', 'Current in amps A', 'Current (amperes) / A', 'The current measured'],
   'Current / A',
   'The papers print the quantity, a solidus, then the unit symbol.',
   'The standard form is <b>Current / A</b>: quantity, slash, unit symbol. Writing the unit twice, or leaving it out, both lose the mark.'],

  ['g9s-inq-351', 'recording_data', 2,
   'What should a pupil include with the record of a circuit that was built?',
   ['A labelled circuit diagram using the standard symbols',
    'A photograph of the bench taken from directly above it',
    'A written list of everyone who was in the group',
    'A drawing of the laboratory with the benches in'],
   'A labelled circuit diagram using the standard symbols',
   'How does the exam paper itself show a circuit?',
   'A labelled diagram in standard symbols records exactly how the components were joined, which a picture or a list of names cannot.'],

  ['g9s-inq-352', 'recording_data', 4,
   'One timing in a set of repeats is clearly much larger than the others. What should the pupil write down?',
   ['All the readings, marking the odd one clearly',
    'Only the readings that fit the pattern well',
    'The mean of the readings, and nothing else',
    'A new reading invented to replace the odd one'],
   'All the readings, marking the odd one clearly',
   'Which choice keeps the record complete and honest?',
   'Every reading is recorded. The odd one is marked as anomalous and left out of the mean, so a reader can see the judgement that was made.'],

  // ── interpreting_results ──────────────────────────────────────────────
  ['g9s-inq-355', 'interpreting_results', 2,
   RAMP + '<br>What conclusion do the results in the table support?',
   ['The higher the ramp, the greater the speed',
    'The higher the ramp, the smaller the speed',
    'The height of the ramp changes nothing',
    'The speed rises and then falls again'],
   'The higher the ramp, the greater the speed',
   'Read down the two columns together.',
   'Speed rises from 1.4 m/s to 3.2 m/s as the height rises from 10 cm to 50 cm, so a steeper ramp gives a greater speed.'],

  ['g9s-inq-356', 'interpreting_results', 3,
   CELLS + '<br>Which reading in the table is <b>anomalous</b>?',
   ['1.5 A at four cells', '0.6 A at three cells', '1.0 A at five cells', '0.4 A at two cells'],
   '1.5 A at four cells',
   'The current rises by the same step each time except once.',
   'The current climbs 0.2 A per cell, so four cells should give about 0.8 A. The 1.5 A reading breaks the pattern and is anomalous.'],

  ['g9s-inq-357', 'interpreting_results', 2,
   'What should a pupil do about an anomalous reading?',
   ['Repeat that reading and leave it out of the mean',
    'Rub it out so the pattern in the table is clear',
    'Use it in the mean like all the other readings',
    'Replace it with the value the pattern suggests'],
   'Repeat that reading and leave it out of the mean',
   'It must be checked, but it must not vanish.',
   'An anomaly is repeated to see whether it happens again, and excluded from the mean if not. It still stays in the table, marked.'],

  ['g9s-inq-358', 'interpreting_results', 3,
   'A graph of the results is a straight line through the origin. What does that show?',
   ['One quantity is proportional to the other',
    'One quantity falls as the other one rises',
    'The two quantities are not connected',
    'The readings were all taken twice over'],
   'One quantity is proportional to the other',
   'Think about what doubling one quantity does to the other.',
   'A straight line through the origin means doubling one quantity doubles the other: they are directly proportional.'],

  ['g9s-inq-359', 'interpreting_results', 3,
   'What does the <b>gradient</b> of a speed&ndash;time graph tell you?',
   ['The acceleration of the moving object',
    'The distance the object has travelled',
    'The total time the object was moving',
    'The largest speed the object reached'],
   'The acceleration of the moving object',
   'Gradient is change in speed divided by change in time.',
   'Gradient is change in speed &divide; time taken, which is the definition of acceleration. A steeper line means a greater acceleration.'],

  ['g9s-inq-360', 'interpreting_results', 3,
   'What does the <b>area</b> under a speed&ndash;time graph represent?',
   ['The distance travelled by the object',
    'The acceleration reached by the object',
    'The average speed during the journey',
    'The largest speed shown on the graph'],
   'The distance travelled by the object',
   'Multiply a speed by a time and see what unit you get.',
   'Speed &times; time gives distance, and that product is exactly the area under the line. A flat section gives a rectangle.'],

  ['g9s-inq-363', 'interpreting_results', 3,
   'A conclusion should always be written so that it refers to what?',
   ['The pattern in the results and the prediction',
    'The apparatus that was used on the bench',
    'The pupils who were working in the group',
    'The lesson in which the work was carried out'],
   'The pattern in the results and the prediction',
   'A conclusion answers a question that was asked at the start.',
   'A conclusion states the pattern the readings show and says whether it supports the hypothesis. Listing apparatus belongs in the method.'],

  ['g9s-inq-364', 'interpreting_results', 3,
   'A pupil times a swinging pendulum with a hand-held stopwatch. What is the main source of error?',
   ['The pupil&rsquo;s reaction time when pressing it',
    'The mass of the bob hanging on the string',
    'The colour of the string used to hang it',
    'The height of the bench it is clamped to'],
   'The pupil&rsquo;s reaction time when pressing it',
   'The stopwatch itself measures to a hundredth of a second.',
   'The watch is far more precise than the hand using it: starting and stopping late or early can be a couple of tenths of a second each time.'],

  ['g9s-inq-365', 'interpreting_results', 3,
   'How can a pupil reduce the timing error when finding the time for one swing?',
   ['Time twenty swings and then divide by twenty',
    'Time one swing and round it to a whole second',
    'Use a stopwatch with a much larger display',
    'Ask another pupil to guess the time instead'],
   'Time twenty swings and then divide by twenty',
   'Spread one reaction-time mistake over many swings.',
   'Timing 20 swings and dividing spreads a single reaction-time error across twenty, cutting its effect on each swing to a twentieth.'],

  ['g9s-inq-366', 'interpreting_results', 2,
   'How is <b>parallax error</b> avoided when reading a scale?',
   ['Look squarely at the mark, straight along it',
    'Hold the ruler as far from the eye as possible',
    'Read the scale from one side of the bench',
    'Take the reading twice from two positions'],
   'Look squarely at the mark, straight along it',
   'The error comes from where the eye is, not from the scale.',
   'Parallax happens when the eye is to one side, so the mark appears against the wrong number. Looking straight on removes it.'],

  ['g9s-inq-367', 'interpreting_results', 2,
   'Why does taking a mean of repeat readings improve a result?',
   ['It reduces the effect of small random errors',
    'It makes every reading exactly the same value',
    'It removes the need to draw a results table',
    'It proves the hypothesis must have been right'],
   'It reduces the effect of small random errors',
   'Some readings come out high and some low.',
   'Random errors scatter readings above and below the true value, so averaging them cancels much of the scatter. It cannot fix a zero error.'],

  ['g9s-inq-368', 'interpreting_results', 4,
   CELLS + '<br>Ignoring the anomaly, what pattern do the results show?',
   ['The current rises steadily as cells are added',
    'The current falls steadily as cells are added',
    'The current stays the same however many cells',
    'The current rises and then drops back down'],
   'The current rises steadily as cells are added',
   'Read the readings for one, two and three cells.',
   'One, two and three cells give 0.2 A, 0.4 A and 0.6 A: a steady rise of 0.2 A per cell. The 1.5 A reading is anomalous and is set aside.'],

  ['g9s-inq-369', 'interpreting_results', 3,
   'What makes a set of results <b>reliable</b>?',
   ['Repeats at each setting agree closely with each other',
    'The readings were all taken very quickly one after another',
    'A large number of columns is in the table',
    'The graph paper used has very small squares'],
   'Repeats at each setting agree closely with each other',
   'Reliability is about what happens when the test is done again.',
   'Reliable results are repeatable: doing it again gives nearly the same reading. Speed of working and the size of the squares change nothing.'],

  ['g9s-inq-370', 'interpreting_results', 4,
   'A pupil measures these pairs with a ray box and mirror: 20&deg; and 20&deg;, 30&deg; and 31&deg;, 40&deg; and 40&deg;. What is the conclusion?',
   ['The angle of reflection equals the angle of incidence',
    'The angle of reflection is always the larger of the two',
    'The angle of reflection is always the smaller one',
    'The two angles are not connected to each other'],
   'The angle of reflection equals the angle of incidence',
   'The odd degree at 30&deg; is smaller than the measuring error.',
   'The pairs match within one degree, which is about the accuracy of a protractor, so the results support the law of reflection.'],

  ['g9s-inq-371', 'interpreting_results', 3,
   'A pupil writes: "The trolley was faster." Why is this a weak conclusion?',
   ['It gives no numbers and no reason for the change',
    'It uses far too many words for a conclusion',
    'It should have been written before the test began',
    'It is about the trolley and not the ramp'],
   'It gives no numbers and no reason for the change',
   'What would a reader still want to know?',
   'A conclusion should say faster than what, by how much, and why: "the trolley reached 3.2 m/s from 50 cm compared with 1.4 m/s from 10 cm, because a steeper slope&hellip;".'],

  ['g9s-inq-372', 'interpreting_results', 4,
   'A cooling curve for hot water falls steeply at first and then more gently. What does the changing gradient show?',
   ['The water cools more slowly as it gets cooler',
    'The water cools more quickly as it gets cooler',
    'The thermometer was misread near the start',
    'The water reached its boiling point twice over'],
   'The water cools more slowly as it gets cooler',
   'A steeper part of a graph means a faster change.',
   'A steep gradient is a fast temperature drop. As the water gets closer to room temperature the curve flattens, so it cools more slowly.'],

  // ── lab_safety ────────────────────────────────────────────────────────
  ['g9s-inq-375', 'lab_safety', 1,
   'What should a pupil do before switching on any circuit that has been built?',
   ['Have the teacher check the connections first',
    'Turn the power supply up to its highest setting',
    'Take the fuse out of the plug on the bench',
    'Hold the bare wire ends between the fingers'],
   'Have the teacher check the connections first',
   'Which choice happens before any current flows?',
   'A checked circuit cannot short out or overheat. The other three either raise the current dangerously or put a hand in the circuit.'],

  ['g9s-inq-376', 'lab_safety', 2,
   'Why must a circuit be disconnected from the supply before it is rewired?',
   ['So no current flows while wires are handled',
    'So the ammeter can be read more easily',
    'So the wires stay tidy on the bench top',
    'So the cells last for much longer in use'],
   'So no current flows while wires are handled',
   'Think about what is flowing while the supply is on.',
   'Switching off first means no current can pass through a hand or through a wrongly joined component while the circuit is being changed.'],

  ['g9s-inq-377', 'lab_safety', 2,
   'Why should hands be dry when working with any electrical apparatus?',
   ['Water lets a current pass through the skin',
    'Water makes the plug sockets go rusty',
    'Wet hands cannot grip the wires firmly',
    'Wet hands smudge the results table page'],
   'Water lets a current pass through the skin',
   'What does water do to how well the skin conducts?',
   'Dry skin has a high resistance; wet skin has a much lower one, so a voltage that would be harmless can drive a dangerous current.'],

  ['g9s-inq-378', 'lab_safety', 2,
   'A ray box has been switched on for some minutes. What is the hazard?',
   ['The lamp and its case become very hot',
    'The lamp gives out a loud humming sound',
    'The ray box slowly fills up with water',
    'The lamp gives off a strong smell of gas'],
   'The lamp and its case become very hot',
   'A filament lamp turns most of its energy into something other than light.',
   'Most of the energy becomes heat, so the metal case can burn a hand. Let it cool, or move it by the base, before packing it away.'],

  ['g9s-inq-379', 'lab_safety', 2,
   'Why should a pupil never look straight into a bright lamp or a laser?',
   ['The bright light can damage the eye',
    'The lamp becomes dimmer when watched',
    'The bulb may go out while being watched',
    'The light makes the room seem darker'],
   'The bright light can damage the eye',
   'Think about what is being pointed at the eye.',
   'A bright beam concentrated on the retina can damage it permanently, and a laser does so in a fraction of a second. Work with beams at bench level.'],

  ['g9s-inq-380', 'lab_safety', 2,
   'A pendulum is hung from a clamp on a stand. What keeps the stand from tipping over?',
   ['A heavy mass placed on the base of the stand',
    'A longer piece of string tied on to the bob',
    'A heavier bob hung on the end of it',
    'A wider swing given to the pendulum'],
   'A heavy mass placed on the base of the stand',
   'The bob swings out beyond the base.',
   'As the bob swings out, the stand can topple. A weight on the base, or clamping the stand to the bench, holds it steady.'],

  ['g9s-inq-381', 'lab_safety', 3,
   'A trolley runs down a ramp towards the edge of the bench. What is the sensible precaution?',
   ['Place a barrier to stop it at the bench end',
    'Catch the trolley with a hand as it arrives',
    'Raise the ramp higher so it moves faster',
    'Stand right at the end of the bench to watch'],
   'Place a barrier to stop it at the bench end',
   'The trolley must be stopped without anyone reaching in.',
   'A block or a padded barrier stops the trolley without a hand in its path and keeps it off the floor and off feet.'],

  ['g9s-inq-382', 'lab_safety', 2,
   'Why should slotted masses never be held above a foot or a bench edge?',
   ['They are heavy and can cause an injury if dropped',
    'They lose a little of their mass when dropped',
    'They become magnetised when they are dropped',
    'They are difficult to put back on their hanger'],
   'They are heavy and can cause an injury if dropped',
   'Think about what a falling kilogram would land on.',
   'A 1 kg mass falling on a foot causes a real injury. Masses are used over a soft mat, well back from the edge of the bench.'],

  ['g9s-inq-383', 'lab_safety', 3,
   'A connecting wire in a circuit becomes hot to the touch. What should be done first?',
   ['Switch the supply off at once and tell the teacher',
    'Wait a while to see whether it cools down again',
    'Turn the power supply up to a higher voltage',
    'Hold the wire with a cloth and keep working'],
   'Switch the supply off at once and tell the teacher',
   'A hot wire means the current is too large for it.',
   'Heat means an overload, usually a short circuit. Switching off stops it; turning the voltage up would make it worse.'],

  ['g9s-inq-384', 'lab_safety', 2,
   'Why are school electrical experiments done with low-voltage supplies and cells?',
   ['A low voltage cannot drive a dangerous current',
    'A low voltage makes the lamps glow more brightly',
    'A low voltage lets the ammeter be read faster',
    'A low voltage makes the cells last much longer'],
   'A low voltage cannot drive a dangerous current',
   'Compare a 1.5 V cell with the mains.',
   'Cells and low-voltage supplies cannot push enough current through the body to be dangerous. Mains voltage easily can, which is why it is never used on the bench.'],

  ['g9s-inq-385', 'lab_safety', 1,
   'Why should bags and stools be kept out of the gangways in a laboratory?',
   ['Someone hurrying to leave could trip on them',
    'They make the room look untidy to visitors',
    'They take up space that is needed for benches',
    'They may be taken home by the wrong pupil'],
   'Someone hurrying to leave could trip on them',
   'Think about what happens when a room has to be cleared quickly.',
   'A clear gangway matters most when everyone leaves at once. A trip in a lab means falling among glassware and trailing leads.'],

  ['g9s-inq-386', 'lab_safety', 3,
   'Why are trailing leads across a bench or a floor a hazard?',
   ['They can be caught, pulling apparatus over',
    'They make the current flow more slowly',
    'They make the voltmeter read incorrectly',
    'They use up more of the cell&rsquo;s energy'],
   'They can be caught, pulling apparatus over',
   'What happens if a sleeve catches one?',
   'A caught lead drags the supply, the meter or a hot lamp off the bench. Leads are kept short and run along the bench, not across the walkway.'],

  ['g9s-inq-387', 'lab_safety', 3,
   'Why is a pupil told to work with a partner during a practical?',
   ['One can watch while the other handles apparatus',
    'The work is finished in half of the time',
    'Only one set of results has to be written up',
    'Two pupils can share one pair of goggles'],
   'One can watch while the other handles apparatus',
   'The syllabus asks for investigations done <b>in cooperation with others</b>.',
   'A partner watches the meter, holds the stand and can call for help. Sharing goggles or copying one set of results is not cooperation.'],

  ['g9s-inq-388', 'lab_safety', 3,
   'When should eye protection be worn in a physics practical?',
   ['When a wire is heated or a mass may fall',
    'Only when a liquid is being poured out',
    'Only when the teacher is watching closely',
    'When the results table is being filled in'],
   'When a wire is heated or a mass may fall',
   'Ask what could reach the eye.',
   'Goggles are worn whenever something could fly, snap or spit &mdash; a heated wire, a stretched spring, a falling mass. They are not only for chemistry.'],

  ['g9s-inq-389', 'lab_safety', 1,
   'What is the first thing to do if apparatus is broken during a practical?',
   ['Tell the teacher and leave the pieces alone',
    'Pick up all the pieces with bare hands',
    'Hide the pieces under the bench for later',
    'Carry on with the experiment as before'],
   'Tell the teacher and leave the pieces alone',
   'Broken glass and hot metal are cleared by an adult.',
   'Reporting it means it is cleared safely and replaced. Picking up broken glass by hand is how a practical becomes a cut.'],

  ['g9s-inq-390', 'lab_safety', 3,
   'A lamp is to be connected to a supply marked 0&ndash;12 V. What should the supply be set to first?',
   ['The lowest setting, then raised if it is needed',
    'The highest setting, then lowered by a little',
    'Any setting, as a lamp cannot be damaged',
    'Half of the range, which is always safest'],
   'The lowest setting, then raised if it is needed',
   'Which direction can be undone if it turns out to be wrong?',
   'Starting low and raising slowly protects the lamp and the meters. Starting at 12 V can blow the lamp and swing the ammeter off its scale.'],

  ['g9s-inq-391', 'lab_safety', 4,
   'Why is a fuse or a circuit breaker fitted in a mains circuit?',
   ['It cuts the current off if it grows too large',
    'It makes the current flow round more smoothly',
    'It stores charge for when it is next needed',
    'It measures the current passing through it'],
   'It cuts the current off if it grows too large',
   'What has to happen before a cable overheats?',
   'A fuse wire melts, and a breaker trips, when the current exceeds a set value. That breaks the circuit before the cable can overheat and start a fire.'],

  ['g9s-inq-392', 'lab_safety', 2,
   'What should be done with the power supply at the end of a practical?',
   ['Switch it off and unplug it before packing up',
    'Leave it switched on for the next class to use',
    'Wind the leads tightly around the case',
    'Turn it up so it is ready for next time'],
   'Switch it off and unplug it before packing up',
   'Nothing should still be live while apparatus is being moved.',
   'Switching off and unplugging means nothing is live while leads are pulled out. Tightly wound leads also break inside the insulation.'],

  ['g9s-inq-393', 'lab_safety', 4,
   'Before a class starts an experiment, what is a <b>risk assessment</b> for?',
   ['To find what could go wrong and prevent it',
    'To decide which pupil will write the report',
    'To list the readings that will be taken',
    'To choose which graph will be drawn'],
   'To find what could go wrong and prevent it',
   'It is done before anything is switched on.',
   'A risk assessment names the hazards &mdash; hot lamp, falling mass, live supply &mdash; and states the precaution for each, before the practical begins.'],

  ['g9s-inq-394', 'lab_safety', 1,
   'Why must pupils never eat or drink in a laboratory?',
   ['Substances on the bench can get into food',
    'Crumbs may fall between the bench and wall',
    'Eating makes the practical take much longer',
    'Food makes the room smell for the next class'],
   'Substances on the bench can get into food',
   'What might already be on the bench or on a hand?',
   'Chemicals, dust from apparatus and residues transfer from bench to hand to food. Nothing is eaten in a lab, however clean it looks.'],

  // ── reporting_findings ────────────────────────────────────────────────
  ['g9s-inq-395', 'reporting_findings', 1,
   'Which part of a practical report says what the investigation was trying to find out?',
   ['The aim, written at the start of it',
    'The method, listing what was done',
    'The results, giving all the readings',
    'The conclusion, at the end of it all'],
   'The aim, written at the start of it',
   'It comes first, before any apparatus is named.',
   'The aim states the question in one sentence: "to find out how the height of a ramp affects the speed of a trolley".'],

  ['g9s-inq-396', 'reporting_findings', 2,
   'What is the test of a well-written <b>method</b>?',
   ['Another pupil could repeat it exactly as written',
    'It fills at least one whole side of the exercise book',
    'It names every pupil who was in the group',
    'It gives the results that were expected'],
   'Another pupil could repeat it exactly as written',
   'Think about who else has to be able to use it.',
   'A method is written so someone else can repeat the work and check the result. That is why measurements, apparatus and order all have to be there.'],

  ['g9s-inq-397', 'reporting_findings', 2,
   'In which order do the parts of a practical report normally come?',
   ['Aim, method, results, conclusion',
    'Method, aim, conclusion, results',
    'Results, conclusion, aim, method',
    'Conclusion, results, method, aim'],
   'Aim, method, results, conclusion',
   'The report follows the order the work was actually done in.',
   'The report follows the investigation: what was asked, what was done, what was measured, what it shows.'],

  ['g9s-inq-398', 'reporting_findings', 3,
   'Which sentence is written in the style expected of a method?',
   ['The ramp was raised to a height of 20 cm',
    'I raised my ramp up to about 20 cm high',
    'You should raise the ramp to some height',
    'We think the ramp was around 20 cm high'],
   'The ramp was raised to a height of 20 cm',
   'Reports are impersonal and past tense, and they carry the number.',
   'A method reports what was done, not who did it, and states the actual measurement. "About" and "we think" leave the reader unable to repeat it.'],

  ['g9s-inq-399', 'reporting_findings', 1,
   'What must be included with every numerical result in a report?',
   ['Its unit, written after the number',
    'The name of the pupil who took it',
    'The time of day it was taken at',
    'The make of the instrument used'],
   'Its unit, written after the number',
   'A number on its own does not say how much.',
   '"3" could be 3 m/s, 3 A or 3 s. Without the unit the reading means nothing and the mark is lost.'],

  ['g9s-inq-400', 'reporting_findings', 3,
   'How should the apparatus be shown in a physics report?',
   ['As a labelled diagram drawn with a ruler',
    'As a paragraph naming each item in turn',
    'As a photograph taken from the front',
    'As a list of the items with their prices'],
   'As a labelled diagram drawn with a ruler',
   'How does the exam paper itself show a set-up?',
   'A labelled line diagram shows how the parts were arranged in a way words cannot, and it is how every paper prints an experiment.'],

  ['g9s-inq-401', 'reporting_findings', 3,
   'A pupil found one anomalous reading. What should the report say about it?',
   ['That it was found, and how it was dealt with',
    'Nothing at all, because it was left out',
    'That the apparatus must have been faulty',
    'That the experiment did not work at all'],
   'That it was found, and how it was dealt with',
   'A reader should be able to see the judgement that was made.',
   'The report names the anomaly, says it was repeated and excluded from the mean, and gives the reason. Silence hides a decision that affected the result.'],

  ['g9s-inq-402', 'reporting_findings', 3,
   'What belongs in the <b>evaluation</b> at the end of a report?',
   ['The errors met and how to improve the method',
    'The list of every result that was measured',
    'The aim of the whole investigation again',
    'The names of everyone who was in the group'],
   'The errors met and how to improve the method',
   'It is the part that looks back at how well the work was done.',
   'An evaluation judges the quality of the evidence: what limited the accuracy, which readings were doubtful, and what would be done differently.'],

  ['g9s-inq-403', 'reporting_findings', 2,
   'Why should a graph in a report always carry a title and labelled axes?',
   ['So a reader knows what is plotted against what',
    'So the graph fills more of the page than before',
    'So the points can be plotted much more quickly',
    'So the line can be drawn without using a ruler'],
   'So a reader knows what is plotted against what',
   'Imagine the graph on its own, away from the report.',
   'A graph should make sense on its own. Labels with units, and a title, tell a reader what the two quantities are and how they were measured.'],

  ['g9s-inq-404', 'reporting_findings', 4,
   'A pupil presents results to the class. Which is the most useful way to show the pattern?',
   ['A graph projected so everyone can see it',
    'A long list of readings read out aloud',
    'A copy of the notes passed round slowly',
    'A description of the apparatus in words'],
   'A graph projected so everyone can see it',
   'What shows a trend in a single glance?',
   'A graph shows the trend at once; a spoken list of numbers cannot be followed, and the apparatus is not the finding.'],

  ['g9s-inq-405', 'reporting_findings', 3,
   'Why should a report state the number of repeats that were taken?',
   ['It lets a reader judge how reliable the mean is',
    'It shows how long the practical lesson lasted',
    'It fills out the method section of the report',
    'It proves that the prediction had been right'],
   'It lets a reader judge how reliable the mean is',
   'A mean of two readings and a mean of five are not equally trustworthy.',
   'Knowing there were three repeats, and how closely they agreed, tells a reader how much confidence the mean deserves.'],

  ['g9s-inq-406', 'reporting_findings', 3,
   'Which conclusion is written well?',
   ['Speed rose from 1.4 to 3.2 m/s as height rose',
    'The trolley went a lot faster down the ramp',
    'The experiment worked and the results are good',
    'The prediction that was made turned out right'],
   'Speed rose from 1.4 to 3.2 m/s as height rose',
   'A conclusion carries the numbers, not just a direction.',
   'A good conclusion names the quantities, gives the figures with units and states the pattern. The others could describe almost any experiment.'],

  ['g9s-inq-407', 'reporting_findings', 4,
   'A pupil uses a spreadsheet to present the results. What is the main advantage?',
   ['The graph is redrawn whenever a value changes',
    'The readings do not have to be written down',
    'The spreadsheet works out the conclusion too',
    'The results are certain to be free of error'],
   'The graph is redrawn whenever a value changes',
   'Think about what happens when one reading is corrected.',
   'A spreadsheet recalculates means and redraws the chart when a figure is corrected. It cannot decide what the results mean, and it cannot make a wrong reading right.'],

  ['g9s-inq-408', 'reporting_findings', 3,
   'Why should the source of any information copied into a report be given?',
   ['So a reader can check where it came from',
    'So the report is a little longer than before',
    'So the teacher knows a book was opened',
    'So the words do not have to be understood'],
   'So a reader can check where it came from',
   'It is the same reason a result needs a method.',
   'Naming the book or site lets a reader judge how trustworthy the claim is and find it again. Using someone else&rsquo;s words as your own is not honest reporting.'],

  ['g9s-inq-409', 'reporting_findings', 1,
   'What should the title of a practical report tell a reader?',
   ['What was investigated in the practical',
    'How long the whole practical lasted',
    'Which class carried out the practical',
    'How many pupils were in the group'],
   'What was investigated in the practical',
   'A title names the investigation, not the lesson.',
   '"How the height of a ramp affects the speed of a trolley" names both variables. "Physics practical 3" names nothing at all.'],

  ['g9s-inq-410', 'reporting_findings', 4,
   'A pupil is asked to report results to the class in two minutes. What should be left out?',
   ['Every individual reading from the table',
    'The pattern that the results showed',
    'The main conclusion that was drawn',
    'The one anomaly that was found'],
   'Every individual reading from the table',
   'Two minutes is enough for the finding, not for the raw data.',
   'A short talk gives the aim, the pattern, the conclusion and any anomaly. Reading out forty numbers uses the time and communicates nothing.'],

  ['g9s-inq-411', 'reporting_findings', 3,
   'Why should a report avoid the word "it" when several things have been mentioned?',
   ['A reader cannot tell which thing is meant',
    'The word is too short for a science report',
    'It makes the report look far too casual',
    'The word cannot be used in the past tense'],
   'A reader cannot tell which thing is meant',
   'Think of "the trolley, the ramp and the timer &mdash; it was moved".',
   'Reports name things: "the trolley was released", not "it was released". Ambiguity in a method makes it impossible to repeat exactly.'],

  ['g9s-inq-412', 'reporting_findings', 4,
   'Two pupils get different results from the same experiment. What should each report do?',
   ['State the results honestly and compare methods',
    'Agree on one set of readings to write up',
    'Choose whichever result looks the neater',
    'Leave the difference out of both reports'],
   'State the results honestly and compare methods',
   'The difference itself is evidence about the method.',
   'A disagreement points at something in the method &mdash; a different timing technique, a zero error. Reporting both and comparing is what finds it.'],

  ['g9s-inq-413', 'reporting_findings', 2,
   'Which of these belongs in the <b>results</b> section?',
   ['The table of readings and the mean values',
    'The prediction made before the experiment',
    'The list of apparatus set up on the bench',
    'The reason the pattern came out that way'],
   'The table of readings and the mean values',
   'Results are what the instruments said, and nothing else.',
   'The results section carries the table, the means and the graph. Predictions belong at the start and explanations belong in the conclusion.'],

  ['g9s-inq-414', 'reporting_findings', 3,
   'Why is a practical report normally written soon after the lesson?',
   ['The details are still remembered accurately',
    'The teacher will not accept it any later',
    'The apparatus is still out on the bench',
    'The graph paper is easier to get hold of'],
   'The details are still remembered accurately',
   'Which part of the report suffers most from a week&rsquo;s delay?',
   'Small details of the method &mdash; the order, the settings, an odd reading &mdash; fade quickly, and they are exactly what makes a report repeatable.'],
];

MCQ.forEach(([id, subsection, difficulty, question, options, answer, hint, explanation]) => {
  STATIC_QUESTIONS.push(makeMCQ({ id, chapterId: CH, subsection, difficulty,
    question, options, answer, hint, explanation }));
});

const SHORT = [
  ['g9s-inq-331', 'hypothesis_testing', 1,
   'Name the variable that is deliberately changed in an investigation.',
   'Independent', ['independent variable', 'the independent variable'],
   'It is the one the pupil chooses.',
   'The <b>independent</b> variable is the one changed on purpose &mdash; the ramp height, the pendulum length, the number of cells.'],
  ['g9s-inq-332', 'hypothesis_testing', 2,
   'Name the variable that is measured in an investigation.',
   'Dependent', ['dependent variable', 'the dependent variable'],
   'Its value depends on the one that was changed.',
   'The <b>dependent</b> variable is measured each time &mdash; the speed, the swing time, the current on the ammeter.'],
  ['g9s-inq-333', 'hypothesis_testing', 2,
   'Give the name for a variable that is kept the same throughout a fair test.',
   'Controlled', ['controlled variable', 'control variable', 'constant'],
   'Keeping it the same is what makes the test fair.',
   'A <b>controlled</b> variable is held constant so that only one thing can explain the change in the measurement.'],
  ['g9s-inq-334', 'hypothesis_testing', 3,
   'What name is given to a testable statement made before an investigation?',
   'Hypothesis', ['a hypothesis', 'hypotheses'],
   'One word, and it comes before the readings.',
   'A <b>hypothesis</b> is a prediction the experiment can support or contradict, written before any measurement is taken.'],

  ['g9s-inq-353', 'recording_data', 1,
   'Apart from the quantity, what else must a column heading in a results table give?',
   'Unit', ['the unit', 'units', 'its unit'],
   'Think of "Current / A" and what the letter A is.',
   'A heading gives the quantity and its <b>unit</b>, written once, as in <b>Time / s</b> or <b>Height / cm</b>.'],
  ['g9s-inq-354', 'recording_data', 2,
   'Name the type of graph drawn when both quantities are measured on continuous scales.',
   'Line graph', ['a line graph', 'line'],
   'Not the kind with separate bars.',
   'A <b>line graph</b> is used when both quantities vary continuously, such as current against voltage. Bar charts are for separate categories.'],

  ['g9s-inq-373', 'interpreting_results', 2,
   'Give the word for a result that does not fit the pattern of the others.',
   'Anomalous', ['an anomaly', 'anomaly', 'anomalous result', 'outlier'],
   'It is repeated and then left out of the mean.',
   'An <b>anomalous</b> result breaks the trend. It is recorded, repeated if possible, and excluded from the mean.'],
  ['g9s-inq-374', 'interpreting_results', 3,
   'State what the area under a speed&ndash;time graph represents.',
   'Distance', ['distance travelled', 'the distance travelled', 'distance moved'],
   'Multiply a speed by a time and look at the unit.',
   'Speed &times; time gives the <b>distance</b> travelled, and that product is the area beneath the line.'],
];

SHORT.forEach(([id, subsection, difficulty, question, answer, alsoAccept, hint, explanation]) => {
  STATIC_QUESTIONS.push(makeText({ id, chapterId: CH, subsection, difficulty,
    question, answer, alsoAccept, hint, explanation }));
});
})();
