'use strict';
// Grade 2 English — Chapter: Speaking
// IDs: g2eng-spk-001 … g2eng-spk-075

(function () {

STATIC_QUESTIONS.push(

  // ── retelling (25) ────────────────────────────────────────────────────────

  makeMCQ({ id:'g2eng-spk-001', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'When retelling a story, which word helps you say what happened at the START?',
    options:['First','Then','Last','Next'],
    answer:'First',
    hint:'Retelling uses order words. What word goes at the very beginning?',
    explanation:'We use <b>First</b> to say what happened at the start of a story. The order words are: First → Next → Then → Last.' }),

  makeMCQ({ id:'g2eng-spk-002', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"First, the girl found a kitten. Next, she gave it some milk. Then, she made it a bed. Last, the kitten fell asleep." What happened AFTER she gave it milk?',
    options:['She made it a bed','She found the kitten','The kitten fell asleep','She called her mum'],
    answer:'She made it a bed',
    hint:'The order is: found → gave milk → ??? → fell asleep. What comes after giving milk?',
    explanation:'After giving the kitten milk, <b>she made it a bed</b>. The order words First, Next, Then and Last help you follow the story.' }),

  makeMCQ({ id:'g2eng-spk-003', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'Which sentence is the BEST way to start retelling a story about a dog?',
    options:['First, a dog ran into the park.','Dog park running.','And then the dog.','Last, the dog sat.'],
    answer:'First, a dog ran into the park.',
    hint:'A good retelling starts with a full sentence that tells WHO and WHAT happened first.',
    explanation:'"<b>First, a dog ran into the park.</b>" is a complete sentence. It uses the order word "First" and tells us who (a dog) and what happened (ran into the park).' }),

  makeMCQ({ id:'g2eng-spk-004', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'A story says: "The children played in the garden. They heard the rain start. They ran inside." What happened LAST?',
    options:['They ran inside.','They played in the garden.','They heard the rain.','They got wet.'],
    answer:'They ran inside.',
    hint:'The events happen in order in the story. Which event is at the end?',
    explanation:'The children <b>ran inside</b> last — after they heard the rain. We always retell events in the order they happened.' }),

  makeMCQ({ id:'g2eng-spk-005', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'Which word goes in the blank? "First he ate breakfast. ___ he put on his shoes."',
    options:['Next','Last','Because','But'],
    answer:'Next',
    hint:'We are telling what happened after breakfast. Which order word fits here?',
    explanation:'"<b>Next</b>" tells us what happened after the first thing. First… Next… Then… Last — these are the order words we use when retelling.' }),

  makeMCQ({ id:'g2eng-spk-006', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'When retelling a story, what THREE things should you always include?',
    options:['Who, what happened, how it ended','The date, the weather, the colour','The teacher\'s name, the page number, the title','The longest sentence, the shortest word, the middle'],
    answer:'Who, what happened, how it ended',
    hint:'Think about the most important parts of any story.',
    explanation:'A good retelling always includes <b>who</b> was in the story, <b>what happened</b>, and <b>how it ended</b>. These three things give your listener a complete picture.' }),

  makeMCQ({ id:'g2eng-spk-007', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"The baby lost his toy. He started to cry. His sister found it under the bed." Who found the toy?',
    options:['His sister','The baby','His mother','His brother'],
    answer:'His sister',
    hint:'Read the last sentence — it tells you who found the toy.',
    explanation:'<b>His sister</b> found the toy — she found it under the bed. The baby was lucky to have such a helpful sister!' }),

  makeMCQ({ id:'g2eng-spk-008', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'Which order word means the FINAL thing that happened?',
    options:['Last','First','Next','Then'],
    answer:'Last',
    hint:'Think about the order: First → Next → Then → ___.',
    explanation:'<b>Last</b> tells us the final event in the story. The order is: First (1st) → Next (2nd) → Then (3rd) → Last (final).' }),

  makeMCQ({ id:'g2eng-spk-009', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"Tom dropped his book. Next, he picked it up. Last, he put it in his bag." What did Tom do first?',
    options:['dropped his book','picked it up','put it in his bag','went to school'],
    answer:'dropped his book',
    hint:'The story starts with what Tom did first — before "Next" and "Last".',
    explanation:'Tom <b>dropped his book</b> first. Then he picked it up, and last he put it in his bag. Stories happen in a sequence!' }),

  makeMCQ({ id:'g2eng-spk-010', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'Which sentence retells the MIDDLE part of this story: "The rabbit was hungry. It ate a carrot. Then it hopped away."',
    options:['It ate a carrot.','The rabbit was hungry.','Then it hopped away.','The rabbit slept.'],
    answer:'It ate a carrot.',
    hint:'The middle event comes between the beginning (hungry rabbit) and the end (hopped away).',
    explanation:'"<b>It ate a carrot.</b>" is the middle event — it comes after the rabbit was hungry and before it hopped away.' }),

  makeMCQ({ id:'g2eng-spk-011', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'In a retelling, why do we use the words First, Next, Then and Last?',
    options:['To show the order of events','To describe the characters','To name the places','To count the words'],
    answer:'To show the order of events',
    hint:'These words help our listener understand WHEN each thing happened.',
    explanation:'We use First, Next, Then and Last <b>to show the order of events</b> — they help our listener follow the story in the right sequence.' }),

  makeMCQ({ id:'g2eng-spk-012', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"Sara planted a seed. It grew into a tall flower. She gave the flower to her mum." What did Sara plant?',
    options:['a seed','a flower','a tree','a vegetable'],
    answer:'a seed',
    hint:'The first sentence tells you what Sara planted.',
    explanation:'Sara planted <b>a seed</b> — and it grew into a beautiful tall flower!' }),

  makeMCQ({ id:'g2eng-spk-013', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'Which tells you what a story is MOSTLY about?',
    options:['The main character and the main event','The colour of the sky','The number of pages','The name of the author'],
    answer:'The main character and the main event',
    hint:'When you retell a story, you focus on the most important person and what happened to them.',
    explanation:'A retelling focuses on <b>the main character and the main event</b>. These are the most important parts that your listener needs to know.' }),

  makeMCQ({ id:'g2eng-spk-014', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"The frog jumped into the pond. It swam to a lily pad. It sat in the sun and croaked happily." Where did the frog jump?',
    options:['into the pond','onto a log','up a tree','under a leaf'],
    answer:'into the pond',
    hint:'The very first sentence tells you where the frog jumped.',
    explanation:'The frog jumped <b>into the pond</b>. That was the first event in this little story.' }),

  makeMCQ({ id:'g2eng-spk-015', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'A good retelling uses YOUR OWN words. Which sentence is the best example?',
    options:['The brave boy helped his friend who was hurt.','Brave the boy hurt friend helped.','Boy. Friend. Help.','He was brave and then friend hurt.'],
    answer:'The brave boy helped his friend who was hurt.',
    hint:'A good retelling is a complete sentence that makes sense.',
    explanation:'"<b>The brave boy helped his friend who was hurt.</b>" is a complete, clear sentence — it tells us who, what happened, and gives detail. Great retelling!' }),

  makeMCQ({ id:'g2eng-spk-016', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"Lucy could not find her pencil. She looked in her bag. She found it on the floor." What is this story mostly about?',
    options:['Lucy looking for her pencil','Lucy going to school','Lucy drawing a picture','Lucy losing her bag'],
    answer:'Lucy looking for her pencil',
    hint:'What is the main event that keeps happening through the whole story?',
    explanation:'The story is mostly about <b>Lucy looking for her pencil</b>. She looked in her bag and then found it on the floor!' }),

  makeMCQ({ id:'g2eng-spk-017', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'What does it mean to "retell" a story?',
    options:['To say what happened in the story using your own words','To read the story out loud exactly','To draw a picture of the story','To write the story in your book'],
    answer:'To say what happened in the story using your own words',
    hint:'Retelling is about sharing the story — but you do not read it word for word.',
    explanation:'To <b>retell</b> means to say what happened in the story <b>using your own words</b>. You share the key events in order without reading it word for word.' }),

  makeMCQ({ id:'g2eng-spk-018', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"The monkey climbed the tree. It found some bananas. It ate them all and felt very full." How did the monkey feel at the END?',
    options:['very full','very hungry','very tired','very scared'],
    answer:'very full',
    hint:'The last sentence tells you how the monkey felt after eating.',
    explanation:'The monkey felt <b>very full</b> at the end — after eating all the bananas!' }),

  makeMCQ({ id:'g2eng-spk-019', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'Which sentence would be the BEST ending to a retelling?',
    options:['Last, the girl smiled and went home happily.','And then the girl.','Last the home girl smile.','She home.'],
    answer:'Last, the girl smiled and went home happily.',
    hint:'The ending should be a full sentence that tells us the final event and how the character felt.',
    explanation:'"<b>Last, the girl smiled and went home happily.</b>" is a great ending — it uses "Last" and it is a complete sentence that tells us the final event.' }),

  makeMCQ({ id:'g2eng-spk-020', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"First it was dark. Then the sun came up. Next the birds started to sing. Last it was a bright, beautiful morning." What happened THIRD?',
    options:['The birds started to sing.','It was dark.','The sun came up.','It was a bright morning.'],
    answer:'The birds started to sing.',
    hint:'First=1st, Then=2nd, Next=3rd, Last=4th. What is the third event?',
    explanation:'The <b>third</b> event (Next) was: the birds started to sing. First=dark, Then=sun came up, Next=birds singing, Last=bright morning.' }),

  makeMCQ({ id:'g2eng-spk-021', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'Which TWO words could both go in: "___, she opened the door and walked in."',
    options:['First and Then','Big and small','Red and blue','Jump and run'],
    answer:'First and Then',
    hint:'We are talking about the order of events. Which words show sequence?',
    explanation:'Both <b>First</b> and <b>Then</b> are sequence (order) words that could start a retelling sentence. Both make sense: "First, she opened the door…" or "Then, she opened the door…"' }),

  makeMCQ({ id:'g2eng-spk-022', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"The old lion was very thirsty. He walked slowly to the river. He drank a long drink of cool water." What did the lion drink?',
    options:['cool water','warm soup','fresh juice','salty water'],
    answer:'cool water',
    hint:'The last sentence tells you what the lion drank.',
    explanation:'The lion drank <b>cool water</b> from the river. He was very thirsty and the cool water made him feel much better!' }),

  makeMCQ({ id:'g2eng-spk-023', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'Which sentence tells us WHO is in the story?',
    options:['A little girl named Asha lived near the sea.','It was very hot that day.','The sand was yellow and warm.','The waves were big.'],
    answer:'A little girl named Asha lived near the sea.',
    hint:'The character is the person (or animal) in the story. Which sentence names a character?',
    explanation:'"<b>A little girl named Asha lived near the sea.</b>" tells us WHO — Asha, a little girl. The other sentences describe the setting.' }),

  makeMCQ({ id:'g2eng-spk-024', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'When retelling, what does "the ending" tell your listener?',
    options:['How the story finished','What the character looks like','Where the story happened','When the story started'],
    answer:'How the story finished',
    hint:'The ending is the last part — it tells your listener how everything worked out.',
    explanation:'The ending tells your listener <b>how the story finished</b> — did the problem get solved? Was the character happy or sad at the end?' }),

  makeMCQ({ id:'g2eng-spk-025', chapterId:'g2eng-speaking', difficulty:1, subsection:'retelling',
    question:'"The puppy was lost. A boy found it. The boy took it home. Last, the puppy had a new family." What is the BEST title for this story?',
    options:['The Lost Puppy Finds a Home','A Day at the Park','The Hungry Cat','The Big Red Bus'],
    answer:'The Lost Puppy Finds a Home',
    hint:'The title should match what the story is mostly about.',
    explanation:'"<b>The Lost Puppy Finds a Home</b>" is the best title — it matches the whole story: a lost puppy who eventually found a new family.' }),

  // ── describing_pictures (25) ──────────────────────────────────────────────

  makeMCQ({ id:'g2eng-spk-026', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which sentence gives the BEST description of a picture showing a red apple on a table?',
    options:['There is a shiny red apple sitting on the table.','Apple.','A thing is there.','Red is on the table.'],
    answer:'There is a shiny red apple sitting on the table.',
    hint:'A good description uses adjectives (describing words) and forms a complete sentence.',
    explanation:'"<b>There is a shiny red apple sitting on the table.</b>" — it uses adjectives (shiny, red), names the object (apple) and its location (table). A complete and vivid description!' }),

  makeMCQ({ id:'g2eng-spk-027', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows two children playing in the rain. Which sentence describes it best?',
    options:['Two happy children are splashing in puddles in the rain.','Rain.','Children outside.','It is wet.'],
    answer:'Two happy children are splashing in puddles in the rain.',
    hint:'Use numbers, adjectives and action words (verbs) to describe what you see.',
    explanation:'"<b>Two happy children are splashing in puddles in the rain.</b>" — it uses a number (two), an adjective (happy), a verb (splashing) and a detail (puddles, rain). Excellent description!' }),

  makeMCQ({ id:'g2eng-spk-028', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'When describing a picture, which question should you ask FIRST?',
    options:['What can I see?','What do I smell?','What is the date?','How old is the picture?'],
    answer:'What can I see?',
    hint:'Describing a picture starts with looking carefully at everything in it.',
    explanation:'We always start by asking "<b>What can I see?</b>" — we name everything we observe: the people, animals, objects, colours and what is happening.' }),

  makeMCQ({ id:'g2eng-spk-029', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which describing word (adjective) best fills the gap: "There is a ___ butterfly on the flower."',
    options:['beautiful colourful','runs quickly','the big','and happy'],
    answer:'beautiful colourful',
    hint:'We need a describing word (adjective) — a word that tells us what the butterfly looks like.',
    explanation:'"<b>Beautiful colourful</b>" are adjectives that describe the butterfly. They tell us what it looks like. "Runs quickly" is an action, not a description.' }),

  makeMCQ({ id:'g2eng-spk-030', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows a boy kicking a football. Which verb (action word) describes what the boy is doing?',
    options:['kicking','eating','sleeping','reading'],
    answer:'kicking',
    hint:'Look at the action in the picture — what is the boy doing with his foot?',
    explanation:'The boy is <b>kicking</b> the football. In a description, we use verbs to say what the people or animals in the picture are doing.' }),

  makeMCQ({ id:'g2eng-spk-031', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which sentence describes WHERE something is in a picture?',
    options:['The cat is sitting under the chair.','The cat is brown.','The cat is small.','The cat meows.'],
    answer:'The cat is sitting under the chair.',
    hint:'A position word (under, on, next to, behind) tells us where something is.',
    explanation:'"<b>The cat is sitting under the chair.</b>" uses the position word "under" to tell us WHERE the cat is. Good descriptions include position words!' }),

  makeMCQ({ id:'g2eng-spk-032', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows the sea, a beach and a bright sun. Which word describes the weather in the picture?',
    options:['sunny','rainy','cloudy','windy'],
    answer:'sunny',
    hint:'Look at the bright sun in the sky. What does that tell you about the weather?',
    explanation:'The bright sun means the weather is <b>sunny</b>. Describing the weather in a picture tells your listener about the setting.' }),

  makeMCQ({ id:'g2eng-spk-033', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which sentence best describes the COLOUR and SIZE of an object?',
    options:['I can see a tiny yellow star.','I can see a star.','A star is there.','It is shining.'],
    answer:'I can see a tiny yellow star.',
    hint:'Include the colour AND size — both are important adjectives.',
    explanation:'"<b>I can see a tiny yellow star.</b>" gives both the size (tiny) and the colour (yellow). Including multiple adjectives makes descriptions richer!' }),

  makeMCQ({ id:'g2eng-spk-034', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows a market with many fruits. Which sentence describes what is happening?',
    options:['A busy market is selling lots of colourful fruits.','The market.','Fruits are fruit.','Many many many.'],
    answer:'A busy market is selling lots of colourful fruits.',
    hint:'Use an adjective, name the place, and say what is happening.',
    explanation:'"<b>A busy market is selling lots of colourful fruits.</b>" — adjective (busy), place (market), action (selling), and detail (colourful fruits). A complete picture description!' }),

  makeMCQ({ id:'g2eng-spk-035', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which position word tells us that the ball is between two trees?',
    options:['between','above','below','beside'],
    answer:'between',
    hint:'"Between" means in the middle of two things.',
    explanation:'"<b>Between</b>" is the correct word — "The ball is between two trees" means the ball is in the middle, with one tree on each side.' }),

  makeMCQ({ id:'g2eng-spk-036', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows a girl with long curly hair. Which word describes her hair?',
    options:['curly','purple','fast','loud'],
    answer:'curly',
    hint:'What does the hair LOOK like? Is it straight or curved?',
    explanation:'The girl has <b>curly</b> hair — curly means it has lots of curves and ringlets. "Purple, fast and loud" do not describe hair in this picture.' }),

  makeMCQ({ id:'g2eng-spk-037', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which word tells us HOW MANY objects there are in a picture?',
    options:['three','blue','running','loud'],
    answer:'three',
    hint:'Numbers tell us quantity — how many of something there is.',
    explanation:'"<b>Three</b>" is a number word that tells us HOW MANY. When describing a picture, include how many of each thing you can see.' }),

  makeMCQ({ id:'g2eng-spk-038', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows a big elephant next to a small rabbit. Which sentence compares them correctly?',
    options:['The elephant is much bigger than the rabbit.','The rabbit is bigger than the elephant.','They are the same size.','The elephant is smaller than the rabbit.'],
    answer:'The elephant is much bigger than the rabbit.',
    hint:'Elephants are very large animals and rabbits are very small. Which sentence is true?',
    explanation:'"<b>The elephant is much bigger than the rabbit.</b>" — this is correct! Comparing sizes in a description makes it more interesting and accurate.' }),

  makeMCQ({ id:'g2eng-spk-039', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which word tells us about a FEELING we might imagine from a picture?',
    options:['happy','green','running','table'],
    answer:'happy',
    hint:'Feelings are words like happy, sad, excited, scared. Which word from the list is a feeling?',
    explanation:'"<b>Happy</b>" is a feeling word. When describing a picture, we can say how the people in it seem to feel: "The children look very happy."' }),

  makeMCQ({ id:'g2eng-spk-040', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows clouds, rain and a dark sky. Which word best describes the weather?',
    options:['stormy','sunny','warm','bright'],
    answer:'stormy',
    hint:'Dark clouds and heavy rain usually mean what kind of weather?',
    explanation:'Dark clouds, rain and a dark sky describe <b>stormy</b> weather. Stormy means there is heavy rain and perhaps thunder — not a nice day to go outside!' }),

  makeMCQ({ id:'g2eng-spk-041', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which sentence uses the word "above" correctly to describe a picture?',
    options:['The kite is flying above the trees.','The kite is below the trees.','The kite is inside the trees.','The kite runs above.'],
    answer:'The kite is flying above the trees.',
    hint:'"Above" means higher than. A kite in the sky would be above (higher than) the trees.',
    explanation:'"<b>The kite is flying above the trees.</b>" — "above" means higher up than something. The kite is up in the sky, above the tree tops.' }),

  makeMCQ({ id:'g2eng-spk-042', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which sentence describes the BACKGROUND of a picture showing children in a park?',
    options:['In the background, there are tall green trees.','The children are laughing.','A girl has a red dress.','A boy is running.'],
    answer:'In the background, there are tall green trees.',
    hint:'The background is what is behind the main thing in the picture.',
    explanation:'"<b>In the background, there are tall green trees.</b>" describes what is behind the children. The background gives important information about the setting.' }),

  makeMCQ({ id:'g2eng-spk-043', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows fish swimming in the sea. Which verb tells us what the fish are doing?',
    options:['swimming','flying','running','climbing'],
    answer:'swimming',
    hint:'Fish live in water — what do they do to move around?',
    explanation:'The fish are <b>swimming</b> in the sea. Fish use their fins and tails to swim. In descriptions, verbs (action words) tell us what is happening.' }),

  makeMCQ({ id:'g2eng-spk-044', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which adjective describes a fruit that looks juicy and ripe?',
    options:['delicious','cold','loud','fast'],
    answer:'delicious',
    hint:'Think about a word that describes how food looks when it is ready to eat and tastes great.',
    explanation:'"<b>Delicious</b>" describes something that looks or tastes wonderful. We can say "The delicious ripe mango looks ready to eat!"' }),

  makeMCQ({ id:'g2eng-spk-045', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which sentence correctly uses a colour, a size and an action to describe a picture?',
    options:['A tiny orange cat is sleeping.','Cat.','It is orange.','Sleeping the cat.'],
    answer:'A tiny orange cat is sleeping.',
    hint:'Look for the sentence that has a size word, a colour word AND an action word.',
    explanation:'"<b>A tiny orange cat is sleeping.</b>" — tiny (size), orange (colour), sleeping (action). It is a complete sentence with three types of detail!' }),

  makeMCQ({ id:'g2eng-spk-046', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows a woman carrying a heavy basket of vegetables. Which word tells us about the basket?',
    options:['heavy','quickly','purple','singing'],
    answer:'heavy',
    hint:'We need a word that describes the basket — what it is like.',
    explanation:'"<b>Heavy</b>" is the adjective that describes the basket. A basket full of vegetables would be heavy to carry.' }),

  makeMCQ({ id:'g2eng-spk-047', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which sentence best says what a character in a picture might be thinking or feeling?',
    options:['The girl looks excited to open her present.','The present is red.','The box is big.','It is a present.'],
    answer:'The girl looks excited to open her present.',
    hint:'We can imagine a character\'s feelings when describing a picture.',
    explanation:'"<b>The girl looks excited to open her present.</b>" — this adds a feeling (excited) to our description, making it more interesting and alive!' }),

  makeMCQ({ id:'g2eng-spk-048', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'A picture shows a rainbow over mountains after rain. Which adjective describes the rainbow?',
    options:['colourful','quiet','tiny','flat'],
    answer:'colourful',
    hint:'Think about what a rainbow looks like — it has seven colours!',
    explanation:'A rainbow is <b>colourful</b> — it has seven beautiful colours (red, orange, yellow, green, blue, indigo, violet). "Colourful" is the perfect adjective!' }),

  makeMCQ({ id:'g2eng-spk-049', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which position word best describes a bird sitting on a branch?',
    options:['on','under','beside','behind'],
    answer:'on',
    hint:'If the bird is resting on top of the branch, which position word fits?',
    explanation:'"<b>On</b>" is correct — "The bird is sitting <b>on</b> the branch." It is resting on top of the branch.' }),

  makeMCQ({ id:'g2eng-spk-050', chapterId:'g2eng-speaking', difficulty:1, subsection:'describing_pictures',
    question:'Which sentence has the MOST detail about a picture of a market?',
    options:['A noisy, colourful market is full of people buying fresh fruit and vegetables.','It is a market.','There are things to buy.','A market with stuff.'],
    answer:'A noisy, colourful market is full of people buying fresh fruit and vegetables.',
    hint:'The best description includes the most vivid and accurate details.',
    explanation:'"<b>A noisy, colourful market is full of people buying fresh fruit and vegetables.</b>" — it uses two adjectives, names the people and tells us exactly what is happening. Excellent description!' }),

  // ── conversation (25) ─────────────────────────────────────────────────────

  makeMCQ({ id:'g2eng-spk-051', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'In a conversation, when your friend is talking, what should you do?',
    options:['Listen carefully','Talk at the same time','Walk away','Look at the ceiling'],
    answer:'Listen carefully',
    hint:'Good conversations need TWO things: listening and speaking. What do you do when it\'s the other person\'s turn?',
    explanation:'In a conversation, you should <b>listen carefully</b> when your friend is talking. Then they listen to you when it is your turn. This is called "taking turns".' }),

  makeMCQ({ id:'g2eng-spk-052', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which is the POLITE way to ask for something?',
    options:['Could I please have a pencil?','Give me a pencil.','I want a pencil now.','Pencil. Now.'],
    answer:'Could I please have a pencil?',
    hint:'Polite questions often use words like "please", "could" and "may".',
    explanation:'"<b>Could I please have a pencil?</b>" is the polite way to ask. Using "please" and "could" shows good manners in conversation.' }),

  makeMCQ({ id:'g2eng-spk-053', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'If someone asks "How are you today?", which is the BEST response?',
    options:['I am very well, thank you! How are you?','Fine.','Yes.','I don\'t know.'],
    answer:'I am very well, thank you! How are you?',
    hint:'A good response answers the question AND shows interest in the other person.',
    explanation:'"<b>I am very well, thank you! How are you?</b>" — it answers the question fully and then asks back, which keeps the conversation going. Excellent manners!' }),

  makeMCQ({ id:'g2eng-spk-054', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'What does "taking turns" in a conversation mean?',
    options:['One person speaks, then the other person speaks','Everyone speaks at the same time','Only one person speaks the whole time','Nobody speaks'],
    answer:'One person speaks, then the other person speaks',
    hint:'A conversation is like a tennis match — one person hits, then the other hits back.',
    explanation:'"<b>One person speaks, then the other person speaks</b>" — this is taking turns. Good conversations have back-and-forth, like a ball being passed between two people.' }),

  makeMCQ({ id:'g2eng-spk-055', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which question would help you KEEP a conversation going?',
    options:['What do you like to do after school?','Stop talking.','I don\'t want to talk.','Be quiet.'],
    answer:'What do you like to do after school?',
    hint:'A good question shows interest in the other person and invites them to share.',
    explanation:'"<b>What do you like to do after school?</b>" keeps the conversation going — it shows you are interested and gives the other person something to talk about.' }),

  makeMCQ({ id:'g2eng-spk-056', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Your friend says, "I lost my favourite toy." Which response shows you are being a GOOD listener?',
    options:['Oh no, that is sad! Where did you last see it?','That\'s nice.','So what?','I am hungry.'],
    answer:'Oh no, that is sad! Where did you last see it?',
    hint:'A good listener shows they heard what was said and cares about the other person.',
    explanation:'"<b>Oh no, that is sad! Where did you last see it?</b>" — you showed you listened (oh no, that is sad!) and you asked a helpful question. Brilliant!' }),

  makeMCQ({ id:'g2eng-spk-057', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which phrase do you use to join a conversation politely?',
    options:['Excuse me, may I join in?','Move! I want to talk.','Hello stop talking.','Quiet, my turn.'],
    answer:'Excuse me, may I join in?',
    hint:'"Excuse me" is a polite phrase for entering a conversation or getting someone\'s attention.',
    explanation:'"<b>Excuse me, may I join in?</b>" is polite and respectful. Using "excuse me" and "may I" shows good manners.' }),

  makeMCQ({ id:'g2eng-spk-058', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Someone says: "My name is Sam. I am seven years old." What can you say NEXT to keep the conversation going?',
    options:['Nice to meet you, Sam! I am six. What is your favourite subject?','OK.','Yes.','Goodbye.'],
    answer:'Nice to meet you, Sam! I am six. What is your favourite subject?',
    hint:'Share your own information AND ask a question to keep the conversation flowing.',
    explanation:'"<b>Nice to meet you, Sam! I am six. What is your favourite subject?</b>" — you greeted Sam, shared about yourself and asked a question. Perfect conversation!' }),

  makeMCQ({ id:'g2eng-spk-059', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which is the correct way to AGREE with someone politely?',
    options:['Yes, I think so too!','You are right because I said so.','Whatever.','Fine.'],
    answer:'Yes, I think so too!',
    hint:'Agreeing politely means saying yes in a friendly and enthusiastic way.',
    explanation:'"<b>Yes, I think so too!</b>" is a polite and friendly way to agree. It shows you are listening and you share the same opinion.' }),

  makeMCQ({ id:'g2eng-spk-060', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Your friend says "I love reading books." If you DISAGREE, which is the polite way to say so?',
    options:['I prefer playing football, but reading is nice too.','No! You are wrong.','Books are boring, stop talking.','Reading is bad.'],
    answer:'I prefer playing football, but reading is nice too.',
    hint:'You can share a different opinion and still be kind and respectful.',
    explanation:'"<b>I prefer playing football, but reading is nice too.</b>" — you shared a different view politely and acknowledged your friend\'s opinion. That is respectful conversation!' }),

  makeMCQ({ id:'g2eng-spk-061', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'What should you do if you do NOT understand what someone said?',
    options:['Say "Sorry, could you say that again please?"','Pretend you understood','Walk away','Get angry'],
    answer:'Say "Sorry, could you say that again please?"',
    hint:'It is always okay to ask someone to repeat themselves — it shows you are trying to understand.',
    explanation:'"<b>Sorry, could you say that again please?</b>" — asking politely for someone to repeat themselves is perfectly fine and shows good listening. Much better than pretending!' }),

  makeMCQ({ id:'g2eng-spk-062', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which sentence asks a question in a conversation?',
    options:['What is your favourite food?','I like mangoes.','She has a cat.','The dog is big.'],
    answer:'What is your favourite food?',
    hint:'A question asks for information. It usually ends with a question mark (?). Which sentence is asking something?',
    explanation:'"<b>What is your favourite food?</b>" is a question — it asks for information. The other sentences are statements (they give information). Questions keep conversations interesting!' }),

  makeMCQ({ id:'g2eng-spk-063', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'A good conversation is like a tennis rally. What does this mean?',
    options:['You take turns, going back and forth','Only one person speaks','Everyone shouts at once','You play tennis to talk'],
    answer:'You take turns, going back and forth',
    hint:'In tennis, the ball goes back and forth between two players. How is this like a conversation?',
    explanation:'Like tennis, a good conversation goes <b>back and forth</b> — you speak, then they speak, then you speak again. Taking turns keeps it going!' }),

  makeMCQ({ id:'g2eng-spk-064', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which phrase is a good way to START a conversation with someone new?',
    options:['Hello! My name is Leila. What is yours?','You! Talk.','Tell me everything.','What do you want?'],
    answer:'Hello! My name is Leila. What is yours?',
    hint:'Start with a greeting, share your name, and ask a question.',
    explanation:'"<b>Hello! My name is Leila. What is yours?</b>" — greeting (Hello!), sharing (My name is Leila), asking (What is yours?). A perfect conversation starter!' }),

  makeMCQ({ id:'g2eng-spk-065', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'What does it mean to "stay on topic" in a conversation?',
    options:['Talk about the same subject the whole time','Jump to a new topic every sentence','Stop talking suddenly','Speak very quietly'],
    answer:'Talk about the same subject the whole time',
    hint:'A topic is what the conversation is about. "Staying on topic" means keeping to the same subject.',
    explanation:'"<b>Talk about the same subject the whole time</b>" — staying on topic means not suddenly changing the subject to something unrelated.' }),

  makeMCQ({ id:'g2eng-spk-066', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Someone says: "I have a little sister." Which response keeps the conversation going?',
    options:['Oh nice! How old is she?','I know.','So what.','Stop.'],
    answer:'Oh nice! How old is she?',
    hint:'Show interest and ask a follow-up question.',
    explanation:'"<b>Oh nice! How old is she?</b>" — you showed interest (Oh nice!) and asked a question to learn more. That keeps the conversation flowing!' }),

  makeMCQ({ id:'g2eng-spk-067', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which is the CORRECT way to end a conversation?',
    options:['It was nice talking to you! Goodbye!','Just walk away silently.','Stop listening and look away.','Say nothing.'],
    answer:'It was nice talking to you! Goodbye!',
    hint:'Ending a conversation politely means saying you enjoyed talking and saying goodbye.',
    explanation:'"<b>It was nice talking to you! Goodbye!</b>" — this is a warm and polite way to end a conversation. It makes the other person feel good!' }),

  makeMCQ({ id:'g2eng-spk-068', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'In a conversation, which is the BEST way to introduce your friend?',
    options:['This is my friend Ali. He loves football.','That one is Ali.','Ali. Over there.','You know Ali.'],
    answer:'This is my friend Ali. He loves football.',
    hint:'A good introduction gives the person\'s name and something interesting about them.',
    explanation:'"<b>This is my friend Ali. He loves football.</b>" — a good introduction gives a name and a detail. It helps start a conversation between two people who don\'t know each other.' }),

  makeMCQ({ id:'g2eng-spk-069', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'What does it mean to "speak clearly" in a conversation?',
    options:['Use a voice that is easy to hear and understand','Shout very loudly','Mumble quietly','Speak with your mouth full'],
    answer:'Use a voice that is easy to hear and understand',
    hint:'Speaking clearly means the other person can hear and understand every word you say.',
    explanation:'To <b>speak clearly</b> means to use a voice that is easy to hear and understand — not too quiet, not too fast, and using proper words.' }),

  makeMCQ({ id:'g2eng-spk-070', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which phrase shows that you are INTERESTED in what someone is saying?',
    options:['That is so interesting! Tell me more.','Whatever.','I am bored.','Stop talking.'],
    answer:'That is so interesting! Tell me more.',
    hint:'Interest means you want to learn more. Which phrase shows that?',
    explanation:'"<b>That is so interesting! Tell me more.</b>" — this shows enthusiasm and invites the person to keep sharing. It is a wonderful conversation response!' }),

  makeMCQ({ id:'g2eng-spk-071', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Your friend is talking about their pet. Which is the WORST thing to do?',
    options:['Interrupt and change the topic to yourself','Listen carefully','Ask a question about the pet','Smile and nod to show you are listening'],
    answer:'Interrupt and change the topic to yourself',
    hint:'Interrupting someone and changing the topic shows you are not listening to them.',
    explanation:'The worst thing is to <b>interrupt and change the topic</b> — this is rude and shows you are not listening. Always wait for your turn to speak!' }),

  makeMCQ({ id:'g2eng-spk-072', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which word is a greeting used to START a conversation?',
    options:['Hello','Goodbye','Thank you','Sorry'],
    answer:'Hello',
    hint:'A greeting is the first thing you say when you meet someone.',
    explanation:'"<b>Hello</b>" is a greeting — we say it at the START of a conversation. "Goodbye" is for ending. "Thank you" is for thanks. "Sorry" is for apologising.' }),

  makeMCQ({ id:'g2eng-spk-073', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'What is the BEST question to ask someone to find out what they enjoy?',
    options:['What do you like to do for fun?','What is 5 + 5?','What colour is the sky?','How tall are you?'],
    answer:'What do you like to do for fun?',
    hint:'A conversation question about hobbies and interests helps you get to know someone better.',
    explanation:'"<b>What do you like to do for fun?</b>" — this is a great conversation question! It helps you learn about the other person\'s interests and keeps the conversation lively.' }),

  makeMCQ({ id:'g2eng-spk-074', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'If you want to say sorry in a conversation, which phrase is most appropriate?',
    options:['I am very sorry, I didn\'t mean to.','Sorry. Whatever.','I said sorry already.','Why should I say sorry?'],
    answer:'I am very sorry, I didn\'t mean to.',
    hint:'A sincere apology shows you care about the other person\'s feelings.',
    explanation:'"<b>I am very sorry, I didn\'t mean to.</b>" — this is a sincere and heartfelt apology. It shows you care about how the other person feels.' }),

  makeMCQ({ id:'g2eng-spk-075', chapterId:'g2eng-speaking', difficulty:1, subsection:'conversation',
    question:'Which shows the CORRECT order of a short conversation?',
    options:['Greeting → Question → Response → Goodbye','Goodbye → Question → Greeting → Response','Response → Goodbye → Greeting → Question','Question → Goodbye → Response → Greeting'],
    answer:'Greeting → Question → Response → Goodbye',
    hint:'Think about how a conversation naturally starts, continues and ends.',
    explanation:'A good conversation flows: <b>Greeting</b> (Hello!) → <b>Question</b> (How are you?) → <b>Response</b> (I am fine, thanks!) → <b>Goodbye</b> (See you later!). A natural pattern!' })

);

})();
