'use strict';
// ══════════════════════════════════════════════════════════════════════════
//  Grade 9 Science - B3 · Biodiversity  volume batch (66 questions)
//  IDs: g9s-b3-v001 through g9s-b3-v066
//  Source: NCE Science (Biology) 2021-2025; NCF Grades 7-9 §B3.
// ══════════════════════════════════════════════════════════════════════════

(function () {

const CH = 'g9s-b3-biodiversity';

const MCQ = [

  // ── what_is_biodiversity (v001–v012) ─────────────────────────────────

  ['g9s-b3-v001', 'what_is_biodiversity', 1,
   'What does the term <b>biodiversity</b> refer to?',
   ['The variety of living organisms in a given area',
    'The total mass of all plants in an ecosystem',
    'The number of individual animals in a habitat',
    'The range of non-living conditions in an environment'],
   'The variety of living organisms in a given area',
   'Bio = life; diversity = variety.',
   'Biodiversity is the variety of all living things — including species, habitats and genetic variation — found in a given area.'],

  ['g9s-b3-v002', 'what_is_biodiversity', 1,
   'Which of the following is an example of <b>species diversity</b>?',
   ['A forest containing trees, ferns, insects, birds and mammals',
    'Two dogs of the same breed having slightly different coat colours',
    'A single lake covering a very large geographical area',
    'All the members of one ant colony living in the same nest'],
   'A forest containing trees, ferns, insects, birds and mammals',
   'Species diversity is about the range of different species present.',
   'Species diversity measures the number of different species in an area; a forest with many types of organisms has high species diversity.'],

  ['g9s-b3-v003', 'what_is_biodiversity', 2,
   'A scientist notes that the individuals in a population of Mauritian pink pigeons have slightly different beak sizes and feather patterns. Which type of biodiversity does this illustrate?',
   ['Genetic diversity within a species',
    'Species diversity across a habitat',
    'Habitat diversity across the island',
    'Ecosystem diversity across Mauritius'],
   'Genetic diversity within a species',
   'The differences are between individuals of the same species.',
   'Genetic diversity refers to the variation in genes between individuals of the same species; different beak sizes and feather patterns in a pigeon population arise from genetic differences.'],

  ['g9s-b3-v004', 'what_is_biodiversity', 2,
   'Which of the following best describes <b>habitat diversity</b>?',
   ['The range of different types of ecosystems and habitats in a region',
    'The number of individuals of a single species in one habitat',
    'The variation in DNA sequences between members of a population',
    'The total number of different species found in one square metre'],
   'The range of different types of ecosystems and habitats in a region',
   'Habitat diversity is about the variety of places where organisms live.',
   'Habitat diversity refers to the variety of different habitats and ecosystems — such as coral reefs, forests, wetlands and grasslands — present in a region.'],

  ['g9s-b3-v005', 'what_is_biodiversity', 1,
   'How many main components of biodiversity are scientists generally agreed upon?',
   ['Three — species, genetic and habitat diversity',
    'Two — plant diversity and animal diversity only',
    'Four — species, gene, habitat and climate diversity',
    'One — species diversity is the only recognised measure'],
   'Three — species, genetic and habitat diversity',
   'Think of the three levels at which biodiversity is measured.',
   'Biodiversity is measured at three levels: species diversity (range of species), genetic diversity (variation within species) and habitat/ecosystem diversity (range of habitats).'],

  ['g9s-b3-v006', 'what_is_biodiversity', 2,
   'A coral reef off the coast of Mauritius contains hundreds of species of fish, coral, molluscs and echinoderms. Which type of biodiversity is this BEST describing?',
   ['Species diversity in a marine habitat',
    'Genetic diversity within the coral species',
    'Habitat diversity across the whole island',
    'Ecosystem services of the Indian Ocean'],
   'Species diversity in a marine habitat',
   'The question counts different types of organisms.',
   'The presence of hundreds of different species in the coral reef is a measure of high species diversity; it is not describing variation within one species or the range of different habitats.'],

  ['g9s-b3-v007', 'what_is_biodiversity', 2,
   'Why is it important to consider genetic diversity as well as species diversity when measuring biodiversity?',
   ['Genetic diversity determines how well a species can adapt to future changes',
    'Species diversity always includes genetic diversity, so they are the same measure',
    'Genetic diversity only matters for domesticated crops, not wild species',
    'Counting species is impossible, so genetic measures are used instead'],
   'Genetic diversity determines how well a species can adapt to future changes',
   'Think about what happens when all individuals of a species are genetically identical.',
   'High genetic diversity gives a species a wider range of traits; if conditions change, some individuals are more likely to survive. Low genetic diversity increases the risk of extinction from disease or climate change.'],

  ['g9s-b3-v008', 'what_is_biodiversity', 3,
   'A conservation scientist says: "Mauritius has lost biodiversity at all three levels." What does this mean?',
   ['Fewer species exist now, individuals within species are more similar genetically, and fewer habitat types remain',
    'The total mass of organisms has fallen, food chains are shorter, and the climate has become wetter',
    'Animals can no longer breed successfully, plants produce fewer seeds, and rivers have dried up',
    'The country now imports more food, tourism has declined, and the sea temperature has dropped'],
   'Fewer species exist now, individuals within species are more similar genetically, and fewer habitat types remain',
   'Match the three components of biodiversity to the three losses described.',
   'Loss of biodiversity at all three levels means: reduced species diversity (fewer species), reduced genetic diversity (less variation within remaining species) and reduced habitat diversity (fewer different ecosystems surviving).'],

  ['g9s-b3-v009', 'what_is_biodiversity', 3,
   'A tropical island has 200 species, all of which are tree species. A nearby island has 50 species spread across insects, birds, reptiles, plants and fungi. Which island has GREATER biodiversity? Explain.',
   ['The 50-species island — it has greater variety across different groups of organisms',
    'The 200-species island — it has the highest total number of species present',
    'Both islands are equal — species count is the only valid measure of biodiversity',
    'Neither can be compared — they have different climates and areas'],
   'The 50-species island — it has greater variety across different groups of organisms',
   'Biodiversity is about variety, not just total number.',
   'True biodiversity reflects variation across different groups; an island with 50 species spread across many taxonomic groups shows greater ecological and functional diversity than one with 200 species all from the same group.'],

  ['g9s-b3-v010', 'what_is_biodiversity', 1,
   'Which of these habitats is generally considered to have the HIGHEST species biodiversity on Earth?',
   ['Tropical rainforests',
    'Arctic tundra regions',
    'Desert sand dune systems',
    'Deep ocean trenches below 3 km'],
   'Tropical rainforests',
   'Warm, wet, productive environments support the most life.',
   'Tropical rainforests receive high rainfall and sunlight all year, providing food and shelter for an enormous number of species — they contain over half of all known species despite covering less than 6% of land.'],

  ['g9s-b3-v011', 'what_is_biodiversity', 2,
   'Black River Gorges National Park in Mauritius protects native forests, rivers and grasslands. Which aspect of biodiversity does this park best preserve?',
   ['Habitat diversity, by maintaining several different ecosystem types',
    'Genetic diversity, by keeping all animals genetically identical',
    'Species diversity, by introducing new species from other countries',
    'Climate diversity, by controlling rainfall in the park area'],
   'Habitat diversity, by maintaining several different ecosystem types',
   'The park contains multiple different ecosystem types.',
   'Black River Gorges protects native forests, wetlands and grasslands in one area; this maintains habitat diversity by keeping several ecosystem types intact within a single protected region.'],

  ['g9s-b3-v012', 'what_is_biodiversity', 3,
   'Scientists find that all remaining individuals of an endangered Mauritian plant species are genetically nearly identical. Why is this a serious concern even if their numbers are currently stable?',
   ['A single disease or climate change event could kill all individuals simultaneously',
    'Genetically identical plants always produce seeds that fail to germinate properly',
    'Conservationists cannot measure biodiversity if all individuals look the same',
    'Identical genes mean the plants will produce poisonous fruits over time'],
   'A single disease or climate change event could kill all individuals simultaneously',
   'Think about what genetic uniformity means for resilience.',
   'When all individuals share very similar genes, none may carry traits that resist a new pathogen or cope with changed conditions; a single outbreak could wipe out the entire population, making extinction highly likely.'],

  // ── importance_of_biodiversity (v014–v025) ───────────────────────────

  ['g9s-b3-v014', 'importance_of_biodiversity', 1,
   'Which term describes the benefits that humans receive from natural ecosystems?',
   ['Ecosystem services',
    'Ecological footprints',
    'Environmental impacts',
    'Genetic resources'],
   'Ecosystem services',
   'Think about what nature does for people.',
   'Ecosystem services are the benefits that healthy ecosystems provide to humans, including clean air, clean water, food production, medicine and climate regulation.'],

  ['g9s-b3-v015', 'importance_of_biodiversity', 1,
   'Which process, carried out by flowering plants, is an ecosystem service that is essential for food production?',
   ['Pollination of crops by insects',
    'Respiration of roots in the soil',
    'Decomposition of dead plant matter',
    'Transpiration of water through leaves'],
   'Pollination of crops by insects',
   'Without this service, most fruit and vegetable crops would not produce food.',
   'Many crop plants depend on insects (especially bees) for pollination; loss of insect diversity directly reduces crop yields and threatens food security.'],

  ['g9s-b3-v016', 'importance_of_biodiversity', 2,
   'Many modern medicines were first discovered from wild organisms. Which of the following best illustrates this link between biodiversity and medicine?',
   ['Penicillin was discovered from the Penicillium mould fungus',
    'Vaccines are produced entirely from chemicals in a factory',
    'Doctors use electricity generated by hydroelectric dams',
    'Surgery is performed using instruments made from iron ore'],
   'Penicillin was discovered from the Penicillium mould fungus',
   'The first widely used antibiotic came from a fungus.',
   'Penicillin, the first widely used antibiotic, was isolated from the Penicillium fungus; many cancer drugs, pain killers and other medicines also originate from wild plants, animals and microorganisms.'],

  ['g9s-b3-v017', 'importance_of_biodiversity', 2,
   'How does a high level of biodiversity in crop wild relatives help to secure the future of food production?',
   ['Wild relatives carry genes that can be used to breed disease-resistant or climate-tolerant crop varieties',
    'Wild relatives produce more food per hectare than cultivated varieties on all soil types',
    'Wild relatives do not need water, making farming cheaper in dry regions',
    'Wild relatives attract pollinators that then move exclusively to farmed fields'],
   'Wild relatives carry genes that can be used to breed disease-resistant or climate-tolerant crop varieties',
   'Genetic diversity in wild plants gives breeders raw material to improve crops.',
   'Wild relatives of crop plants often carry genes for pest resistance, drought tolerance or disease resistance; breeders use these genes to develop improved varieties that can feed a growing and changing world.'],

  ['g9s-b3-v018', 'importance_of_biodiversity', 2,
   'Why does a diverse ecosystem tend to be more stable than one with only a few species?',
   ['If one species declines, others can fill its role and maintain ecosystem function',
    'More species means more predators, which keeps all population sizes exactly equal',
    'Diverse ecosystems always receive more rainfall and have richer soils than simple ones',
    'A greater number of species means that food chains are shorter and simpler'],
   'If one species declines, others can fill its role and maintain ecosystem function',
   'More species means more redundancy in the system.',
   'In a species-rich ecosystem, several organisms may perform similar roles (e.g. as pollinators or decomposers); if one declines, others compensate, so the ecosystem continues to function.'],

  ['g9s-b3-v019', 'importance_of_biodiversity', 1,
   'Forests help regulate the climate by absorbing large quantities of which gas?',
   ['Carbon dioxide',
    'Oxygen gas',
    'Nitrogen gas',
    'Water vapour'],
   'Carbon dioxide',
   'Trees use this gas during photosynthesis.',
   'Trees absorb carbon dioxide during photosynthesis and store the carbon in their trunks, roots and leaves; forests therefore act as large carbon sinks that help slow climate change.'],

  ['g9s-b3-v020', 'importance_of_biodiversity', 2,
   'Mangrove forests along the Mauritian coastline protect the shoreline from storm damage and trap sediment. Which category of ecosystem service does this represent?',
   ['Regulating services — they control natural processes',
    'Provisioning services — they provide materials for human use',
    'Cultural services — they provide places for recreation and tourism',
    'Supporting services — they directly produce oxygen for breathing'],
   'Regulating services — they control natural processes',
   'The mangroves are controlling (regulating) a natural process: erosion.',
   'Regulating services are ecosystem benefits that involve the regulation of natural processes; mangroves reduce coastal erosion, absorb wave energy and stabilise sediment, all of which regulate the impact of storms.'],

  ['g9s-b3-v021', 'importance_of_biodiversity', 3,
   'In Mauritius, the dodo became extinct in the 17th century. The tambalacoque tree (Calvaria major) was thought to depend on the dodo to disperse its seeds. What does this illustrate about biodiversity?',
   ['The loss of one species can affect the survival of other species in the same ecosystem',
    'Extinction of large birds always causes an increase in insect populations',
    'Trees with large seeds can only be dispersed by large extinct animals',
    'Biodiversity loss only matters when it affects species that humans can eat'],
   'The loss of one species can affect the survival of other species in the same ecosystem',
   'Think about what happens when a seed disperser disappears.',
   'The dodo ate tambalacoque fruits and the seeds passed through its gut; with the dodo gone, seeds could not germinate as effectively, showing how extinction of one species can threaten others linked to it in the ecosystem.'],

  ['g9s-b3-v022', 'importance_of_biodiversity', 3,
   'A reef tourist site in Mauritius depends on healthy coral reefs with high fish diversity. Which ecosystem service does this represent AND why is biodiversity essential to it?',
   ['Cultural service — tourists pay to see diverse marine life, so fewer species directly reduces economic income',
    'Provisioning service — tourists consume fish directly from the reef during their visit',
    'Supporting service — the reef produces oxygen that tourists breathe while snorkelling',
    'Regulating service — the reef controls ocean temperature, which tourists prefer for swimming'],
   'Cultural service — tourists pay to see diverse marine life, so fewer species directly reduces economic income',
   'Tourism gives people experiences and cultural enrichment — which service category is that?',
   'Tourism is a cultural ecosystem service; tourists are attracted by the diversity and beauty of the reef ecosystem, so a loss of fish species or coral diversity directly reduces the value and income that this service provides.'],

  ['g9s-b3-v023', 'importance_of_biodiversity', 2,
   'Wetland ecosystems in Mauritius naturally filter pollutants from water before it reaches the sea. Which category of ecosystem service is this?',
   ['Regulating services — the wetland controls a natural water-purification process',
    'Provisioning services — the wetland provides clean drinking water directly to homes',
    'Cultural services — the wetland is used for outdoor recreation and education',
    'Supporting services — the wetland produces the nutrients that other ecosystems need'],
   'Regulating services — the wetland controls a natural water-purification process',
   'Filtering and purifying water is a regulation of a natural process.',
   'Wetlands trap sediment and absorb nutrients and pollutants from run-off water; this is a regulating service because the ecosystem is moderating a natural process (the water cycle and water quality).'],

  ['g9s-b3-v024', 'importance_of_biodiversity', 2,
   'Why is it important to conserve genetic diversity in wild plant species, even those that humans do not currently use?',
   ['Those plants may contain genes useful to medicine or agriculture in the future',
    'All wild plants produce oxygen that is more pure than that from cultivated species',
    'Wild plants with more genetic diversity always grow faster in all conditions',
    'Genetic diversity in wild plants prevents invasive species from establishing nearby'],
   'Those plants may contain genes useful to medicine or agriculture in the future',
   'We cannot predict which species or genes will become useful.',
   'Many medicines and improved crop varieties have been developed from species once considered unimportant; conserving wild genetic diversity preserves options for future scientific discoveries.'],

  ['g9s-b3-v025', 'importance_of_biodiversity', 3,
   'A keystone species is one that has a disproportionately large effect on its ecosystem relative to its population size. What would most likely happen if a keystone predator were removed from an ecosystem?',
   ['Prey populations would explode and out-compete other species, reducing overall biodiversity',
    'Other predators would immediately take over the same role with no effect on biodiversity',
    'Producer populations would decrease because less predator dung fertilises the soil',
    'Biodiversity would increase because fewer animals are being eaten and killed'],
   'Prey populations would explode and out-compete other species, reducing overall biodiversity',
   'Think about what controls prey numbers in the absence of a predator.',
   'Without the keystone predator, certain prey populations grow unchecked, consuming so much vegetation or smaller prey that other species are displaced, leading to a collapse in species diversity in the ecosystem.'],

  // ── quadrat_sampling (v027–v035 MCQ) ─────────────────────────────────

  ['g9s-b3-v027', 'quadrat_sampling', 1,
   'What is a quadrat used for in ecological field work?',
   ['Sampling the species and abundance of organisms in a defined area',
    'Measuring the temperature of water in a river or pond sample',
    'Counting the total number of animals in a very large territory',
    'Testing the pH and mineral content of a soil sample'],
   'Sampling the species and abundance of organisms in a defined area',
   'A quadrat marks out a fixed area for counting.',
   'A quadrat is a square frame (e.g. 1 m × 1 m) placed on the ground; scientists count all individuals of each species inside it to estimate abundance across a larger area.'],

  ['g9s-b3-v028', 'quadrat_sampling', 1,
   'Why must quadrats be placed <b>randomly</b> in a survey area?',
   ['To avoid bias and ensure the sample represents the whole area fairly',
    'To make sure every quadrat lands in the most species-rich part of the area',
    'To ensure that only rare species are recorded and common ones are ignored',
    'To save time by concentrating sampling in easy-to-reach locations'],
   'To avoid bias and ensure the sample represents the whole area fairly',
   'Non-random placement would bias the results.',
   'Random placement ensures that each part of the survey area has an equal chance of being sampled, so the results give a representative and unbiased estimate of the whole area.'],

  ['g9s-b3-v029', 'quadrat_sampling', 2,
   'How are random numbers typically used in quadrat surveys?',
   ['To generate random coordinates that determine where each quadrat is placed',
    'To count how many species are found inside each individual quadrat',
    'To calculate the total area covered by the quadrats placed in the field',
    'To determine which species to record and which ones to ignore'],
   'To generate random coordinates that determine where each quadrat is placed',
   'Lay a grid and use numbers to choose x and y positions.',
   'A pair of random numbers from a table or calculator is used to select the x and y coordinates on a grid overlaid on the survey area, ensuring that quadrat positions are unbiased.'],

  ['g9s-b3-v030', 'quadrat_sampling', 2,
   'A student places 10 quadrats of 1 m² each in a 100 m² field and counts 30 daisy plants in total. What is the best estimate for the total number of daisies in the field?',
   ['300 daisy plants',
    '30 daisy plants',
    '3000 daisy plants',
    '3 daisy plants'],
   '300 daisy plants',
   'Find the mean per quadrat, then scale up to the full area.',
   'Mean per quadrat = 30 ÷ 10 = 3 plants per m². Total estimate = 3 × 100 = 300 daisy plants.'],

  ['g9s-b3-v031', 'quadrat_sampling', 2,
   'What is the main limitation of using only one quadrat to estimate species abundance in a large habitat?',
   ['One quadrat may not be representative of the whole area',
    'One quadrat takes too long to complete compared to using many',
    'A single quadrat always records too many species to count accurately',
    'One quadrat cannot be placed randomly without mathematical equipment'],
   'One quadrat may not be representative of the whole area',
   'A single measurement is always less reliable than many.',
   'A single quadrat gives only one data point; that particular spot may be unusually rich or poor in species compared to the rest of the habitat, making the estimate unreliable.'],

  ['g9s-b3-v032', 'quadrat_sampling', 3,
   'A student places quadrats only under trees because it is easier to work in the shade. How does this affect the reliability of the results?',
   ['It introduces systematic bias — shaded areas may have different species from sunny patches',
    'It reduces reliability because trees produce more oxygen, affecting plant growth',
    'It improves reliability because shade provides consistent temperature conditions',
    'It has no effect because species are randomly distributed under trees anyway'],
   'It introduces systematic bias — shaded areas may have different species from sunny patches',
   'Placing quadrats in chosen spots rather than randomly is biased sampling.',
   'Choosing to sample only under trees is a biased approach; shade-tolerant species would be over-represented and sun-loving species ignored, so the data would not reflect the true composition of the habitat.'],

  ['g9s-b3-v033', 'quadrat_sampling', 2,
   'What does <b>percentage cover</b> measure in a quadrat?',
   ['The fraction of the quadrat area covered by a particular species',
    'The number of individual plants of each species inside the quadrat',
    'The percentage of the total survey area sampled by the quadrat',
    'The proportion of species in the quadrat that are rare or endangered'],
   'The fraction of the quadrat area covered by a particular species',
   'You estimate how much of the square is taken up by that species.',
   'Percentage cover estimates what proportion of the quadrat area is occupied by a species; it is useful for plants that are difficult to count individually, such as grasses.'],

  ['g9s-b3-v034', 'quadrat_sampling', 3,
   'A researcher is comparing the biodiversity of two grassland sites. She uses more quadrats at one site than the other because it is larger. Why is this a sensible decision?',
   ['More quadrats in a larger site give a more representative sample of its greater area',
    'More quadrats always produce lower estimates, correcting for the site being larger',
    'The number of quadrats must match the number of species expected to be found',
    'Larger sites have more sunlight, so more quadrats are needed to record light levels'],
   'More quadrats in a larger site give a more representative sample of its greater area',
   'Sample size should relate to the area being studied.',
   'Using more quadrats in a larger area ensures that a similar proportion of the site is sampled; using the same small number of quadrats in a much larger area would mean each quadrat represents a greater unseen area, reducing reliability.'],

  ['g9s-b3-v035', 'quadrat_sampling', 2,
   'Quadrats are most suitable for surveying which type of organism?',
   ['Plants and slow-moving animals such as limpets and barnacles',
    'Fast-moving animals such as fish, birds and running insects',
    'Microscopic organisms such as bacteria and single-celled algae',
    'Underground organisms such as earthworms and burrowing beetles'],
   'Plants and slow-moving animals such as limpets and barnacles',
   'Think about which organisms stay in one place long enough to be counted.',
   'Quadrats work best for organisms that do not move or move very slowly; plants, lichens, barnacles and limpets stay within the quadrat long enough to be counted accurately.'],

  // ── natural_threats (v041–v052) ───────────────────────────────────────

  ['g9s-b3-v041', 'natural_threats', 1,
   'What is a tropical cyclone?',
   ['An intense rotating storm with very strong winds and heavy rainfall',
    'A long dry period with no rainfall lasting several months or years',
    'A sudden cold snap that kills tropical plants and animals in hours',
    'A gradual rise in sea level that floods low-lying coastal habitats'],
   'An intense rotating storm with very strong winds and heavy rainfall',
   'Mauritius experiences these storms, especially between November and April.',
   'A tropical cyclone is a powerful rotating storm system characterised by very strong winds, heavy rain and low atmospheric pressure; Mauritius lies in the cyclone belt of the Indian Ocean.'],

  ['g9s-b3-v042', 'natural_threats', 2,
   'How does a cyclone directly reduce biodiversity in a forest ecosystem?',
   ['Strong winds uproot trees and destroy nesting sites, killing or displacing many species',
    'Cyclones bring cold air that freezes tropical organisms not adapted to low temperatures',
    'Heavy rain raises ocean salinity, which kills freshwater species in coastal rivers',
    'Low air pressure during a cyclone causes animals to lose their sense of direction'],
   'Strong winds uproot trees and destroy nesting sites, killing or displacing many species',
   'Think about the physical destruction caused by high winds.',
   'Cyclone winds can snap and uproot trees, strip leaves, flatten undergrowth and destroy nesting holes; this eliminates food sources and shelter for birds, mammals and invertebrates, causing deaths and habitat loss.'],

  ['g9s-b3-v043', 'natural_threats', 2,
   'How does a severe drought reduce plant biodiversity in a tropical region?',
   ['Water stress kills species that are not drought-tolerant, leaving only hardy survivors',
    'Drought raises soil temperature until all plant seeds are destroyed by heat',
    'Lack of rain increases soil pH until all plant nutrients become unavailable',
    'Drought causes animals to migrate away, removing pollination of all plant species'],
   'Water stress kills species that are not drought-tolerant, leaving only hardy survivors',
   'Plants that need regular moisture cannot survive long dry periods.',
   'Prolonged drought deprives plants of the water needed for photosynthesis and growth; species with shallow roots or high water requirements die first, leaving mainly drought-tolerant species and reducing species diversity.'],

  ['g9s-b3-v044', 'natural_threats', 1,
   'Which natural disaster is Mauritius MOST frequently affected by that can damage forest biodiversity?',
   ['Tropical cyclones',
    'Volcanic eruptions',
    'Major earthquakes',
    'Prolonged ice storms'],
   'Tropical cyclones',
   'Mauritius is located in the Indian Ocean cyclone belt.',
   'Mauritius is regularly struck by tropical cyclones between November and April; their strong winds and flooding cause significant damage to native vegetation and wildlife populations.'],

  ['g9s-b3-v045', 'natural_threats', 2,
   'Following a severe drought, a population of frogs in a Mauritian river declines sharply. What is the most likely direct reason?',
   ['Reduced water levels shrink the aquatic habitat that frogs depend on for breeding',
    'Drought raises air temperature until frogs cannot move fast enough to catch prey',
    'Low rainfall increases soil nitrogen, which is toxic to amphibian skin',
    'Frogs are sensitive to sound, and drought causes louder conditions that stress them'],
   'Reduced water levels shrink the aquatic habitat that frogs depend on for breeding',
   'Frogs need standing or flowing water to lay eggs and for tadpoles to develop.',
   'Frogs are aquatic breeders; drought reduces or eliminates pools and streams, so eggs and tadpoles die and adults lose their breeding habitat, causing the population to fall sharply.'],

  ['g9s-b3-v046', 'natural_threats', 3,
   'After a cyclone, some native bird species recover their population quickly while others remain at very low numbers for years. What factor most likely explains this difference?',
   ['Species with flexible diets and multiple nesting options recover faster than specialised species',
    'Species with larger body sizes always recover more rapidly than small species after storms',
    'Bird species that are native to Mauritius always out-compete introduced species after a cyclone',
    'Recovery speed depends entirely on how much financial aid is provided by conservationists'],
   'Species with flexible diets and multiple nesting options recover faster than specialised species',
   'Specialists depend on one food source or nest site that may be destroyed.',
   'Generalist species can switch to alternative food sources and nest in various sites; specialists that depend on one tree species for food or nesting have fewer options after a cyclone destroys those resources.'],

  ['g9s-b3-v047', 'natural_threats', 2,
   'How can a powerful cyclone damage coral reef biodiversity around Mauritius?',
   ['Strong waves and debris physically break apart coral structures and smother reefs with sediment',
    'Cyclones lower sea temperature until coral is unable to photosynthesise and dies immediately',
    'Storm surges carry freshwater offshore that permanently increases the salinity of the reef',
    'High winds remove all dissolved carbon dioxide from the sea, preventing coral growth'],
   'Strong waves and debris physically break apart coral structures and smother reefs with sediment',
   'Think about the physical impact of storm waves on a shallow reef.',
   'Cyclone waves can be several metres high; they smash coral branches, overturn boulders, and deposit sediment over living coral, blocking light and suffocating the organisms, causing significant reef damage.'],

  ['g9s-b3-v048', 'natural_threats', 3,
   'A conservationist argues that drought is a greater long-term threat to biodiversity than a single cyclone. Which argument best supports this view?',
   ['Drought can persist for months or years, causing cumulative mortality that species cannot recover from',
    'Cyclones last only a few days, so animals can always escape their path by moving away',
    'Drought only affects plants, whereas cyclones damage both plants and animals simultaneously',
    'Biodiversity always increases after a cyclone because new habitats are created by fallen trees'],
   'Drought can persist for months or years, causing cumulative mortality that species cannot recover from',
   'Compare the duration and ongoing impact of each natural disaster.',
   'A cyclone is an acute event lasting hours to days; species begin to recover almost immediately. Drought is a chronic stress lasting months or years, draining water resources and causing prolonged mortality with no recovery window.'],

  ['g9s-b3-v049', 'natural_threats', 1,
   'Which natural process removes water from the soil and reduces its availability for plants during a dry period?',
   ['Evaporation from the soil surface and transpiration by plants',
    'Photosynthesis in green leaves, which converts water to sugar',
    'Decomposition by bacteria, which uses up water molecules quickly',
    'Pollination by insects, which moves water droplets between flowers'],
   'Evaporation from the soil surface and transpiration by plants',
   'Two processes remove water from plants and soil to the air.',
   'During dry periods, evaporation from the soil and transpiration through plant leaves continuously remove water; without rainfall to replenish it, soil moisture drops and plants become water-stressed.'],

  ['g9s-b3-v050', 'natural_threats', 2,
   'Flash flooding caused by heavy cyclone rainfall can reduce soil biodiversity by:',
   ['Washing away topsoil and the organisms it contains into rivers and the sea',
    'Adding excess minerals to the soil that stimulate bacterial overgrowth',
    'Raising soil oxygen levels until anaerobic bacteria are killed instantly',
    'Cooling the soil so rapidly that all soil organisms enter permanent dormancy'],
   'Washing away topsoil and the organisms it contains into rivers and the sea',
   'Topsoil contains the most organic matter and living organisms.',
   'Flash floods carry away the nutrient-rich topsoil layer along with seeds, invertebrates and microorganisms; this strips the land of the biological resources needed for plant regrowth and soil ecosystem recovery.'],

  ['g9s-b3-v051', 'natural_threats', 3,
   'Why are endemic island species, such as those found only in Mauritius, particularly vulnerable to natural disasters compared to species with wide geographical ranges?',
   ['They exist in only one location, so a single disaster can affect their entire global population',
    'Island species are always smaller, which makes them weaker and less able to survive storms',
    'Island species never evolved defensive behaviours, leaving them helpless against any threat',
    'Natural disasters cannot reach islands because they are surrounded by ocean'],
   'They exist in only one location, so a single disaster can affect their entire global population',
   'If a species lives only on one island, there is nowhere else for it to survive.',
   'An endemic species found only on Mauritius has its entire global population in one place; a severe cyclone or drought that devastates that island threatens the species with total extinction, as there are no other populations elsewhere.'],

  ['g9s-b3-v052', 'natural_threats', 2,
   'After a major cyclone, which of the following would BEST help a forest ecosystem to recover its biodiversity?',
   ['Protecting the area from further disturbance so that natural succession can occur',
    'Immediately planting fast-growing exotic trees to replace all the fallen native trees',
    'Introducing new predator species to control the populations of surviving prey animals',
    'Burning the fallen wood to release nutrients quickly into the soil for faster growth'],
   'Protecting the area from further disturbance so that natural succession can occur',
   'Natural recovery needs time and stability — not new disturbances.',
   'Given adequate protection from further disturbance (especially human interference), native species naturally recolonise and regenerate over time through ecological succession; introducing exotics or burning debris can hinder this process.'],

  // ── human_threats (v054–v065) ─────────────────────────────────────────

  ['g9s-b3-v054', 'human_threats', 1,
   'What is deforestation?',
   ['The large-scale removal of trees and forest habitats by humans',
    'The natural death of old trees that have reached the end of their lifespan',
    'The movement of forest species to new areas due to climate change',
    'The replanting of trees on previously farmed agricultural land'],
   'The large-scale removal of trees and forest habitats by humans',
   'It involves humans clearing forest areas.',
   'Deforestation is the human-driven process of clearing forests, typically for agriculture, logging, urban development or charcoal production, resulting in the permanent loss of woodland habitat.'],

  ['g9s-b3-v055', 'human_threats', 2,
   'How does deforestation in Mauritius directly reduce biodiversity?',
   ['It destroys the habitat that native species depend on, leaving them without food or shelter',
    'It causes sea levels to rise around the island, flooding coastal wetland habitats',
    'It removes all the carbon dioxide from the air, preventing photosynthesis by remaining plants',
    'It increases rainfall so much that rivers flood and destroy aquatic ecosystems'],
   'It destroys the habitat that native species depend on, leaving them without food or shelter',
   'When the habitat disappears, the species that live there disappear too.',
   'Native Mauritian species — from birds and reptiles to insects and plants — are adapted to forest habitats; when those forests are cleared, species lose their food sources, nesting sites and shelter, leading to local extinction.'],

  ['g9s-b3-v056', 'human_threats', 2,
   'What is an <b>invasive alien species</b>?',
   ['A species introduced from another region that establishes and spreads, harming native biodiversity',
    'A native species that suddenly grows much faster than it did in previous years',
    'A species that migrates naturally between habitats each season as conditions change',
    'Any animal that is kept as a pet and occasionally escapes into the wild briefly'],
   'A species introduced from another region that establishes and spreads, harming native biodiversity',
   'It is non-native, introduced — usually by humans — and causes ecological harm.',
   'Invasive alien species are organisms brought to a new region (intentionally or accidentally) where they have no natural predators or competitors; they spread rapidly and out-compete or prey on native species.'],

  ['g9s-b3-v057', 'human_threats', 1,
   'Which of the following is a well-known invasive alien plant species in Mauritius that threatens native forest?',
   ['Psidium cattleianum (strawberry guava)',
    'Hibiscus rosa-sinensis (Chinese hibiscus)',
    'Eucalyptus globulus (Tasmanian blue gum)',
    'Cocos nucifera (coconut palm)'],
   'Psidium cattleianum (strawberry guava)',
   'This fruit-bearing shrub has spread widely across Mauritian native forests.',
   'Strawberry guava (Psidium cattleianum) was introduced to Mauritius and has become one of the most destructive invasive plants, out-competing native vegetation in the Black River Gorges and other protected areas.'],

  ['g9s-b3-v058', 'human_threats', 2,
   'How do invasive alien species reduce native biodiversity?',
   ['They out-compete native species for food, space and light, causing native populations to decline',
    'They produce chemicals that increase soil fertility, which native plants cannot tolerate',
    'They always hybridise with native species, producing sterile offspring that cannot reproduce',
    'They carry diseases that only affect invasive species, reducing their own populations first'],
   'They out-compete native species for food, space and light, causing native populations to decline',
   'Invasive species often spread rapidly because they face fewer competitors or predators.',
   'In their new environment, invasive species often face no natural predators or diseases that control them; they grow faster or reproduce more quickly than native species and crowd them out of available resources.'],

  ['g9s-b3-v059', 'human_threats', 3,
   'Why are invasive alien species often so successful in their new environment?',
   ['They have no natural predators, parasites or competitors in the new region to control their populations',
    'They are always larger and physically stronger than the native species they encounter',
    'They carry genetic mutations that allow them to adapt instantly to the new climate',
    'Humans always protect invasive species from harm because they are rare in the new country'],
   'They have no natural predators, parasites or competitors in the new region to control their populations',
   'Biological controls that limited the species at home are absent in the new place.',
   'In their native range, invasive species are kept in check by predators, parasites and competitors that co-evolved with them; in the new environment these controls are absent, allowing the species to reproduce unchecked.'],

  ['g9s-b3-v060', 'human_threats', 2,
   'How does water pollution from agricultural run-off affect aquatic biodiversity?',
   ['Excess fertilisers cause algal blooms that deplete oxygen and kill aquatic animals',
    'Pesticide residues in water raise the pH until fish scales dissolve and the fish die',
    'Agricultural water heats rivers to above 50 °C, which cooks all aquatic invertebrates',
    'Run-off adds so much calcium to the water that invertebrate shells become too thick to open'],
   'Excess fertilisers cause algal blooms that deplete oxygen and kill aquatic animals',
   'This process is called eutrophication.',
   'Fertiliser run-off enriches water with nitrates and phosphates; algae multiply rapidly, blocking light and then dying; their decomposition by bacteria consumes dissolved oxygen, causing hypoxia and death of fish and invertebrates.'],

  ['g9s-b3-v061', 'human_threats', 3,
   'What is habitat fragmentation, and why is it particularly harmful to biodiversity?',
   ['Breaking large habitats into isolated patches — species cannot move between patches to breed or find food',
    'The physical removal of all plants from a habitat, leaving bare rock and soil behind',
    'The introduction of new species into a fragmented habitat to replace lost native ones',
    'A process where habitats are divided into smaller sections that are then individually protected'],
   'Breaking large habitats into isolated patches — species cannot move between patches to breed or find food',
   'Small isolated populations are at much greater risk of extinction than large connected ones.',
   'Habitat fragmentation divides continuous habitats with roads, farms or buildings; isolated populations become too small to be genetically viable, cannot migrate to new areas, and are more vulnerable to local extinction events.'],

  ['g9s-b3-v062', 'human_threats', 2,
   'How does the widespread use of pesticides in agriculture reduce biodiversity?',
   ['Pesticides kill non-target organisms such as insects and birds that feed on treated plants',
    'Pesticides improve soil quality so much that only a few dominant plant species can thrive',
    'Pesticides attract invasive species that then colonise areas of treated farmland',
    'Pesticides are only harmful to the specific pest species and have no wider effects'],
   'Pesticides kill non-target organisms such as insects and birds that feed on treated plants',
   'Most pesticides are not perfectly selective — other organisms are also affected.',
   'Many pesticides kill non-target insects including pollinators such as bees; animals that eat treated insects (e.g. insectivorous birds) are also affected through bioaccumulation, reducing species diversity across food chains.'],

  ['g9s-b3-v063', 'human_threats', 1,
   'What does the term <b>habitat destruction</b> mean in the context of biodiversity loss?',
   ['The permanent alteration of a natural habitat so that it can no longer support its native species',
    'The temporary disturbance of a habitat that species can recover from within a few weeks',
    'The natural process by which old habitats are replaced by newer ones over geological time',
    'The protection of habitats by creating national parks and nature reserves around them'],
   'The permanent alteration of a natural habitat so that it can no longer support its native species',
   'Destruction means the habitat can no longer function as it did.',
   'Habitat destruction occurs when human activities permanently change a natural environment — through building, farming, mining or drainage — so that the species that previously lived there can no longer survive.'],

  ['g9s-b3-v064', 'human_threats', 3,
   'Why are small islands such as Mauritius particularly vulnerable to the effects of invasive alien species?',
   ['Island species evolved in isolation and lack defences or behaviours to deal with new predators or competitors',
    'Islands always have warmer climates that allow invasive species to breed all year round',
    'Islands have high genetic diversity in native species that makes them easy for invaders to exploit',
    'Island governments cannot afford to remove invasive species, unlike mainland countries'],
   'Island species evolved in isolation and lack defences or behaviours to deal with new predators or competitors',
   'Isolation means no co-evolution with certain types of threats.',
   'Mauritian species evolved on an isolated island with no mammalian predators for millions of years; they have no evolved fear responses or physical defences against introduced predators such as rats, cats and mongooses.'],

  ['g9s-b3-v065', 'human_threats', 2,
   'How does climate change threaten the coral reefs around Mauritius?',
   ['Rising sea temperatures cause coral bleaching, which can kill the coral and destroy reef biodiversity',
    'Climate change causes more lightning strikes that directly burn coral during tropical storms',
    'Warmer air temperatures evaporate the ocean until reefs are exposed to air and dry out',
    'Climate change increases river flow, which carries so much freshwater that reefs freeze'],
   'Rising sea temperatures cause coral bleaching, which can kill the coral and destroy reef biodiversity',
   'Coral lives in symbiosis with algae; heat disrupts this relationship.',
   'When sea temperatures rise above 1–2 °C above normal for extended periods, corals expel their symbiotic algae (zooxanthellae), turning white (bleaching); without the algae they lose their food source and may die, devastating reef biodiversity.'],

];

MCQ.forEach(([id, subsection, difficulty, question, options, answer, hint, explanation]) => {
  STATIC_QUESTIONS.push(makeMCQ({ id, chapterId: CH, subsection, difficulty,
    question, options, answer, hint, explanation }));
});

// ── Numeric (quadrat calculations) ────────────────────────────────────────

const NUM = [
  ['g9s-b3-v036', 'quadrat_sampling', 2,
   'A 1 m² quadrat is placed randomly in a field. It contains 8 dandelion plants. The field has a total area of 50 m². Estimate the total number of dandelion plants in the field.',
   400,
   'Multiply the count in the quadrat by the number of times the quadrat fits into the field.',
   'The quadrat is 1 m², so it fits into the 50 m² field 50 times. Estimated total = 8 × 50 = 400 dandelion plants.'],

  ['g9s-b3-v037', 'quadrat_sampling', 2,
   'A student counts 12 buttercup plants in a 0.5 m² quadrat. The total area of the grassland being surveyed is 20 m². Estimate the total number of buttercup plants in the grassland.',
   480,
   'First find the number of plants per m², then multiply by the total area.',
   '12 plants in 0.5 m² = 24 plants per m². Total estimate = 24 × 20 = 480 buttercup plants.'],

  ['g9s-b3-v038', 'quadrat_sampling', 3,
   'A 2 m × 2 m quadrat placed in a meadow contains 20 clover plants. Estimate the total number of clover plants in a 400 m² meadow.',
   2000,
   'Calculate the area of the quadrat first, then find plants per m², then scale up.',
   'Quadrat area = 2 × 2 = 4 m². Density = 20 ÷ 4 = 5 plants per m². Total = 5 × 400 = 2000 clover plants.'],

  ['g9s-b3-v039', 'quadrat_sampling', 2,
   'Five 1 m² quadrats are placed randomly in a habitat. The number of grass plants counted in each quadrat is 4, 6, 5, 3 and 7. Calculate the mean number of grass plants per quadrat.',
   5,
   'Add all five counts together, then divide by the number of quadrats.',
   'Total = 4 + 6 + 5 + 3 + 7 = 25. Mean = 25 ÷ 5 = 5 plants per quadrat.'],
];

NUM.forEach(([id, subsection, difficulty, question, answer, hint, explanation]) => {
  STATIC_QUESTIONS.push(makeNum({ id, chapterId: CH, subsection, difficulty,
    question, answer, hint, explanation }));
});

// ── Short-answer ──────────────────────────────────────────────────────────

const SHORT = [
  ['g9s-b3-v013', 'what_is_biodiversity', 1,
   'Give one example of a habitat in Mauritius that is known for high biodiversity.',
   'Coral reef',
   ['Black River Gorges', 'the coral reef', 'coral reefs', 'tropical forest',
    'native forest', 'Black River Gorges National Park', 'mangrove'],
   'Think about Mauritius environments on land and in the sea.',
   'Mauritius has highly biodiverse habitats including its coral reef system, the native forests of Black River Gorges National Park, and coastal mangroves.'],

  ['g9s-b3-v026', 'importance_of_biodiversity', 1,
   'State one ecosystem service that forests provide to humans.',
   'Carbon dioxide absorption / carbon storage',
   ['clean air', 'oxygen production', 'water purification', 'filtering water',
    'preventing soil erosion', 'providing timber', 'providing medicine',
    'regulating climate', 'carbon sequestration', 'absorbing carbon dioxide'],
   'Think about what trees do for the environment and for people.',
   'Forests provide many ecosystem services including: absorbing carbon dioxide, purifying water, preventing soil erosion, providing timber, and supplying medicines from plants.'],

  ['g9s-b3-v040', 'quadrat_sampling', 2,
   'State one reason why quadrats must be placed randomly when conducting a biodiversity survey.',
   'To prevent bias in the results',
   ['to avoid bias', 'so results represent the whole area', 'to get a fair sample',
    'to make results representative', 'to ensure all areas have equal chance of being sampled'],
   'Think about what goes wrong if you choose where to place each quadrat.',
   'Random placement prevents the scientist from (deliberately or accidentally) choosing areas that are unusually rich or poor in species, making the sample representative of the whole habitat.'],

  ['g9s-b3-v053', 'natural_threats', 1,
   'Name one natural threat to biodiversity in Mauritius.',
   'Tropical cyclone',
   ['cyclone', 'hurricane', 'drought', 'cyclones', 'droughts',
    'flooding', 'flash floods'],
   'Think about natural events that damage habitats in the Indian Ocean region.',
   'Mauritius is regularly affected by tropical cyclones and periods of drought, both of which can damage habitats and reduce biodiversity.'],

  ['g9s-b3-v066', 'human_threats', 1,
   'Give one example of an invasive alien species found in Mauritius.',
   'Psidium cattleianum (strawberry guava)',
   ['strawberry guava', 'guava', 'mongoose', 'rat', 'black rat',
    'Indian myna', 'myna bird', 'rose apple', 'Syzygium jambos',
    'common myna', 'Achatina fulica', 'giant African land snail'],
   'Think of a plant or animal brought to Mauritius that now threatens native species.',
   'Mauritius has many invasive alien species including strawberry guava (Psidium cattleianum), the common myna bird (Acridotheres tristis), the mongoose, and the giant African land snail.'],
];

SHORT.forEach(([id, subsection, difficulty, question, answer, alsoAccept, hint, explanation]) => {
  STATIC_QUESTIONS.push(makeText({ id, chapterId: CH, subsection, difficulty,
    question, answer, alsoAccept, hint, explanation }));
});

})();
