'use strict';
// ══════════════════════════════════════════════════════════════════════════
//  Grade 9 Biology - Science, Technology & Society, coverage fill
//
//  ⚠ THIS FILE EXISTS BECAUSE OF THE SPLIT. g9s-sts was divided between the
//    three science packs by subject affinity rather than duplicated, so this
//    pack kept 11 items across three subsections. Chromatography, distillation,
//    optical fibres and the climate-data correlation live in the chemistry and
//    physics packs; biology keeps Barnard, evaluating information and ethics,
//    and this file fills all three to depth in biological contexts.
//
//  ⚠ EVERY NAMED FACT IS REAL AND CHECKABLE. Christiaan Barnard, a South
//    African surgeon, performed the first human-to-human heart transplant at
//    Groote Schuur Hospital in Cape Town in December 1967. The patient, Louis
//    Washkansky, survived 18 days and died of pneumonia, because the drugs
//    given to stop rejection also suppressed his defences against infection.
//    His second patient, Philip Blaiberg, lived over eighteen months. The 18
//    days carry the lesson: a scientific first is not the same as a success,
//    and a bank that rounds that off teaches the wrong thing about science.
//
//  ⚠ ETHICS ITEMS MUST NOT SMUGGLE IN AN OPINION AS THE ANSWER. The mark is
//    for recognising WHAT KIND of question is being asked - what ought to be
//    done, rather than what is true - never for holding a particular view.
//
//  Source: NCE Biology 2021-2025; NCF Grades 7-9 §STS.
// ══════════════════════════════════════════════════════════════════════════

(function () {

const CH = 'g9s-sts';

const MCQ = [

  // ── christiaan_barnard ────────────────────────────────────────────────
  ['g9s-stsb-001', 'christiaan_barnard', 1,
   'In which city did Christiaan Barnard carry out the first human heart transplant?',
   ['Cape Town', 'Johannesburg', 'Port Louis', 'Pretoria'],
   'Cape Town',
   'It is a coastal city in South Africa.',
   'The operation was performed at Groote Schuur Hospital in Cape Town in December 1967.'],

  ['g9s-stsb-002', 'christiaan_barnard', 1,
   'Christiaan Barnard was a surgeon from which country?',
   ['South Africa', 'New Zealand', 'Switzerland', 'Netherlands'],
   'South Africa',
   'The hospital was Groote Schuur.',
   'Barnard was a South African surgeon, and the first transplant was carried out in his own country rather than in Europe or America.'],

  ['g9s-stsb-003', 'christiaan_barnard', 2,
   'In which year was the first human-to-human heart transplant performed?',
   ['1967', '1947', '1977', '1987'], '1967',
   'It was in the same decade as the first Moon landing.',
   'The operation took place in December 1967, two years before the first Moon landing.'],

  ['g9s-stsb-004', 'christiaan_barnard', 2,
   'Who was the first patient to receive a transplanted human heart?',
   ['Louis Washkansky', 'Philip Blaiberg', 'Christiaan Barnard', 'Denise Darvall'],
   'Louis Washkansky',
   'He survived the operation by eighteen days.',
   'Louis Washkansky received the heart in December 1967; Philip Blaiberg was Barnard&rsquo;s second patient and lived far longer.'],

  ['g9s-stsb-005', 'christiaan_barnard', 2,
   'The heart used in the first transplant came from a young woman killed in a road accident. What is such a person called?',
   ['The donor', 'The patient', 'The surgeon', 'The nurse'],
   'The donor',
   'The organ is given, not taken.',
   'The person whose organ is given for transplant is the donor; the person who receives it is the recipient or patient.'],

  ['g9s-stsb-006', 'christiaan_barnard', 3,
   'The first transplant patient died of pneumonia eighteen days after the operation. Why was he at risk of infection?',
   ['Drugs had weakened his immune system',
    'The operation had taken many hours',
    'The new heart could not pump blood',
    'He was not allowed to drink water'],
   'Drugs had weakened his immune system',
   'Something had to stop his body attacking the new heart.',
   'Drugs were given so his body would not reject the heart, but the same drugs lowered his defence against infection, and pneumonia killed him.'],

  ['g9s-stsb-007', 'christiaan_barnard', 3,
   'Barnard&rsquo;s second transplant patient lived for more than eighteen months. What did that show?',
   ['The technique was improving with practice',
    'Rejection had been solved completely then',
    'Heart transplants had become very common',
    'The first patient had not been treated'],
   'The technique was improving with practice',
   'Compare eighteen days with eighteen months.',
   'Surviving eighteen months rather than eighteen days showed real progress, but rejection and infection remained serious problems for years afterwards.'],

  ['g9s-stsb-008', 'christiaan_barnard', 3,
   'Which advance did most to turn heart transplants into a long-term success?',
   ['Better drugs to prevent rejection',
    'Larger operating theatres in cities',
    'Faster ways of stitching a wound',
    'Cheaper anaesthetics for surgery'],
   'Better drugs to prevent rejection',
   'The surgery worked from the start; something else did not.',
   'Barnard showed the operation was possible in 1967; it became a lasting treatment only when drugs could hold rejection back without leaving patients defenceless.'],

  ['g9s-stsb-009', 'christiaan_barnard', 3,
   'Why is a donor heart matched to the patient before a transplant?',
   ['To reduce the chance of rejection',
    'To keep the heart beating in transport',
    'To lower the cost of the operation',
    'To make the operation take less time'],
   'To reduce the chance of rejection',
   'The closer the match, the less the immune system objects.',
   'A closely matched heart looks less foreign to the immune system, so it is less likely to be attacked and less immunosuppressive drug is needed.'],

  ['g9s-stsb-010', 'christiaan_barnard', 4,
   'Transplants depend on people agreeing in advance to donate their organs. Why does that make it a question for society?',
   ['It depends on what people choose to allow',
    'It depends on how fast surgeons can work',
    'It depends on the cost of the equipment',
    'It depends on the size of the hospital'],
   'It depends on what people choose to allow',
   'Surgery is possible; the organs still have to be offered.',
   'The operation is a technical matter, but whether organs are available at all rests on what people and their families are willing to agree to.'],

  ['g9s-stsb-011', 'christiaan_barnard', 3,
   'What is meant by saying that a body has <b>rejected</b> a transplanted organ?',
   ['The immune system attacks the new organ',
    'The organ is the wrong size for the space',
    'The surgeon removes the organ once more',
    'The patient refuses to accept the organ'],
   'The immune system attacks the new organ',
   'It is the same system that fights infection.',
   'The immune system recognises the transplanted tissue as foreign and attacks it, which is why patients take drugs to hold that response back.'],

  ['g9s-stsb-012', 'christiaan_barnard', 2,
   'Which statement about the first heart transplant is a <b>fact</b> rather than an opinion?',
   ['The patient lived for eighteen days',
    'The patient should not have agreed to it',
    'The operation was the finest ever done',
    'The surgeon deserved far more praise'],
   'The patient lived for eighteen days',
   'A fact can be checked; an opinion cannot.',
   'The eighteen days is a recorded, checkable fact; the other three are judgements that different people could reasonably disagree about.'],

  ['g9s-stsb-013', 'christiaan_barnard', 4,
   'A magazine writes that Barnard "cured heart disease in 1967". Why is that wrong?',
   ['One operation on one patient cures nothing',
    'Heart disease was unknown in South Africa',
    'Barnard worked on lungs and not on hearts',
    'The operation was carried out much later'],
   'One operation on one patient cures nothing',
   'What happened to the patient after eighteen days?',
   'A single operation on a single patient who died within three weeks was a first, not a cure; heart disease remains a leading cause of death today.'],

  // ── evaluating_information ────────────────────────────────────────────
  ['g9s-stsb-016', 'evaluating_information', 2,
   'Two websites give different numbers for how many plant species are found only in Mauritius. What should a pupil do?',
   ['Look for the source of each number',
    'Choose the website with more pictures',
    'Add the two numbers together to check',
    'Choose the larger of the two numbers'],
   'Look for the source of each number',
   'Ask where each figure came from.',
   'A number is only as good as its source, so the survey or study behind each figure is what decides which one to use.'],

  ['g9s-stsb-017', 'evaluating_information', 2,
   'Which source of information about a new medicine is likely to be most reliable?',
   ['A study checked by other scientists',
    'An advertisement made by the maker of it',
    'A comment posted underneath a video',
    'A message forwarded on by a friend'],
   'A study checked by other scientists',
   'Who has looked at the evidence besides the person making the claim?',
   'A study reviewed by independent scientists has been checked by people with no interest in the result; the other three carry no such check.'],

  ['g9s-stsb-018', 'evaluating_information', 3,
   'Why is a result that several separate groups have obtained more trustworthy?',
   ['A repeated result is less likely to be chance',
    'The first group is usually the least careful',
    'More groups means the work costs more money',
    'A longer claim is always a stronger claim'],
   'A repeated result is less likely to be chance',
   'Think what one unlucky sample could produce.',
   'One group can be unlucky, mistaken or biased; the same result found independently several times is far harder to explain away as chance.'],

  ['g9s-stsb-019', 'evaluating_information', 3,
   'A website selling a herbal remedy says it "cures asthma". What should be looked for before believing it?',
   ['Evidence from a properly controlled trial',
    'The number of people who have shared it',
    'How many pictures the website contains',
    'The price the remedy is being sold for'],
   'Evidence from a properly controlled trial',
   'What would show the remedy, and not something else, did the work?',
   'Only a controlled trial, in which a treated group is compared with a control group, can show that the remedy itself produced the improvement.'],

  ['g9s-stsb-020', 'evaluating_information', 3,
   'Why should the date on a scientific web page be checked?',
   ['Newer evidence may have replaced it',
    'A dated page is written by a scientist',
    'A page without a date cannot be found',
    'Older pages are harder to read online'],
   'Newer evidence may have replaced it',
   'Scientific understanding changes as evidence builds.',
   'Advice on treatment, conservation or disease is revised as new evidence arrives, so an undated or very old page may be giving superseded information.'],

  ['g9s-stsb-021', 'evaluating_information', 3,
   'A newspaper reports that "scientists say chocolate prevents heart disease". What is missing?',
   ['Which scientists, and what evidence',
    'Which shops are selling the chocolate',
    'How much the chocolate costs to buy',
    'How much chocolate a bar contains'],
   'Which scientists, and what evidence',
   'The headline names nobody and cites nothing.',
   'Without the study, its size and who carried it out, there is nothing to judge; "scientists say" is not itself evidence for anything.'],

  ['g9s-stsb-022', 'evaluating_information', 4,
   'A pupil researching biodiversity finds a useful page written by a charity that is asking for donations. How should the page be used?',
   ['Used, but checked against another source',
    'Accepted because the cause is a good one',
    'Copied straight into the report as it is',
    'Ignored because it is asking for money'],
   'Used, but checked against another source',
   'Having an interest in the answer is not the same as being wrong.',
   'An organisation with a cause may present evidence selectively without being dishonest, so its figures are used but confirmed elsewhere.'],

  ['g9s-stsb-023', 'evaluating_information', 3,
   'What does it mean to say that a source is <b>biased</b>?',
   ['It favours one conclusion over others',
    'It contains a number of spelling errors',
    'It is written in more than one language',
    'It was written a very long time ago'],
   'It favours one conclusion over others',
   'Ask who gains if the reader is convinced.',
   'A biased source leans towards one conclusion, often because the writer has something to gain from it, so its evidence needs independent checking.'],

  ['g9s-stsb-024', 'evaluating_information', 2,
   'Which question best tests whether a health claim is scientific?',
   ['What evidence was collected, and how',
    'How often it appears on the internet',
    'How many people believe it is true',
    'How famous the person saying it is'],
   'What evidence was collected, and how',
   'Science is judged on evidence, not on popularity.',
   'How the evidence was gathered decides whether a claim stands; fame, popularity and repetition change nothing about whether it is true.'],

  ['g9s-stsb-025', 'evaluating_information', 3,
   'A forwarded phone message claims that a fruit "kills all viruses". Why should it be treated with caution?',
   ['No evidence travels with the message',
    'The fruit does not grow in Mauritius',
    'Forwarded messages are hard to read',
    'The message was sent by a classmate'],
   'No evidence travels with the message',
   'What arrived with the claim?',
   'A forwarded message carries the claim but not the study behind it, so there is nothing to check and no way to judge whether it is true.'],

  ['g9s-stsb-026', 'evaluating_information', 3,
   'Why is a result from a sample of 1000 people usually more reliable than one from 10?',
   ['A larger sample is less affected by chance',
    'A larger sample is always cheaper to test',
    'A smaller sample takes far longer to test',
    'A smaller sample is harder to write down'],
   'A larger sample is less affected by chance',
   'Think how much one unusual person changes each result.',
   'One unusual person changes a group of ten far more than a group of a thousand, so the larger sample gives a result closer to the true value.'],

  ['g9s-stsb-027', 'evaluating_information', 4,
   'Two graphs show the same HIV figures, but one has a stretched vertical scale so the rise looks much steeper. What does this show?',
   ['How a graph is drawn can mislead',
    'The steeper graph is the correct one',
    'HIV data cannot be shown on a graph',
    'One of the two graphs must be false'],
   'How a graph is drawn can mislead',
   'The numbers are identical in both.',
   'The same data can be made to look dramatic or gentle by the choice of scale, which is why an axis and its scale are read before the shape of the line.'],

  ['g9s-stsb-028', 'evaluating_information', 3,
   'What is the best reason for reading more than one source on a topic?',
   ['One source may leave something out',
    'More sources fill more pages of notes',
    'The longest source is the best of them',
    'Sources always agree with each other'],
   'One source may leave something out',
   'What would you never notice from a single page?',
   'A second source may add evidence the first omitted or disagree with it, and either way the reader learns something a single page could not show.'],

  ['g9s-stsb-029', 'evaluating_information', 2,
   'Who checks a scientific paper before a journal publishes it?',
   ['Other scientists in the same field',
    'The company that made the product',
    'The readers who buy the journal',
    'The government of that country'],
   'Other scientists in the same field',
   'The checkers must understand the work.',
   'Papers are reviewed by independent scientists working on the same subject, who judge the methods and the evidence before publication is allowed.'],

  ['g9s-stsb-030', 'evaluating_information', 4,
   'A claim on a website has no author, no date and no references. How should it be treated?',
   ['As unsupported until it is checked',
    'As proved because a website printed it',
    'As false because there is no author',
    'As true because it is written down'],
   'As unsupported until it is checked',
   'An unchecked claim is not the same as a false one.',
   'With no author, date or references there is nothing to check, so the claim is set aside as unsupported rather than accepted or declared false.'],

  // ── ethics_of_science ─────────────────────────────────────────────────
  ['g9s-stsb-033', 'ethics_of_science', 2,
   'Which of these is an <b>ethical</b> question about dissecting animals in school?',
   ['Whether animals should be used at all',
    'Which instruments cut the tissue best',
    'How the specimen should be preserved',
    'Where the specimen jars are stored'],
   'Whether animals should be used at all',
   'Three of these can be settled by trying them out.',
   'Whether it is right to use an animal is a question of values; the other three are practical questions answered by observation.'],

  ['g9s-stsb-034', 'ethics_of_science', 3,
   'An unborn baby can now be tested for certain diseases. Which is the ethical question this raises?',
   ['What parents should be told, and when',
    'Which machine takes the sample best',
    'How long the test takes to complete',
    'How the sample is stored in the lab'],
   'What parents should be told, and when',
   'Which of these has no measurement that could answer it?',
   'What families should be told, and what they may then decide, is a matter of values; the sampling, the timing and the storage are technical questions.'],

  ['g9s-stsb-035', 'ethics_of_science', 3,
   'Why must consent be obtained before a person takes part in a medical trial?',
   ['They have a right to decide for themselves',
    'The trial can then be finished more quickly',
    'The medicine then costs less to produce',
    'The results are then easier to write up'],
   'They have a right to decide for themselves',
   'Whose body is being used?',
   'A person must understand the risks and agree freely before taking part; consent protects the volunteer, not the convenience of the trial.'],

  ['g9s-stsb-036', 'ethics_of_science', 3,
   'The result of a person&rsquo;s HIV test is kept confidential. Why is that an ethical duty?',
   ['Private medical information belongs to them',
    'The result could change if tested again later',
    'The laboratory has too many results to file',
    'The doctor may not remember it correctly'],
   'Private medical information belongs to them',
   'Think about the harm that follows if it is shared.',
   'A person&rsquo;s medical information is theirs to share or withhold, and disclosure can cost them work, housing and relationships, so confidentiality is a duty.'],

  ['g9s-stsb-037', 'ethics_of_science', 3,
   'Endangered species are protected by law in Mauritius. Which is an <b>ethical</b> argument for protecting them?',
   ['Other living things have a right to exist',
    'They can be counted easily using a quadrat',
    'They are found on more than one island',
    'They were discovered a long time ago'],
   'Other living things have a right to exist',
   'One of these is a claim about what ought to be.',
   'Saying that other species have a right to exist is a claim about values; where they live and how they are counted are matters of fact.'],

  ['g9s-stsb-038', 'ethics_of_science', 3,
   'Which of these questions can <b>science</b> answer, rather than ethics?',
   ['How quickly the virus spreads',
    'Who should be treated first',
    'Whether the trial was fair',
    'Whether the cost is right'],
   'How quickly the virus spreads',
   'Which one could be settled by measurement?',
   'The rate of spread is measured from case data; who should be treated first, and what is fair or right, are judgements measurement cannot make.'],

  ['g9s-stsb-039', 'ethics_of_science', 3,
   'A new medicine is costly and there is not enough for everyone. What kind of question is "who should receive it"?',
   ['An ethical question', 'A measurement question',
    'A practical question', 'A chemical question'],
   'An ethical question',
   'It asks what ought to happen.',
   'Deciding fairly who receives a scarce treatment is a question about what ought to be done, which no experiment can settle.'],

  ['g9s-stsb-040', 'ethics_of_science', 4,
   'Why might a scientist refuse to work on a project even though it could be done?',
   ['They judge the use of it to be wrong',
    'They prefer to work on their own ideas',
    'They cannot measure the results of it',
    'They have run out of laboratory space'],
   'They judge the use of it to be wrong',
   'Being able to do something is not a reason to do it.',
   'A scientist may decide the likely use of the work is harmful; that is an ethical judgement, separate from whether the work is technically possible.'],

  ['g9s-stsb-041', 'ethics_of_science', 3,
   'Genetically modified crops can raise the yield of a harvest. Which is an ethical concern about them?',
   ['Who controls the seed that farmers buy',
    'How quickly the crop grows in a field',
    'Which fertiliser the crop needs most',
    'How the seed is stored before sowing'],
   'Who controls the seed that farmers buy',
   'Three of these could be answered by a field trial.',
   'Who owns and controls the seed decides who benefits from the technology, which is a question about fairness rather than about the crop itself.'],

  ['g9s-stsb-042', 'ethics_of_science', 4,
   'An invasive plant is cleared from a nature reserve by cutting it down. Which is the ethical question here?',
   ['Which living things we may remove',
    'Which tool cuts the stems fastest',
    'How many workers are needed here',
    'How long the clearing work takes'],
   'Which living things we may remove',
   'One of these asks what we are entitled to do.',
   'Deciding that one species may be destroyed to protect others is a judgement about value; the tools, the workers and the time are practical matters.'],

  ['g9s-stsb-043', 'ethics_of_science', 3,
   'Why is testing new medicines on animals debated?',
   ['It weighs animal suffering against human benefit',
    'It requires laboratories with a great deal of space',
    'It makes the medicines take much longer to develop',
    'It needs more scientists than any other kind of work'],
   'It weighs animal suffering against human benefit',
   'Two things that both matter are being set against each other.',
   'The debate sets real harm to animals against real benefit to patients, and reasonable people weigh those two differently; no measurement settles it.'],

  ['g9s-stsb-044', 'ethics_of_science', 2,
   'Which statement about science and ethics is correct?',
   ['Science says what is; ethics says what ought',
    'Ethics says what is; science says what ought',
    'Science and ethics answer the same questions',
    'Ethics can be settled by an experiment alone'],
   'Science says what is; ethics says what ought',
   'One describes the world; the other judges what to do in it.',
   'Science establishes what is the case; ethics asks what we ought to do about it, and an experiment cannot decide the second.'],

  ['g9s-stsb-045', 'ethics_of_science', 3,
   'Why should the risks of a new medical technology be explained to the public?',
   ['People affected by it have a right to know',
    'The public pays for the research to be done',
    'The technology then works more reliably',
    'The scientists then have less to explain'],
   'People affected by it have a right to know',
   'Who bears the risk?',
   'Those who carry the risk are entitled to know what it is, and a decision made without that information is not a free choice at all.'],

  ['g9s-stsb-046', 'ethics_of_science', 4,
   'A company conceals a harmful side effect of its medicine. Which principle has it broken?',
   ['Honesty about the evidence collected',
    'Speed in bringing a product to sale',
    'Secrecy about a new discovery made',
    'Neatness in recording the results'],
   'Honesty about the evidence collected',
   'What did the company do with what it knew?',
   'Reporting evidence honestly, including results that harm the case, is the basic duty of science; concealing a side effect puts patients in danger.'],

  ['g9s-stsb-047', 'ethics_of_science', 3,
   'Who should decide how a new scientific discovery is used?',
   ['Society, informed by the scientists',
    'The scientists working on it alone',
    'Nobody, because it cannot be used',
    'The company that paid for the work'],
   'Society, informed by the scientists',
   'The knowledge and its use are two different things.',
   'Scientists explain what a discovery can and cannot do; deciding how it is used affects everyone, so that decision belongs to society as a whole.'],

];

MCQ.forEach(([id, subsection, difficulty, question, options, answer, hint, explanation]) => {
  STATIC_QUESTIONS.push(makeMCQ({ id, chapterId: CH, subsection, difficulty,
    question, options, answer, hint, explanation }));
});

const SHORT = [
  ['g9s-stsb-014', 'christiaan_barnard', 2,
   'Give the year in which the first human-to-human heart transplant was performed.',
   '1967', ['in 1967', 'december 1967', '1967.'],
   'It was two years before the first Moon landing.',
   'Christiaan Barnard performed the first human-to-human heart transplant in December 1967.'],

  ['g9s-stsb-015', 'christiaan_barnard', 2,
   'Give the term for a person whose organ is given for transplant into another person.',
   'Donor', ['a donor', 'the donor', 'organ donor'],
   'The organ is given, not taken.',
   'The donor supplies the organ and the recipient receives it; matching the two reduces the chance of rejection.'],

  ['g9s-stsb-031', 'evaluating_information', 2,
   'Give the word for a source that favours one conclusion because it has something to gain.',
   'Biased', ['bias', 'biassed', 'it is biased'],
   'It leans one way.',
   'A biased source leans towards a conclusion it benefits from, so its evidence must be checked against an independent source.'],

  ['g9s-stsb-032', 'evaluating_information', 3,
   'State what should be looked for behind any scientific claim before it is believed.',
   'Evidence', ['the evidence', 'proof', 'scientific evidence', 'evidence for it'],
   'It is not how confidently the claim is stated.',
   'A claim stands on the evidence collected for it and on whether independent scientists have checked that evidence.'],

  ['g9s-stsb-048', 'ethics_of_science', 2,
   'Give the word describing a question about what ought to be done rather than about what is true.',
   'Ethical', ['an ethical question', 'ethics', 'ethical question', 'a moral question', 'moral'],
   'It is about right and wrong.',
   'An ethical question asks what we ought to do, and no measurement or experiment can settle it on its own.'],

  ['g9s-stsb-049', 'ethics_of_science', 3,
   'State what must be obtained from a person before they may take part in a medical trial.',
   'Consent', ['their consent', 'informed consent', 'permission', 'agreement', 'consent form'],
   'They must understand the risks and agree freely.',
   'Informed consent means the volunteer has been told the risks and has agreed without pressure to take part.'],
];

SHORT.forEach(([id, subsection, difficulty, question, answer, alsoAccept, hint, explanation]) => {
  STATIC_QUESTIONS.push(makeText({ id, chapterId: CH, subsection, difficulty,
    question, answer, alsoAccept, hint, explanation }));
});
})();
