'use strict';
// Grade 7 Maths — expanded questions (ch02), continuing from ch01_core.js IDs

STATIC_QUESTIONS.push(

  // ── g7m-integers ────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-integers-007', chapterId:'g7m-integers', difficulty:2,
    subsection:'number_types',
    question:'Which of the following is a COMPOSITE number?',
    options:['2','7','11','15'],
    answer:'15',
    hint:'A composite number has more than two factors.',
    explanation:'15 = 3 × 5 — it has factors 1, 3, 5 and 15. 2, 7 and 11 are all prime.' }),

  makeMCQ({ id:'g7m-integers-008', chapterId:'g7m-integers', difficulty:2,
    subsection:'number_types',
    question:'The triangular numbers begin 1, 3, 6, 10, … What is the FIFTH triangular number?',
    options:['12','14','15','16'],
    answer:'15',
    hint:'Add the next natural number: 10 + 5.',
    explanation:'Each triangular number is formed by adding the next counting number. 10 + 5 = 15.' }),

  makeTF({ id:'g7m-integers-009', chapterId:'g7m-integers', difficulty:1,
    subsection:'number_types',
    question:'1 is a prime number.',
    answer:false,
    explanation:'1 is NOT prime. A prime number must have exactly TWO distinct factors: 1 and itself. The number 1 has only one factor, so it is neither prime nor composite.' }),

  makeMCQ({ id:'g7m-integers-010', chapterId:'g7m-integers', difficulty:1,
    subsection:'number_line',
    question:'Which of these integers is furthest to the LEFT on a number line?',
    options:['−3','0','2','−1'],
    answer:'−3',
    hint:'Further left means a smaller (more negative) value.',
    explanation:'On a number line: −3 < −1 < 0 < 2, so −3 is furthest left.' }),

  makeNum({ id:'g7m-integers-011', chapterId:'g7m-integers', difficulty:2,
    subsection:'number_line',
    question:'What integer is exactly HALFWAY between −4 and 8 on a number line?',
    answer:2, tolerance:0,
    hint:'Add the two values and divide by 2.',
    explanation:'Midpoint = (−4 + 8) ÷ 2 = 4 ÷ 2 = 2.' }),

  makeNum({ id:'g7m-integers-012', chapterId:'g7m-integers', difficulty:2,
    subsection:'operations',
    question:'Calculate: (−12) ÷ (−3)',
    answer:4, tolerance:0,
    hint:'Negative ÷ negative = positive.',
    explanation:'(−12) ÷ (−3) = +4. Two negatives divided give a positive.' }),

  makeMCQ({ id:'g7m-integers-013', chapterId:'g7m-integers', difficulty:3,
    subsection:'operations',
    question:'What is (−5) + (−8) − (−3)?',
    options:['−10','−16','−6','0'],
    answer:'−10',
    hint:'Subtracting a negative is the same as adding a positive.',
    explanation:'(−5) + (−8) = −13. Then −13 − (−3) = −13 + 3 = −10.' }),

  makeMCQ({ id:'g7m-integers-014', chapterId:'g7m-integers', difficulty:4,
    subsection:'operations',
    question:'At noon the temperature was 7°C. By midnight it had fallen by 11°C. What was the midnight temperature?',
    options:['18°C','4°C','−4°C','−11°C'],
    answer:'−4°C',
    hint:'7 − 11 = ?',
    explanation:'7 − 11 = −4°C. The temperature dropped below zero.' }),

  // ── g7m-operations ──────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-operations-006', chapterId:'g7m-operations', difficulty:2,
    subsection:'order_operations',
    question:'What is the value of 36 ÷ 4 + 2 × 3?',
    options:['33','15','12','21'],
    answer:'15',
    hint:'Division and multiplication before addition.',
    explanation:'36 ÷ 4 = 9; 2 × 3 = 6; then 9 + 6 = 15.' }),

  makeNum({ id:'g7m-operations-007', chapterId:'g7m-operations', difficulty:3,
    subsection:'order_operations',
    question:'Evaluate: 5 + 3² × 2 − 4',
    answer:19, tolerance:0,
    hint:'Indices first, then multiply, then add and subtract left to right.',
    explanation:'3² = 9; 9 × 2 = 18; 5 + 18 − 4 = 19.' }),

  makeMCQ({ id:'g7m-operations-008', chapterId:'g7m-operations', difficulty:1,
    subsection:'properties',
    question:'Which property is shown by (3 + 5) + 7 = 3 + (5 + 7)?',
    options:['Commutative','Associative','Distributive','Identity'],
    answer:'Associative',
    hint:'The GROUPING changes but the result stays the same.',
    explanation:'The associative property: (a + b) + c = a + (b + c). The grouping changes, not the order.' }),

  makeTF({ id:'g7m-operations-009', chapterId:'g7m-operations', difficulty:1,
    subsection:'properties',
    question:'8 × 0 = 8 demonstrates the identity property of multiplication.',
    answer:false,
    explanation:'8 × 0 = 0, not 8. The identity property states n × 1 = n. Multiplying by zero gives zero (zero property).' }),

  makeMCQ({ id:'g7m-operations-010', chapterId:'g7m-operations', difficulty:2,
    subsection:'brackets',
    question:'Evaluate: 100 − (20 + 3 × 4)',
    options:['68','72','332','60'],
    answer:'68',
    hint:'Inside the bracket: multiply first, then add.',
    explanation:'Inside: 3 × 4 = 12; 20 + 12 = 32. Then 100 − 32 = 68.' }),

  makeNum({ id:'g7m-operations-011', chapterId:'g7m-operations', difficulty:3,
    subsection:'brackets',
    question:'Evaluate: (15 − 3) × (8 + 4) ÷ 6',
    answer:24, tolerance:0,
    hint:'Work out each bracket first, then multiply and divide left to right.',
    explanation:'(15 − 3) = 12; (8 + 4) = 12. Then 12 × 12 ÷ 6 = 144 ÷ 6 = 24.' }),

  // ── g7m-indices ─────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-indices-006', chapterId:'g7m-indices', difficulty:1,
    subsection:'index_notation',
    question:'In the expression 7³, what is the BASE?',
    options:['3','7','21','343'],
    answer:'7',
    hint:'In aⁿ, a is the base and n is the index.',
    explanation:'In 7³, the base is 7 and the index (power) is 3. 7³ = 7 × 7 × 7 = 343.' }),

  makeTF({ id:'g7m-indices-007', chapterId:'g7m-indices', difficulty:1,
    subsection:'index_notation',
    question:'Any non-zero number raised to the power 0 equals 1.',
    answer:true,
    explanation:'n⁰ = 1 for any non-zero n. For example, 5⁰ = 1 and 100⁰ = 1.' }),

  makeMCQ({ id:'g7m-indices-008', chapterId:'g7m-indices', difficulty:2,
    subsection:'prime_factorisation',
    question:'Which is the prime factorisation of 48?',
    options:['2⁴ × 3','2³ × 6','4 × 12','2³ × 3²'],
    answer:'2⁴ × 3',
    hint:'48 = 2 × 24 = 2 × 2 × 12 = …',
    explanation:'48 = 2 × 2 × 2 × 2 × 3 = 2⁴ × 3. Only prime bases are used.' }),

  makeNum({ id:'g7m-indices-009', chapterId:'g7m-indices', difficulty:3,
    subsection:'prime_factorisation',
    question:'Express 100 as a product of prime factors: 100 = 2? × 5². What is the index of 2?',
    answer:2, tolerance:0,
    hint:'100 = 4 × 25 = 2² × 5².',
    explanation:'100 = 2 × 2 × 5 × 5 = 2² × 5². The index of 2 is 2.' }),

  makeNum({ id:'g7m-indices-010', chapterId:'g7m-indices', difficulty:2,
    subsection:'evaluating_powers',
    question:'What is the value of 2⁶?',
    answer:64, tolerance:0,
    hint:'2⁶ = 2 × 2 × 2 × 2 × 2 × 2',
    explanation:'2¹=2, 2²=4, 2³=8, 2⁴=16, 2⁵=32, 2⁶=64.' }),

  makeMCQ({ id:'g7m-indices-011', chapterId:'g7m-indices', difficulty:3,
    subsection:'evaluating_powers',
    question:'Which is greater: 2⁵ or 4³?',
    options:['2⁵','4³','They are equal','Cannot compare'],
    answer:'4³',
    hint:'Calculate each value: 2⁵ = ? and 4³ = ?',
    explanation:'2⁵ = 32. 4³ = 64. Since 64 > 32, 4³ is greater.' }),

  // ── g7m-factors ─────────────────────────────────────────────────────────
  makeTF({ id:'g7m-factors-006', chapterId:'g7m-factors', difficulty:1,
    subsection:'divisibility',
    question:'342 is divisible by 6.',
    answer:true,
    explanation:'Divisible by 6 requires divisibility by both 2 and 3. 342 is even ✓; digit sum 3+4+2 = 9 is divisible by 3 ✓. So 342 ÷ 6 = 57 ✓.' }),

  makeMCQ({ id:'g7m-factors-007', chapterId:'g7m-factors', difficulty:2,
    subsection:'divisibility',
    question:'Which of these is divisible by 7?',
    options:['44','49','52','58'],
    answer:'49',
    hint:'7 × 7 = 49.',
    explanation:'49 ÷ 7 = 7 exactly. 44, 52 and 58 are not multiples of 7.' }),

  makeNum({ id:'g7m-factors-008', chapterId:'g7m-factors', difficulty:2,
    subsection:'hcf_lcm',
    question:'Find the LCM of 8 and 12.',
    answer:24, tolerance:0,
    hint:'List multiples of each number until you find the first in common.',
    explanation:'Multiples of 8: 8, 16, 24 … Multiples of 12: 12, 24 … LCM = 24.' }),

  makeMCQ({ id:'g7m-factors-009', chapterId:'g7m-factors', difficulty:3,
    subsection:'hcf_lcm',
    question:'Two bells ring every 4 minutes and 6 minutes respectively. They ring together now. After how many minutes will they next ring together?',
    options:['10','12','18','24'],
    answer:'12',
    hint:'Find the LCM of 4 and 6.',
    explanation:'LCM(4, 6) = 12. The bells ring together again after 12 minutes.' }),

  makeNum({ id:'g7m-factors-010', chapterId:'g7m-factors', difficulty:3,
    subsection:'prime_factors',
    question:'Using prime factorisation (24 = 2³ × 3 and 36 = 2² × 3²), find the HCF of 24 and 36.',
    answer:12, tolerance:0,
    hint:'HCF = product of common prime factors with LOWEST powers.',
    explanation:'Common factors with lowest powers: 2² × 3 = 4 × 3 = 12.' }),

  makeMCQ({ id:'g7m-factors-011', chapterId:'g7m-factors', difficulty:2,
    subsection:'prime_factors',
    question:'How many DISTINCT prime factors does 60 have? (60 = 2² × 3 × 5)',
    options:['2','3','4','6'],
    answer:'3',
    hint:'Count the different prime numbers used, ignoring their powers.',
    explanation:'60 = 2² × 3 × 5. The distinct prime factors are 2, 3 and 5 — that is 3.' }),

  // ── g7m-fractions ───────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-fractions-006', chapterId:'g7m-fractions', difficulty:2,
    subsection:'comparing_fractions',
    question:'Which fraction is BETWEEN ⅓ and ½?',
    options:['¼','⅔','2/5','3/4'],
    answer:'2/5',
    hint:'Convert to thirtieths: ⅓=10/30, ½=15/30.',
    explanation:'In thirtieths: ⅓=10/30, 2/5=12/30, ½=15/30. Since 10 < 12 < 15, 2/5 lies between ⅓ and ½.' }),

  makeMCQ({ id:'g7m-fractions-007', chapterId:'g7m-fractions', difficulty:2,
    subsection:'comparing_fractions',
    question:'Which list is in DESCENDING order (largest first)?',
    options:['½, ⅓, ¼','¼, ⅓, ½','⅓, ½, ¼','½, ¼, ⅓'],
    answer:'½, ⅓, ¼',
    hint:'Convert to twelfths: ½=6/12, ⅓=4/12, ¼=3/12.',
    explanation:'In twelfths: ½=6/12, ⅓=4/12, ¼=3/12. Descending: 6 > 4 > 3, so ½ > ⅓ > ¼.' }),

  makeMCQ({ id:'g7m-fractions-008', chapterId:'g7m-fractions', difficulty:1,
    subsection:'converting',
    question:'Convert 0.6 to a fraction in its simplest form.',
    options:['6/10','3/5','3/4','6/8'],
    answer:'3/5',
    hint:'0.6 = 6/10. Simplify by dividing both by 2.',
    explanation:'0.6 = 6/10. HCF of 6 and 10 is 2. 6/10 = 3/5.' }),

  makeNum({ id:'g7m-fractions-009', chapterId:'g7m-fractions', difficulty:2,
    subsection:'converting',
    question:'Convert 7/4 to a mixed number. Type the WHOLE NUMBER part only.',
    answer:1, tolerance:0,
    hint:'7 ÷ 4 = 1 remainder 3, so 7/4 = 1¾.',
    explanation:'7 ÷ 4 = 1 with remainder 3. So 7/4 = 1¾. The whole number part is 1.' }),

  makeMCQ({ id:'g7m-fractions-010', chapterId:'g7m-fractions', difficulty:2,
    subsection:'operations_fractions',
    question:'Calculate ⅔ − ⅙.',
    options:['½','⅓','¼','⅙'],
    answer:'½',
    hint:'Convert ⅔ to sixths first: ⅔ = 4/6.',
    explanation:'⅔ = 4/6. 4/6 − 1/6 = 3/6 = ½.' }),

  makeMCQ({ id:'g7m-fractions-011', chapterId:'g7m-fractions', difficulty:3,
    subsection:'operations_fractions',
    question:'What is 1½ × 2⅓?',
    options:['3½','3⅙','2⅚','4'],
    answer:'3½',
    hint:'Convert to improper fractions: 3/2 × 7/3.',
    explanation:'1½ = 3/2; 2⅓ = 7/3. Multiply: (3×7)/(2×3) = 21/6 = 7/2 = 3½.' }),

  // ── g7m-percentages ─────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-percentages-006', chapterId:'g7m-percentages', difficulty:1,
    subsection:'percent_basics',
    question:'What is 50% as a fraction in its simplest form?',
    options:['50/100','5/10','1/2','5/9'],
    answer:'1/2',
    hint:'50/100 — divide both by 50.',
    explanation:'50% = 50/100 = 1/2.' }),

  makeTF({ id:'g7m-percentages-007', chapterId:'g7m-percentages', difficulty:1,
    subsection:'percent_basics',
    question:'0.35 is the same as 35%.',
    answer:true,
    explanation:'Multiply a decimal by 100 to get the percentage. 0.35 × 100 = 35%.' }),

  makeNum({ id:'g7m-percentages-008', chapterId:'g7m-percentages', difficulty:2,
    subsection:'percent_quantity',
    question:'What is 15% of 80?',
    answer:12, tolerance:0,
    hint:'10% of 80 = 8, then 5% of 80 = 4.',
    explanation:'10% = 8. 5% = 4. 15% = 8 + 4 = 12.' }),

  makeMCQ({ id:'g7m-percentages-009', chapterId:'g7m-percentages', difficulty:2,
    subsection:'percent_quantity',
    question:'A class has 40 pupils and 60% are girls. How many boys are there?',
    options:['16','24','20','18'],
    answer:'16',
    hint:'Girls = 60% of 40. Boys = 40 − number of girls.',
    explanation:'Girls = 24. Boys = 40 − 24 = 16.' }),

  makeNum({ id:'g7m-percentages-010', chapterId:'g7m-percentages', difficulty:3,
    subsection:'percent_problems',
    question:'A price increased by 25% to become Rs 6,000. What was the original price in rupees?',
    answer:4800, tolerance:0,
    hint:'Rs 6,000 = 125% of original. Divide by 1.25.',
    explanation:'125% of original = 6,000. Original = 6,000 ÷ 1.25 = Rs 4,800.' }),

  makeMCQ({ id:'g7m-percentages-011', chapterId:'g7m-percentages', difficulty:4,
    subsection:'percent_problems',
    question:'A trader buys mangoes at Rs 50 each and sells them at Rs 65 each. What is the profit percentage?',
    options:['15%','25%','30%','35%'],
    answer:'30%',
    hint:'Profit % = (profit ÷ cost price) × 100.',
    explanation:'Profit = Rs 15. Profit % = (15 ÷ 50) × 100 = 30%.' }),

  // ── g7m-ratio ───────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-ratio-006', chapterId:'g7m-ratio', difficulty:1,
    subsection:'simplifying_ratio',
    question:'Simplify the ratio 20 : 35.',
    options:['4 : 7','5 : 7','4 : 5','2 : 7'],
    answer:'4 : 7',
    hint:'HCF of 20 and 35 is 5.',
    explanation:'20 ÷ 5 = 4, 35 ÷ 5 = 7. Simplified ratio: 4 : 7.' }),

  makeTF({ id:'g7m-ratio-007', chapterId:'g7m-ratio', difficulty:1,
    subsection:'simplifying_ratio',
    question:'The ratio 3 : 6 is equivalent to 1 : 2.',
    answer:true,
    explanation:'Dividing both parts of 3:6 by 3 gives 1:2. Equivalent ratios are formed by multiplying or dividing both parts by the same non-zero number.' }),

  makeNum({ id:'g7m-ratio-008', chapterId:'g7m-ratio', difficulty:2,
    subsection:'dividing_ratio',
    question:'Rs 480 is shared between Asha and Bala in the ratio 3 : 5. How many rupees does Asha receive?',
    answer:180, tolerance:0,
    hint:'Total parts = 8. Each part = 480 ÷ 8. Asha gets 3 parts.',
    explanation:'Each part = 60. Asha = 3 × 60 = Rs 180.' }),

  makeMCQ({ id:'g7m-ratio-009', chapterId:'g7m-ratio', difficulty:2,
    subsection:'proportion',
    question:'A recipe for 6 portions needs 300 g of flour. How much flour is needed for 10 portions?',
    options:['400 g','450 g','500 g','600 g'],
    answer:'500 g',
    hint:'Find flour per portion, then multiply by 10.',
    explanation:'Per portion = 300 ÷ 6 = 50 g. For 10: 50 × 10 = 500 g.' }),

  makeMCQ({ id:'g7m-ratio-010', chapterId:'g7m-ratio', difficulty:4,
    subsection:'proportion',
    question:'On a map, 2 cm represents 5 km. Two towns are 3.5 cm apart on the map. How far apart are they in real life?',
    options:['7 km','8 km','8.5 km','8.75 km'],
    answer:'8.75 km',
    hint:'Scale: 1 cm = 2.5 km. Multiply 3.5 × 2.5.',
    explanation:'1 cm = 2.5 km. 3.5 cm = 3.5 × 2.5 = 8.75 km.' }),

  // ── g7m-polygons ────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-polygons-006', chapterId:'g7m-polygons', difficulty:1,
    subsection:'classifying_polygons',
    question:'A polygon with ALL sides equal and ALL angles equal is called …',
    options:['Scalene','Irregular','Regular','Equidistant'],
    answer:'Regular',
    hint:'Both conditions must hold: equal sides AND equal angles.',
    explanation:'A regular polygon has all sides equal and all interior angles equal.' }),

  makeTF({ id:'g7m-polygons-007', chapterId:'g7m-polygons', difficulty:1,
    subsection:'classifying_polygons',
    question:'A trapezium has exactly ONE pair of parallel sides.',
    answer:true,
    explanation:'A trapezium has exactly one pair of parallel sides. A parallelogram has two pairs.' }),

  makeNum({ id:'g7m-polygons-008', chapterId:'g7m-polygons', difficulty:2,
    subsection:'angles_polygons',
    question:'What is the sum of interior angles of an octagon (8 sides) in degrees?',
    answer:1080, tolerance:0,
    hint:'Formula: (n − 2) × 180. Use n = 8.',
    explanation:'(8 − 2) × 180 = 6 × 180 = 1080°.' }),

  makeMCQ({ id:'g7m-polygons-009', chapterId:'g7m-polygons', difficulty:3,
    subsection:'angles_polygons',
    question:'Each exterior angle of a regular polygon is 36°. How many sides does it have?',
    options:['8','10','12','15'],
    answer:'10',
    hint:'Number of sides = 360° ÷ exterior angle.',
    explanation:'360 ÷ 36 = 10 sides.' }),

  makeNum({ id:'g7m-polygons-010', chapterId:'g7m-polygons', difficulty:3,
    subsection:'triangles_quadrilaterals',
    question:'In triangle PQR, angle P = 48° and angle Q = 67°. What is angle R in degrees?',
    answer:65, tolerance:0,
    hint:'Angles in a triangle sum to 180°.',
    explanation:'Angle R = 180 − 48 − 67 = 65°.' }),

  makeMCQ({ id:'g7m-polygons-011', chapterId:'g7m-polygons', difficulty:2,
    subsection:'triangles_quadrilaterals',
    question:'Which quadrilateral has one pair of parallel sides but is NOT a parallelogram?',
    options:['Rectangle','Rhombus','Trapezium','Square'],
    answer:'Trapezium',
    hint:'A parallelogram has TWO pairs of parallel sides.',
    explanation:'A trapezium has exactly one pair of parallel sides. Rectangles, rhombuses and squares all have two pairs.' }),

  // ── g7m-coordinates ─────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-coordinates-006', chapterId:'g7m-coordinates', difficulty:1,
    subsection:'plotting_points',
    question:'When plotting the point (3, 5), which number is the x-coordinate?',
    options:['5','3','8','0'],
    answer:'3',
    hint:'Coordinates are written (x, y). The first number is always x.',
    explanation:'In (3, 5), 3 is the x-coordinate (horizontal) and 5 is the y-coordinate (vertical).' }),

  makeMCQ({ id:'g7m-coordinates-007', chapterId:'g7m-coordinates', difficulty:2,
    subsection:'quadrants',
    question:'Point A(−5, −3) is reflected in the x-axis. What are the new coordinates?',
    options:['(5, −3)','(−5, 3)','(5, 3)','(−5, −3)'],
    answer:'(−5, 3)',
    hint:'Reflection in the x-axis: x stays the same, y changes sign.',
    explanation:'(−5, −3) reflected in the x-axis: x unchanged, y = +3. New point: (−5, 3).' }),

  makeMCQ({ id:'g7m-coordinates-008', chapterId:'g7m-coordinates', difficulty:3,
    subsection:'shapes_coordinates',
    question:'A rectangle has vertices A(1,1), B(5,1), C(5,4), D(1,4). What is its area in square units?',
    options:['12','16','20','8'],
    answer:'12',
    hint:'Width = B.x − A.x. Height = D.y − A.y.',
    explanation:'Width = 5−1 = 4. Height = 4−1 = 3. Area = 4 × 3 = 12 sq units.' }),

  // ── g7m-constructions ───────────────────────────────────────────────────
  makeMCQ({ id:'g7m-constructions-006', chapterId:'g7m-constructions', difficulty:1,
    subsection:'using_instruments',
    question:'A set square can be used directly to draw which angles?',
    options:['20° and 80°','30°, 60° or 90°','Any angle','55° and 35°'],
    answer:'30°, 60° or 90°',
    hint:'A set square is a fixed triangular tool with specific angle combinations.',
    explanation:'One type of set square gives 30°, 60°, 90°; another gives 45°, 45°, 90°. These are its built-in angles.' }),

  makeMCQ({ id:'g7m-constructions-007', chapterId:'g7m-constructions', difficulty:2,
    subsection:'parallel_perpendicular',
    question:'To draw a line parallel to a given line through a point, which tools are most useful?',
    options:['Protractor only','Compasses only','Ruler and set square','Dividers only'],
    answer:'Ruler and set square',
    hint:'The set square slides along the ruler while keeping the angle constant.',
    explanation:'A ruler acts as a guide while the set square is slid along it to draw lines at the same angle — producing parallel lines.' }),

  makeMCQ({ id:'g7m-constructions-008', chapterId:'g7m-constructions', difficulty:2,
    subsection:'bisecting',
    question:'When bisecting segment AB with compasses, the compass width must be set to …',
    options:['Less than half of AB','More than half of AB','Exactly half of AB','Equal to AB'],
    answer:'More than half of AB',
    hint:'If the arcs are too small, they will not cross each other.',
    explanation:'The compass must be set to MORE than half the length of AB so that arcs from A and B intersect above and below, marking the midpoint.' }),

  // ── g7m-symmetry ────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-symmetry-006', chapterId:'g7m-symmetry', difficulty:2,
    subsection:'lines_symmetry',
    question:'How many lines of symmetry does a regular pentagon have?',
    options:['3','4','5','10'],
    answer:'5',
    hint:'A regular polygon with n sides has n lines of symmetry.',
    explanation:'A regular pentagon has 5 sides and 5 lines of symmetry, each passing from a vertex to the midpoint of the opposite side.' }),

  makeMCQ({ id:'g7m-symmetry-007', chapterId:'g7m-symmetry', difficulty:2,
    subsection:'completing_figures',
    question:'The capital letter H has …',
    options:['No lines of symmetry','One line of symmetry','Two lines of symmetry','Four lines of symmetry'],
    answer:'Two lines of symmetry',
    hint:'H can be folded both vertically and horizontally to match.',
    explanation:'H has a vertical line of symmetry AND a horizontal line of symmetry — two in total.' }),

  makeNum({ id:'g7m-symmetry-008', chapterId:'g7m-symmetry', difficulty:2,
    subsection:'rotational_symmetry',
    question:'What is the order of rotational symmetry of a regular octagon?',
    answer:8, tolerance:0,
    hint:'A regular polygon with n sides has order n rotational symmetry.',
    explanation:'A regular octagon fits its outline every 360°÷8 = 45°, giving order 8.' }),

  // ── g7m-transformation ──────────────────────────────────────────────────
  makeMCQ({ id:'g7m-transformation-006', chapterId:'g7m-transformation', difficulty:2,
    subsection:'reflection',
    question:'Point Q(2, 5) is reflected in the x-axis. What are the coordinates of Q′?',
    options:['(−2, 5)','(2, −5)','(−2, −5)','(5, 2)'],
    answer:'(2, −5)',
    hint:'Reflection in the x-axis: x stays the same, y changes sign.',
    explanation:'(2, 5) reflected in the x-axis → (2, −5). x unchanged; y changes sign.' }),

  makeNum({ id:'g7m-transformation-007', chapterId:'g7m-transformation', difficulty:2,
    subsection:'translation',
    question:'Point A(4, 3) is translated by vector (−2, +5). What is the new y-coordinate?',
    answer:8, tolerance:0,
    hint:'Add the y-component of the vector to the y-coordinate.',
    explanation:'New y = 3 + 5 = 8. New x = 4 + (−2) = 2. New position: (2, 8).' }),

  makeMCQ({ id:'g7m-transformation-008', chapterId:'g7m-transformation', difficulty:2,
    subsection:'congruence',
    question:'Which transformation does NOT produce a congruent image?',
    options:['Reflection','Rotation','Translation','Enlargement'],
    answer:'Enlargement',
    hint:'Congruent shapes are the same size. Which transformation changes size?',
    explanation:'An enlargement changes the size of the shape, making the image similar but NOT congruent. Reflection, rotation and translation preserve both shape and size.' }),

  // ── g7m-mass ────────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-mass-006', chapterId:'g7m-mass', difficulty:1,
    subsection:'units_mass',
    question:'1 tonne = how many kilograms?',
    options:['100 kg','500 kg','1,000 kg','10,000 kg'],
    answer:'1,000 kg',
    hint:'Tonne is the largest common unit of mass.',
    explanation:'1 tonne = 1,000 kg. It is used for very heavy objects such as vehicles.' }),

  makeMCQ({ id:'g7m-mass-007', chapterId:'g7m-mass', difficulty:2,
    subsection:'converting_mass',
    question:'A sack weighs 2,500 g. What is this in kilograms?',
    options:['0.25 kg','2.5 kg','25 kg','250 kg'],
    answer:'2.5 kg',
    hint:'Divide by 1,000 to convert grams to kilograms.',
    explanation:'2,500 ÷ 1,000 = 2.5 kg.' }),

  makeMCQ({ id:'g7m-mass-008', chapterId:'g7m-mass', difficulty:4,
    subsection:'mass_problems',
    question:'A lorry can carry a maximum load of 2 tonnes. It carries 15 crates each of mass 120 kg. How many MORE kg can it carry?',
    options:['100 kg','200 kg','300 kg','400 kg'],
    answer:'200 kg',
    hint:'Current load = 15 × 120 kg. Maximum = 2,000 kg.',
    explanation:'15 × 120 = 1,800 kg. Maximum = 2,000 kg. Remaining = 2,000 − 1,800 = 200 kg.' }),

  // ── g7m-length ──────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-length-006', chapterId:'g7m-length', difficulty:1,
    subsection:'units_length',
    question:'How many millimetres are in 1 centimetre?',
    options:['1','10','100','1,000'],
    answer:'10',
    hint:'The prefix milli- means one thousandth; centi- means one hundredth.',
    explanation:'1 cm = 10 mm. To convert cm to mm, multiply by 10.' }),

  makeNum({ id:'g7m-length-007', chapterId:'g7m-length', difficulty:2,
    subsection:'perimeter',
    question:'An equilateral triangle has sides of 9 cm each. What is its perimeter in cm?',
    answer:27, tolerance:0,
    hint:'All three sides of an equilateral triangle are equal.',
    explanation:'Perimeter = 3 × 9 = 27 cm.' }),

  makeNum({ id:'g7m-length-008', chapterId:'g7m-length', difficulty:3,
    subsection:'distance_problems',
    question:'A farmer walks all the way round a field 450 m × 280 m, twice. How far in km does he walk?',
    answer:2.92, tolerance:0.01,
    hint:'Perimeter = 2×(450+280). Double it. Divide by 1,000.',
    explanation:'Perimeter = 2 × 730 = 1,460 m. Twice = 2,920 m = 2.92 km.' }),

  // ── g7m-area ────────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-area-006', chapterId:'g7m-area', difficulty:2,
    subsection:'rectangle_area',
    question:'A square has a perimeter of 20 cm. What is its area?',
    options:['16 cm²','20 cm²','25 cm²','100 cm²'],
    answer:'25 cm²',
    hint:'Side = perimeter ÷ 4. Area = side².',
    explanation:'Side = 20 ÷ 4 = 5 cm. Area = 5² = 25 cm².' }),

  makeNum({ id:'g7m-area-007', chapterId:'g7m-area', difficulty:2,
    subsection:'triangle_area',
    question:'A right-angled triangle has legs of 6 cm and 8 cm. What is its area in cm²?',
    answer:24, tolerance:0,
    hint:'Area = ½ × base × height. For a right triangle the two legs are the base and height.',
    explanation:'Area = ½ × 6 × 8 = 24 cm².' }),

  makeMCQ({ id:'g7m-area-008', chapterId:'g7m-area', difficulty:3,
    subsection:'compound_shapes',
    question:'A cross shape is made from two rectangles, each 6 cm × 2 cm, that overlap in a 2 cm × 2 cm square. What is the area of the cross?',
    options:['24 cm²','20 cm²','16 cm²','28 cm²'],
    answer:'20 cm²',
    hint:'Add both rectangles, then subtract the shared overlap.',
    explanation:'Each rectangle = 12 cm². Overlap = 4 cm². Total = 12 + 12 − 4 = 20 cm².' }),

  // ── g7m-time ────────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-time-006', chapterId:'g7m-time', difficulty:1,
    subsection:'reading_time',
    question:'What is 09:05 in 12-hour clock format?',
    options:['9:05 pm','9:05 am','21:05','12:05 am'],
    answer:'9:05 am',
    hint:'Times before 12:00 noon just need "am" added.',
    explanation:'09:05 is before noon. In 12-hour format: 9:05 am.' }),

  makeNum({ id:'g7m-time-007', chapterId:'g7m-time', difficulty:2,
    subsection:'time_intervals',
    question:'A journey starts at 22:45 on Monday and arrives at 06:15 on Tuesday. How long is the journey in minutes?',
    answer:450, tolerance:0,
    hint:'22:45 to midnight = 75 min; midnight to 06:15 = 375 min.',
    explanation:'22:45 to 00:00 = 75 min. 00:00 to 06:15 = 375 min. Total = 450 min (7 h 30 min).' }),

  makeMCQ({ id:'g7m-time-008', chapterId:'g7m-time', difficulty:3,
    subsection:'timetables',
    question:'Science starts at 10:25 and lasts 50 minutes. When does it end?',
    options:['11:10','11:15','11:20','11:25'],
    answer:'11:15',
    hint:'10:25 + 50 min: add 35 min to reach 11:00, then 15 more.',
    explanation:'10:25 + 35 min = 11:00. 11:00 + 15 min = 11:15.' }),

  // ── g7m-speed ───────────────────────────────────────────────────────────
  makeNum({ id:'g7m-speed-006', chapterId:'g7m-speed', difficulty:2,
    subsection:'speed_formula',
    question:'How many hours does it take to travel 150 km at 50 km/h?',
    answer:3, tolerance:0,
    hint:'Time = Distance ÷ Speed.',
    explanation:'Time = 150 ÷ 50 = 3 hours.' }),

  makeMCQ({ id:'g7m-speed-007', chapterId:'g7m-speed', difficulty:2,
    subsection:'unit_conversion',
    question:'10 m/s is equivalent to how many km/h?',
    options:['10 km/h','36 km/h','100 km/h','3.6 km/h'],
    answer:'36 km/h',
    hint:'Multiply m/s by 3.6 to convert to km/h.',
    explanation:'1 m/s = 3.6 km/h. 10 m/s = 10 × 3.6 = 36 km/h.' }),

  makeMCQ({ id:'g7m-speed-008', chapterId:'g7m-speed', difficulty:4,
    subsection:'distance_time',
    question:'Two towns are 120 km apart. Car A leaves Town 1 at 60 km/h and Car B leaves Town 2 at 40 km/h, heading towards each other simultaneously. How many minutes until they meet?',
    options:['60 min','72 min','80 min','90 min'],
    answer:'72 min',
    hint:'Combined speed = 60 + 40 km/h. Time = 120 ÷ combined speed.',
    explanation:'Combined speed = 100 km/h. Time = 120 ÷ 100 = 1.2 h = 72 minutes.' }),

  // ── g7m-money ───────────────────────────────────────────────────────────
  makeNum({ id:'g7m-money-006', chapterId:'g7m-money', difficulty:2,
    subsection:'money_operations',
    question:'Goods cost Rs 143.70. Mia pays with Rs 200. What is her change in rupees?',
    answer:56.3, tolerance:0.01,
    hint:'Change = 200 − 143.70.',
    explanation:'200.00 − 143.70 = Rs 56.30.' }),

  makeMCQ({ id:'g7m-money-007', chapterId:'g7m-money', difficulty:3,
    subsection:'profit_loss',
    question:'A watch is sold for Rs 630 at a LOSS of 10%. What was the cost price?',
    options:['Rs 567','Rs 693','Rs 700','Rs 630'],
    answer:'Rs 700',
    hint:'Selling price = 90% of cost price. Divide Rs 630 by 0.9.',
    explanation:'90% of cost = 630. Cost = 630 ÷ 0.9 = Rs 700.' }),

  makeMCQ({ id:'g7m-money-008', chapterId:'g7m-money', difficulty:3,
    subsection:'currency',
    question:'If 1 USD = Rs 45, how many USD can you get for Rs 1,350?',
    options:['25','30','35','40'],
    answer:'30',
    hint:'Divide rupees by the exchange rate.',
    explanation:'1,350 ÷ 45 = 30 USD.' }),

  // ── g7m-algebra ─────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-algebra-006', chapterId:'g7m-algebra', difficulty:2,
    subsection:'writing_expressions',
    question:'A bag of rice costs Rs r. Flour costs Rs 10 less per bag. Write an expression for the total cost of 3 bags of rice and 2 bags of flour.',
    options:['5r − 10','5r − 20','3r + 2r − 10','5r + 20'],
    answer:'5r − 20',
    hint:'Flour per bag = r − 10. Total = 3r + 2(r − 10).',
    explanation:'3r + 2(r − 10) = 3r + 2r − 20 = 5r − 20.' }),

  makeMCQ({ id:'g7m-algebra-007', chapterId:'g7m-algebra', difficulty:2,
    subsection:'simplifying',
    question:'Simplify: 5x + 3y − 2x + y',
    options:['3x + 4y','7x + 4y','3x + 2y','5x + 4y'],
    answer:'3x + 4y',
    hint:'Collect x-terms and y-terms separately.',
    explanation:'x-terms: 5x − 2x = 3x. y-terms: 3y + y = 4y. Answer: 3x + 4y.' }),

  makeNum({ id:'g7m-algebra-008', chapterId:'g7m-algebra', difficulty:3,
    subsection:'substitution',
    question:'If p = 2 and q = −3, find the value of p² − 2q.',
    answer:10, tolerance:0,
    hint:'p² = 4. Then 4 − 2 × (−3) = ?',
    explanation:'p² = 4; 2q = −6; p² − 2q = 4 − (−6) = 4 + 6 = 10.' }),

  // ── g7m-equations ───────────────────────────────────────────────────────
  makeNum({ id:'g7m-equations-006', chapterId:'g7m-equations', difficulty:2,
    subsection:'solving_equations',
    question:'Solve: 4x + 3 = 19. What is x?',
    answer:4, tolerance:0,
    hint:'Subtract 3 from both sides, then divide by 4.',
    explanation:'4x + 3 = 19 → 4x = 16 → x = 4.' }),

  makeMCQ({ id:'g7m-equations-007', chapterId:'g7m-equations', difficulty:3,
    subsection:'solving_equations',
    question:'Solve: 3(x + 2) = 21',
    options:['x = 5','x = 7','x = 9','x = 6'],
    answer:'x = 5',
    hint:'Divide both sides by 3 first, then subtract 2.',
    explanation:'3(x+2) = 21 → x+2 = 7 → x = 5.' }),

  makeMCQ({ id:'g7m-equations-008', chapterId:'g7m-equations', difficulty:3,
    subsection:'forming_equations',
    question:'Three consecutive integers add up to 48. Which equation represents this?',
    options:['3n = 48','n + (n+1) + (n+2) = 48','n + n + 2n = 48','n(n+1)(n+2) = 48'],
    answer:'n + (n+1) + (n+2) = 48',
    hint:'Let the first integer be n. The next two are n+1 and n+2.',
    explanation:'n + (n+1) + (n+2) = 3n + 3 = 48, so n = 15. The three integers are 15, 16, 17.' }),

  makeMCQ({ id:'g7m-equations-009', chapterId:'g7m-equations', difficulty:4,
    subsection:'word_equations',
    question:'A number is doubled and then 9 is subtracted. The result is 15. What is the number?',
    options:['10','12','13','15'],
    answer:'12',
    hint:'Form the equation: 2n − 9 = 15.',
    explanation:'2n − 9 = 15 → 2n = 24 → n = 12.' }),

  // ── g7m-sets ────────────────────────────────────────────────────────────
  makeMCQ({ id:'g7m-sets-006', chapterId:'g7m-sets', difficulty:1,
    subsection:'set_notation',
    question:'What does the symbol ∩ represent?',
    options:['Union','Intersection','Subset','Element of'],
    answer:'Intersection',
    hint:'∩ is used for the overlapping region of two sets.',
    explanation:'∩ denotes intersection: A ∩ B is the set of elements belonging to BOTH A and B.' }),

  makeMCQ({ id:'g7m-sets-007', chapterId:'g7m-sets', difficulty:2,
    subsection:'venn_diagrams',
    question:'In a class, 12 students like football, 8 like cricket, and 3 like both. How many students like at least one sport?',
    options:['17','20','23','3'],
    answer:'17',
    hint:'n(F ∪ C) = n(F) + n(C) − n(F ∩ C).',
    explanation:'n(F ∪ C) = 12 + 8 − 3 = 17.' }),

  makeTF({ id:'g7m-sets-008', chapterId:'g7m-sets', difficulty:2,
    subsection:'set_types',
    question:'The empty set is a subset of every set.',
    answer:true,
    explanation:'The empty set (∅) is a subset of EVERY set, including itself. This is a fundamental rule of set theory.' }),

  // ── g7m-statistics ──────────────────────────────────────────────────────
  makeNum({ id:'g7m-statistics-006', chapterId:'g7m-statistics', difficulty:2,
    subsection:'data_tables',
    question:'A frequency table shows Red=12, Blue=18, Green=9, Yellow=6. What is the total frequency?',
    answer:45, tolerance:0,
    hint:'Add all the frequencies.',
    explanation:'12 + 18 + 9 + 6 = 45.' }),

  makeMCQ({ id:'g7m-statistics-007', chapterId:'g7m-statistics', difficulty:2,
    subsection:'bar_charts',
    question:'A bar chart shows 24 students chose Maths and 16 chose English. The Maths bar is how many times taller than the English bar?',
    options:['1.5 times','2 times','3 times','8 times'],
    answer:'1.5 times',
    hint:'Divide 24 by 16.',
    explanation:'24 ÷ 16 = 1.5. The Maths bar is 1.5 times the height of the English bar.' }),

  makeMCQ({ id:'g7m-statistics-008', chapterId:'g7m-statistics', difficulty:3,
    subsection:'mean',
    question:'A student scores 72, 85, 68, 91 and 74 in five tests. What is the mean score?',
    options:['76','78','80','82'],
    answer:'78',
    hint:'Mean = total ÷ number of scores.',
    explanation:'Total = 72+85+68+91+74 = 390. Mean = 390 ÷ 5 = 78.' })

);
