'use strict';
// Grade 7 Science — Expanded questions, all 14 chapters
// IDs: g7s-<chapter>-007 onwards (ch01 ended at -006)

(function () {

STATIC_QUESTIONS.push(

  // ── g7s-inquiry ─────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-inquiry-007', chapterId:'g7s-inquiry', difficulty:1, subsection:'lab_safety',
    question:'What should you do with long hair before starting a laboratory experiment involving a Bunsen burner?',
    options:['Tie it back securely','Leave it loose','Wet it with water','Cut it short'],
    answer:'Tie it back securely',
    hint:'Loose hair near a flame is a fire hazard.',
    explanation:'Long hair must be <b>tied back securely</b> before working near flames or moving equipment to prevent it from catching fire or becoming tangled.' }),

  makeMCQ({ id:'g7s-inquiry-008', chapterId:'g7s-inquiry', difficulty:1, subsection:'lab_safety',
    question:'You notice a broken glass beaker on the laboratory bench. What should you do first?',
    options:['Tell your teacher immediately','Pick it up with your hands','Sweep it away with a cloth','Leave it and continue working'],
    answer:'Tell your teacher immediately',
    hint:'Broken glass is sharp and dangerous — always inform an adult.',
    explanation:'You should <b>tell your teacher immediately</b>. Broken glass must be cleaned up safely by an adult using appropriate tools. Never handle broken glass with bare hands.' }),

  makeMCQ({ id:'g7s-inquiry-009', chapterId:'g7s-inquiry', difficulty:2, subsection:'lab_safety',
    question:'Why should you never eat or drink in the laboratory?',
    options:['Chemicals could contaminate food or drinks and cause poisoning','It wastes experiment time','The teacher will be angry','Food smells disturb experiments'],
    answer:'Chemicals could contaminate food or drinks and cause poisoning',
    hint:'Even tiny amounts of some chemicals can be very harmful if swallowed.',
    explanation:'Eating or drinking in the lab risks <b>chemical contamination</b>. Chemicals on surfaces, in the air or on your hands could transfer to food or drink and cause serious poisoning.' }),

  makeMCQ({ id:'g7s-inquiry-010', chapterId:'g7s-inquiry', difficulty:2, subsection:'investigations',
    question:'In a scientific investigation, what is a hypothesis?',
    options:['A testable prediction or explanation for what you expect to happen','The final conclusion of the experiment','The equipment list','A graph of the results'],
    answer:'A testable prediction or explanation for what you expect to happen',
    hint:'It usually takes the form "If … then … because …".',
    explanation:'A <b>hypothesis</b> is a testable prediction made before the experiment. It states what you expect to happen and suggests a reason, and it must be able to be supported or disproved by evidence.' }),

  makeMCQ({ id:'g7s-inquiry-011', chapterId:'g7s-inquiry', difficulty:2, subsection:'investigations',
    question:'Which of the following is a controlled variable?',
    options:['A variable kept the same throughout the experiment','The variable you deliberately change','The variable you measure','The variable that is unpredictable'],
    answer:'A variable kept the same throughout the experiment',
    hint:'Controlled variables ensure the test is fair.',
    explanation:'A <b>controlled variable</b> is one that is kept the same throughout the experiment so it cannot influence the results. Only the independent variable is changed, making the test fair.' }),

  makeMCQ({ id:'g7s-inquiry-012', chapterId:'g7s-inquiry', difficulty:3, subsection:'investigations',
    question:'A student investigates how the height of a ramp affects the speed of a toy car. She keeps the same car, the same surface and the same release point each time. Why?',
    options:['To make it a fair test by keeping all other variables constant','Because she only has one car','To save time','The teacher told her to'],
    answer:'To make it a fair test by keeping all other variables constant',
    hint:'Changing only one variable at a time isolates its effect.',
    explanation:'By keeping everything else constant, the student ensures a <b>fair test</b> — any difference in the car\'s speed must be due to ramp height alone, not other factors.' }),

  makeMCQ({ id:'g7s-inquiry-013', chapterId:'g7s-inquiry', difficulty:1, subsection:'data_recording',
    question:'What does the term "anomalous result" mean?',
    options:['A result that does not fit the pattern of the other results','The most accurate result','The average of all results','The first result recorded'],
    answer:'A result that does not fit the pattern of the other results',
    hint:'It stands out as unusually high or low compared to the others.',
    explanation:'An <b>anomalous result</b> is one that does not fit the overall pattern or trend. It may be caused by an experimental error and should be identified and often excluded from the average.' }),

  makeMCQ({ id:'g7s-inquiry-014', chapterId:'g7s-inquiry', difficulty:2, subsection:'data_recording',
    question:'A student records the following volumes when measuring the same object three times: 23.5 cm³, 23.6 cm³, 23.4 cm³. What is the mean (average) volume?',
    options:['23.5 cm³','23.6 cm³','23.4 cm³','70.5 cm³'],
    answer:'23.5 cm³',
    hint:'Add all values then divide by the number of readings.',
    explanation:'Mean = (23.5 + 23.6 + 23.4) ÷ 3 = 70.5 ÷ 3 = <b>23.5 cm³</b>. Taking an average of repeated readings improves reliability.' }),

  makeMCQ({ id:'g7s-inquiry-015', chapterId:'g7s-inquiry', difficulty:2, subsection:'data_recording',
    question:'Which type of graph is best for showing how temperature changes over time?',
    options:['Line graph','Bar chart','Pie chart','Pictogram'],
    answer:'Line graph',
    hint:'It shows continuous change over time.',
    explanation:'A <b>line graph</b> is best for showing continuous data over time. Points are plotted and joined by a line to show how one variable (temperature) changes as another (time) increases.' }),

  makeMCQ({ id:'g7s-inquiry-016', chapterId:'g7s-inquiry', difficulty:3, subsection:'data_recording',
    question:'A student\'s experiment gives results that do not support her hypothesis. What should she do?',
    options:['Analyse the data honestly and reconsider the hypothesis','Change the results to fit the hypothesis','Ignore the results and write what she expected','Repeat the experiment until she gets the right answer'],
    answer:'Analyse the data honestly and reconsider the hypothesis',
    hint:'In science, disproving a hypothesis is just as valuable as proving one.',
    explanation:'Good science requires <b>honesty</b>. If results do not support the hypothesis, the scientist should analyse why and revise the hypothesis. Falsifying data is never acceptable.' }),

  // ── g7s-measurement ─────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-measurement-007', chapterId:'g7s-measurement', difficulty:1, subsection:'si_units',
    question:'What is the SI unit for measuring time?',
    options:['Second (s)','Minute (min)','Hour (h)','Millisecond (ms)'],
    answer:'Second (s)',
    hint:'This is the base unit — all others are derived from it.',
    explanation:'The SI base unit for time is the <b>second (s)</b>. Minutes and hours are derived units commonly used in everyday life but seconds are the scientific standard.' }),

  makeMCQ({ id:'g7s-measurement-008', chapterId:'g7s-measurement', difficulty:1, subsection:'si_units',
    question:'How many centimetres are in one metre?',
    options:['100','10','1000','1'],
    answer:'100',
    hint:'The prefix "centi" means one hundredth.',
    explanation:'There are <b>100</b> centimetres in 1 metre. The prefix "centi" (from Latin centum) means one hundredth, so 1 cm = 0.01 m.' }),

  makeMCQ({ id:'g7s-measurement-009', chapterId:'g7s-measurement', difficulty:1, subsection:'si_units',
    question:'What does the prefix "kilo" mean in SI units?',
    options:['1000 times','100 times','One thousandth','One hundredth'],
    answer:'1000 times',
    hint:'A kilogram is 1000 grams; a kilometre is 1000 metres.',
    explanation:'The prefix <b>kilo</b> means 1000 times the base unit. So 1 kilogram = 1000 g and 1 kilometre = 1000 m.' }),

  makeMCQ({ id:'g7s-measurement-010', chapterId:'g7s-measurement', difficulty:2, subsection:'measuring_instruments',
    question:'When reading the volume of liquid in a measuring cylinder, where should you read the level?',
    options:['At the bottom of the curved surface (meniscus)','At the top of the curved surface','At the middle of the curve','From above the cylinder'],
    answer:'At the bottom of the curved surface (meniscus)',
    hint:'The meniscus is the curved surface of the liquid.',
    explanation:'You should read the volume <b>at the bottom of the meniscus</b> (the lowest point of the curved liquid surface) with your eye at the same level. Reading from the top gives an incorrect (too high) reading.' }),

  makeMCQ({ id:'g7s-measurement-011', chapterId:'g7s-measurement', difficulty:2, subsection:'measuring_instruments',
    question:'Which instrument is used to measure mass accurately in a laboratory?',
    options:['Electronic balance','Spring balance','Ruler','Measuring cylinder'],
    answer:'Electronic balance',
    hint:'This instrument measures the amount of matter in an object.',
    explanation:'An <b>electronic balance</b> measures mass accurately. A spring balance measures force (weight), not mass directly, and is less precise for laboratory work.' }),

  makeMCQ({ id:'g7s-measurement-012', chapterId:'g7s-measurement', difficulty:2, subsection:'measuring_instruments',
    question:'Why is it important to check that a balance reads zero before measuring mass?',
    options:['To ensure the measurement starts from zero so the reading is accurate','To warm up the balance','Because the teacher requires it','To save electricity'],
    answer:'To ensure the measurement starts from zero so the reading is accurate',
    hint:'Any initial reading other than zero will add to your measurement.',
    explanation:'<b>Zeroing (taring) the balance</b> before use ensures that any reading shows only the mass of the object being measured. An un-zeroed balance gives a systematic error in every reading.' }),

  makeMCQ({ id:'g7s-measurement-013', chapterId:'g7s-measurement', difficulty:3, subsection:'calculating_measurements',
    question:'A swimming pool is 25 m long, 10 m wide and 2 m deep. What is its volume?',
    options:['500 m³','250 m³','37 m³','5000 m³'],
    answer:'500 m³',
    hint:'Volume = length × width × depth.',
    explanation:'Volume = 25 × 10 × 2 = <b>500 m³</b>. The formula for the volume of a cuboid (rectangular prism) is length × width × height.' }),

  makeMCQ({ id:'g7s-measurement-014', chapterId:'g7s-measurement', difficulty:3, subsection:'calculating_measurements',
    question:'A circle has a radius of 7 cm. What is its area? (Use π ≈ 3.14)',
    options:['153.86 cm²','43.96 cm','21.98 cm²','49 cm²'],
    answer:'153.86 cm²',
    hint:'Area of a circle = π × radius².',
    explanation:'Area = π × r² = 3.14 × 7² = 3.14 × 49 = <b>153.86 cm²</b>.' }),

  makeMCQ({ id:'g7s-measurement-015', chapterId:'g7s-measurement', difficulty:2, subsection:'calculating_measurements',
    question:'A student measures a table as 1.5 m long. How many millimetres is this?',
    options:['1500 mm','150 mm','15 mm','15 000 mm'],
    answer:'1500 mm',
    hint:'1 m = 1000 mm; multiply by 1000.',
    explanation:'1.5 m × 1000 = <b>1500 mm</b>. There are 1000 millimetres in 1 metre, so multiply metres by 1000 to convert.' }),

  makeMCQ({ id:'g7s-measurement-016', chapterId:'g7s-measurement', difficulty:2, subsection:'si_units',
    question:'What is the SI unit for temperature in scientific work?',
    options:['Kelvin (K)','Celsius (°C)','Fahrenheit (°F)','Joule (J)'],
    answer:'Kelvin (K)',
    hint:'This scale starts at absolute zero — the coldest possible temperature.',
    explanation:'The SI unit for temperature is the <b>Kelvin (K)</b>. Celsius (°C) is used in everyday science; to convert, K = °C + 273. Absolute zero (0 K) is the lowest possible temperature.' }),

  // ── g7s-cells ───────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-cells-007', chapterId:'g7s-cells', difficulty:1, subsection:'cell_characteristics',
    question:'Which of these is NOT a characteristic of living things?',
    options:['Moving only when blown by wind','Reproducing','Responding to stimuli','Excreting waste'],
    answer:'Moving only when blown by wind',
    hint:'True movement in living things is self-generated.',
    explanation:'<b>Moving only when blown by wind</b> is not a characteristic of living things — it is passive movement caused by an external force. Living things move on their own (e.g. plants grow towards light).' }),

  makeMCQ({ id:'g7s-cells-008', chapterId:'g7s-cells', difficulty:1, subsection:'cell_characteristics',
    question:'A single-celled organism that carries out all life processes on its own is called ___.',
    options:['Unicellular','Multicellular','Tissue','Organ'],
    answer:'Unicellular',
    hint:'"Uni" means one.',
    explanation:'A <b>unicellular</b> organism consists of a single cell that carries out all the functions of life (feeding, respiration, excretion, reproduction). Examples include Amoeba and bacteria.' }),

  makeMCQ({ id:'g7s-cells-009', chapterId:'g7s-cells', difficulty:2, subsection:'cell_parts',
    question:'What is the function of mitochondria in a cell?',
    options:['To release energy from food through respiration','To store water','To control cell division','To make proteins'],
    answer:'To release energy from food through respiration',
    hint:'They are called the "powerhouse" of the cell.',
    explanation:'<b>Mitochondria</b> are the site of aerobic respiration, where glucose is broken down using oxygen to release energy (ATP) for all cell activities. They are often called the powerhouse of the cell.' }),

  makeMCQ({ id:'g7s-cells-010', chapterId:'g7s-cells', difficulty:2, subsection:'cell_parts',
    question:'Which organelle is responsible for protein synthesis (making proteins)?',
    options:['Ribosome','Nucleus','Mitochondrion','Vacuole'],
    answer:'Ribosome',
    hint:'Proteins are assembled here using instructions from the DNA.',
    explanation:'<b>Ribosomes</b> are small organelles found in the cytoplasm where proteins are made. They read the instructions (mRNA) from the nucleus and assemble amino acids into protein chains.' }),

  makeMCQ({ id:'g7s-cells-011', chapterId:'g7s-cells', difficulty:2, subsection:'cell_parts',
    question:'What does the vacuole do in a plant cell?',
    options:['Stores water and sap, helping to keep the cell firm','Produces energy','Controls cell division','Makes food by photosynthesis'],
    answer:'Stores water and sap, helping to keep the cell firm',
    hint:'A full vacuole pushes against the cell wall — this is called turgor pressure.',
    explanation:'The <b>vacuole</b> in plant cells stores water, salts and sugars. When full, it pushes outward against the cell wall, creating turgor pressure that keeps plant cells firm and plants upright.' }),

  makeMCQ({ id:'g7s-cells-012', chapterId:'g7s-cells', difficulty:1, subsection:'animal_plant_cells',
    question:'Which structure is found only in plant cells and carries out photosynthesis?',
    options:['Chloroplast','Mitochondrion','Ribosome','Cell membrane'],
    answer:'Chloroplast',
    hint:'These are green because they contain chlorophyll.',
    explanation:'<b>Chloroplasts</b> are found only in plant cells (and algae). They contain chlorophyll, the green pigment that absorbs light energy for photosynthesis.' }),

  makeMCQ({ id:'g7s-cells-013', chapterId:'g7s-cells', difficulty:2, subsection:'animal_plant_cells',
    question:'A cheek cell (animal cell) and an onion cell (plant cell) are viewed under a microscope. Which feature would you expect to see in the onion cell but NOT in the cheek cell?',
    options:['A cell wall','A nucleus','A cell membrane','Cytoplasm'],
    answer:'A cell wall',
    hint:'Plant cells have this rigid outer layer; animal cells do not.',
    explanation:'The <b>cell wall</b> is present in plant cells but absent in animal cells. It is made of cellulose and gives plant cells their rigid, rectangular shape.' }),

  makeMCQ({ id:'g7s-cells-014', chapterId:'g7s-cells', difficulty:3, subsection:'animal_plant_cells',
    question:'Why do plant cells need both chloroplasts AND mitochondria?',
    options:['Chloroplasts make food by photosynthesis (in light); mitochondria release energy from food for all activities','Chloroplasts store water; mitochondria make proteins','Both do the same job','Chloroplasts are only for colour; mitochondria are for movement'],
    answer:'Chloroplasts make food by photosynthesis (in light); mitochondria release energy from food for all activities',
    hint:'Plants make food during the day but need energy day and night.',
    explanation:'Chloroplasts produce glucose by photosynthesis when light is available. <b>Mitochondria</b> then break down that glucose to release energy (through respiration) for all the cell\'s activities, at any time of day or night.' }),

  makeMCQ({ id:'g7s-cells-015', chapterId:'g7s-cells', difficulty:2, subsection:'cell_characteristics',
    question:'What is the correct order of organisation from smallest to largest?',
    options:['Cell → Tissue → Organ → Organ system → Organism','Organism → Organ system → Organ → Tissue → Cell','Cell → Organ → Tissue → Organ system → Organism','Tissue → Cell → Organ → Organism → Organ system'],
    answer:'Cell → Tissue → Organ → Organ system → Organism',
    hint:'Cells group together to form tissues, tissues to organs, and so on.',
    explanation:'The levels of organisation are: <b>Cell → Tissue → Organ → Organ system → Organism</b>. For example: muscle cells → muscle tissue → heart → circulatory system → human.' }),

  makeMCQ({ id:'g7s-cells-016', chapterId:'g7s-cells', difficulty:1, subsection:'cell_parts',
    question:'What is the function of the cell membrane in both animal and plant cells?',
    options:['It controls which substances enter and leave the cell','It produces energy for the cell','It stores water','It makes food'],
    answer:'It controls which substances enter and leave the cell',
    hint:'It acts as a selectively permeable barrier.',
    explanation:'The <b>cell membrane</b> is a thin, flexible barrier that surrounds all cells. It is selectively permeable, meaning it controls which substances pass into and out of the cell.' }),

  // ── g7s-matter ──────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-matter-007', chapterId:'g7s-matter', difficulty:1, subsection:'states_of_matter',
    question:'Which state of matter takes the shape of its container but has a fixed volume?',
    options:['Liquid','Solid','Gas','Plasma'],
    answer:'Liquid',
    hint:'Pour water into different containers — it always fills the bottom.',
    explanation:'A <b>liquid</b> takes the shape of its container but has a fixed volume. Its particles can move past each other (they flow) but remain close together, so the volume stays the same.' }),

  makeMCQ({ id:'g7s-matter-008', chapterId:'g7s-matter', difficulty:2, subsection:'states_of_matter',
    question:'Which state of matter fills the entire volume of any container it is in?',
    options:['Gas','Liquid','Solid','None of the above'],
    answer:'Gas',
    hint:'Particles in this state move freely in all directions.',
    explanation:'A <b>gas</b> fills the entire volume of its container because its particles move rapidly in all directions and spread out to fill all available space.' }),

  makeMCQ({ id:'g7s-matter-009', chapterId:'g7s-matter', difficulty:2, subsection:'properties_states',
    question:'Why can solids not flow?',
    options:['Because particles are held in fixed positions by strong forces between them','Because solid particles are heavy','Because solid particles have no energy','Because solid particles are too small to move'],
    answer:'Because particles are held in fixed positions by strong forces between them',
    hint:'Solid particles can only vibrate, not move past each other.',
    explanation:'In a solid, particles are held in fixed positions by <b>strong attractive forces</b>. They can only vibrate — they cannot slide past each other, which is why solids have a definite shape and cannot flow.' }),

  makeMCQ({ id:'g7s-matter-010', chapterId:'g7s-matter', difficulty:2, subsection:'properties_states',
    question:'Why are gases much less dense than solids?',
    options:['Gas particles are very far apart with lots of empty space between them','Gas particles are lighter atoms','Gas particles move slowly','Gas particles do not attract each other at all'],
    answer:'Gas particles are very far apart with lots of empty space between them',
    hint:'Most of the space in a gas is actually empty space.',
    explanation:'Gas density is low because <b>particles are very far apart</b> with large empty spaces between them. In a solid, particles are tightly packed, giving much higher density.' }),

  makeMCQ({ id:'g7s-matter-011', chapterId:'g7s-matter', difficulty:2, subsection:'changes_of_state',
    question:'What is the change of state from gas to liquid called?',
    options:['Condensation','Evaporation','Melting','Sublimation'],
    answer:'Condensation',
    hint:'Dew forming on grass in the morning is an example.',
    explanation:'<b>Condensation</b> is when a gas changes to a liquid. It happens when a gas loses heat energy and its particles slow down enough to attract each other and form a liquid. Dew and water droplets on a cold glass are examples.' }),

  makeMCQ({ id:'g7s-matter-012', chapterId:'g7s-matter', difficulty:1, subsection:'changes_of_state',
    question:'What is the temperature at which water changes from liquid to solid called?',
    options:['Freezing point','Boiling point','Melting point','Condensation point'],
    answer:'Freezing point',
    hint:'Pure water freezes at 0 °C.',
    explanation:'The <b>freezing point</b> is the temperature at which a liquid changes to a solid. For pure water this is 0 °C. The same temperature is also the melting point (solid to liquid) for ice.' }),

  makeMCQ({ id:'g7s-matter-013', chapterId:'g7s-matter', difficulty:3, subsection:'changes_of_state',
    question:'What happens to the temperature of water while it is boiling (changing from liquid to gas)?',
    options:['It stays constant at 100 °C until all the water has evaporated','It continues to rise','It drops suddenly','It rises and falls repeatedly'],
    answer:'It stays constant at 100 °C until all the water has evaporated',
    hint:'The energy is used to break intermolecular forces, not to raise temperature.',
    explanation:'During boiling, the temperature remains <b>constant at 100 °C</b>. The energy added is used to break the forces between water molecules (latent heat of vaporisation), not to increase temperature.' }),

  makeMCQ({ id:'g7s-matter-014', chapterId:'g7s-matter', difficulty:1, subsection:'states_of_matter',
    question:'Which of these is an example of matter?',
    options:['A wooden chair','Light from a torch','Sound from a speaker','Heat from a flame'],
    answer:'A wooden chair',
    hint:'Matter has mass and takes up space.',
    explanation:'A <b>wooden chair</b> is matter — it has mass and occupies space. Light, sound and heat are forms of energy, not matter.' }),

  makeMCQ({ id:'g7s-matter-015', chapterId:'g7s-matter', difficulty:2, subsection:'properties_states',
    question:'A gas is put into a smaller container (compressed). What happens to it?',
    options:['Its volume decreases because the particles are pushed closer together','Its mass increases','Its particles get smaller','It turns into a liquid immediately'],
    answer:'Its volume decreases because the particles are pushed closer together',
    hint:'Gas particles have large spaces between them that can be reduced.',
    explanation:'A gas can be compressed because <b>there is a lot of empty space between its particles</b>. Applying pressure pushes the particles closer together, reducing the volume.' }),

  makeMCQ({ id:'g7s-matter-016', chapterId:'g7s-matter', difficulty:3, subsection:'changes_of_state',
    question:'Why does sweat cooling your skin on a hot day involve evaporation?',
    options:['Sweat particles on the skin absorb heat energy from the body to escape as vapour, cooling the skin','Sweat makes the skin wet, which is naturally cool','The wind blows heat away from the sweat','Cold sweat comes from inside the body'],
    answer:'Sweat particles on the skin absorb heat energy from the body to escape as vapour, cooling the skin',
    hint:'Evaporation is an endothermic process — it takes in energy.',
    explanation:'Evaporation is <b>endothermic</b> — liquid particles need energy to escape as gas. Sweat takes this energy from the skin, removing heat and cooling the body down. This is the body\'s natural cooling mechanism.' }),

  // ── g7s-solar-system ────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-solar-system-007', chapterId:'g7s-solar-system', difficulty:1, subsection:'planets',
    question:'List the first four planets from the Sun in the correct order.',
    options:['Mercury, Venus, Earth, Mars','Venus, Mercury, Mars, Earth','Earth, Mars, Mercury, Venus','Mercury, Earth, Venus, Mars'],
    answer:'Mercury, Venus, Earth, Mars',
    hint:'My Very Educated Mother (Mercury, Venus, Earth, Mars).',
    explanation:'The first four planets in order from the Sun are <b>Mercury, Venus, Earth, Mars</b>. A useful mnemonic is "My Very Educated Mother Just Served Us Nachos".' }),

  makeMCQ({ id:'g7s-solar-system-008', chapterId:'g7s-solar-system', difficulty:1, subsection:'planets',
    question:'Which planet is farthest from the Sun?',
    options:['Neptune','Uranus','Saturn','Jupiter'],
    answer:'Neptune',
    hint:'It is the eighth and last planet in our solar system.',
    explanation:'<b>Neptune</b> is the farthest planet from the Sun. It is the eighth planet and takes about 165 Earth years to complete one orbit around the Sun.' }),

  makeMCQ({ id:'g7s-solar-system-009', chapterId:'g7s-solar-system', difficulty:2, subsection:'solar_system_structure',
    question:'What is an asteroid?',
    options:['A rocky object that orbits the Sun, mostly found in the asteroid belt between Mars and Jupiter','A large moon of Jupiter','A type of comet','A small star near the Sun'],
    answer:'A rocky object that orbits the Sun, mostly found in the asteroid belt between Mars and Jupiter',
    hint:'The asteroid belt lies between the rocky inner planets and the gas giants.',
    explanation:'An <b>asteroid</b> is a rocky, irregular body that orbits the Sun. Most are found in the <b>asteroid belt</b> between Mars and Jupiter. They are remnants from the formation of the solar system.' }),

  makeMCQ({ id:'g7s-solar-system-010', chapterId:'g7s-solar-system', difficulty:2, subsection:'solar_system_structure',
    question:'What is a comet?',
    options:['A body made of ice, dust and rock that orbits the Sun, developing a bright tail as it nears the Sun','A type of asteroid','A small planet','A moon of Neptune'],
    answer:'A body made of ice, dust and rock that orbits the Sun, developing a bright tail as it nears the Sun',
    hint:'The tail always points away from the Sun due to solar wind.',
    explanation:'A <b>comet</b> is composed of ice, dust and rocky material. As it approaches the Sun, the ice vaporises and solar wind pushes the released particles into a bright tail that always points away from the Sun.' }),

  makeMCQ({ id:'g7s-solar-system-011', chapterId:'g7s-solar-system', difficulty:2, subsection:'planet_characteristics',
    question:'Which two planets are called "gas giants" and are the largest in the solar system?',
    options:['Jupiter and Saturn','Uranus and Neptune','Mars and Venus','Earth and Uranus'],
    answer:'Jupiter and Saturn',
    hint:'They are famous for their enormous size and ring systems.',
    explanation:'<b>Jupiter and Saturn</b> are the two largest gas giants. Jupiter is the biggest planet overall; Saturn is famous for its spectacular ring system. Both are composed mainly of hydrogen and helium.' }),

  makeMCQ({ id:'g7s-solar-system-012', chapterId:'g7s-solar-system', difficulty:1, subsection:'planet_characteristics',
    question:'Which planet takes the longest to orbit the Sun?',
    options:['Neptune','Jupiter','Saturn','Uranus'],
    answer:'Neptune',
    hint:'A planet farther from the Sun takes longer to complete one orbit.',
    explanation:'<b>Neptune</b> takes approximately 165 Earth years to orbit the Sun once. The farther a planet is from the Sun, the longer its orbital period because it travels a greater distance at a slower speed.' }),

  makeMCQ({ id:'g7s-solar-system-013', chapterId:'g7s-solar-system', difficulty:2, subsection:'solar_system_structure',
    question:'What keeps all the planets in orbit around the Sun?',
    options:['Gravity — the Sun\'s massive gravitational pull','Magnetism from the Sun','The shape of space','The planets\' engines'],
    answer:'Gravity — the Sun\'s massive gravitational pull',
    hint:'The same force that makes an apple fall keeps planets in orbit.',
    explanation:'The <b>Sun\'s gravity</b> keeps all the planets in orbit. The Sun\'s enormous mass creates a gravitational field that continuously pulls the planets inward, balancing the planets\' tendency to travel in straight lines.' }),

  makeMCQ({ id:'g7s-solar-system-014', chapterId:'g7s-solar-system', difficulty:3, subsection:'planet_characteristics',
    question:'Venus is the hottest planet even though Mercury is closest to the Sun. Why?',
    options:['Venus has a thick atmosphere of carbon dioxide that traps heat (greenhouse effect)','Venus is bigger than Mercury','Venus rotates faster','Venus has oceans that store heat'],
    answer:'Venus has a thick atmosphere of carbon dioxide that traps heat (greenhouse effect)',
    hint:'The greenhouse effect is key here.',
    explanation:'Venus has an extreme <b>greenhouse effect</b>. Its thick CO₂ atmosphere traps solar radiation, raising surface temperatures to about 465 °C — hotter than Mercury despite being farther from the Sun.' }),

  makeMCQ({ id:'g7s-solar-system-015', chapterId:'g7s-solar-system', difficulty:1, subsection:'planets',
    question:'How long does it take the Earth to complete one orbit of the Sun?',
    options:['About 365 days (1 year)','About 24 hours (1 day)','About 28 days (1 month)','About 10 years'],
    answer:'About 365 days (1 year)',
    hint:'This is the basis of our calendar year.',
    explanation:'Earth takes approximately <b>365¼ days (1 year)</b> to complete one full orbit around the Sun. We add the extra quarter-day as a leap day every four years.' }),

  makeMCQ({ id:'g7s-solar-system-016', chapterId:'g7s-solar-system', difficulty:2, subsection:'solar_system_structure',
    question:'What is a galaxy?',
    options:['A vast system of billions of stars, gas and dust held together by gravity','A type of planet','A large asteroid','A special kind of comet'],
    answer:'A vast system of billions of stars, gas and dust held together by gravity',
    hint:'Our solar system is part of one called the Milky Way.',
    explanation:'A <b>galaxy</b> is a massive system containing billions of stars, along with gas, dust and dark matter, all bound by gravity. Our solar system is located in the <b>Milky Way</b> galaxy.' }),

  // ── g7s-electricity ─────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-electricity-007', chapterId:'g7s-electricity', difficulty:1, subsection:'circuit_parts',
    question:'What is a resistor used for in an electric circuit?',
    options:['To reduce (limit) the flow of electric current','To store electrical energy','To increase the voltage','To convert electrical energy to light'],
    answer:'To reduce (limit) the flow of electric current',
    hint:'The name gives the clue — it "resists" the current.',
    explanation:'A <b>resistor</b> limits or reduces the flow of electric current in a circuit. By controlling current, resistors protect components from being damaged by too much current.' }),

  makeMCQ({ id:'g7s-electricity-008', chapterId:'g7s-electricity', difficulty:2, subsection:'circuit_parts',
    question:'An ammeter is used in a circuit. What does it measure?',
    options:['Electric current in amperes','Voltage in volts','Resistance in ohms','Power in watts'],
    answer:'Electric current in amperes',
    hint:'The unit of current is named after André-Marie Ampère.',
    explanation:'An <b>ammeter</b> measures the electric current flowing through a circuit. It is always connected in series and measures current in <b>amperes (A)</b>.' }),

  makeMCQ({ id:'g7s-electricity-009', chapterId:'g7s-electricity', difficulty:2, subsection:'circuit_symbols',
    question:'In a circuit diagram, a circle with a cross inside it represents which component?',
    options:['A bulb (lamp)','A battery','A switch','A resistor'],
    answer:'A bulb (lamp)',
    hint:'The cross suggests the filament inside a light bulb.',
    explanation:'A <b>bulb (lamp)</b> is represented in a circuit diagram by a circle with an X (cross) inside. It converts electrical energy into light energy (and some heat).' }),

  makeMCQ({ id:'g7s-electricity-010', chapterId:'g7s-electricity', difficulty:2, subsection:'circuit_symbols',
    question:'In a circuit diagram, which symbol represents an open switch?',
    options:['A line with a gap or a line tilted away from a contact','A complete straight line','Two parallel lines of different lengths','A rectangle'],
    answer:'A line with a gap or a line tilted away from a contact',
    hint:'An open switch has a break in the circuit.',
    explanation:'An <b>open switch</b> is shown as a line (the switch lever) tilted away from the contact point, indicating that the circuit is broken and current cannot flow.' }),

  makeMCQ({ id:'g7s-electricity-011', chapterId:'g7s-electricity', difficulty:2, subsection:'simple_circuits',
    question:'What happens to the brightness of a bulb when you add more cells (batteries) to a series circuit?',
    options:['It gets brighter because more voltage drives more current','It gets dimmer','It stays the same','It goes off'],
    answer:'It gets brighter because more voltage drives more current',
    hint:'More voltage means more current, and more current means more brightness.',
    explanation:'Adding more cells increases the <b>total voltage</b> in the circuit. Higher voltage drives more current through the bulb, making it glow brighter.' }),

  makeMCQ({ id:'g7s-electricity-012', chapterId:'g7s-electricity', difficulty:3, subsection:'simple_circuits',
    question:'Two bulbs are connected in parallel with a battery. One bulb breaks. What happens to the other?',
    options:['It stays on because each bulb has its own separate path for current','It also goes off','It gets dimmer','It explodes'],
    answer:'It stays on because each bulb has its own separate path for current',
    hint:'In parallel, each branch has its own complete circuit.',
    explanation:'In a <b>parallel circuit</b>, each component has its own separate path to the battery. If one bulb breaks, current still flows through the other branch, so the other bulb stays on.' }),

  makeMCQ({ id:'g7s-electricity-013', chapterId:'g7s-electricity', difficulty:1, subsection:'circuit_parts',
    question:'What is the unit of electrical resistance?',
    options:['Ohm (Ω)','Volt (V)','Ampere (A)','Watt (W)'],
    answer:'Ohm (Ω)',
    hint:'Named after Georg Ohm, who discovered the relationship between voltage, current and resistance.',
    explanation:'The unit of electrical resistance is the <b>Ohm (Ω)</b>. Resistance is the opposition to the flow of electric current. Ohm\'s Law states: Voltage = Current × Resistance.' }),

  makeMCQ({ id:'g7s-electricity-014', chapterId:'g7s-electricity', difficulty:2, subsection:'circuit_parts',
    question:'Household wiring uses copper. Why is copper chosen for electrical wires?',
    options:['Copper is an excellent conductor of electricity and is flexible enough to bend into wires','Copper is the cheapest metal','Copper is magnetic','Copper is the lightest metal'],
    answer:'Copper is an excellent conductor of electricity and is flexible enough to bend into wires',
    hint:'Metals with low resistance are good conductors.',
    explanation:'<b>Copper</b> is used for electrical wires because it is an excellent conductor (low resistance), is ductile (can be drawn into thin wires), is flexible, and is relatively affordable compared to silver or gold.' }),

  makeMCQ({ id:'g7s-electricity-015', chapterId:'g7s-electricity', difficulty:1, subsection:'circuit_symbols',
    question:'What does a voltmeter measure in a circuit?',
    options:['The voltage (potential difference) across a component','The current through a component','The resistance of a component','The power consumed'],
    answer:'The voltage (potential difference) across a component',
    hint:'A voltmeter is always connected in parallel across a component.',
    explanation:'A <b>voltmeter</b> measures the voltage (potential difference) across a component, in volts (V). Unlike an ammeter, it is connected in parallel across the component being tested.' }),

  makeMCQ({ id:'g7s-electricity-016', chapterId:'g7s-electricity', difficulty:3, subsection:'simple_circuits',
    question:'Why are the lights in a house connected in parallel rather than in series?',
    options:['So each light can be switched on and off independently, and a faulty bulb does not affect others','Because it uses less electricity','Because series circuits are too complicated','Because parallel circuits are cheaper to make'],
    answer:'So each light can be switched on and off independently, and a faulty bulb does not affect others',
    hint:'Think about what happens to Christmas lights in series when one bulb fails.',
    explanation:'Parallel wiring means each light has its own <b>independent path</b>. You can switch each light separately, and if one bulb blows, the others remain on. In series, one failure breaks the whole circuit.' }),

  // ── g7s-ecosystem ───────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-ecosystem-007', chapterId:'g7s-ecosystem', difficulty:1, subsection:'ecosystem_types',
    question:'Which of these is a terrestrial (land) ecosystem?',
    options:['A tropical rainforest','A coral reef','A lake','The open ocean'],
    answer:'A tropical rainforest',
    hint:'"Terrestrial" means land-based.',
    explanation:'A <b>tropical rainforest</b> is a terrestrial ecosystem — it exists on land. Coral reefs, lakes and oceans are aquatic ecosystems.' }),

  makeMCQ({ id:'g7s-ecosystem-008', chapterId:'g7s-ecosystem', difficulty:2, subsection:'ecosystem_types',
    question:'What is a wetland ecosystem?',
    options:['An area where the land is covered by shallow water for all or part of the year, such as a mangrove forest','A deep ocean habitat','A dry desert','A rainforest'],
    answer:'An area where the land is covered by shallow water for all or part of the year, such as a mangrove forest',
    hint:'Wetlands occur at the boundary between land and water.',
    explanation:'A <b>wetland</b> is an ecosystem where land is saturated with water for much or all of the year. Mangroves, marshes and swamps are examples. They support high biodiversity and protect coastlines.' }),

  makeMCQ({ id:'g7s-ecosystem-009', chapterId:'g7s-ecosystem', difficulty:1, subsection:'ecosystem_balance',
    question:'What do we call the non-living parts of an ecosystem such as water, light and temperature?',
    options:['Abiotic factors','Biotic factors','Producers','Consumers'],
    answer:'Abiotic factors',
    hint:'"A-" means without; "bios" means life.',
    explanation:'<b>Abiotic factors</b> are the non-living components of an ecosystem: water, sunlight, temperature, soil, air and minerals. Biotic factors are the living organisms.' }),

  makeMCQ({ id:'g7s-ecosystem-010', chapterId:'g7s-ecosystem', difficulty:2, subsection:'ecosystem_balance',
    question:'What would most likely happen to the plant population in an ecosystem if all the herbivores were removed?',
    options:['The plant population would increase as fewer plants would be eaten','The plant population would decrease','Nothing would change','The plants would stop photosynthesising'],
    answer:'The plant population would increase as fewer plants would be eaten',
    hint:'Fewer grazers means less pressure on the plants.',
    explanation:'Without herbivores to eat them, <b>the plant population would increase</b>. This shows how the balance of an ecosystem depends on the relationships between all organisms.' }),

  makeMCQ({ id:'g7s-ecosystem-011', chapterId:'g7s-ecosystem', difficulty:2, subsection:'human_impact',
    question:'Which of the following best describes how oil spills harm ocean ecosystems?',
    options:['Oil coats feathers and fur, causes animals to drown or die of cold, and poisons fish and plankton','Oil makes the water saltier','Oil provides food for fish','Oil blocks sunlight but has no other effect'],
    answer:'Oil coats feathers and fur, causes animals to drown or die of cold, and poisons fish and plankton',
    hint:'Oil affects animals physically and chemically.',
    explanation:'Oil spills devastate ecosystems: oil <b>coats the feathers of birds and fur of mammals</b>, removing their insulation and causing death from cold. It also suffocates fish, kills plankton (the base of ocean food chains) and contaminates food supplies.' }),

  makeMCQ({ id:'g7s-ecosystem-012', chapterId:'g7s-ecosystem', difficulty:3, subsection:'human_impact',
    question:'How does introducing an invasive species threaten an ecosystem?',
    options:['It competes with native species for resources, and without natural predators it may overpopulate and push out native species','It always improves biodiversity','It helps plants grow faster','It has no effect if introduced carefully'],
    answer:'It competes with native species for resources, and without natural predators it may overpopulate and push out native species',
    hint:'In Mauritius, introduced rats and mongooses devastated native bird populations.',
    explanation:'An <b>invasive species</b> has no natural predators in its new environment, so it can reproduce rapidly and outcompete native species for food, space and habitat, causing native populations to decline or go extinct.' }),

  makeMCQ({ id:'g7s-ecosystem-013', chapterId:'g7s-ecosystem', difficulty:1, subsection:'ecosystem_types',
    question:'Mauritius has both coral reefs and mangrove forests. Which type of ecosystem is the mangrove forest?',
    options:['A wetland ecosystem','A terrestrial ecosystem','An open ocean ecosystem','A desert ecosystem'],
    answer:'A wetland ecosystem',
    hint:'Mangroves grow in shallow, brackish coastal water.',
    explanation:'Mangrove forests are <b>wetland ecosystems</b>. They grow in shallow coastal waters and are vital for protecting shorelines, providing habitat for fish nurseries and storing carbon.' }),

  makeMCQ({ id:'g7s-ecosystem-014', chapterId:'g7s-ecosystem', difficulty:2, subsection:'ecosystem_balance',
    question:'Why are decomposers essential to any ecosystem?',
    options:['They recycle nutrients by breaking down dead material, making minerals available to plants again','They produce oxygen','They are the top predators','They create new soil from rock'],
    answer:'They recycle nutrients by breaking down dead material, making minerals available to plants again',
    hint:'Without decomposers, dead material would accumulate and nutrients would be locked away.',
    explanation:'<b>Decomposers</b> (bacteria and fungi) break down dead organisms and waste. This releases nutrients (minerals) back into the soil, where plants absorb them again — completing the nutrient cycle.' }),

  makeMCQ({ id:'g7s-ecosystem-015', chapterId:'g7s-ecosystem', difficulty:1, subsection:'human_impact',
    question:'Which of these is a way that humans can protect ecosystems?',
    options:['Creating nature reserves and protected areas','Building factories in forests','Dumping waste in rivers','Overfishing the ocean'],
    answer:'Creating nature reserves and protected areas',
    hint:'Protected areas limit human activity that harms wildlife.',
    explanation:'<b>Nature reserves and protected areas</b> limit harmful human activities such as hunting, deforestation and development, allowing wildlife populations and habitats to recover and thrive.' }),

  makeMCQ({ id:'g7s-ecosystem-016', chapterId:'g7s-ecosystem', difficulty:2, subsection:'ecosystem_types',
    question:'What is biodiversity?',
    options:['The variety of different species of living organisms in an area','The number of plants in a forest','The amount of water in an ecosystem','The total mass of all animals'],
    answer:'The variety of different species of living organisms in an area',
    hint:'Greater variety of species = higher biodiversity.',
    explanation:'<b>Biodiversity</b> refers to the variety of life — the number of different species — in an ecosystem. High biodiversity generally makes ecosystems more stable and resilient to change.' }),

  // ── g7s-elements ────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-elements-007', chapterId:'g7s-elements', difficulty:1, subsection:'elements_symbols',
    question:'What is the chemical symbol for iron?',
    options:['Fe','Ir','In','I'],
    answer:'Fe',
    hint:'It comes from the Latin word "ferrum".',
    explanation:'The chemical symbol for iron is <b>Fe</b>, from the Latin "ferrum". Iron is one of the most common elements on Earth and is widely used in construction and manufacturing.' }),

  makeMCQ({ id:'g7s-elements-008', chapterId:'g7s-elements', difficulty:1, subsection:'elements_symbols',
    question:'What is the chemical symbol for sodium?',
    options:['Na','So','Sd','Nm'],
    answer:'Na',
    hint:'It comes from the Latin word "natrium".',
    explanation:'The symbol for sodium is <b>Na</b>, from the Latin "natrium". Sodium is a very reactive metal in Group 1 of the Periodic Table and is found in table salt (NaCl).' }),

  makeMCQ({ id:'g7s-elements-009', chapterId:'g7s-elements', difficulty:2, subsection:'periodic_table',
    question:'What are elements in the same GROUP (column) of the Periodic Table known to have?',
    options:['Similar chemical properties','The same atomic mass','The same number of protons','The same colour'],
    answer:'Similar chemical properties',
    hint:'Group 1 metals all react vigorously with water, for example.',
    explanation:'Elements in the same <b>group (vertical column)</b> of the Periodic Table have similar chemical properties because they have the same number of electrons in their outermost shell.' }),

  makeMCQ({ id:'g7s-elements-010', chapterId:'g7s-elements', difficulty:2, subsection:'periodic_table',
    question:'What are the horizontal rows of the Periodic Table called?',
    options:['Periods','Groups','Families','Columns'],
    answer:'Periods',
    hint:'Elements in the same row have the same number of electron shells.',
    explanation:'Horizontal rows in the Periodic Table are called <b>periods</b>. Elements in the same period have the same number of electron shells. Moving across a period, properties change systematically.' }),

  makeMCQ({ id:'g7s-elements-011', chapterId:'g7s-elements', difficulty:2, subsection:'metals_nonmetals',
    question:'Which of these properties is NOT typical of metals?',
    options:['Brittle and dull','High melting point','Good electrical conductor','Malleable (can be hammered into shape)'],
    answer:'Brittle and dull',
    hint:'Brittleness and dullness are properties of non-metals.',
    explanation:'<b>Brittle and dull</b> are properties of non-metals. Metals are typically shiny (lustrous), have high melting points, conduct electricity and heat, and are malleable and ductile.' }),

  makeMCQ({ id:'g7s-elements-012', chapterId:'g7s-elements', difficulty:1, subsection:'metals_nonmetals',
    question:'Which of these is a property of non-metals?',
    options:['Poor conductors of heat and electricity','High melting point','Shiny and lustrous','Malleable'],
    answer:'Poor conductors of heat and electricity',
    hint:'Non-metals are often used as insulators.',
    explanation:'Non-metals are generally <b>poor conductors of heat and electricity</b>. This is why plastic (a non-metal) is used to coat electrical wires — it insulates and prevents electric shocks.' }),

  makeMCQ({ id:'g7s-elements-013', chapterId:'g7s-elements', difficulty:3, subsection:'metals_nonmetals',
    question:'Why are elements on the left side of the Periodic Table generally metals, while those on the right are generally non-metals?',
    options:['Left-side elements have few outer electrons and tend to lose them (metallic behaviour); right-side elements have more outer electrons and tend to gain them (non-metallic behaviour)','It is a historical convention with no scientific basis','Metals are heavier, so they sink to the left','Non-metals are all gases, so they float to the right'],
    answer:'Left-side elements have few outer electrons and tend to lose them (metallic behaviour); right-side elements have more outer electrons and tend to gain them (non-metallic behaviour)',
    hint:'Electron configuration determines chemical behaviour.',
    explanation:'Metals on the left have <b>few electrons in their outer shell</b> and readily lose them, forming positive ions. Non-metals on the right have nearly full outer shells and gain electrons. This determines their different chemical behaviours.' }),

  makeMCQ({ id:'g7s-elements-014', chapterId:'g7s-elements', difficulty:2, subsection:'elements_symbols',
    question:'The chemical symbol for copper is Cu. From which language does this symbol come?',
    options:['Latin (from "cuprum")','Greek','French','Arabic'],
    answer:'Latin (from "cuprum")',
    hint:'Many element symbols come from Latin names.',
    explanation:'Copper\'s symbol <b>Cu</b> comes from the Latin word "cuprum", which itself derives from Cyprus — an island famous for its copper mines in ancient times.' }),

  makeMCQ({ id:'g7s-elements-015', chapterId:'g7s-elements', difficulty:1, subsection:'periodic_table',
    question:'What is the lightest element and appears first in the Periodic Table?',
    options:['Hydrogen (H)','Helium (He)','Lithium (Li)','Carbon (C)'],
    answer:'Hydrogen (H)',
    hint:'It has an atomic number of 1.',
    explanation:'<b>Hydrogen (H)</b> is the lightest and most abundant element in the universe. It has atomic number 1 (1 proton) and appears first in the Periodic Table.' }),

  makeMCQ({ id:'g7s-elements-016', chapterId:'g7s-elements', difficulty:2, subsection:'periodic_table',
    question:'What is the difference between an element and a compound?',
    options:['An element contains atoms of one type only; a compound contains two or more elements chemically joined','Elements are gases; compounds are solids','Elements are natural; compounds are man-made','There is no difference'],
    answer:'An element contains atoms of one type only; a compound contains two or more elements chemically joined',
    hint:'Pure gold is an element; water (H₂O) is a compound.',
    explanation:'An <b>element</b> consists of only one type of atom (e.g. gold = only Au atoms). A <b>compound</b> contains two or more different elements chemically combined in fixed ratios (e.g. H₂O = H and O chemically joined).' }),

  // ── g7s-air ─────────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-air-007', chapterId:'g7s-air', difficulty:2, subsection:'composition_air',
    question:'What percentage of clean, dry air is carbon dioxide (CO₂)?',
    options:['About 0.04%','About 21%','About 78%','About 1%'],
    answer:'About 0.04%',
    hint:'It is a tiny fraction but very important for plant photosynthesis and the greenhouse effect.',
    explanation:'Carbon dioxide makes up only about <b>0.04%</b> of clean air. Despite its small proportion, it is vital for photosynthesis and plays a major role in the greenhouse effect.' }),

  makeMCQ({ id:'g7s-air-008', chapterId:'g7s-air', difficulty:1, subsection:'composition_air',
    question:'Which gas in the air is used by plants for photosynthesis?',
    options:['Carbon dioxide (CO₂)','Nitrogen (N₂)','Oxygen (O₂)','Argon (Ar)'],
    answer:'Carbon dioxide (CO₂)',
    hint:'Plants take in this gas through tiny pores called stomata.',
    explanation:'Plants absorb <b>carbon dioxide (CO₂)</b> from the air through their stomata and use it in photosynthesis to make glucose and oxygen.' }),

  makeMCQ({ id:'g7s-air-009', chapterId:'g7s-air', difficulty:2, subsection:'oxygen_co2_tests',
    question:'A student heats a substance and collects a gas. A glowing splint relights when placed in the gas. What is the gas?',
    options:['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],
    answer:'Oxygen',
    hint:'Only this gas supports combustion well enough to relight a glowing splint.',
    explanation:'<b>Oxygen</b> supports combustion. The test for oxygen is that a glowing splint (a splint still glowing but not burning) bursts back into flame when placed in the gas.' }),

  makeMCQ({ id:'g7s-air-010', chapterId:'g7s-air', difficulty:2, subsection:'oxygen_co2_tests',
    question:'A student breathes out through a straw into lime water. What change would she observe?',
    options:['The lime water turns milky (cloudy)','The lime water turns red','The lime water evaporates','No change'],
    answer:'The lime water turns milky (cloudy)',
    hint:'Exhaled breath contains carbon dioxide.',
    explanation:'Exhaled air contains carbon dioxide. When CO₂ passes through lime water (calcium hydroxide solution), it reacts to form calcium carbonate, making the liquid <b>turn milky (cloudy)</b>.' }),

  makeMCQ({ id:'g7s-air-011', chapterId:'g7s-air', difficulty:2, subsection:'air_properties',
    question:'What does atmospheric pressure tell us?',
    options:['The weight of the column of air above us pressing down on every surface','The speed at which air moves','The temperature of the air','The amount of water vapour in the air'],
    answer:'The weight of the column of air above us pressing down on every surface',
    hint:'Think of it as the air "pushing down" with its weight.',
    explanation:'<b>Atmospheric pressure</b> is caused by the weight of the column of air in the atmosphere pressing down on surfaces. At sea level it is approximately 101,325 Pa (about 1 atmosphere).' }),

  makeMCQ({ id:'g7s-air-012', chapterId:'g7s-air', difficulty:3, subsection:'air_properties',
    question:'Why do mountain climbers carry oxygen cylinders at high altitudes?',
    options:['Air is thinner at high altitude so there is less oxygen per breath, making normal breathing insufficient','Oxygen is heavier and sinks to low altitudes','There is no air above a certain altitude','Cold temperatures destroy oxygen'],
    answer:'Air is thinner at high altitude so there is less oxygen per breath, making normal breathing insufficient',
    hint:'Air pressure decreases with altitude, meaning fewer air molecules per volume.',
    explanation:'At high altitudes, atmospheric pressure is lower, meaning <b>fewer air molecules per breath</b> — including less oxygen. The body cannot get enough oxygen for normal activity, so climbers carry supplementary oxygen.' }),

  makeMCQ({ id:'g7s-air-013', chapterId:'g7s-air', difficulty:2, subsection:'composition_air',
    question:'Argon (Ar) makes up about 0.93% of air. What type of element is argon?',
    options:['A noble (inert) gas — it is very unreactive','A reactive metal','A non-metal that burns','An acidic gas'],
    answer:'A noble (inert) gas — it is very unreactive',
    hint:'Noble gases are in Group 18 (the last column) of the Periodic Table.',
    explanation:'Argon is a <b>noble gas</b>. Noble gases have full outer electron shells, making them extremely unreactive (inert). Argon is used in light bulbs to prevent the filament from burning.' }),

  makeMCQ({ id:'g7s-air-014', chapterId:'g7s-air', difficulty:1, subsection:'oxygen_co2_tests',
    question:'Which gas is needed for combustion (burning)?',
    options:['Oxygen','Nitrogen','Carbon dioxide','Argon'],
    answer:'Oxygen',
    hint:'You cannot burn something in a jar with no air.',
    explanation:'<b>Oxygen</b> is required for combustion. The fire triangle (fuel, heat, oxygen) shows that removing oxygen stops a fire. This is why a fire goes out when smothered.' }),

  makeMCQ({ id:'g7s-air-015', chapterId:'g7s-air', difficulty:2, subsection:'air_properties',
    question:'How can you prove that air occupies space?',
    options:['Push an empty cup upside down into water — the air inside prevents water from entering','Weigh an empty container','Light a candle in a jar','Nothing — air is invisible so it has no space'],
    answer:'Push an empty cup upside down into water — the air inside prevents water from entering',
    hint:'Air is matter and takes up space, even though we cannot see it.',
    explanation:'Pushing an upturned cup into water shows that <b>air occupies space</b> — the trapped air prevents water from entering the cup. This simple demonstration proves air takes up space.' }),

  makeMCQ({ id:'g7s-air-016', chapterId:'g7s-air', difficulty:1, subsection:'composition_air',
    question:'Which gas in air is most important for the respiration of living things?',
    options:['Oxygen','Nitrogen','Carbon dioxide','Water vapour'],
    answer:'Oxygen',
    hint:'Cells use this gas to release energy from glucose.',
    explanation:'<b>Oxygen</b> (making up 21% of air) is essential for aerobic respiration in living things. Cells combine oxygen with glucose to release energy, producing carbon dioxide and water as waste.' }),

  // ── g7s-biodiversity ────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-biodiversity-007', chapterId:'g7s-biodiversity', difficulty:1, subsection:'classifying_organisms',
    question:'Which kingdom do mushrooms belong to?',
    options:['Fungi','Animalia','Plantae','Protista'],
    answer:'Fungi',
    hint:'Fungi are not plants — they cannot photosynthesise.',
    explanation:'Mushrooms belong to the <b>Fungi</b> kingdom. Fungi cannot make their own food (they are not photosynthetic); instead they absorb nutrients from dead or living organic matter.' }),

  makeMCQ({ id:'g7s-biodiversity-008', chapterId:'g7s-biodiversity', difficulty:2, subsection:'classifying_organisms',
    question:'What is the purpose of scientific (Latin) names for organisms?',
    options:['To give each species a universal name understood by scientists worldwide, regardless of language','To make biology more difficult','Because Latin is the most beautiful language','Scientists enjoy using Latin'],
    answer:'To give each species a universal name understood by scientists worldwide, regardless of language',
    hint:'Common names vary by country; scientific names are consistent globally.',
    explanation:'<b>Scientific names</b> (binomial nomenclature, e.g. <i>Homo sapiens</i>) are universal — scientists in any country use the same name for the same species, avoiding confusion from different local common names.' }),

  makeMCQ({ id:'g7s-biodiversity-009', chapterId:'g7s-biodiversity', difficulty:2, subsection:'vertebrates_invertebrates',
    question:'Which class of vertebrates are warm-blooded, have feathers and lay eggs?',
    options:['Birds','Reptiles','Mammals','Amphibians'],
    answer:'Birds',
    hint:'They have wings (even if some cannot fly) and beaks.',
    explanation:'<b>Birds</b> (class Aves) are warm-blooded vertebrates with feathers, wings, beaks and scales on their legs. They lay hard-shelled eggs. Examples include pigeons, eagles and ostriches.' }),

  makeMCQ({ id:'g7s-biodiversity-010', chapterId:'g7s-biodiversity', difficulty:1, subsection:'vertebrates_invertebrates',
    question:'Fish, frogs, lizards, birds and humans all belong to which group?',
    options:['Vertebrates','Invertebrates','Insects','Molluscs'],
    answer:'Vertebrates',
    hint:'All of these animals have a backbone.',
    explanation:'All of these animals are <b>vertebrates</b> — they all have a backbone (vertebral column). The five classes of vertebrates are fish, amphibians, reptiles, birds and mammals.' }),

  makeMCQ({ id:'g7s-biodiversity-011', chapterId:'g7s-biodiversity', difficulty:2, subsection:'vertebrates_invertebrates',
    question:'Which class of vertebrates can live both on land and in water, and have moist, scaleless skin?',
    options:['Amphibians','Reptiles','Fish','Mammals'],
    answer:'Amphibians',
    hint:'Frogs and toads start life in water (as tadpoles) and live on land as adults.',
    explanation:'<b>Amphibians</b> (e.g. frogs, toads, salamanders) spend the early part of life in water and adulthood on land. They have moist, scaleless skin and lay eggs in water.' }),

  makeMCQ({ id:'g7s-biodiversity-012', chapterId:'g7s-biodiversity', difficulty:2, subsection:'plant_types',
    question:'What is the main feature that distinguishes flowering plants from non-flowering plants?',
    options:['Flowering plants produce flowers that develop into seeds and fruits; non-flowering plants do not','Flowering plants are always colourful','Non-flowering plants cannot grow in sunlight','Flowering plants cannot produce oxygen'],
    answer:'Flowering plants produce flowers that develop into seeds and fruits; non-flowering plants do not',
    hint:'Ferns reproduce using spores; roses reproduce using seeds from flowers.',
    explanation:'<b>Flowering plants (angiosperms)</b> reproduce sexually through flowers that produce seeds enclosed in fruits. <b>Non-flowering plants</b> like ferns and mosses use spores; conifers use cones.' }),

  makeMCQ({ id:'g7s-biodiversity-013', chapterId:'g7s-biodiversity', difficulty:1, subsection:'plant_types',
    question:'Ferns reproduce using spores. Where are the spores usually found?',
    options:['On the underside of the leaves (in structures called sori)','In flowers','In fruits','In roots'],
    answer:'On the underside of the leaves (in structures called sori)',
    hint:'Look for small brown dots on the backs of fern leaves.',
    explanation:'Fern spores are produced in clusters called <b>sori</b> found on the underside of the fronds (leaves). When ripe, spores are released and can grow into new fern plants if conditions are suitable.' }),

  makeMCQ({ id:'g7s-biodiversity-014', chapterId:'g7s-biodiversity', difficulty:3, subsection:'classifying_organisms',
    question:'Why is classification important in biology?',
    options:['It helps scientists organise the huge variety of life, identify relationships between organisms and communicate precisely','It is required by law','It makes organisms easier to catch','Classification is only used to name things'],
    answer:'It helps scientists organise the huge variety of life, identify relationships between organisms and communicate precisely',
    hint:'Over 8 million species have been described — organisation is essential.',
    explanation:'<b>Classification</b> organises the enormous variety of life into manageable groups based on shared features. It reveals evolutionary relationships, aids scientific communication worldwide, and helps identify unknown organisms.' }),

  makeMCQ({ id:'g7s-biodiversity-015', chapterId:'g7s-biodiversity', difficulty:1, subsection:'vertebrates_invertebrates',
    question:'Which of these is a mammal?',
    options:['Dolphin','Shark','Crocodile','Frog'],
    answer:'Dolphin',
    hint:'Mammals are warm-blooded, breathe air and feed their young on milk.',
    explanation:'A <b>dolphin</b> is a mammal — it is warm-blooded, breathes air through a blowhole, gives birth to live young and feeds them milk. Sharks are fish; crocodiles are reptiles; frogs are amphibians.' }),

  makeMCQ({ id:'g7s-biodiversity-016', chapterId:'g7s-biodiversity', difficulty:2, subsection:'classifying_organisms',
    question:'Bacteria are placed in the kingdom Monera. What makes bacteria different from all other organisms?',
    options:['They are prokaryotes — they have no membrane-bound nucleus','They are the largest organisms','They cannot reproduce','They only live in soil'],
    answer:'They are prokaryotes — they have no membrane-bound nucleus',
    hint:'Pro = before, karyon = nucleus; their genetic material is not enclosed in a membrane.',
    explanation:'Bacteria are <b>prokaryotes</b> — their cells have no membrane-bound nucleus. Their DNA floats freely in the cytoplasm. All other living things (animals, plants, fungi, protists) are eukaryotes with a true nucleus.' }),

  // ── g7s-food-chains ─────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-food-chains-007', chapterId:'g7s-food-chains', difficulty:1, subsection:'feeding_relationships',
    question:'What do we call an animal that eats both plants and animals?',
    options:['Omnivore','Herbivore','Carnivore','Decomposer'],
    answer:'Omnivore',
    hint:'Humans are an example of this feeding type.',
    explanation:'An <b>omnivore</b> eats both plants and animals. Humans, bears and pigs are omnivores. The prefix "omni" means "all", reflecting their varied diet.' }),

  makeMCQ({ id:'g7s-food-chains-008', chapterId:'g7s-food-chains', difficulty:1, subsection:'feeding_relationships',
    question:'What is a predator?',
    options:['An animal that hunts and eats other animals','An animal that only eats plants','An organism that breaks down dead matter','A plant that traps insects'],
    answer:'An animal that hunts and eats other animals',
    hint:'A lion hunting a zebra is a classic example.',
    explanation:'A <b>predator</b> is an organism that actively hunts, catches and eats other organisms (its prey). For example, a hawk is a predator that preys on mice.' }),

  makeMCQ({ id:'g7s-food-chains-009', chapterId:'g7s-food-chains', difficulty:2, subsection:'food_chains',
    question:'In the food chain: sugarcane → rat → mongoose → hawk, what is the rat?',
    options:['A primary consumer (herbivore)','A producer','A secondary consumer','A decomposer'],
    answer:'A primary consumer (herbivore)',
    hint:'It is the first animal in the chain, eating the producer.',
    explanation:'The rat eats sugarcane (the producer), making it the <b>primary consumer</b> — the first level of animal in the food chain. Primary consumers are herbivores.' }),

  makeMCQ({ id:'g7s-food-chains-010', chapterId:'g7s-food-chains', difficulty:2, subsection:'food_chains',
    question:'A food WEB contains many interconnected food chains. Why is a food web more realistic than a single food chain?',
    options:['Because most animals eat more than one type of food and are eaten by more than one predator','Because food webs are easier to draw','Because food chains do not exist in nature','Because food webs contain more animals'],
    answer:'Because most animals eat more than one type of food and are eaten by more than one predator',
    hint:'In reality, a rabbit might eat grass AND clover AND berries.',
    explanation:'A <b>food web</b> is more realistic because animals rarely eat only one type of food. A food web shows all the feeding relationships in an ecosystem — multiple producers, consumers and decomposers linked together.' }),

  makeMCQ({ id:'g7s-food-chains-011', chapterId:'g7s-food-chains', difficulty:3, subsection:'energy_flow',
    question:'Why does a food chain rarely have more than 4 or 5 links?',
    options:['Because so much energy is lost as heat at each level that there is not enough energy left to support another level','Because animals at the top are too large to eat more','Because there are not enough species for longer chains','Because the first organism runs out of food'],
    answer:'Because so much energy is lost as heat at each level that there is not enough energy left to support another level',
    hint:'Only about 10% of energy passes from one trophic level to the next.',
    explanation:'At each level of a food chain, about 90% of energy is lost as heat through respiration and movement. After 4–5 levels, <b>so little energy remains</b> that it could not support another population.' }),

  makeMCQ({ id:'g7s-food-chains-012', chapterId:'g7s-food-chains', difficulty:2, subsection:'energy_flow',
    question:'What is a trophic level?',
    options:['The position an organism occupies in a food chain — producers are level 1, primary consumers level 2, and so on','The number of organisms in an ecosystem','The amount of energy stored in an ecosystem','The speed at which organisms digest food'],
    answer:'The position an organism occupies in a food chain — producers are level 1, primary consumers level 2, and so on',
    hint:'"Trophic" comes from the Greek word for food/nourishment.',
    explanation:'A <b>trophic level</b> is the position in a food chain. Producers are trophic level 1; primary consumers (herbivores) are level 2; secondary consumers are level 3; and so on. Energy decreases at higher trophic levels.' }),

  makeMCQ({ id:'g7s-food-chains-013', chapterId:'g7s-food-chains', difficulty:1, subsection:'feeding_relationships',
    question:'Why are producers always the starting point of every food chain?',
    options:['Because they are the only organisms that can capture energy from sunlight and convert it into food','Because they are the largest organisms','Because they reproduce fastest','Because they are the most common organisms'],
    answer:'Because they are the only organisms that can capture energy from sunlight and convert it into food',
    hint:'All energy in a food chain originally comes from sunlight.',
    explanation:'<b>Producers</b> (mainly green plants) use photosynthesis to capture solar energy and convert it into chemical energy stored in glucose. This is the original energy source for the entire food chain.' }),

  makeMCQ({ id:'g7s-food-chains-014', chapterId:'g7s-food-chains', difficulty:2, subsection:'food_chains',
    question:'In a marine food chain: phytoplankton → zooplankton → small fish → large fish → shark, which organism is the top predator?',
    options:['Shark','Large fish','Phytoplankton','Zooplankton'],
    answer:'Shark',
    hint:'The top predator is at the end of the food chain.',
    explanation:'The <b>shark</b> is the top predator — it is not eaten by any other organism in this food chain. Phytoplankton are the producers; the others are consumers at different levels.' }),

  makeMCQ({ id:'g7s-food-chains-015', chapterId:'g7s-food-chains', difficulty:3, subsection:'energy_flow',
    question:'Pesticide is sprayed on crops. Small amounts enter insects, more accumulates in birds that eat insects, and even more in hawks that eat birds. What is this process called?',
    options:['Biomagnification (bioaccumulation)','Decomposition','Nitrification','Photosynthesis'],
    answer:'Biomagnification (bioaccumulation)',
    hint:'The chemical builds up at each trophic level.',
    explanation:'<b>Biomagnification</b> is the process by which toxic substances (like pesticides) become more concentrated at each trophic level. Top predators accumulate the highest and most dangerous concentrations.' }),

  makeMCQ({ id:'g7s-food-chains-016', chapterId:'g7s-food-chains', difficulty:1, subsection:'feeding_relationships',
    question:'What do we call an animal that only eats other animals?',
    options:['Carnivore','Herbivore','Omnivore','Producer'],
    answer:'Carnivore',
    hint:'"Carni" comes from Latin for flesh.',
    explanation:'A <b>carnivore</b> eats only other animals. Lions, sharks and spiders are carnivores. The word comes from the Latin "caro" (flesh) and "vorare" (to devour).' }),

  // ── g7s-changes ─────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-changes-007', chapterId:'g7s-changes', difficulty:1, subsection:'physical_changes',
    question:'Which of the following is a reversible physical change?',
    options:['Dissolving sugar in water','Burning coal','Rusting iron','Cooking an egg'],
    answer:'Dissolving sugar in water',
    hint:'You can get the sugar back by evaporating the water.',
    explanation:'<b>Dissolving sugar in water</b> is a reversible physical change — you can recover the sugar by evaporating the water. The sugar has not changed chemically; it has simply dispersed in the water.' }),

  makeMCQ({ id:'g7s-changes-008', chapterId:'g7s-changes', difficulty:2, subsection:'physical_changes',
    question:'When salt water is heated and the water evaporates, the salt is left behind. Is this a physical or chemical change?',
    options:['Physical — the salt and water have just been separated, no new substances formed','Chemical — evaporation creates new substances','Both physical and chemical','Neither'],
    answer:'Physical — the salt and water have just been separated, no new substances formed',
    hint:'The salt is still salt; the water is still water.',
    explanation:'Separating salt from water by evaporation is a <b>physical change</b>. The salt and water retain their original identities — no new substances are formed. The process can be reversed by dissolving the salt again.' }),

  makeMCQ({ id:'g7s-changes-009', chapterId:'g7s-changes', difficulty:2, subsection:'chemical_changes',
    question:'Which of these is a sign that a chemical change has taken place?',
    options:['A permanent colour change','A temporary change in size','A change in temperature that reverses immediately','A substance melting'],
    answer:'A permanent colour change',
    hint:'Chemical changes form new substances, which may have different colours.',
    explanation:'A <b>permanent colour change</b> indicates a chemical change — new substances with different properties (including colour) have been formed. Melting is physical; temporary temperature changes may be physical.' }),

  makeMCQ({ id:'g7s-changes-010', chapterId:'g7s-changes', difficulty:1, subsection:'chemical_changes',
    question:'Is cooking rice a physical or chemical change?',
    options:['Chemical — the starch and proteins in the rice change permanently when heated','Physical — rice can be uncooked again','Physical — it only changes shape','Neither'],
    answer:'Chemical — the starch and proteins in the rice change permanently when heated',
    hint:'You cannot un-cook rice.',
    explanation:'<b>Cooking rice is a chemical change</b>. Heat causes irreversible changes in the starch and protein molecules. The cooked rice cannot be turned back into raw rice.' }),

  makeMCQ({ id:'g7s-changes-011', chapterId:'g7s-changes', difficulty:3, subsection:'examples_changes',
    question:'Respiration in cells can be summarised as: glucose + oxygen → carbon dioxide + water + energy. Is this a chemical change? Why?',
    options:['Yes — new substances (CO₂ and water) are formed from glucose and oxygen; the original molecules are broken down and cannot easily be reformed','No — the glucose just moves around','No — living things do not undergo chemical changes','Yes — but only because heat is produced'],
    answer:'Yes — new substances (CO₂ and water) are formed from glucose and oxygen; the original molecules are broken down and cannot easily be reformed',
    hint:'New molecules are formed that were not present at the start.',
    explanation:'<b>Cellular respiration is a chemical change</b>. Glucose molecules are broken down and combined with oxygen to form new substances (CO₂ and water), releasing energy. These products cannot spontaneously reform glucose.' }),

  makeMCQ({ id:'g7s-changes-012', chapterId:'g7s-changes', difficulty:2, subsection:'examples_changes',
    question:'Why is a change of state (e.g. ice melting) considered a physical change, not a chemical change?',
    options:['Because the chemical identity of the substance stays the same — H₂O is still H₂O whether it is ice, water or steam','Because no energy is involved','Because it is reversible and chemical changes are not','Because changes of state are too simple to be chemical'],
    answer:'Because the chemical identity of the substance stays the same — H₂O is still H₂O whether it is ice, water or steam',
    hint:'Only the arrangement of molecules changes, not the molecules themselves.',
    explanation:'Changes of state are <b>physical changes</b> because only the arrangement and energy of the particles change — not their chemical identity. Ice, water and steam are all H₂O.' }),

  makeMCQ({ id:'g7s-changes-013', chapterId:'g7s-changes', difficulty:2, subsection:'physical_changes',
    question:'Which of the following involves ONLY a physical change?',
    options:['Sharpening a pencil','Setting fire to paper','Making bread rise','Milk going sour'],
    answer:'Sharpening a pencil',
    hint:'Sharpening just removes wood and graphite — no new substances form.',
    explanation:'<b>Sharpening a pencil</b> is a physical change — wood and graphite are just cut away; no new substances are formed. Setting fire to paper, bread rising (CO₂ production) and milk souring are all chemical changes.' }),

  makeMCQ({ id:'g7s-changes-014', chapterId:'g7s-changes', difficulty:1, subsection:'chemical_changes',
    question:'What is produced when vinegar (acetic acid) reacts with baking soda (sodium bicarbonate)?',
    options:['Carbon dioxide gas, water and a salt','Only water','Only heat','Only a colour change'],
    answer:'Carbon dioxide gas, water and a salt',
    hint:'The fizzing you observe is the CO₂ gas being released.',
    explanation:'Vinegar (acid) reacts with baking soda (carbonate) to produce <b>carbon dioxide gas</b> (the fizzing), water and a salt (sodium acetate). This is a chemical change — new substances are formed.' }),

  makeMCQ({ id:'g7s-changes-015', chapterId:'g7s-changes', difficulty:2, subsection:'examples_changes',
    question:'How can you prevent iron from rusting?',
    options:['By coating it with paint, oil or another metal to prevent contact with water and oxygen','By heating it','By adding water to it','By placing it in sunlight'],
    answer:'By coating it with paint, oil or another metal to prevent contact with water and oxygen',
    hint:'Rusting requires both water and oxygen — remove either to prevent it.',
    explanation:'Rusting requires both oxygen and water. <b>Coating iron</b> with paint, oil, grease or another metal (like zinc — galvanising) acts as a barrier, preventing contact with water and oxygen and stopping rust forming.' }),

  makeMCQ({ id:'g7s-changes-016', chapterId:'g7s-changes', difficulty:1, subsection:'physical_changes',
    question:'Is stretching a rubber band a physical or chemical change?',
    options:['Physical — the rubber returns to its original shape; no new substance is formed','Chemical — the rubber becomes a new material','Both — it changes shape and composition','Chemical — it is irreversible'],
    answer:'Physical — the rubber returns to its original shape; no new substance is formed',
    hint:'The rubber band can return to its original shape.',
    explanation:'Stretching a rubber band is a <b>physical change</b>. It is reversible (the rubber returns to its original shape when released) and no new substance is formed — the rubber\'s chemical identity is unchanged.' }),

  // ── g7s-energy ──────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-energy-007', chapterId:'g7s-energy', difficulty:2, subsection:'forms_energy',
    question:'A stretched spring has which type of energy?',
    options:['Elastic (strain) potential energy','Kinetic energy','Chemical energy','Thermal energy'],
    answer:'Elastic (strain) potential energy',
    hint:'It is stored in the spring due to its deformed shape.',
    explanation:'A stretched spring stores <b>elastic (strain) potential energy</b>. This energy is released when the spring returns to its original shape, and can be converted to kinetic energy (e.g. in a slingshot).' }),

  makeMCQ({ id:'g7s-energy-008', chapterId:'g7s-energy', difficulty:1, subsection:'forms_energy',
    question:'What type of energy is stored in food?',
    options:['Chemical energy','Kinetic energy','Nuclear energy','Sound energy'],
    answer:'Chemical energy',
    hint:'This energy is released during digestion and respiration.',
    explanation:'Food stores <b>chemical energy</b> in the bonds between molecules. During digestion and cellular respiration, this chemical energy is released to power all body functions.' }),

  makeMCQ({ id:'g7s-energy-009', chapterId:'g7s-energy', difficulty:2, subsection:'energy_transformation',
    question:'A hydroelectric power station uses water stored behind a dam. What energy transformation takes place?',
    options:['Gravitational potential energy → kinetic energy → electrical energy','Electrical energy → potential energy','Chemical energy → electrical energy','Sound energy → electrical energy'],
    answer:'Gravitational potential energy → kinetic energy → electrical energy',
    hint:'Water falls from height (stored energy), spins turbines (movement), generates electricity.',
    explanation:'In hydroelectric power: <b>gravitational potential energy</b> (water at height) → <b>kinetic energy</b> (falling water turns turbines) → <b>electrical energy</b> (generators produce electricity).' }),

  makeMCQ({ id:'g7s-energy-010', chapterId:'g7s-energy', difficulty:2, subsection:'energy_transformation',
    question:'A solar panel on a roof converts sunlight into electricity. What energy transformation occurs?',
    options:['Light energy → electrical energy','Chemical energy → electrical energy','Kinetic energy → light energy','Thermal energy → kinetic energy'],
    answer:'Light energy → electrical energy',
    hint:'Photovoltaic cells convert photons into electrons.',
    explanation:'A solar panel converts <b>light energy from the sun → electrical energy</b>. Photovoltaic cells in the panel absorb photons and release electrons, generating a current.' }),

  makeMCQ({ id:'g7s-energy-011', chapterId:'g7s-energy', difficulty:2, subsection:'renewable_nonrenewable',
    question:'Which of these is a renewable energy source?',
    options:['Wind energy','Coal','Nuclear energy','Natural gas'],
    answer:'Wind energy',
    hint:'Wind is continuously replenished by the sun heating the atmosphere.',
    explanation:'<b>Wind energy</b> is renewable — wind is caused by uneven heating of the atmosphere by the Sun and will not run out. Coal, nuclear energy (uranium) and natural gas are non-renewable resources that will eventually be exhausted.' }),

  makeMCQ({ id:'g7s-energy-012', chapterId:'g7s-energy', difficulty:3, subsection:'renewable_nonrenewable',
    question:'Mauritius gets most of its electricity from burning oil and coal. What is the main environmental disadvantage of this?',
    options:['It releases carbon dioxide and other greenhouse gases that contribute to climate change','It is too cheap','It produces too much electricity','It makes the island too warm'],
    answer:'It releases carbon dioxide and other greenhouse gases that contribute to climate change',
    hint:'Burning fossil fuels releases CO₂ stored millions of years ago.',
    explanation:'Burning fossil fuels releases <b>carbon dioxide</b> into the atmosphere. This greenhouse gas traps heat, contributing to global warming and climate change — causing sea level rise, more extreme weather events and ocean acidification.' }),

  makeMCQ({ id:'g7s-energy-013', chapterId:'g7s-energy', difficulty:1, subsection:'forms_energy',
    question:'What is gravitational potential energy?',
    options:['Energy stored in an object due to its height above the ground','Energy due to an object\'s movement','Energy stored in chemical bonds','Energy produced by the sun'],
    answer:'Energy stored in an object due to its height above the ground',
    hint:'A book on a high shelf has more of this than the same book on the floor.',
    explanation:'<b>Gravitational potential energy</b> is energy stored in an object because of its position above the ground. The higher the object and the heavier it is, the more gravitational potential energy it has.' }),

  makeMCQ({ id:'g7s-energy-014', chapterId:'g7s-energy', difficulty:2, subsection:'energy_transformation',
    question:'When a ball is dropped, its gravitational potential energy converts to kinetic energy. What happens to the energy when the ball hits the ground and stops?',
    options:['It converts to heat and sound energy — energy is conserved but changes form','It disappears','It goes back to potential energy','All energy is lost'],
    answer:'It converts to heat and sound energy — energy is conserved but changes form',
    hint:'The law of conservation of energy — energy cannot disappear.',
    explanation:'When the ball hits the ground and stops, its kinetic energy converts to <b>heat</b> (warming the ball and ground slightly) and <b>sound</b>. Total energy is conserved — it changes form but does not disappear.' }),

  makeMCQ({ id:'g7s-energy-015', chapterId:'g7s-energy', difficulty:1, subsection:'renewable_nonrenewable',
    question:'Which of the following is an example of biomass energy?',
    options:['Burning wood or sugarcane bagasse to produce electricity','Harnessing tidal waves','Solar panels on roofs','Wind turbines on a hill'],
    answer:'Burning wood or sugarcane bagasse to produce electricity',
    hint:'Biomass uses organic material as fuel.',
    explanation:'<b>Biomass energy</b> uses organic materials such as wood, agricultural waste (like sugarcane bagasse in Mauritius) or biogas. It is considered renewable because plants can be regrown.' }),

  makeMCQ({ id:'g7s-energy-016', chapterId:'g7s-energy', difficulty:3, subsection:'renewable_nonrenewable',
    question:'A student says "when I use energy, I waste it." Is this scientifically accurate?',
    options:['No — energy is not destroyed (law of conservation), but it may be converted to less useful forms like heat','Yes — energy is used up completely','Yes — but only electrical energy','No — energy actually increases when used'],
    answer:'No — energy is not destroyed (law of conservation), but it may be converted to less useful forms like heat',
    hint:'Energy cannot be created or destroyed, only changed in form.',
    explanation:'Energy cannot be wasted in the sense of disappearing. The <b>law of conservation of energy</b> states energy is always conserved. What we call "wasting" energy means converting it to less useful forms (mainly heat) that spread out and are hard to use again.' }),

  // ── g7s-sts ─────────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7s-sts-007', chapterId:'g7s-sts', difficulty:1, subsection:'science_technology',
    question:'How has the development of the microscope contributed to medicine?',
    options:['It allowed scientists to discover bacteria and viruses, leading to germ theory and the development of vaccines and antibiotics','It made it possible to see the sun more clearly','It was used to improve farming methods','It allowed scientists to study rocks'],
    answer:'It allowed scientists to discover bacteria and viruses, leading to germ theory and the development of vaccines and antibiotics',
    hint:'Louis Pasteur and Robert Koch used microscopes to identify disease-causing microorganisms.',
    explanation:'The microscope allowed scientists to discover <b>bacteria and viruses</b>, establishing germ theory (diseases are caused by microorganisms). This led to vaccines, antibiotics and antiseptic surgery — transforming medicine.' }),

  makeMCQ({ id:'g7s-sts-008', chapterId:'g7s-sts', difficulty:2, subsection:'discoveries',
    question:'Galileo Galilei used an early telescope to study the sky. What was his most significant scientific contribution related to the solar system?',
    options:['He provided evidence that the Earth orbits the Sun (heliocentric model), not the other way around','He discovered gravity','He invented the compass','He made the first map of Africa'],
    answer:'He provided evidence that the Earth orbits the Sun (heliocentric model), not the other way around',
    hint:'Before Galileo, most people believed the Sun orbited the Earth.',
    explanation:'Galileo\'s observations (e.g. moons orbiting Jupiter, phases of Venus) supported the <b>heliocentric model</b> — that Earth and the planets orbit the Sun. This challenged the accepted geocentric view and transformed our understanding of the solar system.' }),

  makeMCQ({ id:'g7s-sts-009', chapterId:'g7s-sts', difficulty:2, subsection:'discoveries',
    question:'How does recycling metals like aluminium benefit society?',
    options:['It conserves natural resources, uses much less energy than producing metal from ore, and reduces landfill waste','It makes metals more expensive','It stops mines from producing new metal','Recycled metal is weaker and less useful'],
    answer:'It conserves natural resources, uses much less energy than producing metal from ore, and reduces landfill waste',
    hint:'Recycling aluminium uses only about 5% of the energy of making new aluminium.',
    explanation:'Recycling metals <b>conserves natural ore reserves</b>, requires far less energy (reducing greenhouse gas emissions), creates less pollution, and reduces the amount of waste going to landfill — key benefits for both society and the environment.' }),

  makeMCQ({ id:'g7s-sts-010', chapterId:'g7s-sts', difficulty:2, subsection:'sustainability',
    question:'What is meant by "sustainable development"?',
    options:['Development that meets the needs of the present without compromising the ability of future generations to meet their own needs','Building as many factories as possible now','Using all available resources as quickly as possible','Stopping all development permanently'],
    answer:'Development that meets the needs of the present without compromising the ability of future generations to meet their own needs',
    hint:'Balance between present use and future availability.',
    explanation:'<b>Sustainable development</b> means meeting current human needs for resources and development while preserving resources and the environment for future generations. It involves using renewable energy, recycling and reducing waste.' }),

  makeMCQ({ id:'g7s-sts-011', chapterId:'g7s-sts', difficulty:1, subsection:'science_technology',
    question:'What is the main use of communication satellites orbiting Earth?',
    options:['To relay telephone calls, internet signals and television broadcasts across long distances','To observe distant stars','To monitor volcanoes only','To control aircraft'],
    answer:'To relay telephone calls, internet signals and television broadcasts across long distances',
    hint:'They act as relay stations high above Earth.',
    explanation:'<b>Communication satellites</b> receive signals from one point on Earth and retransmit them to another. They enable global telephone calls, internet connectivity, GPS navigation and satellite television.' }),

  makeMCQ({ id:'g7s-sts-012', chapterId:'g7s-sts', difficulty:2, subsection:'sustainability',
    question:'Which of the following is the most sustainable way to deal with household waste?',
    options:['Reduce, Reuse, Recycle — in that order of priority','Burn everything in the garden','Dump it in the nearest river','Bury it in the garden'],
    answer:'Reduce, Reuse, Recycle — in that order of priority',
    hint:'The 3 Rs of waste management.',
    explanation:'The most sustainable approach is the <b>3 Rs</b>: first reduce (buy less and avoid waste), then reuse (use items again), then recycle (process materials into new products). Each step conserves more resources than the one after it.' }),

  makeMCQ({ id:'g7s-sts-013', chapterId:'g7s-sts', difficulty:3, subsection:'science_technology',
    question:'A new medicine is developed in a laboratory. Before it can be used on patients, what must happen?',
    options:['It must go through extensive clinical trials to test its safety and effectiveness in humans','It can be immediately sold to the public','The doctor can use it as soon as it looks promising','It only needs to be tested on animals'],
    answer:'It must go through extensive clinical trials to test its safety and effectiveness in humans',
    hint:'Science has ethical responsibilities — safety must come before profit.',
    explanation:'New medicines must undergo rigorous <b>clinical trials</b> — first on cells, then animals, then controlled trials on volunteers — to prove they are safe and effective before being licensed for public use. This protects patients from harm.' }),

  makeMCQ({ id:'g7s-sts-014', chapterId:'g7s-sts', difficulty:2, subsection:'discoveries',
    question:'Isaac Newton discovered the law of universal gravitation. How did this advance our understanding of the solar system?',
    options:['It explained why planets orbit the Sun and why objects fall to Earth — the same force governs both','It proved that the Sun is a star','It showed that planets are made of rock','It explained why the Moon glows'],
    answer:'It explained why planets orbit the Sun and why objects fall to Earth — the same force governs both',
    hint:'Newton realised that the force that makes an apple fall is the same force that keeps the Moon in orbit.',
    explanation:'Newton\'s law of <b>universal gravitation</b> showed that gravity acts between all masses in the universe. The same force that pulls a falling apple pulls the Moon and planets into their orbits — unifying Earth-based physics with celestial mechanics.' }),

  makeMCQ({ id:'g7s-sts-015', chapterId:'g7s-sts', difficulty:1, subsection:'science_technology',
    question:'How has astronomy benefited navigation?',
    options:['Early sailors used the positions of stars to navigate at sea; today GPS satellites give precise positioning','Astronomy created better ships','Telescopes replaced compasses','Astronomy only benefits scientists, not sailors'],
    answer:'Early sailors used the positions of stars to navigate at sea; today GPS satellites give precise positioning',
    hint:'The North Star (Polaris) guided sailors north for centuries.',
    explanation:'<b>Astronomy</b> has long guided navigation. Sailors used star positions and the Sun to determine latitude and direction. Modern GPS — a network of satellites — gives precise position anywhere on Earth, building on our understanding of orbital mechanics.' }),

  makeMCQ({ id:'g7s-sts-016', chapterId:'g7s-sts', difficulty:2, subsection:'sustainability',
    question:'Why is it important for scientists to share their findings publicly?',
    options:['So other scientists can check and build on the work, improving reliability and accelerating progress','So they can earn more money','Because the government requires it','It is not important — results should be kept secret'],
    answer:'So other scientists can check and build on the work, improving reliability and accelerating progress',
    hint:'Science is self-correcting because others repeat and verify experiments.',
    explanation:'<b>Sharing findings</b> allows peer review — other scientists check results for errors, repeat experiments and build on discoveries. This makes scientific knowledge more reliable and speeds up progress for the benefit of society.' })

);

})();
