\set ON_ERROR_STOP on
\pset pager off

CREATE OR REPLACE FUNCTION pg_temp.ck(name text, got text, want text) RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  IF got IS NOT DISTINCT FROM want THEN RAISE NOTICE '  ok   % [%]', name, got;
  ELSE RAISE EXCEPTION '  FAIL % (got %, want %)', name, got, want; END IF;
END $$;

-- The two forms PostgREST can emit. `.insert()` alone sends a plain INSERT;
-- `.insert().select()` - which the app must use, because family_code is
-- generated by the database - sends INSERT ... RETURNING.
CREATE OR REPLACE FUNCTION pg_temp.try_insert(p_owner uuid, p_name text, p_returning boolean) RETURNS text
LANGUAGE plpgsql AS $$
DECLARE v uuid;
BEGIN
  IF p_returning THEN
    INSERT INTO public.families (parent_id, family_name) VALUES (p_owner, p_name) RETURNING id INTO v;
  ELSE
    INSERT INTO public.families (parent_id, family_name) VALUES (p_owner, p_name);
  END IF;
  RETURN 'ok';
EXCEPTION WHEN insufficient_privilege THEN RETURN '42501';
          WHEN others THEN RETURN SQLSTATE;
END $$;

-- ⚠ Everything below runs as `authenticated`, never the superuser: RLS does not
--   apply to a superuser, so every check would pass vacuously.
SET ROLE authenticated;

SELECT '=== creating a family, the way the app actually does it ===';
SET test.uid = '11111111-1111-1111-1111-111111111111';
SELECT pg_temp.ck('alice may create her own family with RETURNING',
  pg_temp.try_insert('11111111-1111-1111-1111-111111111111', 'Alice Family', true), 'ok');
SELECT pg_temp.ck('...and reads it straight back',
  (SELECT count(*)::text FROM public.families), '1');

SELECT '=== the rules that must NOT have widened ===';
SET test.uid = '22222222-2222-2222-2222-222222222222';
SELECT pg_temp.ck('bob may not create a family owned by alice',
  pg_temp.try_insert('11111111-1111-1111-1111-111111111111', 'Hijack', true), '42501');
SELECT pg_temp.ck('bob sees none of alice''s family',
  (SELECT count(*)::text FROM public.families), '0');
SELECT pg_temp.ck('bob may create his own',
  pg_temp.try_insert('22222222-2222-2222-2222-222222222222', 'Bob Family', true), 'ok');

SELECT '=== an anonymous caller has no auth.uid(), so no family to own ===';
RESET ROLE;
SET ROLE anon;
SET test.uid = '';
SELECT pg_temp.ck('anon may not create a family',
  pg_temp.try_insert('11111111-1111-1111-1111-111111111111', 'Anon', true), '42501');

-- The whole reason the USING clause was widened in the first place. If this
-- regresses, the repair has undone supabase-coparent.sql instead of completing it.
SELECT '=== the co-parent read path still works ===';
RESET ROLE;
INSERT INTO public.family_members (family_id, user_id)
  SELECT id, '33333333-3333-3333-3333-333333333333' FROM public.families WHERE family_name = 'Alice Family';
SET ROLE authenticated;
SET test.uid = '33333333-3333-3333-3333-333333333333';
SELECT pg_temp.ck('carol, a co-parent who owns nothing, still sees the family',
  (SELECT count(*)::text FROM public.families), '1');
SELECT pg_temp.ck('carol may not create a family owned by alice',
  pg_temp.try_insert('11111111-1111-1111-1111-111111111111', 'Carol Hijack', true), '42501');
