'use strict';
STATIC_QUESTIONS.push(
  makeMCQ({ id: 'g9sms-pp24-001', chapterId: 'g9sms-colonial-independence', difficulty: 2,
    subsection: 'republic_1992',
    question: 'In which year did Mauritius become a republic?',
    options: ['1992', '1960', '1968', '2002'], answer: '1992',
    explanation: 'Mauritius became a republic on 12 March 1992. The post of President replaced the Governor General, making Mauritius a fully independent republic within the Commonwealth. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-002', chapterId: 'g9sms-government-welfare', difficulty: 2,
    subsection: 'head_of_state_voting',
    question: 'What is the voting age in Mauritius?',
    options: ['18', '17', '19', '20'], answer: '18',
    explanation: 'The minimum voting age in Mauritius is 18 years. All Mauritian citizens aged 18 and above are entitled to vote in national and local elections. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-003', chapterId: 'g9sms-economy-today', difficulty: 2,
    subsection: 'factors_of_production',
    question: 'Which of the following is an example of an <b>output of the production process</b> in a factory?',
    options: ['Waste', 'Capital', 'Labour', 'Raw materials'], answer: 'Waste',
    explanation: 'In the production process, inputs (capital, labour, raw materials) are transformed into outputs. Waste is a by-product output of the production process. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-004', chapterId: 'g9sms-economy-today', difficulty: 2,
    subsection: 'sectors',
    question: 'Which economic activity is part of the <b>tertiary</b> sector?',
    options: ['Tourism', 'Agriculture', 'Fishing', 'Manufacturing'], answer: 'Tourism',
    explanation: 'The tertiary sector covers services. Tourism is a service industry and part of the tertiary sector. Agriculture and fishing are primary sector activities; manufacturing is secondary. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-005', chapterId: 'g9sms-colonial-independence', difficulty: 2,
    subsection: 'parties_1967',
    question: 'Who led the Independence Party in 1967?',
    options: ['Sir Seewoosagur Ramgoolam', 'Sir Abdool Razack Mohamed', 'Sir Gaetan Duval', 'Sir Veerasamy Ringadoo'], answer: 'Sir Seewoosagur Ramgoolam',
    explanation: 'Sir Seewoosagur Ramgoolam led the Independence Party (the Labour Party coalition) that won the 1967 elections and steered Mauritius to independence in 1968. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-006', chapterId: 'g9sms-chagos-tromelin', difficulty: 2,
    subsection: 'tromelin',
    question: 'What was Tromelin named when it was discovered in 1722 by the French?',
    options: ['Ile de Sable', 'Ile Ronde', 'Ile de France', 'Ile Bourbon'], answer: 'Ile de Sable',
    explanation: 'When the French discovered Tromelin in 1722, they named it "Ile de Sable" (Island of Sand). It was later renamed Tromelin in honour of a French officer. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-007', chapterId: 'g9sms-living-conditions', difficulty: 2,
    subsection: 'education_before_reform',
    question: 'Which one of the following events occurred in 1977 in Mauritius?',
    options: ['Introduction of free secondary education', 'Strike of secondary school students', 'Imposition of a state of emergency', 'Outbreak of riots in Port Louis'], answer: 'Introduction of free secondary education',
    explanation: 'In 1977, Mauritius introduced free secondary education, making secondary schooling accessible to all Mauritian students regardless of their families\' ability to pay fees. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-008', chapterId: 'g9sms-industrialisation', difficulty: 2,
    subsection: 'mauritian_miracle',
    question: 'Which one of the following was <b>not</b> an impact of industrialisation in Mauritius?',
    options: ['Increased death rate', 'Higher life expectancy', 'Reduced birth rate', 'Change in the family structure'], answer: 'Increased death rate',
    explanation: 'Industrialisation in Mauritius led to higher life expectancy, reduced birth rate and changes in family structure — all positive social outcomes. Increased death rate was NOT an impact; death rates actually fell due to better healthcare and living standards. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-009', chapterId: 'g9sms-links', difficulty: 2,
    subsection: 'links_india_africa',
    question: 'Which country supported Mauritius in developing the Jin Fei Smart City?',
    options: ['China', 'Australia', 'India', 'Singapore'], answer: 'China',
    explanation: 'China supported the development of the Jin Fei Smart City project in Mauritius as part of its Belt and Road Initiative and growing bilateral ties with the island nation. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-010', chapterId: 'g9sms-living-conditions', difficulty: 2,
    subsection: 'health_and_disease',
    question: 'Why were children provided with milk and vitamins in the 1960s in Mauritius?',
    options: ['They suffered from malnutrition.', 'They suffered from malaria.', 'They suffered from polio.', 'They suffered from tuberculosis.'], answer: 'They suffered from malnutrition.',
    explanation: 'In the 1960s, many children in Mauritius suffered from malnutrition due to poverty and poor diet. The government provided free milk and vitamins to improve their health and nutrition. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-011', chapterId: 'g9sms-outer-islands', difficulty: 2,
    subsection: 'rodrigues',
    question: 'The inhabitants of Rodrigues are mostly engaged in ………………… as an economic activity.',
    options: ['fishing', 'textiles', 'banking', 'manufacturing'], answer: 'fishing',
    explanation: 'The inhabitants of Rodrigues are mainly engaged in fishing and agriculture. The island is known for its fishing industry and the export of seafood products. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-012', chapterId: 'g9sms-population', difficulty: 2,
    subsection: 'structure_pyramids',
    question: 'The composition of a population is referred to as population ……………….',
    options: ['structure', 'size', 'census', 'density'], answer: 'structure',
    explanation: 'Population structure refers to the composition of a population, including the distribution by age and sex. It is often represented visually using a population pyramid. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' }),

  makeMCQ({ id: 'g9sms-pp24-013', chapterId: 'g9sms-chagos-tromelin', difficulty: 2,
    subsection: 'expulsion_and_icj',
    question: 'Match each date with the correct historical event related to the Chagos Archipelago. In 1793, the Chagos Archipelago ……………….',
    options: ['French settlement began', 'became a British colony', 'Chagossians were expelled', 'ICJ hearings started'], answer: 'French settlement began',
    explanation: 'French settlement in the Chagos Archipelago began in 1793. The islands were later ceded to Britain in 1814 under the Treaty of Paris. 📄 NCE 2024 Social & Modern Studies exam.',
    learnMore: '📄 NCE 2024 Social & Modern Studies exam.' })
);
