'use strict';
(function () {

STATIC_QUESTIONS.push(

  // ── Population Studies ───────────────────────────────────────────────────

  makeMCQ({ id:'g9sms-v101', chapterId:'g9sms-population', subsection:'density_distribution', difficulty:2,
    question:'A district has a population of 240 000 and covers 80 km². What is its population density?',
    options:['3 000 people/km²','300 people/km²','30 000 people/km²','30 people/km²'],
    answer:'3 000 people/km²',
    hint:'Divide population by area.',
    explanation:'240 000 ÷ 80 = <b>3 000 people per km²</b>. Mauritius as a whole has one of the highest population densities in sub-Saharan Africa because a large population lives on a small island.' }),

  makeMCQ({ id:'g9sms-v102', chapterId:'g9sms-population', subsection:'density_distribution', difficulty:3,
    question:'Which part of Mauritius tends to have the highest population density?',
    options:['The northern coastal plain and the area around Port Louis','The forested central plateau','The eastern coast, which is the driest part of the island','Rodrigues, because it has fewer towns'],
    answer:'The northern coastal plain and the area around Port Louis',
    hint:'People cluster near the capital city and on flat, accessible land.',
    explanation:'The <b>Port Louis area and the northern coastal plain</b> are most densely populated because of proximity to the capital, economic opportunities and flat terrain. The forested plateau is less settled.' }),

  makeMCQ({ id:'g9sms-v103', chapterId:'g9sms-population', subsection:'density_distribution', difficulty:2,
    question:'What does an uneven distribution of population across districts tell a geographer?',
    options:['Some areas have more attractive conditions for living and working than others','Every district has exactly the same resources and opportunities','Population density is always highest where rainfall is greatest','Governments set rules deciding exactly how many people live in each district'],
    answer:'Some areas have more attractive conditions for living and working than others',
    hint:'People choose where to live based on available opportunities.',
    explanation:'Uneven distribution reflects <b>variations in economic opportunity, infrastructure, terrain and services</b>. People concentrate where jobs, schools, hospitals and transport are most accessible.' }),

  makeMCQ({ id:'g9sms-v104', chapterId:'g9sms-population', subsection:'density_distribution', difficulty:3,
    question:'Mauritius covers about 2 040 km² and had a population of roughly 1.3 million in 2020. Approximately what was its population density?',
    options:['637 people/km²','130 people/km²','2 040 people/km²','6 370 people/km²'],
    answer:'637 people/km²',
    hint:'1 300 000 ÷ 2 040 ≈ 637.',
    explanation:'1 300 000 ÷ 2 040 ≈ <b>637 people/km²</b>, making Mauritius one of the most densely populated countries in Africa, comparable to many European nations.' }),

  makeMCQ({ id:'g9sms-v105', chapterId:'g9sms-population', subsection:'structure_pyramids', difficulty:2,
    question:'What shape of population pyramid would have been typical of Mauritius in the 1960s?',
    options:['A wide base narrowing quickly toward the top, showing many young people','A narrow base widening toward the middle, showing few young people','A rectangular shape with equal numbers at every age','An inverted triangle with the oldest groups most numerous'],
    answer:'A wide base narrowing quickly toward the top, showing many young people',
    hint:'High birth rates in the past → many young people → wide base.',
    explanation:'High birth rates and relatively early death gave Mauritius a <b>classic wide-based pyramid</b> in the 1960s — lots of young people and relatively few elderly, typical of a developing country at that time.' }),

  makeMCQ({ id:'g9sms-v106', chapterId:'g9sms-population', subsection:'structure_pyramids', difficulty:3,
    question:'Which feature of a population pyramid shows that a country has recently experienced a "baby boom" followed by declining birth rates?',
    options:['A bulge in the middle age groups with a narrower base below it','An equal width at all age levels from 0 to 80','A very wide base that remains constant across all young age groups','A complete absence of bars for any age group under 20'],
    answer:'A bulge in the middle age groups with a narrower base below it',
    hint:'The baby boom produced a large cohort; fewer births since then produced a narrower base.',
    explanation:'A <b>bulge in the middle</b> of the pyramid represents the large baby-boom cohort. The <b>narrower base below</b> them reflects the subsequent fall in birth rates — exactly the shape Mauritius\'s pyramid shows today.' }),

  makeMCQ({ id:'g9sms-v107', chapterId:'g9sms-population', subsection:'birth_death_rates', difficulty:2,
    question:'What is the crude birth rate?',
    options:['The number of live births per 1 000 of the total population per year','The total number of babies born in a country in any given century','The percentage of women who have more than three children','The number of births minus the number of deaths in a single year'],
    answer:'The number of live births per 1 000 of the total population per year',
    hint:'It is expressed per 1 000 people per year.',
    explanation:'The <b>crude birth rate</b> is the number of live births per 1 000 of the total population in a year. "Crude" means it is not adjusted for the age structure of the population.' }),

  makeMCQ({ id:'g9sms-v108', chapterId:'g9sms-population', subsection:'birth_death_rates', difficulty:3,
    question:'Mauritius\'s crude birth rate was approximately 34 per 1 000 in 1968 and 12 per 1 000 in 2020. Which factors best explain the fall?',
    options:['Family planning, rising education levels and urbanisation','A dramatic increase in the death rate that reduced the base population','Large-scale emigration of all women of childbearing age','A government law limiting every family to one child'],
    answer:'Family planning, rising education levels and urbanisation',
    hint:'These are the standard demographic transition factors.',
    explanation:'<b>Family planning</b>, rising female education, growing female employment and urbanisation all reduce birth rates — the mechanisms behind Mauritius\'s demographic transition from the 1960s onward.' }),

  makeMCQ({ id:'g9sms-v109', chapterId:'g9sms-population', subsection:'birth_death_rates', difficulty:2,
    question:'If Mauritius has a birth rate of 12 per 1 000 and a death rate of 8 per 1 000, what is the rate of natural increase?',
    options:['4 per 1 000','20 per 1 000','96 per 1 000','1.5 per 1 000'],
    answer:'4 per 1 000',
    hint:'Natural increase = birth rate minus death rate.',
    explanation:'12 − 8 = <b>4 per 1 000</b>. This is a low natural increase, consistent with a country in the late stages of the demographic transition.' }),

  makeMCQ({ id:'g9sms-v110', chapterId:'g9sms-population', subsection:'life_expectancy', difficulty:2,
    question:'Life expectancy at birth for Mauritian women is approximately 78 years. What does this figure mean?',
    options:['A girl born today can expect, on average, to live to about 78','No woman born in Mauritius will ever live beyond 78','Every woman currently aged 78 will die within the year','Women earn 78% of the male average wage in Mauritius'],
    answer:'A girl born today can expect, on average, to live to about 78',
    hint:'Life expectancy is an average projected from current health conditions.',
    explanation:'Life expectancy at birth is an <b>average</b>: it projects, based on current mortality rates, how long a newborn is likely to live. Some individuals will live shorter lives, others longer.' }),

  makeMCQ({ id:'g9sms-v111', chapterId:'g9sms-population', subsection:'life_expectancy', difficulty:3,
    question:'Why do women in Mauritius (as in most countries) have a higher life expectancy than men?',
    options:['Biological factors and differences in risk-taking behaviour and occupational hazards','Men are required by law to retire earlier, shortening their lives','Women have access to better healthcare only from the age of 60','Men leave Mauritius permanently at age 50 on average, removing them from statistics'],
    answer:'Biological factors and differences in risk-taking behaviour and occupational hazards',
    hint:'The gender gap in life expectancy is a global pattern, not unique to Mauritius.',
    explanation:'Women have a longer life expectancy worldwide due to <b>biological advantages</b> and because men are statistically more likely to engage in <b>risky behaviour</b> and work in dangerous occupations.' }),

  makeMCQ({ id:'g9sms-v112', chapterId:'g9sms-population', subsection:'ageing', difficulty:2,
    question:'What is the main reason Mauritius has an ageing population?',
    options:['Birth rates have fallen while people live longer due to better healthcare','Birth rates have risen dramatically in the last decade','A massive wave of elderly immigrants has arrived from Europe','The government compulsorily relocated young people to Rodrigues'],
    answer:'Birth rates have fallen while people live longer due to better healthcare',
    hint:'An ageing population requires both fewer young people being born AND older people surviving longer.',
    explanation:'Mauritius has both <b>falling birth rates</b> and <b>rising life expectancy</b>. Together these produce an ageing population: the proportion aged over 60 grows as fewer children are born and people live into old age.' }),

  makeMCQ({ id:'g9sms-v113', chapterId:'g9sms-population', subsection:'ageing', difficulty:3,
    question:'Which economic challenge is directly linked to an ageing population in Mauritius?',
    options:['Funding pension and healthcare costs from a proportionally smaller working-age tax base','Building more primary schools to accommodate the rising number of children','Recruiting more young immigrants to fill unskilled manufacturing jobs','Expanding sugar production to feed a growing elderly rural population'],
    answer:'Funding pension and healthcare costs from a proportionally smaller working-age tax base',
    hint:'More old people need more support; fewer working people pay the taxes for it.',
    explanation:'As more Mauritians live into old age, the cost of <b>pensions and public healthcare</b> rises. But the working-age population that pays taxes to fund these services is proportionally shrinking, creating fiscal pressure.' }),

  // ── Migration & the Movement of People ──────────────────────────────────

  makeMCQ({ id:'g9sms-v114', chapterId:'g9sms-migration', subsection:'internal_international', difficulty:2,
    question:'A Mauritian worker moves from the village of Mahebourg to work in an office in Port Louis. What type of migration is this?',
    options:['Internal migration','International migration','Forced displacement','Circular migration between two countries'],
    answer:'Internal migration',
    hint:'Both places are in the same country.',
    explanation:'Moving within a country\'s borders is <b>internal migration</b>. Moving from Mahebourg to Port Louis stays within Mauritius, so no international border is crossed.' }),

  makeMCQ({ id:'g9sms-v115', chapterId:'g9sms-migration', subsection:'internal_international', difficulty:3,
    question:'What has been the dominant direction of internal migration in Mauritius since the 1970s?',
    options:['From rural areas to towns and cities, especially the Port Louis corridor','From towns to rural areas as people escape urban overcrowding','From the main island to Rodrigues for agricultural opportunities','From all coastal areas toward the central forest reserve'],
    answer:'From rural areas to towns and cities, especially the Port Louis corridor',
    hint:'Think about where the new factories and offices were built.',
    explanation:'EPZ factories and service sector jobs concentrated in and around <b>Port Louis and the northern urban corridor</b>, drawing workers from rural sugar estates — a classic rural-to-urban internal migration pattern.' }),

  makeMCQ({ id:'g9sms-v116', chapterId:'g9sms-migration', subsection:'push_pull', difficulty:2,
    question:'A Mauritian graduate moves to France because French universities offer better PhD programmes. Is this a push or pull factor?',
    options:['A pull factor, because the attraction is in the destination','A push factor, because something in Mauritius forced the person to leave','Both equally: push and pull factors never apply to education','Neither: education migration is not classified as migration at all'],
    answer:'A pull factor, because the attraction is in the destination',
    hint:'Ask: is the reason about fleeing the home or being drawn to the destination?',
    explanation:'Better PhD programmes at the destination draw the graduate toward France — a classic <b>pull factor</b>. Push factors would be problems at home that drive the person away.' }),

  makeMCQ({ id:'g9sms-v117', chapterId:'g9sms-migration', subsection:'push_pull', difficulty:3,
    question:'Which combination correctly pairs a push and a pull factor?',
    options:['Push: political persecution at home — Pull: democratic safety in the destination','Push: high wages in the destination — Pull: unemployment at home','Push: better climate in the destination — Pull: war at home','Push: family reunion in the destination — Pull: low wages at home'],
    answer:'Push: political persecution at home — Pull: democratic safety in the destination',
    hint:'Pushes are negative conditions at home; pulls are positive conditions at the destination.',
    explanation:'<b>Political persecution</b> (push) drives people away from home; <b>democratic safety</b> (pull) draws them to the destination. The other options have the push/pull labels reversed.' }),

  makeMCQ({ id:'g9sms-v118', chapterId:'g9sms-migration', subsection:'refugees_displacement', difficulty:2,
    question:'Under international law, which organisation is responsible for protecting refugees?',
    options:['The United Nations High Commissioner for Refugees (UNHCR)','The World Trade Organisation','Interpol, the international police agency','The International Monetary Fund'],
    answer:'The United Nations High Commissioner for Refugees (UNHCR)',
    hint:'The clue is in the title — it names refugees directly.',
    explanation:'The <b>UNHCR</b> (United Nations High Commissioner for Refugees) is the international body mandated to protect refugees and find durable solutions — repatriation, local integration or resettlement.' }),

  makeMCQ({ id:'g9sms-v119', chapterId:'g9sms-migration', subsection:'refugees_displacement', difficulty:3,
    question:'The 1951 Refugee Convention defines a refugee as a person who has fled their country due to a well-founded fear of persecution based on which grounds?',
    options:['Race, religion, nationality, political opinion or membership of a particular social group','Poverty alone, or the desire for a better-paid job in another country','Natural disaster such as a cyclone or earthquake in their home country','Failure to obtain a valid passport or travel document'],
    answer:'Race, religion, nationality, political opinion or membership of a particular social group',
    hint:'The Convention is specific about the grounds — economic hardship is not enough.',
    explanation:'The 1951 Convention protects people fleeing persecution for <b>race, religion, nationality, political opinion or membership of a particular social group</b>. Economic migrants and disaster-displaced people are not automatically covered.' }),

  // ── Rodrigues, Agalega & the Outer Islands ───────────────────────────────

  makeMCQ({ id:'g9sms-v120', chapterId:'g9sms-outer-islands', subsection:'rodrigues', difficulty:2,
    question:'Approximately how far is Rodrigues from the main island of Mauritius?',
    options:['About 560 km to the east','About 100 km to the north','About 2 000 km to the south','About 50 km to the west'],
    answer:'About 560 km to the east',
    hint:'It lies well to the east, not just offshore.',
    explanation:'Rodrigues is approximately <b>560 km east</b> of the main island — far enough that it needs its own local governance, given the distance and infrequent transport links.' }),

  makeMCQ({ id:'g9sms-v121', chapterId:'g9sms-outer-islands', subsection:'rodrigues', difficulty:3,
    question:'What is the main economic activity of Rodrigues?',
    options:['Small-scale agriculture, fishing and emerging tourism','Large-scale sugar manufacturing for export','Deep-sea oil extraction','Financial services and offshore banking'],
    answer:'Small-scale agriculture, fishing and emerging tourism',
    hint:'Rodrigues lacks the flat land and scale for sugar or the infrastructure for finance.',
    explanation:'Rodrigues relies on <b>small-scale agriculture</b> (lentils, onions, garlic), <b>fishing</b> and a growing <b>tourism</b> sector attracted by its relative isolation and natural environment.' }),

  makeMCQ({ id:'g9sms-v122', chapterId:'g9sms-outer-islands', subsection:'agalega', difficulty:2,
    question:'What traditional economic activity has historically supported the small population of Agalega?',
    options:['Coconut production and the export of copra','Deep-sea fishing for the Japanese market','Sugar cultivation on plantation estates','Tourism from Europe and South Africa'],
    answer:'Coconut production and the export of copra',
    hint:'Coconut palms dominate the landscape of both islands.',
    explanation:'Agalega\'s economy has traditionally centred on <b>coconut cultivation</b> and the export of <b>copra</b> (dried coconut meat used for oil), managed historically by the Mauritius government as a state enterprise.' }),

  makeMCQ({ id:'g9sms-v123', chapterId:'g9sms-outer-islands', subsection:'services_and_access', difficulty:3,
    question:'What is the main transport link between Rodrigues and the main island of Mauritius?',
    options:['Regular flights and a weekly cargo/passenger ship service','A bridge that was completed in the 1990s','Daily high-speed ferry from Port Louis','A submarine tunnel used by both vehicles and rail'],
    answer:'Regular flights and a weekly cargo/passenger ship service',
    hint:'For a small island 560 km away, both air and sea links are used.',
    explanation:'Rodrigues is served by <b>regular flights</b> from Sir Seewoosagur Ramgoolam Airport and a <b>weekly ship</b> (the MV Mauritius Trochetia), which carries cargo and passengers. There is no bridge or tunnel.' }),

  makeMCQ({ id:'g9sms-v124', chapterId:'g9sms-outer-islands', subsection:'services_and_access', difficulty:2,
    question:'Which service is hardest to provide adequately on the outer islands because of their remoteness?',
    options:['Specialist hospital care requiring advanced equipment','Primary school education for children aged 5–11','Religious ceremonies and community festivals','Retail shops selling basic food products'],
    answer:'Specialist hospital care requiring advanced equipment',
    hint:'Some services need large facilities that cannot exist on a small remote island.',
    explanation:'<b>Specialist hospital care</b> (surgery, intensive care, specialist consultants) requires costly equipment and staff that a small remote island cannot sustain. Patients must be evacuated to the main island, which is expensive and sometimes dangerous.' }),

  // ── Natural Hazards & the Environment ───────────────────────────────────

  makeMCQ({ id:'g9sms-v125', chapterId:'g9sms-hazards-environment', subsection:'cyclones', difficulty:2,
    question:'Which warning class indicates that a cyclone is at its most dangerous level in Mauritius?',
    options:['Class IV','Class I','Class II','Class III'],
    answer:'Class IV',
    hint:'Classes run from I to IV; the highest number is the most severe.',
    explanation:'<b>Class IV</b> is the highest alert level, indicating that a very intense cyclone is either over or very close to Mauritius. Residents must remain indoors and all outdoor activity ceases.' }),

  makeMCQ({ id:'g9sms-v126', chapterId:'g9sms-hazards-environment', subsection:'cyclones', difficulty:3,
    question:'Why are cyclones particularly damaging to small island nations like Mauritius?',
    options:['A small island has no large land mass to weaken a cyclone before it reaches settled areas','Small islands always produce stronger cyclones than large countries','Cyclones only ever form directly above small islands in the Indian Ocean','Mauritius lacks a meteorological service capable of tracking cyclones'],
    answer:'A small island has no large land mass to weaken a cyclone before it reaches settled areas',
    hint:'Think about how cyclones weaken when they cross land.',
    explanation:'Cyclones weaken when they move over land. A <b>small island</b> offers no large land mass to dissipate a storm\'s energy, so it hits settled areas close to full strength. The whole island is within the damage radius.' }),

  makeMCQ({ id:'g9sms-v127', chapterId:'g9sms-hazards-environment', subsection:'cyclones', difficulty:2,
    question:'What long-term infrastructure change followed the destructive cyclone Carol in 1960?',
    options:['A major programme to replace wood and iron housing with concrete construction','The closure of all beaches to tourism for ten years','The construction of an underground bunker network across the island','The permanent evacuation of all coastal villages to the central plateau'],
    answer:'A major programme to replace wood and iron housing with concrete construction',
    hint:'The lesson from mass destruction is to build more durably.',
    explanation:'Cyclone Carol\'s devastation accelerated a government-backed shift to <b>concrete housing</b>, which could withstand high winds far better than the traditional wood and corrugated iron structures.' }),

  makeMCQ({ id:'g9sms-v128', chapterId:'g9sms-hazards-environment', subsection:'climate_change', difficulty:3,
    question:'How does climate change threaten Mauritius\'s tourism industry specifically?',
    options:['Rising sea levels and beach erosion reduce the coastal assets that attract visitors','Climate change increases rainfall, making outdoor activities impossible year-round','Warmer temperatures drive tourists away to colder destinations exclusively','Climate change is predicted to strengthen the reef, reducing its visual appeal'],
    answer:'Rising sea levels and beach erosion reduce the coastal assets that attract visitors',
    hint:'Mauritius sells its beaches and reef — both are coastal.',
    explanation:'Tourism in Mauritius depends heavily on <b>beaches and coral reefs</b>. Rising seas erode beaches and more intense storms damage reefs, directly threatening the natural assets the industry is built on.' }),

  makeMCQ({ id:'g9sms-v129', chapterId:'g9sms-hazards-environment', subsection:'climate_change', difficulty:2,
    question:'Which commitment has Mauritius made under international climate agreements?',
    options:['To reduce greenhouse gas emissions and transition toward renewable energy','To increase coal production to diversify its energy supply','To ban all tourism as it produces too much carbon dioxide','To build a nuclear power station with French assistance'],
    answer:'To reduce greenhouse gas emissions and transition toward renewable energy',
    hint:'Small island states are among the most vulnerable to climate change and most vocal advocates for action.',
    explanation:'Mauritius is a signatory to the Paris Agreement and has committed to <b>reducing emissions</b> and expanding <b>renewable energy</b> (solar, wind) to reduce its dependence on imported fossil fuels.' }),

  makeMCQ({ id:'g9sms-v130', chapterId:'g9sms-hazards-environment', subsection:'environmental_damage', difficulty:2,
    question:'What is one measure individuals can take to reduce environmental damage in Mauritius?',
    options:['Reducing single-use plastic waste and recycling where facilities exist','Increasing car use to avoid public transport congestion','Cutting down native forest to plant more sugar cane','Releasing treated sewage directly into coastal lagoons'],
    answer:'Reducing single-use plastic waste and recycling where facilities exist',
    hint:'Individual action targets consumption choices.',
    explanation:'<b>Reducing single-use plastic</b> prevents litter from entering the ocean and harming marine life. Mauritius has introduced regulations on plastic bags as part of broader environmental policy.' }),

  makeMCQ({ id:'g9sms-v131', chapterId:'g9sms-hazards-environment', subsection:'environmental_damage', difficulty:3,
    question:'The MV Wakashio ran aground off Mauritius in 2020, causing an oil spill. What did this event highlight about the island\'s vulnerability?',
    options:['A single incident can cause catastrophic damage to a small island\'s fragile marine ecosystem','Oil spills are beneficial because they fertilise coral growth','Mauritius has such a large coastline that a spill affects very little of it','The incident proved that coral reefs are entirely immune to oil pollution'],
    answer:'A single incident can cause catastrophic damage to a small island\'s fragile marine ecosystem',
    hint:'Small places have less capacity to absorb large shocks.',
    explanation:'The Wakashio spill demonstrated that a <b>single environmental incident</b> can affect a significant proportion of a small island\'s coastline, damaging tourism, fisheries and biodiversity in ways that take years to recover.' }),

  // ── Government, Citizenship & the Welfare State ──────────────────────────

  makeMCQ({ id:'g9sms-v132', chapterId:'g9sms-government-welfare', subsection:'head_of_state_voting', difficulty:2,
    question:'How is the President of Mauritius chosen?',
    options:['Elected by the National Assembly, not by a direct popular vote','Chosen by the Prime Minister alone without any parliamentary vote','Elected directly by all citizens in a national presidential election','Appointed by the British monarch as a legacy of the colonial period'],
    answer:'Elected by the National Assembly, not by a direct popular vote',
    hint:'Mauritius is a parliamentary republic, not a presidential one.',
    explanation:'The President is <b>elected by the National Assembly</b>. Mauritius has a parliamentary system in which the Prime Minister holds executive power and the President performs a largely ceremonial role.' }),

  makeMCQ({ id:'g9sms-v133', chapterId:'g9sms-government-welfare', subsection:'head_of_state_voting', difficulty:3,
    question:'In the Mauritian electoral system, what is the "Best Loser" system designed to ensure?',
    options:['That ethnic minority communities are represented in the National Assembly','That the best-performing losing party automatically forms the government','That losing candidates in sports competitions receive a prize','That the Prime Minister is always from the party with the most seats'],
    answer:'That ethnic minority communities are represented in the National Assembly',
    hint:'It is a constitutional mechanism specific to Mauritius\'s multicultural society.',
    explanation:'The <b>Best Loser system</b> allocates up to eight additional seats to candidates from under-represented ethnic communities, helping to ensure that all major communities have a voice in Parliament.' }),

  makeMCQ({ id:'g9sms-v134', chapterId:'g9sms-government-welfare', subsection:'head_of_state_voting', difficulty:2,
    question:'How often must a general election be held in Mauritius (at most)?',
    options:['Every 5 years','Every 3 years','Every 7 years','Every 10 years'],
    answer:'Every 5 years',
    hint:'Five years is the standard parliamentary term in Commonwealth nations.',
    explanation:'The Mauritian constitution requires a general election at least <b>every 5 years</b>. The Prime Minister may call one earlier if necessary, but cannot delay beyond the five-year term.' }),

  makeMCQ({ id:'g9sms-v135', chapterId:'g9sms-government-welfare', subsection:'constitution', difficulty:2,
    question:'Which chapter of the Mauritian Constitution protects fundamental rights such as freedom of speech and religion?',
    options:['The Chapter on the Protection of Fundamental Rights and Freedoms','The Chapter on Public Finance and Taxation','The Chapter on the Appointment of Judges','The Chapter on Foreign Affairs and Trade Treaties'],
    answer:'The Chapter on the Protection of Fundamental Rights and Freedoms',
    hint:'The Constitution protects rights in a dedicated section.',
    explanation:'The <b>Chapter on the Protection of Fundamental Rights and Freedoms</b> guarantees rights including freedom of expression, freedom of religion and the right to a fair trial — enforceable through the courts.' }),

  makeMCQ({ id:'g9sms-v136', chapterId:'g9sms-government-welfare', subsection:'constitution', difficulty:3,
    question:'What happens if an Act of Parliament contradicts the Mauritian Constitution?',
    options:['The Act is declared void by the Supreme Court','The Constitution is automatically amended to accommodate the Act','The Prime Minister chooses which document to follow','The Act takes effect for five years until the next election'],
    answer:'The Act is declared void by the Supreme Court',
    hint:'The Constitution is the supreme law — no ordinary law can override it.',
    explanation:'The <b>Supreme Court</b> can strike down any Act of Parliament that contradicts the Constitution. This constitutional supremacy is the foundation of the rule of law in Mauritius.' }),

  makeMCQ({ id:'g9sms-v137', chapterId:'g9sms-government-welfare', subsection:'constitution', difficulty:2,
    question:'Which institution is responsible for interpreting the Constitution of Mauritius?',
    options:['The Supreme Court','The National Assembly','The Office of the President','The Mauritius Revenue Authority'],
    answer:'The Supreme Court',
    hint:'Courts, not politicians, interpret the law.',
    explanation:'The <b>Supreme Court</b> is the highest court in Mauritius and the body constitutionally mandated to interpret the Constitution and rule on whether legislation complies with it.' }),

  makeMCQ({ id:'g9sms-v138', chapterId:'g9sms-government-welfare', subsection:'taxes_and_mra', difficulty:2,
    question:'What type of tax is applied to goods and services purchased in Mauritius?',
    options:['Value Added Tax (VAT)','A progressive income tax only','A flat poll tax per adult per year','Import duty on all goods, including locally made ones'],
    answer:'Value Added Tax (VAT)',
    hint:'VAT is collected at each stage of production and at the point of sale.',
    explanation:'Mauritius has a <b>Value Added Tax (VAT)</b> applied to most goods and services at the point of sale. The MRA collects VAT along with income tax, customs duty and corporate tax.' }),

  makeMCQ({ id:'g9sms-v139', chapterId:'g9sms-government-welfare', subsection:'taxes_and_mra', difficulty:3,
    question:'Why is paying taxes a civic responsibility rather than just a legal obligation?',
    options:['Taxes fund the public services — schools, hospitals, roads — that benefit everyone','Taxes are paid only by the wealthy and do not affect ordinary citizens','Tax revenue goes directly to the President\'s personal account','Taxes are completely voluntary and no one is compelled to pay them'],
    answer:'Taxes fund the public services — schools, hospitals, roads — that benefit everyone',
    hint:'Think about where public services come from.',
    explanation:'Taxes are the means by which citizens collectively fund <b>public goods</b> — education, healthcare, infrastructure — that would not exist if everyone only paid for what they personally used.' }),

  makeMCQ({ id:'g9sms-v140', chapterId:'g9sms-government-welfare', subsection:'welfare_measures', difficulty:2,
    question:'When was the universal old age pension introduced in Mauritius?',
    options:['1950s — before independence','After 2000 as part of a modern reform','Only in 1992 when Mauritius became a republic','It has not yet been introduced as of 2024'],
    answer:'1950s — before independence',
    hint:'Mauritius built its welfare state remarkably early.',
    explanation:'Mauritius introduced a <b>universal old age pension</b> in the 1950s — one of the earliest such provisions in the developing world, paid to all citizens above retirement age regardless of employment history.' }),

  makeMCQ({ id:'g9sms-v141', chapterId:'g9sms-government-welfare', subsection:'welfare_measures', difficulty:3,
    question:'What makes Mauritius\'s public health system a "welfare" system?',
    options:['It provides care to all citizens free at the point of use, funded by general taxation','Patients pay a fee for every consultation and procedure','Only workers who pay into a special insurance fund receive treatment','Only children and the elderly receive free care; all adults pay full costs'],
    answer:'It provides care to all citizens free at the point of use, funded by general taxation',
    hint:'A welfare system is universal and tax-funded.',
    explanation:'Mauritius operates a <b>universal public health service</b>: any citizen can walk into a government hospital or clinic and receive treatment at no direct charge, with costs met from general tax revenue.' }),

  makeMCQ({ id:'g9sms-v142', chapterId:'g9sms-government-welfare', subsection:'rights_and_law', difficulty:2,
    question:'What does the principle of the "presumption of innocence" mean in Mauritian law?',
    options:['An accused person is assumed innocent until the court finds them guilty','A person is assumed guilty if they cannot immediately prove their innocence','Judges presume that all police reports are accurate and complete','The government presumes that every citizen is obeying the law at all times'],
    answer:'An accused person is assumed innocent until the court finds them guilty',
    hint:'This is a cornerstone of criminal law in all democratic countries.',
    explanation:'The <b>presumption of innocence</b> means the prosecution must prove guilt; the accused does not have to prove innocence. It protects citizens from arbitrary conviction.' }),

  makeMCQ({ id:'g9sms-v143', chapterId:'g9sms-government-welfare', subsection:'rights_and_law', difficulty:3,
    question:'What is the role of an independent judiciary in a democratic state like Mauritius?',
    options:['To apply the law impartially, without influence from the government or any other party','To implement the policies of whichever political party wins the election','To advise the Prime Minister on which laws to introduce to Parliament','To collect taxes on behalf of the Mauritius Revenue Authority'],
    answer:'To apply the law impartially, without influence from the government or any other party',
    hint:'Independence means judges follow the law, not politicians.',
    explanation:'An <b>independent judiciary</b> applies the law impartially: judges cannot be removed for their decisions, ensuring that even government actions can be challenged legally.' }),

  // ── Media & Communication ────────────────────────────────────────────────

  makeMCQ({ id:'g9sms-v144', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:1,
    question:'Which of the following is an example of digital (online) media?',
    options:['A news website updated in real time','A printed weekly magazine','A radio bulletin broadcast on FM','A television documentary broadcast live'],
    answer:'A news website updated in real time',
    hint:'Digital media is delivered via the internet.',
    explanation:'A <b>news website</b> is digital media — accessed online. Print, radio and television are traditional media, even when their content is also available online.' }),

  makeMCQ({ id:'g9sms-v145', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:2,
    question:'What distinguishes social media from traditional broadcast media?',
    options:['Social media allows users to both receive and produce content; traditional media is one-way','Social media is only available in printed form','Traditional media has been entirely replaced by social media since 2010','Social media is regulated more strictly than any other type of media'],
    answer:'Social media allows users to both receive and produce content; traditional media is one-way',
    hint:'Think about who can speak in each model.',
    explanation:'Traditional broadcast media is <b>one-to-many</b> (one source, many readers/viewers); social media is <b>many-to-many</b>, allowing any user to produce and share content as well as consume it.' }),

  makeMCQ({ id:'g9sms-v146', chapterId:'g9sms-media', subsection:'roles_of_media', difficulty:2,
    question:'A newspaper investigates corruption in a government ministry and publishes its findings. Which media role does this illustrate?',
    options:['The watchdog role — holding power to account','The entertainment role — amusing and distracting readers','The advertising role — promoting commercial products','The educational role — teaching readers technical skills'],
    answer:'The watchdog role — holding power to account',
    hint:'Investigating wrongdoing by those in authority is the defining watchdog function.',
    explanation:'The <b>watchdog role</b> means the press scrutinises those in power and reports wrongdoing, providing a check on government and corporate behaviour that is fundamental to democracy.' }),

  makeMCQ({ id:'g9sms-v147', chapterId:'g9sms-media', subsection:'roles_of_media', difficulty:3,
    question:'What is the risk of "media concentration" — when one owner controls most of the media?',
    options:['News may reflect the owner\'s interests rather than the public interest, reducing scrutiny of power','Competition between outlets always increases when one owner controls them all','Audiences gain access to a wider range of viewpoints and perspectives','Media concentration increases journalistic independence and reduces censorship'],
    answer:'News may reflect the owner\'s interests rather than the public interest, reducing scrutiny of power',
    hint:'An owner with business interests may not want those interests reported critically.',
    explanation:'When one owner controls multiple outlets, editorial decisions may favour the <b>owner\'s interests</b>, suppressing coverage critical of them and narrowing the range of views the public hears.' }),

  makeMCQ({ id:'g9sms-v148', chapterId:'g9sms-media', subsection:'media_and_learning', difficulty:2,
    question:'Which of the following is an example of media supporting learning positively?',
    options:['Watching a documentary on climate change as part of a geography lesson','Spending six hours a day playing online games instead of studying','Sharing exam answers on a messaging application','Reading only posts from friends rather than any educational content'],
    answer:'Watching a documentary on climate change as part of a geography lesson',
    hint:'Media supports learning when it extends or reinforces what is taught.',
    explanation:'A <b>documentary</b> used in class extends learning beyond the textbook with visuals, expert interviews and real-world examples — a productive use of media in education.' }),

  makeMCQ({ id:'g9sms-v149', chapterId:'g9sms-media', subsection:'media_and_lifestyle', difficulty:3,
    question:'Research shows a link between heavy social media use and lower self-esteem among teenagers. What mechanism best explains this?',
    options:['Comparing oneself to the idealised images others post online can create unrealistic standards','Social media physically damages the brain cells responsible for self-confidence','Low self-esteem is caused entirely by a lack of physical exercise, not by screens','Teenagers who use social media are simply less intelligent than those who do not'],
    answer:'Comparing oneself to the idealised images others post online can create unrealistic standards',
    hint:'Social media shows curated highlight reels, not everyday reality.',
    explanation:'People share their <b>best moments</b> on social media; comparing one\'s ordinary life with others\' curated highlights creates unrealistic expectations and can lower <b>self-esteem</b>.' }),

  // ── Family & Social Roles ────────────────────────────────────────────────

  makeMCQ({ id:'g9sms-v150', chapterId:'g9sms-family', subsection:'family_types', difficulty:2,
    question:'Which term describes a family in which only a single parent lives with the children?',
    options:['A lone-parent family','A nuclear family','An extended family','A reconstituted family'],
    answer:'A lone-parent family',
    hint:'One adult, not two, heads the household.',
    explanation:'A <b>lone-parent family</b> consists of one parent (mother or father) living with one or more children. It may result from separation, divorce, bereavement or a choice not to form a partnership.' }),

  makeMCQ({ id:'g9sms-v151', chapterId:'g9sms-family', subsection:'family_types', difficulty:3,
    question:'What is a "reconstituted" family?',
    options:['A family formed when two adults with children from previous relationships combine into one household','A family in which both parents work full-time outside the home','A traditional family where both parents were born on the same island','A family consisting of grandparents raising their grandchildren only'],
    answer:'A family formed when two adults with children from previous relationships combine into one household',
    hint:'Think of the prefix "re-" meaning again — a new family assembled from existing ones.',
    explanation:'A <b>reconstituted family</b> (also called blended or step-family) forms when partners who each have children from earlier relationships join together, creating a new household with step-siblings and step-parents.' }),

  makeMCQ({ id:'g9sms-v152', chapterId:'g9sms-family', subsection:'family_functions', difficulty:2,
    question:'Which of the following is an economic function of the family?',
    options:['Providing financial support and pooling income to meet household needs','Deciding the national budget and setting interest rates','Building and maintaining public roads and schools','Collecting taxes on behalf of the Mauritius Revenue Authority'],
    answer:'Providing financial support and pooling income to meet household needs',
    hint:'The economic function is about money within the family unit.',
    explanation:'Families <b>pool income</b> and share resources to pay for housing, food, education and healthcare — a fundamental economic safety net for individual members.' }),

  makeMCQ({ id:'g9sms-v153', chapterId:'g9sms-family', subsection:'family_functions', difficulty:3,
    question:'What is the "reproductive function" of the family, as sociologists define it?',
    options:['Bearing and raising children to ensure the continuation of society','Reproducing the family\'s income level in the next generation','Recreating the same family structure identically each generation','Producing goods and services for sale to other families'],
    answer:'Bearing and raising children to ensure the continuation of society',
    hint:'Reproduction here means producing the next generation, not just biology.',
    explanation:'The <b>reproductive function</b> encompasses both having children and raising them to become productive members of society — without which the population and social order could not continue.' }),

  makeMCQ({ id:'g9sms-v154', chapterId:'g9sms-family', subsection:'gender_roles', difficulty:2,
    question:'Traditional gender roles in Mauritius often assigned cooking and childcare to women. What type of factor are these roles?',
    options:['Social and cultural — they are learned, not biological','Biological — they are determined by genetics at birth','Legal — they are set by the Mauritian constitution','Economic — they are determined by the labour market only'],
    answer:'Social and cultural — they are learned, not biological',
    hint:'If roles differ between societies and change over time, they cannot be purely biological.',
    explanation:'Gender roles are <b>socially constructed</b>: they are learned through upbringing, culture and media. Because they vary across societies and have changed dramatically over decades, they are cultural rather than biological.' }),

  makeMCQ({ id:'g9sms-v155', chapterId:'g9sms-family', subsection:'women_at_work', difficulty:3,
    question:'Despite high female labour-force participation in Mauritius, women are still under-represented in senior management roles. What term describes this barrier?',
    options:['The glass ceiling','The iron curtain','The bamboo barrier','The demographic dividend'],
    answer:'The glass ceiling',
    hint:'You can see the top but cannot reach it.',
    explanation:'The <b>glass ceiling</b> describes the invisible barrier that prevents women from advancing to the highest levels of organisations, despite formal equal opportunities and visible presence in the workforce below.' }),

  // ── Social Change & Collective Behaviour ─────────────────────────────────

  makeMCQ({ id:'g9sms-v156', chapterId:'g9sms-social-change', subsection:'forces_of_change', difficulty:2,
    question:'How has globalisation acted as a force of social change in Mauritius?',
    options:['It has introduced new values, consumption patterns and cultural influences from abroad','It has caused Mauritius to completely abandon all its traditional cultural practices','It has isolated Mauritius from the rest of the world by cutting trade links','It has reduced the standard of living of all Mauritians since independence'],
    answer:'It has introduced new values, consumption patterns and cultural influences from abroad',
    hint:'Globalisation connects societies, bringing cultural exchange.',
    explanation:'<b>Globalisation</b> brings foreign media, products and ideas, changing tastes, family structures and values. In Mauritius this is visible in fashion, music, food and the growing influence of digital culture.' }),

  makeMCQ({ id:'g9sms-v157', chapterId:'g9sms-social-change', subsection:'forces_of_change', difficulty:3,
    question:'How does education act as a force of social change?',
    options:['It equips individuals with knowledge and skills that allow them to question traditions and take on new roles','It always preserves traditional society by transmitting only existing values to the next generation','It reduces social mobility by keeping people in the occupations of their parents','Education has no measurable effect on social change in any society'],
    answer:'It equips individuals with knowledge and skills that allow them to question traditions and take on new roles',
    hint:'Educated people can access new information and opportunities.',
    explanation:'Education develops critical thinking and opens access to new occupations, enabling individuals to <b>challenge inherited roles</b>, change social class and contribute to wider social transformation.' }),

  makeMCQ({ id:'g9sms-v158', chapterId:'g9sms-social-change', subsection:'social_movements', difficulty:2,
    question:'What makes a social movement different from a political party?',
    options:['A social movement seeks to change society without necessarily seeking to hold government office','A social movement is only allowed to operate during election campaigns','A social movement must be registered with the electoral commission','There is no difference — social movements and political parties are the same thing'],
    answer:'A social movement seeks to change society without necessarily seeking to hold government office',
    hint:'Environmental groups, student movements and labour unions are social movements, not parties.',
    explanation:'A <b>social movement</b> organises citizens around a cause — environmental protection, education rights, workers\' rights — without the primary aim of winning government power, which distinguishes it from a political party.' }),

  makeMCQ({ id:'g9sms-v159', chapterId:'g9sms-social-change', subsection:'deviance_and_norms', difficulty:2,
    question:'Which of the following is an example of informal social control?',
    options:['Friends and family expressing disapproval of someone\'s behaviour','A police officer arresting a person for speeding','A judge sentencing someone to community service','Parliament passing a new law against littering'],
    answer:'Friends and family expressing disapproval of someone\'s behaviour',
    hint:'Informal control uses social pressure, not law.',
    explanation:'<b>Informal social control</b> operates through social pressure — the disapproval of peers, family or community. It does not involve the formal legal system and is often more immediately powerful than the law.' }),

  makeMCQ({ id:'g9sms-v160', chapterId:'g9sms-social-change', subsection:'social_mobility', difficulty:3,
    question:'What is the difference between upward and downward social mobility?',
    options:['Upward mobility means moving to a higher social position; downward means moving to a lower one','Upward mobility means moving to a wealthier city; downward means returning to a village','Upward mobility is always permanent; downward mobility always temporary','They are opposite terms for the same experience, depending on who is reporting it'],
    answer:'Upward mobility means moving to a higher social position; downward means moving to a lower one',
    hint:'Up and down refer to social position, not physical movement.',
    explanation:'<b>Upward social mobility</b> (e.g. through education, promotion) raises a person\'s social position; <b>downward mobility</b> (e.g. through job loss, illness) lowers it. Both are possible across generations or within a lifetime.' }),

  // ── Mauritius and the World ──────────────────────────────────────────────

  makeMCQ({ id:'g9sms-v161', chapterId:'g9sms-links', subsection:'origins_of_our_people', difficulty:2,
    question:'Aapravasi Ghat in Port Louis is a UNESCO World Heritage Site. What historic role did it play?',
    options:['It was the landing point for Indian indentured labourers arriving after 1834','It was the seat of government during British colonial rule','It was the site where Mauritius\'s independence was proclaimed in 1968','It served as the main sugar export terminal until 1970'],
    answer:'It was the landing point for Indian indentured labourers arriving after 1834',
    hint:'It processed people arriving on a specific labour system.',
    explanation:'<b>Aapravasi Ghat</b> was the immigration depot through which around half a million Indian indentured labourers entered Mauritius after the abolition of slavery in 1835. Its World Heritage status recognises the indenture system as a defining migration in world history.' }),

  makeMCQ({ id:'g9sms-v162', chapterId:'g9sms-links', subsection:'origins_of_our_people', difficulty:3,
    question:'Why did the abolition of slavery in 1835 lead directly to indentured labour from India?',
    options:['Sugar estate owners needed a replacement workforce and turned to contracted labour from India','The abolition was immediately followed by full mechanisation of all sugar production','Freed slaves voluntarily chose to continue working on estates under the same conditions','Britain prohibited all further migration to Mauritius after 1835'],
    answer:'Sugar estate owners needed a replacement workforce and turned to contracted labour from India',
    hint:'Sugar production continued — so who did the work?',
    explanation:'When slavery was abolished, estate owners could no longer rely on unpaid labour. They recruited <b>indentured workers from India</b> under fixed-term contracts — a system that brought hundreds of thousands to Mauritius over the following decades.' }),

  makeMCQ({ id:'g9sms-v163', chapterId:'g9sms-links', subsection:'links_india_africa', difficulty:2,
    question:'What proportion of Mauritius\'s population today is of South Asian (mainly Indian) descent?',
    options:['About two thirds','About one quarter','About one tenth','About nine tenths'],
    answer:'About two thirds',
    hint:'The indenture system brought the largest single group to the island.',
    explanation:'Approximately <b>two thirds</b> of Mauritius\'s population descends from Indian indentured labourers — the largest group, which is why Hindi, Tamil, Telugu and Urdu are spoken alongside French, English and Creole.' }),

  makeMCQ({ id:'g9sms-v164', chapterId:'g9sms-links', subsection:'links_india_africa', difficulty:3,
    question:'How does the African diaspora maintain cultural links with Mauritius today?',
    options:['Through Creole language, Sega music and shared cultural practices rooted in the African slave experience','Through formal political unions between African states and Mauritius','Through compulsory African history lessons taught in every Mauritian school by law','Mauritius has no cultural links with Africa because all African cultural practices were lost'],
    answer:'Through Creole language, Sega music and shared cultural practices rooted in the African slave experience',
    hint:'Culture survived even when people were separated from their origins.',
    explanation:'<b>Mauritian Creole</b> and <b>Sega music</b> are rooted in the experience of enslaved Africans and Malagasy people, preserved and developed over generations as living links to African cultural heritage.' }),

  makeMCQ({ id:'g9sms-v165', chapterId:'g9sms-links', subsection:'links_europe_france', difficulty:2,
    question:'Which religion brought by French settlers remains widely practised in Mauritius today?',
    options:['Roman Catholicism','Protestantism','Sunni Islam','Eastern Orthodox Christianity'],
    answer:'Roman Catholicism',
    hint:'French colonists brought the religion of their home country.',
    explanation:'<b>Roman Catholicism</b> was introduced by French settlers and remains the religion of the majority of the general population (Creole and Franco-Mauritian communities), with major churches dating from the colonial period.' }),

  makeMCQ({ id:'g9sms-v166', chapterId:'g9sms-links', subsection:'links_europe_france', difficulty:3,
    question:'How do Mauritius\'s legal and educational systems reflect both French and British colonial legacies?',
    options:['Civil law follows the French Napoleonic Code while government and examinations follow British parliamentary and educational traditions','All laws are entirely French and all education is entirely British with no overlap','The French legacy is limited to cuisine; the British legacy covers everything else','Both systems were abolished at independence and replaced with a unique Mauritian system'],
    answer:'Civil law follows the French Napoleonic Code while government and examinations follow British parliamentary and educational traditions',
    hint:'France ruled first (law); Britain ruled second (government and schools).',
    explanation:'Mauritius has a <b>hybrid legal system</b>: civil law (property, family, contracts) follows the <b>Napoleonic Code</b> from French rule, while the <b>parliamentary system, public examinations (Cambridge) and use of English</b> reflect British rule.' }),

  makeMCQ({ id:'g9sms-v167', chapterId:'g9sms-links', subsection:'regional_organisations', difficulty:2,
    question:'What does COMESA stand for, and what type of organisation is it?',
    options:['Common Market for Eastern and Southern Africa — a regional trade bloc','Commonwealth of Middle Eastern and South Asian states — a defence alliance','Council of Mediterranean and Sub-Saharan Associations — a cultural body','Commission on Migration and Economic Security for Africa — a development fund'],
    answer:'Common Market for Eastern and Southern Africa — a regional trade bloc',
    hint:'The key word is "Common Market".',
    explanation:'<b>COMESA</b> is the Common Market for Eastern and Southern Africa, a regional economic community promoting <b>trade and investment</b> among its member states. Mauritius is a member and benefits from preferential trade access.' }),

  makeMCQ({ id:'g9sms-v168', chapterId:'g9sms-links', subsection:'regional_organisations', difficulty:3,
    question:'Why is Mauritius a member of both SADC and COMESA, two regional bodies that partly overlap geographically?',
    options:['Membership of multiple organisations maximises trade access and diplomatic influence for a small state','International law requires every African country to join all regional bodies','The two organisations have identical rules, so membership of one automatically confers membership of the other','SADC and COMESA have never had any overlapping members'],
    answer:'Membership of multiple organisations maximises trade access and diplomatic influence for a small state',
    hint:'A small country gains more from multiple memberships than from exclusivity.',
    explanation:'A small island state gains <b>wider market access and stronger diplomatic standing</b> by belonging to multiple regional bodies. Despite some duplication, each membership opens different trade preferences and forums.' }),

  makeMCQ({ id:'g9sms-v169', chapterId:'g9sms-links', subsection:'benefits_of_membership', difficulty:2,
    question:'How does membership of the Indian Ocean Commission (IOC) benefit Mauritius?',
    options:['It enables cooperation with neighbouring island states on environmental, economic and security issues','It gives Mauritius the right to claim all ocean resources within 5 000 km','It automatically settles all maritime sovereignty disputes in Mauritius\'s favour','It requires France to pay compensation for its former colonial rule'],
    answer:'It enables cooperation with neighbouring island states on environmental, economic and security issues',
    hint:'Regional bodies are about cooperation, not unilateral rights.',
    explanation:'The <b>Indian Ocean Commission</b> brings Mauritius, Réunion, Comoros, Madagascar and Seychelles together for <b>joint management</b> of environmental challenges, economic opportunities and regional security.' }),

  makeMCQ({ id:'g9sms-v170', chapterId:'g9sms-links', subsection:'benefits_of_membership', difficulty:3,
    question:'What is a preferential trade agreement and how does Mauritius benefit from having one with the European Union?',
    options:['It allows Mauritian goods to enter the EU market with lower or zero tariffs, making them more competitive than non-member exports','It requires Mauritius to buy all its imports exclusively from EU member states','It means EU countries automatically invest in Mauritian infrastructure projects','It gives Mauritius the right to set all tariff rates for goods entering the EU from any country'],
    answer:'It allows Mauritian goods to enter the EU market with lower or zero tariffs, making them more competitive than non-member exports',
    hint:'Preferential = better than the standard terms.',
    explanation:'A <b>preferential trade agreement</b> reduces tariff barriers for Mauritian exports — sugar, textiles, seafood — giving them a <b>price advantage</b> over competitors from outside the agreement in the EU market.' }),

  // ── Economy & Work Today ─────────────────────────────────────────────────

  makeMCQ({ id:'g9sms-v171', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:2,
    question:'Sugar cultivation belongs to which sector of the economy?',
    options:['The primary sector','The secondary sector','The tertiary sector','The quaternary sector'],
    answer:'The primary sector',
    hint:'The primary sector extracts or grows raw materials directly from nature.',
    explanation:'Growing sugar cane involves taking directly from the land, making it <b>primary sector</b> activity. Processing it into refined sugar would be secondary; selling it in a shop would be tertiary.' }),

  makeMCQ({ id:'g9sms-v172', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:3,
    question:'The quaternary sector is sometimes listed as a fourth economic sector. Which activity belongs to it?',
    options:['Research and development, information technology and knowledge-based services','Mining minerals from the seabed','Assembling mobile phones in a factory','Selling those phones in a retail shop'],
    answer:'Research and development, information technology and knowledge-based services',
    hint:'The quaternary sector deals in knowledge and innovation, not goods.',
    explanation:'The <b>quaternary sector</b> covers knowledge-intensive activities — ICT, research, consulting, finance. As Mauritius moves up the value chain, this sector is becoming increasingly important.' }),

  makeMCQ({ id:'g9sms-v173', chapterId:'g9sms-economy-today', subsection:'factors_of_production', difficulty:2,
    question:'Which of the four factors of production refers to human effort in the production process?',
    options:['Labour','Land','Capital','Enterprise'],
    answer:'Labour',
    hint:'It is the human input — what workers provide.',
    explanation:'<b>Labour</b> is the human effort — physical or mental — that contributes to production. Land provides natural resources; capital is machinery and buildings; enterprise is the organising and risk-taking function.' }),

  makeMCQ({ id:'g9sms-v174', chapterId:'g9sms-economy-today', subsection:'factors_of_production', difficulty:3,
    question:'A new technology company sets up in Mauritius. Which factor of production does the company\'s founding entrepreneur represent?',
    options:['Enterprise — organising the other factors and taking the risk of the venture','Labour — since the entrepreneur also works in the company','Capital — since the entrepreneur provides the startup funding','Land — since the entrepreneur owns the office building'],
    answer:'Enterprise — organising the other factors and taking the risk of the venture',
    hint:'Enterprise is the factor that brings the others together.',
    explanation:'The <b>enterprise</b> factor is provided by the entrepreneur who organises land, labour and capital, makes strategic decisions and accepts the financial risk of starting the business.' }),

  makeMCQ({ id:'g9sms-v175', chapterId:'g9sms-economy-today', subsection:'siting_a_factory', difficulty:2,
    question:'A clothing manufacturer wants to open a new factory in Mauritius. Which factor would most influence the choice of location?',
    options:['Proximity to a labour supply and good road links to the port','The colour of the buildings in the nearest village','The age of the district\'s oldest resident','The number of primary schools within 50 km'],
    answer:'Proximity to a labour supply and good road links to the port',
    hint:'Factories need workers and a way to move goods.',
    explanation:'A clothing factory needs <b>workers</b> (labour) and efficient transport to ship finished goods for export. The proximity to the port and the available workforce are the decisive practical factors.' }),

  makeMCQ({ id:'g9sms-v176', chapterId:'g9sms-economy-today', subsection:'siting_a_factory', difficulty:3,
    question:'Why has the Freeport Zone at Port Louis become an important location for warehousing and distribution businesses?',
    options:['It offers duty-free storage and handling of goods for re-export, and is adjacent to the main port','It has the highest average temperatures on the island, reducing heating costs for warehouses','It is furthest from the airport, reducing noise pollution near business premises','The government built it on the central plateau to avoid coastal flooding'],
    answer:'It offers duty-free storage and handling of goods for re-export, and is adjacent to the main port',
    hint:'A freeport zone is defined by its tax and customs status, not by geography alone.',
    explanation:'The <b>Freeport Zone</b> allows goods to be stored, processed and re-exported without paying import duties, and its location next to <b>Port Louis harbour</b> makes it ideal for logistics companies serving regional markets.' }),

  makeMCQ({ id:'g9sms-v177', chapterId:'g9sms-economy-today', subsection:'siting_a_factory', difficulty:2,
    question:'What is the term for the area around Port Louis and the north of Mauritius where most industry and commerce is concentrated?',
    options:['The urban corridor or northern belt','The sugar plateau','The ecological reserve zone','The southern fishing district'],
    answer:'The urban corridor or northern belt',
    hint:'A corridor runs between points — here, between Port Louis and the northern towns.',
    explanation:'The <b>northern urban corridor</b> (Port Louis–Beau Bassin-Rose Hill–Quatre Bornes–Vacoas-Phoenix) concentrates most of Mauritius\'s industry, commerce and services because it has the best road links, utilities and labour supply.' }),

  makeMCQ({ id:'g9sms-v178', chapterId:'g9sms-economy-today', subsection:'siting_a_factory', difficulty:3,
    question:'A pharmaceutical company is deciding where to site a new research laboratory in Mauritius. Which factor matters most for this type of facility?',
    options:['Proximity to a university and a pool of skilled science graduates','Distance from the nearest beach resort','Access to sugar cane fields for raw materials','The presence of corrugated iron buildings for cheap expansion'],
    answer:'Proximity to a university and a pool of skilled science graduates',
    hint:'A research lab needs knowledge workers, not unskilled labour.',
    explanation:'Research and development facilities are <b>knowledge-intensive</b>: they need proximity to universities and a skilled graduate workforce. Physical infrastructure and raw materials matter far less than human capital.' })

);

})();
