'use strict';
(function () {

// ══════════════════════════════════════════════════════════════════════════
//  Grade 9 Social & Modern Studies — Paper-Inspired Bank
//  IDs g9sms-pi001 – g9sms-pi080  (80 questions)
//  Source: 2025 NCE SMS paper (N570) and the MIE NCF Grades 7–9 syllabus.
//  Difficulty mix: 20 × d1 · 40 × d2 · 20 × d3
// ══════════════════════════════════════════════════════════════════════════

STATIC_QUESTIONS.push(

  // ── Government, Citizenship & the Welfare State ─────────────────────────

  makeMCQ({ id:'g9sms-pi001', chapterId:'g9sms-government-welfare', subsection:'head_of_state_voting', difficulty:1,
    question:'Who is the head of state of the Republic of Mauritius?',
    options:['The President','The Prime Minister','The Speaker of the National Assembly','The Chief Justice'],
    answer:'The President',
    hint:'The head of state is not the same as the head of government.',
    explanation:'The <b>President</b> is the constitutional head of state of the Republic of Mauritius. The Prime Minister is the head of government, responsible for running the Cabinet and day-to-day administration.' }),

  makeMCQ({ id:'g9sms-pi002', chapterId:'g9sms-government-welfare', subsection:'head_of_state_voting', difficulty:1,
    question:'Who is the head of government in Mauritius?',
    options:['The Prime Minister','The President','The Speaker of the National Assembly','The Chief Justice'],
    answer:'The Prime Minister',
    hint:'The head of government leads the Cabinet.',
    explanation:'The <b>Prime Minister</b> leads the Cabinet and is responsible for running the country\'s day-to-day government. The President is the head of state but plays a largely ceremonial role.' }),

  makeMCQ({ id:'g9sms-pi003', chapterId:'g9sms-colonial-independence', subsection:'republic_1992', difficulty:2,
    question:'In which year did Mauritius become a Republic?',
    options:['1992','1968','1975','1982'],
    answer:'1992',
    hint:'It happened 24 years after independence.',
    explanation:'Mauritius became a Republic on <b>12 March 1992</b>, replacing the Queen (represented by the Governor-General) with an elected President as head of state.' }),

  makeMCQ({ id:'g9sms-pi004', chapterId:'g9sms-government-welfare', subsection:'taxes_and_mra', difficulty:2,
    question:'What is the main function of the Mauritius Revenue Authority (MRA)?',
    options:['To collect taxes on behalf of the government','To manage the national budget','To print and issue currency','To audit government spending'],
    answer:'To collect taxes on behalf of the government',
    hint:'The MRA is a revenue-collection body.',
    explanation:'The <b>MRA</b> is responsible for the assessment and collection of taxes and other levies on behalf of the Government of Mauritius, including income tax, VAT and customs duties.' }),

  makeMCQ({ id:'g9sms-pi005', chapterId:'g9sms-government-welfare', subsection:'constitution', difficulty:1,
    question:'How many elected members does the National Assembly of Mauritius have?',
    options:['70','60','80','50'],
    answer:'70',
    hint:'Remember: sixty-two from constituencies plus eight from the Best Loser System.',
    explanation:'The <b>National Assembly</b> consists of 70 elected members: 62 representing the country\'s constituencies and 8 allocated through the Best Loser System to ensure communal balance.' }),

  makeMCQ({ id:'g9sms-pi006', chapterId:'g9sms-colonial-independence', subsection:'independence_1968', difficulty:2,
    question:'On which date does Mauritius celebrate its National Day (Independence Day)?',
    options:['12 March 1968','12 March 1992','1 January 1968','12 March 1810'],
    answer:'12 March 1968',
    hint:'The year is the same as Mauritius\'s independence; the date is a March one.',
    explanation:'Mauritius gained independence from Britain on <b>12 March 1968</b>. This date is celebrated annually as National Day, marking the birth of the independent nation.' }),

  makeMCQ({ id:'g9sms-pi007', chapterId:'g9sms-government-welfare', subsection:'constitution', difficulty:2,
    question:'Which branch of government is responsible for making laws in Mauritius?',
    options:['The Legislature (National Assembly)','The Executive (Cabinet)','The Judiciary (Courts)','The President\'s Office'],
    answer:'The Legislature (National Assembly)',
    hint:'This branch debates and votes on bills.',
    explanation:'The <b>Legislature</b> — the National Assembly — debates and passes laws. The Executive implements them and the Judiciary interprets them. This separation of powers prevents any one branch from having too much authority.' }),

  makeMCQ({ id:'g9sms-pi008', chapterId:'g9sms-government-welfare', subsection:'constitution', difficulty:2,
    question:'Which branch of government implements and enforces laws in Mauritius?',
    options:['The Executive (Cabinet and Prime Minister)','The Legislature (National Assembly)','The Judiciary (Courts)','The Electoral Commission'],
    answer:'The Executive (Cabinet and Prime Minister)',
    hint:'This branch is led by the Prime Minister.',
    explanation:'The <b>Executive</b> branch, headed by the Prime Minister and the Cabinet of Ministers, is responsible for implementing and enforcing the laws passed by the Legislature.' }),

  makeMCQ({ id:'g9sms-pi009', chapterId:'g9sms-government-welfare', subsection:'constitution', difficulty:2,
    question:'Who presides over the sittings of the National Assembly of Mauritius?',
    options:['The Speaker','The President','The Prime Minister','The Chief Justice'],
    answer:'The Speaker',
    hint:'This person is elected by members of the Assembly itself.',
    explanation:'The <b>Speaker</b> is elected by members of the National Assembly and is responsible for presiding over parliamentary sittings, maintaining order and ensuring that debates follow the rules of procedure.' }),

  makeMCQ({ id:'g9sms-pi010', chapterId:'g9sms-chagos-tromelin', subsection:'diego_garcia', difficulty:3,
    question:'Diego Garcia is an island that Mauritius claims sovereignty over. Which country currently operates a military base there?',
    options:['The United States of America','The United Kingdom','France','China'],
    answer:'The United States of America',
    hint:'The UK leased the island to an ally.',
    explanation:'The <b>USA</b> operates a major military base on Diego Garcia. The UK leased it to the USA, but Mauritius maintains that the Chagos Archipelago — of which Diego Garcia is part — was illegally detached from Mauritius before independence. The ICJ issued an advisory opinion in 2019 supporting Mauritius\'s position.' }),

  makeMCQ({ id:'g9sms-pi011', chapterId:'g9sms-government-welfare', subsection:'taxes_and_mra', difficulty:1,
    question:'Income tax is an example of which type of tax?',
    options:['A direct tax','An indirect tax','A value-added tax','A customs duty'],
    answer:'A direct tax',
    hint:'This type of tax is paid directly to the government by the person who earns the money.',
    explanation:'A <b>direct tax</b> is levied directly on an individual or organisation. Income tax — charged on a person\'s earnings — is a classic example, because the taxpayer pays it straight to the government via the MRA.' }),

  makeMCQ({ id:'g9sms-pi012', chapterId:'g9sms-government-welfare', subsection:'taxes_and_mra', difficulty:2,
    question:'Value Added Tax (VAT) is an example of which type of tax?',
    options:['An indirect tax','A direct tax','An income tax','A corporate tax'],
    answer:'An indirect tax',
    hint:'This tax is added to the price of goods; the buyer pays it without handing money directly to the government.',
    explanation:'<b>VAT</b> is an <b>indirect tax</b> collected by the seller on behalf of the government. It is built into the price of goods and services, so the consumer pays it indirectly rather than submitting it themselves to the MRA.' }),

  makeMCQ({ id:'g9sms-pi013', chapterId:'g9sms-government-welfare', subsection:'taxes_and_mra', difficulty:3,
    question:'Which of the following is a government EXPENDITURE item, not a source of government income?',
    options:['Spending on public health services','Income tax collected from workers','VAT collected on goods and services','Fees charged for government licences'],
    answer:'Spending on public health services',
    hint:'Money going OUT is not the same as money coming IN.',
    explanation:'Government <b>revenue</b> (income) comes from taxes, fees and fines. Government <b>expenditure</b> is money spent on services such as health, education, social welfare and infrastructure. Spending on public health is a use of revenue, not a source of it.' }),

  makeMCQ({ id:'g9sms-pi014', chapterId:'g9sms-government-welfare', subsection:'head_of_state_voting', difficulty:3,
    question:'Which local government body is responsible for administering RURAL areas in Mauritius?',
    options:['District Councils','Municipal Councils','Village Councils','Town Councils'],
    answer:'District Councils',
    hint:'Urban areas are served by a different type of council.',
    explanation:'Mauritius has two main tiers of local government: <b>Municipal Councils</b> govern urban towns and cities, while <b>District Councils</b> administer the rural areas. There are five district council areas outside the main municipal towns.' }),

  makeMCQ({ id:'g9sms-pi015', chapterId:'g9sms-government-welfare', subsection:'constitution', difficulty:3,
    question:'Which branch of government is responsible for interpreting laws and settling legal disputes in Mauritius?',
    options:['The Judiciary (Courts)','The Legislature (National Assembly)','The Executive (Cabinet)','The Electoral Commission'],
    answer:'The Judiciary (Courts)',
    hint:'This branch includes the Supreme Court.',
    explanation:'The <b>Judiciary</b> — made up of the courts, including the Supreme Court — interprets laws, resolves legal disputes and ensures that laws are applied fairly and in accordance with the Constitution. It is independent of the other two branches.' }),

  // ── Colonial Past & the Road to Independence ────────────────────────────

  makeMCQ({ id:'g9sms-pi016', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:1,
    question:'Which European nation were the first to settle permanently in Mauritius?',
    options:['The Dutch','The French','The British','The Portuguese'],
    answer:'The Dutch',
    hint:'They gave the island its name.',
    explanation:'The <b>Dutch</b> were the first Europeans to establish a permanent settlement in Mauritius, arriving around 1598. They named the island after Prince Maurice of Nassau, but abandoned it in 1710.' }),

  makeMCQ({ id:'g9sms-pi017', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:1,
    question:'After whom did the Dutch name the island of Mauritius?',
    options:['Prince Maurice of Nassau','King Maurice of Holland','Admiral Mauritius van Diemen','Duke Maurice of Saxony'],
    answer:'Prince Maurice of Nassau',
    hint:'He was the Stadtholder (leader) of the Netherlands at the time.',
    explanation:'The Dutch named the island <b>"Mauritius"</b> in honour of <b>Prince Maurice of Nassau</b>, the Stadtholder of the Netherlands, when they claimed it around 1598.' }),

  makeMCQ({ id:'g9sms-pi018', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:2,
    question:'In which year was slavery abolished in Mauritius?',
    options:['1835','1815','1868','1810'],
    answer:'1835',
    hint:'This was two years after the British Slavery Abolition Act was passed.',
    explanation:'Slavery was abolished in Mauritius in <b>1835</b> under British colonial rule, following the Slavery Abolition Act of 1833. Slaveholders received compensation; the enslaved people received none and were bound to an "apprenticeship" system for several more years.' }),

  makeMCQ({ id:'g9sms-pi019', chapterId:'g9sms-colonial-independence', subsection:'parties_1967', difficulty:1,
    question:'Who is known as the "Father of the Nation" in Mauritius?',
    options:['Sir Seewoosagur Ramgoolam','Sir Anerood Jugnauth','Sir Gaetan Duval','Paul Bérenger'],
    answer:'Sir Seewoosagur Ramgoolam',
    hint:'He led the party that won the 1967 election.',
    explanation:'<b>Sir Seewoosagur Ramgoolam</b> is revered as the Father of the Nation. He led the Labour Party and negotiated Mauritius\'s independence from Britain in 1968, becoming the country\'s first Prime Minister.' }),

  makeMCQ({ id:'g9sms-pi020', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:2,
    question:'What name did the French give to Mauritius when they occupied the island from 1715 to 1810?',
    options:['Île de France','Île Maurice','Fort Dauphin','Île Bourbon'],
    answer:'Île de France',
    hint:'They renamed it after their own country.',
    explanation:'When the French took possession of Mauritius in 1715, they renamed it <b>Île de France</b>. They founded Port Louis, built infrastructure and introduced slavery on a large scale. The British restored the name Mauritius after taking the island in 1810.' }),

  makeMCQ({ id:'g9sms-pi021', chapterId:'g9sms-living-conditions', subsection:'health_and_disease', difficulty:2,
    question:'Which disease was successfully eradicated in Mauritius between 1948 and 1950, leading to a significant population boom?',
    options:['Malaria','Cholera','Tuberculosis','Smallpox'],
    answer:'Malaria',
    hint:'DDT spraying was the main weapon used.',
    explanation:'The British colonial government launched a <b>malaria eradication</b> programme, mainly using DDT spraying, between 1948 and 1950. Its success dramatically reduced the death rate and caused a rapid population increase — which itself created economic difficulties in the 1960s.' }),

  makeMCQ({ id:'g9sms-pi022', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:2,
    question:'After the abolition of slavery in 1835, what system of labour was introduced in Mauritius to work on sugar plantations?',
    options:['Indentured labour','Free labour contracts','Convict labour','Seasonal migrant workers'],
    answer:'Indentured labour',
    hint:'Workers signed fixed-term contracts and were tied to their employer.',
    explanation:'<b>Indentured labourers</b>, mainly from India but also from China, Madagascar and East Africa, were brought to Mauritius on fixed-term contracts to replace the freed enslaved workers on the sugar estates. This system lasted until 1924.' }),

  makeMCQ({ id:'g9sms-pi023', chapterId:'g9sms-hazards-environment', subsection:'cyclones', difficulty:1,
    question:'Which devastating cyclone struck Mauritius in 1960, causing widespread destruction and loss of life?',
    options:['Cyclone Carol','Cyclone Gervaise','Cyclone Claudette','Cyclone Hollanda'],
    answer:'Cyclone Carol',
    hint:'This was the most destructive cyclone in living memory at the time.',
    explanation:'<b>Cyclone Carol</b> struck Mauritius in February 1960 and was one of the most destructive cyclones in the island\'s recorded history, causing many deaths and massive damage to homes and infrastructure.' }),

  makeMCQ({ id:'g9sms-pi024', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:3,
    question:'Which TWO things did the Dutch introduce to Mauritius during their period of settlement?',
    options:['Sugarcane and deer','Rice cultivation and cattle','Tea plantations and goats','Cotton farming and pigs'],
    answer:'Sugarcane and deer',
    hint:'One became the backbone of the economy for centuries; the other was introduced for hunting.',
    explanation:'The Dutch introduced <b>sugarcane</b> cultivation and <b>deer</b> to Mauritius. Sugarcane would dominate the economy for the next three centuries. They also caused the extinction of the Dodo through hunting and the introduction of invasive animals such as pigs and rats.' }),

  makeMCQ({ id:'g9sms-pi025', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:3,
    question:'Which treaty, signed in 1814, formally confirmed British sovereignty over Mauritius?',
    options:['The Treaty of Paris','The Treaty of Vienna','The Treaty of Amiens','The Treaty of Versailles'],
    answer:'The Treaty of Paris',
    hint:'This is not the 1783 treaty — the 1814 version ended the Napoleonic Wars.',
    explanation:'The <b>Treaty of Paris (1814)</b> confirmed British control over Mauritius, which Britain had captured from France in 1810. Britain agreed to respect French settlers\' language, religion and civil law — the basis of today\'s dual French–English heritage.' }),

  makeMCQ({ id:'g9sms-pi026', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:2,
    question:'In which year did the French first take possession of Mauritius and rename it Île de France?',
    options:['1715','1598','1810','1700'],
    answer:'1715',
    hint:'The Dutch had abandoned the island a few years earlier.',
    explanation:'The French East India Company took possession of Mauritius in <b>1715</b>, naming it Île de France. They developed the island significantly, founding Port Louis as its capital and turning it into an important naval base.' }),

  makeMCQ({ id:'g9sms-pi027', chapterId:'g9sms-economy-1960s', subsection:'obstacles', difficulty:3,
    question:'The main reason for the rapid population increase in Mauritius in the 1950s was:',
    options:['The eradication of malaria sharply reducing the death rate','A large influx of immigrants from India','Improved food supply from new farming methods','The end of World War II bringing men home'],
    answer:'The eradication of malaria sharply reducing the death rate',
    hint:'The birth rate stayed the same; it was the death rate that changed dramatically.',
    explanation:'The malaria eradication campaign (1948–1950) dramatically reduced the death rate. With the birth rate remaining high but deaths falling sharply, the population grew rapidly — creating the large, young workforce that led to <b>mass unemployment</b> in the 1960s.' }),

  makeMCQ({ id:'g9sms-pi028', chapterId:'g9sms-colonial-independence', subsection:'colonial_period', difficulty:2,
    question:'During which period of colonial rule was Port Louis founded and developed as the capital of Mauritius?',
    options:['The French period (1715–1810)','The Dutch period (1598–1710)','The British period (1810–1968)','The period after independence (1968–present)'],
    answer:'The French period (1715–1810)',
    hint:'The Dutch had a small settlement but left. The next power built the city.',
    explanation:'<b>Port Louis</b> was founded and developed during the <b>French colonial period</b>. The French built the harbour, the Citadel and much of the city\'s early infrastructure, and it served as the main base for the French Indian Ocean fleet.' }),

  makeMCQ({ id:'g9sms-pi029', chapterId:'g9sms-colonial-independence', subsection:'parties_1967', difficulty:2,
    question:'Which political party led the movement for Mauritian independence from Britain?',
    options:['The Mauritius Labour Party (MLP)','The Parti Mauricien Social Démocrate (PMSD)','The Mouvement Militant Mauricien (MMM)','The Mauritius Alliance'],
    answer:'The Mauritius Labour Party (MLP)',
    hint:'Its leader became the first Prime Minister.',
    explanation:'The <b>Mauritius Labour Party (MLP)</b>, led by Sir Seewoosagur Ramgoolam, was the driving force behind the independence movement. It won the 1967 general election and led Mauritius to independence on 12 March 1968.' }),

  makeMCQ({ id:'g9sms-pi030', chapterId:'g9sms-hazards-environment', subsection:'cyclones', difficulty:3,
    question:'Mauritius uses a four-class cyclone warning system. What does a Class IV warning indicate?',
    options:['Extremely dangerous cyclonic winds are expected within 12 hours','A cyclone is at least 48 hours away','A cyclone has passed and conditions are improving','Gusts of 60–90 km/h are expected'],
    answer:'Extremely dangerous winds are expected within 12 hours',
    hint:'Class IV is the highest and most urgent warning level.',
    explanation:'The Mauritian cyclone warning system runs from Class I (a potential threat within 48 hours) to <b>Class IV</b> (the highest level), signalling that extremely dangerous cyclonic winds are expected to strike within 12 hours. Class IV requires immediate shelter.' }),

  // ── Economy at Independence & Industrialisation ─────────────────────────

  makeMCQ({ id:'g9sms-pi031', chapterId:'g9sms-economy-1960s', subsection:'sugar_dependence', difficulty:1,
    question:'Which economic sector is considered the OLDEST pillar of the Mauritian economy, dating back to colonial times?',
    options:['The sugar cane sector','The tourism sector','The ICT and BPO sector','The manufacturing sector'],
    answer:'The sugar cane sector',
    hint:'The Dutch introduced the crop; the French and British expanded it.',
    explanation:'<b>Sugar cane</b> cultivation was introduced by the Dutch and became the dominant industry during the French and British colonial periods. At independence in 1968, sugar accounted for over 90% of export earnings.' }),

  makeMCQ({ id:'g9sms-pi032', chapterId:'g9sms-industrialisation', subsection:'epz_incentives', difficulty:1,
    question:'What does EPZ stand for in the context of Mauritian economic development?',
    options:['Export Processing Zone','Economic Production Zone','Extended Production Zone','Export Promotion Zone'],
    answer:'Export Processing Zone',
    hint:'It was a zone where goods were manufactured specifically for export.',
    explanation:'The <b>Export Processing Zone (EPZ)</b> was established by the EPZ Act of 1970. It attracted foreign investment into manufacturing (especially textiles and garments) by offering tax incentives and duty-free imports of raw materials for re-export as finished goods.' }),

  makeMCQ({ id:'g9sms-pi033', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:2,
    question:'Tourism in Mauritius is classified under which economic sector?',
    options:['The tertiary (service) sector','The secondary (manufacturing) sector','The primary (extractive) sector','The quaternary (knowledge) sector'],
    answer:'The tertiary (service) sector',
    hint:'Tourism provides a service rather than producing a physical good.',
    explanation:'Tourism is a service industry and belongs to the <b>tertiary sector</b>. Hotels, restaurants, guides and transport operators all provide services to visitors. Mauritius became a major tourism destination from the 1980s onwards.' }),

  makeMCQ({ id:'g9sms-pi034', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:2,
    question:'Manufacturing industries such as textile factories belong to which economic sector?',
    options:['The secondary sector','The primary sector','The tertiary sector','The quaternary sector'],
    answer:'The secondary sector',
    hint:'This sector transforms raw materials into finished goods.',
    explanation:'The <b>secondary sector</b> involves processing and manufacturing raw materials into finished goods. The EPZ textile factories — which took raw cotton and produced clothing for export — are a classic example of secondary sector activity in Mauritius.' }),

  makeMCQ({ id:'g9sms-pi035', chapterId:'g9sms-industrialisation', subsection:'mauritian_miracle', difficulty:2,
    question:'In which year was the Stock Exchange of Mauritius established?',
    options:['1989','1968','1975','2000'],
    answer:'1989',
    hint:'It was part of the development of the financial services sector in the late 1980s.',
    explanation:'The <b>Stock Exchange of Mauritius</b> was established in 1989 as Mauritius developed its financial services sector. It enables companies to raise capital by issuing shares, and is a key symbol of the country\'s economic diversification.' }),

  makeMCQ({ id:'g9sms-pi036', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:2,
    question:'What is the primary purpose of the Freeport in Mauritius?',
    options:['To warehouse and re-export goods without import duties','To allow tourists to shop without paying VAT','To provide free shipping services to local businesses','To house the national fishing fleet'],
    answer:'To warehouse and re-export goods without import duties',
    hint:'Think about the strategic position of Mauritius in the Indian Ocean trade routes.',
    explanation:'The <b>Freeport</b> allows goods to be imported, stored, processed and re-exported without the payment of customs duties. Mauritius uses its strategic location in the Indian Ocean to position itself as a regional trade and logistics hub.' }),

  makeMCQ({ id:'g9sms-pi037', chapterId:'g9sms-industrialisation', subsection:'sectors_over_time', difficulty:2,
    question:'Which economic sector is considered the MOST RECENT major pillar of the Mauritian economy?',
    options:['The ICT and BPO sector','The tourism sector','The manufacturing (EPZ) sector','The sugar cane sector'],
    answer:'The ICT and BPO sector',
    hint:'This sector grew significantly from the late 1990s and 2000s.',
    explanation:'The <b>ICT (Information and Communication Technology) and BPO (Business Process Outsourcing)</b> sector is the most recently developed pillar, growing from the late 1990s. It includes call centres, software development and data processing services.' }),

  makeMCQ({ id:'g9sms-pi038', chapterId:'g9sms-industrialisation', subsection:'sectors_over_time', difficulty:3,
    question:'Which list places the main pillars of the Mauritian economy in the correct CHRONOLOGICAL ORDER from oldest to most recent?',
    options:['Sugar cane → Manufacturing (EPZ) → Tourism → Banking & Finance → ICT/BPO','Tourism → Sugar cane → Manufacturing → ICT/BPO → Banking','Manufacturing → Sugar cane → Banking → Tourism → ICT/BPO','ICT/BPO → Banking → Tourism → Manufacturing → Sugar cane'],
    answer:'Sugar cane → Manufacturing (EPZ) → Tourism → Banking & Finance → ICT/BPO',
    hint:'Each sector was added without removing the previous ones.',
    explanation:'Sugar cane dominated from colonial times; the EPZ and manufacturing took off in the <b>1970s</b>; tourism boomed in the <b>1980s</b>; banking and financial services grew through the <b>1990s</b>; ICT and BPO became a major sector from <b>2000</b> onwards. This diversification is the core of the Mauritian Miracle.' }),

  makeMCQ({ id:'g9sms-pi039', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:2,
    question:'Which of the following activities belongs to the PRIMARY economic sector?',
    options:['Sugar cane farming','Textile manufacturing','Hotel management','Banking services'],
    answer:'Sugar cane farming',
    hint:'The primary sector harvests or extracts directly from nature.',
    explanation:'The <b>primary sector</b> involves the extraction or harvesting of natural resources. Farming, fishing and mining are all primary sector activities. Sugar cane farming — growing and cutting cane — is therefore a primary sector activity.' }),

  makeMCQ({ id:'g9sms-pi040', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:1,
    question:'Fishing belongs to which economic sector?',
    options:['The primary sector','The secondary sector','The tertiary sector','The quaternary sector'],
    answer:'The primary sector',
    hint:'This sector takes resources directly from the natural environment.',
    explanation:'Fishing involves harvesting natural resources directly from the sea, so it is classified as a <b>primary sector</b> activity, alongside agriculture and mining.' }),

  makeMCQ({ id:'g9sms-pi041', chapterId:'g9sms-government-welfare', subsection:'taxes_and_mra', difficulty:2,
    question:'What does VAT stand for?',
    options:['Value Added Tax','Variable Annual Tax','Valued Asset Tax','Voluntary Additional Tax'],
    answer:'Value Added Tax',
    hint:'It is added at each stage of production and sale.',
    explanation:'<b>VAT</b> stands for <b>Value Added Tax</b>. It is an indirect tax charged on goods and services at each stage of production and sale. In Mauritius, businesses collect VAT from customers and pass it to the MRA.' }),

  makeMCQ({ id:'g9sms-pi042', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:3,
    question:'A student argues that the ICT sector belongs to the secondary sector because it involves producing digital products. Is this correct?',
    options:['No — ICT is a tertiary (service) sector activity','Yes — digital production makes it secondary','No — ICT is a primary sector activity','Yes — technology manufacturing is always secondary'],
    answer:'No — ICT is a tertiary (service) sector activity',
    hint:'Consider what the ICT and BPO sector actually provides to its clients.',
    explanation:'ICT and BPO firms provide <b>services</b> — data processing, software support, call handling — rather than manufacturing physical goods. Services belong to the <b>tertiary sector</b>. The secondary sector requires physical transformation of raw materials into tangible products.' }),

  makeMCQ({ id:'g9sms-pi043', chapterId:'g9sms-industrialisation', subsection:'epz_incentives', difficulty:1,
    question:'The EPZ, established in Mauritius in the 1970s, was dominated mainly by which type of manufacturing?',
    options:['Textiles and garments','Sugar refining','Electronics assembly','Vehicle manufacturing'],
    answer:'Textiles and garments',
    hint:'Think about what Mauritius could produce with low-cost labour for export to Europe.',
    explanation:'The EPZ of the 1970s was dominated by <b>textiles and garment manufacturing</b>. Factories produced clothing mainly for export to Europe, creating tens of thousands of jobs, particularly for women, and reducing dependence on sugar.' }),

  makeMCQ({ id:'g9sms-pi044', chapterId:'g9sms-government-welfare', subsection:'taxes_and_mra', difficulty:3,
    question:'Which of the following is NOT a source of government REVENUE (income) in Mauritius?',
    options:['Spending on public road infrastructure','Income tax collected from employees','VAT on goods and services','Fees for government-issued business licences'],
    answer:'Spending on public road infrastructure',
    hint:'Revenue means money coming IN to the government, not money going OUT.',
    explanation:'Government revenue comes from <b>taxes</b> (income tax, VAT, corporate tax), <b>fees</b>, fines and grants. Spending on public roads is <b>government expenditure</b> — money going out — not a source of income.' }),

  makeMCQ({ id:'g9sms-pi045', chapterId:'g9sms-economy-1960s', subsection:'obstacles', difficulty:3,
    question:'Which economic challenge did Mauritius face in the 1960s as a direct consequence of the population boom that followed the malaria eradication programme?',
    options:['High unemployment caused by a rapidly growing workforce outpacing job creation','Severe food shortages resulting from over-farming of sugar land','A collapse of the sugar cane export price that destroyed the economy','Mass emigration of skilled workers leaving the island'],
    answer:'High unemployment caused by a rapidly growing workforce outpacing job creation',
    hint:'More people → more job-seekers → but the economy was still just sugar.',
    explanation:'The malaria eradication of 1948–1950 triggered a population boom. By the 1960s large numbers of young people entered the labour market, but the economy — still almost entirely dependent on sugar — could not provide enough jobs, producing <b>mass unemployment</b> and the urgent need to diversify.' }),

  // ── Family & Social Roles ────────────────────────────────────────────────

  makeMCQ({ id:'g9sms-pi046', chapterId:'g9sms-family', subsection:'family_types', difficulty:1,
    question:'Which type of family consists of two parents and their dependent children all living in the same household?',
    options:['A nuclear family','An extended family','A single-parent family','A reconstituted family'],
    answer:'A nuclear family',
    hint:'This is the smallest and most basic family unit.',
    explanation:'A <b>nuclear family</b> is made up of two parents and their dependent children living together in one household. The term comes from the idea of a "nucleus" — the central core.' }),

  makeMCQ({ id:'g9sms-pi047', chapterId:'g9sms-social-change', subsection:'deviance_and_norms', difficulty:1,
    question:'In Social Studies, what is meant by "deviance"?',
    options:['Behaviour that breaks accepted social norms','Any criminal act punishable by law','Behaviour that is mentally unusual or disturbed','Any action that causes physical harm to another person'],
    answer:'Behaviour that breaks accepted social norms',
    hint:'Deviance is broader than crime — it includes rule-breaking that may not be illegal.',
    explanation:'<b>Deviance</b> refers to behaviour that departs from what a society considers normal or acceptable. Not all deviance is illegal — some deviance simply breaks social expectations or conventions without breaking any law.' }),

  makeMCQ({ id:'g9sms-pi048', chapterId:'g9sms-family', subsection:'family_types', difficulty:2,
    question:'Which type of family includes three or more generations — such as grandparents, parents and children — living together or in close contact?',
    options:['An extended family','A nuclear family','A single-parent family','A reconstituted family'],
    answer:'An extended family',
    hint:'Three generations or more make it "extended" beyond the basic unit.',
    explanation:'An <b>extended family</b> includes multiple generations — grandparents, parents, children and sometimes aunts, uncles and cousins — living together or near one another. This type of family structure was more common in Mauritius before urbanisation and the move to smaller homes.' }),

  makeMCQ({ id:'g9sms-pi049', chapterId:'g9sms-social-change', subsection:'deviance_and_norms', difficulty:2,
    question:'Which of the following is an example of deviant behaviour?',
    options:['Smoking inside a hospital','Walking on a public footpath','Paying taxes on time','Wearing a school uniform'],
    answer:'Smoking inside a hospital',
    hint:'It breaks both a social norm AND a legal rule about permitted smoking areas.',
    explanation:'Smoking inside a hospital breaks both social expectations (hospitals are places of healing) and legal rules about designated non-smoking areas. It is therefore an example of <b>deviant behaviour</b>. The other options all describe normal, conforming behaviour.' }),

  makeMCQ({ id:'g9sms-pi050', chapterId:'g9sms-population', subsection:'ageing', difficulty:2,
    question:'From an economic perspective, how are people aged 80 and above classified?',
    options:['As economically inactive (dependent population)','As economically active (working population)','As semi-economically active part-time workers','As voluntary workers contributing without pay'],
    answer:'As economically inactive (dependent population)',
    hint:'At this age people are generally retired and no longer in the labour force.',
    explanation:'People aged 80 and above are generally retired and no longer part of the paid labour force. They are classified as <b>economically inactive</b> and form part of the <b>dependent population</b>, supported by the working-age population through pensions and services.' }),

  makeMCQ({ id:'g9sms-pi051', chapterId:'g9sms-population', subsection:'structure_pyramids', difficulty:2,
    question:'Which age group is generally considered the "economically active" population?',
    options:['15 to 64 years','0 to 14 years','65 years and above','18 to 60 years only'],
    answer:'15 to 64 years',
    hint:'This is the working-age range used in international statistics.',
    explanation:'The <b>economically active population</b> — also called the working-age population — is conventionally defined as those aged <b>15 to 64</b>. Those below 15 (children) and above 64 (elderly) are generally considered economically dependent.' }),

  makeMCQ({ id:'g9sms-pi052', chapterId:'g9sms-family', subsection:'family_types', difficulty:1,
    question:'What is a reconstituted (or blended) family?',
    options:['A family formed when one or both partners bring children from a previous relationship','A family where divorced parents live near each other to share childcare','A family consisting entirely of adopted children','A family where grandparents are the sole primary carers'],
    answer:'A family formed when one or both partners bring children from a previous relationship',
    hint:'It is "blended" because children from different families are combined.',
    explanation:'A <b>reconstituted or blended family</b> is formed when two people come together in a new relationship, and one or both bring children from a previous relationship. The children may become step-siblings within the new household.' }),

  makeMCQ({ id:'g9sms-pi053', chapterId:'g9sms-family', subsection:'women_at_work', difficulty:2,
    question:'In Mauritius in the 1940s, where did most working women labour?',
    options:['In the sugar cane fields','In textile factories','In government offices','In schools as teachers'],
    answer:'In the sugar cane fields',
    hint:'The economy was almost entirely based on one crop at this time.',
    explanation:'In the 1940s the Mauritian economy was almost entirely dependent on <b>sugar cane</b>. Most working women laboured in the cane fields as agricultural workers. Women\'s roles changed dramatically from the 1970s when EPZ textile factories offered factory work.' }),

  makeMCQ({ id:'g9sms-pi054', chapterId:'g9sms-government-welfare', subsection:'welfare_measures', difficulty:2,
    question:'In Mauritius, textbooks are provided free of charge to pupils at which level of education?',
    options:['Primary school level','Secondary school level','University level','All levels of education'],
    answer:'Primary school level',
    hint:'Free, compulsory primary education is a constitutional right.',
    explanation:'The government of Mauritius provides free textbooks to all <b>primary school</b> pupils as part of its commitment to free and compulsory primary education. This policy reduces financial barriers and ensures that every child has access to learning materials.' }),

  makeMCQ({ id:'g9sms-pi055', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:3,
    question:'Facebook and YouTube are classified under which type of media?',
    options:['New Age Digital media','Electronic media','Print media','Broadcast media'],
    answer:'New Age Digital media',
    hint:'They are internet-based and allow users to create content as well as consume it.',
    explanation:'Social media platforms such as Facebook and YouTube are classified as <b>New Age Digital media</b>. They are internet-based and allow two-way interaction, unlike traditional electronic media (TV and radio), which broadcasts one-way to a passive audience.' }),

  makeMCQ({ id:'g9sms-pi056', chapterId:'g9sms-links', subsection:'origins_of_our_people', difficulty:2,
    question:'With which of the following groups of countries does Mauritius have the STRONGEST historical and cultural links due to colonisation and migration?',
    options:['India, France and the United Kingdom','China, Portugal and Spain','South Africa, Australia and Canada','Egypt, Kenya and Nigeria'],
    answer:'India, France and the United Kingdom',
    hint:'Consider who colonised the island and where the labour force came from.',
    explanation:'Mauritius was colonised first by France (1715–1810) and then by Britain (1810–1968). Indentured labourers from India formed the largest ethnic community. These three countries therefore have the strongest historical ties with Mauritius — reflected in its languages, legal system and cultural practices.' }),

  makeMCQ({ id:'g9sms-pi057', chapterId:'g9sms-social-change', subsection:'deviance_and_norms', difficulty:3,
    question:'Which statement best describes the difference between deviance and crime?',
    options:['All deviance breaks social norms, but only some deviance is also criminal (illegal)','Crime and deviance mean exactly the same thing in Social Studies','Deviance is always more serious and harmful than crime','Only adults can commit deviant acts, while children can only commit crimes'],
    answer:'All deviance breaks social norms, but only some deviance is also criminal (illegal)',
    hint:'Crime is a subset of deviance — the overlap where a behaviour is also against the law.',
    explanation:'<b>Deviance</b> is a broader concept covering any behaviour that breaks social norms, whether legal or not. <b>Crime</b> is a specific type of deviance that also breaks a law. For example, speaking rudely is deviant but not criminal; theft is both deviant and criminal.' }),

  makeMCQ({ id:'g9sms-pi058', chapterId:'g9sms-family', subsection:'family_types', difficulty:2,
    question:'Which type of family consists of one parent living with and raising their dependent children alone?',
    options:['A single-parent family','An extended family','A nuclear family','A reconstituted family'],
    answer:'A single-parent family',
    hint:'This family has only one adult parent present in the home.',
    explanation:'A <b>single-parent family</b> (also called a lone-parent family) consists of one parent — either the mother or the father — raising one or more children without a partner in the household. The number of single-parent families in Mauritius has grown in recent decades.' }),

  makeMCQ({ id:'g9sms-pi059', chapterId:'g9sms-economy-today', subsection:'sectors', difficulty:3,
    question:'Manufacturing industries such as textile factories belong to which economic sector, and why?',
    options:['The secondary sector, because they transform raw materials into finished goods','The primary sector, because they use natural resources','The tertiary sector, because they provide employment services to the economy','The quaternary sector, because they use modern technology in production'],
    answer:'The secondary sector, because they transform raw materials into finished goods',
    hint:'Think about what the factory does to the raw material.',
    explanation:'The <b>secondary sector</b> involves transforming raw materials (such as cotton fibre) into manufactured finished products (such as garments). This transformation process — from natural resource to usable product — is the defining feature of secondary sector activity.' }),

  makeMCQ({ id:'g9sms-pi060', chapterId:'g9sms-living-conditions', subsection:'housing_transport', difficulty:2,
    question:'What type of houses did most ordinary Mauritian families live in during the 1940s?',
    options:['Straw (thatched) houses','Concrete block houses','Wooden houses with tiled roofs','Stone-walled houses'],
    answer:'Straw (thatched) houses',
    hint:'Housing was basic; the economy was poor at that time.',
    explanation:'In the 1940s, most ordinary Mauritian families lived in simple <b>straw or thatched houses</b>. These were cheap to build but offered little protection from cyclones or heavy rain. Concrete housing became more widespread from the 1960s and 1970s as living standards improved.' }),

  makeMCQ({ id:'g9sms-pi061', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:1,
    question:'Television is classified as which type of media?',
    options:['Electronic media','Print media','New Age Digital media','Social media'],
    answer:'Electronic media',
    hint:'It transmits information using electrical signals over the airwaves or a cable.',
    explanation:'Television is classified as <b>electronic media</b>, along with radio and mobile phones. Electronic media transmits information using electrical signals. This is distinct from print media (newspapers, books) and New Age Digital media (internet, social networks).' }),

  makeMCQ({ id:'g9sms-pi062', chapterId:'g9sms-social-change', subsection:'deviance_and_norms', difficulty:3,
    question:'A student argues that exceeding the speed limit is only deviant, not criminal, because no one was hurt. Is this argument correct?',
    options:['No — exceeding the speed limit is both deviant AND criminal, regardless of whether harm occurred','Yes — an act is only criminal if it causes direct harm to another person','Yes — traffic violations are matters of social norms, not law','No — speeding is only criminal if it leads to an accident'],
    answer:'No — exceeding the speed limit is both deviant AND criminal, regardless of whether harm occurred',
    hint:'Breaking a law is a crime regardless of the outcome.',
    explanation:'Speeding breaks both a social norm (safe driving) and a specific law (the Road Traffic Act). A crime is defined by <b>breaking a law</b>, not by whether harm results. The student confuses the legal definition of crime with the civil concept of harm or negligence.' }),

  // ── Rodrigues, Agalega & the Outer Islands ──────────────────────────────

  makeMCQ({ id:'g9sms-pi063', chapterId:'g9sms-outer-islands', subsection:'services_and_access', difficulty:1,
    question:'What is the name of the highest mountain peak in Mauritius, reaching approximately 828 metres above sea level?',
    options:['Piton de la Petite Rivière Noire','Le Pouce','Corps de Garde','Piton du Milieu'],
    answer:'Piton de la Petite Rivière Noire',
    hint:'It is located in the Black River Gorges National Park in the south-west.',
    explanation:'<b>Piton de la Petite Rivière Noire</b>, located in the Black River Gorges National Park, is the highest peak in Mauritius at approximately <b>828 metres</b> above sea level.' }),

  makeMCQ({ id:'g9sms-pi064', chapterId:'g9sms-hazards-environment', subsection:'cyclones', difficulty:2,
    question:'During which months does the cyclone season in the Indian Ocean pose a risk to Mauritius?',
    options:['November to April','May to October','June to September','January to June'],
    answer:'November to April',
    hint:'This is the Southern Hemisphere summer — when the sea is warmest.',
    explanation:'The cyclone season in the south-west Indian Ocean runs from <b>November to April</b>. Warm sea surface temperatures during this period provide the energy that generates tropical cyclones. Mauritius lies in the path of cyclones forming in this region.' }),

  makeMCQ({ id:'g9sms-pi065', chapterId:'g9sms-outer-islands', subsection:'agalega', difficulty:1,
    question:'Which outer island of Mauritius is located approximately 1,000 km north of the main island, closer to the African continent?',
    options:['Agalega','Rodrigues','St Brandon (Cargados Carajos)','Tromelin'],
    answer:'Agalega',
    hint:'It consists of two small islands joined by a sandbar.',
    explanation:'<b>Agalega</b> is a dependency of Mauritius consisting of two small islands — North Agalega and South Agalega — located about 1,000 km north of the main island of Mauritius. It has a small resident population and relies on inter-island shipping for supplies.' }),

  makeMCQ({ id:'g9sms-pi066', chapterId:'g9sms-hazards-environment', subsection:'environmental_damage', difficulty:2,
    question:'What is the main function of the coral reef surrounding Mauritius?',
    options:['It acts as a natural barrier, protecting the coastline from the full force of ocean waves','It provides deep-sea fishing grounds for commercial trawlers','It prevents foreign ships from sailing into Mauritian territorial waters','It filters seawater to make it suitable for drinking'],
    answer:'It acts as a natural barrier, protecting the coastline from the full force of ocean waves',
    hint:'The lagoon it creates is calm because the reef breaks the incoming swells.',
    explanation:'The coral reef creates a sheltered <b>lagoon</b> around much of Mauritius that acts as a natural barrier, breaking the force of ocean waves before they reach the shore. This protects the beaches and coastline from erosion and storm damage, and supports the tourism industry.' }),

  makeMCQ({ id:'g9sms-pi067', chapterId:'g9sms-outer-islands', subsection:'rodrigues', difficulty:2,
    question:'Rodrigues is an island located east of Mauritius. It forms part of which country?',
    options:['The Republic of Mauritius','The Republic of France','The United Kingdom','The Republic of Madagascar'],
    answer:'The Republic of Mauritius',
    hint:'It has its own Regional Assembly but is not independent.',
    explanation:'<b>Rodrigues</b> is located about 560 km east of the main island of Mauritius. It is an autonomous region and forms an integral part of the <b>Republic of Mauritius</b>, with its own elected Regional Assembly dealing with local matters.' }),

  makeMCQ({ id:'g9sms-pi068', chapterId:'g9sms-outer-islands', subsection:'services_and_access', difficulty:3,
    question:'Which of the following islands is NOT part of the territory of the Republic of Mauritius?',
    options:['Réunion','Rodrigues','Agalega','St Brandon (Cargados Carajos Shoals)'],
    answer:'Réunion',
    hint:'One of these islands belongs to France, not Mauritius.',
    explanation:'<b>Réunion</b> is a French overseas territory (département) and is not part of Mauritius. Rodrigues, Agalega and St Brandon (Cargados Carajos Shoals) are all dependencies of the Republic of Mauritius. Mauritius also claims the Chagos Archipelago (including Diego Garcia).' }),

  makeMCQ({ id:'g9sms-pi069', chapterId:'g9sms-hazards-environment', subsection:'climate_change', difficulty:2,
    question:'What is the main cause of coral bleaching in the waters around Mauritius?',
    options:['Rising sea temperatures linked to climate change','Over-fishing removing the fish that clean the coral reef','Oil pollution from shipping lanes crossing the Indian Ocean','Excessive tourism and physical contact with the reef'],
    answer:'Rising sea temperatures linked to climate change',
    hint:'Coral bleaches when it expels the algae that give it colour and food.',
    explanation:'Coral bleaching occurs when water temperatures rise above normal. The coral expels the symbiotic algae (zooxanthellae) that give it colour and nutrients, turning white and becoming vulnerable to disease. <b>Rising sea temperatures caused by climate change</b> are the primary cause of widespread bleaching events.' }),

  makeMCQ({ id:'g9sms-pi070', chapterId:'g9sms-links', subsection:'regional_organisations', difficulty:3,
    question:'Mauritius is located in the Indian Ocean. Why is this location strategically important for the country\'s economy?',
    options:['It allows Mauritius to serve as a trade and financial hub between Africa, Asia and Australia','It gives Mauritius control over the main oil shipping routes between the Gulf and Europe','It provides Mauritius with access to the richest deep-sea mineral deposits in the world','It positions Mauritius as the main refuelling stop for transpacific airline routes'],
    answer:'It allows Mauritius to serve as a trade and financial hub between Africa, Asia and Australia',
    hint:'Think about what lies to the west, north and east of Mauritius.',
    explanation:'Mauritius is situated in the south-west Indian Ocean, roughly equidistant between Africa, Asia and Australia. This strategic location has historically made it an important port of call for trade ships, and today supports its role as a <b>financial, logistics and trade hub</b> for the region.' }),

  makeMCQ({ id:'g9sms-pi071', chapterId:'g9sms-outer-islands', subsection:'agalega', difficulty:2,
    question:'Agalega consists of two small islands located north of Mauritius. What is its administrative status?',
    options:['An outer island dependency of the Republic of Mauritius','An autonomous republic within the African Union','A French protectorate administered by Mauritius','An uninhabited nature reserve managed by the UN'],
    answer:'An outer island dependency of the Republic of Mauritius',
    hint:'It is governed from Port Louis, not independently.',
    explanation:'<b>Agalega</b> is an outer island dependency of the Republic of Mauritius, located about 1,000 km north of the main island. It has a small resident population and falls under the direct administration of the Government of Mauritius.' }),

  makeMCQ({ id:'g9sms-pi072', chapterId:'g9sms-hazards-environment', subsection:'environmental_damage', difficulty:2,
    question:'The coral reef around Mauritius creates a sheltered body of calm water between the reef and the shoreline. What is this body of water called?',
    options:['A lagoon','A bay','A strait','A sound'],
    answer:'A lagoon',
    hint:'Its calm turquoise colour is one of Mauritius\'s most famous natural features.',
    explanation:'A <b>lagoon</b> is a shallow body of water separated from the open sea by a coral reef, sandbar or similar natural barrier. The coral reef surrounding much of Mauritius creates a beautiful turquoise lagoon that protects beaches, supports marine life and attracts tourists.' }),

  // ── Media & Communication ────────────────────────────────────────────────

  makeMCQ({ id:'g9sms-pi073', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:1,
    question:'Which of the following is an example of PRINT media?',
    options:['A daily newspaper','A television news programme','A Facebook post','A radio broadcast'],
    answer:'A daily newspaper',
    hint:'Print media is physically printed on paper.',
    explanation:'<b>Print media</b> refers to physically printed materials such as newspapers, magazines, books and journals. A daily newspaper is a classic example. Print media is the oldest category of mass media.' }),

  makeMCQ({ id:'g9sms-pi074', chapterId:'g9sms-media', subsection:'roles_of_media', difficulty:2,
    question:'Which of the following is NOT one of the main roles of the media in society?',
    options:['To set prices for goods and services','To inform the public about news and events','To educate people on important issues','To entertain audiences'],
    answer:'To set prices for goods and services',
    hint:'Pricing is decided by markets and businesses, not by media organisations.',
    explanation:'The main roles of the media are to <b>inform, educate, entertain</b> and influence public opinion. Setting prices for goods and services is not a media function — that is determined by market forces, businesses and government policy.' }),

  makeMCQ({ id:'g9sms-pi075', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:2,
    question:'Which of the following is an example of ELECTRONIC media?',
    options:['A television programme','A printed magazine','A published novel','A handwritten community newsletter'],
    answer:'A television programme',
    hint:'Electronic media uses electrical signals or radio waves to transmit information.',
    explanation:'<b>Electronic media</b> transmits information through electronic means — radio waves, electrical cables or satellite signals. Television programmes, radio broadcasts and mobile phone calls are all examples. This distinguishes them from printed materials.' }),

  makeMCQ({ id:'g9sms-pi076', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:1,
    question:'Which of the following is an example of New Age Digital media?',
    options:['YouTube','A printed textbook','A radio station','A television channel'],
    answer:'YouTube',
    hint:'It is internet-based and allows users to upload and comment as well as watch.',
    explanation:'<b>YouTube</b> is a New Age Digital media platform accessed via the internet. New Age Digital media includes social networks, websites, streaming platforms and apps that allow users to both consume and create content interactively.' }),

  makeMCQ({ id:'g9sms-pi077', chapterId:'g9sms-media', subsection:'roles_of_media', difficulty:2,
    question:'What does "freedom of the press" mean?',
    options:['The right of journalists and media organisations to publish information without government censorship','The right of all citizens to receive free printed newspapers','The right of the government to approve or block what is published','The right of journalists to enter any private property to gather news'],
    answer:'The right of journalists and media organisations to publish information without government censorship',
    hint:'Freedom of the press is a fundamental democratic right.',
    explanation:'<b>Freedom of the press</b> means that journalists, editors and media organisations can report, comment and publish information without prior restraint or censorship by the government. It is a cornerstone of democratic societies and is protected in constitutions and charters of rights.' }),

  makeMCQ({ id:'g9sms-pi078', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:3,
    question:'A student classifies a mobile phone as "print media" because it can display text messages. Is this classification correct?',
    options:['No — a mobile phone is electronic media because it transmits information electronically','Yes — because it displays text, it is a form of print media','No — a mobile phone is New Age Digital media only, not electronic media','Yes — any device that displays written text belongs to print media'],
    answer:'No — a mobile phone is electronic media because it transmits information electronically',
    hint:'The medium of transmission, not the content type, determines the category.',
    explanation:'A mobile phone is classified as <b>electronic media</b> because it transmits and receives information using electronic signals. <b>Print media</b> refers specifically to physically printed materials (newspapers, books, magazines). A mobile phone can also access New Age Digital media through apps and the internet, but its core classification is electronic.' }),

  makeMCQ({ id:'g9sms-pi079', chapterId:'g9sms-media', subsection:'types_of_media', difficulty:3,
    question:'Which of the following correctly matches each medium to its media type?',
    options:['Newspaper → Print; Radio → Electronic; Facebook → New Age Digital','Television → Print; Newspaper → Electronic; Instagram → New Age Digital','Radio → New Age Digital; Newspaper → Electronic; Television → Print','Facebook → Electronic; Newspaper → New Age Digital; Radio → Print'],
    answer:'Newspaper → Print; Radio → Electronic; Facebook → New Age Digital',
    hint:'Think about the physical form each medium takes and how it transmits information.',
    explanation:'<b>Newspapers</b> are print media (physically printed on paper). <b>Radio</b> is electronic media (transmits sound via radio waves). <b>Facebook</b> is New Age Digital media (internet-based, interactive social platform). This three-way classification is the one used in the NCE SMS syllabus.' }),

  makeMCQ({ id:'g9sms-pi080', chapterId:'g9sms-media', subsection:'roles_of_media', difficulty:2,
    question:'In what way can the media influence public opinion in a democratic society?',
    options:['By shaping how people perceive events through the stories it chooses to cover and how it frames them','By directly instructing citizens on how to vote in elections','By enforcing laws and punishing those who break social norms','By setting official government policy on national issues'],
    answer:'By shaping how people perceive events through the stories it chooses to cover and how it frames them',
    hint:'The media does not have legal power — its influence works through ideas.',
    explanation:'The media influences public opinion through <b>agenda-setting</b> (choosing which stories to cover) and <b>framing</b> (deciding how to present them). This shapes what people think about and how they think about it. However, the media does not have the power to enforce laws or set government policy directly.' })

);

})();
