'use strict';
(function () {
STATIC_QUESTIONS.push(

  makeMCQ({ id:'g7fr-hd-001', chapterId:'g7fr-co', subsection:'type_texte_oral', difficulty:4,
    question:'Vous entendez dans un haut-parleur : <i>&laquo; Le car &agrave; destination de Curepipe partira du quai num&eacute;ro 3 avec dix minutes de retard. Les passagers sont pri&eacute;s de patienter. &raquo;</i> De quel type de texte oral s\'agit-il ?',
    options:['une annonce faite dans une gare routière','un bulletin météorologique très détaillé','un dialogue entre deux amis de la classe','une publicité pour une agence de voyages'],
    answer:'une annonce faite dans une gare routière',
    hint:'Demandez-vous qui parle, &agrave; qui, et dans quel lieu : le message s\'adresse &agrave; tous les voyageurs &agrave; la fois.',
    explanation:'Un seul locuteur informe un public nombreux d\'un changement pratique (quai, retard) : c\'est une <b>annonce</b> publique. Aucun &eacute;change entre deux personnes ni argument de vente n\'appara&icirc;t.' }),

  makeMCQ({ id:'g7fr-hd-002', chapterId:'g7fr-co', subsection:'type_texte_oral', difficulty:4,
    question:'La radio diffuse : <i>&laquo; Un avis de fortes pluies est en vigueur. La population des r&eacute;gions basses est invit&eacute;e &agrave; ne pas traverser les rivi&egrave;res. &raquo;</i> Ce texte oral est :',
    options:['un communiqué officiel de sécurité','une conversation téléphonique privée','un extrait d\'un conte traditionnel','une critique de film à la radio'],
    answer:'un communiqué officiel de sécurité',
    hint:'Le message vient d\'une autorit&eacute; et s\'adresse &agrave; toute la population, pas &agrave; une personne pr&eacute;cise.',
    explanation:'Un avis impersonnel qui informe et recommande une conduite &agrave; toute la population est un <b>communiqu&eacute;</b> officiel. Un &eacute;change priv&eacute; ou un conte n\'emploieraient jamais &laquo; est en vigueur &raquo;.' }),

  makeMCQ({ id:'g7fr-hd-003', chapterId:'g7fr-co', subsection:'type_texte_oral', difficulty:3,
    question:'Vous entendez : <i>&laquo; — Et depuis quand pratiquez-vous la p&ecirc;che au large, monsieur ? — Depuis l\'&acirc;ge de quinze ans, quand mon p&egrave;re m\'emmenait. &raquo;</i> Ce texte oral est :',
    options:['une interview','une recette de cuisine','un monologue','un mode d\'emploi'],
    answer:'une interview',
    hint:'Une personne pose les questions, l\'autre raconte son exp&eacute;rience.',
    explanation:'L\'alternance question / r&eacute;ponse, avec un locuteur qui interroge et un autre qui t&eacute;moigne, est la marque de l\'<b>interview</b>. Un monologue n\'aurait qu\'une seule voix.' }),

  makeMCQ({ id:'g7fr-hd-004', chapterId:'g7fr-co', subsection:'type_texte_oral', difficulty:4,
    question:'Un vendeur annonce : <i>&laquo; Profitez-en vite : chez nous, la mangue de saison est &agrave; vingt roupies le kilo, mais seulement jusqu\'&agrave; samedi ! &raquo;</i> Quel indice montre qu\'il s\'agit d\'une publicit&eacute; et non d\'une simple information ?',
    options:['l\'appel direct au client et l\'urgence de l\'offre','la mention d\'un prix précis exprimé en roupies mauriciennes','le nom d\'un fruit connu de tous les Mauriciens','l\'emploi du présent de l\'indicatif dans la phrase'],
    answer:'l\'appel direct au client et l\'urgence de l\'offre',
    hint:'Une information se contente de dire ; une publicit&eacute; pousse &agrave; agir tout de suite.',
    explanation:'Un prix ou un pr&eacute;sent de l\'indicatif se rencontre aussi dans une simple information. Ce qui fait la <b>publicit&eacute;</b>, c\'est l\'interpellation du client (&laquo; profitez-en &raquo;) et la limite de temps qui cr&eacute;e l\'urgence.' }),

  makeMCQ({ id:'g7fr-hd-005', chapterId:'g7fr-co', subsection:'locuteur_message', difficulty:4,
    question:'Vous entendez : <i>&laquo; Je vous rappelle que les cahiers doivent &ecirc;tre remis lundi, sans exception ; ceux qui &eacute;taient absents viendront me voir &agrave; la r&eacute;cr&eacute;ation. &raquo;</i> Qui parle, et &agrave; qui ?',
    options:['un enseignant qui s\'adresse à sa classe','un surveillant qui explique le règlement aux parents','un élève qui parle à ses camarades','un bibliothécaire qui range des livres'],
    answer:'un enseignant qui s\'adresse à sa classe',
    hint:'Qui peut exiger la remise des cahiers et convoquer un &eacute;l&egrave;ve &agrave; la r&eacute;cr&eacute;ation ?',
    explanation:'Le locuteur donne une consigne de travail et fixe un rendez-vous aux &eacute;l&egrave;ves absents : seul un <b>enseignant</b> devant sa classe parle ainsi. Un camarade n\'aurait pas cette autorit&eacute;.' }),

  makeMCQ({ id:'g7fr-hd-006', chapterId:'g7fr-co', subsection:'locuteur_message', difficulty:4,
    question:'Un professeur annonce : <i>&laquo; Nous sommes d&eacute;sol&eacute;s, mais la sortie au Jardin de Pamplemousses est report&eacute;e : le car est tomb&eacute; en panne ce matin. &raquo;</i> Quel est le message essentiel ?',
    options:['la sortie aura lieu plus tard, à cause d\'une panne','la sortie est définitivement annulée pour cette année','le car est arrivé en retard au Jardin de Pamplemousses','les élèves doivent payer eux-mêmes le transport'],
    answer:'la sortie aura lieu plus tard, à cause d\'une panne',
    hint:'Attention au sens exact du mot &laquo; report&eacute;e &raquo;.',
    explanation:'&laquo; Report&eacute;e &raquo; veut dire remise &agrave; une date ult&eacute;rieure, et non <b>annul&eacute;e</b>. La cause donn&eacute;e est la panne du car ; rien n\'est dit d\'un paiement.' }),

  makeMCQ({ id:'g7fr-hd-007', chapterId:'g7fr-co', subsection:'locuteur_message', difficulty:4,
    question:'Un fr&egrave;re dit &agrave; sa s&oelig;ur : <i>&laquo; Tu as encore laiss&eacute; la fen&ecirc;tre ouverte pendant l\'averse... Bravo ! &raquo;</i> Quelle est son intention ?',
    options:['il exprime un reproche sur un ton ironique','il demande poliment que la fenêtre soit fermée','il félicite sincèrement sa sœur','il pose une question à sa sœur'],
    answer:'il exprime un reproche sur un ton ironique',
    hint:'Le mot &laquo; Bravo &raquo; ne veut pas toujours dire ce qu\'il semble dire.',
    explanation:'Les points de suspension et le contexte (une fen&ecirc;tre ouverte sous la pluie) montrent que &laquo; Bravo &raquo; est dit &agrave; l\'envers : c\'est de l\'<b>ironie</b>, donc un reproche d&eacute;guis&eacute;.' }),

  makeMCQ({ id:'g7fr-hd-008', chapterId:'g7fr-co', subsection:'locuteur_message', difficulty:4,
    question:'Vous entendez : <i>&laquo; — Votre fils travaille bien, madame, mais il bavarde beaucoup. — Je lui en parlerai ce soir. &raquo;</i> Qui sont les deux locuteurs ?',
    options:['une enseignante et un parent d\'élève','une directrice et une inspectrice de l\'école','deux élèves de la même classe','un parent et son propre fils'],
    answer:'une enseignante et un parent d\'élève',
    hint:'Les mots &laquo; votre fils &raquo; disent tout de suite qui est qui.',
    explanation:'La premi&egrave;re personne parle du travail de l\'enfant &agrave; quelqu\'un qu\'elle appelle &laquo; madame &raquo; et qui r&eacute;pond &laquo; je lui en parlerai &raquo; : une <b>enseignante</b> face &agrave; la <b>m&egrave;re</b> de l\'&eacute;l&egrave;ve.' }),

  makeMCQ({ id:'g7fr-hd-009', chapterId:'g7fr-co', subsection:'vocabulaire_oral', difficulty:4,
    question:'Un journaliste raconte : <i>&laquo; Apr&egrave;s le passage du cyclone, les villageois se sont <b>entraid&eacute;s</b> pour d&eacute;gager la route. &raquo;</i> Dans cette phrase, &laquo; entraid&eacute;s &raquo; signifie :',
    options:['se sont aidés les uns les autres','se sont réunis pour discuter longuement','se sont plaints auprès des autorités','se sont mis à l\'abri dans les maisons'],
    answer:'se sont aidés les uns les autres',
    hint:'Le pr&eacute;fixe &laquo; entre- &raquo; indique une action r&eacute;ciproque.',
    explanation:'S\'entraider, c\'est <b>s\'aider mutuellement</b>. Le contexte le confirme : ensemble, les villageois d&eacute;gagent la route apr&egrave;s le cyclone.' }),

  makeMCQ({ id:'g7fr-hd-010', chapterId:'g7fr-co', subsection:'vocabulaire_oral', difficulty:4,
    question:'Au march&eacute;, un vendeur dit : <i>&laquo; Cette ann&eacute;e, les litchis sont <b>hors de prix</b>. &raquo;</i> Cela veut dire qu\'ils sont :',
    options:['extrêmement chers','de très mauvaise qualité cette saison','vendus sans étiquette de prix','offerts gratuitement aux clients'],
    answer:'extrêmement chers',
    hint:'Un prix si haut qu\'il sort de l\'ordinaire.',
    explanation:'&laquo; Hors de prix &raquo; est une expression fig&eacute;e : le prix d&eacute;passe ce qu\'on peut normalement payer, donc c\'est <b>tr&egrave;s cher</b>. Elle ne parle ni de l\'&eacute;tiquette ni de la qualit&eacute;.' }),

  makeMCQ({ id:'g7fr-hd-011', chapterId:'g7fr-co', subsection:'vocabulaire_oral', difficulty:3,
    question:'Un guide annonce aux visiteurs : <i>&laquo; Nous partirons <b>aux aurores</b> pour voir le lagon avant les bateaux. &raquo;</i> Le d&eacute;part aura lieu :',
    options:['très tôt le matin','juste avant le coucher du soleil','en pleine nuit, vers minuit','au milieu de l\'après-midi'],
    answer:'très tôt le matin',
    hint:'L\'aurore, c\'est la lumi&egrave;re qui pr&eacute;c&egrave;de le lever du soleil.',
    explanation:'&laquo; Aux aurores &raquo; signifie <b>au lever du jour</b>, donc tr&egrave;s t&ocirc;t le matin. Le d&eacute;tail &laquo; avant les bateaux &raquo; confirme cette heure matinale.' }),

  makeMCQ({ id:'g7fr-hd-012', chapterId:'g7fr-eo', subsection:'lecture_voix_haute', difficulty:4,
    question:'Vous lisez &agrave; voix haute : <i>&laquo; Quand le vent est tomb&eacute;, les p&ecirc;cheurs de Mah&eacute;bourg ont repris la mer. &raquo;</i> O&ugrave; faut-il marquer la pause principale ?',
    options:['après « tombé », à la fin de la subordonnée','après « pêcheurs », entre le sujet et son complément','après « vent », juste avant le verbe « est tombé »','après « repris », juste avant « la mer »'],
    answer:'après « tombé », à la fin de la subordonnée',
    hint:'La virgule &eacute;crite correspond ici &agrave; la respiration du lecteur.',
    explanation:'La proposition subordonn&eacute;e de temps se termine &agrave; &laquo; tomb&eacute; &raquo;, o&ugrave; la virgule marque la fronti&egrave;re de sens. Couper entre un sujet et son verbe rendrait la phrase incompr&eacute;hensible &agrave; l\'oreille.' }),

  makeMCQ({ id:'g7fr-hd-013', chapterId:'g7fr-eo', subsection:'lecture_voix_haute', difficulty:4,
    question:'Lue en insistant fortement sur le mot &laquo; toi &raquo;, la phrase <i>&laquo; C\'est toi qui as rang&eacute; la salle ? &raquo;</i> exprime surtout :',
    options:['la surprise devant l\'identité de la personne','un reproche adressé à toute la classe présente','une simple demande d\'information neutre','un ordre donné à celui qui écoute'],
    answer:'la surprise devant l\'identité de la personne',
    hint:'L\'accent d\'insistance porte sur celui qui a fait l\'action.',
    explanation:'Appuyer sur &laquo; toi &raquo; oppose cette personne &agrave; toutes les autres : le lecteur exprime son <b>&eacute;tonnement</b> que ce soit elle. La m&ecirc;me phrase dite platement serait une simple question.' }),

  makeMCQ({ id:'g7fr-hd-014', chapterId:'g7fr-eo', subsection:'lecture_voix_haute', difficulty:3,
    question:'Dans la lecture &agrave; voix haute de <i>&laquo; les grands arbres ont r&eacute;sist&eacute; au cyclone &raquo;</i>, la liaison obligatoire se fait entre :',
    options:['« grands » et « arbres »','« résisté » et « au cyclone »','« arbres » et « ont »','« les » et « grands »'],
    answer:'« grands » et « arbres »',
    hint:'La liaison est obligatoire entre un adjectif et le nom qu\'il pr&eacute;c&egrave;de.',
    explanation:'Entre l\'adjectif &laquo; grands &raquo; et le nom &laquo; arbres &raquo; la liaison est <b>obligatoire</b> : on entend un son z. Entre un sujet nominal et son verbe (&laquo; arbres ont &raquo;) elle ne se fait pas &agrave; l\'oral courant.' }),

  makeMCQ({ id:'g7fr-hd-015', chapterId:'g7fr-eo', subsection:'lecture_voix_haute', difficulty:4,
    question:'Un &eacute;l&egrave;ve lit ce passage d\'un conte : <i>&laquo; — Au secours ! cria la vieille dame. — N\'ayez pas peur, r&eacute;pondit calmement le p&ecirc;cheur. &raquo;</i> Comment doit-il le lire ?',
    options:['fort et vif pour la première réplique, plus posé pour la seconde','en criant les deux répliques pour bien marquer l\'urgence du moment','sur le même ton neutre pour les deux répliques','très lentement du début à la fin du passage'],
    answer:'fort et vif pour la première réplique, plus posé pour la seconde',
    hint:'Le verbe qui suit chaque r&eacute;plique indique le ton &agrave; prendre.',
    explanation:'Les verbes de parole donnent la consigne de lecture : &laquo; cria &raquo; demande une voix forte et rapide, &laquo; r&eacute;pondit calmement &raquo; demande une voix pos&eacute;e. Lire les deux de la m&ecirc;me fa&ccedil;on effacerait le contraste voulu par l\'auteur.' }),

  makeMCQ({ id:'g7fr-hd-016', chapterId:'g7fr-eo', subsection:'expression_confiance', difficulty:4,
    question:'Pendant votre expos&eacute;, un mot vous &eacute;chappe et vous restez bloqu&eacute; devant la classe. Que vaut-il mieux faire ?',
    options:['reformuler l\'idée avec des mots plus simples et continuer','répéter la même phrase plusieurs fois jusqu\'à retrouver le mot','s\'arrêter et attendre que le professeur souffle le mot','lire le reste de l\'exposé sans lever les yeux'],
    answer:'reformuler l\'idée avec des mots plus simples et continuer',
    hint:'Le but est que le public comprenne, pas que la phrase soit parfaite.',
    explanation:'Un orateur assur&eacute; <b>reformule</b> : il dit la m&ecirc;me id&eacute;e autrement et poursuit. R&eacute;p&eacute;ter ou attendre de l\'aide coupe le fil et fait perdre l\'attention de la classe.' }),

  makeMCQ({ id:'g7fr-hd-017', chapterId:'g7fr-eo', subsection:'expression_confiance', difficulty:4,
    question:'Vous pr&eacute;sentez un expos&eacute; sur le lagon de Blue Bay devant votre classe. Quelle ouverture est &agrave; la fois claire et adapt&eacute;e ?',
    options:['Aujourd\'hui, je vais vous parler du lagon de Blue Bay et de ses coraux.','Je ne sais pas vraiment par où commencer, mais je vais essayer quand même.','Bon, alors, euh, moi je voulais dire un truc sur Blue Bay, voilà.','Le lagon de Blue Bay, vous savez tous ce que c\'est, non ?'],
    answer:'Aujourd\'hui, je vais vous parler du lagon de Blue Bay et de ses coraux.',
    hint:'Une bonne introduction annonce le sujet en une phrase, sans s\'excuser.',
    explanation:'Annoncer clairement le sujet met l\'auditoire sur les rails d&egrave;s la premi&egrave;re seconde. H&eacute;siter, s\'excuser ou supposer que tout le monde sait d&eacute;j&agrave; affaiblit imm&eacute;diatement l\'expos&eacute;.' }),

  makeMCQ({ id:'g7fr-hd-018', chapterId:'g7fr-eo', subsection:'expression_confiance', difficulty:4,
    question:'Dans un d&eacute;bat en classe, vous n\'&ecirc;tes pas d\'accord avec un camarade. Quelle intervention est &agrave; la fois polie et efficace ?',
    options:['Je ne suis pas tout à fait d\'accord, car il me semble que...','Tu dis n\'importe quoi, ce n\'est vraiment pas comme cela du tout.','C\'est faux, et tout le monde le sait bien ici.','Je préfère ne rien dire, ce n\'est pas grave.'],
    answer:'Je ne suis pas tout à fait d\'accord, car il me semble que...',
    hint:'On critique l\'id&eacute;e, jamais la personne qui la d&eacute;fend.',
    explanation:'Nuancer (&laquo; pas tout &agrave; fait &raquo;) puis annoncer sa raison (&laquo; car &raquo;) permet de s\'opposer sans blesser. Attaquer le camarade ferme la discussion, et se taire n\'y participe pas.' }),

  makeMCQ({ id:'g7fr-hd-019', chapterId:'g7fr-eo', subsection:'expression_confiance', difficulty:4,
    question:'Un &eacute;l&egrave;ve parle tr&egrave;s vite et garde les yeux fix&eacute;s sur ses notes pendant tout son expos&eacute;. Quel conseil l\'aidera le plus ?',
    options:['ralentir le débit et lever les yeux vers l\'auditoire','apprendre tout l\'exposé par cœur avant de le présenter','parler plus fort pour couvrir le bruit de la classe','écrire un texte plus long pour ne rien oublier'],
    answer:'ralentir le débit et lever les yeux vers l\'auditoire',
    hint:'Deux choses le trahissent : la vitesse et le regard.',
    explanation:'Ce sont pr&eacute;cis&eacute;ment ces deux points qu\'il faut corriger : un <b>d&eacute;bit plus lent</b> et le <b>regard vers le public</b>. Apprendre par c&oelig;ur ou allonger le texte aggraverait la lecture m&eacute;canique.' }),

  makeMCQ({ id:'g7fr-hd-020', chapterId:'g7fr-eo', subsection:'lexique_approprie', difficulty:4,
    question:'Vous demandez &agrave; la directrice l\'autorisation d\'organiser une vente de g&acirc;teaux. Quelle formulation convient ?',
    options:['Madame, pourrions-nous organiser une vente de gâteaux ?','Madame, il faut que vous nous laissiez vendre des gâteaux.','Madame, on peut faire une vente de gâteaux, non ?','Dis, madame, on fait une vente de gâteaux ?'],
    answer:'Madame, pourrions-nous organiser une vente de gâteaux ?',
    hint:'Le conditionnel adoucit une demande adress&eacute;e &agrave; une personne qui a l\'autorit&eacute;.',
    explanation:'Le conditionnel &laquo; pourrions-nous &raquo; formule une <b>demande</b> et non une exigence : c\'est le registre soutenu qu\'appelle cette situation. &laquo; Il faut que vous &raquo; donne un ordre &agrave; la directrice.' }),

  makeMCQ({ id:'g7fr-hd-021', chapterId:'g7fr-eo', subsection:'lexique_approprie', difficulty:3,
    question:'Compl&eacute;tez avec le mot le plus pr&eacute;cis : <i>&laquo; Apr&egrave;s trois heures de marche sous le soleil, les randonneurs &eacute;taient ___ . &raquo;</i>',
    options:['épuisés','tranquilles','fatigants','ennuyés'],
    answer:'épuisés',
    hint:'Attention : &laquo; fatigant &raquo; d&eacute;crit ce qui fatigue, pas celui qui est fatigu&eacute;.',
    explanation:'Apr&egrave;s trois heures de marche au soleil, le mot juste est <b>&eacute;puis&eacute;s</b>, c\'est-&agrave;-dire tr&egrave;s fatigu&eacute;s. &laquo; Fatigants &raquo; qualifierait la marche elle-m&ecirc;me, pas les marcheurs.' }),

  makeMCQ({ id:'g7fr-hd-022', chapterId:'g7fr-eo', subsection:'lexique_approprie', difficulty:4,
    question:'Vous expliquez &agrave; des &eacute;l&egrave;ves de Grade 3 ce qu\'est un cyclone. Quelle phrase est la mieux adapt&eacute;e &agrave; ce public ?',
    options:['C\'est une très grosse tempête, avec un vent qui tourne.','C\'est une dépression tropicale dont les vents dépassent 118 km/h.','C\'est un phénomène météorologique de basse pression atmosphérique.','C\'est un système dépressionnaire accompagné de rafales cycloniques.'],
    answer:'C\'est une très grosse tempête, avec un vent qui tourne.',
    hint:'Choisir son lexique, c\'est penser d\'abord &agrave; celui qui &eacute;coute.',
    explanation:'Pour de jeunes enfants, il faut des mots concrets et connus : <b>temp&ecirc;te</b>, <b>vent</b>. Les termes techniques (d&eacute;pression tropicale, rafales cycloniques) sont exacts mais incompr&eacute;hensibles &agrave; cet &acirc;ge.' }),

  makeMCQ({ id:'g7fr-hd-023', chapterId:'g7fr-ee', subsection:'textes_fonctionnels', difficulty:4,
    question:'Vous &eacute;crivez une lettre &agrave; la directrice de votre coll&egrave;ge pour demander une salle. Quelle formule de politesse finale convient ?',
    options:['Veuillez agréer, Madame la Directrice, mes salutations distinguées.','Salut Madame, et merci beaucoup d\'avance pour votre réponse rapide !','Bisous et à très bientôt, Madame la Directrice.','Je t\'embrasse très fort en attendant ta réponse.'],
    answer:'Veuillez agréer, Madame la Directrice, mes salutations distinguées.',
    hint:'Une lettre officielle garde le vouvoiement jusqu\'au dernier mot.',
    explanation:'La formule consacr&eacute;e reprend le titre du destinataire et reste au vouvoiement. Le tutoiement, les bisous ou &laquo; Salut &raquo; appartiennent &agrave; la lettre <b>amicale</b>.' }),

  makeMCQ({ id:'g7fr-hd-024', chapterId:'g7fr-ee', subsection:'textes_fonctionnels', difficulty:4,
    question:'Voici une affiche pr&eacute;par&eacute;e par la classe : <i>&laquo; KERMESSE DE L\'&Eacute;COLE — Samedi, dans la cour. Jeux, g&acirc;teaux, musique. Entr&eacute;e : 20 roupies. &raquo;</i> Quelle information indispensable manque ?',
    options:['l\'heure et la date complète de la kermesse','la liste complète des gâteaux qui seront vendus','le nom des élèves qui organisent la fête','le prix exact de chaque jeu de la cour'],
    answer:'l\'heure et la date complète de la kermesse',
    hint:'Une affiche doit r&eacute;pondre &agrave; quatre questions : quoi, o&ugrave;, quand, combien.',
    explanation:'&laquo; Samedi &raquo; ne dit ni quel samedi ni &agrave; quelle heure : sans <b>date pr&eacute;cise et horaire</b>, personne ne sait quand venir. Le reste (quoi, o&ugrave;, prix) figure d&eacute;j&agrave; sur l\'affiche.' }),

  makeMCQ({ id:'g7fr-hd-025', chapterId:'g7fr-ee', subsection:'textes_fonctionnels', difficulty:4,
    question:'Vous &eacute;crivez un courriel au responsable de la biblioth&egrave;que pour signaler un livre ab&icirc;m&eacute;. Quel objet convient le mieux ?',
    options:['Livre abîmé : signalement (exemplaire 214)','Bonjour, j\'ai un petit problème à vous raconter','Urgent !!! lisez ce message tout de suite svp','Message d\'un élève de la classe de Grade 7'],
    answer:'Livre abîmé : signalement (exemplaire 214)',
    hint:'L\'objet d\'un courriel annonce le contenu en quelques mots.',
    explanation:'Un bon objet est court, pr&eacute;cis et permet de classer le message : il nomme le probl&egrave;me et l\'ouvrage concern&eacute;. Un objet vague ou tout en majuscules oblige le destinataire &agrave; ouvrir le message pour savoir de quoi il s\'agit.' }),

  makeMCQ({ id:'g7fr-hd-026', chapterId:'g7fr-ee', subsection:'textes_fonctionnels', difficulty:3,
    question:'Vous affichez une annonce au coll&egrave;ge pour retrouver un sac perdu. Quelle phrase est la plus utile ?',
    options:['Perdu : sac bleu, jeudi, près du laboratoire ; contacter la 7B.','Quelqu\'un aurait-il vu passer un sac bleu quelque part au collège ?','J\'ai perdu quelque chose d\'important, aidez-moi s\'il vous plaît.','Mon sac me manque beaucoup depuis jeudi dernier, c\'est triste.'],
    answer:'Perdu : sac bleu, jeudi, près du laboratoire ; contacter la 7B.',
    hint:'Une annonce donne des faits : quoi, quand, o&ugrave;, qui contacter.',
    explanation:'Seule cette version donne toutes les informations utiles &agrave; celui qui a trouv&eacute; le sac. Les autres expriment un sentiment ou posent une question vague, sans dire &agrave; qui r&eacute;pondre.' }),

  makeMCQ({ id:'g7fr-hd-027', chapterId:'g7fr-ee', subsection:'organisation_paragraphes', difficulty:4,
    question:'Lisez ce paragraphe : <i>&laquo; Le jardin de l\'&eacute;cole a &eacute;t&eacute; replant&eacute; par les &eacute;l&egrave;ves. Chaque classe s\'occupe d\'un carr&eacute; de l&eacute;gumes. Mon fr&egrave;re joue tr&egrave;s bien au football. Les tomates seront r&eacute;colt&eacute;es en juin. &raquo;</i> Quelle phrase faut-il supprimer ?',
    options:['Mon frère joue très bien au football.','Le jardin de l\'école a été replanté par les élèves.','Chaque classe s\'occupe d\'un carré de légumes.','Les tomates seront récoltées en juin.'],
    answer:'Mon frère joue très bien au football.',
    hint:'Toutes les phrases d\'un paragraphe doivent servir la m&ecirc;me id&eacute;e.',
    explanation:'Le paragraphe traite du <b>jardin de l\'&eacute;cole</b> : le football du fr&egrave;re n\'a aucun lien avec cette id&eacute;e directrice et brise l\'unit&eacute; du paragraphe.' }),

  makeMCQ({ id:'g7fr-hd-028', chapterId:'g7fr-ee', subsection:'organisation_paragraphes', difficulty:4,
    question:'Compl&eacute;tez avec le connecteur qui convient : <i>&laquo; Le cyclone a coup&eacute; la route du village. ___ , les secours ont mis deux jours &agrave; arriver. &raquo;</i>',
    options:['C\'est pourquoi','En dépit de cela','Par exemple','Au contraire'],
    answer:'C\'est pourquoi',
    hint:'Quel est le lien logique entre la route coup&eacute;e et le retard des secours ?',
    explanation:'La route coup&eacute;e est la <b>cause</b> et le retard des secours la <b>cons&eacute;quence</b> : le connecteur doit donc exprimer la cons&eacute;quence. &laquo; En d&eacute;pit de cela &raquo; dirait l\'inverse, c\'est-&agrave;-dire que les secours seraient arriv&eacute;s vite malgr&eacute; la route coup&eacute;e.' }),

  makeMCQ({ id:'g7fr-hd-029', chapterId:'g7fr-ee', subsection:'organisation_paragraphes', difficulty:4,
    question:'Ces quatre phrases forment un paragraphe m&eacute;lang&eacute; : <i>1. Ensuite, le car nous a d&eacute;pos&eacute;s &agrave; Flic-en-Flac. 2. D\'abord, il a fallu compter tous les &eacute;l&egrave;ves devant le coll&egrave;ge. 3. Enfin, nous avons partag&eacute; un pique-nique sous les filaos. 4. Ce samedi-l&agrave;, notre classe est all&eacute;e &agrave; la plage.</i> Quel est le bon ordre ?',
    options:['4 - 2 - 1 - 3','2 - 4 - 1 - 3','4 - 1 - 2 - 3','2 - 1 - 4 - 3'],
    answer:'4 - 2 - 1 - 3',
    hint:'Rep&eacute;rez la phrase qui annonce le sujet, puis suivez les connecteurs de temps.',
    explanation:'La phrase 4 pose la situation (qui, quand, o&ugrave;). Les connecteurs donnent ensuite la suite exacte : <b>D\'abord</b> (2), puis <b>Ensuite</b> (1), puis <b>Enfin</b> (3).' }),

  makeMCQ({ id:'g7fr-hd-030', chapterId:'g7fr-ee', subsection:'correction_syntaxe', difficulty:4,
    question:'Corrigez la phrase : <i>&laquo; Les &eacute;l&egrave;ves que j\'ai parl&eacute; hier sont de Rodrigues. &raquo;</i>',
    options:['Les élèves à qui j\'ai parlé hier sont de Rodrigues.','Les élèves lesquels j\'ai parlé hier sont de Rodrigues.','Les élèves qui j\'ai parlé hier sont de Rodrigues.','Les élèves que j\'ai parlé à hier sont de Rodrigues.'],
    answer:'Les élèves à qui j\'ai parlé hier sont de Rodrigues.',
    hint:'On dit &laquo; parler <b>&agrave;</b> quelqu\'un &raquo; : la pr&eacute;position doit rester devant le pronom relatif.',
    explanation:'Le verbe se construit avec la pr&eacute;position &agrave; (parler &agrave; quelqu\'un), donc le relatif est <b>&agrave; qui</b> lorsqu\'il s\'agit de personnes. &laquo; Que &raquo; ne s\'emploie que pour un compl&eacute;ment direct.' }),

  makeMCQ({ id:'g7fr-hd-031', chapterId:'g7fr-ee', subsection:'correction_syntaxe', difficulty:4,
    question:'Corrigez les accords : <i>&laquo; La lettre que j\'ai &eacute;crit &agrave; ma tante est parti hier. &raquo;</i>',
    options:['La lettre que j\'ai écrite à ma tante est partie hier.','La lettre que j\'ai écrits à ma tante est partis hier.','La lettre que j\'ai écrit à ma tante est partie hier.','La lettre que j\'ai écrite à ma tante est parti hier.'],
    answer:'La lettre que j\'ai écrite à ma tante est partie hier.',
    hint:'Il y a deux accords &agrave; faire : l\'un avec <i>avoir</i> et son COD plac&eacute; avant, l\'autre avec <i>&ecirc;tre</i>.',
    explanation:'Avec <b>avoir</b>, le participe s\'accorde avec le COD plac&eacute; devant : &laquo; que &raquo; remplace &laquo; la lettre &raquo;, donc &eacute;crit<b>e</b>. Avec <b>&ecirc;tre</b>, il s\'accorde avec le sujet f&eacute;minin : la lettre est parti<b>e</b>.' }),

  makeMCQ({ id:'g7fr-hd-032', chapterId:'g7fr-ee', subsection:'correction_syntaxe', difficulty:3,
    question:'Corrigez la phrase : <i>&laquo; Si j\'aurais su, je serais rest&eacute; &agrave; la maison. &raquo;</i>',
    options:['Si j\'avais su, je serais resté à la maison.','Si je saurais, je serais resté à la maison.','Si j\'aurais su, je serai resté à la maison.','Si j\'avais su, j\'aurais resté à la maison.'],
    answer:'Si j\'avais su, je serais resté à la maison.',
    hint:'Apr&egrave;s &laquo; si &raquo;, on n\'emploie jamais le conditionnel.',
    explanation:'La condition irr&eacute;elle du pass&eacute; se construit avec le <b>plus-que-parfait</b> apr&egrave;s &laquo; si &raquo; et le <b>conditionnel pass&eacute;</b> dans l\'autre partie. Le verbe rester se conjugue avec <i>&ecirc;tre</i>, donc &laquo; je serais rest&eacute; &raquo;.' }),

  makeMCQ({ id:'g7fr-hd-033', chapterId:'g7fr-litterature', subsection:'genres_litteraires', difficulty:4,
    question:'Lisez : <i>&laquo; &Ocirc; lagon endormi, tu berces mes deux &icirc;les, / Et le vent de l\'aliz&eacute; emporte mes soucis. &raquo;</i> Quel indice montre qu\'il s\'agit d\'un po&egrave;me et non d\'un r&eacute;cit ?',
    options:['la disposition en vers et l\'image poétique adressée au lagon','le fait que le texte parle de la mer, du vent et des deux îles','la présence de deux lignes seulement dans le texte cité','l\'emploi du pronom « tu » dans la première ligne'],
    answer:'la disposition en vers et l\'image poétique adressée au lagon',
    hint:'Regardez la forme du texte autant que son contenu.',
    explanation:'Un r&eacute;cit peut lui aussi parler de la mer et employer &laquo; tu &raquo;. Ce qui d&eacute;signe le <b>po&egrave;me</b>, c\'est la mise en vers, marqu&eacute;e ici par la barre oblique, et l\'apostrophe lyrique adress&eacute;e au lagon.' }),

  makeMCQ({ id:'g7fr-hd-034', chapterId:'g7fr-litterature', subsection:'genres_litteraires', difficulty:4,
    question:'Lisez : <i>&laquo; MARIE, entrant vivement. — Papa, le car est d&eacute;j&agrave; pass&eacute; ! LE P&Egrave;RE, sans lever la t&ecirc;te. — Alors tu marcheras. &raquo;</i> Quels &eacute;l&eacute;ments montrent qu\'il s\'agit d\'une pi&egrave;ce de th&eacute;&acirc;tre ?',
    options:['les noms des personnages en tête et les indications de jeu','le fait que l\'histoire se passe tôt le matin, avant l\'école','la présence d\'un dialogue entre deux personnes','l\'emploi du futur dans la dernière réplique'],
    answer:'les noms des personnages en tête et les indications de jeu',
    hint:'Un roman aussi contient des dialogues : cherchez ce qu\'un roman n\'a pas.',
    explanation:'Le nom du personnage plac&eacute; avant sa r&eacute;plique et les <b>didascalies</b> (&laquo; entrant vivement &raquo;, &laquo; sans lever la t&ecirc;te &raquo;) sont propres au texte de th&eacute;&acirc;tre, &eacute;crit pour &ecirc;tre jou&eacute;.' }),

  makeMCQ({ id:'g7fr-hd-035', chapterId:'g7fr-litterature', subsection:'genres_litteraires', difficulty:4,
    question:'Lisez : <i>&laquo; Le h&eacute;ron, trop fier, refusa le petit poisson ; le soir venu, il dut se contenter d\'un escargot. Ne m&eacute;prisons pas ce que nous avons. &raquo;</i> Ce texte est :',
    options:['une fable, car un animal illustre une leçon','un conte merveilleux rempli d\'objets magiques','un récit historique sur les oiseaux de Maurice','une description scientifique du héron cendré'],
    answer:'une fable, car un animal illustre une leçon',
    hint:'La derni&egrave;re phrase ne raconte plus : elle enseigne.',
    explanation:'Un animal qui se conduit comme un humain, une histoire tr&egrave;s br&egrave;ve et une <b>morale</b> finale : c\'est la structure de la fable. Aucun &eacute;l&eacute;ment magique ni aucune donn&eacute;e scientifique n\'appara&icirc;t ici.' }),

  makeMCQ({ id:'g7fr-hd-036', chapterId:'g7fr-litterature', subsection:'genres_litteraires', difficulty:4,
    question:'Lisez : <i>&laquo; Je suis n&eacute;e &agrave; Rodrigues, dans une maison de bois que mon grand-p&egrave;re avait b&acirc;tie. Je me souviens encore de l\'odeur du pain chaud. &raquo;</i> Ce d&eacute;but est celui :',
    options:['d\'un récit autobiographique','d\'un article encyclopédique sur Rodrigues','d\'un conte merveilleux','d\'une notice explicative'],
    answer:'d\'un récit autobiographique',
    hint:'Qui dit &laquo; je &raquo; ici, et de quoi se souvient-il ?',
    explanation:'Le narrateur dit &laquo; je &raquo;, parle de sa naissance et de ses souvenirs personnels : il raconte <b>sa propre vie</b>. Un article encyclop&eacute;dique n\'emploierait ni &laquo; je &raquo; ni le souvenir d\'une odeur.' }),

  makeMCQ({ id:'g7fr-hd-037', chapterId:'g7fr-litterature', subsection:'types_textes', difficulty:4,
    question:'Lisez : <i>&laquo; Il faut interdire les sacs en plastique dans les boutiques du village. En effet, ils &eacute;touffent le lagon et tuent les tortues. &raquo;</i> Ce texte est :',
    options:['argumentatif, car il défend une opinion avec une raison','narratif, car il raconte les événements du village dans l\'ordre','descriptif, car il donne à voir le paysage du lagon','injonctif, car il donne une recette à suivre'],
    answer:'argumentatif, car il défend une opinion avec une raison',
    hint:'Le connecteur &laquo; en effet &raquo; annonce toujours la m&ecirc;me chose.',
    explanation:'Le texte prend d\'abord position (&laquo; il faut interdire &raquo;) puis justifie cette position avec &laquo; en effet &raquo; : c\'est un texte <b>argumentatif</b>. Rien n\'y est racont&eacute; ni d&eacute;crit.' }),

  makeMCQ({ id:'g7fr-hd-038', chapterId:'g7fr-litterature', subsection:'types_textes', difficulty:4,
    question:'Lisez : <i>&laquo; M&eacute;langez la farine et l\'eau. Laissez reposer une heure. Faites frire les g&acirc;teaux piments dans l\'huile bien chaude. &raquo;</i> Quel indice montre que ce texte est injonctif ?',
    options:['l\'emploi de l\'impératif dans chaque phrase','le fait que les phrases soient toutes très courtes','l\'ordre chronologique des trois phrases','la présence d\'ingrédients mauriciens'],
    answer:'l\'emploi de l\'impératif dans chaque phrase',
    hint:'Regardez le mode des verbes : &laquo; M&eacute;langez &raquo;, &laquo; Laissez &raquo;, &laquo; Faites &raquo;.',
    explanation:'Le texte injonctif <b>fait agir</b> le lecteur, et sa marque grammaticale est ici l\'imp&eacute;ratif r&eacute;p&eacute;t&eacute;. Des phrases courtes ou un ordre chronologique se rencontrent aussi dans un r&eacute;cit.' }),

  makeMCQ({ id:'g7fr-hd-039', chapterId:'g7fr-litterature', subsection:'types_textes', difficulty:3,
    question:'Lisez : <i>&laquo; Un cyclone se forme au-dessus d\'une mer chaude. L\'air humide monte, se refroidit et provoque de fortes pluies. &raquo;</i> Ce texte a pour but :',
    options:['d\'expliquer un phénomène','de donner un ordre précis au lecteur','de raconter une aventure','de convaincre le lecteur'],
    answer:'d\'expliquer un phénomène',
    hint:'Le texte r&eacute;pond &agrave; la question &laquo; comment cela se produit-il ? &raquo;.',
    explanation:'Le texte d&eacute;crit un encha&icirc;nement de causes pour faire comprendre un ph&eacute;nom&egrave;ne naturel : il est <b>explicatif</b>. Il ne d&eacute;fend aucune opinion et ne raconte aucune histoire.' }),

  makeMCQ({ id:'g7fr-hd-040', chapterId:'g7fr-litterature', subsection:'types_textes', difficulty:4,
    question:'Dans un r&eacute;cit, on lit : <i>&laquo; Le sentier montait entre les goyaviers. &Agrave; gauche, la vall&eacute;e s\'ouvrait, verte et silencieuse, jusqu\'&agrave; la mer. &raquo;</i> Ce passage sert surtout &agrave; :',
    options:['planter le décor de l\'action','faire avancer l\'intrigue rapidement','présenter la morale de l\'histoire','donner un conseil au lecteur'],
    answer:'planter le décor de l\'action',
    hint:'Rien ne se passe dans ces deux phrases : on voit.',
    explanation:'Aucune action nouvelle n\'a lieu ; l\'auteur donne &agrave; voir le lieu, avec des adjectifs et des rep&egrave;res d\'espace. C\'est une <b>pause descriptive</b> ins&eacute;r&eacute;e dans le r&eacute;cit.' }),

  makeMCQ({ id:'g7fr-hd-041', chapterId:'g7fr-litterature', subsection:'conte_bd', difficulty:4,
    question:'Lisez ce d&eacute;but de conte : <i>&laquo; Il &eacute;tait une fois un p&ecirc;cheur qui vivait heureux pr&egrave;s du lagon. Un matin, sa pirogue avait disparu. &raquo;</i> La deuxi&egrave;me phrase correspond :',
    options:['à l\'élément perturbateur','à la morale finale du conte','à la situation initiale','au dénouement du conte'],
    answer:'à l\'élément perturbateur',
    hint:'Quelque chose vient rompre l\'&eacute;quilibre du d&eacute;but.',
    explanation:'La premi&egrave;re phrase installe la <b>situation initiale</b> (un p&ecirc;cheur heureux) ; la disparition de la pirogue casse cet &eacute;quilibre et lance l\'histoire : c\'est l\'<b>&eacute;l&eacute;ment perturbateur</b>.' }),

  makeMCQ({ id:'g7fr-hd-042', chapterId:'g7fr-litterature', subsection:'conte_bd', difficulty:4,
    question:'Dans une bande dessin&eacute;e, la voix du narrateur (&laquo; Le lendemain, &agrave; Port-Louis... &raquo;) est &eacute;crite :',
    options:['dans un cartouche','dans un phylactère en pointes','dans une bulle ronde','dans une onomatopée'],
    answer:'dans un cartouche',
    hint:'Ce n\'est pas un personnage qui parle : ce texte ne sort de la bouche de personne.',
    explanation:'Le r&eacute;cit du narrateur est plac&eacute; dans un <b>cartouche</b>, un rectangle situ&eacute; en haut de la vignette. Les bulles, elles, contiennent les paroles ou les pens&eacute;es des personnages.' }),

  makeMCQ({ id:'g7fr-hd-043', chapterId:'g7fr-litterature', subsection:'conte_bd', difficulty:3,
    question:'Dans une planche de bande dessin&eacute;e, une bulle reli&eacute;e au personnage par de petits ronds qui montent indique :',
    options:['qu\'il pense sans parler','qu\'il chuchote un secret','qu\'il crie très fort','qu\'il chante une chanson'],
    answer:'qu\'il pense sans parler',
    hint:'La forme de l\'appendice de la bulle dit comment il faut la lire.',
    explanation:'Les petits ronds signalent la <b>bulle de pens&eacute;e</b> : le personnage r&eacute;fl&eacute;chit et les autres ne l\'entendent pas. Un cri se dessine, lui, avec une bulle en dents de scie.' }),

  makeMCQ({ id:'g7fr-hd-044', chapterId:'g7fr-litterature', subsection:'conte_bd', difficulty:4,
    question:'Lisez la fin de ce conte : <i>&laquo; Le petit marchand partagea sa derni&egrave;re mangue avec une vieille femme. Le lendemain, son panier &eacute;tait plein de fruits m&ucirc;rs. &raquo;</i> Quelle morale convient ?',
    options:['Qui donne de bon cœur reçoit à son tour.','La chance sourit à ceux qui se lèvent tôt le matin.','Il faut toujours garder ses fruits pour soi.','Mieux vaut vendre au marché qu\'au bord de la route.'],
    answer:'Qui donne de bon cœur reçoit à son tour.',
    hint:'Reliez le geste du marchand &agrave; ce qui lui arrive le lendemain.',
    explanation:'Le conte oppose un don d&eacute;sint&eacute;ress&eacute; et la r&eacute;compense qui suit : la le&ccedil;on porte donc sur la <b>g&eacute;n&eacute;rosit&eacute;</b>. Rien dans le texte ne parle de l\'heure du lever ni du lieu de vente.' })

);
})();
