'use strict';
STATIC_QUESTIONS.push(

  makeMCQ({ id:'g8eng-gr-nouns-010', chapterId:'g8eng-gr-nouns', difficulty:2,
    subsection:'noun_phrases',
    question:'Which sentence has an <b>expanded noun phrase</b> as its subject?',
    options:['The rusty iron gate creaked','The gate creaked in the morning','Slowly, the gate began to creak','It creaked, that old iron gate'],
    answer:'The rusty iron gate creaked',
    hint:'Look at the words before the verb, not after it.',
    explanation:'The subject here is "the rusty iron gate" — a determiner and two adjectives built around the head noun. In the others the subject is only "the gate" or "it"; the extra words are adverbs or come after the verb.' }),

  makeMCQ({ id:'g8eng-gr-nouns-011', chapterId:'g8eng-gr-nouns', difficulty:2,
    subsection:'gerunds',
    question:'Which sentence uses a <b>gerund as the subject</b>?',
    options:['Cycling to school saves money','She likes cycling to school','They were cycling to school','He cycles to school each day'],
    answer:'Cycling to school saves money',
    hint:'Find the -ing word, then ask whether it is what the sentence is about.',
    explanation:'"Cycling to school" is what saves money, so the gerund is the subject. In the second it is the object of "likes", in the third it is part of the verb "were cycling", and the fourth has no -ing word at all.' }),

  makeMCQ({ id:'g8eng-gr-nouns-012', chapterId:'g8eng-gr-nouns', difficulty:2,
    subsection:'noun_phrases',
    question:'Which word is the <b>head noun</b> of the phrase "a long queue of tired shoppers"?',
    options:['queue','shoppers','long','tired'],
    answer:'queue',
    hint:'Which single word could replace the whole phrase and still make sense?',
    explanation:'The phrase is about a queue; everything else describes it. "Shoppers" is the head of the smaller phrase inside "of tired shoppers", and "long" and "tired" are adjectives.' }),

  makeText({ id:'g8eng-gr-nouns-013', chapterId:'g8eng-gr-nouns', difficulty:3,
    subsection:'gerunds',
    question:'Write the gerund that completes the sentence:<br><i>"She is very good at ______ (swim) in the lagoon."</i>',
    answer:'swimming',
    hint:'After a preposition such as "at", a verb takes its -ing form.',
    explanation:'A preposition must be followed by a noun or a gerund, so "swim" becomes "swimming". "To swim" is an infinitive and cannot follow "at", and the bare form would leave the preposition without an object.' }),

  makeMCQ({ id:'g8eng-gr-nouns-014', chapterId:'g8eng-gr-nouns', difficulty:3,
    subsection:'noun_phrases',
    question:'Which expansion of "dog" is a <b>noun phrase</b>, not a clause?',
    options:['the stray dog by the gate','the dog that sat by the gate','the dog which we found there','the dog when it ran away'],
    answer:'the stray dog by the gate',
    hint:'A clause contains its own verb. A noun phrase does not.',
    explanation:'"By the gate" is a prepositional phrase with no verb, so the whole group stays a noun phrase. The other three add "sat", "found" and "ran", each of which makes a clause.' }),

  makeMCQ({ id:'g8eng-gr-nouns-015', chapterId:'g8eng-gr-nouns', difficulty:3,
    subsection:'gerunds',
    question:'Which sentence is <b>incorrect</b>?',
    options:['She avoided to answer the call','She avoided answering the call','She refused to answer the call','She kept answering the call'],
    answer:'She avoided to answer the call',
    hint:'Some verbs take a gerund after them and never an infinitive.',
    explanation:'"Avoid" is always followed by a gerund, so it must be "avoided answering". "Refuse" takes the infinitive and "keep" takes the gerund, so those three sentences all follow their verb\'s pattern.' }),

  makeMCQ({ id:'g8eng-gr-nouns-016', chapterId:'g8eng-gr-nouns', difficulty:3,
    subsection:'noun_phrases',
    question:'In the phrase <i>"a photograph of my grandmother in a silver frame"</i>, which noun does "in a silver frame" most naturally describe?',
    options:['photograph','grandmother','silver','frame'],
    answer:'photograph',
    hint:'Which of the two nouns is usually the thing inside a frame?',
    explanation:'A photograph is what sits in a frame, so the phrase attaches to the head noun even though "grandmother" is nearer. "Silver" is an adjective and "frame" is inside the phrase doing the describing.' }),

  makeMCQ({ id:'g8eng-gr-nouns-017', chapterId:'g8eng-gr-nouns', difficulty:3,
    subsection:'gerunds',
    question:'Which verb must be followed by a <b>gerund</b>, never an infinitive?',
    options:['enjoy','decide','hope','agree'],
    answer:'enjoy',
    hint:'Try each one in "I ______ reading" and then in "I ______ to read".',
    explanation:'"Enjoy reading" is correct and "enjoy to read" is not. "Decide", "hope" and "agree" all take the infinitive: decide to go, hope to win, agree to help.' }),

  makeText({ id:'g8eng-gr-nouns-018', chapterId:'g8eng-gr-nouns', difficulty:3,
    subsection:'noun_phrases',
    question:'Write the <b>head noun</b> of this noun phrase:<br><i>"the crowded bus to Mahébourg"</i>',
    answer:'bus',
    hint:'Take every modifier away and see which word cannot go.',
    explanation:'Strip "the", "crowded" and "to Mahébourg" and only "bus" must stay, so it is the head. The others are a determiner, an adjective and a prepositional phrase that describe it.' }),

  makeMCQ({ id:'g8eng-gr-nouns-019', chapterId:'g8eng-gr-nouns', difficulty:4,
    subsection:'gerunds',
    question:'Read: <i>"Reading widely improves writing, and writing daily improves reading."</i><br>How many <b>gerunds</b> does the sentence contain?',
    options:['Four','Three','Two','Five'],
    answer:'Four',
    hint:'Count every -ing word that is doing a noun\'s job, as subject or as object.',
    explanation:'"Reading" and "writing" each appear twice, once as a subject and once as an object, giving four gerunds. None of them is part of a verb tense, so no -ing word here is a participle.' }),

  makeMCQ({ id:'g8eng-gr-nouns-020', chapterId:'g8eng-gr-nouns', difficulty:4,
    subsection:'noun_phrases',
    question:'Which noun phrase is <b>ambiguous</b> — it can be understood in two ways?',
    options:['the boy with the dog we saw','the small boy near the shop','the boy in the green shirt','the tall boy on the beach'],
    answer:'the boy with the dog we saw',
    hint:'In one of these, ask yourself exactly what was seen.',
    explanation:'"We saw" could attach to the boy or to the dog, and nothing in the phrase decides which. In the other three every modifier can only describe the boy, so there is one reading each.' })

);
