'use strict';
STATIC_QUESTIONS.push(

  makeMCQ({ id:'g8eng-gr-adjectives-010', chapterId:'g8eng-gr-adjectives', difficulty:2,
    subsection:'adjective_order',
    question:'Which order is correct?',
    options:['a small round wooden table','a wooden round small table','a round small wooden table','a wooden small round table'],
    answer:'a small round wooden table',
    hint:'Size comes before shape, and the material sits closest to the noun.',
    explanation:'English orders adjectives size, then shape, then material: small, round, wooden. Any order that puts "wooden" before "small" or "round" breaks the sequence, because material always comes last.' }),

  makeMCQ({ id:'g8eng-gr-adjectives-011', chapterId:'g8eng-gr-adjectives', difficulty:2,
    subsection:'participial_adjectives',
    question:'Choose the correct adjective:<br><i>"The results were ______ — nobody expected them."</i>',
    options:['surprising','surprised','surprise','surprisingly'],
    answer:'surprising',
    hint:'Do the results feel something, or do they cause a feeling?',
    explanation:'The results cause the feeling, so they take the -ing form. "Surprised" describes the people who feel it, "surprise" is the plain noun or verb, and "surprisingly" is an adverb.' }),

  makeMCQ({ id:'g8eng-gr-adjectives-012', chapterId:'g8eng-gr-adjectives', difficulty:2,
    subsection:'adjective_order',
    question:'Which order is correct?',
    options:['two long Chinese silk scarves','two Chinese long silk scarves','two silk long Chinese scarves','long two silk Chinese scarves'],
    answer:'two long Chinese silk scarves',
    hint:'Number first, then size, then where it comes from, then what it is made of.',
    explanation:'The sequence is quantity, size, origin, material: two, long, Chinese, silk. Moving the origin or the material forward, or putting the size before the number, breaks that order.' }),

  makeMCQ({ id:'g8eng-gr-adjectives-013', chapterId:'g8eng-gr-adjectives', difficulty:3,
    subsection:'participial_adjectives',
    question:'Which sentence is <b>correct</b>?',
    options:['I was bored by the long film','I was boring by the long film','The film was bored and slow','I felt boring during the film'],
    answer:'I was bored by the long film',
    hint:'The person feels the -ed form; the thing causes the -ing form.',
    explanation:'The speaker feels the boredom, so "bored" is right and the film is what is "boring". The other three swap the two forms, which says the speaker caused the feeling or that the film felt it.' }),

  makeMCQ({ id:'g8eng-gr-adjectives-014', chapterId:'g8eng-gr-adjectives', difficulty:3,
    subsection:'adjective_order',
    question:'Which order is correct for a description of a bag?',
    options:['an old brown leather school bag','a leather old brown school bag','a school old brown leather bag','a brown leather old school bag'],
    answer:'an old brown leather school bag',
    hint:'Age, then colour, then material, then what the thing is for.',
    explanation:'The order runs age, colour, material, purpose: old, brown, leather, school. The other three move the material or the purpose in front of the age or the colour, which no English speaker would say.' }),

  makeText({ id:'g8eng-gr-adjectives-015', chapterId:'g8eng-gr-adjectives', difficulty:3,
    subsection:'participial_adjectives',
    question:'Write the correct adjective form:<br><i>"The children were ______ (excite) about the trip to Chamarel."</i>',
    answer:'excited',
    hint:'Do the children feel it, or do they cause it?',
    explanation:'People feel the -ed form, so the children are "excited"; "exciting" would describe the trip, which causes the feeling. The plain verb "excite" cannot follow "were" as an adjective.' }),

  makeMCQ({ id:'g8eng-gr-adjectives-016', chapterId:'g8eng-gr-adjectives', difficulty:3,
    subsection:'adjective_order',
    question:'Where does an <b>opinion</b> adjective go in a string of adjectives?',
    options:['Before all the others','After the size adjective','After the colour adjective','Just before the noun itself'],
    answer:'Before all the others',
    hint:'Think of "a lovely large metal jug" and note where the judgement sits.',
    explanation:'What you think of something comes first, before every fact about it: "a lovely large metal jug". The place just before the noun belongs to the material or the purpose, which are the last facts given.' }),

  makeMCQ({ id:'g8eng-gr-adjectives-017', chapterId:'g8eng-gr-adjectives', difficulty:3,
    subsection:'participial_adjectives',
    question:'Which pair fills the two gaps correctly?<br><i>"The ______ crowd watched the ______ finish."</i>',
    options:['excited … thrilling','exciting … thrilled','excited … thrilled','exciting … thrilling'],
    answer:'excited … thrilling',
    hint:'The crowd feels; the finish causes.',
    explanation:'People feel, so the crowd is "excited"; events cause, so the finish is "thrilling". Each of the other pairs makes the crowd cause a feeling or the finish have one.' }),

  makeMCQ({ id:'g8eng-gr-adjectives-018', chapterId:'g8eng-gr-adjectives', difficulty:4,
    subsection:'adjective_order',
    question:'A pupil writes <i>"a French beautiful small vase"</i>.<br>Which two adjectives are in the wrong places?',
    options:['beautiful and French','small and beautiful','French and small','vase and French'],
    answer:'beautiful and French',
    hint:'Write out the correct version first, then compare it word by word.',
    explanation:'The correct order is "a beautiful small French vase", so the opinion has to move to the front and the origin to the back. "Small" is already in its right place, and "vase" is the noun, not an adjective.' }),

  makeMCQ({ id:'g8eng-gr-adjectives-019', chapterId:'g8eng-gr-adjectives', difficulty:4,
    subsection:'participial_adjectives',
    question:'Read: <i>"The frightening noise left the frightened dog under the bed."</i><br>Why are the two forms different?',
    options:['One causes, the other feels','One is older than the other','One is a verb, one a noun','One is plural, one singular'],
    answer:'One causes, the other feels',
    hint:'Ask what the noise does and what the dog does.',
    explanation:'The noise causes fear, which takes the -ing form, and the dog experiences it, which takes the -ed form. Both words are adjectives here, both describe one thing each, and age has nothing to do with it.' }),

  makeText({ id:'g8eng-gr-adjectives-020', chapterId:'g8eng-gr-adjectives', difficulty:3,
    subsection:'adjective_order',
    question:'Put these adjectives in the correct order before the noun and write the <b>first</b> one:<br><i>"a ______ ______ ______ jug"  (metal / large / lovely)</i>',
    answer:'lovely',
    hint:'Opinion comes before size, and size before material.',
    explanation:'The correct phrase is "a lovely large metal jug", so the opinion word comes first. "Large" is a size and "metal" is the material, and neither of those can be placed ahead of a judgement.' })

);
