'use strict';
STATIC_QUESTIONS.push(

  makeMCQ({ id:'g8eng-gr-punctuation-010', chapterId:'g8eng-gr-punctuation', difficulty:2,
    subsection:'ellipsis',
    question:'How many dots make up an <b>ellipsis</b>?',
    options:['Three','Two','Four','Five'],
    answer:'Three',
    hint:'Count the dots in the mark itself, not the full stop that may follow it.',
    explanation:'An ellipsis is exactly three dots. Two dots is a typing slip, and four is only ever three dots printed after a full stop at the end of a sentence.' }),

  makeMCQ({ id:'g8eng-gr-punctuation-011', chapterId:'g8eng-gr-punctuation', difficulty:2,
    subsection:'punctuation_review',
    question:'Which sentence uses the <b>colon</b> correctly?',
    options:['We need three things: rope, water, food','We need: rope, water and food today','We need three, rope: water and food','We: need rope, water and food today'],
    answer:'We need three things: rope, water, food',
    hint:'A colon needs a complete statement in front of it.',
    explanation:'"We need three things" is a full clause, so a colon may introduce the list that explains it. The others put the colon after a verb, a number or a pronoun, cutting the clause in half.' }),

  makeMCQ({ id:'g8eng-gr-punctuation-012', chapterId:'g8eng-gr-punctuation', difficulty:3,
    subsection:'ellipsis',
    question:'A story reads: <i>"If only I had known…"</i><br>What does the ellipsis show?',
    options:['A thought left unfinished','A word spelled incorrectly','A quotation from a book','A list that continues on'],
    answer:'A thought left unfinished',
    hint:'What has the speaker not gone on to say?',
    explanation:'The character breaks off before finishing the sentence, and the ellipsis marks that silence. Nothing is misspelled, no source is quoted, and no list has been started.' }),

  makeText({ id:'g8eng-gr-punctuation-013', chapterId:'g8eng-gr-punctuation', difficulty:3,
    subsection:'punctuation_review',
    question:'One punctuation mark is missing from this sentence. Write its <b>name</b>:<br><i>"My brother who lives in Vacoas, is coming on Sunday."</i>',
    answer:'comma', alsoAccept:['a comma','the comma'],
    hint:'The extra information already has one of its two markers.',
    explanation:'An added clause is fenced off by a pair of commas, and here only the closing one is present, so a comma is missing after "brother". No other mark would balance the pair.' }),

  makeText({ id:'g8eng-gr-punctuation-014', chapterId:'g8eng-gr-punctuation', difficulty:3,
    subsection:'ellipsis',
    question:'A pupil shortens a quotation in an essay and marks the missing words with three dots.<br>Write the <b>name</b> of that punctuation mark.',
    answer:'ellipsis', alsoAccept:['an ellipsis','the ellipsis','ellipsis points','ellipses'],
    hint:'It is the same mark that shows a speaker trailing off.',
    explanation:'Three dots used this way are called an ellipsis, and in an essay they show that words have been left out of a quotation. A dash marks an interruption and a colon introduces, so neither would do this job.' }),

  makeMCQ({ id:'g8eng-gr-punctuation-015', chapterId:'g8eng-gr-punctuation', difficulty:3,
    subsection:'punctuation_review',
    question:'Which form is correct for lockers belonging to <b>several</b> pupils?',
    options:['the pupils\' lockers','the pupil\'s lockers','the pupils lockers\'','the pupils\'s lockers'],
    answer:'the pupils\' lockers',
    hint:'Make the noun plural first, then decide where the apostrophe goes.',
    explanation:'A plural already ending in -s takes the apostrophe after the s. "Pupil\'s" means one pupil, the third puts the mark on the wrong noun, and the last adds an s that plural nouns never need.' }),

  makeMCQ({ id:'g8eng-gr-punctuation-016', chapterId:'g8eng-gr-punctuation', difficulty:3,
    subsection:'ellipsis',
    question:'In a play script, an ellipsis at the end of a line shows that the speaker…',
    options:['trails off without finishing','shouts the last word loudly','asks a direct question','repeats the whole line'],
    answer:'trails off without finishing',
    hint:'What does the actor do with their voice at that point?',
    explanation:'The ellipsis tells the actor to let the line fade rather than end it. Shouting would need an exclamation mark, a question needs a question mark, and repetition is written out in full.' }),

  makeMCQ({ id:'g8eng-gr-punctuation-017', chapterId:'g8eng-gr-punctuation', difficulty:3,
    subsection:'punctuation_review',
    question:'Which sentence uses the <b>question mark</b> correctly?',
    options:['Are you well? she asked me.','She asked whether I was well?','Was she asking if I am well.','She asked, was I well or not.'],
    answer:'Are you well? she asked me.',
    hint:'Only a real question, actually spoken, takes the mark.',
    explanation:'The direct question keeps its own question mark inside the quotation. A reported question is a statement and ends with a full stop, which is why the second is wrong and the third and fourth are muddled.' }),

  makeMCQ({ id:'g8eng-gr-punctuation-018', chapterId:'g8eng-gr-punctuation', difficulty:4,
    subsection:'ellipsis',
    question:'A pupil quotes: <i>The report said the plan "…would cost too much…"</i><br>What do the two ellipses tell the reader?',
    options:['Words are missing at both ends','The pupil disagrees with it','The report was never finished','The quotation is very long'],
    answer:'Words are missing at both ends',
    hint:'The quotation begins and ends in the middle of a sentence.',
    explanation:'An ellipsis at each end shows the pupil has taken the words from the middle of a longer sentence. It expresses no opinion, says nothing about the report being incomplete, and does not measure length.' }),

  makeMCQ({ id:'g8eng-gr-punctuation-019', chapterId:'g8eng-gr-punctuation', difficulty:4,
    subsection:'punctuation_review',
    question:'Read: <i>"The winners were announced Rahul, Fatima and Yash."</i><br>Which mark is missing, and where?',
    options:['A colon after announced','A comma after winners','A semicolon after were','A full stop after Fatima'],
    answer:'A colon after announced',
    hint:'A complete statement is followed by the list that explains it.',
    explanation:'"The winners were announced" is a full clause, so a colon introduces the names that follow. A comma after "winners" would split subject from verb, and the other two marks would break the sentence apart.' }),

  makeMCQ({ id:'g8eng-gr-punctuation-020', chapterId:'g8eng-gr-punctuation', difficulty:3,
    subsection:'ellipsis',
    question:'Which mark shows a speaker being <b>interrupted</b>, rather than trailing off?',
    options:['A dash','An ellipsis','A comma','A colon'],
    answer:'A dash',
    hint:'One mark cuts the line off sharply; the other lets it fade.',
    explanation:'A dash cuts the sentence off suddenly, which is how an interruption is written. An ellipsis shows the speaker fading out by choice, and a comma or colon simply divides parts of a sentence.' })

);
