'use strict';
STATIC_QUESTIONS.push(

  makeMCQ({ id:'g8eng-gr-sentence-010', chapterId:'g8eng-gr-sentence', difficulty:2,
    subsection:'direct_indirect_speech',
    question:'Change to indirect speech:<br><i>She said, "I am cooking now."</i>',
    options:['She said she was cooking then','She said she is cooking now','She said I was cooking then','She said she cooking was then'],
    answer:'She said she was cooking then',
    hint:'Both the tense and the time word have to shift back.',
    explanation:'The present continuous moves back to the past continuous and "now" becomes "then". Keeping "is" and "now" leaves the words unshifted, and "I" would make the speaker someone else.' }),

  makeMCQ({ id:'g8eng-gr-sentence-011', chapterId:'g8eng-gr-sentence', difficulty:2,
    subsection:'complex_sentences',
    question:'Which sentence is <b>complex</b> — a main clause plus a subordinate clause?',
    options:['We left when the rain stopped','We left and the rain stopped','The rain stopped, so we left','We left; the rain had stopped'],
    answer:'We left when the rain stopped',
    hint:'A complex sentence needs a joining word that makes one clause depend on the other.',
    explanation:'"When" makes the second clause subordinate, so the sentence is complex. "And" and "so" join two equal clauses, making a compound sentence, and the semicolon does the same with no joining word.' }),

  makeMCQ({ id:'g8eng-gr-sentence-012', chapterId:'g8eng-gr-sentence', difficulty:3,
    subsection:'direct_indirect_speech',
    question:'In indirect speech, what does <b>"tomorrow"</b> usually become?',
    options:['the next day','the last day','that same day','the day before'],
    answer:'the next day',
    hint:'The report is made later, so every time word moves one step back.',
    explanation:'Reporting shifts the viewpoint, so "tomorrow" becomes "the next day" or "the following day". "The day before" is what "yesterday" becomes, and the other two point at the wrong day.' }),

  makeMCQ({ id:'g8eng-gr-sentence-013', chapterId:'g8eng-gr-sentence', difficulty:3,
    subsection:'complex_sentences',
    question:'Which sentence is a <b>third conditional</b>?',
    options:['If I had known, I would have come','If I knew, I would come along','If I know, I will come along','If I had known, I would come'],
    answer:'If I had known, I would have come',
    hint:'The third conditional talks about a past that cannot now be changed.',
    explanation:'The pattern is "if + past perfect, would have + past participle", which is the only one here that keeps both halves. The second is a second conditional, the third a first, and the fourth mixes the two.' }),

  makeText({ id:'g8eng-gr-sentence-014', chapterId:'g8eng-gr-sentence', difficulty:3,
    subsection:'direct_indirect_speech',
    question:'Change to indirect speech. Write the <b>two words</b> that replace "will go":<br><i>He said, "I will go to Souillac."</i> → He said he ______ ______ to Souillac.',
    answer:'would go',
    hint:'"Will" has a past form of its own.',
    explanation:'In reported speech "will" shifts back to "would", so "will go" becomes "would go". Keeping "will" leaves the tense unshifted, and "went" loses the future meaning of the original.' }),

  makeMCQ({ id:'g8eng-gr-sentence-015', chapterId:'g8eng-gr-sentence', difficulty:3,
    subsection:'complex_sentences',
    question:'Which word makes the clause that follows it <b>subordinate</b>?',
    options:['although','and','but','or'],
    answer:'although',
    hint:'Read "______ it rained" aloud. Which one cannot stand alone?',
    explanation:'"Although it rained" cannot stand as a sentence, so "although" subordinates the clause. "And", "but" and "or" are coordinating conjunctions that join two clauses of equal weight.' }),

  makeMCQ({ id:'g8eng-gr-sentence-016', chapterId:'g8eng-gr-sentence', difficulty:3,
    subsection:'direct_indirect_speech',
    question:'Change to indirect speech:<br><i>She asked, "Are you ready?"</i>',
    options:['She asked if I was ready','She asked was I ready then','She asked me are you ready','She asked if am I ready'],
    answer:'She asked if I was ready',
    hint:'A reported question keeps the word order of a statement.',
    explanation:'A yes-or-no question is reported with "if" or "whether" and normal statement order. The others keep the inverted question order, which reported speech does not use.' }),

  makeMCQ({ id:'g8eng-gr-sentence-017', chapterId:'g8eng-gr-sentence', difficulty:3,
    subsection:'complex_sentences',
    question:'Which sentence uses the <b>past conditional</b> correctly?',
    options:['If she had left, she would have won','If she left, she would have won','If she leaves, she would have won','If she had left, she will have won'],
    answer:'If she had left, she would have won',
    hint:'Check both halves, not just the "if" clause.',
    explanation:'The past conditional needs the past perfect after "if" and "would have" in the main clause. Each of the others gets one half right and the other wrong, which breaks the pair.' }),

  makeMCQ({ id:'g8eng-gr-sentence-018', chapterId:'g8eng-gr-sentence', difficulty:4,
    subsection:'direct_indirect_speech',
    question:'Read: <i>He told me that he had lost his keys the day before.</i><br>What were his exact words?',
    options:['I lost my keys yesterday','I have lost my keys today','I had lost my keys before','I will lose my keys today'],
    answer:'I lost my keys yesterday',
    hint:'Work backwards: undo the tense shift and the time word together.',
    explanation:'"Had lost" comes from a simple past and "the day before" comes from "yesterday", so the original was "I lost my keys yesterday". The others keep a reported form or change the meaning of the time word.' }),

  makeMCQ({ id:'g8eng-gr-sentence-019', chapterId:'g8eng-gr-sentence', difficulty:4,
    subsection:'complex_sentences',
    question:'Read: <i>"Because the ferry was cancelled, which nobody had expected, we slept in Port Louis."</i><br>How many <b>subordinate clauses</b> are there?',
    options:['Two','Three','One','Four'],
    answer:'Two',
    hint:'Look for the joining words at the front of each clause.',
    explanation:'"Because the ferry was cancelled" and "which nobody had expected" are both subordinate, leaving "we slept in Port Louis" as the main clause. That gives two dependent clauses, not one or three.' }),

  makeMCQ({ id:'g8eng-gr-sentence-020', chapterId:'g8eng-gr-sentence', difficulty:3,
    subsection:'complex_sentences',
    question:'Join these two ideas into a <b>complex</b> sentence:<br><i>The bell rang. We packed our bags.</i>',
    options:['When the bell rang, we packed','The bell rang and we packed','The bell rang; we packed then','The bell rang, then we packed'],
    answer:'When the bell rang, we packed',
    hint:'A complex sentence needs one clause to depend on the other.',
    explanation:'"When" turns the first clause into a subordinate one, which is what makes the sentence complex. "And" gives a compound sentence, and the semicolon and comma versions keep both clauses equal.' })

);
