'use strict';
STATIC_QUESTIONS.push(

  makeMCQ({ id:'g8eng-gr-verbs-010', chapterId:'g8eng-gr-verbs', difficulty:2,
    subsection:'present_perfect',
    question:'Choose the correct form:<br><i>"I ______ my homework, so I can go out now."</i>',
    options:['have finished','finished','was finishing','will finish'],
    answer:'have finished',
    hint:'The past action matters because of its result right now.',
    explanation:'The present perfect links a finished action to the present, which is why going out is possible. The simple past would just report when, the past continuous shows it unfinished, and the future has not happened.' }),

  makeMCQ({ id:'g8eng-gr-verbs-011', chapterId:'g8eng-gr-verbs', difficulty:2,
    subsection:'future_continuous',
    question:'Choose the correct form:<br><i>"Do not call at eight — we ______ dinner then."</i>',
    options:['will be having','will have had','have been having','was being had'],
    answer:'will be having',
    hint:'The meal will be going on at that exact moment.',
    explanation:'"Will be" plus the -ing form shows an action in progress at a future time. "Will have had" finishes it before eight, and the last two put the dinner in the past.' }),

  makeMCQ({ id:'g8eng-gr-verbs-012', chapterId:'g8eng-gr-verbs', difficulty:3,
    subsection:'present_perfect',
    question:'Which sentence is <b>incorrect</b>?',
    options:['I have seen him yesterday','I saw him yesterday morning','I have seen him this week','I have not seen him today'],
    answer:'I have seen him yesterday',
    hint:'The present perfect refuses one kind of time word. Which?',
    explanation:'A finished time such as "yesterday" needs the simple past, so it cannot sit with "have seen". "This week" and "today" are unfinished periods, which the present perfect accepts.' }),

  makeMCQ({ id:'g8eng-gr-verbs-013', chapterId:'g8eng-gr-verbs', difficulty:3,
    subsection:'future_continuous',
    question:'What does <i>"This time next year I will be studying in Réduit"</i> tell you?',
    options:['An action in progress then','An action already finished','A habit repeated each year','A wish that may not happen'],
    answer:'An action in progress then',
    hint:'"This time next year" points at one moment in the future.',
    explanation:'The future continuous shows an action already running at a named future moment. A finished action would need "will have studied", a habit would use the simple present, and no doubt is expressed.' }),

  makeMCQ({ id:'g8eng-gr-verbs-014', chapterId:'g8eng-gr-verbs', difficulty:3,
    subsection:'present_perfect',
    question:'Choose the correct word:<br><i>"She has lived in Quatre Bornes ______ 2019."</i>',
    options:['since','for','from','during'],
    answer:'since',
    hint:'Does 2019 name a starting point or a length of time?',
    explanation:'"Since" is used with the point at which something began, and 2019 is a point. "For" needs a length such as six years, while "from" and "during" do not fit the present perfect here.' }),

  makeText({ id:'g8eng-gr-verbs-015', chapterId:'g8eng-gr-verbs', difficulty:3,
    subsection:'future_continuous',
    question:'Write the verb in the <b>future continuous</b>:<br><i>"At ten o\'clock tomorrow the class ______ (sit) the test."</i>',
    answer:'will be sitting',
    hint:'The pattern is will + be + the -ing form.',
    explanation:'"Will be sitting" shows the test already in progress at ten. "Will sit" is the simple future and says only that it happens, and "is sitting" places it in the present.' }),

  makeMCQ({ id:'g8eng-gr-verbs-016', chapterId:'g8eng-gr-verbs', difficulty:3,
    subsection:'present_perfect',
    question:'Which question uses the present perfect correctly?',
    options:['Have you ever been to Rodrigues?','Did you ever have been to Rodrigues?','Have you went to Rodrigues before?','Are you ever been to Rodrigues?'],
    answer:'Have you ever been to Rodrigues?',
    hint:'The present perfect is "have" plus the past participle.',
    explanation:'"Have" plus "been" is the correct pair for asking about experience. "Went" is a past simple, not a participle, and the other two mix "did" or "are" into a tense that needs "have".' }),

  makeMCQ({ id:'g8eng-gr-verbs-017', chapterId:'g8eng-gr-verbs', difficulty:3,
    subsection:'future_continuous',
    question:'Which question uses the future continuous to sound <b>polite</b> rather than pushy?',
    options:['Will you be joining us later?','Will you join us later or not?','You will join us later, yes?','Are you joining us later then?'],
    answer:'Will you be joining us later?',
    hint:'One form asks about your plans; the others ask you to decide now.',
    explanation:'The future continuous asks what is already arranged, so it puts no pressure on the listener. The other three demand a decision, which is why they sound blunt.' }),

  makeMCQ({ id:'g8eng-gr-verbs-018', chapterId:'g8eng-gr-verbs', difficulty:4,
    subsection:'present_perfect',
    question:'Read: <i>"Mauritius has hosted the games twice. It hosted them again in 1985."</i><br>Why is the second sentence in the simple past?',
    options:['It names a finished time','It is shorter than the first','It uses a different subject','It refers to another country'],
    answer:'It names a finished time',
    hint:'Compare "twice" with "in 1985".',
    explanation:'Once a finished year is given, English switches to the simple past; "twice" gives no time, so the present perfect fits. Length and subject are the same in both sentences, and only one country is named.' }),

  makeMCQ({ id:'g8eng-gr-verbs-019', chapterId:'g8eng-gr-verbs', difficulty:3,
    subsection:'future_continuous',
    question:'Which sentence is <b>incorrect</b>?',
    options:['I will be knowing the answer','I will be waiting at the gate','I will be revising all evening','I will be leaving before six'],
    answer:'I will be knowing the answer',
    hint:'Some verbs describe a state, not an activity, and states do not take -ing.',
    explanation:'"Know" is a state verb, so it cannot go into a continuous form: it should be "I will know". Waiting, revising and leaving are all activities that can be in progress.' }),

  makeText({ id:'g8eng-gr-verbs-020', chapterId:'g8eng-gr-verbs', difficulty:4,
    subsection:'future_continuous',
    question:'Rewrite in the future continuous. Write the <b>three words</b> that replace "cooks":<br><i>"At noon Mum cooks lunch."</i> → "At noon Mum ______ lunch."',
    answer:'will be cooking',
    hint:'The pattern has three words and the last one ends in -ing.',
    explanation:'"Will be cooking" shows the cooking already under way at noon. "Will cook" is the simple future and reports only that it happens, and "is cooking" puts it in the present.' })

);
