'use strict';
(function () {

  // Level 4 — "Extended Analysis" — for the three grammar chapters that carried
  // almost none of it: Adverbs (0), Prepositions (0) and Sentence Structure (2).
  //
  // L4 here is never "a harder rule". It is a sentence in which TWO things
  // interact and the pupil has to reason: where a focusing adverb sits decides
  // what it scopes over; which particle follows a verb decides what the verb
  // means; whether a passive names its agent decides what the reader learns.
  // Anything answerable by recognising a rule is L1 or L2, and this pack
  // already holds hundreds of those.

  STATIC_QUESTIONS.push(

    // ══ g9eng-gr-adverbs · attitude_adverbs (001–020) ═════════════════════
    // The chapter declares one subsection. Position, scope and degree all
    // belong to it: an adverb that comments on the whole clause IS the
    // attitude adverb, and the items below make the pupil separate that use
    // from the manner, focus and degree uses it is confused with.

    makeMCQ({ id:'g9eng-d6-001', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'The same four words appear in every option; only the position of <b>only</b> changes. Which sentence says that nobody except Rahul had read the report?',
      options:['Only Rahul had read the report before the meeting.',
               'Rahul had only read the report before the meeting.',
               'Rahul had read only the report before the meeting.',
               'Rahul had read the report only before the meeting.'],
      answer:'Only Rahul had read the report before the meeting.',
      hint:'A focusing adverb points at whatever follows it. Ask what each <b>only</b> is standing in front of.',
      explanation:'<b>Only</b> focuses on the word group immediately after it, so <i>Only Rahul</i> excludes every other person. Put in front of the verb it excludes other actions (he did nothing but read); in front of <i>the report</i> it excludes other documents; in front of <i>before the meeting</i> it excludes other times. One word, four sentences, four different claims.' }),

    makeMCQ({ id:'g9eng-d6-002', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Which sentence says that the inspector — the last person you would expect — was surprised <b>as well as</b> everyone else?',
      options:['Even the inspector was surprised by the verdict.',
               'The inspector was even surprised by the verdict.',
               'The inspector was surprised even by the verdict.',
               'The inspector alone was surprised by the verdict.'],
      answer:'Even the inspector was surprised by the verdict.',
      hint:'Decide which word group each focusing adverb is pointing at before you read the sentence as a whole.',
      explanation:'<b>Even</b> in front of <i>the inspector</i> adds him to a list and marks him as the unlikeliest member of it. In front of the verb it says being surprised went further than his other reactions; in front of <i>by the verdict</i> it makes the verdict the unlikeliest cause; and <i>alone</i> takes everyone else out of the sentence, which is the opposite of what was asked.' }),

    makeText({ id:'g9eng-d6-003', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Two adverbs appear in this sentence: <i>Frankly, the committee answered evasively.</i> Write the ONE adverb that gives the speaker&rsquo;s own comment on the whole statement rather than describing how the committee answered.',
      answer:'Frankly', alsoAccept:['frankly'],
      hint:'One adverb could be replaced by &ldquo;I will be honest with you&rdquo;; the other could be replaced by &ldquo;in an evasive way&rdquo;.',
      explanation:'<b>Frankly</b> is a sentence adverb: it comments on the act of speaking itself and could be moved to the end without changing the claim. <b>Evasively</b> is a manner adverb tied to the verb <i>answered</i> and cannot be moved without changing what is being described. Two adverbs in one sentence can be doing two completely different jobs.' }),

    makeMCQ({ id:'g9eng-d6-004', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Which sentence tells the reader that the speaker dislikes the new timetable <b>strongly</b>?',
      options:['I really do not like the new timetable.',
               'I do not really like the new timetable.',
               'I do not always like the new timetable.',
               'I do not like the new timetable either.'],
      answer:'I really do not like the new timetable.',
      hint:'Work out whether the adverb is inside the negative or in front of it.',
      explanation:'When <b>really</b> comes before <i>do not</i>, it strengthens the whole negative: the dislike is real and strong. When it comes after, the negative swallows it and the sentence softens to a mild dislike — the commonest trap here. <i>Always</i> changes the sentence to one about frequency, and <i>either</i> only adds the speaker to a group.' }),

    makeMCQ({ id:'g9eng-d6-005', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'An adjective such as <b>impossible</b> is absolute: it names a limit and cannot be held in different amounts. Which adverb may stand in front of it?',
      options:['absolutely','slightly','very','more'],
      answer:'absolutely',
      hint:'Ask of each adverb whether it grades the adjective or simply insists on it.',
      explanation:'<b>Absolutely</b> does not grade the adjective — it confirms that the limit has been reached, which is why it fits an absolute word. <i>Slightly</i>, <i>very</i> and <i>more</i> all place the adjective somewhere on a scale, and a thing cannot be a little impossible or more impossible than another. The same applies to <i>unique</i>, <i>perfect</i> and <i>dead</i>.' }),

    makeTF({ id:'g9eng-d6-006', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'True or False: &ldquo;The design is very unique&rdquo; and &ldquo;The design is absolutely unique&rdquo; are both standard written English.',
      answer:false,
      hint:'Test each adverb by asking whether the adjective can come in different amounts.',
      explanation:'False. <i>Unique</i> means <b>one of a kind</b>, so there are no degrees of it: <i>very unique</i> asks for an amount the adjective cannot have. <i>Absolutely unique</i> is acceptable because it insists on the limit rather than grading it. Both sound alike in speech, which is exactly why written English is where the difference shows.' }),

    makeMCQ({ id:'g9eng-d6-007', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'In which sentence does <b>sadly</b> tell you that the <i>speaker</i> regrets the event, rather than describing how the pianist played?',
      options:['Sadly, the pianist played the last movement.',
               'The pianist played the last movement sadly.',
               'The pianist played the last movement in tears.',
               'The pianist played the sad last movement again.'],
      answer:'Sadly, the pianist played the last movement.',
      hint:'Ask which sentence would still make sense if you began it with &ldquo;It is a pity that&rdquo;.',
      explanation:'At the front of the clause, <b>sadly</b> steps outside the action and gives the speaker&rsquo;s view of it — the playing itself may have been magnificent. After the verb it becomes a manner adverb about the sound, and <i>in tears</i> is a phrase doing that same manner job. The last option moves the idea into an adjective describing the music instead.' }),

    makeText({ id:'g9eng-d6-008', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Read: <i>Understandably, the crowd waited patiently for two hours.</i> Write the ONE adverb that describes HOW the crowd waited.',
      answer:'patiently', alsoAccept:['Patiently'],
      hint:'One adverb could be dropped without changing anything about the waiting itself.',
      explanation:'<b>Patiently</b> modifies the verb <i>waited</i> and tells you the manner of the waiting. <b>Understandably</b> modifies the whole statement and gives the writer&rsquo;s judgement that the waiting was reasonable — remove it and the crowd still waits in exactly the same way.' }),

    makeMCQ({ id:'g9eng-d6-009', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'A reporter writes: &ldquo;___, the minister had seen the file before the debate.&rdquo; Which adverb shows that the reporter is <b>drawing a conclusion</b> rather than stating a checked fact?',
      options:['Presumably','Undeniably','Regrettably','Deliberately'],
      answer:'Presumably',
      hint:'Separate the adverbs by what they claim: how certain, how welcome, or how it was done.',
      explanation:'<b>Presumably</b> marks the statement as an inference the reporter cannot prove. <i>Undeniably</i> claims the opposite — that no doubt is possible. <i>Regrettably</i> judges the event rather than the evidence for it, and <i>deliberately</i> is not a comment on the sentence at all but a manner adverb about how the file was seen.' }),

    makeMCQ({ id:'g9eng-d6-010', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Which sentence says that it was <b>no surprise</b> that Anisha took charge, rather than saying how she took charge?',
      options:['Naturally, Anisha took charge of the rehearsal.',
               'Anisha took charge of the rehearsal naturally.',
               'Anisha was the natural choice for the rehearsal.',
               'Anisha took charge of the rehearsal as usual.'],
      answer:'Naturally, Anisha took charge of the rehearsal.',
      hint:'Try replacing the adverb with &ldquo;of course&rdquo; and see which sentence survives the swap.',
      explanation:'Opening the clause, <b>naturally</b> means <i>of course</i> and comments on the whole event. After the verb it means <i>in an easy, unforced way</i> and describes the manner. The third option turns the word into an adjective about her suitability, and <i>as usual</i> claims a habit rather than the speaker&rsquo;s expectation.' }),

    makeText({ id:'g9eng-d6-011', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Write ONE word in the gap so that the sentence says nobody but his brother was invited: &ldquo;Rakesh invited ___ his brother to the wedding.&rdquo;',
      answer:'only', alsoAccept:['just','solely'],
      hint:'The word has to sit immediately in front of the words it is excluding everyone else from.',
      explanation:'A focusing adverb placed directly before <i>his brother</i> narrows the guest list to that one person. Put the same word in front of the verb — <i>Rakesh only invited his brother</i> — and it starts to narrow the ACTION instead, suggesting he invited him but did nothing further. Position is the whole of the meaning.' }),

    makeMCQ({ id:'g9eng-d6-012', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'The word <b>just</b> can mean <i>only</i>, <i>a moment ago</i> or <i>exactly</i>. In which sentence does it mean <i>a moment ago</i>?',
      options:['The bus has just left the terminus at Curepipe.',
               'The bus takes just twenty minutes to Curepipe.',
               'The bus stopped just outside the gate at Curepipe.',
               'The bus was just as crowded as it was yesterday.'],
      answer:'The bus has just left the terminus at Curepipe.',
      hint:'The tense of the verb in each sentence is a strong clue to which meaning is available.',
      explanation:'With a present perfect verb, <b>just</b> marks a very recent event. In front of a quantity it means <i>no more than</i>; in front of a place phrase it means <i>exactly</i>; and in <i>just as crowded</i> it is grading a comparison. One adverb, four jobs, and only the surrounding words tell you which one is running.' }),

    makeMCQ({ id:'g9eng-d6-013', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Which opening adverb prepares the reader for a sentence that turns out the opposite way from what they expect? &ldquo;___, the cheapest tender was the one the council refused.&rdquo;',
      options:['Oddly','Efficiently','Repeatedly','Unanimously'],
      answer:'Oddly',
      hint:'Three of these describe the way the council worked. Only one describes the writer&rsquo;s reaction to the outcome.',
      explanation:'<b>Oddly</b> comments on the whole statement and warns the reader that what follows does not fit expectation. <i>Efficiently</i> and <i>unanimously</i> describe how the refusing was done, and <i>repeatedly</i> how often — none of them can introduce a contradiction, because none of them is about the writer&rsquo;s view of the event.' }),

    makeMCQ({ id:'g9eng-d6-014', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Read: <i>Honestly, she answered every question honestly.</i> What does the FIRST <b>honestly</b> do that the second one does not?',
      options:['It comments on the speaker&rsquo;s whole statement.',
               'It describes the manner of her answering.',
               'It tells the reader how long she took.',
               'It makes the adjective in the clause stronger.'],
      answer:'It comments on the speaker&rsquo;s whole statement.',
      hint:'Delete each adverb in turn and see which deletion changes what we are told about her.',
      explanation:'The opening <b>honestly</b> is the speaker vouching for their own words — it can be replaced by <i>to be honest</i>. The second is a manner adverb tied to <i>answered</i>, and deleting it changes what we are told about her. The same word in two positions is doing two unrelated jobs in one sentence.' }),

    makeMCQ({ id:'g9eng-d6-015', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Which adverb signals that the writer is conceding a point they are about to argue against? &ldquo;___, the scheme cost more than planned; but it saved three villages from flooding.&rdquo;',
      options:['Granted','Apparently','Eventually','Angrily'],
      answer:'Granted',
      hint:'Read past the semicolon first. The second half tells you what job the first word has to do.',
      explanation:'<b>Granted</b> accepts the objection before answering it, which is exactly what the <i>but</i> clause needs. <i>Apparently</i> would cast doubt on the cost instead of accepting it, <i>eventually</i> places it in time, and <i>angrily</i> describes a manner. The word after the semicolon decides the word before it.' }),

    makeTF({ id:'g9eng-d6-016', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'True or False: &ldquo;Only she told the truth&rdquo; and &ldquo;She only told the truth&rdquo; mean the same thing.',
      answer:false,
      hint:'Work out what each sentence is ruling out — other people, or other actions.',
      explanation:'False. The first excludes every other person: she was the one truthful witness. The second excludes every other action: telling the truth was all she did, and it says nothing about anybody else. Moving a focusing adverb by two words changes who or what the sentence is about.' }),

    makeTF({ id:'g9eng-d6-017', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'True or False: in <i>Personally, I would sell the land</i>, the adverb <b>Personally</b> describes the way the selling would be done.',
      answer:false,
      hint:'Ask whether the adverb could be attached to any single verb in the sentence.',
      explanation:'False. <b>Personally</b> does not modify <i>sell</i>; it stands outside the clause and marks the whole opinion as the speaker&rsquo;s own. A manner reading would have to mean selling in a personal manner, which is not what anyone hears. Sentence adverbs are typically set off by a comma for precisely this reason.' }),

    makeMCQ({ id:'g9eng-d6-018', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'One of these sentences grades an adjective that cannot be graded, and is therefore wrong. Which one?',
      options:['The second attempt was slightly impossible.',
               'The second attempt was almost impossible.',
               'The second attempt was simply impossible.',
               'The second attempt was clearly impossible.'],
      answer:'The second attempt was slightly impossible.',
      hint:'Only one adverb here is asking the adjective to come in an amount.',
      explanation:'<b>Slightly</b> asks for a small quantity of an adjective that has no quantities. <i>Almost</i> is different: it says the limit was nearly reached, which is a legitimate thing to say. <i>Simply</i> insists on the statement and <i>clearly</i> comments on how evident it is — neither of them grades the adjective at all.' }),

    makeText({ id:'g9eng-d6-019', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'Write ONE word in the gap so that the sentence says the tank had reached its limit and was not merely close to it: &ldquo;The tank was ___ full when we left the depot.&rdquo;',
      answer:'completely', alsoAccept:['totally','entirely','absolutely','quite'],
      hint:'The adjective here names a limit, so choose an adverb that confirms the limit instead of measuring towards it.',
      explanation:'<i>Full</i> is an absolute adjective, so the adverb in front of it must insist on the limit rather than grade it — <b>completely</b>, <i>totally</i>, <i>entirely</i> and <i>absolutely</i> all do that. <i>Nearly</i> and <i>half</i> would say the opposite of what the question states, and <i>very</i> tries to place an absolute on a scale.' }),

    makeMCQ({ id:'g9eng-d6-020', chapterId:'g9eng-gr-adverbs', subsection:'attitude_adverbs', difficulty:4,
      question:'&ldquo;Ironically, the fire station burned down.&rdquo; If <b>Ironically</b> is moved to the very end of the sentence, what happens?',
      options:['The meaning stays the same, and only the emphasis shifts.',
               'The adverb starts to describe how the station burned.',
               'The sentence becomes ungrammatical in written English.',
               'The adverb turns into an adjective describing the fire.'],
      answer:'The meaning stays the same, and only the emphasis shifts.',
      hint:'Some adverbs change job when they move; others keep it. Decide which kind this one is.',
      explanation:'A sentence adverb comments on the whole clause from wherever it stands, so <i>The fire station burned down, ironically</i> says the same thing with the comment held back to the end. Compare <b>sadly</b> or <b>naturally</b>, which DO switch to a manner reading when they follow the verb directly — the difference is that no one can burn in an ironic manner.' }),

    // ══ g9eng-gr-prepositions · phrasal_verbs (021–032) ═══════════════════
    // The particle, not the verb, carries the meaning — so every item states
    // the meaning and makes the pupil choose the particle that produces it.

    makeMCQ({ id:'g9eng-d6-021', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'The verb is the same in all four options. Which one says that Sanjay <b>admires and respects</b> his grandfather? &ldquo;Sanjay has always ___ his grandfather.&rdquo;',
      options:['looked up to','looked after','looked into','looked over'],
      answer:'looked up to',
      hint:'Take each particle in turn and ask what it does to the plain meaning of <i>look</i>.',
      explanation:'<b>Look up to</b> somebody is to admire them. <i>Look after</i> is to care for a person practically, <i>look into</i> is to investigate a matter, and <i>look over</i> is to inspect something quickly. Not one of the four has anything to do with using your eyes, which is what makes phrasal verbs so hard to guess.' }),

    makeText({ id:'g9eng-d6-022', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'Write ONE word so that the phrasal verb means the meeting was <b>postponed</b>, not cancelled: &ldquo;The meeting was put ___ until Thursday.&rdquo;',
      answer:'off', alsoAccept:['back'],
      hint:'Several particles follow <i>put</i>. Choose the one that moves an event to a later date.',
      explanation:'<b>Put off</b> means postpone, and <i>put back</i> is used the same way of a fixture or a clock. The near neighbours mean something else entirely: <i>put out</i> is to extinguish, <i>put up</i> is to give somebody a bed, and <i>put down</i> is to write something or to suppress it. The verb carries none of this; the particle carries all of it.' }),

    makeMCQ({ id:'g9eng-d6-023', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'<i>Fill in</i> is a separable phrasal verb, and its object here is the pronoun <b>it</b>. Which sentence places that pronoun correctly?',
      options:['The form was wrong, so the clerk filled it in again.',
               'The form was wrong, so the clerk filled in it again.',
               'The form was wrong, so the clerk filled in again it.',
               'The form was wrong, so the clerk filled again it in.'],
      answer:'The form was wrong, so the clerk filled it in again.',
      hint:'A full noun may sit on either side of the particle. Ask whether a pronoun is allowed the same freedom.',
      explanation:'With a separable phrasal verb a pronoun object <b>must</b> come between the verb and the particle: <i>filled it in</i>. A full noun may go either side — <i>filled in the form</i> and <i>filled the form in</i> are both good — which is exactly why <i>filled in it</i> sounds almost right and is still wrong.' }),

    makeMCQ({ id:'g9eng-d6-024', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'Which phrasal verb says that the deputy <b>assumed control</b>? &ldquo;When the director resigned, her deputy ___ the running of the office.&rdquo;',
      options:['took over','took after','took in','took up'],
      answer:'took over',
      hint:'Three of these describe something quite different happening to the office. Match the particle to the meaning given.',
      explanation:'<b>Take over</b> is to assume control of something another person was running. <i>Take after</i> is to resemble a relative, <i>take in</i> is to absorb information or to shelter somebody, and <i>take up</i> is to begin a hobby or an occupation. Only the particle separates a promotion from a family likeness.' }),

    makeText({ id:'g9eng-d6-025', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'Write ONE word so that the phrasal verb means <b>resembles a parent</b>: &ldquo;Everyone says Ravi takes ___ his mother.&rdquo;',
      answer:'after',
      hint:'The particle you need is the one that also appears in expressions about following behind somebody.',
      explanation:'<b>Take after</b> somebody is to resemble them in looks or character, and it is used almost only of relatives. <i>Take on</i> would mean accepting work, <i>take over</i> assuming control, and <i>take in</i> absorbing or sheltering — none of which is a family resemblance.' }),

    makeMCQ({ id:'g9eng-d6-026', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'After missing three weeks of school, Anjali had a great deal of work to ___. Which phrasal verb means to do work that was missed?',
      options:['make up','make out','make for','make off'],
      answer:'make up',
      hint:'Ask what each particle does to <i>make</i> before you decide which fits a pupil returning to class.',
      explanation:'<b>Make up</b> work is to complete what you missed. <i>Make out</i> is to manage to see or hear something, <i>make for</i> is to head towards a place, and <i>make off</i> is to run away. One verb, four particles, four unconnected meanings — and <i>make up</i> itself has a second sense, to invent a story.' }),

    makeMCQ({ id:'g9eng-d6-027', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'It took Kiran months to ___ the disappointment of failing the audition. Which phrasal verb means to <b>recover from</b> it?',
      options:['get over','get across','get round to','get on with'],
      answer:'get over',
      hint:'Weigh each particle against the idea of leaving an unhappy feeling behind you.',
      explanation:'<b>Get over</b> something is to recover from it, as though climbing past an obstacle. <i>Get across</i> is to communicate an idea successfully, <i>get round to</i> is to find time for a delayed task, and <i>get on with</i> is either to continue working or to have a good relationship with somebody.' }),

    makeText({ id:'g9eng-d6-028', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'Write ONE word so that the sentence means the supply was <b>exhausted</b>: &ldquo;By the third day the shelter had run ___ of drinking water.&rdquo;',
      answer:'out',
      hint:'The preposition <i>of</i> is already given, so you need the particle that goes in front of it.',
      explanation:'<b>Run out of</b> something is to use up the last of it. <i>Run into</i> is to meet by chance or to collide, <i>run over</i> is to knock down with a vehicle or to exceed a time, and <i>run through</i> is to rehearse. The particle and the preposition work together here: <i>run out</i> alone would describe the water leaving, not the shelter having none.' }),

    makeMCQ({ id:'g9eng-d6-029', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'<b>Stand by</b> has two very different meanings. In which sentence does it mean <i>keep to</i> something promised?',
      options:['The minister will stand by his earlier pledge.',
               'The crowd could only stand by and watch it.',
               'The lifeguards stand by the pool every hour.',
               'Two engineers stand by in case of a failure.'],
      answer:'The minister will stand by his earlier pledge.',
      hint:'Look at what follows the particle in each sentence: a promise, a place, or nothing at all.',
      explanation:'When <b>stand by</b> takes an object such as a pledge or a decision, it means to remain loyal to it. With no object it means to wait in readiness, or to look on without acting — and followed by a place it is not a phrasal verb at all, just <i>stand</i> plus an ordinary preposition. What comes after the particle decides which reading you get.' }),

    makeMCQ({ id:'g9eng-d6-030', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'While clearing the attic, Ashvin ___ a bundle of his grandmother&rsquo;s letters. Which phrasal verb says that he found them <b>by chance</b>?',
      options:['came across','came round','came into','came over'],
      answer:'came across',
      hint:'Only one of these particles carries the idea of meeting something in your path unexpectedly.',
      explanation:'<b>Come across</b> something is to find it by accident. <i>Come into</i> is to inherit — <i>came into a fortune</i> — <i>come round</i> is to regain consciousness or to change your mind, and <i>come over</i> is to visit, or to describe a feeling that takes hold of somebody. Every one of them is a real phrasal verb, so only the meaning can decide it.' }),

    makeText({ id:'g9eng-d6-031', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'Write ONE word so that the phrasal verb means <b>raise a subject</b> in conversation: &ldquo;Nobody at the table wanted to bring ___ the question of money.&rdquo;',
      answer:'up',
      hint:'The particle you need is the one that also appears in the phrasal verb for rearing a child.',
      explanation:'<b>Bring up</b> a subject is to introduce it into a discussion, and the same phrasal verb means to rear a child. <i>Bring about</i> is to cause something to happen, <i>bring round</i> is to revive somebody or win them over, and <i>bring out</i> is to publish or to make a quality visible.' }),

    makeMCQ({ id:'g9eng-d6-032', chapterId:'g9eng-gr-prepositions', subsection:'phrasal_verbs', difficulty:4,
      question:'Two of these options would mean the laboratory is doing something other than testing. Which phrasal verb means to <b>perform</b> the tests? &ldquo;The laboratory will ___ a second set of tests before publishing.&rdquo;',
      options:['carry out','carry on','carry off','carry over'],
      answer:'carry out',
      hint:'Decide for each particle whether it starts the work, continues it, delays it or wins with it.',
      explanation:'<b>Carry out</b> an instruction, a test or an order is to perform it. <i>Carry on</i> is to continue with work already begun, <i>carry off</i> is to manage something difficult successfully (or to take something away), and <i>carry over</i> is to move something to a later date or page.' }),

    // ══ g9eng-gr-prepositions · prepositions (033–040) ════════════════════
    // Each item turns on what GOVERNS the preposition — the noun, the
    // adjective or the verb — rather than on remembering a pair.

    makeMCQ({ id:'g9eng-d6-033', chapterId:'g9eng-gr-prepositions', subsection:'prepositions', difficulty:4,
      question:'Here the preposition is chosen by the noun <b>rise</b>, not by the verb <i>explain</i>. Complete: &ldquo;Nobody could explain the sharp rise ___ the price of vegetables.&rdquo;',
      options:['in','of','to','on'],
      answer:'in',
      hint:'Ask which word in the sentence the gap actually belongs to before you choose.',
      explanation:'A <b>rise in</b> something names what is going up: prices, temperature, unemployment. A <i>rise of</i> is followed by an amount — <i>a rise of ten per cent</i> — so it cannot introduce the thing itself. The verb <i>explain</i> takes no preposition at all here, which is why pupils who look at the verb choose wrongly.' }),

    makeText({ id:'g9eng-d6-034', chapterId:'g9eng-gr-prepositions', subsection:'prepositions', difficulty:4,
      question:'The verb <i>solve</i> takes no preposition, but the noun <b>solution</b> does. Write the ONE word needed here: &ldquo;There is no easy solution ___ the traffic problem in Port Louis.&rdquo;',
      answer:'to', alsoAccept:['for'],
      hint:'A noun and the verb it comes from do not always behave the same way. Look at the noun.',
      explanation:'<b>Solution to</b> a problem is the standard pairing, just as we say an <i>answer to</i> a question and a <i>reply to</i> a letter. <i>Solve</i> itself is followed straight by its object — <i>solve the problem</i>, never <i>solve to the problem</i> — so turning the verb into a noun adds a preposition that was not there before.' }),

    makeMCQ({ id:'g9eng-d6-035', chapterId:'g9eng-gr-prepositions', subsection:'prepositions', difficulty:4,
      question:'Which sentence would be accepted in a written school report?',
      options:['Her handwriting is quite different from her brother&rsquo;s.',
               'Her handwriting is quite different than her brother&rsquo;s.',
               'Her handwriting is quite different as her brother&rsquo;s.',
               'Her handwriting is quite different with her brother&rsquo;s.'],
      answer:'Her handwriting is quite different from her brother&rsquo;s.',
      hint:'Two of these are shaped like comparisons with <i>more</i> or <i>the same</i>, which is where the mistake comes from.',
      explanation:'<b>Different from</b> is the form expected in written English. <i>Different than</i> is widely heard and is borrowed from comparatives such as <i>bigger than</i>; <i>as</i> belongs with <i>the same as</i>; and <i>with</i> belongs with <i>compare with</i>. The adjective, not the sentence pattern, chooses the preposition.' }),

    makeMCQ({ id:'g9eng-d6-036', chapterId:'g9eng-gr-prepositions', subsection:'prepositions', difficulty:4,
      question:'One of these sentences contains a preposition that standard English does not allow after its verb. Which one?',
      options:['The class discussed about the new timetable.',
               'The class complained about the new timetable.',
               'The class argued about the new timetable.',
               'The class asked about the new timetable.'],
      answer:'The class discussed about the new timetable.',
      hint:'Try putting each verb straight in front of its object with no preposition, and see which one survives.',
      explanation:'<b>Discuss</b> is a transitive verb: it takes its object directly, so <i>discussed the new timetable</i> is right and <i>discussed about</i> is an extra word. <i>Complain</i>, <i>argue</i> and <i>ask</i> all need a preposition before the topic. The meanings are similar, which is exactly why the pattern has to be learnt verb by verb.' }),

    makeText({ id:'g9eng-d6-037', chapterId:'g9eng-gr-prepositions', subsection:'prepositions', difficulty:4,
      question:'<b>Responsible</b> takes one preposition when it means <i>in charge of a task</i> and a different one when it means <i>answerable to a person</i>. Write the ONE word needed here: &ldquo;The council is responsible ___ maintaining every public beach.&rdquo;',
      answer:'for',
      hint:'Decide first which of the two meanings this sentence is using, then choose.',
      explanation:'<b>Responsible for</b> introduces the duty or the thing being looked after. <i>Responsible to</i> introduces the person or body you must answer to — <i>the council is responsible to the ratepayers</i>. Both are correct English, so only the rest of the sentence can tell you which one is wanted.' }),

    makeMCQ({ id:'g9eng-d6-038', chapterId:'g9eng-gr-prepositions', subsection:'prepositions', difficulty:4,
      question:'A newspaper writes that a diplomat is <i>immune from prosecution</i>. Which preposition follows <b>immune</b> when the sentence is about a disease instead of a law? &ldquo;Two doses have made the herd almost entirely immune ___ the virus.&rdquo;',
      options:['to','from','of','against'],
      answer:'to',
      hint:'The same adjective is being used in two senses. Match the preposition to the sense, not to the newspaper.',
      explanation:'<b>Immune to</b> a disease means the body can resist it; <b>immune from</b> a rule or a penalty means exempt from it, which is the diplomat&rsquo;s sense. <i>Of</i> never follows <i>immune</i>, and <i>against</i> belongs with <i>vaccinate</i> or <i>protect</i>. One adjective, two prepositions, and the topic decides.' }),

    makeMCQ({ id:'g9eng-d6-039', chapterId:'g9eng-gr-prepositions', subsection:'prepositions', difficulty:4,
      question:'Which sentence says that the council agreed <b>eventually</b>, after a long argument — rather than saying when it agreed?',
      options:['In the end, the council agreed to fund the project.',
               'At the end, the council agreed to fund the project.',
               'By the end, the council agreed to fund the project.',
               'To the end, the council agreed to fund the project.'],
      answer:'In the end, the council agreed to fund the project.',
      hint:'Three of these are about a point in time. Only one is about how a process turned out.',
      explanation:'<b>In the end</b> means finally, after difficulty, and reports the outcome of a process. <i>At the end</i> names a point and normally needs a noun after it — <i>at the end of the debate</i>. <i>By the end</i> sets a deadline, and <i>to the end</i> means right through to the finish, which would say the council never changed its mind at all.' }),

    makeText({ id:'g9eng-d6-040', chapterId:'g9eng-gr-prepositions', subsection:'prepositions', difficulty:4,
      question:'<i>Rest on</i> and <i>rest with</i> do not mean the same thing. Write the ONE word needed so that the sentence says the head teacher has the authority: &ldquo;The final decision rests ___ the head teacher alone.&rdquo;',
      answer:'with',
      hint:'One of the two says where the power lies; the other says what the argument depends on.',
      explanation:'A decision <b>rests with</b> the person who has the power to make it. A case or an argument <b>rests on</b> the evidence that supports it — <i>the whole case rests on one witness</i>. Both are ordinary English, so the preposition, and only the preposition, tells the reader whether we are being told about authority or about evidence.' }),

    // ══ g9eng-gr-sentence · voice (041–045) ═══════════════════════════════

    makeMCQ({ id:'g9eng-d6-041', chapterId:'g9eng-gr-sentence', subsection:'voice', difficulty:4,
      question:'All four sentences are passive and all four name their agent. In which one does naming the agent actually tell the reader something worth knowing?',
      options:['The report was written by the head of department.',
               'The classroom was cleaned by somebody yesterday.',
               'The window was broken by someone during the night.',
               'The letters were delivered by a person this morning.'],
      answer:'The report was written by the head of department.',
      hint:'Cross out the <i>by</i> phrase in each sentence and ask what the reader has lost.',
      explanation:'Naming the head of department tells the reader how much authority the report carries, so the agent earns its place. In the other three the agent is <i>somebody</i>, <i>someone</i> or <i>a person</i> — the reader learns nothing, and good writing would simply leave the phrase out. A passive that names a vague agent is the worst of both constructions.' }),

    makeText({ id:'g9eng-d6-042', chapterId:'g9eng-gr-sentence', subsection:'voice', difficulty:1,
      question:'Write the ONE word that must be added so that this passive sentence names the person who acted: &ldquo;The results were announced ___ the head teacher.&rdquo;',
      answer:'by',
      hint:'The missing word is the one that introduces the agent of a passive sentence.',
      explanation:'In a passive sentence the agent — the person or thing that did the action — is introduced by <b>by</b>. Without it the sentence is still correct English, but it simply does not say who announced the results, which is often exactly why a writer chooses the passive.' }),

    makeMCQ({ id:'g9eng-d6-043', chapterId:'g9eng-gr-sentence', subsection:'voice', difficulty:4,
      question:'This active sentence has two objects: <i>The school gave the pupils a new timetable.</i> Which passive keeps <b>the pupils</b> as the subject?',
      options:['The pupils were given a new timetable by the school.',
               'A new timetable was given the pupils by the school.',
               'The pupils were gave a new timetable by the school.',
               'A new timetable gave the pupils by the school today.'],
      answer:'The pupils were given a new timetable by the school.',
      hint:'Decide which noun the question wants at the front, then check the verb form that follows it.',
      explanation:'A verb with two objects can be turned into two different passives, and the question chooses between them: starting with <i>the pupils</i> needs <b>were given</b>. Starting with the timetable is possible English, but it answers a different question. The third option uses the past tense <i>gave</i> where the past participle <i>given</i> is required, and the fourth is active with the roles reversed.' }),

    makeMCQ({ id:'g9eng-d6-044', chapterId:'g9eng-gr-sentence', subsection:'voice', difficulty:4,
      question:'Active: <i>Someone must look into these complaints.</i> The verb is a phrasal verb, so its particle has to travel with it. Which passive is correct?',
      options:['These complaints must be looked into at once.',
               'These complaints must be look into at once.',
               'These complaints must be looking into at once.',
               'These complaints must have looked into at once.'],
      answer:'These complaints must be looked into at once.',
      hint:'After <i>must be</i> the verb can only take one form. Check that form before you look at the particle.',
      explanation:'A passive is <i>be</i> plus a past participle, so <b>must be looked into</b> is the only possible shape, and the particle <i>into</i> stays attached even though nothing follows it. The bare infinitive <i>look</i> and the <i>-ing</i> form cannot follow <i>be</i> in a passive, and <i>must have looked</i> is active perfect — it would say the complaints did the looking.' }),

    makeTF({ id:'g9eng-d6-045', chapterId:'g9eng-gr-sentence', subsection:'voice', difficulty:2,
      question:'True or False: turning &ldquo;The committee rejected every proposal&rdquo; into &ldquo;Every proposal was rejected by the committee&rdquo; changes who did the rejecting.',
      answer:false,
      hint:'Find the agent in each version before deciding.',
      explanation:'False. Changing the voice changes which noun stands at the front of the sentence, not who acted. The committee is the agent in both versions — in the active it is the subject, and in the passive it follows <b>by</b>. What does change is emphasis: the passive puts the proposals first.' }),

    // ══ g9eng-gr-sentence · perfect_conditional (046–057) ═════════════════

    makeMCQ({ id:'g9eng-d6-046', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'Which sentence says that an unreal PAST decision would still be shaping her life NOW?',
      options:['If she had taken the job, she would be in Rodrigues now.',
               'If she had taken the job, she would have been in Rodrigues.',
               'If she takes the job, she will be in Rodrigues next month.',
               'If she took the job, she would be in Rodrigues by August.'],
      answer:'If she had taken the job, she would be in Rodrigues now.',
      hint:'Look at the two halves separately: one must be about the past, the other about the present.',
      explanation:'This is a <b>mixed conditional</b>: a third-conditional <i>if</i> clause about the past joined to a second-conditional result about the present. The second option keeps both halves in the past, so it describes where she would have been then, not where she would be today. The last two are about a decision that is still open.' }),

    makeText({ id:'g9eng-d6-047', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'Write ONE word in the gap so that the result is happening NOW rather than in the past: &ldquo;If I had studied medicine, I ___ be working in a hospital today.&rdquo;',
      answer:'would', alsoAccept:['could','might'],
      hint:'The <i>if</i> clause is already in the past perfect. Only the result clause is yours to fix.',
      explanation:'A present result after a past condition takes <b>would</b> (or <i>could</i> / <i>might</i>) followed by a plain infinitive: <i>would be working</i>. Writing <i>would have been working</i> would push the result back into the past and contradict the word <i>today</i>. The two halves of a mixed conditional are allowed to sit in different times.' }),

    makeMCQ({ id:'g9eng-d6-048', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'Which sentence means the same as <i>If the council had acted sooner, the beach would have survived</i>, with the word <b>if</b> removed?',
      options:['Had the council acted sooner, the beach would have survived.',
               'Should the council act sooner, the beach would survive well.',
               'Did the council act sooner, the beach would have survived it.',
               'Were the council to act sooner, the beach would survive well.'],
      answer:'Had the council acted sooner, the beach would have survived.',
      hint:'When <i>if</i> is dropped, one auxiliary verb moves in front of the subject. Ask which auxiliary the original uses.',
      explanation:'A third conditional drops <i>if</i> by inverting <b>had</b> with the subject: <i>Had the council acted</i>. <i>Should</i> and <i>were</i> invert real conditionals about the future, not unreal ones about the past, and <i>did</i> is never used this way in standard English. Inversion of this kind is formal and common in written reports.' }),

    makeMCQ({ id:'g9eng-d6-049', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'&ldquo;I would have told you, but you were asleep.&rdquo; Which conditional sentence states the condition this speaker has left unsaid?',
      options:['If you had not been asleep, I would have told you.',
               'If I had told you, you would not have been asleep.',
               'If you were asleep, I would have to tell you later.',
               'If I tell you now, you will not be asleep any more.'],
      answer:'If you had not been asleep, I would have told you.',
      hint:'The <i>but</i> clause names the obstacle. Turn that obstacle into a negative condition.',
      explanation:'The <i>but</i> clause gives the real fact — you were asleep — so the unreal condition must be its negative, and the result keeps the perfect conditional the speaker already used. The second option swaps cause and effect, and the last two move the whole sentence out of the past, where the speaker clearly put it.' }),

    makeTF({ id:'g9eng-d6-050', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'True or False: &ldquo;If they had booked earlier, they would have a seat now&rdquo; is a mistake, because a past-perfect <i>if</i> clause can never be followed by a present result.',
      answer:false,
      hint:'Check whether the two halves are describing the same moment in time before you judge the sentence.',
      explanation:'False. That is a mixed conditional and it is perfectly correct: the booking that did not happen is in the past, and the seat they do not have is in the present. Insisting on <i>would have had</i> would lose the word <i>now</i>. A conditional is not obliged to keep both halves in one time.' }),

    makeMCQ({ id:'g9eng-d6-051', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'Which sentence uses a perfect conditional to express regret about something that did NOT happen?',
      options:['I would have apologised, but nobody told me.',
               'I will have apologised before the meeting ends.',
               'I would apologise if anybody ever asked me to.',
               'I had apologised long before the meeting began.'],
      answer:'I would have apologised, but nobody told me.',
      hint:'Three of these describe something real or still possible. Find the one describing something that can no longer happen.',
      explanation:'<b>Would have apologised</b> is the perfect conditional and it always describes an unreal past: the apology was never made. <i>Will have apologised</i> is future perfect and says it certainly will be; <i>would apologise</i> leaves the possibility open; and <i>had apologised</i> is past perfect and reports something that really did happen.' }),

    makeText({ id:'g9eng-d6-052', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'Write ONE word in the gap so that the sentence blames a past obstacle for a result that never came: &ldquo;___ for the heavy rain, the match would have finished before six.&rdquo;',
      answer:'But', alsoAccept:['but','Were','were','Except','except'],
      hint:'The missing word teams up with <i>for</i> to mean &ldquo;if this had not happened&rdquo;.',
      explanation:'<b>But for</b> the heavy rain means <i>if it had not been for</i> the heavy rain — a compact way of writing a third conditional without <i>if</i>. The result clause keeps its perfect conditional, <i>would have finished</i>. Note that the sentence tells you the match did NOT finish before six, because the condition was never met.' }),

    makeMCQ({ id:'g9eng-d6-053', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'Which sentence carries the same meaning as <i>If the alarm had not rung, the fire would have spread</i>?',
      options:['The alarm rang; otherwise the fire would have spread.',
               'The alarm rang, so the fire would have spread quickly.',
               'The alarm did not ring; otherwise the fire spread fast.',
               'The alarm rang because the fire would have spread fast.'],
      answer:'The alarm rang; otherwise the fire would have spread.',
      hint:'First work out from the original whether the alarm actually rang, then find the option that agrees.',
      explanation:'A negative third-conditional <i>if</i> clause reports the opposite as fact: the alarm DID ring, and because it did the fire did not spread. <b>Otherwise</b> carries that unreal alternative on its own. The second option makes the ringing cause the spreading, the third denies the ringing, and the fourth reverses cause and effect.' }),

    makeMCQ({ id:'g9eng-d6-054', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:3,
      question:'Complete the third conditional: &ldquo;If the driver had checked the tyres, the accident ___.&rdquo;',
      options:['would not have happened','would not be happening','will not have happened','had not been happening'],
      answer:'would not have happened',
      hint:'Match the result clause to an <i>if</i> clause that is already in the past perfect.',
      explanation:'The pattern is <i>if</i> + past perfect, then <b>would have</b> + past participle. <i>Would not be happening</i> describes the present, <i>will not have happened</i> is a future prediction, and <i>had not been happening</i> repeats the tense of the <i>if</i> clause instead of answering it.' }),

    makeMCQ({ id:'g9eng-d6-055', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:1,
      question:'In a third conditional, which verb form follows the word <b>if</b>?',
      options:['had + past participle','would + infinitive','will + infinitive','is + past participle'],
      answer:'had + past participle',
      hint:'Think about which half of the sentence the word <i>would</i> belongs in.',
      explanation:'The <i>if</i> clause of a third conditional uses the past perfect: <b>had</b> plus a past participle, as in <i>if she had known</i>. <i>Would</i> belongs in the result clause and never after <i>if</i> in this pattern — putting it there is the commonest third-conditional mistake.' }),

    makeText({ id:'g9eng-d6-056', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:1,
      question:'Write the ONE word that is missing from this third conditional: &ldquo;If Nisha had known about the change, she ___ have warned us.&rdquo;',
      answer:'would', alsoAccept:['could','might'],
      hint:'The result clause of a third conditional begins with a modal verb.',
      explanation:'The result clause of a third conditional is <b>would have</b> plus a past participle. <i>Could have</i> and <i>might have</i> are also possible and soften the claim to <i>was able to</i> or <i>perhaps</i>, but the plain form is <i>would have warned</i>.' }),

    makeMCQ({ id:'g9eng-d6-057', chapterId:'g9eng-gr-sentence', subsection:'perfect_conditional', difficulty:4,
      question:'&ldquo;If the bus had broken down, we would have missed the ceremony.&rdquo; Both halves are in the past. Which half describes something that really happened?',
      options:['Neither half describes something that happened.',
               'The if-clause describes something that happened.',
               'The main clause describes what really happened.',
               'Both halves describe something that really happened.'],
      answer:'Neither half describes something that happened.',
      hint:'Ask what the sentence quietly tells you about the bus and about the ceremony.',
      explanation:'A third conditional is <b>counterfactual</b>: it tells you the opposite of what it says. The bus did not break down, and so the ceremony was not missed. This is why the pattern is used for regret and for relief, and why reading it as a report of events reverses the facts completely.' }),

    // ══ g9eng-gr-sentence · direct_speech (058–068) ═══════════════════════
    // Reported speech and speaker identity. The mechanics of the marks
    // themselves — which mark, where — belong to g9eng-gr-punctuation.

    makeMCQ({ id:'g9eng-d6-058', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:4,
      question:'&ldquo;I will finish your portrait tomorrow,&rdquo; the artist told Nadia last week. Three things must shift at once. Which report is correct?',
      options:['The artist told Nadia she would finish her portrait the next day.',
               'The artist told Nadia she will finish her portrait the next day.',
               'The artist told Nadia I would finish your portrait the next day.',
               'The artist told Nadia that she would finish her portrait tomorrow.'],
      answer:'The artist told Nadia she would finish her portrait the next day.',
      hint:'Check the tense, then the pronouns, then the time word. One option gets two of the three right.',
      explanation:'Reporting a week later shifts the tense (<i>will</i> to <b>would</b>), the pronouns (<i>I</i> and <i>your</i> to <b>she</b> and <b>her</b>) and the time expression (<i>tomorrow</i> to <b>the next day</b>). The last option is the trap: everything is right except the time word, which still points at the day after today rather than the day after the promise.' }),

    makeMCQ({ id:'g9eng-d6-059', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:4,
      question:'&ldquo;Where have you put the keys?&rdquo; Rajesh asked his sister. Which report is correct?',
      options:['Rajesh asked his sister where she had put the keys.',
               'Rajesh asked his sister where had she put the keys.',
               'Rajesh asked his sister where has she put the keys.',
               'Rajesh asked his sister where did she put the keys.'],
      answer:'Rajesh asked his sister where she had put the keys.',
      hint:'A reported question is no longer a question. Ask what that does to the order of subject and verb.',
      explanation:'A reported question takes <b>statement word order</b>: subject before verb, with no inversion and no question mark. The auxiliary also shifts back, so <i>have put</i> becomes <b>had put</b>. Keeping the inverted order of the spoken question is the mistake all three distractors make, in three different tenses.' }),

    makeText({ id:'g9eng-d6-060', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:4,
      question:'The words were spoken at the depot and are being reported somewhere else. Write the ONE word that replaces <b>here</b>: &ldquo;I left the parcel here,&rdquo; he said. &rarr; He said he had left the parcel ___.',
      answer:'there',
      hint:'The reporter is no longer standing where the speaker stood, so the word must point away rather than close.',
      explanation:'Words that point at the speaker&rsquo;s own position shift when the position changes: <b>here</b> becomes <b>there</b>, just as <i>this</i> becomes <i>that</i> and <i>now</i> becomes <i>then</i>. If the report were given at the depot itself, <i>here</i> could stay — the shift follows the situation, not a mechanical rule.' }),

    makeMCQ({ id:'g9eng-d6-061', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:4,
      question:'Ameena and Vikash are arguing. The passage reads:<br><i>&ldquo;You promised to wait for me,&rdquo; said Ameena.</i><br><i>&ldquo;I waited outside for a whole hour.&rdquo;</i><br>Who speaks the second line?',
      options:['Vikash, because a new paragraph marks a new speaker.',
               'Ameena, because she is the speaker named first.',
               'Ameena, because the line has no reporting clause.',
               'Vikash, because the second line answers a question.'],
      answer:'Vikash, because a new paragraph marks a new speaker.',
      hint:'Nothing in the second line names anybody, so the layout is the only evidence you have.',
      explanation:'In written dialogue each new speaker begins a new paragraph, and that convention alone identifies the second voice — which is why a writer can drop the reporting clause once the pattern is running. The absence of <i>said Vikash</i> is not a reason to keep Ameena speaking, and the second line is a reply rather than an answer to a question.' }),

    makeMCQ({ id:'g9eng-d6-062', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:4,
      question:'&ldquo;You must not touch the wires,&rdquo; the electrician warned the boys. Which report is correct?',
      options:['The electrician warned the boys not to touch the wires.',
               'The electrician warned the boys must not touch the wires.',
               'The electrician warned the boys they must not touching wires.',
               'The electrician warned the boys to not touching the wires.'],
      answer:'The electrician warned the boys not to touch the wires.',
      hint:'<i>Warn</i> is one of the verbs that can take an infinitive. Work out where the negative has to go.',
      explanation:'After <b>warn somebody</b>, English prefers a negative infinitive: <i>not to touch</i>. The second option drops the linking word that <i>must</i> would need, and the last two combine <i>to</i> with an <i>-ing</i> form, which no English verb pattern allows. A report of an order or a warning is often shorter than the words spoken.' }),

    makeMCQ({ id:'g9eng-d6-063', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:4,
      question:'&ldquo;Water boils at 100 degrees,&rdquo; the teacher said. Which report keeps the present tense because the statement is still true?',
      options:['The teacher said that water boils at 100 degrees.',
               'The teacher said that water boiled at 100 degrees.',
               'The teacher said that water had boiled at 100 now.',
               'The teacher said that water will boil at 100 degrees.'],
      answer:'The teacher said that water boils at 100 degrees.',
      hint:'The usual backshift is a habit, not a law. Ask whether the fact stopped being true when the teacher stopped speaking.',
      explanation:'Reported speech normally shifts the tense back one step, but a statement that is permanently true may keep the present — and doing so quietly tells the reader the speaker was right. <i>Boiled</i> is not wrong English, yet it reports the claim as belonging to that moment; <i>had boiled</i> turns a general truth into a single past event.' }),

    makeText({ id:'g9eng-d6-064', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:4,
      question:'The listener is named in the report, so the reporting verb must change. Write the ONE word that replaces <b>said</b>: &ldquo;I am leaving,&rdquo; she said. &rarr; She ___ me she was leaving.',
      answer:'told',
      hint:'One reporting verb takes a person straight after it; the other needs a small word in between.',
      explanation:'<b>Told</b> takes the listener as a direct object: <i>she told me</i>. <i>Said</i> cannot — it needs <i>to</i> first, as in <i>she said to me</i>. Choosing between the two is decided by whether the person being spoken to is named, which is why the pair is tested in every paper.' }),

    makeMCQ({ id:'g9eng-d6-065', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:3,
      question:'Report these words: She said, &ldquo;I have lost my umbrella.&rdquo;',
      options:['She said she had lost her umbrella.',
               'She said she has lost her umbrella.',
               'She said she had lost my umbrella.',
               'She said I had lost her umbrella.'],
      answer:'She said she had lost her umbrella.',
      hint:'Two things change together here: the tense of the verb and the owner of the umbrella.',
      explanation:'The present perfect <i>have lost</i> shifts back to the past perfect <b>had lost</b>, and both <i>I</i> and <i>my</i> belong to the speaker, so both become <b>she</b> and <b>her</b>. Changing one and forgetting the other is what the three distractors each do.' }),

    makeMCQ({ id:'g9eng-d6-066', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:1,
      question:'Reported speech usually moves a verb one step further into the past. In a report of &ldquo;I <b>am</b> busy&rdquo;, what does <b>am</b> become?',
      options:['was','were','is','been'],
      answer:'was',
      hint:'Keep the same subject in mind: the verb must still agree with one person.',
      explanation:'The present <i>am</i> shifts back to the simple past <b>was</b>, giving <i>he said he was busy</i>. <i>Were</i> would be needed for a plural subject, <i>is</i> is still present, and <i>been</i> is a participle that cannot stand on its own.' }),

    makeText({ id:'g9eng-d6-067', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:1,
      question:'Write the ONE word that completes the report, given that it is made on a later day: &ldquo;I am busy today,&rdquo; he said. &rarr; He said he was busy that ___.',
      answer:'day',
      hint:'The word <i>that</i> is already there, waiting for the noun it points back to.',
      explanation:'<b>Today</b> becomes <i>that day</i> once the report is made on a different day, in the same way that <i>tomorrow</i> becomes <i>the next day</i> and <i>yesterday</i> becomes <i>the day before</i>. Leaving <i>today</i> in place would point at the day of the report instead of the day he spoke.' }),

    makeTF({ id:'g9eng-d6-068', chapterId:'g9eng-gr-sentence', subsection:'direct_speech', difficulty:2,
      question:'True or False: when a statement is reported, the pronouns may have to change even though nothing about the speaker&rsquo;s meaning has changed.',
      answer:true,
      hint:'Think about who <i>I</i> and <i>you</i> refer to before and after the words are passed on.',
      explanation:'True. <i>I</i> and <i>you</i> mean whoever is speaking and whoever is listening, so once a third person passes the words on, those same people have to be named differently — <i>&ldquo;I saw you&rdquo;</i> becomes <i>he said he had seen her</i>. The meaning is identical; only the point of view has moved.' })

  );

})();
