'use strict';
(function () {
STATIC_QUESTIONS.push(

  // ── future_perfect (g9eng-grv-061 – g9eng-grv-080) ──────────────────────

  makeMCQ({ id:'g9eng-grv-061', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'By the time you arrive at the stadium, the match _____.',
    options:['will have started','will start','has started','started'],
    answer:'will have started',
    hint:'Both events are in the future, but the match starts first.',
    explanation:'The future perfect (<b>will have started</b>) shows an action completed before a specific future point — here, before you arrive.' }),

  makeMCQ({ id:'g9eng-grv-062', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'By next April, she _____ her nursing qualification.',
    options:['will have earned','will earn','has earned','earns'],
    answer:'will have earned',
    hint:'"By next April" is a future deadline — the earning is complete before then.',
    explanation:'<b>Will have earned</b> is the future perfect, signalling that the qualification is gained before next April arrives.' }),

  makeMCQ({ id:'g9eng-grv-063', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:3,
    question:'Which sentence uses the future perfect correctly?',
    options:['By the time he lands, she will have reached the hotel.','By the time he lands, she will reach the hotel.','By the time he lands, she has reached the hotel.','By the time he lands, she had reached the hotel.'],
    answer:'By the time he lands, she will have reached the hotel.',
    hint:'Both events are future, but one is complete before the other.',
    explanation:'<b>Will have reached</b> shows her arrival is complete before his landing. "Will reach" suggests the two happen at the same moment.' }),

  makeMCQ({ id:'g9eng-grv-064', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'By the end of the school year, the pupils _____ twelve novels for the literature course.',
    options:['will have read','will read','have read','were reading'],
    answer:'will have read',
    hint:'"By the end" marks a future point before which the reading is complete.',
    explanation:'<b>Will have read</b> (future perfect) shows the twelve novels are finished before the school year ends.' }),

  makeMCQ({ id:'g9eng-grv-065', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'The renovation crew guarantees that by next weekend, they _____ the kitchen back to the owners.',
    options:['will have returned','will return','are returning','have returned'],
    answer:'will have returned',
    hint:'The handover is done before next weekend — a future point of completion.',
    explanation:'<b>Will have returned</b> (future perfect) places the handover as finished before next weekend. "Will return" does not specify that it is done before the deadline.' }),

  makeMCQ({ id:'g9eng-grv-066', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'Before the committee meets on Monday, the treasurer _____ the accounts.',
    options:['will have audited','will audit','is auditing','audited'],
    answer:'will have audited',
    hint:'"Before the committee meets" places the audit prior to a future event.',
    explanation:'The future perfect <b>will have audited</b> makes the audit clearly complete before Monday\'s meeting. "Will audit" does not convey that sequence.' }),

  makeMCQ({ id:'g9eng-grv-067', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:3,
    question:'A student writes: "By the time the nurse arrives, the patient will recover." What error has been made?',
    options:['The tense is wrong — use "will have recovered".','\"Will recover\" is already correct here.','The past perfect should be used instead.','\"Will be recovering\" is the only correct option.'],
    answer:'The tense is wrong — use "will have recovered".',
    hint:'The recovery is complete before the nurse arrives — which tense shows that?',
    explanation:'Two future events, one before the other, need the future perfect: <b>will have recovered</b>. "Will recover" suggests they happen at the same time.' }),

  makeMCQ({ id:'g9eng-grv-068', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'By midnight tonight, the rescue team _____ the last of the survivors.',
    options:['will have found','will find','finds','had found'],
    answer:'will have found',
    hint:'"By midnight tonight" is the deadline for completion.',
    explanation:'<b>Will have found</b> shows the action complete at or before midnight — the future perfect tense.' }),

  makeMCQ({ id:'g9eng-grv-069', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:3,
    question:'Choose the sentence that correctly uses the future perfect in the passive.',
    options:['The bridge will have been built by 2028.','The bridge will be built by 2028.','The bridge has been built by 2028.','The bridge had been built by 2028.'],
    answer:'The bridge will have been built by 2028.',
    hint:'Passive future perfect = will have been + past participle.',
    explanation:'<b>Will have been built</b> combines passive and future perfect: construction is done by someone and is complete before 2028.' }),

  makeMCQ({ id:'g9eng-grv-070', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'By the time this song ends, I _____ it fifty times.',
    options:['will have heard','will hear','heard','am hearing'],
    answer:'will have heard',
    hint:'The fiftieth hearing is complete at the moment the song ends.',
    explanation:'<b>Will have heard</b> counts an action completed by a future point. The future perfect stacks up repeated actions against a deadline.' }),

  makeMCQ({ id:'g9eng-grv-071', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'"She will have left the office long before you get there." The verb phrase "will have left" is in the _____ tense.',
    options:['future perfect','future simple','present perfect','past perfect'],
    answer:'future perfect',
    hint:'will have + past participle = which tense?',
    explanation:'<b>Will have left</b> is the future perfect: it places her departure before your future arrival. Present perfect uses "has/have" and past perfect uses "had".' }),

  makeMCQ({ id:'g9eng-grv-072', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'Complete the sentence: "By the time the review is published, the author _____ the second draft."',
    options:['will have finished','will finish','finishes','finished'],
    answer:'will have finished',
    hint:'The finishing happens before the publication — both are future.',
    explanation:'Future perfect (<b>will have finished</b>) shows a sequence of two future events: finishing comes before publishing.' }),

  makeMCQ({ id:'g9eng-grv-073', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'Which time expression most commonly signals the future perfect tense?',
    options:['"By the time…"','"Right now…"','"Yesterday…"','"Since last week…"'],
    answer:'"By the time…"',
    hint:'Think about which phrase sets a future deadline for completion.',
    explanation:'"<b>By the time</b>" signals a future deadline — exactly what the future perfect describes: an action completed before that point.' }),

  makeMCQ({ id:'g9eng-grv-074', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:1,
    question:'"By nine o\'clock, the sun will have risen." What does this sentence tell us?',
    options:['A completed action before a future point','An action happening right now','An action completed in the past','An action happening exactly at nine o\'clock'],
    answer:'A completed action before a future point',
    hint:'Will have + past participle — what kind of action does this describe?',
    explanation:'The future perfect shows the sunrise as <b>complete before</b> nine o\'clock. It links a future deadline to a finished action.' }),

  makeMCQ({ id:'g9eng-grv-075', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'Before the year is out, the government _____ five new hospitals.',
    options:['will have opened','will open','has opened','had opened'],
    answer:'will have opened',
    hint:'"Before the year is out" is a future deadline — the openings are done before then.',
    explanation:'Future perfect (<b>will have opened</b>) marks all five openings as finished before the end of the year.' }),

  makeMCQ({ id:'g9eng-grv-076', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:3,
    question:'"Is the report ready?" "Not quite — the editor _____ it long before noon."',
    options:['will have finished','will finish','has finished','had finished'],
    answer:'will have finished',
    hint:'"Long before noon" shows finishing is complete before the deadline.',
    explanation:'The future perfect <b>will have finished</b> emphasises that the work is done well before noon. "Will finish" does not clearly place the action before noon.' }),

  makeMCQ({ id:'g9eng-grv-077', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:3,
    question:'The journalist predicts that by the next election, the new party _____ enough support to win.',
    options:['will have gained','will gain','has gained','gains'],
    answer:'will have gained',
    hint:'The support is built up before the election — which tense shows that?',
    explanation:'The future perfect <b>will have gained</b> describes the support as complete and ready by the future election date.' }),

  makeMCQ({ id:'g9eng-grv-078', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'Transform "She leaves the office" into the future perfect with "by 5 p.m."',
    options:['She will have left the office by 5 p.m.','She will leave the office by 5 p.m.','She had left the office by 5 p.m.','She has left the office by 5 p.m.'],
    answer:'She will have left the office by 5 p.m.',
    hint:'Future perfect = will have + past participle.',
    explanation:'The future perfect of "leave" is <b>will have left</b>. "By 5 p.m." anchors the completed departure to a future time.' }),

  makeMCQ({ id:'g9eng-grv-079', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:2,
    question:'By the end of this century, many species of wildlife _____ extinct.',
    options:['will have become','will become','have become','became'],
    answer:'will have become',
    hint:'"By the end of this century" is a future deadline — the process is complete before then.',
    explanation:'<b>Will have become</b> is the future perfect, placing the extinction as done before the century ends.' }),

  makeMCQ({ id:'g9eng-grv-080', chapterId:'g9eng-gr-verbs', subsection:'future_perfect', difficulty:3,
    question:'"They _____ the experiment three times before the end of the lesson," the teacher announced.',
    options:['will have repeated','will repeat','repeated','repeat'],
    answer:'will have repeated',
    hint:'"Before the end of the lesson" is the future point; the repetitions are complete by then.',
    explanation:'The future perfect <b>will have repeated</b> shows all three repetitions finished before the lesson ends — a completed sequence within a future timeline.' }),

  // ── future_perfect_continuous (g9eng-grv-081 – g9eng-grv-100) ───────────

  makeMCQ({ id:'g9eng-grv-081', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'By the time the school reunion takes place, Priya _____ in London for five years.',
    options:['will have been living','will have lived','will be living','has been living'],
    answer:'will have been living',
    hint:'"For five years" emphasises duration up to a future point.',
    explanation:'<b>Will have been living</b> (future perfect continuous) stresses five continuous years of residence up to the reunion. "Will have lived" focuses on completion rather than the ongoing experience.' }),

  makeMCQ({ id:'g9eng-grv-082', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'By this time tomorrow, we _____ for twelve hours.',
    options:['will have been driving','will have driven','will be driving','had been driving'],
    answer:'will have been driving',
    hint:'A twelve-hour stretch leading up to a future point — which tense captures that?',
    explanation:'The future perfect continuous <b>will have been driving</b> highlights the twelve-hour stretch of driving continuing right up to "this time tomorrow".' }),

  makeMCQ({ id:'g9eng-grv-083', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'What does "will have been + -ing" emphasise compared to "will have + past participle"?',
    options:['The duration or ongoing nature of an action','The completion of an action','The starting point of an action','That an action happened only once'],
    answer:'The duration or ongoing nature of an action',
    hint:'Compare "I will have read the book" with "I will have been reading the book for hours".',
    explanation:'The future perfect continuous draws attention to <b>how long</b> an action continues up to a future point; the simple future perfect focuses on the <b>fact</b> of completion.' }),

  makeMCQ({ id:'g9eng-grv-084', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'By the time the election results are announced, journalists _____ the story for twenty-four hours.',
    options:['will have been covering','will have covered','will be covering','are covering'],
    answer:'will have been covering',
    hint:'"For twenty-four hours" signals a sustained period of activity up to a future point.',
    explanation:'When a time phrase stresses <b>how long</b> an action continues to a future moment, the future perfect continuous is preferred over the simple future perfect.' }),

  makeMCQ({ id:'g9eng-grv-085', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'Which sentence uses the future perfect continuous correctly?',
    options:['By next month, she will have been studying French for two years.','By next month, she will study French for two years.','By next month, she has been studying French for two years.','By next month, she had studied French for two years.'],
    answer:'By next month, she will have been studying French for two years.',
    hint:'"For two years, by next month" — duration up to a future point.',
    explanation:'The future perfect continuous places a two-year stretch of study ending at a specified future point. It is formed with <b>will have been + -ing</b>.' }),

  makeMCQ({ id:'g9eng-grv-086', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'By the time he retires, he _____ medicine for forty years.',
    options:['will have been practising','will have practised','will be practising','has practised'],
    answer:'will have been practising',
    hint:'Is the sentence emphasising the total duration of an ongoing career?',
    explanation:'Retirement closes a forty-year stretch of practice. <b>Will have been practising</b> marks the duration; "will have practised" stresses completion and counts the years less vividly.' }),

  makeMCQ({ id:'g9eng-grv-087', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'Form the future perfect continuous of "teach": "By June, Mrs Ramful _____ at this school for thirty years."',
    options:['will have been teaching','will have taught','will teach','has been teaching'],
    answer:'will have been teaching',
    hint:'will have been + -ing form of the verb.',
    explanation:'The future perfect continuous of "teach" is <b>will have been teaching</b>. It highlights the continuous thirty-year career ending at the future point of June.' }),

  makeMCQ({ id:'g9eng-grv-088', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'A marathon runner says: "By the finish line, I _____ for four hours." Choose the correct form.',
    options:['will have been running','will have run','will run','have been running'],
    answer:'will have been running',
    hint:'"For four hours" stresses continuous effort leading to the finish line.',
    explanation:'The runner emphasises <b>how long</b> the effort continues — four hours of sustained running — so the future perfect continuous is the better choice.' }),

  makeMCQ({ id:'g9eng-grv-089', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'Why might a speaker choose "will have been waiting" over "will have waited"?',
    options:['To stress how long the wait lasts','To show the wait is already over','To indicate the wait never happened','To suggest only one moment of waiting'],
    answer:'To stress how long the wait lasts',
    hint:'The continuous form draws attention to the process; the simple form to the result.',
    explanation:'<b>Will have been waiting</b> foregrounds the stretched-out experience of waiting. "Will have waited" simply records that waiting happened before a future point.' }),

  makeMCQ({ id:'g9eng-grv-090', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:1,
    question:'Identify the future perfect continuous verb phrase: "By July, the research team will have been collecting data for five years."',
    options:['will have been collecting','will have','collecting data','for five years'],
    answer:'will have been collecting',
    hint:'The whole verb phrase, not just part of it, is the answer.',
    explanation:'The future perfect continuous is the full verb phrase <b>will have been collecting</b>. "For five years" is the time expression showing duration, not part of the tense.' }),

  makeMCQ({ id:'g9eng-grv-091', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'By the time they land, the passengers _____ in economy class for nine hours.',
    options:['will have been sitting','will have sat','are sitting','will sit'],
    answer:'will have been sitting',
    hint:'Nine hours of continuous discomfort leading to a future landing — which tense fits?',
    explanation:'The future perfect continuous <b>will have been sitting</b> highlights the nine-hour stretch that ends when the plane lands.' }),

  makeMCQ({ id:'g9eng-grv-092', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'Which sentence best expresses a tiresome duration leading to a future point?',
    options:['By midnight, I will have been marking papers for six hours.','By midnight, I will have marked papers.','By midnight, I will mark papers.','By midnight, I marked papers.'],
    answer:'By midnight, I will have been marking papers for six hours.',
    hint:'Which option makes the reader feel the length of the effort?',
    explanation:'<b>Will have been marking</b> with "for six hours" communicates the exhausting stretch of effort. The simple future perfect only records that marking happened.' }),

  makeMCQ({ id:'g9eng-grv-093', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'Transform "She has been studying" into the future perfect continuous (by next year, for three years).',
    options:['She will have been studying for three years by next year.','She will study for three years by next year.','She has been studying for three years by next year.','She had been studying for three years by next year.'],
    answer:'She will have been studying for three years by next year.',
    hint:'Move the action forward to "next year" and stress the three-year duration.',
    explanation:'The future perfect continuous <b>will have been studying</b> carries the ongoing action to a future point while keeping the emphasis on the three-year duration.' }),

  makeMCQ({ id:'g9eng-grv-094', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'By the time we finish this project, the team _____ together for two years.',
    options:['will have been working','will work','have been working','had worked'],
    answer:'will have been working',
    hint:'"For two years, by the time we finish" — duration up to a future point.',
    explanation:'Future perfect continuous <b>will have been working</b> captures the two-year stretch of collaboration ending at project completion.' }),

  makeMCQ({ id:'g9eng-grv-095', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'When I meet her at the airport next Sunday, she _____ non-stop for twenty hours.',
    options:['will have been travelling','will have travelled','travels','is travelling'],
    answer:'will have been travelling',
    hint:'"Non-stop" and "twenty hours" together emphasise a continuous stretch of effort.',
    explanation:'"Non-stop" and "twenty hours" point to the future perfect continuous <b>will have been travelling</b>, which stresses the continuous effort rather than just its completion.' }),

  makeMCQ({ id:'g9eng-grv-096', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'Choose the sentence that uses the future perfect continuous to highlight a lifelong, continuous effort.',
    options:['By her sixtieth birthday, she will have been painting for forty years.','By her sixtieth birthday, she will paint.','By her sixtieth birthday, she has painted.','By her sixtieth birthday, she had been painting.'],
    answer:'By her sixtieth birthday, she will have been painting for forty years.',
    hint:'Which sentence captures forty years of unbroken dedication?',
    explanation:'<b>Will have been painting</b> stresses forty years of continuous creative work. The simple forms in the other options lose the sense of ongoing dedication.' }),

  makeMCQ({ id:'g9eng-grv-097', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'"They will have been rehearsing for three months by opening night." What does this tell us?',
    options:['They rehearse continuously in the lead-up to opening night.','They rehearsed once, three months ago.','They will begin rehearsing on opening night.','They have never rehearsed before.'],
    answer:'They rehearse continuously in the lead-up to opening night.',
    hint:'The future perfect continuous stresses an ongoing process up to a future point.',
    explanation:'The sentence pictures <b>continuous rehearsal</b> across three months, arriving at opening night — that is what the future perfect continuous communicates.' }),

  makeMCQ({ id:'g9eng-grv-098', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:2,
    question:'By the time the charity race ends, the organisers _____ for twelve months.',
    options:['will have been planning','will plan','plan','planned'],
    answer:'will have been planning',
    hint:'Twelve months of continuous planning leads to the future race day.',
    explanation:'The future perfect continuous <b>will have been planning</b> pictures twelve months of ongoing preparation finishing at the race.' }),

  makeMCQ({ id:'g9eng-grv-099', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'Which form is grammatically correct? "By the age of eighteen, he _____ music for twelve years."',
    options:['will have been learning','will been learning','will have learn','will be learning'],
    answer:'will have been learning',
    hint:'Future perfect continuous = will + have + been + -ing form.',
    explanation:'The correct structure is <b>will have been</b> + the -ing form: <b>learning</b>. "Will been" omits "have"; "will have learn" uses the base form instead of the -ing.' }),

  makeMCQ({ id:'g9eng-grv-100', chapterId:'g9eng-gr-verbs', subsection:'future_perfect_continuous', difficulty:3,
    question:'"By nine tomorrow morning, the bakers will have been making bread for five hours." What does the future perfect continuous add here?',
    options:['It shows the baking is a continuous process ending at nine tomorrow.','It shows the baking happened only once.','It shows the baking finished yesterday.','It shows the baking has not started yet.'],
    answer:'It shows the baking is a continuous process ending at nine tomorrow.',
    hint:'Five hours of sustained work — the continuous form shows the process, not just the result.',
    explanation:'<b>Will have been making</b> pictures a five-hour stretch of continuous work. It stresses the activity itself rather than just the loaves produced — the main function of the future perfect continuous.' }),

  // ── tense_consistency (g9eng-grv-101 – g9eng-grv-120) ──────────────────

  makeMCQ({ id:'g9eng-grv-101', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:1,
    question:'Which sentence keeps its tenses consistent?',
    options:['The scientist measured the temperature and recorded the result.','The scientist measured the temperature and records the result.','The scientist measures the temperature and recorded the result.','The scientist will measure the temperature and recorded the result.'],
    answer:'The scientist measured the temperature and recorded the result.',
    hint:'Both actions happen at the same time in the past.',
    explanation:'Both verbs — <b>measured</b> and <b>recorded</b> — are in the simple past, so the tenses are consistent. Mixing past and present creates an unnatural jump in time.' }),

  makeMCQ({ id:'g9eng-grv-102', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'Spot the tense inconsistency: "The wind had picked up speed and the sky turns dark."',
    options:['"turns" should be "turned"','"had" should be "has"','"picked" should be "picks"','There is no inconsistency.'],
    answer:'"turns" should be "turned"',
    hint:'"Had picked up" sets the scene in the past — what tense should the second verb match?',
    explanation:'"Had picked up" is past perfect; the parallel action must be in the past too: <b>turned</b>. "Turns" pulls the sentence into the present without reason.' }),

  makeMCQ({ id:'g9eng-grv-103', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'A student writes a past-tense story and then writes: "Suddenly the door opens and a man walks in." What should this sentence read?',
    options:['Suddenly the door opened and a man walked in.','Suddenly the door had opened and a man walks in.','Suddenly the door opens and a man will walk in.','No change — both tenses are acceptable here.'],
    answer:'Suddenly the door opened and a man walked in.',
    hint:'The story is in the past tense — every narrative event must match.',
    explanation:'Once a past-tense narrative is established, new events stay in the <b>simple past</b>: <i>opened</i> and <i>walked</i>. Slipping into the present breaks the tense frame.' }),

  makeMCQ({ id:'g9eng-grv-104', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'Which paragraph is written in a consistent tense throughout?',
    options:['The fisherman woke early. He packed his nets and rowed out to sea.','The fisherman woke early. He packs his nets and rowed out to sea.','The fisherman wakes early. He packed his nets and rowed out to sea.','The fisherman woke early. He will pack his nets and rowed out to sea.'],
    answer:'The fisherman woke early. He packed his nets and rowed out to sea.',
    hint:'Every verb in the passage should be in the same tense.',
    explanation:'<b>Woke</b>, <b>packed</b> and <b>rowed</b> are all simple past, making the sequence consistent. The other options each mix a different tense into the past-tense frame.' }),

  makeMCQ({ id:'g9eng-grv-105', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:3,
    question:'In a formal essay about climate change, a student alternates between "is" and "was" for the same ongoing situation. What rule have they broken?',
    options:['Tense consistency — a stable situation should stay in one tense.','Subject-verb agreement — "is" and "was" cannot share a paragraph.','Register — formal essays ban "is" entirely.','No rule — "is" and "was" are always interchangeable.'],
    answer:'Tense consistency — a stable situation should stay in one tense.',
    hint:'If climate change is still ongoing, which tense should be used throughout?',
    explanation:'An ongoing situation needs a consistent tense. Switching between "is" and "was" implies the situation has ended and returned. <b>Tense consistency</b> means one tense for one stable situation.' }),

  makeMCQ({ id:'g9eng-grv-106', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'Choose the version that corrects the tense inconsistency: "He studied hard, so he passes the exam."',
    options:['He studied hard, so he passed the exam.','He studies hard, so he passes the exam.','He had studied hard, so he passes the exam.','He studied hard, so he is passing the exam.'],
    answer:'He studied hard, so he passed the exam.',
    hint:'"Studied" is simple past — the result should match.',
    explanation:'"Studied" sets the past tense; <b>passed</b> maintains it. A past cause cannot logically lead to a present-tense result in a narrative sequence.' }),

  makeMCQ({ id:'g9eng-grv-107', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'Identify the sentence that has a tense shift error.',
    options:['She was reading when the lights go out.','She was reading when the lights went out.','She read and then she went to bed.','She had finished before he arrived.'],
    answer:'She was reading when the lights go out.',
    hint:'"Was reading" is past continuous — the interrupting event should be past too.',
    explanation:'"Was reading" establishes a past background; the interruption must be past: <b>went out</b>. "Go out" switches to the present tense without reason.' }),

  makeMCQ({ id:'g9eng-grv-108', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'A history essay reads: "Napoleon invaded Russia in 1812. The campaign was disastrous and many soldiers die." Correct the error.',
    options:['…many soldiers died.','…many soldiers are dying.','…many soldiers will die.','There is no error.'],
    answer:'…many soldiers died.',
    hint:'The essay uses simple past throughout — the last verb must match.',
    explanation:'Historical narrative uses the <b>simple past</b>. "Die" switches to the present; <b>died</b> restores consistency.' }),

  makeMCQ({ id:'g9eng-grv-109', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'Which sentence avoids a tense inconsistency?',
    options:['The coach blew the whistle and the players stopped immediately.','The coach blew the whistle and the players stop immediately.','The coach blows the whistle and the players stopped immediately.','The coach had blown the whistle and the players stop immediately.'],
    answer:'The coach blew the whistle and the players stopped immediately.',
    hint:'Both actions happen at the same moment in the past.',
    explanation:'<b>Blew</b> and <b>stopped</b> are both simple past, placing both actions in the same moment without ambiguity.' }),

  makeMCQ({ id:'g9eng-grv-110', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:1,
    question:'Why is tense consistency important in written English?',
    options:['It tells the reader clearly when events happen relative to each other.','It makes sentences shorter and easier to punctuate.','It limits the writer to one verb per sentence.','It is only important in formal letters, not in stories.'],
    answer:'It tells the reader clearly when events happen relative to each other.',
    hint:'Think about what a reader does with tense information.',
    explanation:'Tense signals time. Keeping the tense consistent means the reader always knows <b>when</b> events occur — past, present or future — without confusion from unexpected switches.' }),

  makeMCQ({ id:'g9eng-grv-111', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'A student switches from simple past to present tense in the middle of a narrative. What is the likely effect on the reader?',
    options:['Confusion about when events are happening','A clearer sense of the events\' sequence','A more formal tone throughout','A stronger ending to the story'],
    answer:'Confusion about when events are happening',
    hint:'Tense tells the reader where to place events in time.',
    explanation:'An unexplained tense shift disrupts the reader\'s sense of the timeline, causing <b>confusion</b>. Deliberate shifts are possible but must be handled with clear intent.' }),

  makeMCQ({ id:'g9eng-grv-112', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:3,
    question:'Correct the tense inconsistency: "By the time we reached the station, the train leaves."',
    options:['By the time we reached the station, the train had left.','By the time we reached the station, the train leaves.','By the time we reach the station, the train had left.','By the time we reached the station, the train will leave.'],
    answer:'By the time we reached the station, the train had left.',
    hint:'"By the time we reached" sets a past moment — what comes before that in the past?',
    explanation:'When one past action precedes another, the earlier one uses the <b>past perfect</b>: <b>had left</b>. "Leaves" is present tense and breaks the past frame entirely.' }),

  makeMCQ({ id:'g9eng-grv-113', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:3,
    question:'Which rule should guide the tense of verbs in a science report describing an experiment completed last week?',
    options:['Use the simple past for methods and results.','Use the present tense throughout.','Mix past and present freely.','Use the future tense for results.'],
    answer:'Use the simple past for methods and results.',
    hint:'The experiment is already over — which tense fits completed actions?',
    explanation:'Completed experiments are reported in the <b>simple past</b>: "we heated the solution", "the temperature rose". Conclusions may shift to the present ("This shows…"), but the narrative of what was done stays past.' }),

  makeMCQ({ id:'g9eng-grv-114', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'Find the tense error: "Last Tuesday, she visits her grandmother and cooked dinner."',
    options:['"visits" should be "visited"','"cooked" should be "cooks"','"Last Tuesday" should be removed','There is no tense error.'],
    answer:'"visits" should be "visited"',
    hint:'"Last Tuesday" signals the past — both verbs must follow.',
    explanation:'"Cooked" is correctly past, but "visits" drifts to the present. Changing it to <b>visited</b> makes both verbs consistent with "Last Tuesday".' }),

  makeMCQ({ id:'g9eng-grv-115', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'The narrator is writing in the present tense. Which version is tense-consistent?',
    options:['She opens the letter and reads it slowly.','She opened the letter and reads it slowly.','She opens the letter and read it slowly.','She opens the letter and will read it slowly.'],
    answer:'She opens the letter and reads it slowly.',
    hint:'If the narrative frame is present tense, every verb should be present.',
    explanation:'When the narrative uses the present tense, all verbs must be present too: <b>opens</b> and <b>reads</b>. Mixing in past or future breaks the frame.' }),

  makeMCQ({ id:'g9eng-grv-116', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'A student is told their essay has a "tense shift" problem. What does this mean?',
    options:['The essay moves between tenses without a clear reason.','The essay is written entirely in the wrong tense.','The essay has too many verbs.','The essay uses the future tense when the past would be better.'],
    answer:'The essay moves between tenses without a clear reason.',
    hint:'"Shift" means a movement or change.',
    explanation:'A tense shift is an unexplained movement from one tense to another in the middle of a text. It confuses the reader and signals a lack of control over the writing.' }),

  makeMCQ({ id:'g9eng-grv-117', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'Pick the sentence that corrects the tense error: "After the rain stopped, the children run outside and play."',
    options:['After the rain stopped, the children ran outside and played.','After the rain stopped, the children run outside and played.','After the rain stops, the children ran outside and played.','After the rain stops, the children run outside and play.'],
    answer:'After the rain stopped, the children ran outside and played.',
    hint:'"Stopped" is simple past — all the following verbs should match.',
    explanation:'"Ran" and "played" are both simple past, consistent with "stopped". "Run" and "play" are present and create a tense break with the past-tense beginning.' }),

  makeMCQ({ id:'g9eng-grv-118', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:2,
    question:'Identify the correct version of a news report about an event that happened yesterday.',
    options:['The parade began at noon. Thousands of people lined the streets and cheered.','The parade begins at noon. Thousands of people lined the streets and cheered.','The parade began at noon. Thousands of people line the streets and cheered.','The parade began at noon. Thousands of people lined the streets and will cheer.'],
    answer:'The parade began at noon. Thousands of people lined the streets and cheered.',
    hint:'A past event uses the simple past throughout.',
    explanation:'All three verbs — <b>began</b>, <b>lined</b>, <b>cheered</b> — are simple past, making the report consistent. Any present or future verb breaks the "yesterday" time frame.' }),

  makeMCQ({ id:'g9eng-grv-119', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:4,
    question:'A writer begins in the simple past and shifts to the present for dramatic effect. Which example does this deliberately and correctly?',
    options:['He reached the summit. Suddenly, everything changes — the cloud lifts and the valley appears below.','He reached the summit. Suddenly, everything had changed.','He reached the summit. Suddenly, everything will change.','He reached the summit. Suddenly, everything changed.'],
    answer:'He reached the summit. Suddenly, everything changes — the cloud lifts and the valley appears below.',
    hint:'The historical present uses the present tense for vividness at a key moment — it is deliberate, not an error.',
    explanation:'Writers sometimes shift to the present at a dramatic moment — this is the <b>historical present</b>. The pattern "Suddenly…" signals intent. The plain past ("everything changed") is consistent but less vivid; the future and past-perfect versions are ungrammatical here.' }),

  makeMCQ({ id:'g9eng-grv-120', chapterId:'g9eng-gr-verbs', subsection:'tense_consistency', difficulty:3,
    question:'Which best describes "maintaining tense consistency across a whole text"?',
    options:['Choosing one time frame and keeping all verbs in that frame unless there is a clear reason to shift.','Using the present tense in every sentence regardless of the subject.','Alternating between past and present to keep the reader interested.','Avoiding all forms of the verb "to be" throughout the text.'],
    answer:'Choosing one time frame and keeping all verbs in that frame unless there is a clear reason to shift.',
    hint:'Consistency allows exceptions — but those exceptions need to be deliberate.',
    explanation:'Tense consistency means anchoring the text in <b>one time frame</b> and only departing from it when there is a clear purpose. Random shifts without reason undermine the writing.' })

);
})();
