'use strict';
(function () {
STATIC_QUESTIONS.push(

  // ── Nouns · Apposition (g9eng-gr-nouns) · 10 questions ──────────────────

  makeMCQ({ id:'g9eng-grv-001', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:1,
    question:'Identify the <b>appositive</b> in the sentence:<br><i>"Gandhi, a great leader, changed history."</i>',
    options:['a great leader','Gandhi','changed history','a great'], answer:'a great leader',
    hint:'An appositive renames the noun that comes just before it.',
    explanation:'"<b>a great leader</b>" renames Gandhi and sits between commas. Remove it and the sentence still makes sense, which is the test of an appositive.' }),

  makeMCQ({ id:'g9eng-grv-002', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:2,
    question:'Which sentence uses an <b>appositive</b> with correct punctuation?',
    options:['Dr Lam, our headteacher, addressed the hall.','Dr Lam our headteacher, addressed the hall.','Dr Lam, our headteacher addressed the hall.','Dr Lam our headteacher addressed the hall.'],
    answer:'Dr Lam, our headteacher, addressed the hall.',
    hint:'An appositive phrase needs a comma at its beginning and at its end.',
    explanation:'"our headteacher" renames Dr Lam, so it needs a comma <b>on both sides</b>. Using only one comma leaves the boundary unclear.' }),

  makeMCQ({ id:'g9eng-grv-003', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:2,
    question:'What is the appositive in: <i>"Mauritius, a small island nation, has a rich cultural heritage."</i>?',
    options:['a small island nation','Mauritius','has a rich cultural heritage','cultural heritage'],
    answer:'a small island nation',
    hint:'Which phrase renames the subject and could be removed without breaking the sentence?',
    explanation:'"<b>a small island nation</b>" renames Mauritius. An appositive is always a noun or noun phrase placed beside another noun to identify or describe it.' }),

  makeMCQ({ id:'g9eng-grv-004', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:1,
    question:'An appositive is best described as:',
    options:['A noun phrase that renames another noun beside it','An adjective that describes a verb','A clause that explains why something happened','A pronoun that replaces the subject'],
    answer:'A noun phrase that renames another noun beside it',
    hint:'Think about what "appositive" does to the noun next to it.',
    explanation:'An appositive is a <b>noun or noun phrase placed beside another noun to rename or identify it</b>. It gives extra information about that noun.' }),

  makeMCQ({ id:'g9eng-grv-005', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:2,
    question:'Spot the <b>error</b> in: <i>"My sister, a doctor works at the hospital."</i>',
    options:['A closing comma is missing after "doctor"','The opening comma before "a" should be removed','The word "doctor" should be capitalised','There is no error in the sentence'],
    answer:'A closing comma is missing after "doctor"',
    hint:'If you open a pair of commas around an appositive, you must close it too.',
    explanation:'"a doctor" is an appositive and needs commas on <b>both sides</b>. The sentence opens one comma but never closes it, leaving the boundary of the phrase open.' }),

  makeMCQ({ id:'g9eng-grv-006', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:3,
    question:'Which sentence correctly inserts <i>"the longest river in Africa"</i> as an appositive for <i>the Nile</i>?',
    options:['The Nile, the longest river in Africa, flows north.','The Nile the longest river in Africa flows north.','The Nile, the longest river in Africa flows north.','The Nile the, longest river in Africa, flows north.'],
    answer:'The Nile, the longest river in Africa, flows north.',
    hint:'The appositive sits between the noun and the main verb, separated by paired commas.',
    explanation:'The phrase "the longest river in Africa" renames the Nile, so it is enclosed in commas: one after "Nile" and one after "Africa". Both are needed.' }),

  makeMCQ({ id:'g9eng-grv-007', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:2,
    question:'In <i>"My favourite author, J. K. Rowling, wrote the Harry Potter series,"</i> what role does <b>J. K. Rowling</b> play?',
    options:['Appositive — it renames "My favourite author"','Subject — it performs the action','Object — it receives the action','Adverbial — it tells us when'],
    answer:'Appositive — it renames "My favourite author"',
    hint:'Does it do something, receive something, or just tell you more about the noun before it?',
    explanation:'"J. K. Rowling" renames "My favourite author" and is therefore an <b>appositive</b>. The actual subject of the verb is the whole noun phrase including the appositive.' }),

  makeMCQ({ id:'g9eng-grv-008', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:3,
    question:'Which of these does <b>NOT</b> contain an appositive?',
    options:['She left early because the meeting was dull.','Nelson Mandela, South Africa\'s first elected president, died in 2013.','Shakespeare, a playwright and poet, wrote thirty-seven plays.','My dog, a golden retriever, loves to swim.'],
    answer:'She left early because the meeting was dull.',
    hint:'In three of the sentences, a noun phrase sits in commas beside another noun and renames it. Which sentence has no such pair?',
    explanation:'The first sentence has a reason clause ("because…"), not an appositive. The other three each have a noun phrase between commas that renames the subject.' }),

  makeMCQ({ id:'g9eng-grv-009', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:2,
    question:'What is the main purpose of an appositive in a sentence?',
    options:['To identify or give extra information about the noun beside it','To describe how an action is performed','To connect two clauses of equal weight','To show who receives the action of the verb'],
    answer:'To identify or give extra information about the noun beside it',
    hint:'Think about what extra detail the appositive adds and where it sits.',
    explanation:'An appositive <b>identifies or adds information</b> about the noun beside it without starting a new clause. It is always a noun phrase, never a verb form.' }),

  makeMCQ({ id:'g9eng-grv-010', chapterId:'g9eng-gr-nouns', subsection:'apposition', difficulty:3,
    question:'A student writes: <i>"Our coach Mr Persand, led the team to victory."</i> What is wrong?',
    options:['The comma after "Persand" should not be there if no comma precedes "Mr"','The name "Mr Persand" needs to be removed entirely','The verb should be "leads" not "led"','There is no error'],
    answer:'The comma after "Persand" should not be there if no comma precedes "Mr"',
    hint:'Either both commas are present or neither is — a single comma beside an appositive is wrong.',
    explanation:'"Mr Persand" is an appositive for "Our coach". It should either have <b>no commas</b> (when tightly identifying the person) or <b>both commas</b> (one before "Mr" and one after "Persand"). One comma alone misplaces the boundary.' }),

  // ── Pronouns · Reflexive (g9eng-gr-pronouns) · 15 questions ─────────────

  makeMCQ({ id:'g9eng-grv-011', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:1,
    question:'Complete the sentence: <i>"He hurt .......... during the match."</i>',
    options:['himself','him','his','he'], answer:'himself',
    hint:'The subject and the object refer to the same person.',
    explanation:'When the action returns to the subject, a <b>reflexive pronoun</b> is used. The subject is "He", so the reflexive is <b>himself</b>.' }),

  makeMCQ({ id:'g9eng-grv-012', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:1,
    question:'Complete the sentence: <i>"She made .......... a cup of tea."</i>',
    options:['herself','her','hers','she'], answer:'herself',
    hint:'The person making the tea is the same person who will drink it.',
    explanation:'The subject "She" acts upon herself, so the reflexive pronoun <b>herself</b> is needed. "Her" would suggest a different person.' }),

  makeMCQ({ id:'g9eng-grv-013', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:2,
    question:'Complete the sentence: <i>"The students organised .......... into groups."</i>',
    options:['themselves','them','their','they'], answer:'themselves',
    hint:'The students are doing something to themselves as a group.',
    explanation:'The plural subject "students" acts on itself, so the reflexive is <b>themselves</b>. "Them" would refer to a different group of people.' }),

  makeMCQ({ id:'g9eng-grv-014', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:1,
    question:'Complete the sentence: <i>"I blamed .......... for the mistake."</i>',
    options:['myself','me','my','mine'], answer:'myself',
    hint:'The speaker is directing the blame back at themselves.',
    explanation:'When the subject "I" acts on itself, the reflexive pronoun is <b>myself</b>. "Me" is an object pronoun used when referring to a different receiver.' }),

  makeMCQ({ id:'g9eng-grv-015', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:2,
    question:'Which sentence uses a reflexive pronoun <b>correctly</b>?',
    options:['Please help yourself to some food.','Please help yourselfs to some food.','Please help youself to some food.','Please help himself to some food.'],
    answer:'Please help yourself to some food.',
    hint:'The subject of "help" is "you", so the reflexive must match "you" in the singular.',
    explanation:'"Help yourself" means one person is helping themselves. <b>Yourself</b> is the correct reflexive for "you" singular. "Yourselfs" is not a word; "themselves" would be for "they".' }),

  makeMCQ({ id:'g9eng-grv-016', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:2,
    question:'Complete the sentence: <i>"The cat cleaned .......... after its meal."</i>',
    options:['itself','it','its','themselves'], answer:'itself',
    hint:'The subject is singular and refers to an animal.',
    explanation:'For a singular non-person subject, the reflexive pronoun is <b>itself</b>. Using "it" would sound as though the cat cleaned a different object.' }),

  makeMCQ({ id:'g9eng-grv-017', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:2,
    question:'Complete the sentence: <i>"We enjoyed .......... at the beach."</i>',
    options:['ourselves','us','ours','we'], answer:'ourselves',
    hint:'The subject is "we" — the action circles back to the whole group.',
    explanation:'The reflexive of "we" is <b>ourselves</b>. It shows the group is the recipient of its own enjoyment.' }),

  makeMCQ({ id:'g9eng-grv-018', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:2,
    question:'Which reflexive pronoun correctly completes: <i>"You and your partner should introduce .......... to the class."</i>?',
    options:['yourselves','yourself','themselves','ourselves'], answer:'yourselves',
    hint:'More than one person is being addressed.',
    explanation:'"You and your partner" is plural, so the reflexive is <b>yourselves</b>. "Yourself" is for one person; "themselves" would refer to a third party.' }),

  makeMCQ({ id:'g9eng-grv-019', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:3,
    question:'Identify the error: <i>"The manager chose him to lead the project himself."</i>',
    options:['There is no error — "himself" emphasises "him"','The word "himself" should be "he"','The word "him" should be "himself"','The sentence needs a comma before "himself"'],
    answer:'There is no error — "himself" emphasises "him"',
    hint:'Read carefully: is "himself" acting as a reflexive or as an emphasising pronoun?',
    explanation:'"Himself" here emphasises "the manager" (the manager did the choosing in person), so the sentence is correct. The reflexive and the emphasising pronoun share the same form — context decides which job is being done.' }),

  makeMCQ({ id:'g9eng-grv-020', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:2,
    question:'Choose the sentence that uses a reflexive pronoun <b>incorrectly</b>.',
    options:['She looked at herself in the mirror.','They did the work themselves.','Please contact myself if you have questions.','He poured himself a glass of water.'],
    answer:'Please contact myself if you have questions.',
    hint:'"Myself" is only correct when "I" is also in the same clause.',
    explanation:'"Myself" needs its antecedent "I" in the same clause. Saying "contact myself" when the subject is "you" is a common error — the correct form is simply "contact <b>me</b>".' }),

  makeMCQ({ id:'g9eng-grv-021', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:3,
    question:'Which sentence contains a <b>reflexive pronoun error</b>?',
    options:['The report was written by herself alone.','She wrote the report herself.','She injured herself during training.','The award was given to herself and her partner.'],
    answer:'The report was written by herself alone.',
    hint:'Can "herself" follow the preposition "by" on its own, without a subject in the clause?',
    explanation:'"Herself" and "himself" cannot serve as the object of a preposition when no subject pronoun anchors them in the clause. The correct form is "<b>her</b> alone" or "by her alone".' }),

  makeMCQ({ id:'g9eng-grv-022', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:2,
    question:'Complete the sentence with the correct reflexive pronoun: <i>"The team congratulated .......... on the win."</i>',
    options:['itself','themselves','himself','herself'], answer:'themselves',
    hint:'"The team" refers to its members as a group acting together.',
    explanation:'When a collective noun such as "team" refers to its individual members acting together, the plural reflexive <b>themselves</b> is used.' }),

  makeMCQ({ id:'g9eng-grv-023', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:3,
    question:'In <i>"She herself admitted the mistake,"</i> what is the function of <b>herself</b>?',
    options:['It emphasises "she" and can be removed','It is a reflexive and is essential to meaning','It replaces "she" and is the subject','It refers to a different person from "she"'],
    answer:'It emphasises "she" and can be removed',
    hint:'Try removing it. Does the sentence still work?',
    explanation:'"She herself admitted the mistake" → "She admitted the mistake" still works. That removability is the mark of an <b>emphasising</b> pronoun, not a reflexive one.' }),

  makeMCQ({ id:'g9eng-grv-024', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:2,
    question:'Choose the correct pronoun: <i>"After the long journey, the travellers treated .......... to a meal."</i>',
    options:['themselves','them','their','they'], answer:'themselves',
    hint:'The travellers did something kind for themselves.',
    explanation:'"The travellers" acted on themselves, so the reflexive <b>themselves</b> is correct. "Them" would imply someone else treated the travellers.' }),

  makeMCQ({ id:'g9eng-grv-025', chapterId:'g9eng-gr-pronouns', subsection:'reflexive', difficulty:3,
    question:'Which sentence uses a reflexive pronoun <b>correctly and necessarily</b>?',
    options:['She cut herself while cooking.','The director himself approved the budget.','He built the wall himself.','I myself was not there.'],
    answer:'She cut herself while cooking.',
    hint:'In which sentence would removing the pronoun change or break the meaning?',
    explanation:'In "She cut herself", "herself" is the object of the verb and cannot be removed — it tells us who was cut. In the other three, the pronoun is emphasising and optional.' }),

  // ── Pronouns · Emphasising (g9eng-gr-pronouns) · 15 questions ───────────

  makeMCQ({ id:'g9eng-grv-026', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'Which sentence contains an <b>emphasising pronoun</b>?',
    options:['The president himself signed the treaty.','The president hurt himself at the summit.','The president spoke to himself in the mirror.','The president blamed himself for the outcome.'],
    answer:'The president himself signed the treaty.',
    hint:'An emphasising pronoun can be removed without breaking the sentence.',
    explanation:'In "The president himself signed", "himself" adds emphasis and can be dropped: "The president signed the treaty." In the other sentences, removing the pronoun leaves the verb without an object.' }),

  makeMCQ({ id:'g9eng-grv-027', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'What is the key difference between an <b>emphasising</b> and a <b>reflexive</b> pronoun?',
    options:['An emphasising pronoun can be removed; a reflexive cannot','A reflexive pronoun can be removed; an emphasising cannot','They are the same; only the position changes','Emphasising pronouns only go with plural subjects'],
    answer:'An emphasising pronoun can be removed; a reflexive cannot',
    hint:'Try removing the pronoun in each case and see whether the sentence still holds.',
    explanation:'When the pronoun is <b>emphasising</b>, removing it leaves the sentence grammatical. When it is <b>reflexive</b>, it is the object of the verb and removing it breaks the sentence.' }),

  makeMCQ({ id:'g9eng-grv-028', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:1,
    question:'What does an <b>emphasising pronoun</b> do?',
    options:['It stresses that the named person did the action personally','It shows the subject acts on itself','It replaces a noun already mentioned','It asks a question about the subject'],
    answer:'It stresses that the named person did the action personally',
    hint:'Think about what changes when you add "himself" after a name.',
    explanation:'An emphasising pronoun draws attention to the fact that a particular person — and no one else — did something. It adds stress, not new information.' }),

  makeMCQ({ id:'g9eng-grv-029', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'In <i>"She made the cake herself,"</i> what is the role of <b>herself</b>?',
    options:['Emphasising — she made it personally, without help','Reflexive — she is both the maker and the recipient','Relative — it links two clauses','Demonstrative — it points to the cake'],
    answer:'Emphasising — she made it personally, without help',
    hint:'Can you remove "herself" and still have a complete sentence?',
    explanation:'"She made the cake" is complete without "herself". The pronoun adds the idea that she — not anyone else — made it. That extra stress is the mark of an <b>emphasising</b> pronoun.' }),

  makeMCQ({ id:'g9eng-grv-030', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'Choose the sentence where <b>herself</b> is used as an <b>emphasising</b> pronoun.',
    options:['She painted the mural herself.','She painted herself for the show.','She injured herself in training.','She cut herself by accident.'],
    answer:'She painted the mural herself.',
    hint:'In which sentence can "herself" be removed and the sentence still makes sense?',
    explanation:'"She painted the mural" stands alone — "herself" only stresses that she did it personally. In the other sentences, "herself" is the object and removing it changes or breaks the meaning.' }),

  makeMCQ({ id:'g9eng-grv-031', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:3,
    question:'A student writes: <i>"The minister himself is blamed himself for the failure."</i> What is the error?',
    options:['Two pronouns with different functions are used — only one is needed here','The subject should be "the ministers"','Both uses of "himself" are correct','Neither use of "himself" is correct'],
    answer:'Two pronouns with different functions are used — only one is needed here',
    hint:'One "himself" emphasises; the other is reflexive. Can they both appear?',
    explanation:'The sentence uses "himself" as an emphasising pronoun AND as a reflexive object in the same clause, which doubles up awkwardly. Either "The minister himself is blamed" or "The minister blames himself" — not both.' }),

  makeMCQ({ id:'g9eng-grv-032', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'Complete with an <b>emphasising pronoun</b>: <i>"The students .......... cleaned the classroom without being asked."</i>',
    options:['themselves','them','theirs','they'], answer:'themselves',
    hint:'The pronoun stresses the students did this — no teacher was needed.',
    explanation:'<b>Themselves</b> emphasises that the students (and no one else) did the cleaning. It can be removed: "The students cleaned the classroom" remains correct.' }),

  makeMCQ({ id:'g9eng-grv-033', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:3,
    question:'Which two positions can an emphasising pronoun occupy?',
    options:['Immediately after the noun it emphasises, or at the end of the clause','Before the subject, or before the verb','Between two objects, or before the object','Only after a linking verb'],
    answer:'Immediately after the noun it emphasises, or at the end of the clause',
    hint:'Compare "He himself fixed the problem" with "He fixed the problem himself."',
    explanation:'An emphasising pronoun can follow its noun (<i>"He himself fixed it"</i>) or move to the end of the clause (<i>"He fixed it himself"</i>) — both positions are correct and both carry emphasis.' }),

  makeMCQ({ id:'g9eng-grv-034', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'Add an <b>emphasising pronoun</b>: <i>"I assembled the furniture .......... ."</i>',
    options:['myself','me','mine','I'], answer:'myself',
    hint:'The subject "I" needs its corresponding emphatic form.',
    explanation:'The emphasising form of "I" is <b>myself</b>, placed at the end of the clause to stress that no one helped. Remove it and the statement is still complete.' }),

  makeMCQ({ id:'g9eng-grv-035', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:3,
    question:'In <i>"The children themselves set up the exhibition,"</i> classify <b>themselves</b>.',
    options:['Emphasising pronoun','Reflexive pronoun','Relative pronoun','Demonstrative pronoun'],
    answer:'Emphasising pronoun',
    hint:'Can the sentence survive without "themselves"?',
    explanation:'"The children set up the exhibition" is complete. "Themselves" only adds emphasis — stressing that the children, not their teachers, did the work — so it is an <b>emphasising</b> pronoun.' }),

  makeMCQ({ id:'g9eng-grv-036', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'Which sentence uses <b>himself</b> as an emphasising pronoun?',
    options:['The chef himself tasted every dish.','The chef burned himself on the stove.','The chef helped himself to the leftovers.','The chef talked to himself in the kitchen.'],
    answer:'The chef himself tasted every dish.',
    hint:'Remove "himself" — which sentence stays grammatical?',
    explanation:'"The chef tasted every dish" works fine. "Himself" only stresses personal involvement, making it <b>emphasising</b>. In the others "himself" is the object of "burned", "helped" or "talked to" and cannot be dropped.' }),

  makeMCQ({ id:'g9eng-grv-037', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:3,
    question:'Identify the error: <i>"The principal himself, he delivered the speech."</i>',
    options:['The pronoun "he" is redundant alongside "The principal himself"','The word "himself" should be "herself"','"Himself" cannot follow "principal"','There is no error'],
    answer:'The pronoun "he" is redundant alongside "The principal himself"',
    hint:'The subject is already stated twice — once as a noun and once as a pronoun.',
    explanation:'When "himself" follows a noun, adding a second subject pronoun ("he") creates a double subject. The correct form is either "The principal himself delivered…" or "He himself delivered…" — not both.' }),

  makeMCQ({ id:'g9eng-grv-038', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'Which sentence uses an emphasising pronoun <b>correctly</b>?',
    options:['The director herself reviewed every scene.','The director hurt herself on set.','She poured herself a drink.','She locked herself out.'],
    answer:'The director herself reviewed every scene.',
    hint:'Look for the sentence where the pronoun stresses personal involvement and can be cut.',
    explanation:'"The director reviewed every scene" stands alone; "herself" adds nothing but emphasis. In the other options, the pronoun is the object of the verb — it is reflexive and required.' }),

  makeMCQ({ id:'g9eng-grv-039', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:3,
    question:'A student removes <b>ourselves</b> from: <i>"We built the community garden ourselves."</i> What changes?',
    options:['The sentence is still grammatical but the personal effort is no longer stressed','The sentence becomes ungrammatical','The meaning reverses completely','The subject changes from "we" to "they"'],
    answer:'The sentence is still grammatical but the personal effort is no longer stressed',
    hint:'Test it: "We built the community garden." Is it grammatical?',
    explanation:'"We built the community garden" is perfectly grammatical. Removing "ourselves" loses only the <b>emphasis</b> that the group — and no one else — did the work. This removability is the definition of an emphasising pronoun.' }),

  makeMCQ({ id:'g9eng-grv-040', chapterId:'g9eng-gr-pronouns', subsection:'emphasising', difficulty:2,
    question:'Complete with the correct emphasising pronoun: <i>"You .......... chose the topic; no one suggested it."</i>',
    options:['yourself','yourselves','you','yours'], answer:'yourself',
    hint:'One person is being addressed — use the singular form.',
    explanation:'One person is spoken to ("You"), so the emphasising form is <b>yourself</b>. "Yourselves" would be used for more than one person.' }),

  // ── Pronouns · Relative (g9eng-gr-pronouns) · 15 questions ──────────────

  makeMCQ({ id:'g9eng-grv-041', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:1,
    question:'Choose the correct relative pronoun: <i>"The woman .......... won the prize was very surprised."</i>',
    options:['who','which','whose','where'], answer:'who',
    hint:'The pronoun refers to a person and acts as the subject of its clause.',
    explanation:'<b>Who</b> is used for people when the pronoun is the subject of the relative clause. "Which" is for things, and "whose" shows possession.' }),

  makeMCQ({ id:'g9eng-grv-042', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:1,
    question:'Choose the correct relative pronoun: <i>"This is the book .......... changed my life."</i>',
    options:['which','who','whom','whose'], answer:'which',
    hint:'The pronoun refers to a thing, not a person.',
    explanation:'<b>Which</b> is used for things (and sometimes animals). "Who" and "whom" are reserved for people.' }),

  makeMCQ({ id:'g9eng-grv-043', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:2,
    question:'Choose the correct relative pronoun: <i>"The student .......... essay won first prize was from Grade 9."</i>',
    options:['whose','who','which','that'], answer:'whose',
    hint:'The relative pronoun shows possession — the essay belongs to the student.',
    explanation:'<b>Whose</b> indicates possession and is used for both people and things. Here it links "student" to the essay that belongs to them.' }),

  makeMCQ({ id:'g9eng-grv-044', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:2,
    question:'Choose the correct relative pronoun: <i>"She is the scientist .......... the committee awarded the prize."</i>',
    options:['whom','who','whose','which'], answer:'whom',
    hint:'The relative pronoun is the object of "awarded" — the committee awarded the prize to her.',
    explanation:'<b>Whom</b> is the object form of "who". Since the committee (subject) awarded the prize to the scientist (object), the pronoun that replaces the object is <b>whom</b>.' }),

  makeMCQ({ id:'g9eng-grv-045', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:2,
    question:'Choose the correct relative pronoun: <i>"That is the village .......... my grandmother was born."</i>',
    options:['where','which','who','whose'], answer:'where',
    hint:'The relative clause refers to a place.',
    explanation:'<b>Where</b> is used as a relative pronoun to introduce a clause about a place. "Which" could also work ("in which"), but "where" is the simpler option here.' }),

  makeMCQ({ id:'g9eng-grv-046', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:2,
    question:'Choose the correct relative pronoun: <i>"I remember the day .......... the cyclone struck."</i>',
    options:['when','where','which','whose'], answer:'when',
    hint:'The relative clause refers to a time.',
    explanation:'<b>When</b> is used as a relative pronoun after a noun of time such as "day", "year" or "moment".' }),

  makeMCQ({ id:'g9eng-grv-047', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:2,
    question:'In a <b>defining relative clause</b>, which pronoun can replace <b>which</b> or <b>who</b>?',
    options:['that','whom','whose','where'], answer:'that',
    hint:'"That" is a neutral relative pronoun acceptable for both people and things in defining clauses.',
    explanation:'In defining relative clauses, <b>that</b> can replace "which" (things) or "who" (people): "the book that I read", "the man that I met". It cannot be used in non-defining clauses.' }),

  makeMCQ({ id:'g9eng-grv-048', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:3,
    question:'Choose the correct relative pronoun: <i>"The scientist .......... work inspired the team has just retired."</i>',
    options:['whose','who','whom','that'], answer:'whose',
    hint:'Decide what the relative pronoun is replacing: is it the subject, the object or a possessive?',
    explanation:'"Work" belongs to the scientist, so a possessive relative pronoun is needed. <b>Whose</b> is the only possessive relative pronoun in English.' }),

  makeMCQ({ id:'g9eng-grv-049', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:3,
    question:'Which sentence contains a <b>non-defining</b> relative clause?',
    options:['My neighbour, who grows vegetables, won the prize.','The student who works hardest will succeed.','The car that is red belongs to him.','I like books that have pictures.'],
    answer:'My neighbour, who grows vegetables, won the prize.',
    hint:'A non-defining clause adds extra information and is set off by commas.',
    explanation:'The clause "who grows vegetables" is enclosed in commas because it adds optional extra information — remove it and you still know which neighbour is meant. The other clauses identify which thing or person is meant, making them defining.' }),

  makeMCQ({ id:'g9eng-grv-050', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:2,
    question:'Choose the correct relative pronoun: <i>"The report, .......... was presented on Monday, covered three topics."</i>',
    options:['which','who','whom','whose'], answer:'which',
    hint:'The relative clause adds extra information about a thing, not a person.',
    explanation:'The clause gives extra information about a report (a thing), so <b>which</b> is correct. The commas confirm this is a non-defining clause.' }),

  makeMCQ({ id:'g9eng-grv-051', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:3,
    question:'Identify the error: <i>"The man which I spoke to was very helpful."</i>',
    options:['Which should be whom, because the pronoun refers to a person who is the object','Which should be who, because the pronoun refers to a person','Which is correct as the object of the verb','Which should be whose'],
    answer:'Which should be whom, because the pronoun refers to a person who is the object',
    hint:'"Which" is for things. The man is a person, and he is the object of "spoke to".',
    explanation:'"Which" cannot refer to a person. The correct form is <b>whom</b> (object), because the man received the action "spoke to". "Who" would be used if the man were the subject.' }),

  makeMCQ({ id:'g9eng-grv-052', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:2,
    question:'Choose the correct relative pronoun: <i>"The school .......... she studied is now very famous."</i>',
    options:['where','which','who','whose'], answer:'where',
    hint:'A school is a place. The relative clause tells us where she studied.',
    explanation:'<b>Where</b> introduces a relative clause about a place. "Which" could also work formally ("at which she studied"), but "where" is more natural here.' }),

  makeMCQ({ id:'g9eng-grv-053', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:3,
    question:'Why is <b>that</b> <b>not</b> used in: <i>"The president, _______ visited last year, opened the bridge."</i>?',
    options:['Because "that" cannot begin a non-defining relative clause','Because "that" is only used for animals','Because "that" needs a comma after the subject','Because "that" must follow a plural noun'],
    answer:'Because "that" cannot begin a non-defining relative clause',
    hint:'The commas signal a non-defining clause. Which pronoun is banned there?',
    explanation:'"That" is restricted to <b>defining</b> relative clauses. When commas enclose the clause (making it non-defining), "which" or "who" must be used instead.' }),

  makeMCQ({ id:'g9eng-grv-054', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:2,
    question:'Choose the correct relative pronoun: <i>"The trophy .......... the team won is on display in the hall."</i>',
    options:['that','who','whom','whose'], answer:'that',
    hint:'The pronoun refers to a thing and the clause defines which trophy.',
    explanation:'<b>That</b> (or "which") is used for things in a defining relative clause. "Who" and "whom" are for people.' }),

  makeMCQ({ id:'g9eng-grv-055', chapterId:'g9eng-gr-pronouns', subsection:'relative', difficulty:3,
    question:'Which sentence is <b>correct</b>?',
    options:['The candidate whom the board selected performed well.','The candidate who the board selected performed well.','The candidate which the board selected performed well.','The candidate whose the board selected performed well.'],
    answer:'The candidate whom the board selected performed well.',
    hint:'The board (subject) selected the candidate (object). Which form of who/whom serves as an object?',
    explanation:'The pronoun is the object of "selected", so the object form <b>whom</b> is required. "Who" is the subject form. "Which" is for things, and "whose" is possessive.' }),

  // ── Adjectives · Adjectives used as nouns (g9eng-gr-adjectives) · 5 Qs ──

  makeMCQ({ id:'g9eng-grv-056', chapterId:'g9eng-gr-adjectives', subsection:'adjectives_as_nouns', difficulty:2,
    question:'In <i>"The government built housing for the elderly,"</i> what part of speech is <b>the elderly</b>?',
    options:['A noun phrase','An adjective phrase','An adverb phrase','A prepositional phrase'],
    answer:'A noun phrase',
    hint:'"The elderly" is the object of "built … for". What part of speech fills an object slot?',
    explanation:'"The + adjective" can name a whole group of people, making it a <b>noun phrase</b>. "The elderly" means elderly people and works as the object of the preposition "for".' }),

  makeMCQ({ id:'g9eng-grv-057', chapterId:'g9eng-gr-adjectives', subsection:'adjectives_as_nouns', difficulty:2,
    question:'Which sentence uses an adjective as a <b>noun</b>?',
    options:['The rich should pay higher taxes.','She wore a rich, embroidered gown.','His rich voice filled the hall.','The rich sauce coated the pasta.'],
    answer:'The rich should pay higher taxes.',
    hint:'"The rich" stands alone as the subject — it names a group, not a quality of another noun.',
    explanation:'In "The rich should pay…", "the rich" acts as the subject of the sentence and names a group of people. In the other sentences "rich" is an ordinary adjective before a noun.' }),

  makeMCQ({ id:'g9eng-grv-058', chapterId:'g9eng-gr-adjectives', subsection:'adjectives_as_nouns', difficulty:3,
    question:'Identify the sentence where the <b>underlined</b> word functions as a noun: <i>"We must help <u>the wounded</u>"</i> / <i>"A <u>wounded</u> soldier was found"</i> / <i>"She felt <u>wounded</u> by the remark"</i> / <i>"The <u>wounded</u> animal limped away"</i>',
    options:['We must help the wounded','A wounded soldier was found','She felt wounded by the remark','The wounded animal limped away'],
    answer:'We must help the wounded',
    hint:'"The wounded" is the object of the verb. In which case does it name a group, not describe another noun?',
    explanation:'In "We must help the wounded", "the wounded" is the object and names all wounded people — the adjective is doing a noun\'s job. In the other sentences "wounded" still modifies a separate noun.' }),

  makeMCQ({ id:'g9eng-grv-059', chapterId:'g9eng-gr-adjectives', subsection:'adjectives_as_nouns', difficulty:2,
    question:'Which phrase uses an adjective as a <b>noun</b>?',
    options:['the injured','an injured player','an injured knee','the more injured'],
    answer:'the injured',
    hint:'Which phrase stands alone as a name for a group?',
    explanation:'"<b>The injured</b>" names all injured people as a group, so the adjective is functioning as a noun. In the other phrases "injured" describes a specific noun ("player", "knee").' }),

  makeMCQ({ id:'g9eng-grv-060', chapterId:'g9eng-gr-adjectives', subsection:'adjectives_as_nouns', difficulty:3,
    question:'In the sentence <i>"The innocent must never be punished for the crimes of the guilty,"</i> how many adjectives are used <b>as nouns</b>?',
    options:['Two','One','Three','None'],
    answer:'Two',
    hint:'Look for "the + adjective" constructions that name groups rather than describe other nouns.',
    explanation:'Both "the innocent" and "the guilty" name groups of people, so both adjectives function as nouns. The sentence uses this structure <b>twice</b>.' })

);
})();
