'use strict';
// Grade 1 English - Chapter: Reading Readiness
// IDs: g1eng-rdr-001 … g1eng-rdr-075

(function () {

STATIC_QUESTIONS.push(

  // ── print_awareness (25) ─────────────────────────────────────────────────

  makeMCQ({ id:'g1eng-rdr-001', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'In which direction do we read English?',
    options:['Left to right','Right to left','Top to bottom only','Bottom to top'],
    answer:'Left to right',
    hint:'Think about where your eyes start on a line of writing. 👀',
    explanation:'Well done! We always read English from <b>left to right</b>, just like we write it.' }),

  makeMCQ({ id:'g1eng-rdr-002', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'Where do you look first when you start reading a page?',
    options:['The top of the page','The bottom of the page','The middle of the page','The back of the page'],
    answer:'The top of the page',
    hint:'Reading always starts at the very top. 📄',
    explanation:'Well done! We always start reading from <b>the top of the page</b> and move down.' }),

  makeMCQ({ id:'g1eng-rdr-003', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What is a sentence?',
    options:['A group of words that makes sense','One letter','A number','A drawing'],
    answer:'A group of words that makes sense',
    hint:'A sentence is made of words put together. 📝',
    explanation:'Well done! A <b>sentence</b> is a group of words that together make complete sense.' }),

  makeMCQ({ id:'g1eng-rdr-004', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What mark comes at the end of a sentence?',
    options:['A full stop (.)','A comma (,)','A star (*)','A plus (+)'],
    answer:'A full stop (.)',
    hint:'This small dot tells us a sentence has ended. 🔵',
    explanation:'Well done! A <b>full stop (.)</b> is placed at the end of a sentence to show it is finished.' }),

  makeMCQ({ id:'g1eng-rdr-005', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What must the first word of a sentence start with?',
    options:['A capital letter','A small letter','A number','A dot'],
    answer:'A capital letter',
    hint:'Every sentence has a BIG letter at the very start. 🔠',
    explanation:'Well done! Every sentence begins with a <b>capital letter</b>. It is like a signal that a new sentence is starting.' }),

  makeMCQ({ id:'g1eng-rdr-006', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'How many words are in the sentence "The cat sat."?',
    options:['Three','Two','Four','One'],
    answer:'Three',
    hint:'Count the words: The — cat — sat. How many? 🐱',
    explanation:'Well done! "The cat sat." has <b>three</b> words: The, cat, sat.' }),

  makeMCQ({ id:'g1eng-rdr-007', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What do we call the space between two words in a sentence?',
    options:['A word space','A full stop','A comma','A letter'],
    answer:'A word space',
    hint:'There is always a small gap between each word when we write. ➡️',
    explanation:'Well done! We leave a <b>word space</b> between words so they are easy to read separately.' }),

  makeMCQ({ id:'g1eng-rdr-008', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What mark is used at the end of a question?',
    options:['A question mark (?)','A full stop (.)','A comma (,)','An exclamation mark (!)'],
    answer:'A question mark (?)',
    hint:'This mark tells us we need an answer. 🤔',
    explanation:'Well done! A <b>question mark (?)</b> is placed at the end of a question.' }),

  makeMCQ({ id:'g1eng-rdr-009', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'Which of these is a word?',
    options:['cat','123','???','***'],
    answer:'cat',
    hint:'A word is made of letters that make a sound or meaning. 🐱',
    explanation:'Well done! <b>Cat</b> is a word — it is made of letters and has a meaning.' }),

  makeMCQ({ id:'g1eng-rdr-010', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What is a book cover?',
    options:['The front page that shows the title','The last page','The page with pictures','A blank page'],
    answer:'The front page that shows the title',
    hint:'This is the first thing you see when you pick up a book. 📚',
    explanation:'Well done! The <b>book cover</b> is the front of the book. It shows the title and the author\'s name.' }),

  makeMCQ({ id:'g1eng-rdr-011', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What does a picture in a book help you do?',
    options:['Understand the story better','Count numbers','Write letters','Draw shapes'],
    answer:'Understand the story better',
    hint:'Pictures show us what the words are talking about. 🖼️',
    explanation:'Well done! Pictures help us <b>understand the story better</b> by showing what is happening.' }),

  makeMCQ({ id:'g1eng-rdr-012', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'How many letters are in the word "dog"?',
    options:['Three','Two','Four','One'],
    answer:'Three',
    hint:'Count the letters in d-o-g. 🐕',
    explanation:'Well done! The word "dog" has <b>three</b> letters: d, o, g.' }),

  makeMCQ({ id:'g1eng-rdr-013', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What do we call the name of a book?',
    options:['The title','The cover','The page','The author'],
    answer:'The title',
    hint:'This is the name that tells you what the book is about. 📖',
    explanation:'Well done! The <b>title</b> is the name of the book. It appears on the cover.' }),

  makeMCQ({ id:'g1eng-rdr-014', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What is a paragraph?',
    options:['A group of sentences about the same idea','One word','A single letter','A number'],
    answer:'A group of sentences about the same idea',
    hint:'A paragraph is like a small group or family of sentences. 📝',
    explanation:'Well done! A <b>paragraph</b> is a group of sentences that are all about the same topic or idea.' }),

  makeMCQ({ id:'g1eng-rdr-015', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'Which one is a sentence?',
    options:['The dog runs.','dog runs the','runs dog','The runs dog.'],
    answer:'The dog runs.',
    hint:'A sentence has words in the right order and ends with a full stop. 🐕',
    explanation:'Well done! <b>The dog runs.</b> is a sentence — it starts with a capital, has correct order, and ends with a full stop.' }),

  makeMCQ({ id:'g1eng-rdr-016', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'Where does the author\'s name usually appear?',
    options:['On the book cover','Inside the book only','On the last page','At the top of every page'],
    answer:'On the book cover',
    hint:'Look at the front of any book — you will see the author\'s name there. 📚',
    explanation:'Well done! The <b>author\'s name</b> usually appears on the front cover of the book.' }),

  makeMCQ({ id:'g1eng-rdr-017', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What do we call the person who writes a book?',
    options:['The author','The teacher','The reader','The painter'],
    answer:'The author',
    hint:'This person creates the story or the words in the book. ✍️',
    explanation:'Well done! The <b>author</b> is the person who writes the book.' }),

  makeMCQ({ id:'g1eng-rdr-018', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'In a book, the page numbers help you to —',
    options:['find your place in the book','count letters','colour pictures','write words'],
    answer:'find your place in the book',
    hint:'Numbers on pages help you know where you are in the story. 🔢',
    explanation:'Well done! <b>Page numbers</b> help you find your place and go back to where you stopped reading.' }),

  makeMCQ({ id:'g1eng-rdr-019', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'After reading the last line of a page, where do you go next?',
    options:['To the top of the next page','Back to the start of the same page','To the bottom of the same page','To the back of the book'],
    answer:'To the top of the next page',
    hint:'We always move forward in a book, page by page. 📖',
    explanation:'Well done! After finishing a page, we turn to <b>the top of the next page</b> and continue reading.' }),

  makeMCQ({ id:'g1eng-rdr-020', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'How many letters are in the word "sun"?',
    options:['Three','Two','Four','Five'],
    answer:'Three',
    hint:'Count s-u-n. ☀️',
    explanation:'Well done! The word "sun" has <b>three</b> letters: s, u, n.' }),

  makeMCQ({ id:'g1eng-rdr-021', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'Which of these has a capital letter at the start?',
    options:['The bird sings.','the bird sings.','The bird Sings.','THE bird sings.'],
    answer:'The bird sings.',
    hint:'Only the very first word of the sentence should start with a capital. 🐦',
    explanation:'Well done! <b>The bird sings.</b> is correct — only the first word "The" has a capital letter.' }),

  makeMCQ({ id:'g1eng-rdr-022', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'How many words are in "I like dogs"?',
    options:['Three','Two','Four','One'],
    answer:'Three',
    hint:'Count: I — like — dogs. 🐕',
    explanation:'Well done! "I like dogs" has <b>three</b> words: I, like, dogs.' }),

  makeMCQ({ id:'g1eng-rdr-023', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What do illustrations in a book show?',
    options:['Pictures that match the story','Only numbers','Only letters','The author\'s name'],
    answer:'Pictures that match the story',
    hint:'Illustrations make the story come alive! 🖼️',
    explanation:'Well done! <b>Illustrations</b> are pictures inside a book that show what the story is about.' }),

  makeMCQ({ id:'g1eng-rdr-024', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'What is the last thing at the end of a book called?',
    options:['The back cover','The title page','The index','The glossary'],
    answer:'The back cover',
    hint:'This is the very last part of the outside of a book. 📚',
    explanation:'Well done! The <b>back cover</b> is the last part of the outside of a book.' }),

  makeMCQ({ id:'g1eng-rdr-025', chapterId:'g1eng-reading', difficulty:1, subsection:'print_awareness',
    question:'Which sentence has correct punctuation?',
    options:['The cat is soft.','The cat is soft','the cat is soft.','The cat is soft!.'],
    answer:'The cat is soft.',
    hint:'Check the capital letter at the start and the full stop at the end. 🐱',
    explanation:'Well done! <b>The cat is soft.</b> is correct — it has a capital T and a full stop at the end.' }),

  // ── letter_recognition (25) ─────────────────────────────────────────────

  makeMCQ({ id:'g1eng-rdr-026', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'How many letters are in the English alphabet?',
    options:['26','24','28','30'],
    answer:'26',
    hint:'Count from A to Z! 🔤',
    explanation:'Well done! The English alphabet has <b>26</b> letters, from A to Z.' }),

  makeMCQ({ id:'g1eng-rdr-027', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which of these is a vowel?',
    options:['a','b','c','d'],
    answer:'a',
    hint:'The vowels are a, e, i, o, u. 🔡',
    explanation:'Well done! <b>a</b> is a vowel. The five vowels are: a, e, i, o, u.' }),

  makeMCQ({ id:'g1eng-rdr-028', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which of these is NOT a vowel?',
    options:['b','a','e','i'],
    answer:'b',
    hint:'Vowels are a, e, i, o, u. Everything else is a consonant. 🔡',
    explanation:'Well done! <b>b</b> is a consonant, not a vowel. The vowels are: a, e, i, o, u.' }),

  makeMCQ({ id:'g1eng-rdr-029', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What is the capital letter of "a"?',
    options:['A','B','C','D'],
    answer:'A',
    hint:'Every small letter has a big version called a capital. 🔠',
    explanation:'Well done! The capital letter of "a" is <b>A</b>.' }),

  makeMCQ({ id:'g1eng-rdr-030', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which letter comes after "D" in the alphabet?',
    options:['E','F','C','B'],
    answer:'E',
    hint:'Say the alphabet: A B C D ___. What comes next? 🔤',
    explanation:'Well done! <b>E</b> comes after D in the alphabet: A, B, C, D, <b>E</b>.' }),

  makeMCQ({ id:'g1eng-rdr-031', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which letter comes before "C" in the alphabet?',
    options:['B','D','A','E'],
    answer:'B',
    hint:'Say: A, ___, C. What goes in the middle? 🔤',
    explanation:'Well done! <b>B</b> comes before C in the alphabet: A, <b>B</b>, C.' }),

  makeMCQ({ id:'g1eng-rdr-032', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What is the small letter of "M"?',
    options:['m','n','w','h'],
    answer:'m',
    hint:'Capital M and its small version look very similar! Mm 🔡',
    explanation:'Well done! The small letter of "M" is <b>m</b>.' }),

  makeMCQ({ id:'g1eng-rdr-033', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'How many vowels are in the English alphabet?',
    options:['Five','Four','Six','Three'],
    answer:'Five',
    hint:'Count them: a, e, i, o, u. 🖐️',
    explanation:'Well done! There are <b>five</b> vowels in English: a, e, i, o, u.' }),

  makeMCQ({ id:'g1eng-rdr-034', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which of these is a vowel?',
    options:['o','p','q','r'],
    answer:'o',
    hint:'Look for one of these: a, e, i, o, u. ⭕',
    explanation:'Well done! <b>o</b> is a vowel. The five vowels are a, e, i, o, u.' }),

  makeMCQ({ id:'g1eng-rdr-035', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What letter comes after "Z" in the alphabet?',
    options:['Nothing — Z is the last letter','A','B','Y'],
    answer:'Nothing — Z is the last letter',
    hint:'Say the alphabet to the end. What is the very last letter? 🔤',
    explanation:'Well done! <b>Z is the last letter</b> of the English alphabet. There is nothing after it.' }),

  makeMCQ({ id:'g1eng-rdr-036', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which of these is a capital letter?',
    options:['S','s','t','r'],
    answer:'S',
    hint:'Capital letters are BIG letters. 🔠',
    explanation:'Well done! <b>S</b> is the capital letter. The small version is "s".' }),

  makeMCQ({ id:'g1eng-rdr-037', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What is the first letter of the alphabet?',
    options:['A','B','C','D'],
    answer:'A',
    hint:'The alphabet always starts with this letter. 🅰️',
    explanation:'Well done! <b>A</b> is the first letter of the English alphabet.' }),

  makeMCQ({ id:'g1eng-rdr-038', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which letter comes after "M" in the alphabet?',
    options:['N','L','O','P'],
    answer:'N',
    hint:'A B C D E F G H I J K L M ___ . 🔤',
    explanation:'Well done! <b>N</b> comes after M in the alphabet.' }),

  makeMCQ({ id:'g1eng-rdr-039', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which of these is a vowel?',
    options:['u','v','w','x'],
    answer:'u',
    hint:'Remember: a, e, i, o, u are the vowels. 🔡',
    explanation:'Well done! <b>u</b> is a vowel. The five vowels are a, e, i, o, u.' }),

  makeMCQ({ id:'g1eng-rdr-040', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What is the capital of the letter "t"?',
    options:['T','L','I','J'],
    answer:'T',
    hint:'The capital version of t is a letter that looks like a cross. ✝️',
    explanation:'Well done! The capital letter of "t" is <b>T</b>.' }),

  makeMCQ({ id:'g1eng-rdr-041', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which letter is NOT a vowel?',
    options:['g','a','e','i'],
    answer:'g',
    hint:'Vowels are a, e, i, o, u. The rest are consonants. 🔡',
    explanation:'Well done! <b>g</b> is a consonant, not a vowel. Vowels are: a, e, i, o, u.' }),

  makeMCQ({ id:'g1eng-rdr-042', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What comes before "G" in the alphabet?',
    options:['F','H','E','D'],
    answer:'F',
    hint:'A B C D E ___ G. What is missing? 🔤',
    explanation:'Well done! <b>F</b> comes before G in the alphabet: E, <b>F</b>, G.' }),

  makeMCQ({ id:'g1eng-rdr-043', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which of these is a small letter?',
    options:['d','D','B','G'],
    answer:'d',
    hint:'Small letters are the ones we use most in writing. 🔡',
    explanation:'Well done! <b>d</b> is the small letter. Its capital is D.' }),

  makeMCQ({ id:'g1eng-rdr-044', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'How many letters come before "E" in the alphabet?',
    options:['Four','Three','Five','Two'],
    answer:'Four',
    hint:'A, B, C, D come before E. Count them! 🔢',
    explanation:'Well done! There are <b>four</b> letters before E: A, B, C, D.' }),

  makeMCQ({ id:'g1eng-rdr-045', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which of these is a vowel?',
    options:['e','f','g','h'],
    answer:'e',
    hint:'Look for one of: a, e, i, o, u. 🔡',
    explanation:'Well done! <b>e</b> is a vowel. The five vowels are a, e, i, o, u.' }),

  makeMCQ({ id:'g1eng-rdr-046', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What is the last letter of the alphabet?',
    options:['Z','Y','X','W'],
    answer:'Z',
    hint:'Sing the alphabet song all the way to the end! 🎵',
    explanation:'Well done! <b>Z</b> is the very last letter of the English alphabet.' }),

  makeMCQ({ id:'g1eng-rdr-047', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which letters are vowels? Choose the group that has ONLY vowels.',
    options:['a, e, i, o, u','a, b, c, d, e','b, c, d, f, g','a, e, i, p, u'],
    answer:'a, e, i, o, u',
    hint:'All five vowels must be there and only vowels! 🔡',
    explanation:'Well done! The five vowels are <b>a, e, i, o, u</b>.' }),

  makeMCQ({ id:'g1eng-rdr-048', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What comes after "P" in the alphabet?',
    options:['Q','O','R','S'],
    answer:'Q',
    hint:'... N O P ___ R S ... 🔤',
    explanation:'Well done! <b>Q</b> comes after P in the alphabet.' }),

  makeMCQ({ id:'g1eng-rdr-049', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'Which of these is a vowel?',
    options:['i','j','k','l'],
    answer:'i',
    hint:'Remember the five vowels: a, e, i, o, u. 🔡',
    explanation:'Well done! <b>i</b> is a vowel. The five vowels are a, e, i, o, u.' }),

  makeMCQ({ id:'g1eng-rdr-050', chapterId:'g1eng-reading', difficulty:1, subsection:'letter_recognition',
    question:'What is the capital of "b"?',
    options:['B','D','P','R'],
    answer:'B',
    hint:'The big version of this letter has two bumps on the right side. 🔠',
    explanation:'Well done! The capital of "b" is <b>B</b>.' }),

  // ── sight_words (25) ──────────────────────────────────────────────────────

  makeMCQ({ id:'g1eng-rdr-051', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word means the same as "myself"?',
    options:['I','You','He','She'],
    answer:'I',
    hint:'When you talk about yourself, you use this little word. 😊',
    explanation:'Well done! The word <b>I</b> is used when you talk about yourself.' }),

  makeMCQ({ id:'g1eng-rdr-052', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in the blank: "___ is a sunny day."',
    options:['It','He','She','I'],
    answer:'It',
    hint:'When we talk about the weather, we use this word. ☀️',
    explanation:'Well done! We use <b>It</b> when talking about things like weather: "It is sunny."' }),

  makeMCQ({ id:'g1eng-rdr-053', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word do we use when talking about a boy?',
    options:['He','She','They','We'],
    answer:'He',
    hint:'This word is used for a boy or a man. 👦',
    explanation:'Well done! We use <b>He</b> when talking about a boy or man: "He runs fast."' }),

  makeMCQ({ id:'g1eng-rdr-054', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word do we use when talking about a girl?',
    options:['She','He','They','We'],
    answer:'She',
    hint:'This word is used for a girl or a woman. 👧',
    explanation:'Well done! We use <b>She</b> when talking about a girl or woman: "She is kind."' }),

  makeMCQ({ id:'g1eng-rdr-055', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in the blank: "The cat ___ on the mat."',
    options:['is','are','am','were'],
    answer:'is',
    hint:'We use "is" for one thing (the cat is just one cat). 🐱',
    explanation:'Well done! We use <b>is</b> for one person or thing: "The cat <b>is</b> on the mat."' }),

  makeMCQ({ id:'g1eng-rdr-056', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word joins two ideas: "I like cats ___ dogs."',
    options:['and','but','or','so'],
    answer:'and',
    hint:'This small word joins things together that both go with each other. 🐱🐕',
    explanation:'Well done! The word <b>and</b> is used to join two things together: "I like cats <b>and</b> dogs."' }),

  makeMCQ({ id:'g1eng-rdr-057', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word means "able to": "___ you see the bird?"',
    options:['Can','Will','Was','Are'],
    answer:'Can',
    hint:'This word shows that you are able to do something. 🐦',
    explanation:'Well done! <b>Can</b> means "able to": "<b>Can</b> you see the bird?"' }),

  makeMCQ({ id:'g1eng-rdr-058', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in the blank: "Come ___ me, please."',
    options:['to','at','on','in'],
    answer:'to',
    hint:'We use this small word to show where we are going or who we are going towards. 👈',
    explanation:'Well done! We say "Come <b>to</b> me, please" — the word "to" shows direction.' }),

  makeMCQ({ id:'g1eng-rdr-059', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word means "look with your eyes"?',
    options:['See','Hear','Smell','Touch'],
    answer:'See',
    hint:'We do this with our eyes. 👀',
    explanation:'Well done! <b>See</b> means to look at something with your eyes.' }),

  makeMCQ({ id:'g1eng-rdr-060', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in the blank: "___ like apples."',
    options:['I','He','She','We'],
    answer:'I',
    hint:'When YOU say what you like, which word do you use? 😊',
    explanation:'Well done! When we talk about ourselves, we use <b>I</b>: "<b>I</b> like apples."' }),

  makeMCQ({ id:'g1eng-rdr-061', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word means "to move with your feet quickly"?',
    options:['Go','Sit','Sleep','Stop'],
    answer:'Go',
    hint:'When you leave a place, you ___ away. 🏃',
    explanation:'Well done! <b>Go</b> means to move from one place to another.' }),

  makeMCQ({ id:'g1eng-rdr-062', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in: "The book is ___ the table."',
    options:['on','in','at','to'],
    answer:'on',
    hint:'The book is resting on top of the table. 📚',
    explanation:'Well done! We use <b>on</b> when something is resting on top of another thing.' }),

  makeMCQ({ id:'g1eng-rdr-063', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word is the opposite of "go"?',
    options:['Come','Run','Walk','Jump'],
    answer:'Come',
    hint:'If go means move away, this word means move towards. 👋',
    explanation:'Well done! <b>Come</b> is the opposite of "go" — it means to move towards someone.' }),

  makeMCQ({ id:'g1eng-rdr-064', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in: "___ is your name?"',
    options:['What','Where','Who','How'],
    answer:'What',
    hint:'We use this question word to ask about a thing. ❓',
    explanation:'Well done! <b>What</b> is used to ask about things: "<b>What</b> is your name?"' }),

  makeMCQ({ id:'g1eng-rdr-065', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word means "belonging to me"?',
    options:['My','Your','His','Her'],
    answer:'My',
    hint:'When the thing belongs to you, you use this word. 😊',
    explanation:'Well done! <b>My</b> means "belonging to me": "<b>My</b> bag is red."' }),

  makeMCQ({ id:'g1eng-rdr-066', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in: "The dog ___ in the garden."',
    options:['is','am','are','be'],
    answer:'is',
    hint:'The dog is just one. Which verb matches one thing? 🐕',
    explanation:'Well done! We use <b>is</b> for one thing: "The dog <b>is</b> in the garden."' }),

  makeMCQ({ id:'g1eng-rdr-067', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word means "more than one person including yourself"?',
    options:['We','I','He','She'],
    answer:'We',
    hint:'When you and your friends do something together, you say "___". 👫',
    explanation:'Well done! <b>We</b> is used when you and other people do something together: "<b>We</b> play football."' }),

  makeMCQ({ id:'g1eng-rdr-068', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in: "___ is the bird?"',
    options:['Where','What','Who','How'],
    answer:'Where',
    hint:'We use this word to ask about a place or location. 🐦',
    explanation:'Well done! <b>Where</b> is used to ask about a place: "<b>Where</b> is the bird?"' }),

  makeMCQ({ id:'g1eng-rdr-069', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which common word fills the blank: "___ cat is soft."',
    options:['The','A','An','And'],
    answer:'The',
    hint:'We use this word when we mean a specific cat we already know about. 🐱',
    explanation:'Well done! <b>The</b> is used for a specific thing: "<b>The</b> cat is soft."' }),

  makeMCQ({ id:'g1eng-rdr-070', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word fills the blank: "I ___ a dog." (meaning I own it)',
    options:['have','is','are','am'],
    answer:'have',
    hint:'This word shows that something belongs to you. 🐕',
    explanation:'Well done! <b>Have</b> means to own or possess: "I <b>have</b> a dog."' }),

  makeMCQ({ id:'g1eng-rdr-071', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word means "not the same as"?',
    options:['Like','And','But','Or'],
    answer:'Like',
    hint:'Actually — "like" means similar to, not different. The word that shows contrast in a sentence is... 🤔',
    explanation:'Well done — tricky question! <b>Like</b> means similar to or enjoy. For example: "I <b>like</b> cats." It shows something you enjoy.' }),

  makeMCQ({ id:'g1eng-rdr-072', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Fill in: "The flowers are red ___ yellow."',
    options:['and','but','or','so'],
    answer:'and',
    hint:'This word joins things that both apply at the same time. 🌸',
    explanation:'Well done! <b>And</b> joins two things: "red <b>and</b> yellow" means both colours.' }),

  makeMCQ({ id:'g1eng-rdr-073', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word means the same as "also"?',
    options:['Too','To','Two','The'],
    answer:'Too',
    hint:'You say "Me ___!" when you want to be included. 😊',
    explanation:'Well done! <b>Too</b> means "also" or "as well": "I want to come, <b>too</b>!"' }),

  makeMCQ({ id:'g1eng-rdr-074', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word fills the blank: "___ is raining today."',
    options:['It','He','She','I'],
    answer:'It',
    hint:'When we talk about weather, we use this word. 🌧️',
    explanation:'Well done! We use <b>It</b> for weather: "<b>It</b> is raining today."' }),

  makeMCQ({ id:'g1eng-rdr-075', chapterId:'g1eng-reading', difficulty:1, subsection:'sight_words',
    question:'Which word fills the blank: "She ___ to school every day."',
    options:['goes','go','going','went'],
    answer:'goes',
    hint:'When she (one girl) does something every day, we add -es or -s to the verb. 🏫',
    explanation:'Well done! We say "she <b>goes</b>" because for he/she/it we add -s or -es to the verb.' })

);
})();
