'use strict';
// Grade 1 English - Chapter: Phonics
// IDs: g1eng-pho-001 … g1eng-pho-075

(function () {

STATIC_QUESTIONS.push(

  // ── initial_sounds (25) ──────────────────────────────────────────────────

  makeMCQ({ id:'g1eng-pho-001', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /b/ sound?',
    options:['ball','cat','dog','sun'],
    answer:'ball',
    hint:'Say each word slowly. Which one starts with a /b/ sound like "buzz"? 🏀',
    explanation:'Well done! <b>Ball</b> starts with the /b/ sound. B-b-ball! Other /b/ words: bat, bed, bus.' }),

  makeMCQ({ id:'g1eng-pho-002', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /s/ sound?',
    options:['sun','dog','cat','hat'],
    answer:'sun',
    hint:'Say each word. Which starts with the s-s-s sound like a snake? 🐍',
    explanation:'Well done! <b>Sun</b> starts with the /s/ sound. S-s-sun! Other /s/ words: sit, sock, star.' }),

  makeMCQ({ id:'g1eng-pho-003', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /m/ sound?',
    options:['mango','bird','tree','fish'],
    answer:'mango',
    hint:'M-m-m. Which word starts with the humming sound? 🥭',
    explanation:'Well done! <b>Mango</b> starts with the /m/ sound. M-m-mango! Other /m/ words: mat, milk, moon.' }),

  makeMCQ({ id:'g1eng-pho-004', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /c/ (k) sound?',
    options:['cat','sun','dog','fish'],
    answer:'cat',
    hint:'C makes a hard /k/ sound in "cat". C-c-cat! 🐱',
    explanation:'Well done! <b>Cat</b> starts with the hard /c/ (k) sound. C-c-cat! Other /c/ words: cup, car, cow.' }),

  makeMCQ({ id:'g1eng-pho-005', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /f/ sound?',
    options:['fish','dog','cat','bird'],
    answer:'fish',
    hint:'F-f-f. Which word starts with the sound you make blowing out air? 🐟',
    explanation:'Well done! <b>Fish</b> starts with the /f/ sound. F-f-fish! Other /f/ words: fan, fox, frog.' }),

  makeMCQ({ id:'g1eng-pho-006', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /h/ sound?',
    options:['hat','ball','cat','dog'],
    answer:'hat',
    hint:'H makes a puff of air sound. H-h-hat! 🎩',
    explanation:'Well done! <b>Hat</b> starts with the /h/ sound. H-h-hat! Other /h/ words: hen, hop, hill.' }),

  makeMCQ({ id:'g1eng-pho-007', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /d/ sound?',
    options:['dog','cat','sun','hen'],
    answer:'dog',
    hint:'D-d-d. Which word starts the same way as "drum"? 🐕',
    explanation:'Well done! <b>Dog</b> starts with the /d/ sound. D-d-dog! Other /d/ words: drum, door, dig.' }),

  makeMCQ({ id:'g1eng-pho-008', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /t/ sound?',
    options:['tree','dog','fish','hen'],
    answer:'tree',
    hint:'T-t-t. A very sharp, quick sound. T-t-tree! 🌳',
    explanation:'Well done! <b>Tree</b> starts with the /t/ sound. T-t-tree! Other /t/ words: top, tap, table.' }),

  makeMCQ({ id:'g1eng-pho-009', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /p/ sound?',
    options:['pig','cat','dog','fish'],
    answer:'pig',
    hint:'P makes a popping sound. P-p-pig! 🐷',
    explanation:'Well done! <b>Pig</b> starts with the /p/ sound. P-p-pig! Other /p/ words: pen, pot, park.' }),

  makeMCQ({ id:'g1eng-pho-010', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /r/ sound?',
    options:['rabbit','dog','sun','cat'],
    answer:'rabbit',
    hint:'R-r-r. A rolling sound. R-r-rabbit! 🐰',
    explanation:'Well done! <b>Rabbit</b> starts with the /r/ sound. R-r-rabbit! Other /r/ words: red, rain, run.' }),

  makeMCQ({ id:'g1eng-pho-011', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /g/ sound?',
    options:['goat','cat','dog','fish'],
    answer:'goat',
    hint:'G makes a sound from your throat. G-g-goat! 🐐',
    explanation:'Well done! <b>Goat</b> starts with the /g/ sound. G-g-goat! Other /g/ words: go, girl, gap.' }),

  makeMCQ({ id:'g1eng-pho-012', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /l/ sound?',
    options:['lion','cat','dog','sun'],
    answer:'lion',
    hint:'L makes a soft, flowing sound. L-l-lion! 🦁',
    explanation:'Well done! <b>Lion</b> starts with the /l/ sound. L-l-lion! Other /l/ words: leg, leaf, lamp.' }),

  makeMCQ({ id:'g1eng-pho-013', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /n/ sound?',
    options:['nest','cat','dog','hen'],
    answer:'nest',
    hint:'N-n-n. A humming sound through your nose. N-n-nest! 🐦',
    explanation:'Well done! <b>Nest</b> starts with the /n/ sound. N-n-nest! Other /n/ words: nut, nose, night.' }),

  makeMCQ({ id:'g1eng-pho-014', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which two words start with the same sound?',
    options:['big and ball','cat and dog','sun and moon','fish and bird'],
    answer:'big and ball',
    hint:'Say each pair. Which pair starts with the same sound? 🔤',
    explanation:'Well done! <b>Big and ball</b> both start with the /b/ sound: b-ig, b-all.' }),

  makeMCQ({ id:'g1eng-pho-015', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /j/ sound?',
    options:['jam','hat','cat','dog'],
    answer:'jam',
    hint:'J makes a soft, gentle sound. J-j-jam! 🍓',
    explanation:'Well done! <b>Jam</b> starts with the /j/ sound. J-j-jam! Other /j/ words: jet, jump, jar.' }),

  makeMCQ({ id:'g1eng-pho-016', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which two words start with the same sound?',
    options:['sun and sock','cat and dog','tree and bird','fish and hat'],
    answer:'sun and sock',
    hint:'Say each pair. Which starts with s-s-s? 🧦',
    explanation:'Well done! <b>Sun and sock</b> both start with the /s/ sound: s-un, s-ock.' }),

  makeMCQ({ id:'g1eng-pho-017', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /w/ sound?',
    options:['water','dog','cat','fish'],
    answer:'water',
    hint:'W makes a round mouth shape. W-w-water! 💧',
    explanation:'Well done! <b>Water</b> starts with the /w/ sound. W-w-water! Other /w/ words: wet, wind, walk.' }),

  makeMCQ({ id:'g1eng-pho-018', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /v/ sound?',
    options:['van','cat','dog','hat'],
    answer:'van',
    hint:'V makes a buzzing sound on your lip. V-v-van! 🚐',
    explanation:'Well done! <b>Van</b> starts with the /v/ sound. V-v-van! Other /v/ words: vine, vet, very.' }),

  makeMCQ({ id:'g1eng-pho-019', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /k/ sound (spelled with "k")?',
    options:['kite','cat','dog','sun'],
    answer:'kite',
    hint:'K and C both make the /k/ sound. K-k-kite! 🪁',
    explanation:'Well done! <b>Kite</b> starts with the /k/ sound. K-k-kite! Other k words: king, kit, key.' }),

  makeMCQ({ id:'g1eng-pho-020', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which two words start with the same sound?',
    options:['fish and frog','dog and cat','sun and moon','hat and ball'],
    answer:'fish and frog',
    hint:'Say each pair. Which starts with f-f-f? 🐟🐸',
    explanation:'Well done! <b>Fish and frog</b> both start with the /f/ sound: f-ish, f-rog.' }),

  makeMCQ({ id:'g1eng-pho-021', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /z/ sound?',
    options:['zebra','dog','cat','hen'],
    answer:'zebra',
    hint:'Z makes a buzzing sound like a bee. Z-z-zebra! 🦓',
    explanation:'Well done! <b>Zebra</b> starts with the /z/ sound. Z-z-zebra! Other /z/ words: zip, zoo, zero.' }),

  makeMCQ({ id:'g1eng-pho-022', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word does NOT start with the /t/ sound?',
    options:['dog','tree','table','top'],
    answer:'dog',
    hint:'Three words start with /t/. Which one is different? 🐕',
    explanation:'Well done! <b>Dog</b> does NOT start with /t/ — it starts with /d/. Tree, table and top all start with /t/.' }),

  makeMCQ({ id:'g1eng-pho-023', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word starts with the /qu/ sound?',
    options:['queen','dog','cat','fish'],
    answer:'queen',
    hint:'Qu makes a kw sound. Qu-qu-queen! 👑',
    explanation:'Well done! <b>Queen</b> starts with the /qu/ sound. Qu-qu-queen! Other qu words: quick, quiet, quiz.' }),

  makeMCQ({ id:'g1eng-pho-024', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which two words start with the same sound?',
    options:['mango and moon','cat and dog','sun and hat','tree and fish'],
    answer:'mango and moon',
    hint:'Say each pair. Which pair starts with m-m-m? 🥭🌙',
    explanation:'Well done! <b>Mango and moon</b> both start with the /m/ sound: m-ango, m-oon.' }),

  makeMCQ({ id:'g1eng-pho-025', chapterId:'g1eng-phonics', difficulty:1, subsection:'initial_sounds',
    question:'Which word does NOT start with the /c/ (k) sound?',
    options:['sun','cat','car','cup'],
    answer:'sun',
    hint:'Three words start with /c/. Which one starts with a different sound? ☀️',
    explanation:'Well done! <b>Sun</b> does NOT start with /c/ — it starts with /s/. Cat, car and cup all start with /c/ (k).' }),

  // ── rhyming_words (25) ────────────────────────────────────────────────────

  makeMCQ({ id:'g1eng-pho-026', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "cat"?',
    options:['mat','dog','sun','fish'],
    answer:'mat',
    hint:'Cat ends with -at. Find another -at word. 🐱',
    explanation:'Well done! <b>Mat</b> rhymes with cat — they both end with the "-at" sound: c-<b>at</b>, m-<b>at</b>.' }),

  makeMCQ({ id:'g1eng-pho-027', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "pen"?',
    options:['ten','cat','dog','sun'],
    answer:'ten',
    hint:'Pen ends with -en. Find another -en word. ✏️',
    explanation:'Well done! <b>Ten</b> rhymes with pen — they both end with the "-en" sound: p-<b>en</b>, t-<b>en</b>.' }),

  makeMCQ({ id:'g1eng-pho-028', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "dog"?',
    options:['log','cat','fish','hen'],
    answer:'log',
    hint:'Dog ends with -og. Find another -og word. 🐕',
    explanation:'Well done! <b>Log</b> rhymes with dog — they both end with the "-og" sound: d-<b>og</b>, l-<b>og</b>.' }),

  makeMCQ({ id:'g1eng-pho-029', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "sun"?',
    options:['run','dog','fish','cat'],
    answer:'run',
    hint:'Sun ends with -un. Find another -un word. ☀️',
    explanation:'Well done! <b>Run</b> rhymes with sun — they both end with the "-un" sound: s-<b>un</b>, r-<b>un</b>.' }),

  makeMCQ({ id:'g1eng-pho-030', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "big"?',
    options:['pig','dog','sun','hat'],
    answer:'pig',
    hint:'Big ends with -ig. Find another -ig word. 🐷',
    explanation:'Well done! <b>Pig</b> rhymes with big — they both end with the "-ig" sound: b-<b>ig</b>, p-<b>ig</b>.' }),

  makeMCQ({ id:'g1eng-pho-031', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "bed"?',
    options:['red','dog','sun','fish'],
    answer:'red',
    hint:'Bed ends with -ed. Find another -ed word. 🛏️',
    explanation:'Well done! <b>Red</b> rhymes with bed — they both end with the "-ed" sound: b-<b>ed</b>, r-<b>ed</b>.' }),

  makeMCQ({ id:'g1eng-pho-032', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "hop"?',
    options:['top','cat','dog','sun'],
    answer:'top',
    hint:'Hop ends with -op. Find another -op word. 🐸',
    explanation:'Well done! <b>Top</b> rhymes with hop — they both end with the "-op" sound: h-<b>op</b>, t-<b>op</b>.' }),

  makeMCQ({ id:'g1eng-pho-033', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "cup"?',
    options:['pup','cat','dog','hen'],
    answer:'pup',
    hint:'Cup ends with -up. Find another -up word. ☕',
    explanation:'Well done! <b>Pup</b> (a baby dog) rhymes with cup — they both end with the "-up" sound: c-<b>up</b>, p-<b>up</b>.' }),

  makeMCQ({ id:'g1eng-pho-034', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which pair of words rhymes?',
    options:['sat – hat','dog – fish','sun – bird','cat – dog'],
    answer:'sat – hat',
    hint:'Say each pair. Which pair ends with the same sound? 🎩',
    explanation:'Well done! <b>Sat and hat</b> rhyme — they both end with the "-at" sound: s-<b>at</b>, h-<b>at</b>.' }),

  makeMCQ({ id:'g1eng-pho-035', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "net"?',
    options:['wet','dog','sun','cat'],
    answer:'wet',
    hint:'Net ends with -et. Find another -et word. 🎾',
    explanation:'Well done! <b>Wet</b> rhymes with net — they both end with the "-et" sound: n-<b>et</b>, w-<b>et</b>.' }),

  makeMCQ({ id:'g1eng-pho-036', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "bin"?',
    options:['tin','dog','sun','fish'],
    answer:'tin',
    hint:'Bin ends with -in. Find another -in word. 🗑️',
    explanation:'Well done! <b>Tin</b> rhymes with bin — they both end with the "-in" sound: b-<b>in</b>, t-<b>in</b>.' }),

  makeMCQ({ id:'g1eng-pho-037', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "fan"?',
    options:['can','dog','fish','sun'],
    answer:'can',
    hint:'Fan ends with -an. Find another -an word. 🌬️',
    explanation:'Well done! <b>Can</b> rhymes with fan — they both end with the "-an" sound: f-<b>an</b>, c-<b>an</b>.' }),

  makeMCQ({ id:'g1eng-pho-038', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which pair of words rhymes?',
    options:['bus – fuss','dog – cat','sun – bird','fish – hat'],
    answer:'bus – fuss',
    hint:'Say each pair. Which pair ends with the same sound? 🚌',
    explanation:'Well done! <b>Bus and fuss</b> rhyme — they both end with the "-us" sound.' }),

  makeMCQ({ id:'g1eng-pho-039', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "map"?',
    options:['cap','dog','fish','sun'],
    answer:'cap',
    hint:'Map ends with -ap. Find another -ap word. 🗺️',
    explanation:'Well done! <b>Cap</b> rhymes with map — they both end with the "-ap" sound: m-<b>ap</b>, c-<b>ap</b>.' }),

  makeMCQ({ id:'g1eng-pho-040', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "mop"?',
    options:['hop','cat','fish','sun'],
    answer:'hop',
    hint:'Mop ends with -op. Find another -op word. 🧹',
    explanation:'Well done! <b>Hop</b> rhymes with mop — they both end with the "-op" sound: m-<b>op</b>, h-<b>op</b>.' }),

  makeMCQ({ id:'g1eng-pho-041', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word does NOT rhyme with "cat"?',
    options:['dog','hat','sat','bat'],
    answer:'dog',
    hint:'Three words end with -at. Which one is different? 🐕',
    explanation:'Well done! <b>Dog</b> does NOT rhyme with cat — it ends in -og. Hat, sat and bat all end in -at.' }),

  makeMCQ({ id:'g1eng-pho-042', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "lip"?',
    options:['tip','dog','fish','sun'],
    answer:'tip',
    hint:'Lip ends with -ip. Find another -ip word. 👄',
    explanation:'Well done! <b>Tip</b> rhymes with lip — they both end with the "-ip" sound: l-<b>ip</b>, t-<b>ip</b>.' }),

  makeMCQ({ id:'g1eng-pho-043', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "hot"?',
    options:['pot','dog','fish','sun'],
    answer:'pot',
    hint:'Hot ends with -ot. Find another -ot word. 🌶️',
    explanation:'Well done! <b>Pot</b> rhymes with hot — they both end with the "-ot" sound: h-<b>ot</b>, p-<b>ot</b>.' }),

  makeMCQ({ id:'g1eng-pho-044', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which pair of words rhymes?',
    options:['hit – sit','dog – cat','sun – bird','fish – hat'],
    answer:'hit – sit',
    hint:'Say each pair. Which pair ends with the same -it sound? 🎯',
    explanation:'Well done! <b>Hit and sit</b> rhyme — they both end with the "-it" sound.' }),

  makeMCQ({ id:'g1eng-pho-045', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "jam"?',
    options:['ham','dog','fish','sun'],
    answer:'ham',
    hint:'Jam ends with -am. Find another -am word. 🍓',
    explanation:'Well done! <b>Ham</b> rhymes with jam — they both end with the "-am" sound: j-<b>am</b>, h-<b>am</b>.' }),

  makeMCQ({ id:'g1eng-pho-046', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "mug"?',
    options:['bug','dog','fish','sun'],
    answer:'bug',
    hint:'Mug ends with -ug. Find another -ug word. ☕',
    explanation:'Well done! <b>Bug</b> rhymes with mug — they both end with the "-ug" sound: m-<b>ug</b>, b-<b>ug</b>.' }),

  makeMCQ({ id:'g1eng-pho-047', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word does NOT rhyme with "dog"?',
    options:['sun','log','bog','fog'],
    answer:'sun',
    hint:'Three words end with -og. Which one ends differently? ☀️',
    explanation:'Well done! <b>Sun</b> does NOT rhyme with dog — it ends in -un. Log, bog and fog all end in -og.' }),

  makeMCQ({ id:'g1eng-pho-048', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "wet"?',
    options:['jet','dog','fish','sun'],
    answer:'jet',
    hint:'Wet ends with -et. Find another -et word. ✈️',
    explanation:'Well done! <b>Jet</b> rhymes with wet — they both end with the "-et" sound: w-<b>et</b>, j-<b>et</b>.' }),

  makeMCQ({ id:'g1eng-pho-049', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which pair of words rhymes?',
    options:['fox – box','dog – cat','sun – moon','fish – bird'],
    answer:'fox – box',
    hint:'Say each pair. Which pair ends with the same sound? 🦊📦',
    explanation:'Well done! <b>Fox and box</b> rhyme — they both end with the "-ox" sound.' }),

  makeMCQ({ id:'g1eng-pho-050', chapterId:'g1eng-phonics', difficulty:1, subsection:'rhyming_words',
    question:'Which word rhymes with "fun"?',
    options:['bun','dog','fish','cat'],
    answer:'bun',
    hint:'Fun ends with -un. Find another -un word. 🍞',
    explanation:'Well done! <b>Bun</b> rhymes with fun — they both end with the "-un" sound: f-<b>un</b>, b-<b>un</b>.' }),

  // ── syllables (25) ────────────────────────────────────────────────────────

  makeMCQ({ id:'g1eng-pho-051', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does the word "cat" have?',
    options:['One','Two','Three','Four'],
    answer:'One',
    hint:'Clap for each syllable. Cat — one clap! 👏',
    explanation:'Well done! <b>Cat</b> has <b>one</b> syllable. Short words often have just one beat: cat, dog, sun, hat.' }),

  makeMCQ({ id:'g1eng-pho-052', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "banana" have?',
    options:['Three','Two','One','Four'],
    answer:'Three',
    hint:'Clap as you say it: ba-na-na. How many claps? 🍌',
    explanation:'Well done! <b>Ba-na-na</b> has <b>three</b> syllables. Clap each part: ba (1), na (2), na (3).' }),

  makeMCQ({ id:'g1eng-pho-053', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "apple" have?',
    options:['Two','One','Three','Four'],
    answer:'Two',
    hint:'Clap as you say it: ap-ple. How many claps? 🍎',
    explanation:'Well done! <b>Ap-ple</b> has <b>two</b> syllables: ap (1), ple (2).' }),

  makeMCQ({ id:'g1eng-pho-054', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "dog" have?',
    options:['One','Two','Three','Four'],
    answer:'One',
    hint:'Clap as you say it. Dog — one quick clap! 🐕',
    explanation:'Well done! <b>Dog</b> has <b>one</b> syllable. Short CVC words usually have one syllable.' }),

  makeMCQ({ id:'g1eng-pho-055', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "mango" have?',
    options:['Two','One','Three','Four'],
    answer:'Two',
    hint:'Clap as you say it: man-go. How many claps? 🥭',
    explanation:'Well done! <b>Man-go</b> has <b>two</b> syllables: man (1), go (2).' }),

  makeMCQ({ id:'g1eng-pho-056', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "elephant" have?',
    options:['Three','Two','One','Four'],
    answer:'Three',
    hint:'Clap as you say it: el-e-phant. How many claps? 🐘',
    explanation:'Well done! <b>El-e-phant</b> has <b>three</b> syllables: el (1), e (2), phant (3).' }),

  makeMCQ({ id:'g1eng-pho-057', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "sun" have?',
    options:['One','Two','Three','Four'],
    answer:'One',
    hint:'Clap as you say it. Sun — just one! ☀️',
    explanation:'Well done! <b>Sun</b> has <b>one</b> syllable.' }),

  makeMCQ({ id:'g1eng-pho-058', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "teacher" have?',
    options:['Two','One','Three','Four'],
    answer:'Two',
    hint:'Clap as you say it: teach-er. How many claps? 👩‍🏫',
    explanation:'Well done! <b>Teach-er</b> has <b>two</b> syllables: teach (1), er (2).' }),

  makeMCQ({ id:'g1eng-pho-059', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "butterfly" have?',
    options:['Three','Two','One','Four'],
    answer:'Three',
    hint:'Clap as you say it: but-ter-fly. How many claps? 🦋',
    explanation:'Well done! <b>But-ter-fly</b> has <b>three</b> syllables: but (1), ter (2), fly (3).' }),

  makeMCQ({ id:'g1eng-pho-060', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "flower" have?',
    options:['Two','One','Three','Four'],
    answer:'Two',
    hint:'Clap as you say it: flow-er. How many claps? 🌸',
    explanation:'Well done! <b>Flow-er</b> has <b>two</b> syllables: flow (1), er (2).' }),

  makeMCQ({ id:'g1eng-pho-061', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "school" have?',
    options:['One','Two','Three','Four'],
    answer:'One',
    hint:'Clap as you say it. School — just one clap! 🏫',
    explanation:'Well done! <b>School</b> has <b>one</b> syllable. Even though it has 6 letters, we say it as one beat.' }),

  makeMCQ({ id:'g1eng-pho-062', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "rabbit" have?',
    options:['Two','One','Three','Four'],
    answer:'Two',
    hint:'Clap as you say it: rab-bit. How many claps? 🐰',
    explanation:'Well done! <b>Rab-bit</b> has <b>two</b> syllables: rab (1), bit (2).' }),

  makeMCQ({ id:'g1eng-pho-063', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'Which word has TWO syllables?',
    options:['garden','cat','sun','hat'],
    answer:'garden',
    hint:'Clap each word. Which one has two beats? 🌻',
    explanation:'Well done! <b>Gar-den</b> has <b>two</b> syllables: gar (1), den (2). Cat, sun and hat each have only one.' }),

  makeMCQ({ id:'g1eng-pho-064', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "crocodile" have?',
    options:['Three','Two','One','Four'],
    answer:'Three',
    hint:'Clap as you say it: croc-o-dile. How many claps? 🐊',
    explanation:'Well done! <b>Croc-o-dile</b> has <b>three</b> syllables: croc (1), o (2), dile (3).' }),

  makeMCQ({ id:'g1eng-pho-065', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "pencil" have?',
    options:['Two','One','Three','Four'],
    answer:'Two',
    hint:'Clap as you say it: pen-cil. How many claps? ✏️',
    explanation:'Well done! <b>Pen-cil</b> has <b>two</b> syllables: pen (1), cil (2).' }),

  makeMCQ({ id:'g1eng-pho-066', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'Which word has ONE syllable?',
    options:['fish','banana','apple','teacher'],
    answer:'fish',
    hint:'Clap each word. Which one has only one beat? 🐟',
    explanation:'Well done! <b>Fish</b> has <b>one</b> syllable — just one clap: fish.' }),

  makeMCQ({ id:'g1eng-pho-067', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "umbrella" have?',
    options:['Three','Two','One','Four'],
    answer:'Three',
    hint:'Clap as you say it: um-brel-la. How many claps? ☂️',
    explanation:'Well done! <b>Um-brel-la</b> has <b>three</b> syllables: um (1), brel (2), la (3).' }),

  makeMCQ({ id:'g1eng-pho-068', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "book" have?',
    options:['One','Two','Three','Four'],
    answer:'One',
    hint:'Clap as you say it. Book — just one! 📚',
    explanation:'Well done! <b>Book</b> has <b>one</b> syllable.' }),

  makeMCQ({ id:'g1eng-pho-069', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "family" have?',
    options:['Three','Two','One','Four'],
    answer:'Three',
    hint:'Clap as you say it: fam-i-ly. How many claps? 👨‍👩‍👧',
    explanation:'Well done! <b>Fam-i-ly</b> has <b>three</b> syllables: fam (1), i (2), ly (3).' }),

  makeMCQ({ id:'g1eng-pho-070', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'Which word has THREE syllables?',
    options:['holiday','cat','flower','dog'],
    answer:'holiday',
    hint:'Clap each word. Which one has three beats? 🏖️',
    explanation:'Well done! <b>Hol-i-day</b> has <b>three</b> syllables: hol (1), i (2), day (3).' }),

  makeMCQ({ id:'g1eng-pho-071', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "window" have?',
    options:['Two','One','Three','Four'],
    answer:'Two',
    hint:'Clap as you say it: win-dow. How many claps? 🪟',
    explanation:'Well done! <b>Win-dow</b> has <b>two</b> syllables: win (1), dow (2).' }),

  makeMCQ({ id:'g1eng-pho-072', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "bird" have?',
    options:['One','Two','Three','Four'],
    answer:'One',
    hint:'Clap as you say it. Bird — just one! 🐦',
    explanation:'Well done! <b>Bird</b> has <b>one</b> syllable.' }),

  makeMCQ({ id:'g1eng-pho-073', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "watermelon" have?',
    options:['Four','Three','Two','Five'],
    answer:'Four',
    hint:'Clap as you say it: wa-ter-mel-on. How many claps? 🍉',
    explanation:'Well done! <b>Wa-ter-mel-on</b> has <b>four</b> syllables: wa (1), ter (2), mel (3), on (4).' }),

  makeMCQ({ id:'g1eng-pho-074', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'How many syllables does "rainbow" have?',
    options:['Two','One','Three','Four'],
    answer:'Two',
    hint:'Clap as you say it: rain-bow. How many claps? 🌈',
    explanation:'Well done! <b>Rain-bow</b> has <b>two</b> syllables: rain (1), bow (2).' }),

  makeMCQ({ id:'g1eng-pho-075', chapterId:'g1eng-phonics', difficulty:1, subsection:'syllables',
    question:'Which word has TWO syllables?',
    options:['happy','cat','run','fish'],
    answer:'happy',
    hint:'Clap each word. Which one has two beats? 😊',
    explanation:'Well done! <b>Hap-py</b> has <b>two</b> syllables: hap (1), py (2). Cat, run and fish each have one.' })

);
})();
