'use strict';
// Grade 3 Science — Chapter: Living and Non-Living Things
// IDs: g3sc-liv-001 …

(function () {

STATIC_QUESTIONS.push(

  // ── classifying ─────────────────────────────────────────────────────────────

  makeMCQ({ id:'g3sc-liv-001', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is a living thing?',
    options:['cat','rock','pen','spoon'],
    answer:'cat',
    hint:'A living thing can move, grow and breathe on its own.',
    explanation:'A <b>cat</b> is a living thing. It breathes, grows, eats and moves on its own. Rocks, pens and spoons are non-living — they cannot do these things.' }),

  makeMCQ({ id:'g3sc-liv-002', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is NOT a living thing?',
    options:['shoe','bird','flower','worm'],
    answer:'shoe',
    hint:'A non-living thing was never alive and cannot grow or breathe.',
    explanation:'A <b>shoe</b> is NOT a living thing. It cannot breathe, grow or move on its own. Birds, flowers and worms are all living things.' }),

  makeMCQ({ id:'g3sc-liv-003', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is a living thing?',
    options:['tree','stone','cup','table'],
    answer:'tree',
    hint:'This grows from a seed and needs water and sunlight.',
    explanation:'A <b>tree</b> is a living thing. It grows, takes in water and makes food using sunlight. Stones, cups and tables are non-living.' }),

  makeMCQ({ id:'g3sc-liv-004', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is NOT living?',
    options:['window','fish','rose','bee'],
    answer:'window',
    hint:'Can a window breathe, grow or move on its own?',
    explanation:'A <b>window</b> is not a living thing. It cannot breathe, grow or reproduce. Fish, roses and bees are all living things.' }),

  makeMCQ({ id:'g3sc-liv-005', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Is a butterfly living or non-living?',
    options:['Living','Non-living','It depends','Not sure'],
    answer:'Living',
    hint:'Does it grow, breathe and move on its own?',
    explanation:'A butterfly is <b>living</b>. It breathes, grows from a caterpillar, eats nectar and can reproduce (make more butterflies).' }),

  makeMCQ({ id:'g3sc-liv-006', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Is a chair living or non-living?',
    options:['Non-living','Living','Both','Neither'],
    answer:'Non-living',
    hint:'Can a chair breathe, eat or grow?',
    explanation:'A chair is <b>non-living</b>. It cannot breathe, eat, grow or move by itself. It is made by humans from wood or plastic.' }),

  makeMCQ({ id:'g3sc-liv-007', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which group contains ONLY living things?',
    options:['dog, grass, frog','car, dog, tree','pen, frog, grass','stone, bird, flower'],
    answer:'dog, grass, frog',
    hint:'Look for the group where every single thing is alive.',
    explanation:'<b>Dog, grass and frog</b> are all living things — they grow, breathe and reproduce. Cars, pens and stones are non-living.' }),

  makeMCQ({ id:'g3sc-liv-008', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which group contains ONLY non-living things?',
    options:['brick, table, glass','cat, brick, table','rose, brick, table','ant, glass, brick'],
    answer:'brick, table, glass',
    hint:'Look for the group where nothing is alive.',
    explanation:'<b>Brick, table and glass</b> are all non-living. They cannot breathe, grow or reproduce. Cats, roses and ants are living things.' }),

  makeMCQ({ id:'g3sc-liv-009', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'A mushroom grows in the garden. Is it living or non-living?',
    options:['Living','Non-living','It is a plant, not living','Not sure'],
    answer:'Living',
    hint:'Does a mushroom grow and reproduce?',
    explanation:'A mushroom is <b>living</b>. It grows, reproduces by making spores and gets nutrition from the soil. All fungi (including mushrooms) are living things.' }),

  makeMCQ({ id:'g3sc-liv-010', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'A dead leaf on the ground — is it living or non-living?',
    options:['Non-living (it was once living)','Living','Both','Neither'],
    answer:'Non-living (it was once living)',
    hint:'A dead leaf can no longer grow, breathe or carry out life processes.',
    explanation:'A dead leaf is <b>non-living</b> now. It was once part of a living tree, but after it fell and died, it can no longer carry out life processes. Dead things are classified as non-living.' }),

  makeMCQ({ id:'g3sc-liv-011', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is a living thing?',
    options:['lizard','cloud','sand','plastic bag'],
    answer:'lizard',
    hint:'One of these breathes, grows and eats insects.',
    explanation:'A <b>lizard</b> is a living thing. It breathes, grows, eats and can make baby lizards. Clouds, sand and plastic bags are all non-living.' }),

  makeMCQ({ id:'g3sc-liv-012', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is NOT a living thing?',
    options:['bicycle','rabbit','carrot','ant'],
    answer:'bicycle',
    hint:'This is made of metal and cannot move unless someone pedals it.',
    explanation:'A <b>bicycle</b> is NOT a living thing. It cannot breathe, grow or move on its own. Rabbits, carrots and ants are all living things.' }),

  makeMCQ({ id:'g3sc-liv-013', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Fire grows and moves. Does that make it a living thing?',
    options:['No — it cannot breathe, eat or reproduce like living things','Yes — it moves and grows','Yes — it needs oxygen','Not sure'],
    answer:'No — it cannot breathe, eat or reproduce like living things',
    hint:'Living things must do ALL life processes, not just one or two.',
    explanation:'Fire is <b>non-living</b>. Although it moves and grows, it cannot breathe, eat food or reproduce by itself. A living thing must carry out all the basic life processes.' }),

  makeMCQ({ id:'g3sc-liv-014', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is a living thing?',
    options:['mushroom','soil','stone','bottle'],
    answer:'mushroom',
    hint:'This grows, feeds and reproduces in damp places.',
    explanation:'A <b>mushroom</b> is a living thing. It grows, feeds on dead matter and reproduces using spores. Soil, stones and bottles are non-living.' }),

  makeMCQ({ id:'g3sc-liv-015', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Asha finds a feather on the ground. Is the feather living or non-living?',
    options:['Non-living (it fell from a bird)','Living','Both','Depends on the feather'],
    answer:'Non-living (it fell from a bird)',
    hint:'A feather by itself cannot grow, breathe or feed.',
    explanation:'A feather on the ground is <b>non-living</b>. It was once part of a living bird, but on its own it cannot carry out any life processes.' }),

  makeMCQ({ id:'g3sc-liv-016', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is living?',
    options:['earthworm','pebble','rubber','cardboard'],
    answer:'earthworm',
    hint:'This wiggles through the soil, eats decaying material and can reproduce.',
    explanation:'An <b>earthworm</b> is living. It moves, eats, breathes and reproduces. Pebbles, rubber and cardboard are non-living.' }),

  makeMCQ({ id:'g3sc-liv-017', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is non-living?',
    options:['candle','rose bush','dragonfly','mango tree'],
    answer:'candle',
    hint:'This is made of wax and cannot grow or breathe.',
    explanation:'A <b>candle</b> is non-living. It is made of wax and cannot breathe, grow or reproduce. Rose bushes, dragonflies and mango trees are all living.' }),

  makeMCQ({ id:'g3sc-liv-018', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is a living thing?',
    options:['coral reef','gravel','plastic','metal pipe'],
    answer:'coral reef',
    hint:'This is made by tiny sea animals called coral polyps and is actually alive.',
    explanation:'A <b>coral reef</b> is living — it is made up of thousands of tiny living coral animals. Gravel, plastic and metal pipes are non-living.' }),

  makeMCQ({ id:'g3sc-liv-019', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Is water a living thing?',
    options:['No — water is non-living','Yes — fish live in it','Yes — it flows and moves','Yes — plants need it'],
    answer:'No — water is non-living',
    hint:'Does water breathe, grow or reproduce?',
    explanation:'<b>Water is non-living</b>. Although living things need water to survive, water itself cannot breathe, grow, eat or reproduce. It is a non-living substance.' }),

  makeMCQ({ id:'g3sc-liv-020', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is a living thing?',
    options:['coconut tree','rock','cloud','plastic cup'],
    answer:'coconut tree',
    hint:'This grows from a seed, has roots and makes coconuts.',
    explanation:'A <b>coconut tree</b> is a living thing. It grows from a coconut seed, takes in water and sunlight, and produces coconuts. Rocks, clouds and plastic cups are non-living.' }),

  makeMCQ({ id:'g3sc-liv-021', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Is sunlight living or non-living?',
    options:['Non-living','Living because it helps plants grow','Living because it gives warmth','Both'],
    answer:'Non-living',
    hint:'Sunlight is a form of energy, not an organism.',
    explanation:'<b>Sunlight is non-living</b>. It is a form of energy from the sun. Although living things need sunlight to grow, light itself is not alive.' }),

  makeMCQ({ id:'g3sc-liv-022', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which of these is NOT a living thing?',
    options:['shadow','grass','bee','spider'],
    answer:'shadow',
    hint:'A shadow is just the absence of light — it has no body, cannot breathe or grow.',
    explanation:'A <b>shadow</b> is not a living thing. It is simply an area where light is blocked. Grass, bees and spiders are all living things.' }),

  makeMCQ({ id:'g3sc-liv-023', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Priya sees a snail moving slowly in the garden. Is the snail living or non-living?',
    options:['Living','Non-living','It is only a shell, so non-living','Not sure'],
    answer:'Living',
    hint:'It moves on its own and leaves a trail of slime.',
    explanation:'A snail is <b>living</b>. It moves, eats, breathes and can reproduce. Its shell is part of its body.' }),

  makeMCQ({ id:'g3sc-liv-024', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'Which TWO things in this list are living?',
    options:['frog and grass','car and frog','grass and stone','stone and car'],
    answer:'frog and grass',
    hint:'Look for things that grow and breathe on their own.',
    explanation:'<b>Frog and grass</b> are both living things — they grow, breathe and reproduce. Cars and stones are non-living.' }),

  makeMCQ({ id:'g3sc-liv-025', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'classifying',
    question:'What do we call things that were never alive, such as stones and chairs?',
    options:['Non-living things','Dead things','Plants','Animals'],
    answer:'Non-living things',
    hint:'This is the opposite of living things.',
    explanation:'Things that were never alive are called <b>non-living things</b>. Stones, chairs, water and air are examples of non-living things.' }),

  // ── characteristics_living ──────────────────────────────────────────────────

  makeMCQ({ id:'g3sc-liv-026', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Living things ___.',
    options:['grow and need food','cannot move','are always big','do not breathe'],
    answer:'grow and need food',
    hint:'Think about what ALL living things have in common.',
    explanation:'<b>Living things grow and need food</b>. All living things — plants, animals and people — grow bigger over time and need food (or nutrients) to survive.' }),

  makeMCQ({ id:'g3sc-liv-027', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which is a characteristic of living things?',
    options:['They breathe','They are made of metal','They cannot grow','They do not need water'],
    answer:'They breathe',
    hint:'All living things need to take in air to survive.',
    explanation:'All living things <b>breathe</b> — they take in air (oxygen) to get energy. Even plants breathe, though they also make their own food using sunlight.' }),

  makeMCQ({ id:'g3sc-liv-028', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Do living things grow?',
    options:['Yes — all living things grow','No — only animals grow','No — only plants grow','Only humans grow'],
    answer:'Yes — all living things grow',
    hint:'Think about how a baby grows into an adult, or a seed grows into a tree.',
    explanation:'<b>Yes, all living things grow</b>. Animals grow from young to adult, plants grow from seeds, and even tiny living things like bacteria grow and get bigger.' }),

  makeMCQ({ id:'g3sc-liv-029', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which of these do ALL living things need to survive?',
    options:['Food','Cars','Computers','Television'],
    answer:'Food',
    hint:'All living things need energy to live. Where do they get it?',
    explanation:'All living things need <b>food</b> to get the energy they need to live, grow and move. Plants make their own food from sunlight; animals eat plants or other animals.' }),

  makeMCQ({ id:'g3sc-liv-030', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Can living things reproduce (make more of themselves)?',
    options:['Yes — all living things can reproduce','No — only animals can reproduce','No — only plants can reproduce','Non-living things reproduce too'],
    answer:'Yes — all living things can reproduce',
    hint:'Cats have kittens, trees make seeds, people have babies — what do they all do?',
    explanation:'<b>Yes, all living things reproduce</b>. This means they can make new individuals of their own kind — cats have kittens, flowers produce seeds, and people have children.' }),

  makeMCQ({ id:'g3sc-liv-031', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'A stone does not grow. Does this mean it is non-living?',
    options:['Yes — non-living things do not grow','No — some non-living things do grow','Stones grow very slowly','Stones are living'],
    answer:'Yes — non-living things do not grow',
    hint:'Growth is a characteristic of living things only.',
    explanation:'<b>Yes</b>, a stone is non-living partly because it does not grow. Non-living things do not grow by themselves — only living things grow.' }),

  makeMCQ({ id:'g3sc-liv-032', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which of these is NOT a characteristic of living things?',
    options:['Made of glass','They grow','They breathe','They reproduce'],
    answer:'Made of glass',
    hint:'Only non-living things are made of glass.',
    explanation:'Being <b>made of glass</b> is NOT a characteristic of living things. Growing, breathing and reproducing are all characteristics of living things. Living things are made of cells, not glass.' }),

  makeMCQ({ id:'g3sc-liv-033', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'A chick grows into a hen. This shows that living things ___.',
    options:['grow and change','cannot change','stay the same size','do not need food'],
    answer:'grow and change',
    hint:'The chick changed from small to large as it grew.',
    explanation:'A chick growing into a hen shows that living things <b>grow and change</b> over time. This is one of the most important characteristics of living things.' }),

  makeMCQ({ id:'g3sc-liv-034', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Plants are living things. Which characteristic do they share with animals?',
    options:['They both need food and water to survive','They both move around','They both eat other organisms','They both have legs'],
    answer:'They both need food and water to survive',
    hint:'All living things need nutrients and water.',
    explanation:'Plants and animals both <b>need food (nutrients) and water</b> to survive. Plants make their own food from sunlight, while animals eat food. But all living things need nutrients and water.' }),

  makeMCQ({ id:'g3sc-liv-035', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Do all living things need water?',
    options:['Yes — water is essential for all living things','No — only animals need water','No — only plants need water','Only humans need water'],
    answer:'Yes — water is essential for all living things',
    hint:'Think about what happens to plants when they are not watered, or animals when they cannot drink.',
    explanation:'<b>Yes, all living things need water</b>. Water is essential for all life on Earth — plants, animals, humans and even tiny living things like bacteria need water to survive.' }),

  makeMCQ({ id:'g3sc-liv-036', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which characteristic explains why a cat can have kittens?',
    options:['Reproduction','Growth','Breathing','Eating'],
    answer:'Reproduction',
    hint:'Making new young ones is called this.',
    explanation:'<b>Reproduction</b> is the characteristic that allows a cat to have kittens. Reproduction means producing offspring — young ones of the same kind.' }),

  makeMCQ({ id:'g3sc-liv-037', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Why do living things need food?',
    options:['To get energy to grow, move and live','To make their body heavier','Just because they are alive','To make water'],
    answer:'To get energy to grow, move and live',
    hint:'Food gives living things the power they need.',
    explanation:'Living things need food to <b>get energy</b>. This energy is used for growing, moving, breathing and carrying out all life processes.' }),

  makeMCQ({ id:'g3sc-liv-038', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'If a living thing stops breathing, what happens?',
    options:['It will die','It becomes a plant','It grows faster','Nothing happens'],
    answer:'It will die',
    hint:'Breathing is essential for life.',
    explanation:'If a living thing <b>stops breathing</b>, it will die. Breathing brings oxygen into the body, which is needed to produce energy. Without oxygen, life processes stop.' }),

  makeMCQ({ id:'g3sc-liv-039', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'A seed grows into a large tree over many years. Which characteristic does this show?',
    options:['Growth','Reproduction','Breathing','Eating'],
    answer:'Growth',
    hint:'The tree gets bigger and bigger over time.',
    explanation:'A seed growing into a large tree shows the characteristic of <b>growth</b>. Living things grow over time — they get bigger and develop.' }),

  makeMCQ({ id:'g3sc-liv-040', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which of these characteristics do plants and animals BOTH have?',
    options:['They both grow','They both walk around','They both eat insects','They both have fur'],
    answer:'They both grow',
    hint:'Both plants and animals start small and get bigger.',
    explanation:'Plants and animals <b>both grow</b>. This is a characteristic shared by all living things. Plants grow from seeds; animals grow from eggs or are born small and grow bigger.' }),

  makeMCQ({ id:'g3sc-liv-041', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which statement about living things is TRUE?',
    options:['All living things need oxygen to breathe','All living things are made of metal','All living things can fly','All living things live in water'],
    answer:'All living things need oxygen to breathe',
    hint:'Breathing is one of the key characteristics of all living things.',
    explanation:'It is <b>true</b> that all living things need oxygen. Even plants breathe — they take in oxygen at night and release it during the day when making food.' }),

  makeMCQ({ id:'g3sc-liv-042', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'What do we call it when a living thing produces young ones like itself?',
    options:['Reproduction','Growth','Nutrition','Breathing'],
    answer:'Reproduction',
    hint:'This word means making more of your own kind.',
    explanation:'<b>Reproduction</b> is when a living thing produces young ones of its own kind. For example, a dog has puppies, a bird lays eggs that hatch into chicks.' }),

  makeMCQ({ id:'g3sc-liv-043', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Why is breathing important for living things?',
    options:['It provides oxygen to make energy','It helps them move faster','It gives them a nice smell','It makes them grow taller'],
    answer:'It provides oxygen to make energy',
    hint:'Think about what oxygen is used for inside the body.',
    explanation:'Breathing is important because it brings <b>oxygen</b> into the body. Oxygen is used to turn food into energy — energy that living things need to grow, move and stay alive.' }),

  makeMCQ({ id:'g3sc-liv-044', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which of the following best describes a living thing?',
    options:['It grows, breathes, needs food and can reproduce','It is very colourful','It is always moving very fast','It is made of plastic'],
    answer:'It grows, breathes, needs food and can reproduce',
    hint:'Living things share several important characteristics.',
    explanation:'A living thing <b>grows, breathes, needs food and can reproduce</b>. These are the basic characteristics that all living things share.' }),

  makeMCQ({ id:'g3sc-liv-045', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'A puppy grows into a large dog. What characteristic of living things does this show?',
    options:['Growth','Breathing','Reproduction','Eating'],
    answer:'Growth',
    hint:'The puppy gets bigger and bigger over time.',
    explanation:'The puppy growing into a large dog shows the characteristic of <b>growth</b>. All living things start small and grow bigger over time.' }),

  makeMCQ({ id:'g3sc-liv-046', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Can a rock reproduce (make more rocks)?',
    options:['No — only living things can reproduce','Yes — rocks can split into smaller rocks','Yes — rocks grow in the ground','Rocks reproduce very slowly'],
    answer:'No — only living things can reproduce',
    hint:'Reproduction means making new living things of the same kind.',
    explanation:'<b>No</b>, a rock cannot reproduce. Rocks may break into pieces, but this is NOT reproduction. Only living things can produce new living things of their own kind.' }),

  makeMCQ({ id:'g3sc-liv-047', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'What do living things do with food they eat or make?',
    options:['They use it for energy to grow and move','They throw it away','They turn it into water','They give it to non-living things'],
    answer:'They use it for energy to grow and move',
    hint:'Food gives living things the power to do things.',
    explanation:'Living things <b>use food for energy</b>. This energy powers everything they do — growing, moving, breathing and staying healthy.' }),

  makeMCQ({ id:'g3sc-liv-048', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which of these is a key difference between living and non-living things?',
    options:['Living things grow; non-living things do not','Living things are bigger; non-living things are smaller','Living things are always green; non-living things are not','Living things cannot move; non-living things can'],
    answer:'Living things grow; non-living things do not',
    hint:'Only one of these groups grows from a small size to a bigger size on its own.',
    explanation:'A key difference is that <b>living things grow</b> on their own, while non-living things do not grow (they can only be made bigger or smaller by outside forces). A rock stays the same size; a plant grows bigger every week.' }),

  makeMCQ({ id:'g3sc-liv-049', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'A hen lays eggs that hatch into chicks. Which characteristic of living things does this show?',
    options:['Reproduction','Growth','Breathing','Feeding'],
    answer:'Reproduction',
    hint:'The hen is producing new young ones.',
    explanation:'A hen laying eggs shows <b>reproduction</b> — the ability to produce new living things of the same kind. The eggs hatch into chicks, which are new young hens and roosters.' }),

  makeMCQ({ id:'g3sc-liv-050', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'characteristics_living',
    question:'Which statement is FALSE about living things?',
    options:['They do not need water to survive','They grow over time','They breathe','They can reproduce'],
    answer:'They do not need water to survive',
    hint:'Every living thing on Earth needs water.',
    explanation:'The statement "<b>They do not need water to survive</b>" is FALSE. ALL living things need water to survive — without water, living things die.' }),

  // ── variety_organisms ───────────────────────────────────────────────────────

  makeMCQ({ id:'g3sc-liv-051', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is a plant?',
    options:['rose','frog','fish','ant'],
    answer:'rose',
    hint:'This grows in a garden and has petals.',
    explanation:'A <b>rose</b> is a plant. It has roots, a stem, leaves and flowers. Frogs, fish and ants are all animals.' }),

  makeMCQ({ id:'g3sc-liv-052', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is an animal?',
    options:['parrot','palm tree','cactus','grass'],
    answer:'parrot',
    hint:'This can fly and makes a loud squawking sound.',
    explanation:'A <b>parrot</b> is an animal — it is a bird. Palm trees, cacti and grass are all plants.' }),

  makeMCQ({ id:'g3sc-liv-053', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these animals lives in water?',
    options:['fish','cat','lizard','hen'],
    answer:'fish',
    hint:'This animal swims and breathes through gills.',
    explanation:'<b>Fish</b> are animals that live in water. They breathe through gills, which allow them to absorb oxygen from the water.' }),

  makeMCQ({ id:'g3sc-liv-054', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is a plant you might see in a Mauritius garden?',
    options:['bougainvillea','dolphin','monkey','hen'],
    answer:'bougainvillea',
    hint:'This is a colourful flowering plant very common in Mauritius.',
    explanation:'<b>Bougainvillea</b> is a beautiful flowering plant very common in Mauritius. It has bright pink, orange or red flowers. Dolphins, monkeys and hens are animals, not plants.' }),

  makeMCQ({ id:'g3sc-liv-055', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'There are many different types of living things around us. These include ___.',
    options:['plants and animals','only trees and flowers','only cats and dogs','only birds and fish'],
    answer:'plants and animals',
    hint:'Living things include many kinds, not just one type.',
    explanation:'Living things around us include a huge variety of <b>plants and animals</b> — from tiny insects to large trees, from small flowers to enormous whales.' }),

  makeMCQ({ id:'g3sc-liv-056', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is a tree?',
    options:['mango tree','sparrow','butterfly','snail'],
    answer:'mango tree',
    hint:'This grows tall and produces a sweet tropical fruit.',
    explanation:'A <b>mango tree</b> is a plant — specifically a tree. It grows tall, has leaves, and produces mangoes. Sparrows, butterflies and snails are animals.' }),

  makeMCQ({ id:'g3sc-liv-057', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these lives on land AND in water?',
    options:['frog','sparrow','rose','coconut tree'],
    answer:'frog',
    hint:'This animal is born in water and grows to live on land too.',
    explanation:'A <b>frog</b> lives in both water and on land. Frogs start life as tadpoles in water, then grow legs and move onto land — though they always need to stay near water.' }),

  makeMCQ({ id:'g3sc-liv-058', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is an insect?',
    options:['butterfly','goldfish','parrot','rose'],
    answer:'butterfly',
    hint:'Insects have 6 legs and a body divided into 3 parts.',
    explanation:'A <b>butterfly</b> is an insect. Insects have 6 legs, 3 body parts (head, thorax, abdomen) and most have wings. Goldfish are fish, parrots are birds, and roses are plants.' }),

  makeMCQ({ id:'g3sc-liv-059', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Why is there such a wide variety of plants and animals on Earth?',
    options:['Different living things are suited to different places and conditions','There is only one type of each animal','All animals look the same','Plants and animals are the same thing'],
    answer:'Different living things are suited to different places and conditions',
    hint:'A cactus lives in the desert; a water lily lives in a pond — why?',
    explanation:'There is a wide variety of living things because <b>different organisms are suited to different environments</b>. Desert animals can survive without much water; deep sea fish can live in the dark. Each type is perfectly suited to where it lives.' }),

  makeMCQ({ id:'g3sc-liv-060', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is a flower?',
    options:['hibiscus','crow','crab','mongoose'],
    answer:'hibiscus',
    hint:'This is the national flower of Malaysia and very common in Mauritius.',
    explanation:'<b>Hibiscus</b> is a flower — a type of plant. It is commonly seen in Mauritius. Crows are birds, crabs are animals and mongooses are small mammals.' }),

  makeMCQ({ id:'g3sc-liv-061', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these animals can fly?',
    options:['bat','shark','elephant','snail'],
    answer:'bat',
    hint:'This nocturnal mammal uses wings to fly at night.',
    explanation:'A <b>bat</b> is the only mammal that can truly fly. Bats have wings and fly at night, eating insects or fruit. Sharks swim, elephants walk and snails crawl.' }),

  makeMCQ({ id:'g3sc-liv-062', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'What grows from a seed?',
    options:['a plant','an animal','a stone','a cloud'],
    answer:'a plant',
    hint:'Seeds contain the start of a new organism.',
    explanation:'<b>A plant</b> grows from a seed. When a seed is planted in soil and given water and sunlight, it germinates (sprouts) and grows into a plant.' }),

  makeMCQ({ id:'g3sc-liv-063', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is a mammal?',
    options:['rabbit','parrot','goldfish','ant'],
    answer:'rabbit',
    hint:'Mammals have fur and feed their babies with milk.',
    explanation:'A <b>rabbit</b> is a mammal. Mammals have fur or hair, breathe air, give birth to live young and feed them milk. Parrots are birds, goldfish are fish, and ants are insects.' }),

  makeMCQ({ id:'g3sc-liv-064', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is a vegetable?',
    options:['carrot','sparrow','lizard','butterfly'],
    answer:'carrot',
    hint:'This orange vegetable grows underground.',
    explanation:'A <b>carrot</b> is a vegetable — a type of plant we eat. It grows underground. Sparrows, lizards and butterflies are animals.' }),

  makeMCQ({ id:'g3sc-liv-065', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'How many legs does an insect have?',
    options:['6','4','8','10'],
    answer:'6',
    hint:'Insects always have this number of legs.',
    explanation:'All insects have <b>6 legs</b>. This is one way we recognise an insect — 6 legs, 3 body parts and usually wings. Spiders have 8 legs and are not insects.' }),

  makeMCQ({ id:'g3sc-liv-066', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these plants does NOT grow in Mauritius?',
    options:['cactus from the Sahara','sugarcane','bougainvillea','mango tree'],
    answer:'cactus from the Sahara',
    hint:'One of these is from a very hot, dry desert environment.',
    explanation:'A <b>cactus from the Sahara Desert</b> is specially adapted to very dry, hot conditions that are different from Mauritius. Sugarcane, bougainvillea and mango trees all grow well in Mauritius.' }),

  makeMCQ({ id:'g3sc-liv-067', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these animals lives in the sea?',
    options:['dolphin','rabbit','pigeon','lizard'],
    answer:'dolphin',
    hint:'This mammal lives in the ocean and is very intelligent.',
    explanation:'A <b>dolphin</b> lives in the sea. Although it is a mammal (it breathes air and feeds its calves milk), it lives in the ocean and swims using its tail.' }),

  makeMCQ({ id:'g3sc-liv-068', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'What do we call a scientist who studies plants?',
    options:['Botanist','Zoologist','Astronomer','Geologist'],
    answer:'Botanist',
    hint:'The science of plants is called botany.',
    explanation:'A <b>botanist</b> is a scientist who studies plants. They learn about how plants grow, reproduce and survive. Zoologists study animals, astronomers study space and geologists study rocks.' }),

  makeMCQ({ id:'g3sc-liv-069', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is a type of bird?',
    options:['pink pigeon','gecko','mongoose','sea urchin'],
    answer:'pink pigeon',
    hint:'This is a famous bird found only on the island of Mauritius.',
    explanation:'The <b>pink pigeon</b> is a bird that is endemic to Mauritius — found nowhere else on Earth. It was once nearly extinct but conservation programmes have helped it survive. Geckos are reptiles, mongooses are mammals, sea urchins are sea animals.' }),

  makeMCQ({ id:'g3sc-liv-070', chapterId:'g3sc-living-nonliving', difficulty:1, subsection:'variety_organisms',
    question:'Which of these is a fruit?',
    options:['papaya','crab','gecko','dragonfly'],
    answer:'papaya',
    hint:'This is a sweet, orange tropical fruit that grows on a tree.',
    explanation:'<b>Papaya</b> is a fruit — it comes from the papaya tree, a plant. Crabs are sea animals, geckos are reptiles and dragonflies are insects.' })

);

})();
