'use strict';
// Grade 3 Science — Chapter: Materials in our Environment
// IDs: g3sc-mat-001 …

(function () {

STATIC_QUESTIONS.push(

  // ── types_materials ─────────────────────────────────────────────────────────

  makeMCQ({ id:'g3sc-mat-001', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'A chair is often made of ___.',
    options:['wood','water','air','glass'],
    answer:'wood',
    hint:'Think about what most furniture in your home is made from.',
    explanation:'Chairs are often made of <b>wood</b>. Wood is a strong and common material used to make furniture like chairs, tables and shelves.' }),

  makeMCQ({ id:'g3sc-mat-002', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material do we use to make a window?',
    options:['glass','paper','cloth','stone'],
    answer:'glass',
    hint:'You can see through this material.',
    explanation:'Windows are made of <b>glass</b>. Glass is transparent, meaning we can see through it, and it lets light into our homes.' }),

  makeMCQ({ id:'g3sc-mat-003', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'What material is a school bag usually made from?',
    options:['cloth or leather','glass','paper','stone'],
    answer:'cloth or leather',
    hint:'School bags need to be strong and flexible.',
    explanation:'School bags are usually made of <b>cloth or leather</b>. These materials are strong, flexible and can carry heavy books without tearing.' }),

  makeMCQ({ id:'g3sc-mat-004', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material is used to make a book?',
    options:['paper','plastic','metal','stone'],
    answer:'paper',
    hint:'You write and read on this material.',
    explanation:'Books are made of <b>paper</b>. Paper is a thin, light material that we can write and print on. It comes from trees.' }),

  makeMCQ({ id:'g3sc-mat-005', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'What is a plastic bottle made from?',
    options:['plastic','wood','glass','paper'],
    answer:'plastic',
    hint:'This material can be moulded into any shape and is very light.',
    explanation:'Plastic bottles are made from <b>plastic</b>. Plastic is a man-made material that is light, waterproof and can be shaped into bottles, bags and many other objects.' }),

  makeMCQ({ id:'g3sc-mat-006', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material is used to make a drinking glass?',
    options:['glass','wood','cloth','paper'],
    answer:'glass',
    hint:'This material is transparent and does not absorb liquids.',
    explanation:'A drinking glass is made of <b>glass</b>. Glass does not absorb liquids and we can see through it, making it ideal for drinking glasses and cups.' }),

  makeMCQ({ id:'g3sc-mat-007', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'What material is a wooden pencil made from?',
    options:['wood','metal','plastic','glass'],
    answer:'wood',
    hint:'This pencil is made from the same material as trees.',
    explanation:'A wooden pencil is made from <b>wood</b>. The outer part of a pencil is wood, and inside is a graphite (soft black carbon) core for writing.' }),

  makeMCQ({ id:'g3sc-mat-008', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material is used to make a newspaper?',
    options:['paper','cloth','plastic','glass'],
    answer:'paper',
    hint:'You read the news on this flat, light material.',
    explanation:'Newspapers are made of <b>paper</b>. Paper is perfect for printing text and pictures on, and it is cheap and light enough to carry easily.' }),

  makeMCQ({ id:'g3sc-mat-009', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material is used to make a T-shirt?',
    options:['cloth (fabric)','glass','wood','plastic'],
    answer:'cloth (fabric)',
    hint:'Clothes are made from this soft, flexible material.',
    explanation:'T-shirts are made of <b>cloth (fabric)</b>. Cloth is soft, flexible and comfortable to wear. It can be made from cotton, polyester or other fibres.' }),

  makeMCQ({ id:'g3sc-mat-010', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'What material is a glass bottle made from?',
    options:['glass','paper','plastic','wood'],
    answer:'glass',
    hint:'You can see through this bottle.',
    explanation:'A glass bottle is made from <b>glass</b>. Glass bottles are used for juices and sauces because glass does not change the taste of liquids stored inside.' }),

  makeMCQ({ id:'g3sc-mat-011', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which of these objects is made of paper?',
    options:['book','spoon','cup','ruler'],
    answer:'book',
    hint:'You read this object.',
    explanation:'A <b>book</b> is made of paper. The pages of a book are thin sheets of paper bound together.' }),

  makeMCQ({ id:'g3sc-mat-012', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which of these objects is made of wood?',
    options:['wooden ruler','glass bottle','plastic bag','cotton T-shirt'],
    answer:'wooden ruler',
    hint:'This measuring tool is often made from a tree material.',
    explanation:'A <b>wooden ruler</b> is made of wood. Wood is a natural material that can be cut and shaped into rulers and other objects.' }),

  makeMCQ({ id:'g3sc-mat-013', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which of these objects is made of glass?',
    options:['drinking glass','wooden chair','paper book','cloth shirt'],
    answer:'drinking glass',
    hint:'You can see through this object when it holds water.',
    explanation:'A <b>drinking glass</b> is made of glass. Glass is transparent and waterproof, making it perfect for holding liquids.' }),

  makeMCQ({ id:'g3sc-mat-014', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Name the material used to make most water pipes.',
    options:['plastic or metal','paper','wood','glass'],
    answer:'plastic or metal',
    hint:'Water pipes need to be very strong and waterproof.',
    explanation:'Water pipes are made of <b>plastic or metal</b>. These materials are strong, waterproof and do not rust easily, making them ideal for carrying water.' }),

  makeMCQ({ id:'g3sc-mat-015', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'A cardboard box is made of ___.',
    options:['paper (thick cardboard)','plastic','glass','metal'],
    answer:'paper (thick cardboard)',
    hint:'Cardboard is a thick, stiff type of this everyday material.',
    explanation:'A cardboard box is made of thick <b>paper (cardboard)</b>. Cardboard is a heavier form of paper, strong enough to make boxes for packing and moving things.' }),

  makeMCQ({ id:'g3sc-mat-016', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material is used to make a plastic bag?',
    options:['plastic','paper','cloth','wood'],
    answer:'plastic',
    hint:'This material is light, waterproof and unfortunately causes a lot of pollution.',
    explanation:'Plastic bags are made of <b>plastic</b>. While plastic is light and waterproof, plastic bags are harmful to the environment because they do not break down easily.' }),

  makeMCQ({ id:'g3sc-mat-017', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material are most toys in a toy shop made from?',
    options:['plastic','glass','stone','paper'],
    answer:'plastic',
    hint:'This material is light, colourful and can be moulded into any shape.',
    explanation:'Most toys are made of <b>plastic</b>. Plastic is light, safe, colourful and can be shaped into almost any form — from cars to dolls to building blocks.' }),

  makeMCQ({ id:'g3sc-mat-018', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which of the four main materials is NOT usually used to make drinking containers?',
    options:['paper (for drinks, it must be coated)','glass','plastic','wood'],
    answer:'paper (for drinks, it must be coated)',
    hint:'Plain paper soaks up liquid and falls apart.',
    explanation:'Plain <b>paper</b> is not usually used for drinking containers — it absorbs liquid and gets soggy. Paper cups are only possible because they have a waterproof plastic lining inside. Glass, plastic and specially treated wood (bamboo) can hold liquids.' }),

  makeMCQ({ id:'g3sc-mat-019', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Ravi\'s umbrella keeps him dry in the rain. What material is it likely made from?',
    options:['cloth and metal or plastic','only paper','only wood','only glass'],
    answer:'cloth and metal or plastic',
    hint:'An umbrella needs a waterproof cover and a strong frame.',
    explanation:'An umbrella is made of <b>cloth (for the cover) and metal or plastic (for the frame and handle)</b>. The waterproof cloth keeps rain off, and the strong frame holds it open.' }),

  makeMCQ({ id:'g3sc-mat-020', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material comes from trees and is used to make furniture?',
    options:['wood','glass','plastic','paper'],
    answer:'wood',
    hint:'Trees are cut and shaped into planks to make this.',
    explanation:'<b>Wood</b> comes from trees. Trees are cut into planks and shaped into furniture like chairs, tables, cupboards and beds.' }),

  makeMCQ({ id:'g3sc-mat-021', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material is used to wrap sandwiches because it is light and flexible?',
    options:['plastic wrap or paper','glass','metal','stone'],
    answer:'plastic wrap or paper',
    hint:'You need something thin and flexible to wrap food.',
    explanation:'<b>Plastic wrap or paper</b> is used to wrap sandwiches because they are light, thin and flexible — easy to wrap around food.' }),

  makeMCQ({ id:'g3sc-mat-022', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which material is heavy, can break easily if dropped, and can be seen through?',
    options:['glass','cloth','paper','wood'],
    answer:'glass',
    hint:'This material is transparent but fragile.',
    explanation:'<b>Glass</b> is heavy, transparent (you can see through it) and fragile — it breaks easily if dropped. That is why we are careful with glass cups and windows.' }),

  makeMCQ({ id:'g3sc-mat-023', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'What material is a cotton school uniform made from?',
    options:['cloth (cotton fabric)','plastic','paper','glass'],
    answer:'cloth (cotton fabric)',
    hint:'Cotton is a natural fibre that comes from cotton plants.',
    explanation:'A cotton school uniform is made from <b>cloth (cotton fabric)</b>. Cotton is a natural material from cotton plants — it is soft, comfortable and lets the skin breathe.' }),

  makeMCQ({ id:'g3sc-mat-024', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Which of these objects is made of BOTH wood and glass?',
    options:['a window frame with glass panes','a plastic bag','a paper cup','a cloth shirt'],
    answer:'a window frame with glass panes',
    hint:'One part of a window holds the glass in place.',
    explanation:'A <b>window frame with glass panes</b> is made of both wood (the frame that holds it in place) and glass (the transparent pane). This uses the strength of wood and the transparency of glass.' }),

  makeMCQ({ id:'g3sc-mat-025', chapterId:'g3sc-materials', difficulty:1, subsection:'types_materials',
    question:'Name the four common materials we study in this chapter.',
    options:['wood, plastic, paper and glass','fire, water, earth and air','iron, gold, silver and bronze','cotton, wool, silk and nylon'],
    answer:'wood, plastic, paper and glass',
    hint:'These are the four everyday materials found in almost every home.',
    explanation:'The four common materials we study are <b>wood, plastic, paper and glass</b>. These are found all around us in everyday objects like furniture, bags, books and windows.' }),

  // ── properties_materials ────────────────────────────────────────────────────

  makeMCQ({ id:'g3sc-mat-026', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Paper is ___.',
    options:['light and can be torn','heavy and strong','waterproof','hard like metal'],
    answer:'light and can be torn',
    hint:'Think about what happens when you pull the edges of a sheet of paper.',
    explanation:'Paper is <b>light and can be torn</b>. It is thin, easy to carry and tears easily — which is why we do not make doors or windows out of paper.' }),

  makeMCQ({ id:'g3sc-mat-027', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which material is transparent (you can see through it)?',
    options:['glass','wood','cardboard','cloth'],
    answer:'glass',
    hint:'You can see outside through this material in a window.',
    explanation:'<b>Glass</b> is transparent — you can see through it clearly. This is why glass is used for windows and glasses (spectacles), because it lets light and our vision pass through.' }),

  makeMCQ({ id:'g3sc-mat-028', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which property of wood makes it good for making furniture?',
    options:['It is strong and can be shaped','It is transparent','It is waterproof','It is very light'],
    answer:'It is strong and can be shaped',
    hint:'Furniture needs to hold weight without breaking.',
    explanation:'Wood is <b>strong and can be shaped</b> into planks and cut into different forms. This makes it excellent for furniture like chairs, tables and cupboards that need to hold weight.' }),

  makeMCQ({ id:'g3sc-mat-029', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Why is plastic used to make water bottles?',
    options:['It is waterproof and light','It is transparent like glass','It is very heavy','It is made from trees'],
    answer:'It is waterproof and light',
    hint:'Plastic does not let water through and is easy to carry.',
    explanation:'Plastic is used for water bottles because it is <b>waterproof and light</b>. Water cannot pass through it, and it is easy to carry around all day without being too heavy.' }),

  makeMCQ({ id:'g3sc-mat-030', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'What happens to paper when it gets wet?',
    options:['It becomes soft and falls apart','It becomes harder','It becomes transparent','Nothing happens'],
    answer:'It becomes soft and falls apart',
    hint:'Try wetting a piece of paper and see what happens.',
    explanation:'When paper gets wet, it <b>becomes soft and falls apart</b>. Paper is not waterproof — water weakens its fibres and makes it soggy and easy to tear.' }),

  makeMCQ({ id:'g3sc-mat-031', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which of these materials is NOT transparent?',
    options:['wood','clean glass','clear plastic','water'],
    answer:'wood',
    hint:'Can you see through a wooden plank?',
    explanation:'<b>Wood</b> is NOT transparent — you cannot see through it. Clear glass, clean plastic and water are transparent (or at least translucent). Wood is opaque (you cannot see through it at all).' }),

  makeMCQ({ id:'g3sc-mat-032', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Why is glass used for windows?',
    options:['It is transparent and lets light in','It is very soft','It is waterproof like plastic','It is cheap and easy to break'],
    answer:'It is transparent and lets light in',
    hint:'Windows let you see outside and let sunlight into rooms.',
    explanation:'Glass is used for windows because it is <b>transparent</b> — light passes through it and we can see through it. This lets natural light into buildings while keeping wind and rain out.' }),

  makeMCQ({ id:'g3sc-mat-033', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which material is the HARDEST to break?',
    options:['glass compared to paper','paper compared to glass','cloth compared to glass','wood compared to glass'],
    answer:'glass compared to paper',
    hint:'One of these materials shatters; the other crumples.',
    explanation:'In a comparison, <b>glass is harder and stronger than paper</b> — but glass can shatter if dropped on a hard surface. Paper cannot shatter; it tears. Different materials have different strengths.' }),

  makeMCQ({ id:'g3sc-mat-034', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which property of cloth makes it good for making clothes?',
    options:['It is soft and flexible','It is transparent','It is as hard as stone','It is waterproof like glass'],
    answer:'It is soft and flexible',
    hint:'Clothes need to fit comfortably around the body.',
    explanation:'Cloth is <b>soft and flexible</b>, which makes it comfortable to wear. It can bend and stretch with our bodies — unlike glass or wood, which are rigid.' }),

  makeMCQ({ id:'g3sc-mat-035', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Why should you be careful when handling glass objects?',
    options:['Glass is fragile and can break into sharp pieces','Glass is too heavy to lift','Glass melts in the sun','Glass catches fire easily'],
    answer:'Glass is fragile and can break into sharp pieces',
    hint:'Broken glass is dangerous.',
    explanation:'You should be careful with glass because it is <b>fragile</b> — it can break into sharp pieces if dropped or hit. Sharp glass pieces can cut and hurt us.' }),

  makeMCQ({ id:'g3sc-mat-036', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which material soaks up water (absorbs it)?',
    options:['paper and cloth','glass','plastic','wood (not usually)'],
    answer:'paper and cloth',
    hint:'These materials get wet and hold water inside their fibres.',
    explanation:'<b>Paper and cloth</b> both soak up (absorb) water. This is why paper goes soggy when wet and why cloth towels can dry us — they absorb water into their fibres.' }),

  makeMCQ({ id:'g3sc-mat-037', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which material does NOT let water pass through it (waterproof)?',
    options:['plastic','paper','cloth','cardboard'],
    answer:'plastic',
    hint:'You can put plastic in water and it stays dry inside.',
    explanation:'<b>Plastic</b> is waterproof — water cannot pass through it. That is why raincoats and water bottles are made of plastic. Paper, cloth and cardboard all absorb water.' }),

  makeMCQ({ id:'g3sc-mat-038', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which material is very light and easy to write on?',
    options:['paper','wood','glass','stone'],
    answer:'paper',
    hint:'Your school exercise books are made of this.',
    explanation:'<b>Paper</b> is very light and easy to write on. This is why we use paper for books, exercise books, letters and newspapers — it is thin, light and has a smooth surface perfect for writing.' }),

  makeMCQ({ id:'g3sc-mat-039', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Why is wood a good material for building houses?',
    options:['It is strong, hard and can be cut into planks','It is transparent like glass','It is very light like paper','It is flexible like cloth'],
    answer:'It is strong, hard and can be cut into planks',
    hint:'Houses need to be strong enough to stand up and protect people inside.',
    explanation:'Wood is used in building because it is <b>strong, hard and can be cut into planks</b> of different sizes. Its strength means it can support the weight of a roof and walls.' }),

  makeMCQ({ id:'g3sc-mat-040', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which of these is a property of glass?',
    options:['transparent (you can see through it)','soft like cloth','as light as paper','flexible like plastic'],
    answer:'transparent (you can see through it)',
    hint:'Windows are made of glass because of this property.',
    explanation:'<b>Transparency</b> is a key property of glass — you can see through it clearly. This is what makes glass useful for windows, glasses (spectacles) and drinking cups.' }),

  makeMCQ({ id:'g3sc-mat-041', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which property of plastic makes it useful for making toys?',
    options:['It can be moulded (shaped) into any form','It is transparent like glass','It is as strong as stone','It is very heavy'],
    answer:'It can be moulded (shaped) into any form',
    hint:'Toys come in all sorts of shapes — what material can be shaped like this?',
    explanation:'Plastic can be <b>moulded into any shape</b> when it is heated. This is why plastic is used for toys — you can make any shape, from cars to animals to building blocks.' }),

  makeMCQ({ id:'g3sc-mat-042', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Can wood float on water?',
    options:['Yes — wood floats on water','No — wood sinks like a stone','Only small pieces of wood float','Wood dissolves in water'],
    answer:'Yes — wood floats on water',
    hint:'Think about wooden boats and logs in rivers.',
    explanation:'<b>Yes, wood floats on water</b>. Wood is less dense than water, so it floats. This is why boats and rafts were traditionally made of wood.' }),

  makeMCQ({ id:'g3sc-mat-043', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which material is rough and strong, found in walls and roads?',
    options:['stone / concrete','paper','cloth','plastic'],
    answer:'stone / concrete',
    hint:'This material is used to build walls and pathways.',
    explanation:'<b>Stone and concrete</b> are rough and very strong, used for building walls, roads and pathways. They are not one of our four main materials (wood, plastic, paper, glass), but they are important materials in our environment.' }),

  makeMCQ({ id:'g3sc-mat-044', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which of these properties describes BOTH glass and plastic (clear plastic)?',
    options:['transparent (see-through)','waterproof only','heavy only','soft and flexible'],
    answer:'transparent (see-through)',
    hint:'Both clear glass and clear plastic let you see through them.',
    explanation:'Both <b>clear glass and clear plastic</b> are transparent — you can see through them. That is a shared property. However, glass is heavier and more fragile, while plastic is lighter and more flexible.' }),

  makeMCQ({ id:'g3sc-mat-045', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'What does "waterproof" mean?',
    options:['Water cannot pass through it','It is made of water','It floats on water','It is filled with water'],
    answer:'Water cannot pass through it',
    hint:'A waterproof material keeps water OUT.',
    explanation:'<b>Waterproof</b> means water cannot pass through the material. Plastic and glass are waterproof — water cannot soak through them. Paper and cloth are NOT waterproof.' }),

  makeMCQ({ id:'g3sc-mat-046', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which of these is a property of paper?',
    options:['It can be folded and torn easily','It is very hard and heavy','It is transparent','It is always waterproof'],
    answer:'It can be folded and torn easily',
    hint:'What do you do when you make an origami shape or tear open a package?',
    explanation:'Paper <b>can be folded and torn easily</b>. This makes it flexible and easy to work with — perfect for books, origami and packaging.' }),

  makeMCQ({ id:'g3sc-mat-047', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which material is naturally found in tree trunks?',
    options:['wood','plastic','glass','paper'],
    answer:'wood',
    hint:'When a tree is cut down, the hard material inside is used for building.',
    explanation:'<b>Wood</b> comes naturally from tree trunks. When trees are cut down, the hard wood inside can be shaped into planks for building furniture and houses.' }),

  makeMCQ({ id:'g3sc-mat-048', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Why would a glass plate be a bad choice for a small child?',
    options:['It is fragile and breaks into sharp, dangerous pieces','It is too expensive','It is transparent','It is too heavy to see through'],
    answer:'It is fragile and breaks into sharp, dangerous pieces',
    hint:'Small children drop things often.',
    explanation:'A glass plate is a bad choice for small children because it is <b>fragile and breaks into sharp pieces</b> when dropped. Plastic or melamine plates are safer choices for young children.' }),

  makeMCQ({ id:'g3sc-mat-049', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Which material is BEST at keeping food in a lunchbox dry and fresh?',
    options:['plastic (waterproof container)','paper bag','cloth bag','cardboard box'],
    answer:'plastic (waterproof container)',
    hint:'The container needs to be waterproof so food stays dry.',
    explanation:'A <b>plastic container</b> is best for keeping food in a lunchbox because plastic is waterproof. It keeps moisture out and prevents the food from getting soggy or absorbing outside smells.' }),

  makeMCQ({ id:'g3sc-mat-050', chapterId:'g3sc-materials', difficulty:1, subsection:'properties_materials',
    question:'Compare paper and wood. Which statement is TRUE?',
    options:['Wood is stronger and harder than paper','Paper is harder than wood','They have the same strength','Wood is lighter than paper'],
    answer:'Wood is stronger and harder than paper',
    hint:'Would you rather make a chair out of wood or paper?',
    explanation:'<b>Wood is stronger and harder than paper</b>. Wood can hold weight without bending or breaking, while paper is easy to crush and tear. Both come from trees, but paper has been processed to be much thinner and weaker.' }),

  // ── uses_objects ─────────────────────────────────────────────────────────────

  makeMCQ({ id:'g3sc-mat-051', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'We wrap food in ___ to keep it fresh.',
    options:['plastic wrap or paper','glass','wood','stone'],
    answer:'plastic wrap or paper',
    hint:'Think about how sandwiches are wrapped in a lunchbox.',
    explanation:'We wrap food in <b>plastic wrap or paper</b> to keep it fresh. These materials are thin and flexible enough to wrap around food, keeping air and germs out.' }),

  makeMCQ({ id:'g3sc-mat-052', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'A glass is used to ___.',
    options:['drink from','build a wall','wrap food','write on'],
    answer:'drink from',
    hint:'You put juice or water in this and drink from it.',
    explanation:'A glass is used to <b>drink from</b>. Glasses are made of glass or plastic and are used to hold water, juice, milk and other drinks.' }),

  makeMCQ({ id:'g3sc-mat-053', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Why do we use wood to make doors?',
    options:['Wood is strong and provides privacy','Wood is transparent like glass','Wood is waterproof like plastic','Wood is as light as paper'],
    answer:'Wood is strong and provides privacy',
    hint:'Doors need to be solid enough to keep people out.',
    explanation:'Wood is used for doors because it is <b>strong</b> enough to keep unwanted visitors out, and unlike glass, it provides <b>privacy</b> — people cannot see through it.' }),

  makeMCQ({ id:'g3sc-mat-054', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Which material is best for writing a letter to a friend?',
    options:['paper','glass','stone','plastic'],
    answer:'paper',
    hint:'You use a pen to write on this material.',
    explanation:'<b>Paper</b> is best for writing a letter. It is smooth, light and easy to write on with a pen or pencil. You can fold it and put it in an envelope to send to a friend.' }),

  makeMCQ({ id:'g3sc-mat-055', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Why do we use glass for windows and not wood?',
    options:['Glass is transparent so we can see outside and light can come in','Glass is cheaper than wood','Glass does not break','Glass is softer than wood'],
    answer:'Glass is transparent so we can see outside and light can come in',
    hint:'We want to see the outside world from our bedroom without going out.',
    explanation:'We use glass for windows because it is <b>transparent</b> — we can see through it and natural light can enter our homes. Wood is not transparent, so a wooden window would block our view and keep light out.' }),

  makeMCQ({ id:'g3sc-mat-056', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Which material is used to make a raincoat?',
    options:['waterproof plastic or rubber','paper','wood','glass'],
    answer:'waterproof plastic or rubber',
    hint:'A raincoat must stop rain from getting through to your clothes.',
    explanation:'Raincoats are made of <b>waterproof plastic or rubber</b>. These materials do not let water pass through, keeping us dry when it rains.' }),

  makeMCQ({ id:'g3sc-mat-057', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Why is plastic used for food packaging in supermarkets?',
    options:['It is waterproof, light and can be moulded into any shape','It is transparent and heavy','It is made from trees','It is very expensive'],
    answer:'It is waterproof, light and can be moulded into any shape',
    hint:'Supermarket packaging needs to protect food and be easy to carry.',
    explanation:'Plastic is used for supermarket packaging because it is <b>waterproof, light and can be shaped</b> into any form — bottles, trays, bags and wrappers. It keeps food fresh and is easy for shoppers to carry.' }),

  makeMCQ({ id:'g3sc-mat-058', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'What material would you choose to make a bookshelf?',
    options:['wood','glass','paper','cloth'],
    answer:'wood',
    hint:'A bookshelf needs to hold heavy books without bending.',
    explanation:'<b>Wood</b> is the best choice for a bookshelf. It is strong enough to hold many heavy books without bending or breaking. Glass would be too fragile and paper would collapse.' }),

  makeMCQ({ id:'g3sc-mat-059', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Which material is used to make spectacles (glasses for eyes)?',
    options:['glass or clear plastic','wood','paper','cloth'],
    answer:'glass or clear plastic',
    hint:'The lenses in glasses must be transparent so you can see through them.',
    explanation:'Spectacles (eye glasses) are made of <b>glass or clear plastic</b> for the lenses, because they must be transparent. The frames are often made of plastic or metal.' }),

  makeMCQ({ id:'g3sc-mat-060', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Priya wants to store water in a container. Which material should the container be made of?',
    options:['plastic or glass (waterproof)','paper','cloth','cardboard'],
    answer:'plastic or glass (waterproof)',
    hint:'The container must not let the water leak through its sides.',
    explanation:'Priya should use a <b>plastic or glass</b> container because these materials are waterproof — water cannot soak through them. Paper and cloth would get soggy and let the water leak out.' }),

  makeMCQ({ id:'g3sc-mat-061', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Why do we use paper bags in some shops instead of plastic bags?',
    options:['Paper is more eco-friendly and breaks down naturally','Paper is waterproof','Paper is stronger than plastic','Paper is transparent'],
    answer:'Paper is more eco-friendly and breaks down naturally',
    hint:'Think about what happens to a paper bag and a plastic bag if they are left outside.',
    explanation:'Paper bags are used because paper is <b>more eco-friendly</b> — it breaks down naturally in the environment (biodegrades), unlike plastic which can take hundreds of years to break down and pollutes the sea and land.' }),

  makeMCQ({ id:'g3sc-mat-062', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'What is one way we can reuse glass bottles instead of throwing them away?',
    options:['Clean them and refill them with water or other drinks','Burn them','Bury them in the garden','Tear them up'],
    answer:'Clean them and refill them with water or other drinks',
    hint:'Glass does not wear out quickly and can be used many times.',
    explanation:'We can <b>clean glass bottles and refill them</b>. Glass is durable and does not affect the taste of food or drinks, making it perfect for reuse. This reduces waste and is good for the environment.' }),

  makeMCQ({ id:'g3sc-mat-063', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Which material is used to make swimming caps?',
    options:['rubber (a type of plastic)','wood','glass','paper'],
    answer:'rubber (a type of plastic)',
    hint:'Swimming caps need to stretch and be completely waterproof.',
    explanation:'Swimming caps are made of <b>rubber</b> (a type of plastic). Rubber is stretchy, flexible and completely waterproof — perfect for covering hair in a swimming pool.' }),

  makeMCQ({ id:'g3sc-mat-064', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Omar wants to make a kite. Which materials would work best?',
    options:['light paper or cloth with a thin wooden or plastic frame','heavy glass and stone','metal and wood only','thick plastic and heavy cloth'],
    answer:'light paper or cloth with a thin wooden or plastic frame',
    hint:'A kite must be very light so the wind can carry it up.',
    explanation:'The best kite materials are <b>light paper or cloth</b> (for the sail) and a <b>thin wooden or plastic frame</b>. The kite must be very light so it can be lifted by the wind.' }),

  makeMCQ({ id:'g3sc-mat-065', chapterId:'g3sc-materials', difficulty:1, subsection:'uses_objects',
    question:'Which material is NOT suitable for making a cup for hot drinks?',
    options:['plain paper (without lining)','ceramic','glass (heat-resistant)','plastic (heat-resistant)'],
    answer:'plain paper (without lining)',
    hint:'What happens to paper when it gets very hot or wet?',
    explanation:'<b>Plain paper</b> is not suitable for a cup with hot drinks — it gets soggy, loses its shape and hot liquid would seep through. Paper cups must have a waterproof lining inside to work.' })

);

})();
