'use strict';
// Grade 3 English — Speaking
// IDs: g3eng-spk-001 … g3eng-spk-075

(function () {

STATIC_QUESTIONS.push(

  // ── ORAL VOCABULARY (25 questions) ───────────────────────────────────────

  makeMCQ({ id:'g3eng-spk-001', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means almost the same as "happy"?',
    options:['joyful','angry','tired','worried'],
    answer:'joyful',
    hint:'Think of a word that means feeling very good inside.',
    explanation:'<b>Joyful</b> is a synonym for "happy". Both words describe a feeling of great pleasure and delight.' }),

  makeMCQ({ id:'g3eng-spk-002', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means the OPPOSITE of "big"?',
    options:['tiny','large','tall','wide'],
    answer:'tiny',
    hint:'You need a word that means very small.',
    explanation:'<b>Tiny</b> means very small, which is the opposite of big. "Large" and "tall" are similar to big, not opposite.' }),

  makeMCQ({ id:'g3eng-spk-003', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which is a better and more interesting word to use instead of "nice"?',
    options:['wonderful','okay','fine','alright'],
    answer:'wonderful',
    hint:'Choose the word that is most exciting and descriptive.',
    explanation:'<b>Wonderful</b> is a much more interesting and descriptive word than "nice". Good writers use precise words to make their language vivid.' }),

  makeMCQ({ id:'g3eng-spk-004', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'What does the word "enormous" mean?',
    options:['very big','very fast','very cold','very old'],
    answer:'very big',
    hint:'Think of words like "elephant-sized".',
    explanation:'<b>Enormous</b> means very, very big. An elephant is enormous. A whale is enormous.' }),

  makeMCQ({ id:'g3eng-spk-005', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means almost the same as "begin"?',
    options:['start','finish','stop','end'],
    answer:'start',
    hint:'You are looking for a word that means the same as when something first happens.',
    explanation:'<b>Start</b> is a synonym for "begin". Both mean to do something for the first time.' }),

  makeMCQ({ id:'g3eng-spk-006', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word is the BEST description of a lemon?',
    options:['sour','sweet','salty','bitter-hot'],
    answer:'sour',
    hint:'What do you feel on your tongue when you eat a lemon?',
    explanation:'<b>Sour</b> is the correct word. Lemons have a tart, sour taste that makes your face scrunch up.' }),

  makeMCQ({ id:'g3eng-spk-007', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means almost the same as "frightened"?',
    options:['scared','excited','happy','sleepy'],
    answer:'scared',
    hint:'Both words describe a feeling when something makes you want to run away.',
    explanation:'<b>Scared</b> and "frightened" both mean feeling afraid. They are synonyms.' }),

  makeMCQ({ id:'g3eng-spk-008', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word is a more precise way to say "said loudly"?',
    options:['shouted','whispered','murmured','mumbled'],
    answer:'shouted',
    hint:'Which word means to speak at a very high volume?',
    explanation:'<b>Shouted</b> means to say something very loudly. Using "shouted" instead of "said loudly" makes writing more vivid.' }),

  makeMCQ({ id:'g3eng-spk-009', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'What does "ancient" mean?',
    options:['very old','very new','very fast','very large'],
    answer:'very old',
    hint:'Dinosaurs are ancient. Old castles are ancient.',
    explanation:'<b>Ancient</b> means something that is extremely old, often from a very long time ago in history.' }),

  makeMCQ({ id:'g3eng-spk-010', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means the OPPOSITE of "rough"?',
    options:['smooth','hard','wet','bumpy'],
    answer:'smooth',
    hint:'Run your hand along silk — what word describes that feeling?',
    explanation:'<b>Smooth</b> is the opposite of rough. A rough surface has bumps; a smooth surface has none.' }),

  makeMCQ({ id:'g3eng-spk-011', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means "moving very fast"?',
    options:['swift','slow','heavy','quiet'],
    answer:'swift',
    hint:'A cheetah is the swiftest land animal.',
    explanation:'<b>Swift</b> means very fast. It is a more interesting word than "fast" and is used in descriptions and stories.' }),

  makeMCQ({ id:'g3eng-spk-012', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Choose the most interesting word to complete: "The flowers in the garden are ___."',
    options:['gorgeous','nice','good','fine'],
    answer:'gorgeous',
    hint:'Pick the word that paints the most vivid picture.',
    explanation:'<b>Gorgeous</b> paints a much more vivid picture than "nice" or "good". Good writers choose precise, interesting words.' }),

  makeMCQ({ id:'g3eng-spk-013', chapterId:'g3eng-speaking', difficulty:2, subsection:'oral_vocabulary',
    question:'What does the word "transparent" mean?',
    options:['you can see through it','it is very dark','it is very heavy','it cannot be moved'],
    answer:'you can see through it',
    hint:'Glass is transparent. What does that tell you?',
    explanation:'<b>Transparent</b> means you can see through something clearly. Glass and clean water are transparent.' }),

  makeMCQ({ id:'g3eng-spk-014', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word is a synonym for "tired"?',
    options:['exhausted','energetic','awake','excited'],
    answer:'exhausted',
    hint:'"Exhausted" is a stronger version of this feeling.',
    explanation:'<b>Exhausted</b> is a synonym for "tired", but even stronger — it means extremely tired.' }),

  makeMCQ({ id:'g3eng-spk-015', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means "full of colour"?',
    options:['colourful','dull','pale','grey'],
    answer:'colourful',
    hint:'A rainbow is ___ .',
    explanation:'<b>Colourful</b> means having many bright colours. A rainbow, a parrot or a market stall can all be described as colourful.' }),

  makeMCQ({ id:'g3eng-spk-016', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means the OPPOSITE of "noisy"?',
    options:['silent','loud','busy','crowded'],
    answer:'silent',
    hint:'A library is expected to be ___ .',
    explanation:'<b>Silent</b> is the opposite of noisy. Silent means completely quiet with no sound at all.' }),

  makeMCQ({ id:'g3eng-spk-017', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'What does "generous" mean?',
    options:['happy to give and share','mean and selfish','quiet and shy','loud and noisy'],
    answer:'happy to give and share',
    hint:'A generous person always wants to share what they have.',
    explanation:'<b>Generous</b> means being happy to give things to others and share freely.' }),

  makeMCQ({ id:'g3eng-spk-018', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word could replace "walked slowly" to make it more interesting?',
    options:['strolled','ran','jogged','dashed'],
    answer:'strolled',
    hint:'"Strolled" means to walk in a relaxed, unhurried way.',
    explanation:'<b>Strolled</b> means to walk slowly and calmly. It is a more precise and interesting word than "walked slowly".' }),

  makeMCQ({ id:'g3eng-spk-019', chapterId:'g3eng-speaking', difficulty:2, subsection:'oral_vocabulary',
    question:'What does "habitat" mean?',
    options:['the natural home of an animal or plant','a type of food animals eat','a kind of animal coat','the way animals communicate'],
    answer:'the natural home of an animal or plant',
    hint:'A fish\'s habitat is the sea. A bird\'s habitat is a tree or forest.',
    explanation:'<b>Habitat</b> is the natural environment where a plant or animal normally lives, like a pond, forest or desert.' }),

  makeMCQ({ id:'g3eng-spk-020', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word is a better way to say "very sad"?',
    options:['heartbroken','unhappy','bad','not happy'],
    answer:'heartbroken',
    hint:'This word describes the deepest kind of sadness.',
    explanation:'<b>Heartbroken</b> describes an intense sadness — much more vivid and precise than "very sad".' }),

  makeMCQ({ id:'g3eng-spk-021', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word means "to look at something for a long time"?',
    options:['stare','glance','blink','peep'],
    answer:'stare',
    hint:'You stare when you cannot look away.',
    explanation:'<b>Stare</b> means to look fixedly at something for a long time without looking away.' }),

  makeMCQ({ id:'g3eng-spk-022', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'What does "curious" mean?',
    options:['wanting to know or learn about something','feeling very tired','being very angry','feeling very cold'],
    answer:'wanting to know or learn about something',
    hint:'Curious cats always want to explore.',
    explanation:'<b>Curious</b> means eager to know or learn. A curious person asks lots of questions and loves exploring.' }),

  makeMCQ({ id:'g3eng-spk-023', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'Which word is the OPPOSITE of "ugly"?',
    options:['beautiful','small','quiet','dark'],
    answer:'beautiful',
    hint:'You need a word that means very good-looking.',
    explanation:'<b>Beautiful</b> is the opposite of ugly. Beautiful means very attractive or pleasing to look at.' }),

  makeMCQ({ id:'g3eng-spk-024', chapterId:'g3eng-speaking', difficulty:1, subsection:'oral_vocabulary',
    question:'What does "delicious" describe?',
    options:['food that tastes very good','something that is very heavy','a place that is very far','weather that is very hot'],
    answer:'food that tastes very good',
    hint:'You say "delicious" when you really enjoy eating something.',
    explanation:'<b>Delicious</b> describes food or drink that tastes wonderful. It is used specifically for taste.' }),

  makeMCQ({ id:'g3eng-spk-025', chapterId:'g3eng-speaking', difficulty:2, subsection:'oral_vocabulary',
    question:'Which word best completes this sentence: "The brave firefighter ___ into the burning building"?',
    options:['rushed','walked','went','moved'],
    answer:'rushed',
    hint:'Choose the word that shows speed and urgency.',
    explanation:'<b>Rushed</b> is the most precise and exciting word here. It shows the firefighter moved fast and urgently — more vivid than "went" or "walked".' }),

  // ── DESCRIBING & RETELLING (25 questions) ─────────────────────────────────

  makeMCQ({ id:'g3eng-spk-026', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which sentence gives the BEST description of an apple?',
    options:['The apple is round, shiny and red, with sweet white flesh inside.','The apple is a fruit.','I like apples.','The apple is in the basket.'],
    answer:'The apple is round, shiny and red, with sweet white flesh inside.',
    hint:'A good description tells you shape, colour, texture and taste.',
    explanation:'<b>The apple is round, shiny and red, with sweet white flesh inside</b> is the best description. It uses adjectives for shape, appearance and taste.' }),

  makeMCQ({ id:'g3eng-spk-027', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which sentence is the BEST retelling of this story: "Asha found a stray kitten, took it home, gave it milk, and named it Mochi"?',
    options:['Asha rescued a lost kitten, brought it home, fed it and gave it the name Mochi.','Asha has a cat.','A kitten was in the street.','Mochi is a cat name.'],
    answer:'Asha rescued a lost kitten, brought it home, fed it and gave it the name Mochi.',
    hint:'The best retelling keeps all the key events in the right order.',
    explanation:'<b>Asha rescued a lost kitten, brought it home, fed it and gave it the name Mochi</b> is correct. It retells all four events in sequence.' }),

  makeMCQ({ id:'g3eng-spk-028', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'What should you do FIRST when retelling a story?',
    options:['Say what happened at the beginning','Describe the ending','List all the characters','Give your opinion about the story'],
    answer:'Say what happened at the beginning',
    hint:'Retelling follows the same order as the original story.',
    explanation:'<b>Say what happened at the beginning</b> is correct. Retellings follow the sequence: beginning → middle → end.' }),

  makeMCQ({ id:'g3eng-spk-029', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which describing word would you use for a LOUD noise?',
    options:['thunderous','silent','gentle','faint'],
    answer:'thunderous',
    hint:'This word compares a sound to thunder.',
    explanation:'<b>Thunderous</b> describes an extremely loud noise. Using vivid words like this makes your description much more powerful.' }),

  makeMCQ({ id:'g3eng-spk-030', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'To describe a person well, which THREE things should you include?',
    options:['What they look like, how they feel, and what they do','Only their name','Only what they are wearing','Their home address'],
    answer:'What they look like, how they feel, and what they do',
    hint:'A good character description covers appearance, personality and actions.',
    explanation:'<b>Appearance, feelings and actions</b> give a complete picture of a person. Names and addresses alone tell us almost nothing.' }),

  makeMCQ({ id:'g3eng-spk-031', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which sentence BEST describes the weather in the picture: a dark sky with heavy rain falling?',
    options:['The sky is dark and heavy rain is pouring down.','The weather is bad.','It is raining.','The sky is dark.'],
    answer:'The sky is dark and heavy rain is pouring down.',
    hint:'The best sentence uses details and describing words.',
    explanation:'<b>The sky is dark and heavy rain is pouring down</b> uses two details with describing words, making it the most vivid answer.' }),

  makeMCQ({ id:'g3eng-spk-032', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which connective word should you use when something happens AFTER something else in a retelling?',
    options:['Then','But','Because','Although'],
    answer:'Then',
    hint:'"Then" shows the next event in time.',
    explanation:'<b>Then</b> is a time connective that shows the next event. "First... then... after that... finally" are the key retelling connectives.' }),

  makeMCQ({ id:'g3eng-spk-033', chapterId:'g3eng-speaking', difficulty:2, subsection:'describing_retelling',
    question:'A pupil says: "The dog. It barked. It ran." How could this be IMPROVED?',
    options:['The large brown dog barked loudly and then ran swiftly across the field.','A dog barked and ran.','The dog barked and ran away.','Dog: barked, ran.'],
    answer:'The large brown dog barked loudly and then ran swiftly across the field.',
    hint:'Add adjectives and adverbs to give more detail.',
    explanation:'<b>The large brown dog barked loudly and then ran swiftly across the field</b> is best — it adds adjectives (large, brown), adverbs (loudly, swiftly) and a connective (then).' }),

  makeMCQ({ id:'g3eng-spk-034', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which sentence BEST describes a sunset?',
    options:['The sky glowed orange and pink as the sun slowly sank below the horizon.','The sun went down.','It was evening.','The sun is orange sometimes.'],
    answer:'The sky glowed orange and pink as the sun slowly sank below the horizon.',
    hint:'Look for describing words and precise verbs.',
    explanation:'<b>The sky glowed orange and pink as the sun slowly sank below the horizon</b> uses colour words, a precise verb (glowed, sank) and the connective (as).' }),

  makeMCQ({ id:'g3eng-spk-035', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'In a retelling, which word would you use to start the FINAL event?',
    options:['Finally','First','Then','Next'],
    answer:'Finally',
    hint:'Only one of these words signals the very last event.',
    explanation:'<b>Finally</b> is the connective word used to introduce the last event in a retelling or sequence.' }),

  makeMCQ({ id:'g3eng-spk-036', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which group of words describes what someone LOOKS LIKE?',
    options:['tall, curly-haired, wearing a blue uniform','happy, kind, generous','runs quickly, laughs a lot','friendly, caring, helpful'],
    answer:'tall, curly-haired, wearing a blue uniform',
    hint:'Describing appearance means describing what you can SEE.',
    explanation:'<b>Tall, curly-haired, wearing a blue uniform</b> describes physical appearance — what you would see when you look at the person.' }),

  makeMCQ({ id:'g3eng-spk-037', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which adjective describes how something SMELLS?',
    options:['fragrant','colourful','rough','loud'],
    answer:'fragrant',
    hint:'"Fragrant" describes a pleasant smell — like flowers or perfume.',
    explanation:'<b>Fragrant</b> describes a sweet, pleasant smell. It is an adjective for the sense of smell.' }),

  makeMCQ({ id:'g3eng-spk-038', chapterId:'g3eng-speaking', difficulty:2, subsection:'describing_retelling',
    question:'A pupil retells: "A boy went to the sea. He saw a fish. He went home." What is MISSING?',
    options:['Describing words and connectives to link the events','An ending','The name of the fish','The boy\'s age'],
    answer:'Describing words and connectives to link the events',
    hint:'A good retelling uses adjectives and time connectives.',
    explanation:'<b>Describing words and connectives</b> are missing. Better: "A young boy walked to the sparkling sea. Then he spotted a bright silver fish. Finally, he headed home happily."' }),

  makeMCQ({ id:'g3eng-spk-039', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which is the BEST way to describe the taste of ripe mango?',
    options:['Sweet, juicy and slightly tangy','Nice','It is good','A fruit'],
    answer:'Sweet, juicy and slightly tangy',
    hint:'The best description uses at least two or three adjectives.',
    explanation:'<b>Sweet, juicy and slightly tangy</b> uses three precise adjectives to describe the taste exactly. "Nice" and "good" tell us almost nothing.' }),

  makeMCQ({ id:'g3eng-spk-040', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'What makes a retelling DIFFERENT from reading the original story word for word?',
    options:['A retelling uses your own words but keeps all the key events.','A retelling changes all the events.','A retelling only tells the ending.','A retelling makes up new characters.'],
    answer:'A retelling uses your own words but keeps all the key events.',
    hint:'You retell in your OWN words, but you do not change what happened.',
    explanation:'<b>A retelling uses your own words but keeps all the key events</b> is correct. You paraphrase, you do not copy, and you do not change the story.' }),

  makeMCQ({ id:'g3eng-spk-041', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which sentence best describes a butterfly?',
    options:['The butterfly has delicate wings with bright patterns of orange and black.','The butterfly is pretty.','I like butterflies.','Butterflies have wings.'],
    answer:'The butterfly has delicate wings with bright patterns of orange and black.',
    hint:'Look for the sentence that uses the most adjectives and detail.',
    explanation:'<b>The butterfly has delicate wings with bright patterns of orange and black</b> uses adjectives (delicate, bright) and specific details (orange and black patterns).' }),

  makeMCQ({ id:'g3eng-spk-042', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which word would you use to describe something that is very bright and shiny?',
    options:['gleaming','dull','foggy','dim'],
    answer:'gleaming',
    hint:'Think of polished gold or a clean mirror.',
    explanation:'<b>Gleaming</b> means shining brightly. It is a more vivid word than "shiny" and makes descriptions more interesting.' }),

  makeMCQ({ id:'g3eng-spk-043', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which sentence correctly uses "after that" in a retelling?',
    options:['We played games. After that, we had lunch.','After that we played. We had games.','We had lunch. After that, we played. Before that.','After that was lunch and then games.'],
    answer:'We played games. After that, we had lunch.',
    hint:'"After that" comes at the start of the SECOND event.',
    explanation:'<b>We played games. After that, we had lunch</b> is correct. "After that" correctly links the first event to the next one in time.' }),

  makeMCQ({ id:'g3eng-spk-044', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which adjective describes how something FEELS to the touch?',
    options:['velvety','cheerful','thunderous','vivid'],
    answer:'velvety',
    hint:'"Velvety" describes a very soft, smooth texture.',
    explanation:'<b>Velvety</b> is a tactile adjective — it describes the sense of touch. Velvet is soft and smooth, so "velvety" describes something that feels that way.' }),

  makeMCQ({ id:'g3eng-spk-045', chapterId:'g3eng-speaking', difficulty:2, subsection:'describing_retelling',
    question:'A story has three main events: (A) The girl found a lost puppy. (B) She brought it to the vet. (C) The owner was reunited with the puppy. Which is the BEST retelling?',
    options:['First, the girl found a lost puppy. Then, she brought it to the vet. Finally, the happy owner was reunited with the puppy.','A girl found a dog and took it to the vet and the owner got it back.','Lost puppy. Vet. Owner.','The puppy was lost. The vet helped. The owner came.'],
    answer:'First, the girl found a lost puppy. Then, she brought it to the vet. Finally, the happy owner was reunited with the puppy.',
    hint:'The best retelling uses time connectives AND describing words.',
    explanation:'<b>First... Then... Finally</b> uses all three time connectives and adds the adjective "happy" to bring the events to life.' }),

  makeMCQ({ id:'g3eng-spk-046', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which sentence BEST describes the sound of the ocean?',
    options:['The ocean roared and crashed as waves thundered against the rocks.','The ocean was loud.','The sea made noise.','Water sounds loud near rocks.'],
    answer:'The ocean roared and crashed as waves thundered against the rocks.',
    hint:'Look for precise action verbs and describing words.',
    explanation:'<b>Roared, crashed and thundered</b> are all strong verbs that paint a vivid picture of loud, powerful waves.' }),

  makeMCQ({ id:'g3eng-spk-047', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'What does a good description of a PLACE include?',
    options:['What you can see, hear, smell or feel there','Only the name of the place','Only the weather there','How far away the place is'],
    answer:'What you can see, hear, smell or feel there',
    hint:'Use your five senses to describe a place.',
    explanation:'<b>Sight, sound, smell and touch</b> make a place description come alive. Using sensory details is the key to vivid writing.' }),

  makeMCQ({ id:'g3eng-spk-048', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which sentence correctly uses "because" to explain something?',
    options:['Rani wore her coat because it was cold outside.','Rani wore her coat because.','Because it was cold, Rani.','Because, Rani wore a coat cold.'],
    answer:'Rani wore her coat because it was cold outside.',
    hint:'"Because" must connect two complete ideas: a reason and a result.',
    explanation:'<b>Rani wore her coat because it was cold outside</b> is correct. "Because" links the action (wearing the coat) with the reason (it was cold).' }),

  makeMCQ({ id:'g3eng-spk-049', chapterId:'g3eng-speaking', difficulty:1, subsection:'describing_retelling',
    question:'Which word would best describe the texture of sandpaper?',
    options:['rough','smooth','soft','fluffy'],
    answer:'rough',
    hint:'Run your finger over sandpaper — what do you feel?',
    explanation:'<b>Rough</b> describes a surface with bumps and grit. Sandpaper is used specifically because it is rough.' }),

  makeMCQ({ id:'g3eng-spk-050', chapterId:'g3eng-speaking', difficulty:2, subsection:'describing_retelling',
    question:'Which retelling includes the best SEQUENCE CONNECTIVES?',
    options:['First Tara woke up. Then she packed her bag. After that she ate breakfast. Finally she left for school.','Tara woke up packed her bag ate breakfast and left.','Tara: wake up, bag, breakfast, school.','Tara did many things in the morning before school.'],
    answer:'First Tara woke up. Then she packed her bag. After that she ate breakfast. Finally she left for school.',
    hint:'Look for first, then, after that and finally.',
    explanation:'<b>First... Then... After that... Finally</b> are the four key sequence connectives, all used correctly to show the order of events.' }),

  // ── QUESTIONS & ANSWERS (25 questions) ───────────────────────────────────

  makeMCQ({ id:'g3eng-spk-051', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which question word asks about a PERSON?',
    options:['Who','What','Where','When'],
    answer:'Who',
    hint:'This word asks about people.',
    explanation:'<b>Who</b> asks about a person. e.g. "Who baked the cake?" — the answer will be a person\'s name or description.' }),

  makeMCQ({ id:'g3eng-spk-052', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which question word asks about a PLACE?',
    options:['Where','What','Who','When'],
    answer:'Where',
    hint:'This word asks about location.',
    explanation:'<b>Where</b> asks about a place or location. e.g. "Where is the library?" — the answer will name a place.' }),

  makeMCQ({ id:'g3eng-spk-053', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which question word asks about a TIME?',
    options:['When','Where','Who','How'],
    answer:'When',
    hint:'This word asks about the time or date something happened.',
    explanation:'<b>When</b> asks about time. e.g. "When does school start?" — the answer will be a time or date.' }),

  makeMCQ({ id:'g3eng-spk-054', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Priya answers: "I go to school by bus." What question was she most likely answering?',
    options:['How do you get to school?','Where is your school?','Who takes you to school?','When do you go to school?'],
    answer:'How do you get to school?',
    hint:'"By bus" tells us the METHOD of transport — which question word asks about method?',
    explanation:'<b>How</b> asks about method or manner. "By bus" answers the question "How do you get to school?"' }),

  makeMCQ({ id:'g3eng-spk-055', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'The answer is "Because it was raining." What question word was used?',
    options:['Why','What','Where','Who'],
    answer:'Why',
    hint:'"Because" gives a REASON — which question word asks for a reason?',
    explanation:'<b>Why</b> asks for a reason. "Because it was raining" is a reason, so the question started with "Why..."' }),

  makeMCQ({ id:'g3eng-spk-056', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which is a CLOSED question (one that has a simple yes or no answer)?',
    options:['Do you like mangoes?','What is your favourite fruit?','How do you eat a mango?','Why do you like mangoes?'],
    answer:'Do you like mangoes?',
    hint:'A closed question can be answered with just "yes" or "no".',
    explanation:'<b>"Do you like mangoes?"</b> is a closed question — the answer is simply "Yes" or "No". The other questions need longer answers.' }),

  makeMCQ({ id:'g3eng-spk-057', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which is an OPEN question (one that needs a longer answer)?',
    options:['What did you do at the beach today?','Did you go to the beach?','Is the beach nearby?','Are you going to the beach?'],
    answer:'What did you do at the beach today?',
    hint:'An open question cannot be answered with just yes or no.',
    explanation:'<b>"What did you do at the beach today?"</b> needs a full answer describing activities. The others can be answered with "yes" or "no".' }),

  makeMCQ({ id:'g3eng-spk-058', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'The answer is "Three o\'clock." What question word started the question?',
    options:['When','Where','Who','Why'],
    answer:'When',
    hint:'"Three o\'clock" is a TIME — which question asks about time?',
    explanation:'<b>When</b> asks about time. "Three o\'clock" answers "When does the match start?" or a similar question.' }),

  makeMCQ({ id:'g3eng-spk-059', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'The answer is "At the market." What question word started the question?',
    options:['Where','When','Who','How'],
    answer:'Where',
    hint:'"At the market" names a PLACE.',
    explanation:'<b>Where</b> asks about a place. "At the market" answers "Where did you buy the fruit?"' }),

  makeMCQ({ id:'g3eng-spk-060', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'The answer is "My teacher, Mrs Patel." What question started the question?',
    options:['Who','What','When','Why'],
    answer:'Who',
    hint:'The answer names a PERSON.',
    explanation:'<b>Who</b> asks about a person. "My teacher, Mrs Patel" answers "Who helped you with the project?"' }),

  makeMCQ({ id:'g3eng-spk-061', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which question would you ask to find out WHAT something is?',
    options:['What is that animal?','Who is that animal?','Where is that animal?','When is that animal?'],
    answer:'What is that animal?',
    hint:'"What" asks for information about a thing.',
    explanation:'<b>What is that animal?</b> uses "what" to ask for the name or identity of a thing.' }),

  makeMCQ({ id:'g3eng-spk-062', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which question asks for a REASON?',
    options:['Why did you choose that book?','What book did you choose?','When did you choose the book?','Who gave you the book?'],
    answer:'Why did you choose that book?',
    hint:'"Why" always asks for a reason or explanation.',
    explanation:'<b>Why did you choose that book?</b> asks for the reason behind the choice. The answer will start with "Because..."' }),

  makeMCQ({ id:'g3eng-spk-063', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which answer matches the question: "How many pupils are in your class?"',
    options:['There are 28 pupils in my class.','My class is in Block B.','My teacher is Mr Gobin.','We start class at 8 o\'clock.'],
    answer:'There are 28 pupils in my class.',
    hint:'"How many" asks for a NUMBER.',
    explanation:'<b>There are 28 pupils in my class</b> answers "How many" with a number — the only answer that gives a count.' }),

  makeMCQ({ id:'g3eng-spk-064', chapterId:'g3eng-speaking', difficulty:2, subsection:'asking_answering',
    question:'Ravi says: "I felt happy because I won a prize." What question was Ravi most likely asked?',
    options:['How did you feel and why?','What prize did you win?','Where did you win the prize?','Who gave you the prize?'],
    answer:'How did you feel and why?',
    hint:'Ravi named a feeling AND gave a reason — which question asks for both?',
    explanation:'<b>How did you feel and why?</b> is correct. Ravi gave a feeling ("happy") and a reason ("because I won a prize"), answering both parts.' }),

  makeMCQ({ id:'g3eng-spk-065', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which question uses CORRECT word order?',
    options:['What is your favourite colour?','Your favourite colour what is?','Favourite colour what is yours?','Is what your favourite colour?'],
    answer:'What is your favourite colour?',
    hint:'In English, questions usually start with a question word, then the verb, then the subject.',
    explanation:'<b>What is your favourite colour?</b> is correctly formed: question word (What) + verb (is) + subject (your favourite colour).' }),

  makeMCQ({ id:'g3eng-spk-066', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'A friend asks: "Which sport do you prefer, football or swimming?" This is an example of a ___ question.',
    options:['choice question','yes/no question','open question','why question'],
    answer:'choice question',
    hint:'The question offers two specific options to pick from.',
    explanation:'<b>Choice question</b> is correct. This type of question offers two or more options and asks the person to pick one.' }),

  makeMCQ({ id:'g3eng-spk-067', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'You want to know HOW something works. Which question do you ask?',
    options:['How does a rainbow form?','When does a rainbow appear?','Who can see a rainbow?','Where does a rainbow appear?'],
    answer:'How does a rainbow form?',
    hint:'"How" asks about the process or method.',
    explanation:'<b>How does a rainbow form?</b> asks about the process — the answer will explain steps or causes.' }),

  makeMCQ({ id:'g3eng-spk-068', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which answer correctly responds to: "What is the capital of Mauritius?"',
    options:['The capital of Mauritius is Port Louis.','Mauritius is an island.','Port Louis is a beautiful city.','We live in Mauritius.'],
    answer:'The capital of Mauritius is Port Louis.',
    hint:'Answer the question directly with the information asked for.',
    explanation:'<b>The capital of Mauritius is Port Louis</b> directly answers the question by naming the capital city.' }),

  makeMCQ({ id:'g3eng-spk-069', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which sentence correctly turns a statement into a question: "The dog is friendly."',
    options:['Is the dog friendly?','The dog is friendly?','Dog the is friendly?','Friendly the dog is?'],
    answer:'Is the dog friendly?',
    hint:'To make a yes/no question, move the verb to the front.',
    explanation:'<b>Is the dog friendly?</b> is correct. In English, we invert the subject and verb to form a yes/no question.' }),

  makeMCQ({ id:'g3eng-spk-070', chapterId:'g3eng-speaking', difficulty:2, subsection:'asking_answering',
    question:'The teacher asks: "Why is it important to drink water every day?" What is the BEST answer?',
    options:['It is important to drink water because our bodies need it to stay healthy and hydrated.','Water is good.','Because.','Water.'],
    answer:'It is important to drink water because our bodies need it to stay healthy and hydrated.',
    hint:'A good answer uses "because" and gives a clear reason.',
    explanation:'<b>It is important because our bodies need it to stay healthy and hydrated</b> uses "because" and explains the reason in a full sentence.' }),

  makeMCQ({ id:'g3eng-spk-071', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'You want to find out what time the bus leaves. Which question do you ask the driver?',
    options:['When does this bus leave?','Where does this bus go?','Who drives this bus?','Why does the bus stop here?'],
    answer:'When does this bus leave?',
    hint:'You want to know the TIME of departure.',
    explanation:'<b>When does this bus leave?</b> uses "when" to ask about the time of departure.' }),

  makeMCQ({ id:'g3eng-spk-072', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which is polite way to ask someone to repeat what they said?',
    options:['Could you please say that again?','Say it again!','What? Repeat!','I did not hear. Say.'],
    answer:'Could you please say that again?',
    hint:'Polite questions use words like "could", "please" and "thank you".',
    explanation:'<b>Could you please say that again?</b> is polite. Using "could" and "please" shows good manners when making a request.' }),

  makeMCQ({ id:'g3eng-spk-073', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'The answer is "Every morning before school." What question word was most likely used?',
    options:['When','Where','Who','What'],
    answer:'When',
    hint:'"Every morning before school" is a TIME expression.',
    explanation:'<b>When</b> asks about time. "Every morning before school" answers a question about WHEN something happens.' }),

  makeMCQ({ id:'g3eng-spk-074', chapterId:'g3eng-speaking', difficulty:1, subsection:'asking_answering',
    question:'Which question would help you understand a story better?',
    options:['Why did the character make that choice?','What colour is the book cover?','How heavy is the book?','When was the book printed?'],
    answer:'Why did the character make that choice?',
    hint:'Good comprehension questions explore meaning, feelings and reasons.',
    explanation:'<b>Why did the character make that choice?</b> explores the character\'s motivation — the kind of question that deepens understanding of a story.' }),

  makeMCQ({ id:'g3eng-spk-075', chapterId:'g3eng-speaking', difficulty:2, subsection:'asking_answering',
    question:'A pupil answers: "I was upset because my best friend moved to another school." Which question was MOST LIKELY asked?',
    options:['How did you feel when your friend left, and why?','Where did your friend move to?','Who is your best friend?','What is your friend\'s new school called?'],
    answer:'How did you feel when your friend left, and why?',
    hint:'The answer gives a feeling (upset) AND a reason (because...). Which question asks for both?',
    explanation:'<b>How did you feel and why?</b> is the only question that asks for both a feeling and a reason, which matches the answer perfectly.' })

);

})();
