'use strict';
// Grade 3 English — Reading
// IDs: g3eng-rdr-001 … g3eng-rdr-075

(function () {

STATIC_QUESTIONS.push(

  // ── READING COMPREHENSION (25 questions) ──────────────────────────────────

  makeMCQ({ id:'g3eng-rdr-001', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Zara loves going to the beach. She collects shells, builds sandcastles and watches the waves. Her favourite shell is a big pink one she found last year." What does Zara do at the beach?',
    options:['Collects shells and builds sandcastles','Reads books in the shade of a tree','Goes swimming in the sea every day','Sells the shells she finds to tourists'],
    answer:'Collects shells and builds sandcastles',
    hint:'The answer is written clearly in the passage.',
    explanation:'The second sentence lists what Zara does: she <b>collects shells, builds sandcastles</b> and watches the waves. Reading, swimming and selling are never mentioned.'}),

  makeMCQ({ id:'g3eng-rdr-002', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Zara loves going to the beach. She collects shells, builds sandcastles and watches the waves. Her favourite shell is a big pink one she found last year." What is Zara\'s favourite shell?',
    options:['A big pink one she found last year','A round yellow one from the market','A tiny white one from the sea shore','A broken blue one she was given'],
    answer:'A big pink one she found last year',
    hint:'The last sentence tells you about her favourite shell.',
    explanation:'The passage says directly: "Her favourite shell is a <b>big pink one she found last year</b>."'}),

  makeMCQ({ id:'g3eng-rdr-003', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Kai had a bad cold. His nose was running and his throat felt sore. His mum gave him warm soup and told him to rest. By evening, he felt a little better." Why did Kai\'s mum give him soup?',
    options:['Because he had a cold and felt unwell','Because soup is his favourite food','Because he was hungry after school','Because there was no other food left'],
    answer:'Because he had a cold and felt unwell',
    hint:'The soup was given as a remedy — look at what happened before and after.',
    explanation:'His mum gave him warm soup as a <b>remedy for his cold</b>, not just as a meal — the passage says he had a bad cold and a sore throat.'}),

  makeMCQ({ id:'g3eng-rdr-004', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Kai had a bad cold. His nose was running and his throat felt sore. His mum gave him warm soup and told him to rest. By evening, he felt a little better." How did Kai feel by the evening?',
    options:['A little better','Much worse','Perfectly well','Very hungry'],
    answer:'A little better',
    hint:'Read the last sentence carefully.',
    explanation:'<b>A little better</b> — the passage says "By evening, he felt a little better." Not completely well, but improving.' }),

  makeMCQ({ id:'g3eng-rdr-005', chapterId:'g3eng-reading', difficulty:2, subsection:'reading_comprehension',
    question:'Read: "Nadia found a small brown dog outside the school gate. It had no collar. She asked around but nobody knew who it belonged to. After school she took it home and her parents agreed to keep it." What does the phrase "nobody knew who it belonged to" tell you about the dog?',
    options:['The dog was a stray with no owner','The dog was lost from another town','The dog was famous in the area','The dog was rather unfriendly'],
    answer:'The dog was a stray with no owner',
    hint:'"Belonged to" means to be someone\'s property — if nobody knew, it had no owner.',
    explanation:'"Nobody knew who it belonged to" means the dog had <b>no owner</b> in the area — it was a stray.'}),

  makeMCQ({ id:'g3eng-rdr-006', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "The mango tree in our garden is very old. Grandpa planted it fifty years ago. Every summer it gives us plenty of sweet mangoes." Who planted the mango tree?',
    options:['Grandpa','The writer','Grandma','A neighbour'],
    answer:'Grandpa',
    hint:'The passage tells you exactly who planted it.',
    explanation:'<b>Grandpa</b> — the passage clearly states "Grandpa planted it fifty years ago."' }),

  makeMCQ({ id:'g3eng-rdr-007', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "The mango tree in our garden is very old. Grandpa planted it fifty years ago. Every summer it gives us plenty of sweet mangoes." When does the tree give mangoes?',
    options:['Every summer','Every winter','Every month','Every other week'],
    answer:'Every summer',
    hint:'The last sentence tells you WHEN the tree produces mangoes.',
    explanation:'The passage says "<b>Every summer</b> it gives us plenty of sweet mangoes."'}),

  makeMCQ({ id:'g3eng-rdr-008', chapterId:'g3eng-reading', difficulty:2, subsection:'reading_comprehension',
    question:'Read: "Leo was nervous about his first swimming lesson. He stood at the edge of the pool, his heart pounding. His teacher smiled and said, \'You will be swimming like a fish in no time!\'" How do you think Leo felt at the start of the lesson?',
    options:['Nervous and a little scared','Excited and very confident','Bored and rather sleepy','Angry and quite upset'],
    answer:'Nervous and a little scared',
    hint:'The word "nervous" is used directly, and "his heart pounding" also tells you about his feelings.',
    explanation:'The passage says Leo "was nervous" and that his heart was "pounding" — both signs of being <b>nervous and a little scared</b>.'}),

  makeMCQ({ id:'g3eng-rdr-009', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Birds build nests to lay their eggs and raise their chicks. Different birds build nests in different places: on trees, on the ground, or even on rooftops." Where do some birds build their nests? Give TWO places from the passage.',
    options:['On trees and on the ground','Only in the tall mountains','Only on telegraph poles','Only in holes in old walls'],
    answer:'On trees and on the ground',
    hint:'The passage lists three places — pick two that are mentioned.',
    explanation:'The passage says nests are built "on trees, on the ground, or even on rooftops", so <b>trees and the ground</b> are two of the places.'}),

  makeMCQ({ id:'g3eng-rdr-010', chapterId:'g3eng-reading', difficulty:2, subsection:'reading_comprehension',
    question:'Read: "Maria worked hard all term and came first in the class test. Her parents took her out for a special dinner to celebrate. Maria beamed with pride." What does "beamed with pride" most likely mean?',
    options:['She smiled broadly because she was pleased','She felt embarrassed about winning the prize','She shone a light onto her new certificate','She was very surprised indeed by the result'],
    answer:'She smiled broadly because she was pleased',
    hint:'"Beamed" often describes a very wide, happy smile.',
    explanation:'To <b>beam</b> is to smile very broadly. "Beamed with pride" tells us Maria was extremely pleased with what she had achieved.'}),

  makeMCQ({ id:'g3eng-rdr-011', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "The weather in Mauritius is warm all year round. From November to April, cyclones can form in the Indian Ocean. Schools close when a cyclone warning is issued." When can cyclones form near Mauritius?',
    options:['From November to April','From May to October','From June to August','Only during December'],
    answer:'From November to April',
    hint:'The passage gives the exact months.',
    explanation:'The passage says: "<b>From November to April</b>, cyclones can form in the Indian Ocean."'}),

  makeMCQ({ id:'g3eng-rdr-012', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "The weather in Mauritius is warm all year round. From November to April, cyclones can form in the Indian Ocean. Schools close when a cyclone warning is issued." What happens when a cyclone warning is issued?',
    options:['Schools close','Shops open early','Buses run late','Beaches get busy'],
    answer:'Schools close',
    hint:'Read the last sentence.',
    explanation:'The last sentence tells us: "<b>Schools close</b> when a cyclone warning is issued."'}),

  makeMCQ({ id:'g3eng-rdr-013', chapterId:'g3eng-reading', difficulty:2, subsection:'reading_comprehension',
    question:'Read: "Nia saw her little brother crying in the corner. She sat next to him and gently put her arm around his shoulders. \'It\'s okay,\' she whispered softly." What kind of person does the passage suggest Nia is?',
    options:['Kind and caring','Loud and bossy','Shy and quiet','Strict and serious'],
    answer:'Kind and caring',
    hint:'Look at what Nia does and how she speaks.',
    explanation:'<b>Kind and caring</b> — Nia comforts her crying brother by sitting with him, putting her arm around him, and speaking softly. All these actions show she is kind and caring.' }),

  makeMCQ({ id:'g3eng-rdr-014', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Bats sleep during the day and come out at night to find food. They use sound to navigate in the dark, a skill called echolocation. Most bats eat insects." What is echolocation?',
    options:['Using sound to find the way in the dark','Sleeping inside caves during the daytime','Eating flying insects during the night','Flying very fast through the night air'],
    answer:'Using sound to find the way in the dark',
    hint:'The passage explains the word directly after a comma.',
    explanation:'The passage defines it: "They use <b>sound to navigate in the dark</b>, a skill called echolocation."'}),

  makeMCQ({ id:'g3eng-rdr-015', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Sharks are fish, not mammals. They breathe through gills, not lungs. Unlike most fish, sharks do not have bones — they have cartilage instead." What do sharks breathe through?',
    options:['Gills','Lungs','Their skin','Their mouths'],
    answer:'Gills',
    hint:'The passage compares sharks to mammals when explaining breathing.',
    explanation:'<b>Gills</b> — the passage states "They breathe through gills, not lungs." Gills are the breathing organs of fish.' }),

  makeMCQ({ id:'g3eng-rdr-016', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Sharks are fish, not mammals. They breathe through gills, not lungs. Unlike most fish, sharks do not have bones — they have cartilage instead." What do sharks have instead of bones?',
    options:['Cartilage','Feathers','Muscles','Scales'],
    answer:'Cartilage',
    hint:'The last sentence contains the answer.',
    explanation:'The passage says "sharks do not have bones — they have <b>cartilage</b> instead."'}),

  makeMCQ({ id:'g3eng-rdr-017', chapterId:'g3eng-reading', difficulty:2, subsection:'reading_comprehension',
    question:'Read: "The old lighthouse stood at the top of the cliff. Its beam swept across the dark water every night, warning ships of the dangerous rocks below." What is the PURPOSE of the lighthouse?',
    options:['To warn ships about dangerous rocks','To help fishermen find fish','To light up the beach for tourists','To signal to people on shore'],
    answer:'To warn ships about dangerous rocks',
    hint:'The passage explains WHY the beam sweeps across the water.',
    explanation:'<b>To warn ships about dangerous rocks</b> — the passage says the beam was "warning ships of the dangerous rocks below."' }),

  makeMCQ({ id:'g3eng-rdr-018', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Roses need plenty of sunlight and water to grow well. Plant them in good soil and feed them once a month. Remove dead flowers to encourage new blooms." How often should you feed roses?',
    options:['Once a month','Every day','Once a week','Only in summer'],
    answer:'Once a month',
    hint:'The passage gives a specific time period.',
    explanation:'<b>Once a month</b> — the passage says "feed them once a month."' }),

  makeMCQ({ id:'g3eng-rdr-019', chapterId:'g3eng-reading', difficulty:2, subsection:'reading_comprehension',
    question:'Read: "Dan saved his pocket money for six weeks. On Saturday he went to the toy shop and proudly bought the remote-control car he had dreamed about." What does "proudly" tell you about how Dan felt?',
    options:['He felt pleased with his hard work','He felt sorry about spending it all','He felt surprised by the high price','He felt nervous inside the toy shop'],
    answer:'He felt pleased with his hard work',
    hint:'"Proudly" suggests he felt good about something he achieved.',
    explanation:'"Proudly" describes the <b>satisfaction</b> of reaching a goal — Dan had saved for six weeks to buy that car.'}),

  makeMCQ({ id:'g3eng-rdr-020', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Honey bees live in large groups called colonies. Each colony has one queen bee. The worker bees collect nectar from flowers and use it to make honey." What do worker bees collect?',
    options:['Nectar from flowers','Honey from the hive','Water from rivers','Pollen from trees'],
    answer:'Nectar from flowers',
    hint:'The passage tells you exactly what worker bees collect.',
    explanation:'<b>Nectar from flowers</b> — the passage states "The worker bees collect nectar from flowers."' }),

  makeMCQ({ id:'g3eng-rdr-021', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "The market opens early every Saturday morning. Stallholders sell fresh fruits, vegetables, spices and fish. It is a busy, noisy, colourful place." On which day is the market?',
    options:['Saturday','Sunday','Monday','Friday'],
    answer:'Saturday',
    hint:'The first sentence gives you the day.',
    explanation:'<b>Saturday</b> — the passage states "The market opens early every Saturday morning."' }),

  makeMCQ({ id:'g3eng-rdr-022', chapterId:'g3eng-reading', difficulty:2, subsection:'reading_comprehension',
    question:'Read: "The market opens early every Saturday morning. Stallholders sell fresh fruits, vegetables, spices and fish. It is a busy, noisy, colourful place." Which word in the passage tells you the market has many different sights?',
    options:['colourful','busy','noisy','fresh'],
    answer:'colourful',
    hint:'Which word suggests lots of different colours and variety?',
    explanation:'<b>Colourful</b> suggests the market has many vivid colours and a variety of things to see — it is the word linked to sight.' }),

  makeMCQ({ id:'g3eng-rdr-023', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Elephants are the largest land animals on Earth. They use their trunks to breathe, smell, drink and carry food. Elephants live in family groups led by the oldest female." Who leads an elephant family group?',
    options:['The oldest female','The largest male','The youngest calf','The strongest elephant'],
    answer:'The oldest female',
    hint:'The last sentence answers this question.',
    explanation:'<b>The oldest female</b> — the passage states "Elephants live in family groups led by the oldest female."' }),

  makeMCQ({ id:'g3eng-rdr-024', chapterId:'g3eng-reading', difficulty:1, subsection:'reading_comprehension',
    question:'Read: "Maya practised the piano every evening for three months. When the day of the concert arrived, she played her piece perfectly. The audience clapped loudly." Why did Maya play perfectly?',
    options:['Because she had practised hard for months','Because the concert hall was rather small','Because the piano was a very good one','Because the audience was very friendly'],
    answer:'Because she had practised hard for months',
    hint:'What did Maya do BEFORE the concert to prepare?',
    explanation:'Maya <b>practised every evening for three months</b>, and that is why her performance was perfect.'}),

  makeMCQ({ id:'g3eng-rdr-025', chapterId:'g3eng-reading', difficulty:2, subsection:'reading_comprehension',
    question:'Read: "The village pump was the heart of the community. Everyone came here to collect water, exchange news and greet their neighbours." What does "the heart of the community" mean?',
    options:['The most important central meeting place','The place where the village chief lived','The most beautiful part of the village','A water pump shaped like a big heart'],
    answer:'The most important central meeting place',
    hint:'"Heart" here is used as a metaphor — just as the heart is central to the body, this place was central to village life.',
    explanation:'"The heart of the community" is a metaphor: the pump was the <b>central, vital meeting place</b> where everybody gathered.'}),

  // ── VOCABULARY IN CONTEXT (25 questions) ──────────────────────────────────

  makeMCQ({ id:'g3eng-rdr-026', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The athlete sprinted across the finish line, her face red and her breathing ragged." As used in the passage, what does "ragged" most likely mean?',
    options:['uneven and gasping','slow and very calm','fast and very quiet','loud and quite clear'],
    answer:'uneven and gasping',
    hint:'Think about how someone breathes after running very fast.',
    explanation:'After a sprint, breathing is rough and broken. "<b>Ragged</b>" describes that kind of uneven, gasping breathing.'}),

  makeMCQ({ id:'g3eng-rdr-027', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The ancient temple had stood for hundreds of years. Tourists came from around the world to admire it." As used here, "ancient" means ___.',
    options:['very old','very beautiful','very tall','very broken'],
    answer:'very old',
    hint:'Something that has stood for hundreds of years must be ___.',
    explanation:'<b>Very old</b> — "ancient" means something from a very long time ago. A building standing for hundreds of years is ancient.' }),

  makeMCQ({ id:'g3eng-rdr-028', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The puppy was so timid that it hid behind the sofa whenever a stranger came." As used here, "timid" means ___.',
    options:['shy and fearful','loud and playful','angry and fierce','happy and excited'],
    answer:'shy and fearful',
    hint:'A puppy that hides from strangers must be feeling ___.',
    explanation:'<b>Shy and fearful</b> — the puppy\'s behaviour (hiding from strangers) tells us it is timid, meaning shy and easily frightened.' }),

  makeMCQ({ id:'g3eng-rdr-029', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The chef prepared a sumptuous feast for the celebration." As used here, "sumptuous" most likely means ___.',
    options:['large and impressive','small and quite cheap','plain and rather boring','quick and very simple'],
    answer:'large and impressive',
    hint:'A feast for a celebration is usually special — what kind of word fits?',
    explanation:'"<b>Sumptuous</b>" means rich, grand and expensive — a sumptuous feast is especially large and impressive.'}),

  makeMCQ({ id:'g3eng-rdr-030', chapterId:'g3eng-reading', difficulty:2, subsection:'vocabulary_context',
    question:'Read: "The children were reluctant to leave the playground when the bell rang." As used here, "reluctant" means ___.',
    options:['not wanting to','feeling too tired','feeling very quick','feeling very happy'],
    answer:'not wanting to',
    hint:'If you have to leave somewhere you love, how do you feel about going?',
    explanation:'"<b>Reluctant</b>" means unwilling. The children did not want to leave the playground when the bell rang.'}),

  makeMCQ({ id:'g3eng-rdr-031', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The storm raged all night. By morning, the sea was tranquil once more." As used here, "tranquil" means ___.',
    options:['calm and peaceful','rough and stormy','cold and dark','deep and blue'],
    answer:'calm and peaceful',
    hint:'The sea was stormy, then became the OPPOSITE.',
    explanation:'<b>Calm and peaceful</b> — "tranquil" is the opposite of stormy and wild. After a storm, calm water is described as tranquil.' }),

  makeMCQ({ id:'g3eng-rdr-032', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The student was bewildered by the long instructions and did not know where to start." As used here, "bewildered" means ___.',
    options:['confused and unsure','excited and happy','bored and sleepy','angry and upset'],
    answer:'confused and unsure',
    hint:'When you do not know where to start because something is too confusing, you feel ___.',
    explanation:'<b>Confused and unsure</b> — "bewildered" means very confused. The long instructions made the student feel lost.' }),

  makeMCQ({ id:'g3eng-rdr-033', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The scientist made a remarkable discovery about the deep sea." As used here, "remarkable" means ___.',
    options:['extraordinary and surprising','ordinary and very common','small and quite unimportant','old and rather well-known'],
    answer:'extraordinary and surprising',
    hint:'A discovery described as "remarkable" is not an everyday thing.',
    explanation:'"<b>Remarkable</b>" means unusual enough to deserve attention and admiration.'}),

  makeMCQ({ id:'g3eng-rdr-034', chapterId:'g3eng-reading', difficulty:2, subsection:'vocabulary_context',
    question:'Read: "The explorers trudged through the thick mud for hours." As used here, "trudged" tells you they were walking ___.',
    options:['slowly and with great effort','quickly and quite easily','carefully and very silently','lightly and rather happily'],
    answer:'slowly and with great effort',
    hint:'"Trudged" describes a very heavy, tiring kind of walking.',
    explanation:'To "<b>trudge</b>" is to walk slowly and heavily, usually because you are tired or the ground is difficult.'}),

  makeMCQ({ id:'g3eng-rdr-035', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The rescuers acted swiftly to save the drowning man." As used here, "swiftly" means ___.',
    options:['quickly','slowly','carefully','quietly'],
    answer:'quickly',
    hint:'"Swiftly" is an adverb describing the speed of an action.',
    explanation:'<b>Quickly</b> — "swiftly" means very fast. In a rescue, speed is essential, so acting swiftly means acting very quickly.' }),

  makeMCQ({ id:'g3eng-rdr-036', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The toddler clutched her toy bear tightly as she walked into the new classroom." As used here, "clutched" means ___.',
    options:['held on to very tightly','picked up rather gently','pushed it firmly away','threw it right away'],
    answer:'held on to very tightly',
    hint:'Clutching something means holding it as if you might lose it.',
    explanation:'To "<b>clutch</b>" is to grip something firmly, usually out of nervousness or fear of losing it.'}),

  makeMCQ({ id:'g3eng-rdr-037', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The pupil gave a confident answer in front of the whole class." As used here, "confident" means ___.',
    options:['sure of oneself and not afraid','shy and rather nervous inside','showing off to the whole class','speaking in a very loud voice'],
    answer:'sure of oneself and not afraid',
    hint:'A confident person does not feel nervous.',
    explanation:'"<b>Confident</b>" means you believe in your own ability and are not afraid to show it — it is not the same as showing off or shouting.'}),

  makeMCQ({ id:'g3eng-rdr-038', chapterId:'g3eng-reading', difficulty:2, subsection:'vocabulary_context',
    question:'Read: "The vendor at the market haggled over the price until both he and the customer were satisfied." As used here, "haggled" means ___.',
    options:['argued back and forth over the price','shouted angrily at the customer twice','gave all of the goods away for free','stole the goods from the market stall'],
    answer:'argued back and forth over the price',
    hint:'"Haggling" at a market is about negotiating the price.',
    explanation:'To "<b>haggle</b>" is to bargain over a price, each side offering a different amount until they agree.'}),

  makeMCQ({ id:'g3eng-rdr-039', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The forest was dense and dark, with hardly any sunlight reaching the ground." As used here, "dense" means ___.',
    options:['thick and packed tightly together','wet and rather muddy right underfoot','tall and extremely beautiful to see','empty and completely bare of trees'],
    answer:'thick and packed tightly together',
    hint:'If hardly any sunlight gets through, the trees must be very close together.',
    explanation:'A "<b>dense</b>" forest has trees so thick and close together that hardly any light reaches the ground.'}),

  makeMCQ({ id:'g3eng-rdr-040', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "Grandpa has an extensive collection of stamps from over sixty countries." As used here, "extensive" means ___.',
    options:['very large','very colourful','very rare','very old'],
    answer:'very large',
    hint:'"Extensive" describes the SIZE of the collection.',
    explanation:'<b>Very large</b> — "extensive" means covering a large area or including a great number of things. Sixty countries confirms it is huge.' }),

  makeMCQ({ id:'g3eng-rdr-041', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The tiny kitten was frail and needed careful nursing to survive." As used here, "frail" means ___.',
    options:['weak and delicate','noisy and active','healthy and strong','fluffy and warm'],
    answer:'weak and delicate',
    hint:'Something "frail" needs extra care — what kind of thing does?',
    explanation:'<b>Weak and delicate</b> — "frail" means not strong, easily hurt. The kitten needed nursing because it was too weak to survive on its own.' }),

  makeMCQ({ id:'g3eng-rdr-042', chapterId:'g3eng-reading', difficulty:2, subsection:'vocabulary_context',
    question:'Read: "The teacher commended the class for their excellent behaviour during the school trip." As used here, "commended" means ___.',
    options:['praised','punished','warned','questioned'],
    answer:'praised',
    hint:'"Commended" is used when someone does something good.',
    explanation:'<b>Praised</b> — to "commend" someone means to praise or express approval of them. The teacher praised the class for good behaviour.' }),

  makeMCQ({ id:'g3eng-rdr-043', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The path wound through the garden, past the rose bushes and the old oak tree." As used here, "wound" (said like "wined") means ___.',
    options:['curved and twisted','went quite straight','was rather broken','went steeply uphill'],
    answer:'curved and twisted',
    hint:'A path that "winds" does not go in a straight line.',
    explanation:'When a path "<b>winds</b>", it turns and curves rather than running straight.'}),

  makeMCQ({ id:'g3eng-rdr-044', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The news of the school\'s success spread rapidly throughout the village." As used here, "rapidly" means ___.',
    options:['very quickly','very slowly','very quietly','very loudly'],
    answer:'very quickly',
    hint:'"Rapidly" is an adverb of speed.',
    explanation:'<b>Very quickly</b> — "rapidly" means at a great speed. News that spreads rapidly reaches everyone very fast.' }),

  makeMCQ({ id:'g3eng-rdr-045', chapterId:'g3eng-reading', difficulty:2, subsection:'vocabulary_context',
    question:'Read: "Priya was tenacious in her efforts to learn the guitar. She practised even when her fingers hurt." As used here, "tenacious" means ___.',
    options:['determined and not giving up','quick at learning new things','musical and rather talented','frightened of ever failing'],
    answer:'determined and not giving up',
    hint:'Practising even when it hurts shows great ___.',
    explanation:'"<b>Tenacious</b>" means holding on firmly to a goal in spite of difficulty — Priya kept practising even when her fingers hurt.'}),

  makeMCQ({ id:'g3eng-rdr-046', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The children were famished after a long day at the sports meet." As used here, "famished" means ___.',
    options:['very hungry','very tired','very thirsty','very happy'],
    answer:'very hungry',
    hint:'"Famished" is a strong word for hunger.',
    explanation:'<b>Very hungry</b> — "famished" means extremely hungry, often after going without food for a long time.' }),

  makeMCQ({ id:'g3eng-rdr-047', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The audience was captivated by the performer\'s beautiful singing." As used here, "captivated" means ___.',
    options:['held completely spellbound by it','distracted and rather noisy indeed','frightened and quite badly shocked','bored and completely uninterested'],
    answer:'held completely spellbound by it',
    hint:'To be "captivated" means the performance has you completely in its grip.',
    explanation:'To be "<b>captivated</b>" is to be completely absorbed and enchanted — unable to look away.'}),

  makeMCQ({ id:'g3eng-rdr-048', chapterId:'g3eng-reading', difficulty:1, subsection:'vocabulary_context',
    question:'Read: "The sun blazed down on the dry earth, cracking the mud into pieces." As used here, "blazed" means ___.',
    options:['shone very hotly and intensely','rose slowly in the morning sky','set behind the distant mountains','appeared briefly through the clouds'],
    answer:'shone very hotly and intensely',
    hint:'"Blaze" suggests fire-like intensity.',
    explanation:'"<b>Blazed</b>" describes the sun shining with fierce, burning heat, like a fire.'}),

  makeMCQ({ id:'g3eng-rdr-049', chapterId:'g3eng-reading', difficulty:2, subsection:'vocabulary_context',
    question:'Read: "The old man reminisced about his childhood by the sea." As used here, "reminisced" means ___.',
    options:['thought fondly about past memories','talked angrily about his own past','dreamed about his distant future','forgot his childhood completely'],
    answer:'thought fondly about past memories',
    hint:'"Reminiscing" is something you do when you think about the past with warm feelings.',
    explanation:'To "<b>reminisce</b>" is to think or talk warmly about pleasant things that happened in the past.'}),

  makeMCQ({ id:'g3eng-rdr-050', chapterId:'g3eng-reading', difficulty:2, subsection:'vocabulary_context',
    question:'Read: "The young girl was apprehensive about her first day at the new school." As used here, "apprehensive" means ___.',
    options:['worried and slightly fearful','proud and very confident','bored and quite uninterested','excited and extremely happy'],
    answer:'worried and slightly fearful',
    hint:'Being apprehensive is similar to being nervous or anxious.',
    explanation:'"<b>Apprehensive</b>" means feeling worried or slightly frightened about something that is about to happen.'}),

  // ── TEXT FEATURES (25 questions) ──────────────────────────────────────────

  makeMCQ({ id:'g3eng-rdr-051', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'What is the PURPOSE of a TITLE in a text?',
    options:['To tell the reader what the text is about','To tell the reader who wrote the text','To give extra information about a picture','To list what is inside the text'],
    answer:'To tell the reader what the text is about',
    hint:'The title is the name of the text — what does a name do?',
    explanation:'<b>To tell the reader what the text is about</b> — a title introduces the topic of the text so the reader knows what to expect.' }),

  makeMCQ({ id:'g3eng-rdr-052', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'What is a CAPTION in a text?',
    options:['Words under a picture explaining it','A heading for a whole new section','A list of words at the back of a book','The main title given to the text'],
    answer:'Words under a picture explaining it',
    hint:'You find captions just below or next to images.',
    explanation:'A <b>caption</b> is the line of words printed under a picture to explain what it shows.'}),

  makeMCQ({ id:'g3eng-rdr-053', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'What does a HEADING help you do?',
    options:['Find what a new section is about','Understand the meaning of a word','Find a word in the dictionary','Tell you who wrote the text'],
    answer:'Find what a new section is about',
    hint:'Headings appear at the start of each new section.',
    explanation:'A <b>heading</b> is the title of a section, so it tells you what that part of the text is about.'}),

  makeMCQ({ id:'g3eng-rdr-054', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'Which text feature would you use to find information about a specific topic in a non-fiction book?',
    options:['The index or contents page','The title on the front cover','The picture on page 1','The caption under a photo'],
    answer:'The index or contents page',
    hint:'These pages are specifically designed to help you FIND things.',
    explanation:'<b>The index or contents page</b> — the contents page shows you what is in each chapter; the index lists topics alphabetically with page numbers.' }),

  makeMCQ({ id:'g3eng-rdr-055', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'Why are some words printed in BOLD in a non-fiction text?',
    options:['Because they are important key words','Because they are the first words used','Because the author made a mistake','Because they are the longest words'],
    answer:'Because they are important key words',
    hint:'Bold text draws your eye — it is used to highlight something.',
    explanation:'<b>Bold</b> is used to emphasise key words and important ideas that the reader should notice.'}),

  makeMCQ({ id:'g3eng-rdr-056', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'In an information text about animals, you see a box on the side with extra facts called "Did You Know?" This is an example of a ___.',
    options:['sidebar or fact box','glossary or word list','caption or picture label','heading or section title'],
    answer:'sidebar or fact box',
    hint:'It is a separate box that gives additional information.',
    explanation:'A <b>sidebar</b> (or fact box) holds extra information related to the main text but set apart from the main paragraphs.'}),

  makeMCQ({ id:'g3eng-rdr-057', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'What is a GLOSSARY in a non-fiction book?',
    options:['A list of difficult words and meanings','A list of the chapters in the book','A list of the pictures in the book','The name and address of the author'],
    answer:'A list of difficult words and meanings',
    hint:'If you do not understand a word in the text, you look here.',
    explanation:'A <b>glossary</b> sits at the back of a non-fiction book and explains the difficult or technical words used in it.'}),

  makeMCQ({ id:'g3eng-rdr-058', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'You are reading a recipe. The ingredients are listed with bullet points (•). What is the purpose of the bullet points?',
    options:['To list items clearly so they are easy to read','To show the order in which things are done','To give extra facts about the recipe','To show which ingredients are most important'],
    answer:'To list items clearly so they are easy to read',
    hint:'Bullet points are used to organise a LIST.',
    explanation:'<b>To list items clearly so they are easy to read</b> — bullet points organise a list so each item stands alone and is easy to see.' }),

  makeMCQ({ id:'g3eng-rdr-059', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'In a recipe, the METHOD section uses NUMBERED STEPS (1, 2, 3...). Why?',
    options:['To show the order things must be done','To list the ingredients that are needed','To show how long each step will take','To give the name of the chef who wrote it'],
    answer:'To show the order things must be done',
    hint:'In instructions, ORDER matters — what feature shows order?',
    explanation:'<b>Numbered steps</b> make the sequence clear, so you know exactly what to do first, second and third.'}),

  makeMCQ({ id:'g3eng-rdr-060', chapterId:'g3eng-reading', difficulty:2, subsection:'text_features',
    question:'Look at this text feature: "⚠ WARNING: Do not leave the oven unattended." What is the purpose of the warning symbol ⚠?',
    options:['To draw attention to safety information','To tell you just how hot the oven gets','To mark the end of the recipe section','To show the name of the recipe author'],
    answer:'To draw attention to safety information',
    hint:'Warning symbols are used to alert readers to something important.',
    explanation:'The ⚠ symbol is a recognised warning sign: it makes the reader stop and read <b>important safety information</b>.'}),

  makeMCQ({ id:'g3eng-rdr-061', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'A poster has large, bright letters for its main message and smaller text below for details. Why are the main words LARGER?',
    options:['To catch the eye and show what matters','Because they sit at the top of the page','Because they are much harder to spell','Because the printer has made a mistake'],
    answer:'To catch the eye and show what matters',
    hint:'Designers make important things bigger so you notice them first.',
    explanation:'Large type <b>draws the eye first</b>, so the most important message is the one the reader sees straight away.'}),

  makeMCQ({ id:'g3eng-rdr-062', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'What does a MAP KEY (or legend) do?',
    options:['Explains what the symbols and colours mean','Gives the name of the person who drew it','Shows which direction on the map is North','Shows how big the whole area really is'],
    answer:'Explains what the symbols and colours mean',
    hint:'A key "unlocks" the meaning of what you see on the map.',
    explanation:'A <b>map key</b> (or legend) explains what each symbol and colour on the map stands for. Without it the map would be impossible to read.'}),

  makeMCQ({ id:'g3eng-rdr-063', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'In a non-fiction book about the ocean, you see: "Chapter 3: Life on the Coral Reef". This line in the table of contents tells you ___.',
    options:['What topic Chapter 3 covers','Where Chapter 3 begins in it','How long Chapter 3 really is','Who actually wrote Chapter 3'],
    answer:'What topic Chapter 3 covers',
    hint:'The text after the chapter number is its title, which names the topic.',
    explanation:'The chapter title "Life on the Coral Reef" tells you the <b>topic</b> of that chapter.'}),

  makeMCQ({ id:'g3eng-rdr-064', chapterId:'g3eng-reading', difficulty:2, subsection:'text_features',
    question:'You are reading a newspaper article. It has a headline, then a short paragraph giving the most important facts, then more detail in the paragraphs below. Why is the most important information at the TOP?',
    options:['So busy readers get the key facts quickly','Because the top of the page has more room','Because the headline is nearly always wrong','Because readers read from bottom to top'],
    answer:'So busy readers get the key facts quickly',
    hint:'Newspapers are designed for readers who may not have much time.',
    explanation:'This is the "inverted pyramid": the most important facts come <b>first</b>, so a reader who stops early still knows what happened.'}),

  makeMCQ({ id:'g3eng-rdr-065', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'In which type of text would you most likely find numbered steps?',
    options:['A recipe or instruction manual','A story about a lost princess','A poem about the deep sea','A letter to a close friend'],
    answer:'A recipe or instruction manual',
    hint:'Numbered steps are used when ORDER matters.',
    explanation:'A <b>recipe or instruction manual</b> uses numbered steps because the actions have to be done in a set order.'}),

  makeMCQ({ id:'g3eng-rdr-066', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'A text type that has a "Dear ___," at the beginning and "Yours sincerely," at the end is a ___.',
    options:['formal letter','picture poster','cooking recipe','school report'],
    answer:'formal letter',
    hint:'Think about the greeting and the sign-off.',
    explanation:'"Dear [Name]," at the top and "Yours sincerely," at the bottom are the standard features of a <b>formal letter</b>.'}),

  makeMCQ({ id:'g3eng-rdr-067', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'What text feature tells you that you have reached a NEW PARAGRAPH?',
    options:['An indented first line or a blank line','A capital letter in the middle of a word','A full stop at the start of the line','A small picture beside the writing'],
    answer:'An indented first line or a blank line',
    hint:'Paragraphs are separated visually.',
    explanation:'A new paragraph is marked by an <b>indented first line</b> or a blank line before it, showing that a new idea is beginning.'}),

  makeMCQ({ id:'g3eng-rdr-068', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'A story includes the words: "Once upon a time..." What does this phrase tell you about the text type?',
    options:['It is a fairy tale or old story','It is a letter to a friend','It is a recipe for a cake','It is a report in a newspaper'],
    answer:'It is a fairy tale or old story',
    hint:'"Once upon a time" is the classic opening of one particular type of story.',
    explanation:'"Once upon a time" is the traditional opening of a <b>fairy tale</b> or folk story.'}),

  makeMCQ({ id:'g3eng-rdr-069', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'In a poster advertising a school sports day, you see: "WHEN: Saturday 10 June, 9 am". What is the purpose of "WHEN:" in bold?',
    options:['To help you find the date and time fast','To explain the rules of the sports day','To list the teachers who are in charge','To show the title given to the poster'],
    answer:'To help you find the date and time fast',
    hint:'Labels like WHEN, WHERE and WHO help readers skim for specific information.',
    explanation:'Bold labels on a poster let a reader <b>scan</b> for exactly the information they need — here, the date and time.'}),

  makeMCQ({ id:'g3eng-rdr-070', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'Which text feature helps you understand the meaning of a difficult word WITHOUT going to a dictionary?',
    options:['A glossary at the back of the book','A caption printed under a picture','The contents page at the very front','The number given to that chapter'],
    answer:'A glossary at the back of the book',
    hint:'This is the feature specifically designed to explain vocabulary.',
    explanation:'A <b>glossary</b> at the back of a non-fiction book defines the difficult or technical words used in the text.'}),

  makeMCQ({ id:'g3eng-rdr-071', chapterId:'g3eng-reading', difficulty:2, subsection:'text_features',
    question:'A text uses paragraphs with these headings: "What are bees?", "Where do bees live?", "Why are bees important?". What type of text is this MOST LIKELY to be?',
    options:['A non-fiction information text','A fictional adventure story','A personal letter to a friend','A poem about the countryside'],
    answer:'A non-fiction information text',
    hint:'Information texts use question headings to organise facts by topic.',
    explanation:'Question-style headings that organise facts by topic are typical of a <b>non-fiction information text</b>.'}),

  makeMCQ({ id:'g3eng-rdr-072', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'Which part of a newspaper article tells you what the whole article is about IN JUST A FEW WORDS?',
    options:['The headline','The photograph','The last line','The first line'],
    answer:'The headline',
    hint:'You read this first, before anything else in the article.',
    explanation:'A <b>headline</b> sums up an article in a short, catchy phrase designed to catch the reader\'s attention.'}),

  makeMCQ({ id:'g3eng-rdr-073', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'A text begins: "Ingredients: 2 eggs, 1 cup of flour, 1 cup of milk." This format tells you the text is most likely a ___.',
    options:['recipe','diary entry','story','poem'],
    answer:'recipe',
    hint:'Listing ingredients is a feature of one specific text type.',
    explanation:'<b>Recipe</b> — listing ingredients is the first section of a recipe. Other text types do not have ingredient lists.' }),

  makeMCQ({ id:'g3eng-rdr-074', chapterId:'g3eng-reading', difficulty:1, subsection:'text_features',
    question:'Which statement about ILLUSTRATIONS in a text is TRUE?',
    options:['They help readers picture the information','They are always placed at the end of a text','They replace all of the writing in a text','They are only ever used in story books'],
    answer:'They help readers picture the information',
    hint:'Pictures and diagrams support and enhance the text.',
    explanation:'Illustrations, diagrams and photographs help the reader <b>understand and picture</b> the information. They are used in non-fiction too, they appear throughout a text, and they never replace the writing.'}),

  makeMCQ({ id:'g3eng-rdr-075', chapterId:'g3eng-reading', difficulty:2, subsection:'text_features',
    question:'A student reads a non-fiction text and wants to find information about "food chains" quickly. Which text feature should they use FIRST?',
    options:['The index at the back','The title on the cover','A picture in the middle','The first paragraph'],
    answer:'The index at the back',
    hint:'The index lists topics alphabetically with page numbers.',
    explanation:'<b>The index</b> — the index lists keywords alphabetically with the page numbers where they appear, making it the fastest way to find a specific topic.' })

);

})();
