'use strict';
// Grade 3 French – Expression orale
// IDs: g3fr-eo-001 … g3fr-eo-075

(function () {

const CH = 'g3fr-expression-orale';

STATIC_QUESTIONS.push(

  // ── VOCABULAIRE DESCRIPTIF (25 questions) ────────────────────────────────

  makeMCQ({ id:'g3fr-eo-001', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux un éléphant ?',
    options:['grand','petit','léger','rapide'],
    answer:'grand',
    hint:'Pense à la taille d\'un éléphant par rapport à d\'autres animaux.',
    explanation:'Un éléphant est <b>grand</b> et lourd. C\'est l\'adjectif qui le décrit le mieux parmi les choix.' }),

  makeMCQ({ id:'g3fr-eo-002', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif est le contraire de "heureux" ?',
    options:['triste','joyeux','content','souriant'],
    answer:'triste',
    hint:'Le contraire d\'une émotion positive est une émotion négative.',
    explanation:'Le contraire (antonyme) d\'<b>heureux</b> est <b>triste</b>. Les autres options sont tous des synonymes d\'heureux.' }),

  makeMCQ({ id:'g3fr-eo-003', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif est le contraire de "chaud" ?',
    options:['froid','tiède','brûlant','doux'],
    answer:'froid',
    hint:'Quand il ne fait pas chaud, il fait ___.',
    explanation:'Le contraire de <b>chaud</b> est <b>froid</b>. "Tiède" signifie ni chaud ni froid ; "brûlant" est encore plus chaud.' }),

  makeMCQ({ id:'g3fr-eo-004', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif est le contraire de "propre" ?',
    options:['sale','beau','nouveau','grand'],
    answer:'sale',
    hint:'Quand quelque chose n\'est pas propre, il est ___.',
    explanation:'Le contraire de <b>propre</b> est <b>sale</b>.' }),

  makeMCQ({ id:'g3fr-eo-005', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel mot est un synonyme de "rapide" ?',
    options:['vite','lent','calme','doux'],
    answer:'vite',
    hint:'Un synonyme a un sens similaire, pas opposé.',
    explanation:'<b>Vite</b> et <b>rapide</b> sont synonymes. On peut dire "il court vite" ou "il est rapide".' }),

  makeMCQ({ id:'g3fr-eo-006', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel mot est un synonyme de "beau" ?',
    options:['joli','laid','vieux','petit'],
    answer:'joli',
    hint:'Un synonyme de "beau" décrit quelque chose qui plaît à regarder.',
    explanation:'<b>Joli</b> est un synonyme de <b>beau</b>. "Laid" est le contraire.' }),

  makeMCQ({ id:'g3fr-eo-007', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux une fraise ?',
    options:['rouge','bleu','jaune','vert'],
    answer:'rouge',
    hint:'Pense à la couleur d\'une fraise mûre.',
    explanation:'Une fraise mûre est <b>rouge</b>. C\'est l\'adjectif de couleur qui lui correspond.' }),

  makeMCQ({ id:'g3fr-eo-008', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux un citron ?',
    options:['acide','sucré','salé','amer'],
    answer:'acide',
    hint:'Le citron est connu pour son goût piquant sur la langue.',
    explanation:'Le citron est <b>acide</b>. C\'est son goût caractéristique.' }),

  makeMCQ({ id:'g3fr-eo-009', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif est le contraire de "long" ?',
    options:['court','grand','haut','large'],
    answer:'court',
    hint:'Si une corde n\'est pas longue, elle est ___.',
    explanation:'Le contraire de <b>long</b> est <b>court</b>. Ex : un chemin long / un chemin court.' }),

  makeMCQ({ id:'g3fr-eo-010', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux un rocher ?',
    options:['dur','mou','léger','doux'],
    answer:'dur',
    hint:'Si tu essaies d\'écraser un rocher, que ressens-tu ?',
    explanation:'Un rocher est <b>dur</b>. On ne peut pas le déformer facilement.' }),

  makeMCQ({ id:'g3fr-eo-011', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux une plume d\'oiseau ?',
    options:['légère','lourde','dure','froide'],
    answer:'légère',
    hint:'Une plume vole dans l\'air facilement.',
    explanation:'Une plume est <b>légère</b>. Elle pèse presque rien et vole dans l\'air facilement.' }),

  makeMCQ({ id:'g3fr-eo-012', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel mot est un synonyme de "manger" ?',
    options:['dévorer','courir','dormir','lire'],
    answer:'dévorer',
    hint:'"Dévorer" signifie manger très vite ou avec appétit.',
    explanation:'<b>Dévorer</b> est un synonyme de <b>manger</b> (avec une idée d\'intensité). On peut aussi utiliser "avaler", "grignoter".' }),

  makeMCQ({ id:'g3fr-eo-013', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif est le contraire de "vieux" ?',
    options:['jeune','grand','fort','beau'],
    answer:'jeune',
    hint:'Le contraire d\'une personne âgée est une personne ___.',
    explanation:'Le contraire de <b>vieux</b> est <b>jeune</b>. On peut aussi dire "neuf" pour un objet.' }),

  makeMCQ({ id:'g3fr-eo-014', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux le ciel la nuit ?',
    options:['sombre','clair','rouge','chaud'],
    answer:'sombre',
    hint:'La nuit, il n\'y a pas de soleil, donc le ciel est ___.',
    explanation:'La nuit, le ciel est <b>sombre</b> (noir/foncé). On peut voir les étoiles dans ce ciel sombre.' }),

  makeMCQ({ id:'g3fr-eo-015', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel mot est un synonyme de "content" ?',
    options:['heureux','triste','fâché','fatigué'],
    answer:'heureux',
    hint:'Si tu es content, tu te sens bien. Cherche un synonyme de cette sensation.',
    explanation:'<b>Heureux</b> est un synonyme de <b>content</b>. Les deux expriment une émotion positive.' }),

  makeMCQ({ id:'g3fr-eo-016', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux de la glace ?',
    options:['froide','chaude','molle','douce'],
    answer:'froide',
    hint:'La glace fond quand il fait chaud. Qu\'est-ce que ça nous dit sur sa température ?',
    explanation:'La glace est <b>froide</b>. Elle fond parce que la chaleur la transforme en eau.' }),

  makeMCQ({ id:'g3fr-eo-017', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel est le contraire de "silencieux" ?',
    options:['bruyant','calme','doux','lent'],
    answer:'bruyant',
    hint:'Si quelque chose n\'est pas silencieux, il fait beaucoup de ___.',
    explanation:'Le contraire de <b>silencieux</b> est <b>bruyant</b>. Un endroit bruyant fait beaucoup de bruit.' }),

  makeMCQ({ id:'g3fr-eo-018', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux une baleine ?',
    options:['énorme','minuscule','légère','rapide'],
    answer:'énorme',
    hint:'La baleine est le plus grand animal du monde.',
    explanation:'Une baleine est <b>énorme</b>. C\'est le plus grand animal du monde.' }),

  makeMCQ({ id:'g3fr-eo-019', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel mot est un synonyme de "gentil" ?',
    options:['aimable','méchant','dur','froid'],
    answer:'aimable',
    hint:'Un synonyme de gentil décrit quelqu\'un de sympathique et doux.',
    explanation:'<b>Aimable</b> est un synonyme de <b>gentil</b>. On peut aussi dire "sympathique" ou "doux".' }),

  makeMCQ({ id:'g3fr-eo-020', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel est le contraire de "fort" (en parlant d\'une personne) ?',
    options:['faible','grand','lent','vieux'],
    answer:'faible',
    hint:'Si quelqu\'un n\'est pas fort, il est ___.',
    explanation:'Le contraire de <b>fort</b> est <b>faible</b>. Une personne faible n\'a pas beaucoup de force.' }),

  makeMCQ({ id:'g3fr-eo-021', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux du coton ?',
    options:['doux','dur','chaud','lourd'],
    answer:'doux',
    hint:'Le coton est souvent utilisé pour les jouets en peluche et les vêtements confortables.',
    explanation:'Le coton est <b>doux</b> au toucher. C\'est pour ça qu\'on l\'utilise pour les vêtements et les jouets.' }),

  makeMCQ({ id:'g3fr-eo-022', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel est le contraire de "courageux" ?',
    options:['peureux','fort','grand','joyeux'],
    answer:'peureux',
    hint:'Quelqu\'un qui n\'est pas courageux a peur facilement.',
    explanation:'Le contraire de <b>courageux</b> est <b>peureux</b>. Un enfant peureux a souvent peur.' }),

  makeMCQ({ id:'g3fr-eo-023', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel mot décrit le mieux la mer ?',
    options:['vaste','petite','sèche','chaude toujours'],
    answer:'vaste',
    hint:'"Vaste" signifie très grand, immense.',
    explanation:'La mer est <b>vaste</b> (immense). On ne peut pas en voir la fin à l\'horizon.' }),

  makeMCQ({ id:'g3fr-eo-024', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel est le contraire de "nouveau" ?',
    options:['vieux','beau','grand','fort'],
    answer:'vieux',
    hint:'Le contraire de quelque chose de récent est quelque chose d\'___.',
    explanation:'Le contraire de <b>nouveau</b> est <b>vieux</b> (ou "ancien"). Un vieux livre est un livre qui existe depuis longtemps.' }),

  makeMCQ({ id:'g3fr-eo-025', chapterId:CH, difficulty:1, subsection:'vocabulaire_descriptif',
    question:'Quel adjectif décrit le mieux un hôpital ?',
    options:['propre','sale','bruyant','sombre'],
    answer:'propre',
    hint:'Dans un hôpital, la propreté est très importante pour éviter les maladies.',
    explanation:'Un hôpital doit être <b>propre</b>. La propreté empêche les microbes de se propager.' }),

  // ── RACONTER À L'ORAL (25 questions) ─────────────────────────────────────

  makeMCQ({ id:'g3fr-eo-026', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel mot indique ce qui arrive EN PREMIER dans un récit ?',
    options:['D\'abord','Ensuite','Enfin','Puis'],
    answer:'D\'abord',
    hint:'Il y a un ordre pour raconter : premier, deuxième, dernier.',
    explanation:'<b>D\'abord</b> (ou "premièrement", "pour commencer") indique le premier événement d\'un récit.' }),

  makeMCQ({ id:'g3fr-eo-027', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel mot indique ce qui arrive EN DERNIER dans un récit ?',
    options:['Enfin','D\'abord','Puis','Ensuite'],
    answer:'Enfin',
    hint:'La séquence est : d\'abord → ensuite/puis → enfin.',
    explanation:'<b>Enfin</b> (ou "pour finir", "finalement") indique le dernier événement d\'un récit.' }),

  makeMCQ({ id:'g3fr-eo-028', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Continue l\'histoire de façon logique : "D\'abord, le bébé pleure. Ensuite, ___."',
    options:['sa maman le prend dans ses bras','il s\'endort tout seul','il joue dehors','il mange une glace'],
    answer:'sa maman le prend dans ses bras',
    hint:'Que fait une maman quand son bébé pleure ?',
    explanation:'La suite logique est que <b>sa maman le prend dans ses bras</b> pour le consoler.' }),

  makeMCQ({ id:'g3fr-eo-029', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quelle phrase est la meilleure CONCLUSION pour finir une histoire ?',
    options:['Enfin, ils vécurent heureux pour toujours.','D\'abord, il était une fois un roi.','Ensuite, le loup arriva.','Puis, ils partirent dans la forêt.'],
    answer:'Enfin, ils vécurent heureux pour toujours.',
    hint:'Une conclusion finit l\'histoire. Le mot "enfin" nous aide à l\'identifier.',
    explanation:'"<b>Enfin, ils vécurent heureux pour toujours.</b>" est une conclusion car elle utilise "enfin" et donne une fin à l\'histoire.' }),

  makeMCQ({ id:'g3fr-eo-030', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel mot peut remplacer "ensuite" dans un récit ?',
    options:['puis','d\'abord','enfin','parce que'],
    answer:'puis',
    hint:'"Puis" et "ensuite" indiquent tous les deux ce qui vient après.',
    explanation:'<b>Puis</b> est un synonyme de <b>ensuite</b>. Les deux servent à introduire la suite des événements.' }),

  makeMCQ({ id:'g3fr-eo-031', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Dans un récit, pourquoi utilise-t-on des mots comme "d\'abord, ensuite, enfin" ?',
    options:['Pour montrer l\'ordre des événements','Pour décrire les personnages','Pour donner la couleur des objets','Pour poser des questions'],
    answer:'Pour montrer l\'ordre des événements',
    hint:'Ces mots s\'appellent des connecteurs de temps ou de séquence.',
    explanation:'Les mots <b>d\'abord, ensuite, enfin</b> s\'appellent des connecteurs temporels. Ils montrent l\'ordre des événements dans un récit.' }),

  makeMCQ({ id:'g3fr-eo-032', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Continue l\'histoire : "Tom a perdu son chat. Il le cherche partout. Enfin, ___."',
    options:['il retrouve son chat sous le lit','il va à l\'école','il achète un chien','il mange son dîner'],
    answer:'il retrouve son chat sous le lit',
    hint:'"Enfin" annonce la conclusion. Qu\'est-ce qui résoudrait le problème de Tom ?',
    explanation:'La fin logique est qu\'<b>il retrouve son chat sous le lit</b>. Le mot "enfin" annonce la résolution du problème.' }),

  makeMCQ({ id:'g3fr-eo-033', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quelle phrase est la meilleure INTRODUCTION pour commencer une histoire ?',
    options:['Il était une fois un petit garçon nommé Jules.','Enfin, Jules rentra chez lui.','Puis, Jules traversa la forêt.','Jules dit au revoir à ses amis.'],
    answer:'Il était une fois un petit garçon nommé Jules.',
    hint:'Une introduction présente les personnages au début de l\'histoire.',
    explanation:'"<b>Il était une fois un petit garçon nommé Jules.</b>" est une introduction classique qui présente le personnage principal.' }),

  makeMCQ({ id:'g3fr-eo-034', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Lis les phrases et trouve l\'ordre correct : A – Enfin, il dort. B – D\'abord, il se lave les dents. C – Ensuite, il met son pyjama.',
    options:['B, C, A','A, B, C','C, A, B','B, A, C'],
    answer:'B, C, A',
    hint:'Utilise les mots d\'abord (B), ensuite (C), enfin (A).',
    explanation:'L\'ordre correct est <b>B (d\'abord), C (ensuite), A (enfin)</b> : se laver → pyjama → dormir.' }),

  makeMCQ({ id:'g3fr-eo-035', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel mot montre la cause dans une histoire ?',
    options:['parce que','ensuite','d\'abord','enfin'],
    answer:'parce que',
    hint:'"Parce que" explique la raison d\'un événement.',
    explanation:'<b>Parce que</b> montre la cause : "Il pleure <b>parce que</b> il a mal." Alors que "d\'abord, ensuite, enfin" montrent l\'ordre.' }),

  makeMCQ({ id:'g3fr-eo-036', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Continue l\'histoire : "La petite fille plante une graine. Chaque jour, elle l\'arrose. Un mois plus tard, ___."',
    options:['une belle fleur pousse','elle achète une autre graine','il pleut beaucoup','le jardin est vide'],
    answer:'une belle fleur pousse',
    hint:'Que se passe-t-il quand on plante et arrose une graine pendant longtemps ?',
    explanation:'La suite logique est qu\'<b>une belle fleur pousse</b>. Planter + arroser + temps = fleur qui pousse.' }),

  makeMCQ({ id:'g3fr-eo-037', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel mot est le mieux pour COMMENCER un récit ?',
    options:['Un jour','Enfin','Puis','Ensuite'],
    answer:'Un jour',
    hint:'"Un jour" introduit l\'événement de départ d\'une histoire.',
    explanation:'"<b>Un jour</b>" est une expression classique pour commencer un récit et situer l\'action dans le temps.' }),

  makeMCQ({ id:'g3fr-eo-038', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quelle phrase décrit le mieux un personnage courageux dans une histoire ?',
    options:['Il sauta dans l\'eau pour sauver son ami.','Il courut se cacher sous son lit.','Il pleura très fort.','Il attendit que quelqu\'un d\'autre agisse.'],
    answer:'Il sauta dans l\'eau pour sauver son ami.',
    hint:'Le courage, c\'est faire quelque chose de difficile pour aider les autres.',
    explanation:'"<b>Il sauta dans l\'eau pour sauver son ami.</b>" décrit un acte courageux car il affronte le danger pour aider.' }),

  makeMCQ({ id:'g3fr-eo-039', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Dans un récit, comment appelle-t-on les êtres (personnes ou animaux) qui participent à l\'histoire ?',
    options:['Les personnages','Les décors','Les titres','Les chapitres'],
    answer:'Les personnages',
    hint:'Ce sont eux qui font les actions dans l\'histoire.',
    explanation:'Les êtres qui font les actions dans une histoire s\'appellent les <b>personnages</b>.' }),

  makeMCQ({ id:'g3fr-eo-040', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quelle expression utilise-t-on souvent pour finir un conte ?',
    options:['Ils vécurent heureux et eurent beaucoup d\'enfants.','Il était une fois…','Un jour, dans un pays lointain…','Et le lendemain…'],
    answer:'Ils vécurent heureux et eurent beaucoup d\'enfants.',
    hint:'C\'est une formule de fin de conte très connue en français.',
    explanation:'"<b>Ils vécurent heureux et eurent beaucoup d\'enfants.</b>" est la formule finale classique des contes français, l\'équivalent de "happily ever after" en anglais.' }),

  makeMCQ({ id:'g3fr-eo-041', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Lis : "Soudain, un bruit fort se fit entendre." Quel mot indique que quelque chose arrive de manière inattendue ?',
    options:['Soudain','un','bruit','entendre'],
    answer:'Soudain',
    hint:'Ce mot exprime la surprise ou l\'imprévu.',
    explanation:'<b>Soudain</b> (ou "tout à coup", "brusquement") indique qu\'un événement arrive de façon inattendue.' }),

  makeMCQ({ id:'g3fr-eo-042', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel connecteur introduit une conclusion dans un récit ?',
    options:['Pour finir','D\'abord','Soudain','Parce que'],
    answer:'Pour finir',
    hint:'"Pour finir" signale la fin d\'un texte.',
    explanation:'"<b>Pour finir</b>" (comme "enfin", "finalement") est un connecteur de conclusion qui signale la fin d\'un récit.' }),

  makeMCQ({ id:'g3fr-eo-043', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Continue l\'histoire : "La princesse est enfermée dans la tour. Le chevalier arrive. Il ___."',
    options:['la libère','part en vacances','mange un gâteau','lit un livre'],
    answer:'la libère',
    hint:'Dans les contes, le chevalier vient pour aider la princesse.',
    explanation:'La suite logique est que le chevalier <b>la libère</b>. C\'est le schéma classique du conte : problème → héros → solution.' }),

  makeMCQ({ id:'g3fr-eo-044', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel mot exprime le TEMPS dans un récit (quand l\'action se passe) ?',
    options:['Le lendemain','parce que','très','mais'],
    answer:'Le lendemain',
    hint:'"Le lendemain" dit QUAND quelque chose arrive.',
    explanation:'"<b>Le lendemain</b>" est une expression de temps qui dit quand l\'action se passe. D\'autres exemples : "hier", "le matin", "en hiver".' }),

  makeMCQ({ id:'g3fr-eo-045', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel mot exprime le LIEU dans un récit (où l\'action se passe) ?',
    options:['Dans la forêt','parce que','soudain','puis'],
    answer:'Dans la forêt',
    hint:'"Dans la forêt" dit OÙ quelque chose arrive.',
    explanation:'"<b>Dans la forêt</b>" est une indication de lieu. Elle dit où se passe l\'action.' }),

  makeMCQ({ id:'g3fr-eo-046', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Lis les phrases et trouve l\'ordre : A – Il mange sa soupe. B – Il pose son sac. C – Paul arrive de l\'école.',
    options:['C, B, A','A, B, C','B, C, A','C, A, B'],
    answer:'C, B, A',
    hint:'Pense à l\'ordre logique des actions après l\'école.',
    explanation:'L\'ordre logique est : <b>C (arriver) → B (poser son sac) → A (manger)</b>.' }),

  makeMCQ({ id:'g3fr-eo-047', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Comment s\'appelle l\'endroit ou l\'époque où se déroule une histoire ?',
    options:['Le cadre (lieu et temps)','Le personnage','Le titre','La fin'],
    answer:'Le cadre (lieu et temps)',
    hint:'Le cadre répond aux questions "où ?" et "quand ?" de l\'histoire.',
    explanation:'Le <b>cadre</b> d\'une histoire indique le lieu (où ?) et le temps (quand ?). Ex : "Dans un château au Moyen Âge".' }),

  makeMCQ({ id:'g3fr-eo-048', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Quel mot indique une action qui arrive DE FAÇON INATTENDUE ?',
    options:['Tout à coup','D\'abord','Enfin','Parce que'],
    answer:'Tout à coup',
    hint:'"Tout à coup" exprime une surprise dans l\'histoire.',
    explanation:'"<b>Tout à coup</b>" (synonyme de "soudain") indique une action inattendue qui change le cours de l\'histoire.' }),

  makeMCQ({ id:'g3fr-eo-049', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Continue logiquement : "Le garçon tomba de son vélo. Il avait très mal. Sa mère ___."',
    options:['le soigna avec soin','l\'envoya jouer dehors','lui dit de courir','prépara le dîner'],
    answer:'le soigna avec soin',
    hint:'Que fait une maman quand son enfant s\'est blessé ?',
    explanation:'La suite logique est que sa mère <b>le soigna avec soin</b>. C\'est la réaction naturelle d\'une mère face à un enfant blessé.' }),

  makeMCQ({ id:'g3fr-eo-050', chapterId:CH, difficulty:1, subsection:'recit_oral',
    question:'Dans quel ordre correct une histoire est-elle généralement racontée ?',
    options:['Début – Milieu – Fin','Fin – Début – Milieu','Milieu – Fin – Début','Fin – Milieu – Début'],
    answer:'Début – Milieu – Fin',
    hint:'On raconte une histoire dans l\'ordre normal du temps.',
    explanation:'Une histoire est racontée dans l\'ordre chronologique : <b>Début</b> (introduction) → <b>Milieu</b> (aventures/problème) → <b>Fin</b> (conclusion).' }),

  // ── QUESTIONS ET RÉPONSES (25 questions) ─────────────────────────────────

  makeMCQ({ id:'g3fr-eo-051', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "dans le jardin". Quelle était la question ?',
    options:['Où joues-tu ?','Quand joues-tu ?','Qui joues-tu ?','Comment joues-tu ?'],
    answer:'Où joues-tu ?',
    hint:'"Dans le jardin" indique un lieu. Quel mot interrogatif demande un lieu ?',
    explanation:'"<b>Où</b>" demande un lieu. La réponse "dans le jardin" répond à la question "Où joues-tu ?"' }),

  makeMCQ({ id:'g3fr-eo-052', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "le matin". Quelle était la question ?',
    options:['Quand te lèves-tu ?','Où te lèves-tu ?','Qui te lève ?','Comment te lèves-tu ?'],
    answer:'Quand te lèves-tu ?',
    hint:'"Le matin" indique un moment dans le temps. Quel mot interrogatif demande le temps ?',
    explanation:'"<b>Quand</b>" demande le moment. La réponse "le matin" répond à "Quand te lèves-tu ?"' }),

  makeMCQ({ id:'g3fr-eo-053', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "ma sœur". Quelle était la question ?',
    options:['Qui t\'a appelé ?','Où as-tu été ?','Quand est-elle arrivée ?','Comment va-t-elle ?'],
    answer:'Qui t\'a appelé ?',
    hint:'"Ma sœur" est une personne. Quel mot interrogatif demande une personne ?',
    explanation:'"<b>Qui</b>" demande une personne. "Ma sœur" répond à la question "Qui t\'a appelé ?"' }),

  makeMCQ({ id:'g3fr-eo-054', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "à pied". Quelle était la question ?',
    options:['Comment viens-tu à l\'école ?','Où vas-tu à l\'école ?','Quand arrives-tu ?','Qui t\'accompagne ?'],
    answer:'Comment viens-tu à l\'école ?',
    hint:'"À pied" décrit la manière de se déplacer. Quel mot interrogatif demande la manière ?',
    explanation:'"<b>Comment</b>" demande la manière. "À pied" répond à "Comment viens-tu à l\'école ?"' }),

  makeMCQ({ id:'g3fr-eo-055', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "parce qu\'il est malade". Quelle était la question ?',
    options:['Pourquoi est-il absent ?','Où est-il ?','Quand reviendra-t-il ?','Qui est malade ?'],
    answer:'Pourquoi est-il absent ?',
    hint:'"Parce que" introduit une raison/cause. Quel mot interrogatif demande la raison ?',
    explanation:'"<b>Pourquoi</b>" demande la raison. "Parce qu\'il est malade" répond à "Pourquoi est-il absent ?"' }),

  makeMCQ({ id:'g3fr-eo-056', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Quel mot interrogatif complète cette question : "___ heures as-tu ?" ?',
    options:['Combien d\'','Qui','Où','Pourquoi'],
    answer:'Combien d\'',
    hint:'"Combien" demande un nombre ou une quantité.',
    explanation:'"<b>Combien d\'</b> heures as-tu ?" demande une quantité. "Combien" est le mot interrogatif pour les nombres.' }),

  makeMCQ({ id:'g3fr-eo-057', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Quelle est la bonne réponse à : "Quel est ton animal préféré ?" ?',
    options:['Mon animal préféré est le dauphin.','Je suis à la maison.','Il fait beau aujourd\'hui.','Je m\'appelle Priya.'],
    answer:'Mon animal préféré est le dauphin.',
    hint:'La réponse doit être en rapport avec la question posée.',
    explanation:'La question demande un animal préféré. La bonne réponse est "<b>Mon animal préféré est le dauphin.</b>"' }),

  makeMCQ({ id:'g3fr-eo-058', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Comment répond-on poliment à une question en français ?',
    options:['En faisant une phrase complète','En disant seulement "oui" ou "non"','En chantant la réponse','En écrivant la réponse'],
    answer:'En faisant une phrase complète',
    hint:'À l\'oral, une phrase complète montre qu\'on a bien compris la question.',
    explanation:'On répond poliment <b>en faisant une phrase complète</b>. Ex : "Oui, j\'ai faim." plutôt que seulement "Oui".' }),

  makeMCQ({ id:'g3fr-eo-059', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'"Comment t\'appelles-tu ?" — Quelle est la meilleure réponse ?',
    options:['Je m\'appelle Ravi.','Je suis bien.','J\'habite à Curepipe.','Je vais à l\'école.'],
    answer:'Je m\'appelle Ravi.',
    hint:'La question demande un nom. La réponse doit donc donner un nom.',
    explanation:'"Comment t\'appelles-tu ?" demande le nom de la personne. La bonne réponse est "<b>Je m\'appelle Ravi.</b>"' }),

  makeMCQ({ id:'g3fr-eo-060', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'"Quel âge as-tu ?" — Quelle est la meilleure réponse ?',
    options:['J\'ai huit ans.','Je m\'appelle Layla.','J\'habite à Rose-Hill.','Je vais bien.'],
    answer:'J\'ai huit ans.',
    hint:'La question demande un âge. La réponse doit donner un nombre d\'années.',
    explanation:'"Quel âge as-tu ?" demande l\'âge. La bonne réponse est "<b>J\'ai huit ans.</b>"' }),

  makeMCQ({ id:'g3fr-eo-061', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'"Où habites-tu ?" — Quelle est la meilleure réponse ?',
    options:['J\'habite à Port-Louis.','J\'ai dix ans.','Je m\'appelle Sam.','Je mange du riz.'],
    answer:'J\'habite à Port-Louis.',
    hint:'La question demande un lieu. La réponse doit donner un endroit.',
    explanation:'"Où habites-tu ?" demande un lieu. La bonne réponse est "<b>J\'habite à Port-Louis.</b>"' }),

  makeMCQ({ id:'g3fr-eo-062', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "une pomme". Quelle était la question ?',
    options:['Qu\'est-ce que tu manges ?','Où vas-tu ?','Quand arrives-tu ?','Comment te sens-tu ?'],
    answer:'Qu\'est-ce que tu manges ?',
    hint:'"Une pomme" est un objet/aliment. Quel mot interrogatif demande une chose ?',
    explanation:'"<b>Qu\'est-ce que</b>" (ou "Que") demande une chose ou une action. "Une pomme" répond à "Qu\'est-ce que tu manges ?"' }),

  makeMCQ({ id:'g3fr-eo-063', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Quel mot interrogatif utilise-t-on pour demander la MANIÈRE ?',
    options:['Comment','Où','Quand','Qui'],
    answer:'Comment',
    hint:'"Comment" demande de quelle façon quelque chose est fait.',
    explanation:'"<b>Comment</b>" demande la manière. Ex : "Comment vas-tu à l\'école ?" (à pied, en voiture...)' }),

  makeMCQ({ id:'g3fr-eo-064', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Quel mot interrogatif utilise-t-on pour demander un LIEU ?',
    options:['Où','Quand','Qui','Pourquoi'],
    answer:'Où',
    hint:'"Où" demande toujours un endroit ou un lieu.',
    explanation:'"<b>Où</b>" demande un lieu. Ex : "Où habites-tu ?" (à Port-Louis, dans une maison...)' }),

  makeMCQ({ id:'g3fr-eo-065', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Quel mot interrogatif utilise-t-on pour demander le MOMENT ?',
    options:['Quand','Où','Qui','Comment'],
    answer:'Quand',
    hint:'"Quand" demande toujours un moment dans le temps.',
    explanation:'"<b>Quand</b>" demande le moment. Ex : "Quand reviens-tu ?" (demain, à 5h...)' }),

  makeMCQ({ id:'g3fr-eo-066', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Quel mot interrogatif utilise-t-on pour demander une PERSONNE ?',
    options:['Qui','Où','Quand','Comment'],
    answer:'Qui',
    hint:'"Qui" demande toujours une personne ou un être vivant.',
    explanation:'"<b>Qui</b>" demande une personne. Ex : "Qui est ton meilleur ami ?" (C\'est Rajan.)' }),

  makeMCQ({ id:'g3fr-eo-067', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Quel mot interrogatif utilise-t-on pour demander la RAISON ?',
    options:['Pourquoi','Où','Quand','Qui'],
    answer:'Pourquoi',
    hint:'"Pourquoi" demande toujours une raison. La réponse commence souvent par "parce que".',
    explanation:'"<b>Pourquoi</b>" demande la raison. Ex : "Pourquoi pleures-tu ?" — "Parce que j\'ai mal."' }),

  makeMCQ({ id:'g3fr-eo-068', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'"Combien de livres as-tu ?" — Quel type de réponse attend cette question ?',
    options:['Un nombre','Un lieu','Une personne','Une raison'],
    answer:'Un nombre',
    hint:'"Combien" demande toujours une quantité ou un nombre.',
    explanation:'"<b>Combien</b>" demande un nombre. La réponse pourrait être : "J\'ai cinq livres."' }),

  makeMCQ({ id:'g3fr-eo-069', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'Laquelle de ces phrases est une QUESTION correctement formée ?',
    options:['Est-ce que tu aimes le sport ?','Tu aimes le sport.','Le sport tu aimes.','Sport le aimes tu ?'],
    answer:'Est-ce que tu aimes le sport ?',
    hint:'Une question en français peut commencer par "Est-ce que..." ou utiliser l\'inversion.',
    explanation:'"<b>Est-ce que tu aimes le sport ?</b>" est une question bien formée. Elle commence par "Est-ce que" et se termine par "?".' }),

  makeMCQ({ id:'g3fr-eo-070', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'"As-tu des frères et sœurs ?" — Quelle est la meilleure réponse ?',
    options:['Oui, j\'ai un frère et deux sœurs.','Je m\'appelle Kevin.','J\'habite à Beau-Bassin.','Il fait beau.'],
    answer:'Oui, j\'ai un frère et deux sœurs.',
    hint:'La question demande si on a des frères et sœurs. La réponse doit répondre à ça.',
    explanation:'La question demande le nombre de frères et sœurs. La meilleure réponse est "<b>Oui, j\'ai un frère et deux sœurs.</b>"' }),

  makeMCQ({ id:'g3fr-eo-071', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'"Quel est ton plat préféré ?" — Quelle est la meilleure réponse ?',
    options:['Mon plat préféré est le riz frit.','J\'ai neuf ans.','Je vais à l\'école Jean-Paul.','Je joue au football.'],
    answer:'Mon plat préféré est le riz frit.',
    hint:'La question demande un plat. La réponse doit nommer un plat.',
    explanation:'"Quel est ton plat préféré ?" demande un aliment. La bonne réponse est "<b>Mon plat préféré est le riz frit.</b>"' }),

  makeMCQ({ id:'g3fr-eo-072', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "avec mes parents". Quelle était la question ?',
    options:['Avec qui voyages-tu ?','Où voyages-tu ?','Quand voyages-tu ?','Pourquoi voyages-tu ?'],
    answer:'Avec qui voyages-tu ?',
    hint:'"Avec mes parents" désigne des personnes. Quel mot interrogatif demande les personnes qui accompagnent ?',
    explanation:'"<b>Avec qui</b>" demande les personnes qui accompagnent. "Avec mes parents" répond à "Avec qui voyages-tu ?"' }),

  makeMCQ({ id:'g3fr-eo-073', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'"Aimes-tu les mathématiques ?" — Quelle est la meilleure réponse ?',
    options:['Oui, j\'aime beaucoup les mathématiques.','Je m\'appelle Divya.','Il fait 30 degrés.','Mon école est grande.'],
    answer:'Oui, j\'aime beaucoup les mathématiques.',
    hint:'La question demande si on aime les maths. La réponse doit répondre directement.',
    explanation:'"<b>Oui, j\'aime beaucoup les mathématiques.</b>" répond directement à la question "Aimes-tu les mathématiques ?"' }),

  makeMCQ({ id:'g3fr-eo-074', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "en train". Quelle était la question ?',
    options:['Comment voyages-tu ?','Où vas-tu ?','Quand pars-tu ?','Avec qui voyages-tu ?'],
    answer:'Comment voyages-tu ?',
    hint:'"En train" indique un moyen de transport / une manière de voyager.',
    explanation:'"<b>Comment</b>" demande la manière. "En train" répond à "Comment voyages-tu ?"' }),

  makeMCQ({ id:'g3fr-eo-075', chapterId:CH, difficulty:1, subsection:'questions_reponses',
    question:'La réponse est "parce que j\'adore les animaux". Quelle était la question ?',
    options:['Pourquoi veux-tu devenir vétérinaire ?','Où travailles-tu ?','Quand commences-tu ?','Qui est ton docteur ?'],
    answer:'Pourquoi veux-tu devenir vétérinaire ?',
    hint:'"Parce que" répond toujours à "Pourquoi".',
    explanation:'"<b>Pourquoi</b>" demande la raison. "Parce que j\'adore les animaux" répond à "Pourquoi veux-tu devenir vétérinaire ?"' })

);

})();
