'use strict';
// PSAC Grade 6 History & Geography December 2020 (2021 session) — past-paper questions adapted to MCQ format.
STATIC_QUESTIONS.push(
  makeMCQ({ id:'g6h-pp21-001', chapterId:'g6-land-use', difficulty:1,
    question:'The type of land use for the setting up of <b>shops and shopping malls</b> is known as ____________ land use.',
    options:['industrial','recreational','commercial','residential'], answer:'commercial',
    hint:'Think about commerce — buying and selling.',
    explanation:'Commercial land use refers to land used for shops, offices, shopping malls, and other business activities.' }),
  makeMCQ({ id:'g6h-pp21-002', chapterId:'g6-land-use', difficulty:2,
    question:'One tourist resort found in the <b>north</b> of Mauritius is ____________.',
    options:['Belle Mare','Flic en Flac','Bel Ombre','Grand Baie'], answer:'Grand Baie',
    hint:'Mauritius has resort towns in each direction — which well-known resort town is in the north?',
    explanation:'Grand Baie is a major tourist resort in the north of Mauritius, known for its beach, lagoon, and water sports. Belle Mare is in the east, Flic en Flac in the west, Bel Ombre in the south.' }),
  makeMCQ({ id:'g6h-pp21-003', chapterId:'g6-land-use', difficulty:1,
    question:'The rearing of animals <b>only</b> (no crops) is called ____________.',
    options:['mixed farming','pastoral farming','market gardening','plantation agriculture'], answer:'pastoral farming',
    hint:'"Pastoral" relates to pastures and animals.',
    explanation:'Pastoral farming involves rearing animals only (cattle, goats, sheep) without growing crops. Mixed farming combines both crops and animals.' }),
  makeMCQ({ id:'g6h-pp21-004', chapterId:'g6-natural-hazards', difficulty:1,
    question:'Which of the following best describes a <b>tsunami</b>?',
    options:['Eruption of magma from a volcano','Collision of two different parts of the Earth','Occurrence of torrential rainfall','Formation of giant waves caused by undersea earthquakes'], answer:'Formation of giant waves caused by undersea earthquakes',
    hint:'The Japanese word "tsunami" means "harbour wave."',
    explanation:'A tsunami is a series of giant waves caused when an earthquake, volcanic eruption, or landslide occurs under the ocean floor, displacing a large volume of water.' }),
  makeMCQ({ id:'g6h-pp21-005', chapterId:'g6-slaves-immigrants', difficulty:2,
    question:'Which one of the following islands was known as <b>Ile Bourbon</b> in the past?',
    options:['Mauritius','Rodrigues','Réunion','Madagascar'], answer:'Réunion',
    hint:'In the past, nearby islands had different French names. Think about which island near Mauritius was called "Ile Bourbon."',
    explanation:'Réunion was known as Ile Bourbon during the French colonial period. Mauritius was known as Ile de France, and Madagascar was known as Ile Dauphine.' }),
  makeMCQ({ id:'g6h-pp21-006', chapterId:'g6-slaves-immigrants', difficulty:2,
    question:'Macchabee, Mangalkhan, and Diamamouve were well-known ____________ in Mauritius.',
    options:['slaves who ran away from plantations','pirates who attacked ships','early European settlers','French colonial governors'], answer:'slaves who ran away from plantations',
    hint:'They are celebrated as heroes who resisted the colonial system.',
    explanation:'Macchabee, Mangalkhan, and Diamamouve were famous Maroons — slaves who escaped from plantations and hid in the forests and mountains of Mauritius, resisting the slave system.' }),
  makeMCQ({ id:'g6h-pp21-007', chapterId:'g6-independence', difficulty:2,
    question:'Which one of the following is found on the Coat of Arms of <b>Rodrigues</b>?',
    options:['A solitaire bird','A dodo bird','A palm tree','A ship'], answer:'A solitaire bird',
    hint:'This extinct bird was unique to Rodrigues.',
    explanation:'The Solitaire bird is on the Coat of Arms of Rodrigues, representing the extinct flightless bird that was unique to the island. The dodo is on the Coat of Arms of Mauritius.' }),
  makeMCQ({ id:'g6h-pp21-008', chapterId:'g6-slaves-immigrants', difficulty:1,
    question:'On which date is the Abolition of Slavery commemorated in Mauritius?',
    options:['1st February','12th March','2nd November','31st December'], answer:'1st February',
    hint:'Slavery was officially abolished on this date in 1835.',
    explanation:'The 1st of February is Abolition of Slavery Day in Mauritius, marking the date in 1835 when slavery was officially ended following the British Slavery Abolition Act of 1833.' }),
  makeMCQ({ id:'g6h-pp21-009', chapterId:'g6-natural-hazards', difficulty:2,
    question:'During which <b>season</b> are tropical cyclones usually formed near Mauritius?',
    options:['Winter (May–October)','Summer (November–April)','Spring only','All year round equally'], answer:'Summer (November–April)',
    hint:'Cyclones form over warm tropical seas — which season is warmest?',
    explanation:'Tropical cyclones form during the summer season (November to April) in the southern hemisphere, when the sea surface temperature is warm enough (above 26°C) to provide the energy for cyclone formation.' }),
  makeMCQ({ id:'g6h-pp21-010', chapterId:'g6-natural-hazards', difficulty:2,
    question:'Which part of a tropical cyclone has the <b>most violent winds</b> and gusts?',
    options:['The outer spiral rain bands','The eye wall (inner wall around the eye)','The eye (calm centre)','The clouds high above the cyclone'], answer:'The eye wall (inner wall around the eye)',
    hint:'This is the ring immediately surrounding the calm centre.',
    explanation:'The eye wall (the inner wall directly surrounding the eye) has the most violent winds and heaviest rain. The eye itself is calm, and the outer bands have lighter winds.' }),
  makeMCQ({ id:'g6h-pp21-011', chapterId:'g6-natural-hazards', difficulty:2,
    question:'What are the weather conditions in the <b>eye</b> (centre) of a tropical cyclone?',
    options:['Very strong winds and heavy rain','Calm weather, light winds, and clear sky','Extremely cold temperatures and snow','Dark skies with no rain but constant lightning'], answer:'Calm weather, light winds, and clear sky',
    hint:'The eye is the circular zone of calm at the centre of the storm.',
    explanation:'The eye of a tropical cyclone has calm weather, light winds, and a clear or partly cloudy sky. The extreme weather is in the eye wall and outer bands surrounding it.' }),
  makeMCQ({ id:'g6h-pp21-012', chapterId:'g6-independence', difficulty:1,
    question:'The four colours of the National Flag of Mauritius are red, blue, yellow, and ____________.',
    options:['black','green','orange','white'], answer:'green',
    hint:'Think about the natural landscapes and plant life of Mauritius.',
    explanation:'The four colours of the Mauritian national flag are red, blue, yellow, and green. Red = struggle for independence, Blue = Indian Ocean, Yellow = light of independence, Green = vegetation.' }),
  makeMCQ({ id:'g6h-pp21-013', chapterId:'g6-independence', difficulty:2,
    question:'What does the <b>blue</b> colour in the National Flag of Mauritius represent?',
    options:['The sky above Mauritius','The Indian Ocean surrounding Mauritius','The hope of the Mauritian people','The fight for independence'], answer:'The Indian Ocean surrounding Mauritius',
    hint:'Mauritius is an island surrounded by this body of water.',
    explanation:'The blue stripe in the Mauritian national flag represents the Indian Ocean that surrounds the island of Mauritius.' }),
  makeMCQ({ id:'g6h-pp21-014', chapterId:'g6-independence', difficulty:2,
    question:'Who wrote the National Anthem of Mauritius?',
    options:['Jean Georges Prosper','Louis Bouton','Philippe Gentil','Sir Seewoosagur Ramgoolam'], answer:'Jean Georges Prosper',
    hint:'He wrote the lyrics in both French and English versions.',
    explanation:'Jean Georges Prosper wrote the words (lyrics) of the Mauritian National Anthem "Motherland." Philippe Gentil composed the music.' }),
  makeMCQ({ id:'g6h-pp21-015', chapterId:'g6-land-use', difficulty:1,
    question:'What is the main type of farming practised in the <b>river valleys</b> of Rodrigues?',
    options:['Mixed farming','Market gardening','Pastoral farming','Plantation agriculture'], answer:'Market gardening',
    hint:'River valleys have fertile alluvial soil and water — good for growing vegetables.',
    explanation:'Market gardening (growing vegetables, fruits, and herbs on small plots for sale) is the main type of farming in the river valleys of Rodrigues, where alluvial soil and water are available.' }),
  makeMCQ({ id:'g6h-pp21-016', chapterId:'g6-land-use', difficulty:2,
    question:'Why is <b>organic farming</b> encouraged in Mauritius and Rodrigues today?',
    options:['It produces more food than other methods','It does not use chemical pesticides or fertilisers, protecting the environment and health','It is cheaper than conventional farming','It allows growing crops all year round without irrigation'], answer:'It does not use chemical pesticides or fertilisers, protecting the environment and health',
    hint:'The key benefit is no synthetic chemicals.',
    explanation:'Organic farming is encouraged because it avoids the use of chemical pesticides and fertilisers, which can pollute water and soil. It produces healthier food and protects the environment.' }),
  makeMCQ({ id:'g6h-pp21-017', chapterId:'g6-land-use', difficulty:2,
    question:'What is one advantage of growing crops in a <b>greenhouse</b>?',
    options:['Crops are protected from extreme weather conditions and pests','Crops receive less water so they grow faster','The greenhouse makes crops taste better','Greenhouses are cheaper to build than open fields'], answer:'Crops are protected from extreme weather conditions and pests',
    hint:'A greenhouse is an enclosed structure — think about what it protects crops from.',
    explanation:'Growing crops in a greenhouse protects them from extreme weather (heavy rain, strong winds, drought) and from pests and diseases, allowing crops to grow in controlled conditions.' })
);
window.PSAC_PDF_QUESTIONS = window.PSAC_PDF_QUESTIONS || [];
window.PSAC_PDF_QUESTIONS.push(
  { id:'g6h-pp21-pdf-001', chapterId:'g6-natural-hazards', marks:10, year:2021, grade:6, subject:'History & Geography',
    question:'Study Diagram 1 (tropical cyclone cross-section with Parts X, Y, Z). (a) During which season are tropical cyclones formed? (b) Which part has most violent winds — Part X or Part Y? (c) Describe weather in Part Z. (d) Give two precautions before a cyclone. (Volcano: a) Give one reason a volcano is a natural hazard. (b) Explain how volcanoes can be an advantage to people.', type:'diagram-analysis' },
  { id:'g6h-pp21-pdf-002', chapterId:'g6-land-use', marks:7, year:2021, grade:6, subject:'History & Geography',
    question:'Study Map 1 (three river valleys in Rodrigues: Rivière Malgache, Rivière Banane, Rivière Mourouk). (a)(i) What is the main type of farming in these valleys? (a)(ii) Give one reason farmers grow here. (b) Why is organic farming encouraged? (c) Give one advantage of a greenhouse.', type:'map-read' },
  { id:'g6h-pp21-pdf-003', chapterId:'g6-land-use', marks:4, year:2021, grade:6, subject:'History & Geography',
    question:'Match the actions (Column 1) with activities (Column 2): Recycling newspapers → ? ; Using food waste and garden cutting → ? ; Reusing plastic bottles → ? (choices: Growing flowers/herbs, Making paper bags, Making shirts, Making compost)', type:'matching' }
);
