'use strict';
// PSAC Grade 6 History & Geography August 2019 — past-paper questions adapted to MCQ format.
STATIC_QUESTIONS.push(
  makeMCQ({ id:'g6h-pp19-001', chapterId:'g6-land-use', subsection:'agriculture', difficulty:1,
    question:'A stadium is an example of which type of land use?',
    options:['Agricultural','Industrial','Recreational','Residential'], answer:'Recreational',
    hint:'A stadium is used for sports and entertainment — what category is this?',
    explanation:'A stadium is an example of recreational land use — land used for sport, leisure, and entertainment activities.' }),
  makeMCQ({ id:'g6h-pp19-002', chapterId:'g6-land-use', subsection:'agriculture', difficulty:1,
    question:'The growing of crops <b>and</b> the rearing of animals together on the same farm is called ____________.',
    options:['market gardening','mixed farming','pastoral farming','plantation agriculture'], answer:'mixed farming',
    hint:'The word "mixed" tells you that two activities are combined.',
    explanation:'Mixed farming combines crop growing and animal rearing on the same farm. This is different from pastoral farming (animals only) or market gardening (vegetables only).' }),
  makeMCQ({ id:'g6h-pp19-003', chapterId:'g6-land-use', subsection:'tourism', difficulty:1,
    question:'Ecotourism encourages tourists to visit ____________.',
    options:['commercial centres','monuments','museums','national parks'], answer:'national parks',
    hint:'Ecotourism is about experiencing nature and wildlife.',
    explanation:'Ecotourism encourages tourists to visit national parks and nature reserves to experience wildlife and natural landscapes in a sustainable way without causing environmental damage.' }),
  makeMCQ({ id:'g6h-pp19-004', chapterId:'g6-natural-hazards', subsection:'earthquakes', difficulty:2,
    question:'Earthquakes occur when ____________.',
    options:['magma forces its way out to the Earth\'s surface','the temperature of the sea is high','there is widespread rain over a short period of time','two different parts of the Earth collide'], answer:'two different parts of the Earth collide',
    hint:'The Earth\'s crust is made of large pieces (plates) that can move and collide.',
    explanation:'Earthquakes occur when two tectonic plates (different parts of the Earth\'s crust) collide, slide past each other, or move apart, releasing energy as seismic waves.' }),
  makeMCQ({ id:'g6h-pp19-005', chapterId:'g6-slaves-immigrants', subsection:'indentured', difficulty:2,
    question:'How much money did indentured labourers receive <b>monthly</b> for their work in Mauritius?',
    options:['Rs 5','Rs 10','Rs 15','Rs 20'], answer:'Rs 10',
    hint:'This was a very small amount compared to what the planters earned.',
    explanation:'Indentured labourers received Rs 10 per month for their work on the sugar estates. This was a very low wage for the hard labour they performed.' }),
  makeMCQ({ id:'g6h-pp19-006', chapterId:'g6-slaves-immigrants', subsection:'colonial_rule', difficulty:1,
    question:'In which year did the <b>British</b> take possession of Mauritius?',
    options:['1715','1810','1835','1968'], answer:'1810',
    hint:'This happened after the British defeated the French at the Battle of Grand Port.',
    explanation:'The British took possession of Mauritius in 1810, after capturing the island from the French during the Napoleonic Wars. Mauritius remained a British colony until 1968.' }),
  makeMCQ({ id:'g6h-pp19-007', chapterId:'g6-independence', subsection:'independence', difficulty:1,
    question:'Who was the <b>first President</b> of the Republic of Mauritius?',
    options:['Sir Abdool Raman Osman','Sir John Shaw Rennie','Sir Seewoosagur Ramgoolam','Sir Veerasamy Ringadoo'], answer:'Sir Veerasamy Ringadoo',
    hint:'He became President when Mauritius became a Republic in 1992.',
    explanation:'Sir Veerasamy Ringadoo became the first President of the Republic of Mauritius on 12 March 1992, when Mauritius changed from a Commonwealth realm to a Republic.' }),
  makeMCQ({ id:'g6h-pp19-008', chapterId:'g6-cultural-heritage', subsection:'sites', difficulty:2,
    question:'The Slave Route Monument, which reminds us of the countries from which slaves were brought, is found at ____________.',
    options:['Mahebourg','Pamplemousses','Le Morne','Port Louis'], answer:'Le Morne',
    hint:'This UNESCO World Heritage mountain was a refuge for runaway slaves.',
    explanation:'The Slave Route Monument is at the foot of Le Morne Brabant mountain. It commemorates the runaway slaves (Maroons) who hid there and the countries from which enslaved people were brought.' }),
  makeMCQ({ id:'g6h-pp19-009', chapterId:'g6-slaves-immigrants', subsection:'aapravasi', difficulty:1,
    question:'The Aapravasi Ghat, where indentured labourers first landed in Mauritius, is located in ____________.',
    options:['Curepipe','Grand Baie','Mahebourg','Port Louis'], answer:'Port Louis',
    hint:'It is near the waterfront of the capital city.',
    explanation:'The Aapravasi Ghat is in Port Louis, near the harbour. It is a UNESCO World Heritage Site and was the arrival point for Indian indentured labourers from 1834 onwards.' }),
  makeMCQ({ id:'g6h-pp19-010', chapterId:'g6-cultural-heritage', subsection:'sites', difficulty:2,
    question:'The Fort Frederik Hendrik Museum reminds us of which period of Mauritian history?',
    options:['Arab trade era','Dutch settlement of Mauritius','French colonial period','British colonial period'], answer:'Dutch settlement of Mauritius',
    hint:'Frederik Hendrik was a Dutch ruler, and the fort was built by the first European settlers.',
    explanation:'The Fort Frederik Hendrik Museum at Vieux Grand Port reminds us of the Dutch settlement of Mauritius (1638–1710). The Dutch were the first Europeans to settle in Mauritius.' }),
  makeMCQ({ id:'g6h-pp19-011', chapterId:'g6-slaves-immigrants', subsection:'chinese', difficulty:2,
    question:'Chinese immigrants first came to Port Louis towards the end of the ____________ century.',
    options:['16th century','17th century','18th century','19th century'], answer:'18th century',
    hint:'Chinese merchants arrived in Mauritius during the colonial period — think about when French rule was at its peak.',
    explanation:'Chinese immigrants first arrived in Port Louis towards the end of the 18th century (late 1700s). More came during the British period in the 19th century.' }),
  makeMCQ({ id:'g6h-pp19-012', chapterId:'g6-slaves-immigrants', subsection:'chinese', difficulty:1,
    question:'In Port Louis, Chinese immigrants settled in an area now called ____________.',
    options:['Bell Village','China Town','Caudan Waterfront','La Butte'], answer:'China Town',
    hint:'In cities around the world, districts where Chinese communities concentrated often share a similar name.',
    explanation:'Chinese immigrants settled in Port Louis in an area called China Town, where they set up shops and businesses. China Town still exists in Port Louis today.' }),
  makeMCQ({ id:'g6h-pp19-013', chapterId:'g6-slaves-immigrants', subsection:'colonial_rule', difficulty:2,
    question:'Why did the British bring many Indian workers to Mauritius <b>after 1840</b>?',
    options:['To build the railways in Mauritius','To work on the sugar cane plantations after the abolition of slavery','To fight in the British army','To set up a new government administration'], answer:'To work on the sugar cane plantations after the abolition of slavery',
    hint:'Slavery had been abolished in 1835 — planters needed new workers.',
    explanation:'After the abolition of slavery in 1835, planters needed workers for the sugar cane fields. The British brought Indian indentured labourers to fill this need, especially as sugar cane cultivation expanded.' }),
  makeMCQ({ id:'g6h-pp19-014', chapterId:'g6-slaves-immigrants', subsection:'slavery', difficulty:2,
    question:'What does the word <b>"immigrant"</b> mean?',
    options:['A person born in Mauritius','A person who moves from one country to live in another country','A person who travels as a tourist','A person who works at sea'], answer:'A person who moves from one country to live in another country',
    hint:'The prefix "im-" means coming into a place.',
    explanation:'An immigrant is a person who moves from their own country to settle in another country. Indian labourers and Chinese traders who came to Mauritius were immigrants.' }),
  makeMCQ({ id:'g6h-pp19-015', chapterId:'g6-independence', subsection:'coat_of_arms', difficulty:2,
    question:'What does the Latin motto <b>"Stella Clavisque Maris Indici"</b> on the Coat of Arms of Mauritius mean?',
    options:['Land of the free and the brave','Our strength is our diversity','Star and Key of the Indian Ocean','Peace, justice and liberty'], answer:'Star and Key of the Indian Ocean',
    hint:'Think of the nickname for Mauritius — it suggests importance for navigation.',
    explanation:'"Stella Clavisque Maris Indici" is Latin for "Star and Key of the Indian Ocean," reflecting Mauritius\'s strategic importance as a key port on Indian Ocean trade routes.' }),
  makeMCQ({ id:'g6h-pp19-016', chapterId:'g6-independence', subsection:'coat_of_arms', difficulty:2,
    question:'Which feature on the Coat of Arms of Mauritius shows that Mauritius is a <b>tropical island</b>?',
    options:['The dodo bird','The sambar deer','The sugar cane','The ship'], answer:'The sugar cane',
    hint:'This crop is grown in warm, tropical climates and dominates Mauritius\'s landscape.',
    explanation:'The sugar cane plants on the Coat of Arms show that Mauritius is a tropical island, as sugar cane grows in warm, tropical climates. It is also the main crop and industry of Mauritius.' }),
  makeMCQ({ id:'g6h-pp19-017', chapterId:'g6-cultural-heritage', subsection:'sites', difficulty:2,
    question:'Which of the following museums in Mauritius was created to commemorate the <b>Dutch settlement</b> and the first European landing?',
    options:['Aapravasi Ghat Museum','Blue Penny Museum','Fort Frederik Hendrik Museum','National History Museum'], answer:'Fort Frederik Hendrik Museum',
    hint:'The name "Frederik Hendrik" is Dutch, and this museum is at Vieux Grand Port.',
    explanation:'The Fort Frederik Hendrik Museum at Vieux Grand Port commemorates the Dutch settlement of Mauritius (1638–1710) and the first European landing on the island.' })
);
window.PSAC_PDF_QUESTIONS = window.PSAC_PDF_QUESTIONS || [];
window.PSAC_PDF_QUESTIONS.push(
  { id:'g6h-pp19-pdf-001', needsArtwork:true, chapterId:'g6-natural-hazards', marks:9, year:2019, grade:6, subject:'History & Geography',
    question:'Study Diagram 1 (tsunami occurring). (a) A tsunami is a giant ___ caused by a powerful ___ below the ocean floor. (b) Give one reason why Area X (coastal area) will be affected. (c) Which cyclone passed near Rodrigues in January 1991? (Bella) (d) In which direction did Céline 2 move after passing over Rodrigues? (e) Give one condition for cyclone formation. (f) Give two precautions after a cyclone.', type:'diagram-and-map' },
  { id:'g6h-pp19-pdf-002', needsArtwork:true, chapterId:'g6-land-use', marks:6, year:2019, grade:6, subject:'History & Geography',
    question:'Study Map 2 (grid map showing land use: Houses A1/A2, Sugar cane C1, Stadium A3, Commercial Centre B4, Nature Park D3/D4). (i) Name the type of land use in section A2. (ii) In which section is a commercial centre found? (iii) Suggest one reason why there is no road in section D4.', type:'map-grid' },
  { id:'g6h-pp19-pdf-003', chapterId:'g6-cultural-heritage', marks:4, year:2019, grade:6, subject:'History & Geography',
    question:'Complete the table of museums/monuments: Slave Route Monument (Le Morne) — reminds of countries where slaves came from; François Leguat Monument (place?) — reminds of first settlement in Rodrigues; Aapravasi Ghat (Port Louis) — importance?; Fort Frederik Hendrik Museum (place?) — Dutch settlement; Monument at Pointe Canon (Mahebourg) — importance?', type:'table-completion' }
);
