'use strict';
// PSAC Grade 6 History & Geography 2021-2022 — past-paper questions adapted to MCQ format.
STATIC_QUESTIONS.push(
  makeMCQ({ id:'g6h-pp22-001', chapterId:'g6-land-use', difficulty:1,
    question:'Land used to build houses is known as ____________ land use.',
    options:['commercial','industrial','recreational','residential'], answer:'residential',
    hint:'People live in houses — think about what we call the area where people live.',
    explanation:'Residential land use refers to land used for building houses and homes where people live.' }),
  makeMCQ({ id:'g6h-pp22-002', chapterId:'g6-cultural-heritage', difficulty:1,
    question:'The Beau Plan sugar mill in the north of Mauritius has been converted into a ____________.',
    options:['factory','museum','nature reserve','tourist hotel'], answer:'museum',
    hint:'The conversion preserves the history of the sugar industry for visitors to learn about.',
    explanation:'The Beau Plan sugar mill has been converted into a museum called L\'Aventure du Sucre, which celebrates the history of sugar production in Mauritius.' }),
  makeMCQ({ id:'g6h-pp22-003', chapterId:'g6-land-use', difficulty:2,
    question:'Which of the following is a site for <b>ecotourism</b> in Mauritius?',
    options:['The Blue Penny Museum','China Town','L\'Ile aux Aigrettes','The Slave Route Monument'], answer:'L\'Ile aux Aigrettes',
    hint:'Ecotourism involves visiting natural environments and observing wildlife.',
    explanation:'L\'Ile aux Aigrettes is a coral island nature reserve off the south-east coast of Mauritius, where endangered species are protected. It is a famous ecotourism site.' }),
  makeMCQ({ id:'g6h-pp22-004', chapterId:'g6-slaves-immigrants', difficulty:2,
    question:'Who were responsible for the <b>protection</b> of the island of Ile de France during the French period?',
    options:['Farmers','Soldiers','Settlers','Traders'], answer:'Soldiers',
    hint:'Think about which group is specifically trained to defend and protect a territory.',
    explanation:'Soldiers (military garrison) were responsible for the protection and defence of Ile de France (Mauritius) during the French colonial period.' }),
  makeMCQ({ id:'g6h-pp22-005', chapterId:'g6-slaves-immigrants', difficulty:2,
    question:'Mahé de Labourdonnais brought free workers to Ile de France from ____________.',
    options:['India','Madagascar','Mozambique','Senegal'], answer:'Madagascar',
    hint:'This is the large island nation off the south-east coast of Africa, close to Mauritius.',
    explanation:'Mahé de Labourdonnais, the French governor, brought free workers (engagés) from Madagascar to help develop the island, build roads, and work on projects.' }),
  makeMCQ({ id:'g6h-pp22-006', chapterId:'g6-independence', difficulty:2,
    question:'Which colour of the National Flag of Mauritius represents the <b>golden sunshine</b>?',
    options:['Red','Blue','Yellow','Green'], answer:'Yellow',
    hint:'Think about the colour most associated with sunlight and gold.',
    explanation:'The yellow stripe on the Mauritian national flag represents the golden light of independence and the sunshine of the island.' }),
  makeMCQ({ id:'g6h-pp22-007', chapterId:'g6-independence', difficulty:2,
    question:'Who <b>composed the music</b> of the National Anthem of Mauritius?',
    options:['Jean George Prosper','Louis Bouton','Philippe Gentil','Sir John Shaw Rennie'], answer:'Philippe Gentil',
    hint:'He composed the music while Jean Georges Prosper wrote the words.',
    explanation:'Philippe Gentil composed the music of the Mauritian National Anthem "Motherland." Jean Georges Prosper wrote the lyrics.' }),
  makeMCQ({ id:'g6h-pp22-008', chapterId:'g6-slaves-immigrants', difficulty:2,
    question:'Slaves who ran away from their masters were called ____________.',
    options:['Coolies','Engagés','Maroons','Settlers'], answer:'Maroons',
    hint:'This word comes from a French/Spanish word meaning "wild" or "untamed."',
    explanation:'Runaway slaves were called Maroons (Maronnage). They hid in the mountains and forests of Mauritius to escape from their masters.' }),
  makeMCQ({ id:'g6h-pp22-009', chapterId:'g6-slaves-immigrants', difficulty:2,
    question:'Where did runaway slaves (Maroons) hide in Mauritius?',
    options:['In sugar cane fields','In Port Louis','In the mountains and forests','On ships in the harbour'], answer:'In the mountains and forests',
    hint:'They chose remote, difficult-to-reach places where colonists could not easily find them.',
    explanation:'Runaway slaves hid in the mountains and forests, especially around Le Morne Brabant and other remote areas, where it was difficult for slave owners and soldiers to reach them.' }),
  makeMCQ({ id:'g6h-pp22-010', chapterId:'g6-slaves-immigrants', difficulty:1,
    question:'On which date is the Abolition of Slavery celebrated in Mauritius?',
    options:['1st February','12th March','2nd November','25th December'], answer:'1st February',
    hint:'Mauritius celebrates Abolition of Slavery Day in the first month of the year.',
    explanation:'The 1st of February is celebrated as Abolition of Slavery Day in Mauritius, marking the end of slavery on 1 February 1835.' }),
  makeMCQ({ id:'g6h-pp22-011', chapterId:'g6-slaves-immigrants', difficulty:2,
    question:'After the abolition of slavery in 1835, many freed slaves went to live in the interior of Mauritius. How did they earn their living there?',
    options:['They worked in sugar factories','They became fishermen in the lagoons','They grew vegetables and became craftsmen or fishermen','They opened shops in Port Louis'], answer:'They grew vegetables and became craftsmen or fishermen',
    hint:'They chose occupations that gave them more freedom and independence.',
    explanation:'After abolition, freed slaves moved to the interior and earned their living through vegetable growing, fishing, and crafts — occupations that gave them more freedom than plantation work.' }),
  makeMCQ({ id:'g6h-pp22-012', chapterId:'g6-slaves-immigrants', difficulty:2,
    question:'Which of the following statements about life in 19th century Mauritius is <b>TRUE</b>?',
    options:['All children were required by law to go to school','Malaria was a disease that killed many people','Reverend Jean Lebrun introduced railways to Mauritius','Indian immigrants were not allowed to practise their religion'], answer:'Malaria was a disease that killed many people',
    hint:'This disease was a major cause of death before modern medicine.',
    explanation:'Malaria was a deadly disease that killed many people in 19th century Mauritius, spread by mosquitoes in the swampy lowlands.' }),
  makeMCQ({ id:'g6h-pp22-013', chapterId:'g6-natural-hazards', difficulty:1,
    question:'Flash floods are natural hazards which mainly occur during the ____________ season in Mauritius.',
    options:['Spring','Summer','Autumn','Winter'], answer:'Summer',
    hint:'Heavy tropical rainstorms are most common during the hot, wet season.',
    explanation:'Flash floods mainly occur during summer (November to April) in Mauritius, when heavy tropical rains fall rapidly over a short period of time.' }),
  makeMCQ({ id:'g6h-pp22-014', chapterId:'g6-natural-hazards', difficulty:2,
    question:'Flash floods are caused by heavy rain falling ____________ over a place.',
    options:['gently and slowly over days','suddenly and quickly','lightly and steadily','overnight only'], answer:'suddenly and quickly',
    hint:'The word "flash" tells you how quickly it happens.',
    explanation:'Flash floods are caused when very heavy rain falls suddenly and quickly (in a short period) over a place, overwhelming drainage systems and causing rapid flooding.' }),
  makeMCQ({ id:'g6h-pp22-015', chapterId:'g6-independence', difficulty:1,
    question:'When Mauritius became independent on 12 March 1968, Sir Seewoosagur Ramgoolam became the first ____________ of Mauritius.',
    options:['Governor General','King','President','Prime Minister'], answer:'Prime Minister',
    hint:'He was the leader of the elected government, not the Head of State.',
    explanation:'Sir Seewoosagur Ramgoolam became the first Prime Minister of independent Mauritius on 12 March 1968. He led Mauritius to independence.' }),
  makeMCQ({ id:'g6h-pp22-016', chapterId:'g6-independence', difficulty:2,
    question:'Where was the independence ceremony of Mauritius held on 12 March 1968?',
    options:['Champ de Mars in Port Louis','Le Reduit (Government House)','SSR International Airport','Swami Vivekananda International Convention Centre'], answer:'Champ de Mars in Port Louis',
    hint:'The ceremony was held at a large, well-known open space in the capital city.',
    explanation:'The independence ceremony was held at the Champ de Mars in Port Louis on 12 March 1968. The Union Jack was lowered and the Mauritian flag was raised for the first time.' }),
  makeMCQ({ id:'g6h-pp22-017', chapterId:'g6-cultural-heritage', difficulty:2,
    question:'Which museum, situated in Port Louis, contains natural history specimens and was built during the colonial period?',
    options:['Blue Penny Museum','Folk Museum','Martello Tower Museum','Natural History Museum'], answer:'Natural History Museum',
    hint:'This museum in Port Louis is famous for its specimens of wildlife, including an extinct bird unique to Mauritius.',
    explanation:'The Natural History Museum in Port Louis houses important natural history specimens, including the skeleton and models of the extinct dodo bird.' })
);
window.PSAC_PDF_QUESTIONS = window.PSAC_PDF_QUESTIONS || [];
window.PSAC_PDF_QUESTIONS.push(
  { id:'g6h-pp22-pdf-001', chapterId:'g6-land-use', marks:7, year:2022, grade:6, subject:'History & Geography',
    question:'Study Diagram 1 (shows different types of farming in Rodrigues with areas X, Y, Z). (a) What type of farming is carried out in area X? (b) What is market gardening? Name two crops grown in area Z. Give one reason why these crops grow in area Z. (c) What has been done to the sloping land in area Y to facilitate growing crops?', type:'diagram-analysis' },
  { id:'g6h-pp22-pdf-002', chapterId:'g6-natural-hazards', marks:9, year:2022, grade:6, subject:'History & Geography',
    question:'Picture 4 shows flash floods in Mauritius. (a) Complete: Flash floods occur during (summer/winter); caused by (light/heavy) rain falling (suddenly/slowly). (b) Give two reasons why flash floods are more frequent in Mauritius nowadays. (c) Name two other natural hazards.', type:'picture-analysis' },
  { id:'g6h-pp22-pdf-003', chapterId:'g6-cultural-heritage', marks:5, year:2022, grade:6, subject:'History & Geography',
    question:'Study Map 1 showing Port Louis. (i) Name historical site 1 (Aapravasi Ghat). (ii) Which event is commemorated at site 1? (iii) Which museum is Museum A — Natural History Museum, Folk Museum, or Martello Tower Museum?', type:'map-read' }
);
