'use strict';
(function () {

// Grade 3 Health Education — Safety and First Aid
// IDs: g3he-saf-001 onwards
// Subsections: accident_prevention, road_water_safety, emergency_response

STATIC_QUESTIONS.push(

  // ── accident_prevention (001–025) ─────────────────────────────────────────

  makeMCQ({ id:'g3he-saf-001', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'What is an accident?',
    options:['An unplanned event that causes injury or damage','A planned event','A school activity','A type of exercise'],
    answer:'An unplanned event that causes injury or damage',
    hint:'Accidents happen unexpectedly.',
    explanation:'An <b>accident</b> is an unplanned event that results in injury, harm or damage. Many accidents can be prevented with awareness and safe behaviour.' }),

  makeMCQ({ id:'g3he-saf-002', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Which of these behaviours PREVENTS accidents at school?',
    options:['Walking in corridors, using equipment properly and following rules',
             'Running everywhere as fast as possible',
             'Ignoring safety signs',
             'Climbing on furniture'],
    answer:'Walking in corridors, using equipment properly and following rules',
    hint:'Safe behaviour prevents most school accidents.',
    explanation:'<b>Walking, using equipment correctly and following safety rules</b> prevents most common school accidents like falls, collisions and cuts.' }),

  makeMCQ({ id:'g3he-saf-003', chapterId:'g3he-safety', difficulty:2, subsection:'accident_prevention',
    question:'What is the most common cause of accidents among children?',
    options:['Careless behaviour and not following safety rules',
             'Being too healthy',
             'Eating too much food',
             'Learning new things'],
    answer:'Careless behaviour and not following safety rules',
    hint:'Most accidents are preventable.',
    explanation:'The most common cause of childhood accidents is <b>careless behaviour and not following safety rules</b>. Awareness and caution prevent most accidents.' }),

  makeTF({ id:'g3he-saf-004', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Wearing appropriate protective equipment (e.g. helmet for cycling) prevents injuries.',
    answer:true,
    explanation:'<b>True.</b> Protective equipment reduces the severity of injuries if an accident occurs. A helmet can prevent fatal head injuries.' }),

  makeMCQ({ id:'g3he-saf-005', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Why are safety signs and warnings important?',
    options:['They alert us to dangers so we can act safely','They are only for decoration','They are only for adults','They are only in factories'],
    answer:'They alert us to dangers so we can act safely',
    hint:'Safety signs give us important information.',
    explanation:'Safety signs <b>alert us to dangers</b> like slippery floors, electrical hazards or restricted areas, allowing us to take precautions.' }),

  makeMCQ({ id:'g3he-saf-006', chapterId:'g3he-safety', difficulty:2, subsection:'accident_prevention',
    question:'You see a "No Running" sign in the corridor. Why is this rule in place?',
    options:['Running in corridors risks collisions, falls and injuries to many people',
             'Teachers just want it to be quiet',
             'Running makes floors dirty',
             'Running is not allowed for children generally'],
    answer:'Running in corridors risks collisions, falls and injuries to many people',
    hint:'Think about what would happen if many children ran in a narrow space.',
    explanation:'Running in corridors causes <b>collisions and falls</b> that can seriously injure both the runner and others. The rule protects everyone.' }),

  makeTF({ id:'g3he-saf-007', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Falls are one of the leading causes of accidental injury in children.',
    answer:true,
    explanation:'<b>True.</b> Falls are one of the most common causes of childhood injury, particularly from heights, stairs and playground equipment.' }),

  makeMCQ({ id:'g3he-saf-008', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Which of these helps prevent burns at home?',
    options:['Keeping children away from hot stoves, irons and boiling water',
             'Leaving pots unattended on the stove',
             'Letting children use the stove alone',
             'Keeping iron cords trailing across the floor'],
    answer:'Keeping children away from hot stoves, irons and boiling water',
    hint:'Burns happen when hot objects are within reach of children.',
    explanation:'Burns are prevented by <b>keeping children away from hot appliances</b> and ensuring cords do not trail where children walk.' }),

  makeMCQ({ id:'g3he-saf-009', chapterId:'g3he-safety', difficulty:2, subsection:'accident_prevention',
    question:'What makes electrical hazards especially dangerous?',
    options:['Electricity is invisible, can cause severe shock or death, and starts fires',
             'Electricity is always visible as sparks',
             'Electricity only affects adults',
             'Electricity causes minor tingling only'],
    answer:'Electricity is invisible, can cause severe shock or death, and starts fires',
    hint:'You cannot always see that something is electrically dangerous.',
    explanation:'Electrical hazards are dangerous because electricity is <b>invisible</b>, can cause lethal shocks, serious burns and house fires. Always respect electrical equipment.' }),

  makeTF({ id:'g3he-saf-010', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Reporting broken or damaged equipment at school helps prevent accidents.',
    answer:true,
    explanation:'<b>True.</b> Damaged equipment — broken swings, sharp edges, frayed carpets — can injure people. Reporting it promptly allows it to be repaired.' }),

  // ── road_water_safety (011–030) ───────────────────────────────────────────

  makeMCQ({ id:'g3he-saf-011', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'What does the Green Cross Code mean?',
    options:['A set of rules to cross the road safely: stop, look, listen, then cross',
             'A type of first aid',
             'A traffic light system',
             'Rules for cycling on footpaths'],
    answer:'A set of rules to cross the road safely: stop, look, listen, then cross',
    hint:'This code is taught to all children for road safety.',
    explanation:'The <b>Green Cross Code</b>: find a safe place → stop → look right, left and right again → listen → if clear, walk straight across. A pedestrian safety standard.' }),

  makeMCQ({ id:'g3he-saf-012', chapterId:'g3he-safety', difficulty:2, subsection:'road_water_safety',
    question:'Why is it more dangerous to cross the road from between parked cars?',
    options:['Drivers cannot see you until you step out, leaving no time to stop',
             'Parked cars block the wind',
             'There is more rubbish between parked cars',
             'It is against the law only'],
    answer:'Drivers cannot see you until you step out, leaving no time to stop',
    hint:'Think about the sight line between a driver and a pedestrian.',
    explanation:'Parked cars <b>block the driver\'s view</b>. You cannot be seen until you step into the road, and drivers may not have time to brake. Always cross where you can be seen clearly.' }),

  makeTF({ id:'g3he-saf-013', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'Children should never swim alone, even in shallow water.',
    answer:true,
    explanation:'<b>True.</b> Drowning can happen quickly and silently. Children must always swim with an adult present who can help if needed.' }),

  makeMCQ({ id:'g3he-saf-014', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'If you see someone drowning, what should you do?',
    options:['Shout for help and call an adult — do NOT jump in unless you are a trained lifeguard',
             'Jump in to save them immediately',
             'Throw stones to alert them',
             'Run away'],
    answer:'Shout for help and call an adult — do NOT jump in unless you are a trained lifeguard',
    hint:'An untrained person can also drown when trying to save someone.',
    explanation:'<b>Shout for help and call an adult or emergency services</b>. Do not jump in unless you are trained — an untrained person can also drown, resulting in two casualties.' }),

  makeMCQ({ id:'g3he-saf-015', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'Why should we never swim at an unguarded beach or river?',
    options:['Currents and waves can be unpredictable and there is no lifeguard to help','Unguarded beaches have nicer sand','It is always colder there','It is a school rule only'],
    answer:'Currents and waves can be unpredictable and there is no lifeguard to help',
    hint:'Lifeguards are there for a reason.',
    explanation:'Unguarded beaches and rivers have <b>unpredictable currents</b> and no trained lifeguard. Swimming there is extremely dangerous even for strong swimmers.' }),

  makeTF({ id:'g3he-saf-016', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'Young children should always wear a life jacket on a boat.',
    answer:true,
    explanation:'<b>True.</b> A life jacket keeps a person afloat even if they fall overboard and are unconscious. It is essential for all children on any watercraft.' }),

  makeMCQ({ id:'g3he-saf-017', chapterId:'g3he-safety', difficulty:2, subsection:'road_water_safety',
    question:'Which road safety rule applies to ALL road users (pedestrians, cyclists and drivers)?',
    options:['Always be aware of your surroundings and follow road signs and signals',
             'Only pedestrians need to follow rules',
             'Cyclists do not need to follow traffic lights',
             'Only drivers are responsible for road safety'],
    answer:'Always be aware of your surroundings and follow road signs and signals',
    hint:'All road users share responsibility.',
    explanation:'<b>All road users</b> must be aware of their surroundings, follow signs and signals, and treat others responsibly to keep roads safe.' }),

  makeMCQ({ id:'g3he-saf-018', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'What should a pedestrian do when walking at night or in low light?',
    options:['Wear bright or reflective clothing and use a torch if possible',
             'Wear dark clothing to blend in',
             'Walk in the middle of the road',
             'Walk faster than normal'],
    answer:'Wear bright or reflective clothing and use a torch if possible',
    hint:'Visibility is key at night.',
    explanation:'At night, pedestrians should wear <b>bright or reflective clothing</b> and use a torch. This makes them visible to drivers who might otherwise not see them.' }),

  makeTF({ id:'g3he-saf-019', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'Stagnant water (like flooded areas) can be dangerous and should be avoided.',
    answer:true,
    explanation:'<b>True.</b> Flooded areas can hide deep ditches or fast currents. The water may also be contaminated with sewage and bacteria.' }),

  makeMCQ({ id:'g3he-saf-020', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'When cycling, what should you always wear?',
    options:['A correctly fitted helmet','Only sunglasses','A scarf','No special equipment needed'],
    answer:'A correctly fitted helmet',
    hint:'Head injuries from cycling accidents can be fatal.',
    explanation:'A <b>correctly fitted helmet</b> is essential when cycling. It protects the skull and brain in a fall or collision.' }),

  // ── emergency_response (021–040) ──────────────────────────────────────────

  makeMCQ({ id:'g3he-saf-021', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'What is the first thing to do in any emergency situation?',
    options:['Stay calm and call for help from an adult or emergency services',
             'Panic and run',
             'Try to fix the problem yourself',
             'Take a photograph'],
    answer:'Stay calm and call for help from an adult or emergency services',
    hint:'Panic makes emergencies worse.',
    explanation:'In any emergency, the first priority is to <b>stay calm and call for help</b>. Panicking prevents you from thinking clearly and acting effectively.' }),

  makeMCQ({ id:'g3he-saf-022', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'What information should you give when calling for emergency help?',
    options:['Your location, what has happened, how many people are hurt and your phone number',
             'Only your name',
             'Only the address',
             'You do not need to say anything — just stay on the line'],
    answer:'Your location, what has happened, how many people are hurt and your phone number',
    hint:'Emergency responders need to know where to go and what they are dealing with.',
    explanation:'Give <b>your location, the nature of the emergency, number of people affected and your phone number</b>. This allows emergency services to respond appropriately.' }),

  makeMCQ({ id:'g3he-saf-023', chapterId:'g3he-safety', difficulty:2, subsection:'emergency_response',
    question:'What should you do if a classmate has a deep cut that is bleeding heavily?',
    options:['Apply gentle pressure with a clean cloth and tell a teacher immediately',
             'Try to remove any object stuck in the wound yourself',
             'Wash it with whatever liquid is available',
             'Ignore it if the person says they are fine'],
    answer:'Apply gentle pressure with a clean cloth and tell a teacher immediately',
    hint:'Stopping blood flow is the immediate priority.',
    explanation:'Apply <b>gentle pressure with a clean cloth</b> to slow bleeding and <b>tell a teacher immediately</b>. Do not remove objects stuck in wounds — this is for medical professionals.' }),

  makeTF({ id:'g3he-saf-024', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'It is important to know your home address in case you need to call for help.',
    answer:true,
    explanation:'<b>True.</b> Knowing your home address means you can direct emergency services to you in a crisis. All children should memorise their address and a parent\'s phone number.' }),

  makeMCQ({ id:'g3he-saf-025', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'If someone is having difficulty breathing, what should you do?',
    options:['Call for emergency help immediately and keep the person calm and still',
             'Give them food and water',
             'Tell them to breathe faster',
             'Leave them alone to rest'],
    answer:'Call for emergency help immediately and keep the person calm and still',
    hint:'Breathing problems are always a medical emergency.',
    explanation:'Difficulty breathing is a medical emergency. <b>Call for help immediately</b> and keep the person calm and as still as possible until help arrives.' }),

  makeTF({ id:'g3he-saf-026', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'A first aid kit should be kept in an accessible location at home and school.',
    answer:true,
    explanation:'<b>True.</b> A readily available first aid kit enables quick treatment of minor injuries and keeps people safe while waiting for further help.' }),

  makeMCQ({ id:'g3he-saf-027', chapterId:'g3he-safety', difficulty:2, subsection:'emergency_response',
    question:'What is the correct treatment for a minor burn (not covering a large area)?',
    options:['Cool with running water for at least 10-20 minutes, then cover with a clean bandage',
             'Apply butter or toothpaste to soothe it',
             'Pop any blisters that form',
             'Wrap tightly in a thick bandage immediately'],
    answer:'Cool with running water for at least 10-20 minutes, then cover with a clean bandage',
    hint:'Cool water removes heat from the burn.',
    explanation:'For a minor burn: <b>cool under running water for 10-20 minutes</b>, then cover with a clean, non-fluffy bandage. Never use butter, oil or toothpaste — these trap heat and cause infection.' }),

  makeMCQ({ id:'g3he-saf-028', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'What should you NEVER do when trying to help an electric shock victim?',
    options:['Touch them while they are still in contact with the electrical source',
             'Call for emergency help',
             'Switch off the power at the source',
             'Keep them warm'],
    answer:'Touch them while they are still in contact with the electrical source',
    hint:'Electricity can travel through the victim to you.',
    explanation:'Never touch an electric shock victim while they are still in contact with the source — the electricity will pass through them to you. First <b>switch off the power</b>, then call for emergency help.' }),

  makeTF({ id:'g3he-saf-029', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'After any accident, it is important to tell an adult or seek medical advice, even if injuries seem minor.',
    answer:true,
    explanation:'<b>True.</b> Some injuries are not immediately apparent. A medical check ensures nothing is missed and proper treatment is given.' }),

  makeMCQ({ id:'g3he-saf-030', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'Learning about first aid and safety is important because:',
    options:['It prepares us to respond calmly and correctly in an emergency, potentially saving lives',
             'It is only useful for doctors',
             'It is only needed in dangerous countries',
             'It is only for parents and teachers'],
    answer:'It prepares us to respond calmly and correctly in an emergency, potentially saving lives',
    hint:'Knowledge helps us act when it matters most.',
    explanation:'First aid knowledge <b>prepares us to act calmly and correctly</b> in an emergency. Even a child\'s basic first aid response can save a life.' })

);

})();
