'use strict';
(function () {

// Grade 3 Health Education — topup questions (subsections 031–040)
// Brings all 9 subsections from 10 to 20 questions each.

STATIC_QUESTIONS.push(

  // ── body_hygiene (031–040) ────────────────────────────────────────────────

  makeMCQ({ id:'g3he-hyg-031', chapterId:'g3he-hygiene', difficulty:2, subsection:'body_hygiene',
    question:'Why do people who do heavy physical work (like farmers) need to bathe more often?',
    options:['They sweat more, so bacteria build up faster on the skin, causing odour and infection risk',
             'Physical work makes skin cleaner',
             'They produce less sweat than office workers',
             'Sweating is unrelated to hygiene'],
    answer:'They sweat more, so bacteria build up faster on the skin, causing odour and infection risk',
    hint:'Think about the link between activity and sweat.',
    explanation:'Heavy physical work causes more sweating. Sweat left on skin <b>feeds bacteria</b>, causing odour and increasing the risk of skin infections. More activity means more frequent washing is needed.' }),

  makeTF({ id:'g3he-hyg-032', chapterId:'g3he-hygiene', difficulty:1, subsection:'body_hygiene',
    question:'Using antibacterial soap is always better than ordinary soap for everyday hand washing.',
    answer:false,
    explanation:'<b>False.</b> Ordinary soap used correctly (20+ seconds, all surfaces) is equally effective for everyday hand washing. Antibacterial soap overuse can contribute to antibiotic resistance.' }),

  makeMCQ({ id:'g3he-hyg-033', chapterId:'g3he-hygiene', difficulty:2, subsection:'body_hygiene',
    question:'Why is it important to dry between the toes properly after bathing?',
    options:['Moist skin between toes is the ideal environment for fungal infections like athlete\'s foot',
             'Wet toes cause colds',
             'Toe skin is sensitive to air',
             'There is no particular reason'],
    answer:'Moist skin between toes is the ideal environment for fungal infections like athlete\'s foot',
    hint:'Think about fungi and moist environments.',
    explanation:'Fungi thrive in moist, warm conditions. Failing to dry between the toes creates <b>ideal conditions for athlete\'s foot</b> and other fungal infections.' }),

  makeTF({ id:'g3he-hyg-034', chapterId:'g3he-hygiene', difficulty:1, subsection:'body_hygiene',
    question:'Our nails grow about 3 mm per month and should be trimmed every few weeks.',
    answer:true,
    explanation:'<b>True.</b> Nails grow continuously. Trimming every 2-3 weeks keeps them at a hygienic length that does not collect dirt and germs.' }),

  makeMCQ({ id:'g3he-hyg-035', chapterId:'g3he-hygiene', difficulty:1, subsection:'body_hygiene',
    question:'Which practice specifically helps prevent body odour?',
    options:['Washing armpits thoroughly with soap and water every day',
             'Wearing thicker clothing',
             'Eating more food',
             'Sleeping more hours'],
    answer:'Washing armpits thoroughly with soap and water every day',
    hint:'Odour comes from bacteria in warm, moist areas.',
    explanation:'Armpits have sweat glands and bacteria thrive there. <b>Washing with soap daily</b> removes bacteria and sweat, preventing body odour.' }),

  makeMCQ({ id:'g3he-hyg-036', chapterId:'g3he-hygiene', difficulty:2, subsection:'body_hygiene',
    question:'Why is it important to wear clean, breathable clothing (like cotton) in Mauritius\'s hot climate?',
    options:['Cotton absorbs sweat and allows skin to breathe, reducing bacteria and heat rash',
             'Cotton makes us look smarter',
             'Synthetic fabrics are always healthier',
             'Clothing has no impact on skin health'],
    answer:'Cotton absorbs sweat and allows skin to breathe, reducing bacteria and heat rash',
    hint:'In hot climates, what happens to sweat?',
    explanation:'In Mauritius\'s tropical heat, <b>breathable cotton absorbs sweat</b>, allowing it to evaporate. Trapped sweat in synthetic fabrics creates a warm, moist layer that promotes bacteria and skin rashes.' }),

  makeTF({ id:'g3he-hyg-037', chapterId:'g3he-hygiene', difficulty:1, subsection:'body_hygiene',
    question:'It is good hygiene practice to wash our hair at least twice a week.',
    answer:true,
    explanation:'<b>True.</b> Hair collects dirt, sweat and pollutants. Washing at least twice a week keeps the scalp clean and healthy.' }),

  makeMCQ({ id:'g3he-hyg-038', chapterId:'g3he-hygiene', difficulty:1, subsection:'body_hygiene',
    question:'What is the main benefit of wearing clean, properly fitting shoes?',
    options:['They protect the feet from injury, keep them hygienic and support foot development',
             'Only to look fashionable',
             'To make feet sweat more',
             'Shoes have no effect on hygiene'],
    answer:'They protect the feet from injury, keep them hygienic and support foot development',
    hint:'Shoes do more than just cover the feet.',
    explanation:'Well-fitting, clean shoes <b>protect against injury, cuts and infections</b>, while properly sized shoes support foot development and posture during childhood.' }),

  makeTF({ id:'g3he-hyg-039', chapterId:'g3he-hygiene', difficulty:1, subsection:'body_hygiene',
    question:'Sharing towels between family members is acceptable hygiene practice.',
    answer:false,
    explanation:'<b>False.</b> Towels carry bacteria, skin cells and potentially fungi. Each person should use their own towel to prevent sharing infections.' }),

  makeMCQ({ id:'g3he-hyg-040', chapterId:'g3he-hygiene', difficulty:2, subsection:'body_hygiene',
    question:'A child notices a red, itchy rash after using a new soap. What should they do?',
    options:['Stop using the new soap and tell an adult or parent who can consult a pharmacist or doctor',
             'Wash more frequently with the same soap to clear it',
             'Ignore it — all rashes clear up in a day',
             'Apply toothpaste to the rash'],
    answer:'Stop using the new soap and tell an adult or parent who can consult a pharmacist or doctor',
    hint:'Rashes after using a new product suggest a reaction.',
    explanation:'A red, itchy rash after using a new product suggests an <b>allergic reaction or skin sensitivity</b>. Stop using the product immediately and consult a pharmacist or doctor.' }),

  // ── disease_prevention (031–040) ──────────────────────────────────────────

  makeMCQ({ id:'g3he-hyg-041', chapterId:'g3he-hygiene', difficulty:2, subsection:'disease_prevention',
    question:'What is "herd immunity"?',
    options:['When enough people in a community are vaccinated that even unvaccinated people are protected because the disease can\'t spread easily',
             'When animals protect humans from disease',
             'When only old people are vaccinated',
             'When a disease becomes stronger'],
    answer:'When enough people in a community are vaccinated that even unvaccinated people are protected because the disease can\'t spread easily',
    hint:'Think about what happens when most people are immune.',
    explanation:'<b>Herd immunity</b> occurs when a high percentage of the population is vaccinated, making it difficult for a disease to spread — even those who cannot be vaccinated are protected.' }),

  makeTF({ id:'g3he-hyg-042', chapterId:'g3he-hygiene', difficulty:1, subsection:'disease_prevention',
    question:'Antibiotics are effective against bacterial infections but do NOT work against viral infections like the common cold.',
    answer:true,
    explanation:'<b>True.</b> Antibiotics kill bacteria. Viruses (cold, flu) are not affected by antibiotics. Taking them for colds is ineffective and contributes to antibiotic resistance.' }),

  makeMCQ({ id:'g3he-hyg-043', chapterId:'g3he-hygiene', difficulty:1, subsection:'disease_prevention',
    question:'Which disease is spread by drinking contaminated water?',
    options:['Cholera','Chicken pox','Measles','Tooth decay'],
    answer:'Cholera',
    hint:'Think about diseases linked to unclean water.',
    explanation:'<b>Cholera</b> is a bacterial infection spread through water contaminated with faeces. It causes severe diarrhoea and dehydration and can be fatal without treatment.' }),

  makeTF({ id:'g3he-hyg-044', chapterId:'g3he-hygiene', difficulty:1, subsection:'disease_prevention',
    question:'Regular exercise boosts our immune system, helping us fight off illness more effectively.',
    answer:true,
    explanation:'<b>True.</b> Regular moderate exercise improves circulation and immune cell production, helping the body detect and fight infections more efficiently.' }),

  makeMCQ({ id:'g3he-hyg-045', chapterId:'g3he-hygiene', difficulty:2, subsection:'disease_prevention',
    question:'In Mauritius, what is the most important season to be extra careful about mosquito-borne diseases?',
    options:['The hot, rainy season (summer: November to April) when Aedes mosquitoes breed most actively',
             'The cool, dry winter months (June to August)',
             'Only during cyclones',
             'Mosquito activity is the same all year'],
    answer:'The hot, rainy season (summer: November to April) when Aedes mosquitoes breed most actively',
    hint:'Think about when mosquitoes breed most.',
    explanation:'Dengue and other Aedes mosquito-borne diseases peak in <b>Mauritius\'s hot, rainy summer</b> (November–April) when standing water is abundant and temperatures favour mosquito breeding.' }),

  makeMCQ({ id:'g3he-hyg-046', chapterId:'g3he-hygiene', difficulty:1, subsection:'disease_prevention',
    question:'Which practice reduces the risk of food-borne illness?',
    options:['Washing hands before cooking, cooking food thoroughly and storing leftovers in the fridge',
             'Tasting food while cooking to check for freshness',
             'Using the same chopping board for raw meat and vegetables',
             'Leaving cooked food on the counter for 6 hours'],
    answer:'Washing hands before cooking, cooking food thoroughly and storing leftovers in the fridge',
    hint:'Food safety involves preparation, cooking and storage.',
    explanation:'Food safety requires <b>clean hands, thorough cooking and proper storage</b>. Using the same board for raw meat and vegetables causes cross-contamination.' }),

  makeTF({ id:'g3he-hyg-047', chapterId:'g3he-hygiene', difficulty:1, subsection:'disease_prevention',
    question:'Sharing needles or syringes is extremely dangerous and can spread diseases like HIV and hepatitis.',
    answer:true,
    explanation:'<b>True.</b> Shared needles carry blood which may contain serious blood-borne viruses. Even a tiny amount of infected blood can transmit HIV or hepatitis B and C.' }),

  makeMCQ({ id:'g3he-hyg-048', chapterId:'g3he-hygiene', difficulty:2, subsection:'disease_prevention',
    question:'Why do some diseases spread more easily in overcrowded places?',
    options:['More people in a small space means more airborne droplets, more surface contact and faster disease transmission',
             'Overcrowding makes people stronger',
             'People in crowds have more energy',
             'There is no link between crowding and disease spread'],
    answer:'More people in a small space means more airborne droplets, more surface contact and faster disease transmission',
    hint:'Think about what happens to coughs and sneezes in a crowded space.',
    explanation:'Overcrowded spaces allow <b>cough/sneeze droplets and surface contact germs to travel quickly</b> from person to person. Ventilation and spacing reduce risk.' }),

  makeTF({ id:'g3he-hyg-049', chapterId:'g3he-hygiene', difficulty:1, subsection:'disease_prevention',
    question:'Getting enough sleep helps our immune system stay strong.',
    answer:true,
    explanation:'<b>True.</b> During sleep, the body produces cytokines — proteins that fight infection and inflammation. Poor sleep weakens the immune system.' }),

  makeMCQ({ id:'g3he-hyg-050', chapterId:'g3he-hygiene', difficulty:1, subsection:'disease_prevention',
    question:'Which is the best description of a "healthy lifestyle" that prevents disease?',
    options:['Regular exercise, balanced diet, adequate sleep, clean water, good hygiene and no smoking or excessive alcohol',
             'Eating as much food as possible',
             'Sleeping all day and avoiding exercise',
             'Only taking medicine when sick'],
    answer:'Regular exercise, balanced diet, adequate sleep, clean water, good hygiene and no smoking or excessive alcohol',
    hint:'Good health comes from multiple positive habits together.',
    explanation:'A <b>healthy lifestyle</b> combines exercise, balanced nutrition, sleep, hydration, hygiene and avoiding harmful substances — all working together to prevent disease.' }),

  // ── community_hygiene (031–040) ───────────────────────────────────────────

  makeMCQ({ id:'g3he-hyg-051', chapterId:'g3he-hygiene', difficulty:2, subsection:'community_hygiene',
    question:'How does poor rubbish disposal in a community contribute to disease?',
    options:['Rubbish attracts flies and rats that spread disease, and blocks drains causing flooding and mosquito breeding',
             'Rubbish only smells bad — it has no health effects',
             'Rubbish disposal is only an environmental issue, not a health one',
             'Only industrial rubbish causes disease'],
    answer:'Rubbish attracts flies and rats that spread disease, and blocks drains causing flooding and mosquito breeding',
    hint:'Think about what rubbish attracts.',
    explanation:'Uncollected rubbish <b>attracts flies (spreading cholera, dysentery) and rats (spreading leptospirosis)</b>. Blocked drains create mosquito breeding grounds for dengue fever.' }),

  makeTF({ id:'g3he-hyg-052', chapterId:'g3he-hygiene', difficulty:1, subsection:'community_hygiene',
    question:'Open-air burning of rubbish is a safe and healthy way to dispose of waste.',
    answer:false,
    explanation:'<b>False.</b> Burning rubbish releases toxic gases and particles that cause respiratory disease. Safe disposal in bins or at recycling centres is far healthier for the community.' }),

  makeMCQ({ id:'g3he-hyg-053', chapterId:'g3he-hygiene', difficulty:1, subsection:'community_hygiene',
    question:'What is recycling, and why is it good for community health?',
    options:['Converting waste into new materials; it reduces landfill, pollution and the resources needed to make new products',
             'Throwing rubbish in the river to remove it from streets',
             'Burning old items so they disappear',
             'Leaving rubbish in the countryside'],
    answer:'Converting waste into new materials; it reduces landfill, pollution and the resources needed to make new products',
    hint:'Think about what happens to glass, paper and plastic when recycled.',
    explanation:'<b>Recycling</b> converts waste into useful materials, reducing landfill sites, water and air pollution — making the community environment healthier for everyone.' }),

  makeTF({ id:'g3he-hyg-054', chapterId:'g3he-hygiene', difficulty:1, subsection:'community_hygiene',
    question:'A community with access to clean piped water and good sanitation has lower rates of water-borne disease.',
    answer:true,
    explanation:'<b>True.</b> Safe water and sanitation (toilets and sewage systems) directly prevent cholera, typhoid and diarrhoeal diseases — some of history\'s greatest killers.' }),

  makeMCQ({ id:'g3he-hyg-055', chapterId:'g3he-hygiene', difficulty:2, subsection:'community_hygiene',
    question:'After a cyclone in Mauritius, why is it especially important to boil water before drinking?',
    options:['Floodwater can contaminate the water supply with bacteria and sewage, making tap water unsafe',
             'Cyclones make water taste different only',
             'Cyclones bring extra minerals into water',
             'Water is always safe after rain'],
    answer:'Floodwater can contaminate the water supply with bacteria and sewage, making tap water unsafe',
    hint:'Think about what flood water mixes with.',
    explanation:'After cyclones, <b>floodwater can contaminate pipes with sewage and bacteria</b>. Authorities advise boiling water until the supply is confirmed safe, to prevent disease outbreaks.' }),

  makeMCQ({ id:'g3he-hyg-056', chapterId:'g3he-hygiene', difficulty:1, subsection:'community_hygiene',
    question:'What is the purpose of a community health clinic?',
    options:['To provide healthcare, vaccinations and health education to people in the local area',
             'Only to sell medicines',
             'Only for emergencies',
             'Only for elderly people'],
    answer:'To provide healthcare, vaccinations and health education to people in the local area',
    hint:'Community clinics serve the whole local population.',
    explanation:'Community health clinics provide <b>primary healthcare, immunisations and health education</b> to local residents, promoting wellness and preventing disease before it spreads.' }),

  makeTF({ id:'g3he-hyg-057', chapterId:'g3he-hygiene', difficulty:1, subsection:'community_hygiene',
    question:'Every member of a community, including children, has a role in keeping the environment clean.',
    answer:true,
    explanation:'<b>True.</b> Community cleanliness is everyone\'s responsibility. Even children can contribute by not littering, picking up litter and encouraging others to do the same.' }),

  makeMCQ({ id:'g3he-hyg-058', chapterId:'g3he-hygiene', difficulty:1, subsection:'community_hygiene',
    question:'Why should we not wash cars, clothes or animals directly in rivers or streams?',
    options:['Soaps and chemicals pollute the water, harming aquatic life and contaminating water sources used by communities',
             'Rivers are only for swimming',
             'Rivers flow too fast for washing',
             'It is perfectly safe to wash in rivers'],
    answer:'Soaps and chemicals pollute the water, harming aquatic life and contaminating water sources used by communities',
    hint:'Think about where that soapy water goes.',
    explanation:'Detergents and chemicals from washing <b>pollute rivers</b>, destroying aquatic ecosystems and contaminating water sources that communities may rely on for drinking.' }),

  makeTF({ id:'g3he-hyg-059', chapterId:'g3he-hygiene', difficulty:1, subsection:'community_hygiene',
    question:'Reporting a broken drain or sewage pipe to local authorities helps protect the whole community\'s health.',
    answer:true,
    explanation:'<b>True.</b> A broken sewage pipe releases bacteria into the environment. Reporting it quickly allows repairs that prevent disease spreading through the neighbourhood.' }),

  makeMCQ({ id:'g3he-hyg-060', chapterId:'g3he-hygiene', difficulty:2, subsection:'community_hygiene',
    question:'Schools can help improve community health by:',
    options:['Teaching hygiene, organising clean-up activities and providing a safe, hygienic environment for children',
             'Only teaching maths and languages',
             'Providing free sweets and fizzy drinks',
             'Ignoring health topics — those are for hospitals'],
    answer:'Teaching hygiene, organising clean-up activities and providing a safe, hygienic environment for children',
    hint:'Schools are part of the community and can lead by example.',
    explanation:'Schools are <b>powerful community health resources</b> — health education, hygiene practices taught to children spread to families and communities, creating a ripple effect of improved health.' }),

  // ── nutrients (031–040) ───────────────────────────────────────────────────

  makeMCQ({ id:'g3he-nut-031', chapterId:'g3he-nutrition', difficulty:2, subsection:'nutrients',
    question:'Which nutrients provide the building material for ALL body cells?',
    options:['Proteins — they form every enzyme, hormone, muscle and organ in the body',
             'Carbohydrates only',
             'Fats only',
             'Water only'],
    answer:'Proteins — they form every enzyme, hormone, muscle and organ in the body',
    hint:'Building material for the body.',
    explanation:'<b>Proteins</b> are the fundamental building material for every cell, enzyme, hormone and antibody in the body. Without adequate protein, growth and repair cannot happen.' }),

  makeTF({ id:'g3he-nut-032', chapterId:'g3he-nutrition', difficulty:1, subsection:'nutrients',
    question:'Vitamin C is found in citrus fruits, guavas and tomatoes, and helps the body absorb iron.',
    answer:true,
    explanation:'<b>True.</b> Vitamin C enhances the absorption of non-haem iron (from plant sources like spinach). Eating a guava with a lentil dish, for example, doubles the iron absorbed.' }),

  makeMCQ({ id:'g3he-nut-033', chapterId:'g3he-nutrition', difficulty:2, subsection:'nutrients',
    question:'Which of these PAIRS of nutrients works together: one helps build bones, the other helps the body absorb it?',
    options:['Calcium and Vitamin D — Vitamin D is needed for the body to absorb and use calcium',
             'Sugar and salt — they balance each other',
             'Fat and Vitamin C — they work as one unit',
             'Iron and fat — they cancel each other out'],
    answer:'Calcium and Vitamin D — Vitamin D is needed for the body to absorb and use calcium',
    hint:'Think about what makes bones strong.',
    explanation:'<b>Calcium</b> builds bones, but without <b>Vitamin D</b> the gut cannot absorb calcium properly. That\'s why milk (calcium) is often fortified with Vitamin D.' }),

  makeTF({ id:'g3he-nut-034', chapterId:'g3he-nutrition', difficulty:1, subsection:'nutrients',
    question:'Eating too much salt (sodium) over a long period can raise blood pressure and increase the risk of heart disease.',
    answer:true,
    explanation:'<b>True.</b> Excess sodium causes the body to retain water, increasing blood pressure. High blood pressure damages blood vessels and is a leading cause of heart disease and stroke.' }),

  makeMCQ({ id:'g3he-nut-035', chapterId:'g3he-nutrition', difficulty:1, subsection:'nutrients',
    question:'Omega-3 fatty acids, found in fish like tuna and sardines, are important for:',
    options:['Brain development and function, and reducing inflammation in the body',
             'Only making hair shiny',
             'Only providing energy',
             'Replacing calcium in bones'],
    answer:'Brain development and function, and reducing inflammation in the body',
    hint:'These fats are often linked to brain health.',
    explanation:'<b>Omega-3 fatty acids</b> support brain development, improve memory and concentration, and reduce inflammation. Fish common in Mauritius (tuna, sardines) are excellent sources.' }),

  makeMCQ({ id:'g3he-nut-036', chapterId:'g3he-nutrition', difficulty:2, subsection:'nutrients',
    question:'Why do children need MORE iron in their diet than adults (per body weight)?',
    options:['Children are growing rapidly — more red blood cells are needed as the blood volume increases',
             'Children use iron to think better',
             'Children lose more iron through sweat',
             'Iron needs are the same throughout life'],
    answer:'Children are growing rapidly — more red blood cells are needed as the blood volume increases',
    hint:'Think about why growing bodies need more of certain nutrients.',
    explanation:'As children grow, their blood volume increases rapidly. More red blood cells (which contain iron) are needed, so <b>iron requirements are proportionally higher during childhood</b>.' }),

  makeTF({ id:'g3he-nut-037', chapterId:'g3he-nutrition', difficulty:1, subsection:'nutrients',
    question:'Potassium, found in bananas and potatoes, helps muscles (including the heart) contract properly.',
    answer:true,
    explanation:'<b>True.</b> Potassium is essential for nerve signal transmission and muscle contraction, including the heart muscle. Deficiency can cause muscle cramps and heart irregularities.' }),

  makeMCQ({ id:'g3he-nut-038', chapterId:'g3he-nutrition', difficulty:2, subsection:'nutrients',
    question:'A child who does not eat enough iron-rich food may become:',
    options:['Anaemic — pale, tired and short of breath because there are too few red blood cells to carry oxygen',
             'Overweight immediately',
             'More energetic',
             'Unable to swallow food'],
    answer:'Anaemic — pale, tired and short of breath because there are too few red blood cells to carry oxygen',
    hint:'Iron is needed for red blood cells.',
    explanation:'Iron deficiency causes <b>anaemia</b> — too few red blood cells to carry oxygen efficiently. Symptoms include fatigue, pallor, breathlessness and poor concentration.' }),

  makeTF({ id:'g3he-nut-039', chapterId:'g3he-nutrition', difficulty:1, subsection:'nutrients',
    question:'Most vitamins and minerals work best when obtained from FOOD, rather than supplements, because food provides them alongside other helpful compounds.',
    answer:true,
    explanation:'<b>True.</b> Whole foods provide nutrients together with fibre, antioxidants and other compounds that aid absorption. Supplements provide isolated nutrients and are less effective overall.' }),

  makeMCQ({ id:'g3he-nut-040', chapterId:'g3he-nutrition', difficulty:1, subsection:'nutrients',
    question:'Which of the following is NOT a macronutrient (the three main nutrient groups)?',
    options:['Vitamin C','Carbohydrates','Proteins','Fats'],
    answer:'Vitamin C',
    hint:'Macronutrients are needed in large amounts; micronutrients in small amounts.',
    explanation:'The three <b>macronutrients</b> are carbohydrates, proteins and fats — needed in large amounts. Vitamin C is a <b>micronutrient</b> (vitamin), needed only in small amounts.' }),

  // ── food_energy (031–040) ─────────────────────────────────────────────────

  makeMCQ({ id:'g3he-nut-041', chapterId:'g3he-nutrition', difficulty:2, subsection:'food_energy',
    question:'Why do children need more calories (food energy) per kilogram of body weight than adults?',
    options:['They are growing, very physically active and their organs are developing rapidly',
             'Children have smaller stomachs so need more concentrated food',
             'Children burn energy more slowly',
             'There is no difference'],
    answer:'They are growing, very physically active and their organs are developing rapidly',
    hint:'Growth and development require extra energy.',
    explanation:'Children\'s bodies are <b>growing, active and developing</b> simultaneously, requiring proportionally more energy than adult bodies that are only maintaining themselves.' }),

  makeTF({ id:'g3he-nut-042', chapterId:'g3he-nutrition', difficulty:1, subsection:'food_energy',
    question:'Fried foods contain more calories than the same food cooked by boiling or grilling.',
    answer:true,
    explanation:'<b>True.</b> Frying adds significant fat (and therefore calories) to food. Boiling and grilling use little or no added fat, producing lower-calorie versions of the same foods.' }),

  makeMCQ({ id:'g3he-nut-043', chapterId:'g3he-nutrition', difficulty:1, subsection:'food_energy',
    question:'Which meal best provides slow-release energy to keep a child alert throughout a school morning?',
    options:['Wholemeal bread with egg and a piece of fruit',
             'A sugary doughnut and cola',
             'Plain white sugar in warm water',
             'Sweets and chocolate only'],
    answer:'Wholemeal bread with egg and a piece of fruit',
    hint:'Slow-release energy comes from complex carbohydrates, not sugar.',
    explanation:'<b>Wholemeal bread</b> provides complex carbohydrates for slow-release energy. Egg adds protein. Fruit adds vitamins. Together they sustain concentration for hours, unlike sugar which spikes then crashes.' }),

  makeTF({ id:'g3he-nut-044', chapterId:'g3he-nutrition', difficulty:1, subsection:'food_energy',
    question:'If we eat more energy (food) than we use through activity, the extra is stored as fat in the body.',
    answer:true,
    explanation:'<b>True.</b> Unused energy is converted to and stored as body fat. Over time, consistently eating more than we need leads to weight gain and associated health problems.' }),

  makeMCQ({ id:'g3he-nut-045', chapterId:'g3he-nutrition', difficulty:2, subsection:'food_energy',
    question:'Reena walks 3 km to school every day but has a desk job mother who uses a car. Who needs more calories per day?',
    options:['Reena — greater physical activity burns more energy which must be replaced by food',
             'The mother — adults always need more calories',
             'They need exactly the same amount',
             'Calorie needs don\'t depend on activity'],
    answer:'Reena — greater physical activity burns more energy which must be replaced by food',
    hint:'Activity level determines energy expenditure.',
    explanation:'<b>Physical activity is one of the biggest factors in energy needs.</b> Reena burns more energy walking 3 km daily and needs more calories to replace it.' }),

  makeMCQ({ id:'g3he-nut-046', chapterId:'g3he-nutrition', difficulty:1, subsection:'food_energy',
    question:'Which Mauritian food is an excellent plant-based protein that also provides carbohydrate energy?',
    options:['Red kidney beans (pois rouge)','Plain white sugar','Cooking oil','Fizzy drinks'],
    answer:'Red kidney beans (pois rouge)',
    hint:'Think about popular Mauritian legume dishes.',
    explanation:'<b>Red kidney beans (pois rouge)</b> are a staple in Mauritian cuisine. They provide both protein (for growth) and complex carbohydrates (for energy) — a highly nutritious combination.' }),

  makeTF({ id:'g3he-nut-047', chapterId:'g3he-nutrition', difficulty:1, subsection:'food_energy',
    question:'Eating protective foods (fruits and vegetables) with energy foods helps our immune system use the energy efficiently.',
    answer:true,
    explanation:'<b>True.</b> Vitamins and minerals in protective foods are often co-factors for enzymes that metabolise energy. A balanced meal works synergistically, not in isolation.' }),

  makeMCQ({ id:'g3he-nut-048', chapterId:'g3he-nutrition', difficulty:2, subsection:'food_energy',
    question:'Marco eats a large bowl of plain white rice for lunch every day but no protein or vegetables. Over months, what might happen?',
    options:['He may develop protein deficiency (kwashiorkor-like symptoms) and vitamin deficiencies — growth and immunity will suffer',
             'He will become very healthy — rice has everything',
             'His muscles will grow bigger',
             'Nothing will change'],
    answer:'He may develop protein deficiency (kwashiorkor-like symptoms) and vitamin deficiencies — growth and immunity will suffer',
    hint:'What is missing from a diet of only plain rice?',
    explanation:'Plain white rice provides only carbohydrates. Over time, <b>protein and vitamin deficiency</b> leads to stunted growth, muscle loss, weakened immunity and nutrient-deficiency diseases.' }),

  makeTF({ id:'g3he-nut-049', chapterId:'g3he-nutrition', difficulty:1, subsection:'food_energy',
    question:'Brown rice is more nutritious than white rice because the outer bran layer contains fibre, vitamins and minerals.',
    answer:true,
    explanation:'<b>True.</b> Milling removes the bran from white rice, stripping away fibre, B vitamins and minerals. Brown rice retains these, making it more nutritious.' }),

  makeMCQ({ id:'g3he-nut-050', chapterId:'g3he-nutrition', difficulty:1, subsection:'food_energy',
    question:'What is the role of fats in the diet (in the right amount)?',
    options:['Provide energy, absorb fat-soluble vitamins, insulate the body and protect organs',
             'Only to make food taste nice',
             'Only to cause weight gain',
             'Fats have no useful role in the body'],
    answer:'Provide energy, absorb fat-soluble vitamins, insulate the body and protect organs',
    hint:'Fats do more than just provide calories.',
    explanation:'<b>Dietary fats</b> provide concentrated energy, help absorb vitamins A, D, E and K, insulate the body against temperature changes and cushion organs. Healthy fats are necessary.' }),

  // ── water_diet (031–040) ──────────────────────────────────────────────────

  makeMCQ({ id:'g3he-nut-051', chapterId:'g3he-nutrition', difficulty:2, subsection:'water_diet',
    question:'Why is urine colour a useful indicator of hydration?',
    options:['Pale yellow urine indicates good hydration; dark yellow or orange indicates dehydration — the body is conserving water',
             'Urine colour is random and meaningless',
             'Clear urine always means dehydration',
             'Dark urine is healthier'],
    answer:'Pale yellow urine indicates good hydration; dark yellow or orange indicates dehydration — the body is conserving water',
    hint:'The kidneys concentrate urine when water intake is low.',
    explanation:'<b>Urine colour</b> is a reliable hydration signal. Pale yellow = well-hydrated. Dark yellow/orange = dehydrated — the kidneys are conserving water by concentrating urine.' }),

  makeTF({ id:'g3he-nut-052', chapterId:'g3he-nutrition', difficulty:1, subsection:'water_diet',
    question:'In Mauritius\'s hot summer, children should drink more water than in the cooler months.',
    answer:true,
    explanation:'<b>True.</b> Heat increases sweating, which increases water loss. More water must be drunk to replace it and prevent dehydration.' }),

  makeMCQ({ id:'g3he-nut-053', chapterId:'g3he-nutrition', difficulty:2, subsection:'water_diet',
    question:'Why is it dangerous to drink seawater if you are stranded without fresh water?',
    options:['Seawater is saltier than body fluids — drinking it forces the kidneys to use MORE water to excrete the salt, making dehydration worse',
             'Seawater is perfectly safe to drink in small amounts',
             'Seawater provides minerals the body needs when dehydrated',
             'The only problem is the taste'],
    answer:'Seawater is saltier than body fluids — drinking it forces the kidneys to use MORE water to excrete the salt, making dehydration worse',
    hint:'Think about what the kidneys must do to remove excess salt.',
    explanation:'Seawater has far more salt than body fluids. To excrete that salt, the kidneys use <b>more water than was drunk</b>, accelerating dehydration. It is a survival myth that seawater helps.' }),

  makeTF({ id:'g3he-nut-054', chapterId:'g3he-nutrition', difficulty:1, subsection:'water_diet',
    question:'Fruits and vegetables also contribute to our daily water intake because they contain a high percentage of water.',
    answer:true,
    explanation:'<b>True.</b> Cucumbers, watermelon, tomatoes and most fruits are over 80% water. Eating them contributes significantly to daily hydration.' }),

  makeMCQ({ id:'g3he-nut-055', chapterId:'g3he-nutrition', difficulty:2, subsection:'water_diet',
    question:'Which of these is NOT part of a balanced diet?',
    options:['Eating sweets and fried food as the main part of every meal',
             'Eating fruits and vegetables daily',
             'Drinking enough water',
             'Eating protein-rich foods regularly'],
    answer:'Eating sweets and fried food as the main part of every meal',
    hint:'A balanced diet includes some of everything — but not all in equal measure.',
    explanation:'<b>Sweets and fried food</b> are high in sugar/fat and low in nutrients. They should be occasional treats, not the main component of meals. A balanced diet is built on nutrient-dense foods.' }),

  makeMCQ({ id:'g3he-nut-056', chapterId:'g3he-nutrition', difficulty:1, subsection:'water_diet',
    question:'What happens to the body\'s performance when mildly dehydrated (as little as 2% water loss)?',
    options:['Concentration drops, reaction time slows and physical performance decreases',
             'Nothing noticeable occurs',
             'The body performs better',
             'Only athletes are affected by mild dehydration'],
    answer:'Concentration drops, reaction time slows and physical performance decreases',
    hint:'Even mild dehydration affects the brain.',
    explanation:'Just <b>2% water loss</b> (mild dehydration) measurably reduces concentration, mental alertness and physical performance. Children should drink water regularly, not only when very thirsty.' }),

  makeTF({ id:'g3he-nut-057', chapterId:'g3he-nutrition', difficulty:1, subsection:'water_diet',
    question:'A balanced diet that includes all food groups in appropriate amounts helps maintain a healthy body weight.',
    answer:true,
    explanation:'<b>True.</b> When energy intake matches energy expenditure and the diet is nutritionally complete, the body maintains a healthy weight and functions optimally.' }),

  makeMCQ({ id:'g3he-nut-058', chapterId:'g3he-nutrition', difficulty:2, subsection:'water_diet',
    question:'The concept of "eating a rainbow" (red, orange, green, purple foods) is helpful because:',
    options:['Each colour in fruits and vegetables represents different antioxidants and vitamins, so variety ensures the widest range of nutrients',
             'Colourful foods simply taste better',
             'Only orange foods have vitamins',
             'Colour in food indicates the presence of artificial dyes'],
    answer:'Each colour in fruits and vegetables represents different antioxidants and vitamins, so variety ensures the widest range of nutrients',
    hint:'Think about why different colours exist in plants.',
    explanation:'Plant colours come from <b>phytonutrients and antioxidants</b>: red = lycopene, orange = beta-carotene, green = chlorophyll/lutein. "Eating a rainbow" maximises nutrient variety.' }),

  makeTF({ id:'g3he-nut-059', chapterId:'g3he-nutrition', difficulty:1, subsection:'water_diet',
    question:'Drinking water with meals helps digestion.',
    answer:true,
    explanation:'<b>True.</b> Water helps break down food, allows digestive enzymes to work effectively and helps transport nutrients through the digestive system.' }),

  makeMCQ({ id:'g3he-nut-060', chapterId:'g3he-nutrition', difficulty:1, subsection:'water_diet',
    question:'Which meal plan best represents a full day of balanced eating?',
    options:['Breakfast: egg on toast + fruit. Lunch: rice + lentil dhal + vegetable. Dinner: fish + vegetables + rice. Water throughout.',
             'Three meals of fried food and cola',
             'Only salad for all three meals',
             'No breakfast + large dessert for lunch + nothing for dinner'],
    answer:'Breakfast: egg on toast + fruit. Lunch: rice + lentil dhal + vegetable. Dinner: fish + vegetables + rice. Water throughout.',
    hint:'Look for the plan that includes all food groups at every meal.',
    explanation:'This plan includes <b>protein, carbohydrate, vegetables and hydration at every meal</b> — a genuinely balanced day of eating for a growing child in Mauritius.' }),

  // ── accident_prevention (031–040) ─────────────────────────────────────────

  makeMCQ({ id:'g3he-saf-031', chapterId:'g3he-safety', difficulty:2, subsection:'accident_prevention',
    question:'Why is distracted walking (looking at a phone while walking) dangerous?',
    options:['You cannot see hazards like steps, uneven pavement, cyclists or road traffic',
             'It makes you walk slower',
             'It only affects adults',
             'It is only dangerous at night'],
    answer:'You cannot see hazards like steps, uneven pavement, cyclists or road traffic',
    hint:'Think about what you cannot see when looking at a screen.',
    explanation:'Distracted walking means your attention is on the screen, not the environment. You miss <b>steps, obstacles, cyclists and traffic</b> — causing trips, falls and being hit by vehicles.' }),

  makeTF({ id:'g3he-saf-032', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'A spill on the floor should be cleaned up immediately to prevent someone slipping.',
    answer:true,
    explanation:'<b>True.</b> Liquid on a floor creates an invisible hazard. Slips on wet floors are a leading cause of serious injuries. Clean spills up the moment they happen.' }),

  makeMCQ({ id:'g3he-saf-033', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Why should we not run near a swimming pool?',
    options:['Wet pool surfaces are extremely slippery — running causes falls and can result in serious head or spinal injuries',
             'Running makes the water splash',
             'It is a noise regulation',
             'Running near pools is safe in shallow areas'],
    answer:'Wet pool surfaces are extremely slippery — running causes falls and can result in serious head or spinal injuries',
    hint:'Think about the surface condition near pools.',
    explanation:'Pool surrounds are always wet. Running on wet surfaces causes falls. If you hit your head on the pool edge or the hard ground, the result can be <b>fatal</b>. Always walk near pools.' }),

  makeTF({ id:'g3he-saf-034', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Keeping walkways and corridors clear of bags and equipment prevents trip-and-fall accidents.',
    answer:true,
    explanation:'<b>True.</b> Objects in walkways cause people to trip, especially when they are carrying something and cannot see the floor. Clear paths are a simple accident prevention measure.' }),

  makeMCQ({ id:'g3he-saf-035', chapterId:'g3he-safety', difficulty:2, subsection:'accident_prevention',
    question:'Why should we never mix household cleaning chemicals (like bleach and ammonia)?',
    options:['They react chemically to produce toxic gases that can severely damage the lungs and cause death',
             'They cancel each other out and become useless',
             'They only produce a bad smell — no other danger',
             'Mixing makes them work faster'],
    answer:'They react chemically to produce toxic gases that can severely damage the lungs and cause death',
    hint:'Chemical reactions between cleaning products can be deadly.',
    explanation:'Bleach + ammonia creates <b>toxic chloramine gases</b> that damage the respiratory system. Mixing any cleaning chemicals is dangerous. Read labels and never mix products.' }),

  makeMCQ({ id:'g3he-saf-036', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'When using scissors or a craft knife for a school project, which practice prevents cuts?',
    options:['Cut away from yourself, keep fingers clear of the blade and use the correct tool for the material',
             'Cut towards yourself for more control',
             'Use sharp tools as fast as possible',
             'Hold the sharp edge and pass it to a friend'],
    answer:'Cut away from yourself, keep fingers clear of the blade and use the correct tool for the material',
    hint:'Safe cutting technique keeps the blade away from the body.',
    explanation:'Always <b>cut away from yourself</b>, keep fingers well behind the blade and use the appropriate tool. Most craft cuts happen when people cut towards themselves or rush.' }),

  makeTF({ id:'g3he-saf-037', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Wearing appropriate personal protective equipment (PPE) reduces the risk of injury during hazardous activities.',
    answer:true,
    explanation:'<b>True.</b> PPE like helmets for cycling, goggles for science experiments and gloves for gardening directly reduces injury risk by forming a barrier between the body and hazards.' }),

  makeMCQ({ id:'g3he-saf-038', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Which of these is a common cause of house fires in Mauritius?',
    options:['Leaving cooking unattended on the stove and electrical faults',
             'Leaving lights on too long',
             'Running inside the house',
             'Keeping too many books indoors'],
    answer:'Leaving cooking unattended on the stove and electrical faults',
    hint:'Think about heat sources and electrical wiring.',
    explanation:'<b>Unattended cooking and faulty electrical wiring</b> are leading causes of house fires globally and in Mauritius. Never leave cooking unattended; check wiring regularly.' }),

  makeTF({ id:'g3he-saf-039', chapterId:'g3he-safety', difficulty:1, subsection:'accident_prevention',
    question:'Children under 12 should not be left alone to supervise younger siblings, as accidents can happen that they cannot manage alone.',
    answer:true,
    explanation:'<b>True.</b> Young children lack the knowledge, strength and emotional maturity to safely supervise a younger child in an emergency. Adult supervision is needed.' }),

  makeMCQ({ id:'g3he-saf-040', chapterId:'g3he-safety', difficulty:2, subsection:'accident_prevention',
    question:'You notice a loose wire coming out of a wall socket at school. What should you do?',
    options:['Report it to a teacher immediately — do not touch it or plug anything into that socket',
             'Tape it back in yourself',
             'Ignore it if nothing has happened yet',
             'Ask a classmate to look at it'],
    answer:'Report it to a teacher immediately — do not touch it or plug anything into that socket',
    hint:'Electrical faults need qualified repair — not DIY.',
    explanation:'A loose wire is an electrical hazard that could cause shock or fire. <b>Report it immediately</b> to a teacher. Never touch or attempt to fix electrical problems — only qualified electricians should do this.' }),

  // ── road_water_safety (031–040) ───────────────────────────────────────────

  makeMCQ({ id:'g3he-saf-041', chapterId:'g3he-safety', difficulty:2, subsection:'road_water_safety',
    question:'During the Mauritian cyclone season, why is it especially dangerous to walk near rivers and drains?',
    options:['Rivers and drains swell rapidly with floodwater that can sweep a person away without warning',
             'Rivers are always calm during cyclones',
             'Drains are deeper only in the dry season',
             'Wind makes rivers smell bad — the only risk is the smell'],
    answer:'Rivers and drains swell rapidly with floodwater that can sweep a person away without warning',
    hint:'Cyclones bring very heavy rain.',
    explanation:'Cyclone rainfall is intense. Rivers and drains can <b>rise from ankle to head height in minutes</b>, creating powerful currents that sweep people and vehicles away. Stay well back during heavy rain.' }),

  makeTF({ id:'g3he-saf-042', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'All occupants of a vehicle, including children in the back seat, should wear a seatbelt.',
    answer:true,
    explanation:'<b>True.</b> Rear passengers can be thrown forward violently in a crash, injuring themselves and front-seat passengers. Seatbelts save lives in all seats.' }),

  makeMCQ({ id:'g3he-saf-043', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'What does a FLASHING red traffic light signal mean?',
    options:['Treat as a STOP sign — come to a complete stop, check it is safe, then proceed',
             'Speed up to get through quickly',
             'The same as a green light',
             'Stop forever and wait for help'],
    answer:'Treat as a STOP sign — come to a complete stop, check it is safe, then proceed',
    hint:'A flashing light requires more caution than a steady green.',
    explanation:'A <b>flashing red light</b> means treat the intersection as a stop sign: stop completely, check all directions are clear, then proceed carefully. It signals a malfunction or extra caution needed.' }),

  makeTF({ id:'g3he-saf-044', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'Open water (sea, rivers, lakes) is more dangerous than a swimming pool because there are unpredictable currents, no lane markers and no trained lifeguard.',
    answer:true,
    explanation:'<b>True.</b> Open water has hidden currents, sudden depth changes, weeds, and no lifeguard. Even strong swimmers have drowned in open water. Always swim in supervised, designated areas.' }),

  makeMCQ({ id:'g3he-saf-045', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'Which piece of road safety equipment is legally required for a motorcycle rider in Mauritius?',
    options:['A correctly fitted helmet','A bright jacket only','Gloves only','No specific equipment is required'],
    answer:'A correctly fitted helmet',
    hint:'Head protection is the most critical safety item for two-wheeled vehicles.',
    explanation:'Mauritius law requires motorcycle riders to wear <b>a helmet</b>. In a collision, a helmet is the most effective single item in preventing fatal head injuries.' }),

  makeMCQ({ id:'g3he-saf-046', chapterId:'g3he-safety', difficulty:2, subsection:'road_water_safety',
    question:'A child sees a friend in distress in the sea, waving and unable to swim back. What is the SAFEST response?',
    options:['Shout for help loudly, alert any lifeguard or adult, and if possible throw a floating object — do NOT jump in without training',
             'Swim out immediately to save them',
             'Call their name and wait',
             'Run away'],
    answer:'Shout for help loudly, alert any lifeguard or adult, and if possible throw a floating object — do NOT jump in without training',
    hint:'Untrained rescuers often become additional victims.',
    explanation:'<b>Reach or throw before you go.</b> Throw a lifeline, ring or any floating object. Shout for the lifeguard or an adult. An untrained person jumping in often results in two drowning victims.' }),

  makeTF({ id:'g3he-saf-047', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'Using a mobile phone while cycling is as dangerous as using one while driving a car.',
    answer:true,
    explanation:'<b>True.</b> Distraction from a phone affects reaction time and attention for both cyclists and drivers. In Mauritius, using a hand-held phone while driving is illegal for good reason.' }),

  makeMCQ({ id:'g3he-saf-048', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'What should you do before entering deep water when you are unsure of your swimming ability?',
    options:['Wear a life jacket and have a trained adult nearby',
             'Enter quickly so you learn fast',
             'Close your eyes and jump in',
             'There is nothing special to do'],
    answer:'Wear a life jacket and have a trained adult nearby',
    hint:'Safety equipment and supervision protect those who cannot yet swim well.',
    explanation:'<b>A life jacket and adult supervision</b> are essential for non-swimmers or weak swimmers in deep water. These measures prevent drowning when skill is not enough.' }),

  makeTF({ id:'g3he-saf-049', chapterId:'g3he-safety', difficulty:1, subsection:'road_water_safety',
    question:'During a school fire drill, students should walk calmly to the exit, not run, to avoid falls and crowding.',
    answer:true,
    explanation:'<b>True.</b> Running during an evacuation causes falls and crowd surges that injure people. Walking in an orderly line is faster and safer for the whole group.' }),

  makeMCQ({ id:'g3he-saf-050', chapterId:'g3he-safety', difficulty:2, subsection:'road_water_safety',
    question:'Why are reflective road markers (cats\' eyes) built into roads?',
    options:['They reflect car headlights back to the driver, marking the road\'s lanes and edges when it is dark or raining',
             'They generate their own light',
             'They warn drivers about potholes only',
             'They are only decorative'],
    answer:'They reflect car headlights back to the driver, marking the road\'s lanes and edges when it is dark or raining',
    hint:'Think about what happens to light when it hits a reflective surface.',
    explanation:'Cats\' eyes contain a reflective element that <b>bounces headlight beams back to drivers</b>, marking road lanes clearly in darkness and heavy rain when painted lines are invisible.' }),

  // ── emergency_response (031–040) ──────────────────────────────────────────

  makeMCQ({ id:'g3he-saf-051', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'What is the emergency telephone number in Mauritius?',
    options:['999 (police), 114 (ambulance/SAMU), 115 (fire brigade)',
             '911',
             '112 only',
             'Any number — all are forwarded to emergency services'],
    answer:'999 (police), 114 (ambulance/SAMU), 115 (fire brigade)',
    hint:'These numbers are specific to Mauritius.',
    explanation:'In Mauritius: <b>999 for police, 114 for SAMU (medical emergency), 115 for fire brigade</b>. Memorise these — you may need them in a crisis.' }),

  makeTF({ id:'g3he-saf-052', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'If someone is unconscious but breathing normally, placing them in the recovery position prevents choking.',
    answer:true,
    explanation:'<b>True.</b> The recovery position (on their side, head tilted) keeps the airway open and allows vomit or fluid to drain from the mouth rather than blocking the airway.' }),

  makeMCQ({ id:'g3he-saf-053', chapterId:'g3he-safety', difficulty:2, subsection:'emergency_response',
    question:'CPR (Cardiopulmonary Resuscitation) is used when someone:',
    options:['Has stopped breathing and has no pulse — CPR circulates oxygenated blood until medical help arrives',
             'Has a mild headache',
             'Is asleep',
             'Has a sprained ankle'],
    answer:'Has stopped breathing and has no pulse — CPR circulates oxygenated blood until medical help arrives',
    hint:'CPR keeps blood moving when the heart is not.',
    explanation:'<b>CPR</b> is performed when a person is unresponsive, not breathing and has no heartbeat. Chest compressions and rescue breaths circulate blood until medical help arrives.' }),

  makeTF({ id:'g3he-saf-054', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'In an emergency, giving the exact location is the most important piece of information for emergency services.',
    answer:true,
    explanation:'<b>True.</b> Emergency services cannot help if they do not know where to go. Always give the full address, nearest landmark or GPS location first when calling for help.' }),

  makeMCQ({ id:'g3he-saf-055', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'What should you do if someone is having an epileptic seizure?',
    options:['Clear the area of hard objects, time the seizure and call for help — do NOT restrain them or put anything in their mouth',
             'Hold them down firmly to stop the shaking',
             'Put something in their mouth to stop them biting their tongue',
             'Give them water immediately'],
    answer:'Clear the area of hard objects, time the seizure and call for help — do NOT restrain them or put anything in their mouth',
    hint:'Your job is to protect from injury, not to stop the seizure.',
    explanation:'During a seizure: <b>move hard objects away, time it, call for help, place in recovery position when still</b>. Never restrain — it increases injury risk. Never put anything in the mouth — it blocks the airway.' }),

  makeMCQ({ id:'g3he-saf-056', chapterId:'g3he-safety', difficulty:2, subsection:'emergency_response',
    question:'A DRSABC framework helps remember the steps of emergency response. What does the "D" stand for?',
    options:['Danger — check that the scene is safe for you before approaching',
             'Doctor — call a doctor first',
             'Dial — always call 999 before doing anything',
             'Drink — give water to the casualty'],
    answer:'Danger — check that the scene is safe for you before approaching',
    hint:'You cannot help if you become a casualty yourself.',
    explanation:'<b>D = Danger:</b> check the environment is safe before approaching a casualty. A second victim (the rescuer) doubles the problem. Safety first is ALWAYS first in emergency response.' }),

  makeTF({ id:'g3he-saf-057', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'A first aid kit should contain plasters, clean bandages, antiseptic wipes, scissors and a list of emergency numbers.',
    answer:true,
    explanation:'<b>True.</b> These are the basic first aid kit essentials. Plasters and bandages cover wounds; antiseptic wipes clean them; scissors cut bandages; emergency numbers ensure help is called.' }),

  makeMCQ({ id:'g3he-saf-058', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'If you accidentally swallow a chemical or household poison, what should you do?',
    options:['Call SAMU (114) or poison control immediately with the name of the substance — do NOT make yourself vomit',
             'Drink lots of water to dilute it',
             'Wait to see if you feel sick',
             'Make yourself vomit immediately'],
    answer:'Call SAMU (114) or poison control immediately with the name of the substance — do NOT make yourself vomit',
    hint:'Some poisons cause more damage when vomited back up.',
    explanation:'Call <b>SAMU 114</b> with the substance name. Do NOT induce vomiting — some chemicals (acids, alkalis) cause more damage coming back up than going down. Follow the operator\'s instructions.' }),

  makeTF({ id:'g3he-saf-059', chapterId:'g3he-safety', difficulty:1, subsection:'emergency_response',
    question:'Learning the fire escape plan for your home and practising it makes a real fire evacuation faster and safer.',
    answer:true,
    explanation:'<b>True.</b> In a real fire, smoke reduces visibility and panic sets in quickly. A practised escape route becomes automatic, allowing faster, calmer evacuation even under stress.' }),

  makeMCQ({ id:'g3he-saf-060', chapterId:'g3he-safety', difficulty:2, subsection:'emergency_response',
    question:'You arrive at school and find a classmate lying unconscious outside. Which is the CORRECT first step?',
    options:['Check if the scene is safe, then check if they respond — shout their name, tap their shoulder gently',
             'Roll them over immediately to check for injuries',
             'Give them food',
             'Take a photograph and call a friend'],
    answer:'Check if the scene is safe, then check if they respond — shout their name, tap their shoulder gently',
    hint:'Safety → responsiveness → airway → breathing — in that order.',
    explanation:'Following DRSABC: first ensure <b>no danger to yourself</b>, then check for <b>response</b> by calling their name and tapping their shoulder. If no response, call for help immediately and check breathing.' })

);

})();
