'use strict';
// Grade 5 History & Geography - Unit 3: Dutch, French and British settlement
// Written from the Grade 5 revision notes (notes/Historyetgeography.pdf) to fill
// the gaps a coverage check found: what the Dutch actually grew and ate, the six
// reasons their settlement failed, Leguat's two years in Rodrigues, de Nyon and
// the 1722 settlement, what Labourdonnais introduced, how people and goods
// travelled, Decaen, the corsairs, the four stages of the British conquest, and
// the dependencies of the new British colony.
// IDs: g5hg-u3-NNN

STATIC_QUESTIONS.push(

  // ── The Dutch settlement ───────────────────────────────────────────────────
  makeMCQ({ id:'g5hg-u3-001', chapterId:'settlement', subsection:'dutch', difficulty:3,
    question:'Besides using it as a stop-over, why did the Dutch settle Mauritius in 1638?',
    options:['They feared the British or French might occupy it first',
             'They had been driven out of the East Indies by storms',
             'They had found gold and silver on the island',
             'They wanted somewhere cooler than Holland to live'],
    answer:'They feared the British or French might occupy it first',
    hint:'Other European powers were sailing the same ocean.',
    explanation:'Mauritius was a useful stop-over for food, fresh water and rest on voyages to and from the East Indies. The Dutch also <b>feared that the British or French might occupy it</b>, so in <b>1638</b> they settled rather than only calling in.' }),

  makeMCQ({ id:'g5hg-u3-002', chapterId:'settlement', subsection:'dutch', difficulty:2,
    question:'What made Vieux Grand Port a good place for the first Dutch settlement?',
    options:['A sheltered bay, rivers and springs, flat land and forests',
             'A wide sandy desert where nothing could grow',
             'High steep cliffs that no ship could climb',
             'A cold climate like the one they had left behind'],
    answer:'A sheltered bay, rivers and springs, flat land and forests',
    hint:'A settlement needs safe water for ships and fresh water to drink.',
    explanation:'<b>Vieux Grand Port</b> offered a sheltered bay and coves, rivers and springs, flat land, forests, animals and seafood. The Dutch built <b>Fort Frederik Hendrik</b>, placed cannons near it, made roads, built wooden huts and cultivated the land.' }),

  makeMCQ({ id:'g5hg-u3-003', chapterId:'settlement', subsection:'dutch', difficulty:2,
    question:'Which crops did the Dutch grow at their settlement?',
    options:['Maize, sweet potatoes, peas, beans and tobacco','Rice, tea, cocoa, vanilla and pepper',
             'Wheat, barley, apples, olives and dates','Coffee, cotton, indigo, cloves and nutmeg'],
    answer:'Maize, sweet potatoes, peas, beans and tobacco',
    hint:'Coffee, cotton and indigo came later, under the French.',
    explanation:'The Dutch grew <b>maize, sweet potatoes, peas, beans, vegetables, tobacco, grapes, oranges, bananas and lemons</b>. They also introduced <b>sugar cane and deer from Java</b> and reared cattle, goats and pigs.' }),

  makeMCQ({ id:'g5hg-u3-004', chapterId:'settlement', subsection:'dutch', difficulty:2,
    question:'From which island did the Dutch bring sugar cane and deer to Mauritius?',
    options:['Java','Madagascar','Rodrigues','R&eacute;union'],
    answer:'Java',
    hint:'It is an island of the East Indies, where their ships were going.',
    explanation:'Sugar cane and deer were brought from <b>Java</b>, in the East Indies. Both took hold: deer still live wild in Mauritius, and sugar cane became the island’s main crop under the French and the British.' }),

  makeMCQ({ id:'g5hg-u3-005', chapterId:'settlement', subsection:'dutch', difficulty:3,
    question:'What was the Dutch settlers’ main economic activity in Mauritius?',
    options:['Cutting ebony trees for export to Holland','Growing sugar cane for export to Europe',
             'Catching whales in the Indian Ocean','Mining stone from the mountain ranges'],
    answer:'Cutting ebony trees for export to Holland',
    hint:'It was a valuable dark wood the forests were full of.',
    explanation:'The main economic activity was <b>cutting ebony trees for export to Holland</b>. Enslaved people were brought to the island to cut the trees and load the logs.' }),

  makeMCQ({ id:'g5hg-u3-006', chapterId:'settlement', subsection:'dutch', difficulty:3,
    question:'Which of these helped cause the Dutch settlement to fail?',
    options:['The price of ebony fell','The island had no fresh water',
             'The British attacked the fort','A volcano erupted near the bay'],
    answer:'The price of ebony fell',
    hint:'Their whole trade rested on one product.',
    explanation:'The settlement failed for several reasons together: <b>cyclones</b> destroyed houses and crops, <b>rats</b> damaged crops, <b>maroon slaves</b> attacked settlers, some settlers were not hard-working, the <b>price of ebony fell</b>, there were few people, and animals were overhunted. The Dutch abandoned Mauritius in <b>1710</b>.' }),

  makeMCQ({ id:'g5hg-u3-007', chapterId:'settlement', subsection:'dutch', difficulty:2,
    question:'Which animal brought by the ships damaged the settlers’ crops?',
    options:['Rats','Deer','Goats','Monkeys'],
    answer:'Rats',
    hint:'They came ashore from the ships without being invited.',
    explanation:'<b>Rats</b> came ashore from the ships and damaged the crops, as well as eating the eggs of ground-nesting birds. They were one of several reasons the Dutch settlement could not last.' }),

  makeMCQ({ id:'g5hg-u3-008', chapterId:'settlement', subsection:'dutch', difficulty:3,
    question:'Where in Rodrigues did Fran&ccedil;ois Leguat and his friends settle in 1691?',
    options:['At the mouth of Grande Rivi&egrave;re, near Port Mathurin','On the summit of Mont Limon',
             'On the limestone plain of Plaine Corail','At Baie aux Hu&icirc;tres in the south-east'],
    answer:'At the mouth of Grande Rivi&egrave;re, near Port Mathurin',
    hint:'They needed fresh water, so they settled where a river met the sea.',
    explanation:'In <b>1691</b> Leguat and his friends settled at the mouth of <b>Grande Rivi&egrave;re near Port Mathurin</b>. They built latanier-palm huts, gardened, fished and hunted, and kept a <b>diary</b> about the plants and animals, including the Solitaire.' }),

  makeMCQ({ id:'g5hg-u3-009', chapterId:'settlement', subsection:'dutch', difficulty:3,
    question:'Why did Leguat’s small group leave Rodrigues in 1693?',
    options:['No ships brought goods and no more settlers came','A cyclone destroyed all of their huts',
             'The British captured the island from them','They had used up all the fresh water'],
    answer:'No ships brought goods and no more settlers came',
    hint:'A settlement of a handful of people cannot survive alone.',
    explanation:'They left in <b>1693</b> because <b>no ships brought goods and no more settlers came</b>. A settlement needs regular supplies and new people, and Rodrigues was receiving neither.' }),

  // ── The French in Ile de France ────────────────────────────────────────────
  makeMCQ({ id:'g5hg-u3-010', chapterId:'settlement', subsection:'french', difficulty:3,
    question:'Who used Mauritius in the years after the Dutch left in 1710?',
    options:['Sailors and pirates based in Madagascar','Arab traders sailing to the Red Sea',
             'British soldiers stationed in Rodrigues','Portuguese settlers from Goa and Malacca'],
    answer:'Sailors and pirates based in Madagascar',
    hint:'An empty island with sheltered bays suited people who wished to hide.',
    explanation:'After 1710 the island was used by sailors and by <b>pirates based in Madagascar</b>, who hid in its bays and attacked ships carrying valuable goods.' }),

  makeMCQ({ id:'g5hg-u3-011', chapterId:'settlement', subsection:'french', difficulty:3,
    question:'Why did France take possession of Mauritius in 1715?',
    options:['To protect its trade and give ships a safe stop-over',
             'To grow enough wheat to feed the people of France',
             'To find the gold that the Dutch had left behind',
             'To move the French navy away from the Atlantic'],
    answer:'To protect its trade and give ships a safe stop-over',
    hint:'Think about the pirates and about the long voyage to India.',
    explanation:'France took the island to <b>protect Indian Ocean trade</b>, to <b>defend ships from pirates and enemies</b> and to use a <b>safer stop-over</b>. It was renamed <b>&Icirc;le de France</b>.' }),

  makeMCQ({ id:'g5hg-u3-012', chapterId:'settlement', subsection:'french', difficulty:2,
    question:'Which French governor arrived in 1722 with settlers and began a settlement at Grand Port?',
    options:['Denis de Nyon','Mah&eacute; de Labourdonnais','Pierre Poivre','Charles Decaen'],
    answer:'Denis de Nyon',
    hint:'He came before Labourdonnais, who arrived in 1735.',
    explanation:'<b>Governor Denis de Nyon</b> arrived in <b>1722</b> with settlers and enslaved people and began a settlement at <b>Grand Port</b>. Land near the rivers was cleared for houses and food crops.' }),

  makeMCQ({ id:'g5hg-u3-013', chapterId:'settlement', subsection:'french', difficulty:3,
    question:'During the French period, the growing population came from France, Africa, Madagascar and...',
    options:['Mozambique and India','Portugal and Spain','China and Japan','Australia and Java'],
    answer:'Mozambique and India',
    hint:'Look at the countries around the Indian Ocean.',
    explanation:'Officers, farmers, skilled workers and enslaved people came from <b>France, Africa, Madagascar, Mozambique and India</b>. Their descendants are part of the Mauritian population today.' }),

  makeMCQ({ id:'g5hg-u3-014', chapterId:'settlement', subsection:'french', difficulty:3,
    question:'During the French period, where did cattle and rice come from?',
    options:['Madagascar','Rodrigues','R&eacute;union','The East Indies'],
    answer:'Madagascar',
    hint:'It is the nearest large land, and it had herds.',
    explanation:'Fish and turtles came from <b>Rodrigues</b>, cereals from <b>R&eacute;union</b>, and cattle and rice from <b>Madagascar</b>. A small island could not feed itself alone.' }),

  makeMCQ({ id:'g5hg-u3-015', chapterId:'trade-agri', subsection:'crops', difficulty:3,
    question:'Which food crop did Mah&eacute; de Labourdonnais introduce to the island?',
    options:['Manioc','Sugar cane','Tea','Nutmeg'],
    answer:'Manioc',
    hint:'It is a root crop, still eaten in Mauritius today.',
    explanation:'Labourdonnais introduced <b>manioc</b>, encouraged <b>coffee, indigo and cotton</b>, and developed sugar cane. Sugar cane itself had been brought earlier, by the Dutch, from Java.' }),

  makeMCQ({ id:'g5hg-u3-016', chapterId:'trade-agri', subsection:'crops', difficulty:3,
    question:'Where did Labourdonnais build his sugar mills?',
    options:['Villebague and Ferney','Pamplemousses and Moka',
             'Mahebourg and Souillac','Curepipe and Vacoas'],
    answer:'Villebague and Ferney',
    hint:'One of the two is the place where the Dutch had landed in 1598.',
    explanation:'Labourdonnais built sugar mills at <b>Villebague and Ferney</b>. His residence, <b>Mon Plaisir</b>, had a vegetable garden and stands in what is now the Pamplemousses garden.' }),

  makeMCQ({ id:'g5hg-u3-017', chapterId:'trade-agri', subsection:'personalities', difficulty:3,
    question:'What did Pierre Poivre distribute to the settlers from Pamplemousses?',
    options:['Seeds and seedlings of fruits and spices','Ox carts and farming tools',
             'Money borrowed from the French king','Maps of the Indian Ocean routes'],
    answer:'Seeds and seedlings of fruits and spices',
    hint:'A botanical garden is a place where plants are raised.',
    explanation:'<b>Pierre Poivre</b> created the <b>Botanical Garden of Pamplemousses</b> and introduced fruits, medicinal plants and valuable spices such as cloves and nutmeg. <b>Seeds and seedlings were distributed to settlers</b>, so the whole colony could grow them.' }),

  makeMCQ({ id:'g5hg-u3-018', chapterId:'settlement', subsection:'french', difficulty:2,
    question:'How did people travel in &Icirc;le de France during the French period?',
    options:['On foot, on horses, in ox carts and in palanquins',
             'By railway trains running between the towns',
             'By bicycles imported from France',
             'By motor cars owned by the governors'],
    answer:'On foot, on horses, in ox carts and in palanquins',
    hint:'There were no engines of any kind yet.',
    explanation:'People <b>walked or used horses, ox carts and palanquins</b>. Goods were moved by mules, ox carts and coastal boats.' }),

  makeMCQ({ id:'g5hg-u3-019', chapterId:'settlement', subsection:'french', difficulty:3,
    question:'Governor Souillac built a small port at the mouth of which river?',
    options:['River Savanne','Grand River North West','Grande Rivi&egrave;re Sud-Est','River Mourouk'],
    answer:'River Savanne',
    hint:'The town that grew there now carries the governor’s own name.',
    explanation:'<b>Governor Souillac</b> built a small port at the mouth of the <b>River Savanne</b>, in the south. Coastal boats mattered when roads were few and goods were heavy.' }),

  makeMCQ({ id:'g5hg-u3-020', chapterId:'settlement', subsection:'french', difficulty:2,
    question:'Who was the <b>last</b> French governor of &Icirc;le de France?',
    options:['Charles Decaen','Mah&eacute; de Labourdonnais','Denis de Nyon','Pierre Poivre'],
    answer:'Charles Decaen',
    hint:'He is the one who had to surrender to the British.',
    explanation:'<b>Charles Decaen</b> was the last French governor. He made new laws, founded the <b>Lyc&eacute;e Colonial</b> (later the Royal College, Port Louis) and developed <b>Mahebourg</b> with roads, drains and soldiers’ barracks.' }),

  makeMCQ({ id:'g5hg-u3-021', chapterId:'settlement', subsection:'french', difficulty:3,
    question:'Which Port Louis school founded by Charles Decaen still exists under another name?',
    options:['The Lyc&eacute;e Colonial, now the Royal College','The Ecole Centrale, now the Central Market',
             'The Coll&egrave;ge de Moka, now the University','The Petit Lyc&eacute;e, now Government House'],
    answer:'The Lyc&eacute;e Colonial, now the Royal College',
    hint:'It is a college, and its newer name sounds British.',
    explanation:'Decaen founded the <b>Lyc&eacute;e Colonial</b>, which later became the <b>Royal College, Port Louis</b>. A French school kept going under British rule is one sign of how much of French life survived 1810.' }),

  // ── The conquest of Ile de France ──────────────────────────────────────────
  makeMCQ({ id:'g5hg-u3-022', chapterId:'settlement', subsection:'british', difficulty:2,
    question:'What were <b>corsairs</b>?',
    options:['French sailors officially permitted to attack enemy ships in war',
             'British soldiers who guarded the harbour of Port Louis',
             'Traders who carried spices between India and France',
             'Fishermen who supplied the island with fresh fish'],
    answer:'French sailors officially permitted to attack enemy ships in war',
    hint:'They were not ordinary pirates — they had permission.',
    explanation:'<b>Corsairs</b> were French sailors <b>officially permitted to attack enemy ships during war</b>. <b>Robert Surcouf</b>, the "King of Corsairs", sailed from Port Louis in small, swift boats and captured British ships and goods.' }),

  makeMCQ({ id:'g5hg-u3-023', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'What was the main British aim in attacking &Icirc;le de France?',
    options:['To stop corsair attacks and trade safely in the Indian Ocean',
             'To find new farmland for settlers from Britain',
             'To take the sugar mills built by Labourdonnais',
             'To stop the French from cutting down the ebony trees'],
    answer:'To stop corsair attacks and trade safely in the Indian Ocean',
    hint:'British ships were being captured on the route to India.',
    explanation:'The British aim was to <b>stop corsair attacks and trade safely</b> in the Indian Ocean. As long as Port Louis was French, every British merchant ship on the route to India was at risk.' }),

  makeMCQ({ id:'g5hg-u3-024', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Why did the British capture Rodrigues in August 1809?',
    options:['To use it as a base for attacking &Icirc;le de France',
             'To grow sugar cane on its limestone plain',
             'To protect its giant tortoises from sailors',
             'To build a new capital city for their empire'],
    answer:'To use it as a base for attacking &Icirc;le de France',
    hint:'Take the small island first, then use it to prepare.',
    explanation:'The British captured the poorly defended island in <b>August 1809</b>, built <b>Fort Duncan</b> and used <b>Rodrigues as a military base</b>. They captured R&eacute;union in July 1810, leaving &Icirc;le de France as the only French island.' }),

  makeMCQ({ id:'g5hg-u3-025', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Which island did the British capture in July 1810, just before the Battle of Grand Port?',
    options:['R&eacute;union','Rodrigues','Madagascar','Agal&eacute;ga'],
    answer:'R&eacute;union',
    hint:'It is the third Mascarene island, and it is still French today.',
    explanation:'The British captured <b>R&eacute;union in July 1810</b>. That left &Icirc;le de France as the remaining French island in the region — and the next target.' }),

  makeMCQ({ id:'g5hg-u3-026', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'At the Battle of Grand Port in August 1810, why did the British warships lose?',
    options:['They became trapped in shallow sandy areas inside the bay',
             'They ran out of gunpowder before the battle began',
             'A cyclone sank them before they reached the island',
             'Their crews were outnumbered ten to one by the French'],
    answer:'They became trapped in shallow sandy areas inside the bay',
    hint:'The bay looks open but is full of shallows and reef.',
    explanation:'The British captured <b>&Icirc;le de la Passe</b> and entered the bay, but their warships <b>became trapped in shallow sandy areas</b> and the French won. Captains <b>Duperr&eacute;</b> and <b>Willoughby</b> were treated at Robillard’s residence, now the <b>National History Museum in Mahebourg</b>.' }),

  makeMCQ({ id:'g5hg-u3-027', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'The National History Museum in Mahebourg was once whose residence?',
    options:['Robillard’s','Labourdonnais’s','Decaen’s','Marragon’s'],
    answer:'Robillard’s',
    hint:'The wounded captains of both sides were cared for there after the battle.',
    explanation:'The wounded captains <b>Duperr&eacute;</b> (French) and <b>Willoughby</b> (British) were treated at <b>Robillard’s residence</b> after the Battle of Grand Port. The house is now the <b>National History Museum</b> in Mahebourg.' }),

  makeMCQ({ id:'g5hg-u3-028', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Where did the British land in November 1810 for their final attack?',
    options:['Cap Malheureux','Grand Port','Port Louis','Mahebourg'],
    answer:'Cap Malheureux',
    hint:'It is at the very northern tip of Mauritius.',
    explanation:'In <b>November 1810</b> the British prepared again in Rodrigues and landed at <b>Cap Malheureux</b> with more warships, weapons, British soldiers and Indian soldiers, then marched towards Port Louis.' }),

  makeMCQ({ id:'g5hg-u3-029', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Why did Governor Decaen surrender in December 1810?',
    options:['He had far fewer men and weapons than the British force',
             'He had been ordered to do so by the King of France',
             'His soldiers had all been captured at Grand Port',
             'A cyclone had destroyed the defences of Port Louis'],
    answer:'He had far fewer men and weapons than the British force',
    hint:'Winning one sea battle does not replace lost soldiers and guns.',
    explanation:'The British landed with <b>more warships, weapons and soldiers</b>. Decaen, with <b>fewer men and weapons</b>, surrendered in <b>December 1810</b>. French rule ended and Britain renamed &Icirc;le de France <b>Mauritius</b>.' }),

  makeMCQ({ id:'g5hg-u3-030', chapterId:'settlement', subsection:'british', difficulty:2,
    question:'Who was Philibert Marragon, and where did he live?',
    options:['The French officer in charge of Rodrigues, at l’Orangerie farm',
             'The last French governor of &Icirc;le de France, at Mahebourg',
             'The first British governor of Mauritius, at Government House',
             'A corsair captain of Port Louis, at Fort Adelaide'],
    answer:'The French officer in charge of Rodrigues, at l’Orangerie farm',
    hint:'Think of the smaller island, not of Mauritius.',
    explanation:'In the 18th century the three Mascarenes belonged to France. Rodrigues had mainly fishermen, a few farmers and enslaved people, and <b>Philibert Marragon</b>, the French officer in charge, had a farm called <b>l’Orangerie near Baie aux Hu&icirc;tres</b>.' }),

  // ── Mauritius as a British colony ──────────────────────────────────────────
  makeMCQ({ id:'g5hg-u3-031', chapterId:'settlement', subsection:'british', difficulty:2,
    question:'What is an <b>empire</b>?',
    options:['A group of countries ruled by one powerful country','A country governed by its own elected people',
             'A group of islands sharing the same ocean','A country that trades only with its neighbours'],
    answer:'A group of countries ruled by one powerful country',
    hint:'A colony is one piece of it.',
    explanation:'An <b>empire</b> is a group of countries ruled by one powerful country. A <b>colony</b> is a country governed by another country. Mauritius became a colony within the British Empire.' }),

  makeMCQ({ id:'g5hg-u3-032', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Which of these was a <b>dependency</b> of Mauritius under British rule?',
    options:['The Chagos Archipelago','Madagascar','R&eacute;union','The Comoros'],
    answer:'The Chagos Archipelago',
    hint:'Three of these were never governed from Port Louis.',
    explanation:'The dependencies were <b>Rodrigues, St Brandon, Agal&eacute;ga, Tromelin, the Chagos Archipelago and the Seychelles</b>. They were all governed by the Governor of Mauritius.' }),

  makeMCQ({ id:'g5hg-u3-033', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Why did Sir Robert Farquhar encourage the planting of sugar cane?',
    options:['It resisted cyclones better than many other crops',
             'It needed no workers once it had been planted',
             'It could be grown only on the central plateau',
             'It was the one crop the French had never grown'],
    answer:'It resisted cyclones better than many other crops',
    hint:'Think of what a cyclone does to a field of fruit trees.',
    explanation:'<b>Farquhar</b>, the first British governor, encouraged sugar cane because it <b>resisted cyclones better</b> than many other crops. A crop that survives the storm season is worth more to a farmer than a richer crop that does not.' }),

  makeMCQ({ id:'g5hg-u3-034', chapterId:'settlement', subsection:'british', difficulty:2,
    question:'Which main roads did Farquhar have built?',
    options:['From Port Louis to Mahebourg and to Souillac',
             'From Curepipe to Grand Bassin and to Chamarel',
             'From Pamplemousses to Cap Malheureux and to Flacq',
             'From Port Mathurin to Plaine Corail and to Mont Limon'],
    answer:'From Port Louis to Mahebourg and to Souillac',
    hint:'Roads ran from the capital and port to the other harbours.',
    explanation:'Farquhar improved the paths and built roads, including the main routes from <b>Port Louis to Mahebourg and Souillac</b>, making travel and the transport of goods easier.' }),

  makeMCQ({ id:'g5hg-u3-035', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'What were coconuts from Agal&eacute;ga and Chagos sent to Mauritius for?',
    options:['To make oil and soap','To be planted on the plains',
             'To feed the deer in the forests','To be sold to passing ships'],
    answer:'To make oil and soap',
    hint:'Think about what is pressed out of the dried flesh.',
    explanation:'People on Agal&eacute;ga and Chagos fished and worked on coconut plantations. <b>Coconuts were sent to Mauritius for oil and soap</b>, and some islands also exported <b>guano</b> for fertiliser.' }),

  makeMCQ({ id:'g5hg-u3-036', chapterId:'settlement', subsection:'british', difficulty:4,
    question:'The Dutch settlement stayed small and failed, while the French developed the island. Which difference best explains it?',
    options:['The French brought many more people and invested in the colony',
             'The French arrived at a time when there were no cyclones',
             'The French found ebony forests that the Dutch had missed',
             'The French had no enemies in the Indian Ocean to fear'],
    answer:'The French brought many more people and invested in the colony',
    hint:'Compare the number of settlers and what each group actually built.',
    explanation:'The Dutch settlement <b>remained small and failed</b>. The French brought <b>more people and developed agriculture, transport, government and trade</b>. The British then kept much of the existing way of life but expanded sugar cultivation and roads.' }),

  makeMCQ({ id:'g5hg-u3-037', chapterId:'settlement', subsection:'british', difficulty:4,
    question:'The British won the island in 1810 yet changed very little at first. Why?',
    options:['French settlers kept their land, language, religion and customs',
             'There were not enough British soldiers left to govern the island',
             'The British planned to return the island to France within a year',
             'A cyclone in 1811 destroyed all the records of the new government'],
    answer:'French settlers kept their land, language, religion and customs',
    hint:'A ruler who leaves daily life alone meets far less resistance.',
    explanation:'Under <b>Sir Robert Farquhar</b>, French inhabitants kept their land, buildings, religion, language, customs and enslaved people, <b>so few immediate changes occurred</b>. That is why French is still widely spoken in Mauritius today.' }),

  makeMCQ({ id:'g5hg-u3-038', chapterId:'settlement', subsection:'french', difficulty:4,
    question:'Look at the timeline: 1638, 1710, 1715, 1722, 1735. Which pair shows the years with <b>no settlers at all</b> on the island?',
    options:['1710 to 1715','1638 to 1710','1715 to 1722','1722 to 1735'],
    answer:'1710 to 1715',
    hint:'One date is when the Dutch left; the next is when France took over.',
    explanation:'The Dutch abandoned Mauritius in <b>1710</b> and France took possession in <b>1715</b>. In those five years only sailors and pirates used the island. The other dates mark the Dutch settlement (1638), de Nyon’s settlers (1722) and Labourdonnais becoming governor (1735).' }),

  // ── Consolidation pass: the remaining facts of Unit 3 ──────────────────────

  makeMCQ({ id:'g5hg-u3-039', chapterId:'settlement', subsection:'dutch', difficulty:2,
    question:'What does a <b>settlement</b> usually have?',
    options:['Houses, shops, schools and health services','Only a fort and a few soldiers',
             'Only fields with no buildings at all','A harbour but no people living there'],
    answer:'Houses, shops, schools and health services',
    hint:'It is a place where people live, not merely visit.',
    explanation:'A <b>settlement</b> is a place where people live. It may be a village, a town or a city, and it usually has <b>houses, shops or markets, schools and health services</b>.' }),

  makeMCQ({ id:'g5hg-u3-040', chapterId:'settlement', subsection:'dutch', difficulty:2,
    question:'Besides fishing, which birds and animals did the Dutch hunt for food?',
    options:['Bats, tortoises, pigeons, parrots and wild ducks','Deer, cattle, goats, pigs and poultry',
             'Monkeys, rats, dogs, cats and mice','Whales, seals, sharks, eels and crabs'],
    answer:'Bats, tortoises, pigeons, parrots and wild ducks',
    hint:'These were wild animals already living on the island.',
    explanation:'The Dutch <b>fished and hunted bats, tortoises and birds</b> such as the dodo, pigeons, parrots and wild ducks. Cattle, goats and pigs were reared, not hunted.' }),

  makeMCQ({ id:'g5hg-u3-041', chapterId:'settlement', subsection:'dutch', difficulty:3,
    question:'Why did the Dutch bring enslaved people to Mauritius?',
    options:['To cut the ebony trees and load the logs','To build the roads across the island',
             'To grow sugar cane on the coastal plains','To fish in the lagoons for the settlers'],
    answer:'To cut the ebony trees and load the logs',
    hint:'It follows from what their main trade was.',
    explanation:'The main economic activity was cutting ebony for export to Holland, and <b>enslaved people were brought to cut the trees and load the logs</b>.' }),

  makeMCQ({ id:'g5hg-u3-042', chapterId:'settlement', subsection:'dutch', difficulty:3,
    question:'Who attacked the Dutch settlers, helping to make their settlement fail?',
    options:['Maroon slaves','British soldiers','Portuguese sailors','Arab traders'],
    answer:'Maroon slaves',
    hint:'They were enslaved people who had escaped into the forests.',
    explanation:'<b>Maroon slaves</b> — enslaved people who had escaped — attacked the settlers. That was one of several causes of failure, along with cyclones, rats, the falling price of ebony, too few people and overhunting.' }),

  makeMCQ({ id:'g5hg-u3-043', chapterId:'settlement', subsection:'dutch', difficulty:2,
    question:'What did the Dutch place near Fort Frederik Hendrik?',
    options:['Cannons','Sugar mills','A botanical garden','A racecourse'],
    answer:'Cannons',
    hint:'A fort needs something to defend itself with.',
    explanation:'The Dutch built <b>Fort Frederik Hendrik</b>, <b>placed cannons near it</b>, made roads, built wooden huts and cultivated the land.' }),

  makeMCQ({ id:'g5hg-u3-044', chapterId:'settlement', subsection:'french', difficulty:2,
    question:'Besides growing food and rearing animals, what else did French farmers keep?',
    options:['Poultry','Deer','Monkeys','Tortoises'],
    answer:'Poultry',
    hint:'Think of chickens and ducks kept near the house.',
    explanation:'Farmers grew food, reared animals and kept <b>poultry</b>. Even so, the colony still had to import much of its food from its neighbours.' }),

  makeMCQ({ id:'g5hg-u3-045', chapterId:'settlement', subsection:'french', difficulty:2,
    question:'What came to &Icirc;le de France from <b>Rodrigues</b>?',
    options:['Fish and turtles','Cattle and rice','Cereals and grain','Silk and porcelain'],
    answer:'Fish and turtles',
    hint:'Rodrigues is small, with rich lagoons and once with many tortoises.',
    explanation:'<b>Fish and turtles came from Rodrigues</b>, cereals from R&eacute;union, and cattle and rice from Madagascar.' }),

  makeMCQ({ id:'g5hg-u3-046', chapterId:'trade-agri', subsection:'crops', difficulty:3,
    question:'Besides coffee, which two crops did Labourdonnais encourage?',
    options:['Indigo and cotton','Tea and vanilla','Rice and maize','Cloves and nutmeg'],
    answer:'Indigo and cotton',
    hint:'One of them was grown to make a blue dye.',
    explanation:'Labourdonnais introduced manioc and encouraged <b>coffee, indigo and cotton</b>. Cloves and nutmeg belong to Pierre Poivre and the Pamplemousses garden.' }),

  makeMCQ({ id:'g5hg-u3-047', chapterId:'trade-agri', subsection:'personalities', difficulty:3,
    question:'What was <b>Mon Plaisir</b>?',
    options:['The residence of Labourdonnais, with a vegetable garden','The fort the Dutch built at Vieux Grand Port',
             'The first sugar mill built on the island','The house where the wounded captains were treated'],
    answer:'The residence of Labourdonnais, with a vegetable garden',
    hint:'It stands in what is now the Pamplemousses garden.',
    explanation:'<b>Mon Plaisir</b> was Labourdonnais’s residence, and it had a <b>vegetable garden</b>. It stands in the grounds of what became the Botanical Garden of Pamplemousses.' }),

  makeMCQ({ id:'g5hg-u3-048', chapterId:'settlement', subsection:'french', difficulty:3,
    question:'What did Charles Decaen build at Mahebourg?',
    options:['Roads, drains and soldiers’ barracks','A racecourse, a theatre and a market',
             'A shipyard, an aqueduct and quays','A botanical garden and a hospital'],
    answer:'Roads, drains and soldiers’ barracks',
    hint:'He was preparing a town, and a garrison to defend it.',
    explanation:'<b>Charles Decaen</b>, the last French governor, made new laws, founded the Lyc&eacute;e Colonial and <b>developed Mahebourg with roads, drains and soldiers’ barracks</b>.' }),

  makeMCQ({ id:'g5hg-u3-049', chapterId:'settlement', subsection:'british', difficulty:2,
    question:'Robert Surcouf was known by which nickname?',
    options:['The King of Corsairs','The Governor of the Seas',
             'The Admiral of Grand Port','The Prince of Port Louis'],
    answer:'The King of Corsairs',
    hint:'It names what he did, not an office he held.',
    explanation:'<b>Robert Surcouf</b>, the "<b>King of Corsairs</b>", sailed from Port Louis in small, swift boats and captured British ships and goods.' }),

  makeMCQ({ id:'g5hg-u3-050', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Which soldiers landed with the British at Cap Malheureux in November 1810?',
    options:['British and Indian soldiers','British and Dutch soldiers',
             'Indian and Malagasy soldiers','British and French soldiers'],
    answer:'British and Indian soldiers',
    hint:'Britain also ruled a great deal of India at the time.',
    explanation:'The British landed with more warships and weapons, and with <b>British soldiers and Indian soldiers</b>. They then marched towards Port Louis, and Decaen surrendered in December 1810.' }),

  makeMCQ({ id:'g5hg-u3-051', chapterId:'settlement', subsection:'british', difficulty:2,
    question:'What is a <b>colony</b>?',
    options:['A country governed by another country','A group of countries ruled by one country',
             'A country that has just become independent','A country made up of several islands'],
    answer:'A country governed by another country',
    hint:'An empire is made up of several of them.',
    explanation:'A <b>colony</b> is a country governed by another country; an <b>empire</b> is a group of countries ruled by one powerful country. Mauritius became a colony of the British Empire.' }),

  makeMCQ({ id:'g5hg-u3-052', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Which of the dependencies’ exports was used as a fertiliser?',
    options:['Guano','Coconut oil','Ebony','Soap'],
    answer:'Guano',
    hint:'It is a natural fertiliser left by seabirds.',
    explanation:'People on Agal&eacute;ga and Chagos fished and worked on coconut plantations; coconuts went to Mauritius for oil and soap, and some islands also exported <b>guano for fertiliser</b>.' }),

  // ⚠ Found by scripts/test-syllabus-facts.js: &Icirc;le de la Passe was named in
  // an explanation and asked nowhere.

  makeMCQ({ id:'g5hg-u3-053', chapterId:'settlement', subsection:'british', difficulty:3,
    question:'Which island did the British capture before entering the bay at Grand Port in 1810?',
    options:['&Icirc;le de la Passe','&Icirc;le aux Aigrettes','&Icirc;le aux Cerfs','&Icirc;le Cocos'],
    answer:'&Icirc;le de la Passe',
    hint:'Its name says what it guards — the pass into the bay.',
    explanation:'The British captured <b>&Icirc;le de la Passe</b>, which guards the entrance, and entered the bay. Their warships then became trapped in shallow sandy areas and the French won the battle.' })

);
