'use strict';
// Grade 5 History & Geography - Unit 1: Our Natural Environment
// Written from the Grade 5 revision notes (notes/Historyetgeography.pdf), against
// a coverage check of the existing pack. Only the facts the pack did NOT already
// ask are here: the tropics of Cancer, the named continents and oceans, the
// Indian Ocean's own seas, the world natural sites, natural vs man-made features,
// the relief vocabulary (mountain/hill/plateau/plain), the named mountain ranges
// and plains, the Rodrigues relief, the eruption sequence, and the named reserves.
// IDs: g5hg-u1-NNN

STATIC_QUESTIONS.push(

  // ── Planet Earth: continents, oceans and the great lines ────────────────────
  makeMCQ({ id:'g5hg-u1-001', chapterId:'map-skills', subsection:'coordinates', difficulty:2,
    question:'Which line of latitude lies 23.5 degrees <b>North</b> of the Equator?',
    options:['The Tropic of Cancer','The Tropic of Capricorn','The Antarctic Circle','The Greenwich Meridian'],
    answer:'The Tropic of Cancer',
    hint:'Mauritius sits near the southern one. This is its twin in the north.',
    explanation:'The <b>Tropic of Cancer</b> lies 23.5&deg; North and passes through North America, Africa and Asia. The <b>Tropic of Capricorn</b> is its partner at 23.5&deg; South, and that is the one close to Mauritius.' }),

  makeMCQ({ id:'g5hg-u1-002', chapterId:'map-skills', subsection:'coordinates', difficulty:2,
    question:'Lines of longitude are numbered from 0 degrees up to which figure, East and West?',
    options:['180 degrees','90 degrees','120 degrees','360 degrees'],
    answer:'180 degrees',
    hint:'Half of a full turn around the Earth.',
    explanation:'Longitude is measured from the Greenwich Meridian (0&deg;) eastwards and westwards as far as <b>180&deg;</b>. The two halves together make one full turn of 360&deg; around the Earth.' }),

  makeMCQ({ id:'g5hg-u1-003', chapterId:'map-skills', subsection:'coordinates', difficulty:2,
    question:'The Tropic of Capricorn passes through which large island close to Mauritius?',
    options:['Madagascar','Sri Lanka','Rodrigues','Zanzibar'],
    answer:'Madagascar',
    hint:'It is the big island between Mauritius and Africa.',
    explanation:'The <b>Tropic of Capricorn</b> crosses <b>Madagascar</b> and passes close to Mauritius. That is why Mauritius has a tropical climate.' }),

  makeMCQ({ id:'g5hg-u1-004', chapterId:'g5enr-world', subsection:'world', difficulty:1,
    question:'How many continents are there on Earth?',
    options:['Seven','Five','Six','Nine'],
    answer:'Seven',
    hint:'Count them: Asia, Africa, North America, South America, Europe, Australia and one more.',
    explanation:'There are <b>seven continents</b>: Asia, Africa, North America, South America, Europe, Australia and Antarctica. Asia is the largest of them.' }),

  makeMCQ({ id:'g5hg-u1-005', chapterId:'g5enr-world', subsection:'world', difficulty:2,
    question:'Which continent lies at the far south of the Earth and is covered in ice?',
    options:['Antarctica','Australia','South America','Europe'],
    answer:'Antarctica',
    hint:'Its name begins with the same word as the Antarctic Circle.',
    explanation:'<b>Antarctica</b> surrounds the South Pole. It is the coldest continent, it is covered by thick ice, and it has no permanent population.' }),

  makeMCQ({ id:'g5hg-u1-006', chapterId:'g5enr-world', subsection:'world', difficulty:1,
    question:'How many oceans are there on Earth?',
    options:['Five','Three','Four','Seven'],
    answer:'Five',
    hint:'Pacific, Atlantic, Indian... and two more at the ends of the Earth.',
    explanation:'The <b>five oceans</b> are the Pacific, the Atlantic, the Indian, the Arctic and the Southern Ocean. The <b>Pacific</b> is the largest, and Mauritius lies in the <b>Indian</b> Ocean.' }),

  makeMCQ({ id:'g5hg-u1-007', chapterId:'g5enr-world', subsection:'world', difficulty:2,
    question:'Which ocean surrounds the continent of Antarctica?',
    options:['The Southern Ocean','The Arctic Ocean','The Atlantic Ocean','The Indian Ocean'],
    answer:'The Southern Ocean',
    hint:'It is named after the end of the Earth it circles.',
    explanation:'The <b>Southern Ocean</b> circles Antarctica. The <b>Arctic Ocean</b> is the one at the opposite end of the Earth, around the North Pole.' }),

  makeMCQ({ id:'g5hg-u1-008', chapterId:'g5enr-world', subsection:'indian_ocean', difficulty:2,
    question:'The Mozambique Channel is the stretch of sea between Mozambique and which island?',
    options:['Madagascar','Rodrigues','Sri Lanka','Comoros'],
    answer:'Madagascar',
    hint:'Look at the map between Africa and the big island to its east.',
    explanation:'The <b>Mozambique Channel</b> separates the African country of Mozambique from the island of <b>Madagascar</b>. It is an important shipping route in the Indian Ocean.' }),

  makeMCQ({ id:'g5hg-u1-009', chapterId:'g5enr-world', subsection:'indian_ocean', difficulty:2,
    question:'The Arabian Sea is the part of the Indian Ocean lying between Oman and which country?',
    options:['India','Kenya','Australia','Indonesia'],
    answer:'India',
    hint:'Ships from Arabia sailed east across it to buy spices.',
    explanation:'The <b>Arabian Sea</b> lies between Oman (in Arabia) and <b>India</b>. Arab traders crossed it for centuries before European sailors reached the Indian Ocean.' }),

  makeMCQ({ id:'g5hg-u1-010', chapterId:'g5enr-world', subsection:'indian_ocean', difficulty:2,
    question:'The Bay of Bengal lies between India and which neighbouring country?',
    options:['Myanmar','Somalia','Malaysia','Pakistan'],
    answer:'Myanmar',
    hint:'On old maps this country was called Burma.',
    explanation:'The <b>Bay of Bengal</b> lies between India and <b>Myanmar</b>, which older maps call Burma. It is a large arm of the Indian Ocean.' }),

  makeMCQ({ id:'g5hg-u1-011', chapterId:'g5enr-world', subsection:'indian_ocean', difficulty:3,
    question:'The Red Sea is the narrow sea bordered by Sudan and which other country?',
    options:['Saudi Arabia','South Africa','Sri Lanka','Madagascar'],
    answer:'Saudi Arabia',
    hint:'It separates north-east Africa from the Arabian lands.',
    explanation:'The <b>Red Sea</b> lies between Sudan in Africa and <b>Saudi Arabia</b> in Arabia. Today it links the Indian Ocean to the Mediterranean through the Suez Canal.' }),

  makeMCQ({ id:'g5hg-u1-012', chapterId:'g5enr-world', subsection:'world', difficulty:2,
    question:'Victoria Falls, one of the world’s great natural sites, is found on which continent?',
    options:['Africa','South America','Asia','Europe'],
    answer:'Africa',
    hint:'The same continent as the Sahara and Mount Kilimanjaro.',
    explanation:'<b>Victoria Falls</b> is a huge waterfall on the Zambezi River in southern <b>Africa</b>. It is a protected natural site visited by people from all over the world.' }),

  makeMCQ({ id:'g5hg-u1-013', chapterId:'g5enr-world', subsection:'world', difficulty:2,
    question:'The Grand Canyon, a deep valley cut by a river, is found on which continent?',
    options:['North America','South America','Australia','Africa'],
    answer:'North America',
    hint:'It is in the United States.',
    explanation:'The <b>Grand Canyon</b> was carved by the Colorado River in the United States, in <b>North America</b>. It shows how powerfully a river can shape the land over a very long time.' }),

  makeMCQ({ id:'g5hg-u1-014', chapterId:'g5enr-world', subsection:'world', difficulty:3,
    question:'The Giant’s Causeway, with its columns of volcanic rock, is a natural site on which continent?',
    options:['Europe','Asia','Africa','Australia'],
    answer:'Europe',
    hint:'It is on the coast of Northern Ireland.',
    explanation:'The <b>Giant’s Causeway</b> is in Northern Ireland, in <b>Europe</b>. Its thousands of stone columns formed when thick lava cooled and cracked, in the same way that basalt forms in Mauritius.' }),

  // ── Natural and man-made, and sustainability ────────────────────────────────
  makeMCQ({ id:'g5hg-u1-015', chapterId:'natural-env', subsection:'relief', difficulty:1,
    question:'Which of these is a <b>man-made</b> feature of the environment?',
    options:['A road','A river','A mountain','A coral reef'],
    answer:'A road',
    hint:'Which one did people build?',
    explanation:'A <b>road</b> is man-made, like houses, fields and gardens. Rivers, mountains and coral reefs are <b>natural features</b> — they were not made by people.' }),

  makeMCQ({ id:'g5hg-u1-016', chapterId:'env-problems', subsection:'conservation', difficulty:2,
    question:'What does <b>sustainability</b> mean?',
    options:['Using resources so future generations still have them','Using up resources as quickly as we can',
             'Buying only goods that come from abroad','Keeping people away from every natural place'],
    answer:'Using resources so future generations still have them',
    hint:'Think about the children who will live here after us.',
    explanation:'<b>Sustainability</b> means protecting, restoring and conserving our resources so that <b>future generations</b> can use them too. Cutting every tree today leaves nothing for tomorrow.' }),

  // ── Relief of Mauritius ────────────────────────────────────────────────────
  makeMCQ({ id:'g5hg-u1-017', chapterId:'natural-env', subsection:'relief', difficulty:2,
    question:'In geography, what does the word <b>relief</b> mean?',
    options:['The variation in the height of the land','The amount of rain a place receives',
             'The number of rivers in a district','The distance from the sea to a town'],
    answer:'The variation in the height of the land',
    hint:'It is about how high and how low the land is.',
    explanation:'<b>Relief</b> is the variation in the height of the land. Mauritius has three main relief features: the <b>mountains and mountain ranges</b>, the <b>Central Plateau</b> and the <b>plains</b>.' }),

  makeMCQ({ id:'g5hg-u1-018', chapterId:'natural-env', subsection:'relief', difficulty:2,
    question:'What is the difference between a <b>mountain</b> and a <b>hill</b>?',
    options:['A mountain is high and steep; a hill is lower and gentler',
             'A mountain is made of rock; a hill is made of soil',
             'A mountain is found inland; a hill is found on the coast',
             'A mountain has trees on it; a hill has grass on it'],
    answer:'A mountain is high and steep; a hill is lower and gentler',
    hint:'Think about height and about how steep the sides are.',
    explanation:'A <b>mountain</b> is high with steep slopes. A <b>hill</b> is lower with gentler slopes. A <b>plateau</b> is high but fairly flat, and a <b>plain</b> is low and flat.' }),

  makeMCQ({ id:'g5hg-u1-019', chapterId:'natural-env', subsection:'relief', difficulty:1,
    question:'How high is Piton de la Petite Rivi&egrave;re Noire, the highest mountain in Mauritius?',
    options:['828 m','398 m','392 m','1,240 m'],
    answer:'828 m',
    hint:'It is a little over eight hundred metres.',
    explanation:'<b>Piton de la Petite Rivi&egrave;re Noire</b> reaches <b>828 m</b> and is the highest point in Mauritius. Mont Limon in Rodrigues, at 398 m, is less than half its height.' }),

  makeMCQ({ id:'g5hg-u1-020', chapterId:'natural-env', subsection:'relief', difficulty:3,
    question:'Which of these is one of the main mountain ranges of Mauritius?',
    options:['Port Louis-Moka','Plaine des Roches','Central Ridge','Plaine Corail'],
    answer:'Port Louis-Moka',
    hint:'Three of these are flat land, and one of them is in Rodrigues.',
    explanation:'The main ranges are <b>Port Louis-Moka</b>, <b>Black River</b>, <b>Savanne</b> and <b>Grand Port</b>. They are the remains of the ring of the large volcano that built Mauritius. Plaine des Roches is a plain, and the Central Ridge and Plaine Corail are in Rodrigues.' }),

  makeMCQ({ id:'g5hg-u1-021', chapterId:'natural-env', subsection:'relief', difficulty:3,
    question:'Why are the mountain ranges called the <b>oldest</b> relief features of Mauritius?',
    options:['They are what remains of the volcano that formed the island',
             'They were pushed up when two plates collided recently',
             'They were built from sand blown inland by the wind',
             'They were left behind when the sea level fell'],
    answer:'They are what remains of the volcano that formed the island',
    hint:'Mauritius began as one huge volcano. What is left of its rim?',
    explanation:'The ranges are <b>remnants of the large volcano</b> that formed Mauritius. Erosion weakened the ring and rivers carved valleys and gorges through it, leaving the broken ranges we see today.' }),

  makeMCQ({ id:'g5hg-u1-022', chapterId:'natural-env', subsection:'relief', difficulty:2,
    question:'Which of these is one of the main <b>plains</b> of Mauritius?',
    options:['Plaine des Roches','Plaine Champagne','Mont Limon','Le Morne Mountain'],
    answer:'Plaine des Roches',
    hint:'Plains are low and flat, mostly near the coast.',
    explanation:'The main plains are the <b>Northern Plain</b>, <b>Plaine des Roches</b> (north-east), the <b>Flacq Plain</b> (east), the <b>Grand Port Plain</b> (south-east) and <b>Plaine St Pierre</b> (west). Plaine Champagne is high land on the plateau, over 600 m.' }),

  makeMCQ({ id:'g5hg-u1-023', chapterId:'natural-env', subsection:'relief', difficulty:3,
    question:'Why are the plains of Mauritius intensively cultivated, mainly with sugar cane?',
    options:['They are flat, fertile and easy to work','They are the coolest part of the island',
             'They receive the heaviest rainfall','They are the oldest rocks on the island'],
    answer:'They are flat, fertile and easy to work',
    hint:'Think of a tractor on a slope against a tractor on flat ground.',
    explanation:'The plains are <b>low, flat and fertile</b>, so machines can work them and the soil holds. That is why most of the sugar cane is grown there rather than on the steep mountain slopes.' }),

  makeMCQ({ id:'g5hg-u1-024', chapterId:'natural-env', subsection:'relief', difficulty:2,
    question:'Why is the Central Plateau of Mauritius the source of many rivers?',
    options:['It is high, fairly flat and receives much rainfall','It is the lowest and flattest part of the island',
             'It is made of limestone that holds no water','It lies closest to the coral reef'],
    answer:'It is high, fairly flat and receives much rainfall',
    hint:'Rivers need two things: plenty of rain and land that slopes away.',
    explanation:'The <b>Central Plateau</b> was formed by lava. It is mostly flat or undulating, it receives <b>much rainfall</b>, and because it is high the water runs off it in every direction — so many rivers begin there.' }),

  // ── Relief of Rodrigues ────────────────────────────────────────────────────
  makeMCQ({ id:'g5hg-u1-025', chapterId:'natural-env', subsection:'relief', difficulty:2,
    question:'What is the main relief feature running east to west across Rodrigues?',
    options:['The Central Ridge','The Central Plateau','The Northern Plain','The Black River range'],
    answer:'The Central Ridge',
    hint:'It is a long highland running the length of the island.',
    explanation:'Rodrigues has three relief areas: the <b>Central Ridge</b>, the sloping lands and river valleys, and the plains. The ridge is an east-west highland of undulating, hilly land.' }),

  makeMCQ({ id:'g5hg-u1-026', chapterId:'natural-env', subsection:'relief', difficulty:2,
    question:'Which is the second highest mount in Rodrigues, after Mont Limon?',
    options:['Mont Malartic','Le Morne Brabant','Piton de la Fournaise','Pieter Both'],
    answer:'Mont Malartic',
    hint:'It is only six metres lower than Mont Limon.',
    explanation:'<b>Mont Limon</b> is the highest point of Rodrigues at 398 m, and <b>Mont Malartic</b> comes next at 392 m. The other two peaks named here are in Mauritius and R&eacute;union.' }),

  makeMCQ({ id:'g5hg-u1-027', chapterId:'natural-env', subsection:'relief', difficulty:3,
    question:'Plaine Corail, in the south-west of Rodrigues, is a low flat plain made of which rock?',
    options:['Limestone','Basalt','Tuff','Granite'],
    answer:'Limestone',
    hint:'It is a white rock, and it is not volcanic.',
    explanation:'<b>Plaine Corail</b> is made of <b>limestone</b>, a white rock formed from solidified wind-blown sand. Caverne Patate and the limestone quarries there are heritage sites.' }),

  makeMCQ({ id:'g5hg-u1-028', chapterId:'volcanism', subsection:'rocks_soil', difficulty:3,
    question:'In Rodrigues, rivers eroded the soft tuffs and carried <b>alluvium</b>. Where was it deposited?',
    options:['Along river valleys and near river mouths','On the summit of the Central Ridge',
             'On the coral reef out at sea','Inside the caves of Plaine Corail'],
    answer:'Along river valleys and near river mouths',
    hint:'Moving water drops its load where it slows down.',
    explanation:'<b>Alluvium</b> is the material a river carries and drops when it slows. In Rodrigues it settled <b>along the valleys and near the river mouths</b> — at River Mourouk, Rivi&egrave;re Cocos, Rivi&egrave;re Banane and Baie aux Hu&icirc;tres — making flat, fertile, intensively cultivated land.' }),

  // ── Volcanoes: the sequence and the products ───────────────────────────────
  makeMCQ({ id:'g5hg-u1-029', chapterId:'volcanism', subsection:'formation', difficulty:2,
    question:'Inside a volcano, through which part does the magma rise before it reaches the crater?',
    options:['The pipe','The vent cone','The lagoon','The rim'],
    answer:'The pipe',
    hint:'It is the narrow channel from the chamber to the top.',
    explanation:'Hot molten rock is called <b>magma</b>. It is stored in a magma chamber, rises through the <b>pipe</b>, leaves through the <b>crater</b> and then flows down the slope as <b>lava</b>.' }),

  makeMCQ({ id:'g5hg-u1-030', chapterId:'volcanism', subsection:'rocks_soil', difficulty:2,
    question:'What are <b>volcanic bombs</b>?',
    options:['Molten lava thrown into the air that cools as it falls',
             'Ash and dust that settle and harden into tuff',
             'Lava that cools slowly underground into basalt',
             'Rocks dropped on the shore by strong waves'],
    answer:'Molten lava thrown into the air that cools as it falls',
    hint:'The name describes something flying through the air.',
    explanation:'<b>Volcanic bombs</b> are lumps of molten lava thrown into the air by an eruption; they cool as they fly. Cooled lava flows become <b>basalt</b>, while ash and dust settle and solidify into <b>tuff</b>.' }),

  makeMCQ({ id:'g5hg-u1-031', chapterId:'volcanism', subsection:'craters', difficulty:2,
    question:'Which two Mauritian dormant volcanoes hold <b>crater lakes</b>?',
    options:['Bassin Blanc and Grand Bassin','Trou aux Cerfs and Le Pouce',
             'Karthala and La Fournaise','Mont Limon and Mont Malartic'],
    answer:'Bassin Blanc and Grand Bassin',
    hint:'The word "bassin" is a clue: it means a basin that holds water.',
    explanation:'<b>Bassin Blanc</b> and <b>Grand Bassin</b> are crater lakes — craters that have filled with water. Trou aux Cerfs is a dormant crater too, but it does not hold a permanent lake.' }),

  makeMCQ({ id:'g5hg-u1-032', chapterId:'volcanism', subsection:'formation', difficulty:3,
    question:'Mauritius, Rodrigues and R&eacute;union are volcanic islands. How were they built?',
    options:['By repeated eruptions on the ocean floor','By coral growing upward over millions of years',
             'By sand carried out to sea by rivers','By pieces breaking away from Africa'],
    answer:'By repeated eruptions on the ocean floor',
    hint:'Each eruption adds another layer on top of the last.',
    explanation:'The three <b>Mascarene Islands</b> were formed by <b>repeated eruptions on the ocean floor</b>. Layer built on layer until the pile rose above the surface of the sea.' }),

  makeMCQ({ id:'g5hg-u1-033', chapterId:'volcanism', subsection:'formation', difficulty:4,
    question:'A geographer finds tuff in one place and basalt in another, both from the same volcano. What does that tell them?',
    options:['The volcano both exploded ash into the air and poured out lava flows',
             'The volcano is still active and will soon erupt again',
             'The tuff is much younger than the coral reef offshore',
             'The two rocks were carried there by rivers from elsewhere'],
    answer:'The volcano both exploded ash into the air and poured out lava flows',
    hint:'Each rock records a different kind of eruption.',
    explanation:'<b>Basalt</b> forms where lava flowed and cooled; <b>tuff</b> forms where ash and dust were blown out, settled and solidified. Finding both means the same volcano erupted in <b>both ways</b> at different times — explosively, and as quiet flows.' }),

  // ── Environmental problems and protection ──────────────────────────────────
  makeMCQ({ id:'g5hg-u1-034', chapterId:'env-problems', subsection:'beach_erosion', difficulty:2,
    question:'Which of these is a <b>natural</b> cause of beach erosion?',
    options:['Strong waves and storms','Sand mining in the lagoon',
             'Building jetties on the shore','Pollution that damages coral'],
    answer:'Strong waves and storms',
    hint:'Three of these are things people do.',
    explanation:'Natural causes are <b>strong waves, currents and storms</b>. The human causes are past sand mining, jetties and buildings, and pollution that damages the coral reefs.' }),

  makeMCQ({ id:'g5hg-u1-035', chapterId:'env-problems', subsection:'beach_erosion', difficulty:3,
    question:'Why does damaging the coral reef make beach erosion worse?',
    options:['The reef reduces the force of the waves reaching the beach',
             'The reef supplies fresh sand to the beach each year',
             'The reef stops rivers washing soil out to sea',
             'The reef keeps the lagoon water cool in summer'],
    answer:'The reef reduces the force of the waves reaching the beach',
    hint:'Waves break on the reef before they reach the shore.',
    explanation:'<b>Coral reefs reduce the force of the waves</b> and so protect the beach behind them. When pollution kills the coral, stronger waves reach the shore and the beach wears away faster.' }),

  makeMCQ({ id:'g5hg-u1-036', chapterId:'env-problems', subsection:'beach_erosion', difficulty:2,
    question:'Which tree is often uprooted along the coast when the beach becomes narrow?',
    options:['The filao','The ebony','The mangrove','The latanier'],
    answer:'The filao',
    hint:'It is the tall, feathery tree planted just behind many Mauritian beaches.',
    explanation:'As the beach narrows, <b>filaos</b> lose the sand around their roots and are uprooted. Roads and buildings may be damaged too, and corals and other marine life are affected.' }),

  makeMCQ({ id:'g5hg-u1-037', chapterId:'env-problems', subsection:'beach_erosion', difficulty:2,
    question:'Which practice was <b>banned</b> in Mauritius to protect the beaches?',
    options:['Sand mining in the lagoons','Fishing with a rod from the shore',
             'Planting mangroves along the coast','Swimming inside the reef'],
    answer:'Sand mining in the lagoons',
    hint:'It was removing the very material the beaches are made of.',
    explanation:'<b>Sand mining in lagoons has been banned</b>, laws now protect the beaches, beaches are cleaned and restored, and reefs and mangroves are protected.' }),

  makeMCQ({ id:'g5hg-u1-038', chapterId:'env-problems', subsection:'soil_erosion', difficulty:3,
    question:'Which combination makes soil erosion worse in <b>Rodrigues</b>?',
    options:['Steep slopes, deforestation and overgrazing','Flat plains, heavy machinery and irrigation',
             'Limestone caves, sea spray and high tides','Cool weather, thick forest and gentle rain'],
    answer:'Steep slopes, deforestation and overgrazing',
    hint:'Think of bare, steep land with animals grazing on it.',
    explanation:'In Rodrigues, soil erosion is worsened by <b>steep slopes, deforestation, overgrazing</b> and planting crops on steep land. Losing the topsoil reduces soil fertility and crop production.' }),

  makeMCQ({ id:'g5hg-u1-039', chapterId:'env-problems', subsection:'soil_erosion', difficulty:2,
    question:'Building <b>terraces</b> on a hillside helps the farmer because they...',
    options:['slow the water down and reduce erosion','make the slope steeper so water runs off faster',
             'stop the sun reaching the crops','keep animals away from the field'],
    answer:'slow the water down and reduce erosion',
    hint:'Flat steps instead of one long slope.',
    explanation:'<b>Terraces</b> cut the slope into flat steps, so rainwater moves slowly instead of rushing downhill and carrying the topsoil with it. Planting trees helps in the same way, because roots bind the soil.' }),

  makeMCQ({ id:'g5hg-u1-040', chapterId:'env-problems', subsection:'conservation', difficulty:2,
    question:'Which of these is a <b>nature reserve in Rodrigues</b>?',
    options:['Grande Montagne','Blue Bay Marine Park','Black River National Park','&Icirc;le aux Aigrettes'],
    answer:'Grande Montagne',
    hint:'Three of these are in Mauritius.',
    explanation:'In Rodrigues the reserves are <b>Grande Montagne</b>, the Anse Quitor-Fran&ccedil;ois Leguat Giant Tortoise Reserve and &Icirc;le Cocos. Black River National Park, &Icirc;le aux Aigrettes, Vall&eacute;e de Ferney and Blue Bay Marine Park are in Mauritius.' }),

  makeMCQ({ id:'g5hg-u1-041', chapterId:'env-problems', subsection:'conservation', difficulty:3,
    question:'What are nature reserves meant to do?',
    options:['Protect endemic plants and animals from extinction',
             'Provide new land for houses and hotels',
             'Store water for the towns during a drought',
             'Grow sugar cane for export overseas'],
    answer:'Protect endemic plants and animals from extinction',
    hint:'"Endemic" means found in that place and nowhere else.',
    explanation:'Nature reserves <b>protect endemic fauna and flora, restore habitats and prevent extinction</b>. Mauritius has lost species before — the dodo and the Red Rail — and a reserve is how the survivors are kept.' }),

  // ── Consolidation pass: the remaining facts of Unit 1 ──────────────────────
  // Everything below was still uncovered after the first pass, checked fact by
  // fact against the pack's own question stems and answers.

  makeMCQ({ id:'g5hg-u1-042', chapterId:'g5enr-world', subsection:'world', difficulty:2,
    question:'Why is Earth called the only known <b>habitable</b> planet?',
    options:['Air, water, land and soil support plants and animals','It is the largest planet in the solar system',
             'It is the planet closest to the Sun','It is the only planet that has mountains'],
    answer:'Air, water, land and soil support plants and animals',
    hint:'Habitable means that living things can live there.',
    explanation:'Earth is the only planet we know of where life can live. <b>Air, water, land and soil support plants and animals</b> — no other planet is known to offer all four.' }),

  makeMCQ({ id:'g5hg-u1-043', chapterId:'g5enr-world', subsection:'world', difficulty:1,
    question:'Why does Earth look <b>blue</b> from space?',
    options:['Seas and oceans cover most of its surface','The sky around it is blue from every side',
             'The ice at its two poles reflects blue','The forests on it look blue from far away'],
    answer:'Seas and oceans cover most of its surface',
    hint:'About 70% of the surface is water.',
    explanation:'Seas and oceans cover about <b>70%</b> of Earth’s surface, so from space the planet appears blue.' }),

  makeMCQ({ id:'g5hg-u1-044', chapterId:'map-skills', subsection:'using_map', difficulty:1,
    question:'What is a <b>globe</b>?',
    options:['A model of the Earth','A flat map of one country',
             'A line joining places of equal height','A tool for measuring distance'],
    answer:'A model of the Earth',
    hint:'It is round, and it turns.',
    explanation:'A <b>globe</b> is a model of the Earth. On it, the large land areas are the <b>continents</b> and the large sea areas are the <b>oceans</b>.' }),

  makeMCQ({ id:'g5hg-u1-045', chapterId:'g5enr-world', subsection:'world', difficulty:2,
    question:'The Atlantic Ocean lies between South America and which continent?',
    options:['Africa','Asia','Australia','Antarctica'],
    answer:'Africa',
    hint:'Look between the west coast of Africa and the east coast of South America.',
    explanation:'The <b>Atlantic Ocean</b> lies between South America and <b>Africa</b>. The Indian Ocean, on the other side of Africa, is bordered by Africa, Asia and Australia.' }),

  makeMCQ({ id:'g5hg-u1-046', chapterId:'map-skills', subsection:'coordinates', difficulty:1,
    question:'Mauritius and Rodrigues lie in which hemisphere?',
    options:['The Southern Hemisphere','The Northern Hemisphere',
             'The Eastern Hemisphere only','The Western Hemisphere only'],
    answer:'The Southern Hemisphere',
    hint:'They lie below the Equator, near the Tropic of Capricorn.',
    explanation:'Both islands are in the <b>Southern Hemisphere</b>, near the <b>Tropic of Capricorn</b> at 23.5&deg; South. That is why our summer falls in December and our winter in July.' }),

  makeMCQ({ id:'g5hg-u1-047', chapterId:'map-skills', subsection:'coordinates', difficulty:2,
    question:'The Greenwich Meridian passes through which city?',
    options:['London','Paris','Lisbon','Cape Town'],
    answer:'London',
    hint:'Greenwich is a place in that city.',
    explanation:'The <b>Greenwich Meridian</b> is the line of 0&deg; longitude, and it passes through <b>London</b>. Longitudes are numbered from it, 0&deg; to 180&deg; East and West.' }),

  makeMCQ({ id:'g5hg-u1-048', chapterId:'map-skills', subsection:'coordinates', difficulty:3,
    question:'The Tropic of Cancer passes through North America, Africa and ___.',
    options:['Asia','Australia','Antarctica','South America'],
    answer:'Asia',
    hint:'It runs through the northern half of the world.',
    explanation:'The <b>Tropic of Cancer</b> (23.5&deg; North) crosses <b>North America, Africa and Asia</b>. The Tropic of Capricorn, in the south, crosses Madagascar and passes close to Mauritius.' }),

  makeMCQ({ id:'g5hg-u1-049', chapterId:'g5enr-world', subsection:'indian_ocean', difficulty:2,
    question:'In which part of the Indian Ocean are the Mascarene Islands?',
    options:['The south-west','The north-east','The far south','The centre'],
    answer:'The south-west',
    hint:'They lie east of Madagascar, which is itself off south-east Africa.',
    explanation:'Mauritius, Rodrigues and R&eacute;union form the <b>Mascarene Islands</b> in the <b>south-west Indian Ocean</b>. All three are volcanic islands built by repeated eruptions on the ocean floor.' }),

  makeMCQ({ id:'g5hg-u1-050', chapterId:'volcanism', subsection:'formation', difficulty:2,
    question:'Lava flows can build cones, mountains, plains and ___.',
    options:['plateaus','lagoons','coral reefs','river valleys'],
    answer:'plateaus',
    hint:'The flat high land in the middle of Mauritius is one.',
    explanation:'Lava flows can form <b>cones, mountains, plains and plateaus</b>. The Central Plateau of Mauritius was itself formed by lava.' }),

  makeMCQ({ id:'g5hg-u1-051', chapterId:'volcanism', subsection:'formation', difficulty:3,
    question:'Which is the correct order of volcanic rock formation?',
    options:['Magma rises, eruption, lava flows, lava cools, basalt forms',
             'Lava cools, magma rises, basalt forms, eruption, lava flows',
             'Eruption, basalt forms, magma rises, lava cools, lava flows',
             'Lava flows, lava cools, magma rises, eruption, basalt forms'],
    answer:'Magma rises, eruption, lava flows, lava cools, basalt forms',
    hint:'Start deep underground and work upwards.',
    explanation:'The sequence is <b>magma rises &rarr; eruption &rarr; lava flows &rarr; lava cools &rarr; basalt forms</b>. Separately, <b>ash and dust accumulate &rarr; solidify &rarr; tuff forms</b>.' }),

  makeMCQ({ id:'g5hg-u1-052', chapterId:'volcanism', subsection:'formation', difficulty:2,
    question:'Where is magma stored before it rises up the pipe?',
    options:['In a magma chamber','In the crater at the top',
             'In the lava flow outside','In a lagoon under the reef'],
    answer:'In a magma chamber',
    hint:'It waits in a large space deep inside the volcano.',
    explanation:'Hot molten rock, or <b>magma</b>, is stored in a <b>magma chamber</b>. From there it rises through the <b>pipe</b>, leaves by the <b>crater</b> and flows down the slope as <b>lava</b>.' }),

  makeMCQ({ id:'g5hg-u1-053', chapterId:'natural-env', subsection:'relief', difficulty:1,
    question:'A <b>plain</b> is land that is ___.',
    options:['low and flat','high and flat','high and steep','low and steep'],
    answer:'low and flat',
    hint:'Compare it with a plateau, which is also flat.',
    explanation:'A <b>plain</b> is <b>low and flat</b>; a <b>plateau</b> is <b>high and fairly flat</b>. A mountain is high with steep slopes and a hill is lower with gentler slopes.' }),

  makeMCQ({ id:'g5hg-u1-054', chapterId:'natural-env', subsection:'relief', difficulty:3,
    question:'Which two places in the south-west of Mauritius are over 600 m high?',
    options:['Grand Bassin and Plaine Champagne','Plaine des Roches and Flacq Plain',
             'Plaine St Pierre and Northern Plain','Plaine Corail and Caverne Patate'],
    answer:'Grand Bassin and Plaine Champagne',
    hint:'Both are on the high land of the south-west, not on the coast.',
    explanation:'<b>Grand Bassin</b> and <b>Plaine Champagne</b> in the south-west are over <b>600 m</b> high. The other names listed are low coastal plains, and Plaine Corail is in Rodrigues.' }),

  makeMCQ({ id:'g5hg-u1-055', chapterId:'natural-env', subsection:'relief', difficulty:2,
    question:'The Central Plateau of Mauritius was formed by ___.',
    options:['lava','alluvium','limestone','wind-blown sand'],
    answer:'lava',
    hint:'Mauritius is a volcanic island.',
    explanation:'The <b>Central Plateau was formed by lava</b>. It is mostly flat or undulating, receives much rainfall and is the source of many rivers.' }),

  makeMCQ({ id:'g5hg-u1-056', chapterId:'natural-env', subsection:'relief', difficulty:3,
    question:'Why are the mountains of Mauritius part of our <b>natural heritage</b>?',
    options:['They protect endemic fauna and flora','They are the highest land in the Mascarenes',
             'They are the best land for sugar cane','They were built by the first settlers'],
    answer:'They protect endemic fauna and flora',
    hint:'Endemic means found here and nowhere else.',
    explanation:'Our mountains <b>protect endemic fauna and flora</b> and form part of our <b>natural heritage</b>. Steep slopes were never cleared for cane, so native forest survived there.' }),

  makeMCQ({ id:'g5hg-u1-057', chapterId:'natural-env', subsection:'relief', difficulty:3,
    question:'In Rodrigues, where are <b>tuffs</b> found?',
    options:['At La Ferme and La Fouche Corail','On the limestone plain of Plaine Corail',
             'Along the beaches of Baie aux Hu&icirc;tres','Inside the caves of Caverne Patate'],
    answer:'At La Ferme and La Fouche Corail',
    hint:'They lie on the Central Ridge, where the eruptions were explosive.',
    explanation:'Explosive eruptions produced ash and dust which solidified into <b>tuffs</b>. They occur at <b>La Ferme, La Fouche Corail</b> and on the slopes of Petit Br&ucirc;l&eacute;, Roseaux and Mangues.' }),

  makeMCQ({ id:'g5hg-u1-058', chapterId:'natural-env', subsection:'relief', difficulty:3,
    question:'Near which Rodrigues rivers is alluvial land found?',
    options:['River Mourouk and Rivi&egrave;re Banane','Grand River North West and River Savanne',
             'Grande Rivi&egrave;re Sud-Est and Black River','River Rempart and Rivi&egrave;re du Poste'],
    answer:'River Mourouk and Rivi&egrave;re Banane',
    hint:'The other rivers listed are all in Mauritius.',
    explanation:'Alluvial land is flat, fertile and intensively cultivated. In Rodrigues the deposits occur near <b>River Mourouk, Rivi&egrave;re Cocos, Rivi&egrave;re Banane</b> and <b>Baie aux Hu&icirc;tres</b>.' }),

  makeMCQ({ id:'g5hg-u1-059', chapterId:'g5enr-landmarks', subsection:'nature', difficulty:3,
    question:'Caverne Patate and the limestone quarries of Rodrigues are ___.',
    options:['heritage sites','active volcanoes','nature reserves','coral lagoons'],
    answer:'heritage sites',
    hint:'They are protected for what they tell us, not for the animals in them.',
    explanation:'<b>Caverne Patate</b> and the limestone quarries lie on <b>Plaine Corail</b>, the low limestone plain in the south-west of Rodrigues, and are <b>heritage sites</b>.' }),

  makeMCQ({ id:'g5hg-u1-060', chapterId:'env-problems', subsection:'beach_erosion', difficulty:2,
    question:'Besides narrowing the beach, what else can beach erosion damage?',
    options:['Roads and buildings near the shore','Rivers on the central plateau',
             'Crops grown on the high land','Forests in the mountain ranges'],
    answer:'Roads and buildings near the shore',
    hint:'Think about what is built just behind a beach.',
    explanation:'As the beach wears away, <b>roads and buildings may be damaged</b>, filaos may be uprooted, and corals and other marine life are affected.' }),

  makeMCQ({ id:'g5hg-u1-061', chapterId:'env-problems', subsection:'conservation', difficulty:2,
    question:'Which protected area of Mauritius is a <b>marine</b> park?',
    options:['Blue Bay','Grande Montagne','Vall&eacute;e de Ferney','Black River'],
    answer:'Blue Bay',
    hint:'Marine means of the sea, so it protects a lagoon.',
    explanation:'<b>Blue Bay Marine Park</b> protects a lagoon and its corals. Black River National Park, &Icirc;le aux Aigrettes and Vall&eacute;e de Ferney protect land; Grande Montagne is in Rodrigues.' }),

  makeMCQ({ id:'g5hg-u1-062', chapterId:'env-problems', subsection:'conservation', difficulty:3,
    question:'Which Rodrigues reserve is named after the settler who described its giant tortoises?',
    options:['The Fran&ccedil;ois Leguat Giant Tortoise Reserve','The Grande Montagne Nature Reserve',
             'The &Icirc;le Cocos Bird Reserve','The Blue Bay Marine Park'],
    answer:'The Fran&ccedil;ois Leguat Giant Tortoise Reserve',
    hint:'He kept a diary in Rodrigues in 1691.',
    explanation:'The reserve at <b>Anse Quitor</b> is named after <b>Fran&ccedil;ois Leguat</b>, who recorded the abundant giant tortoises in 1691. Rodrigues also protects <b>Grande Montagne</b> and <b>&Icirc;le Cocos</b>.' }),

  makeMCQ({ id:'g5hg-u1-063', chapterId:'env-problems', subsection:'conservation', difficulty:2,
    question:'Which of these is a nature reserve in <b>Mauritius</b>?',
    options:['Vall&eacute;e de Ferney','Grande Montagne','&Icirc;le Cocos','Anse Quitor'],
    answer:'Vall&eacute;e de Ferney',
    hint:'Three of these are in Rodrigues.',
    explanation:'<b>Vall&eacute;e de Ferney</b> is in Mauritius, along with Black River National Park, &Icirc;le aux Aigrettes and Blue Bay Marine Park. Grande Montagne, &Icirc;le Cocos and Anse Quitor are in Rodrigues.' }),

  // ⚠ Found by scripts/test-syllabus-facts.js after the consolidation pass: the
  // three relief features were named in an explanation and asked nowhere.

  makeMCQ({ id:'g5hg-u1-064', chapterId:'natural-env', subsection:'relief', difficulty:2,
    question:'What are the <b>three main relief features</b> of Mauritius?',
    options:['Mountains, the Central Plateau and the plains','Beaches, lagoons and the coral reef',
             'Rivers, waterfalls and crater lakes','Limestone, alluvium and tuff'],
    answer:'Mountains, the Central Plateau and the plains',
    hint:'Think high, middle and low.',
    explanation:'Mauritius has three main relief features: the <b>mountains and mountain ranges</b>, the <b>Central Plateau</b> and the <b>plains</b>. Relief is the variation in the height of the land.' })

);
