'use strict';
(function () {

// ── length_cm_m (20 questions) ────────────────────────────────────────────────

STATIC_QUESTIONS.push(
  makeMCQ({ id:'g2mth-msr-001', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'How many centimetres are in 1 metre?',
    options:['100','10','1000','50'],
    answer:'100',
    hint:'1 m = ___ cm.',
    explanation:'There are <b>100</b> centimetres in 1 metre.' }),

  makeMCQ({ id:'g2mth-msr-002', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'A door is about 2 ___ tall.',
    options:['m','cm','kg','L'],
    answer:'m',
    hint:'A door is much taller than a ruler (30 cm). We use metres for big things.',
    explanation:'A door is about 2 <b>metres (m)</b> tall.' }),

  makeMCQ({ id:'g2mth-msr-003', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'A pencil is about 15 ___ long.',
    options:['cm','m','km','mm'],
    answer:'cm',
    hint:'A pencil is shorter than a metre. We use centimetres for small things.',
    explanation:'A pencil is about 15 <b>centimetres (cm)</b> long.' }),

  makeMCQ({ id:'g2mth-msr-004', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'Which is longer: 80 cm or 1 m?',
    options:['1 m','80 cm','they are equal','cannot tell'],
    answer:'1 m',
    hint:'1 m = 100 cm. Is 100 cm longer than 80 cm?',
    explanation:'1 m = 100 cm, which is longer than 80 cm. So <b>1 m</b> is longer.' }),

  makeMCQ({ id:'g2mth-msr-005', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'What unit do we use to measure the length of a classroom?',
    options:['metres (m)','centimetres (cm)','kilograms (kg)','litres (L)'],
    answer:'metres (m)',
    hint:'A classroom is much longer than 1 metre.',
    explanation:'We use <b>metres (m)</b> to measure the length of a classroom.' }),

  makeMCQ({ id:'g2mth-msr-006', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'Rani\'s hand is about 12 ___ wide.',
    options:['cm','m','kg','L'],
    answer:'cm',
    hint:'A hand is much smaller than 1 metre.',
    explanation:'A hand is about 12 <b>centimetres (cm)</b> wide.' }),

  makeMCQ({ id:'g2mth-msr-007', chapterId:'g2mth-measurement', difficulty:2, subsection:'length_cm_m',
    question:'Dev\'s book is 30 cm long. How many cm short is it from 1 metre?',
    options:['70 cm','80 cm','60 cm','40 cm'],
    answer:'70 cm',
    hint:'1 m = 100 cm. 100 − 30 = ?',
    explanation:'100 cm − 30 cm = <b>70 cm</b>.' }),

  makeMCQ({ id:'g2mth-msr-008', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'Which is shorter: 1 m or 90 cm?',
    options:['90 cm','1 m','they are equal','cannot tell'],
    answer:'90 cm',
    hint:'1 m = 100 cm. Is 90 cm shorter than 100 cm?',
    explanation:'90 cm < 100 cm = 1 m. So <b>90 cm</b> is shorter.' }),

  makeMCQ({ id:'g2mth-msr-009', chapterId:'g2mth-measurement', difficulty:2, subsection:'length_cm_m',
    question:'Mia measures a table: 50 cm + 50 cm = ___',
    options:['1 m','100 cm and 1 m are both correct','2 m','50 cm'],
    answer:'100 cm and 1 m are both correct',
    hint:'50 + 50 = 100 cm = 1 m.',
    explanation:'50 cm + 50 cm = 100 cm = 1 m. <b>Both 100 cm and 1 m are correct</b>.' }),

  makeMCQ({ id:'g2mth-msr-010', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'What do we use to measure length in centimetres?',
    options:['a ruler','a scale','a clock','a thermometer'],
    answer:'a ruler',
    hint:'You use this at school to draw straight lines.',
    explanation:'We use <b>a ruler</b> to measure length in centimetres.' }),

  makeMCQ({ id:'g2mth-msr-011', chapterId:'g2mth-measurement', difficulty:2, subsection:'length_cm_m',
    question:'Priya is 120 cm tall. How tall is she in metres and centimetres?',
    options:['1 m 20 cm','12 m','2 m 20 cm','1 m 2 cm'],
    answer:'1 m 20 cm',
    hint:'100 cm = 1 m. 120 cm = 100 cm + 20 cm.',
    explanation:'120 cm = 100 cm + 20 cm = <b>1 m 20 cm</b>.' }),

  makeMCQ({ id:'g2mth-msr-012', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'Which is longer: 55 cm or 45 cm?',
    options:['55 cm','45 cm','they are equal','cannot tell'],
    answer:'55 cm',
    hint:'Compare the numbers.',
    explanation:'<b>55 cm</b> is longer than 45 cm.' }),

  makeMCQ({ id:'g2mth-msr-013', chapterId:'g2mth-measurement', difficulty:2, subsection:'length_cm_m',
    question:'Raj has a rope 85 cm long. He cuts off 30 cm. How long is the rope now?',
    options:['55 cm','65 cm','45 cm','50 cm'],
    answer:'55 cm',
    hint:'85 − 30 = ?',
    explanation:'85 − 30 = <b>55 cm</b>.' }),

  makeMCQ({ id:'g2mth-msr-014', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'A car is about 4 ___ long.',
    options:['m','cm','mm','kg'],
    answer:'m',
    hint:'A car is longer than any measurement in centimetres you can easily count.',
    explanation:'A car is about 4 <b>metres (m)</b> long.' }),

  makeMCQ({ id:'g2mth-msr-015', chapterId:'g2mth-measurement', difficulty:2, subsection:'length_cm_m',
    question:'Nadia has two sticks: one is 35 cm and the other is 45 cm. How long are they together?',
    options:['80 cm','70 cm','90 cm','75 cm'],
    answer:'80 cm',
    hint:'35 + 45 = ?',
    explanation:'35 + 45 = <b>80 cm</b>.' }),

  makeMCQ({ id:'g2mth-msr-016', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'A finger is about 5 ___ long.',
    options:['cm','m','km','L'],
    answer:'cm',
    hint:'A finger is very short — much less than 1 metre.',
    explanation:'A finger is about 5 <b>centimetres (cm)</b> long.' }),

  makeMCQ({ id:'g2mth-msr-017', chapterId:'g2mth-measurement', difficulty:2, subsection:'length_cm_m',
    question:'Dev\'s table is 1 m 50 cm long. How many centimetres is that?',
    options:['150 cm','105 cm','15 cm','200 cm'],
    answer:'150 cm',
    hint:'1 m = 100 cm. 100 + 50 = ?',
    explanation:'1 m 50 cm = 100 cm + 50 cm = <b>150 cm</b>.' }),

  makeMCQ({ id:'g2mth-msr-018', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'Which is longer: 1 m 10 cm or 100 cm?',
    options:['1 m 10 cm','100 cm','they are equal','cannot tell'],
    answer:'1 m 10 cm',
    hint:'1 m 10 cm = 110 cm. Is 110 cm longer than 100 cm?',
    explanation:'1 m 10 cm = 110 cm, which is longer than 100 cm. So <b>1 m 10 cm</b> is longer.' }),

  makeMCQ({ id:'g2mth-msr-019', chapterId:'g2mth-measurement', difficulty:2, subsection:'length_cm_m',
    question:'Mia has a ribbon 60 cm long and another 40 cm long. What is the total length?',
    options:['100 cm','90 cm','110 cm','80 cm'],
    answer:'100 cm',
    hint:'60 + 40 = ? cm. Can you say it in metres too?',
    explanation:'60 + 40 = <b>100 cm</b> = 1 m.' }),

  makeMCQ({ id:'g2mth-msr-020', chapterId:'g2mth-measurement', difficulty:1, subsection:'length_cm_m',
    question:'A book is about 25 ___ long.',
    options:['cm','m','kg','L'],
    answer:'cm',
    hint:'A book is much shorter than a metre.',
    explanation:'A book is about 25 <b>centimetres (cm)</b> long.' }),

// ── mass_kg (20 questions) ────────────────────────────────────────────────────

  makeMCQ({ id:'g2mth-msr-021', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'A bag of sugar weighs 1 ___.',
    options:['kg','cm','L','m'],
    answer:'kg',
    hint:'We measure how heavy things are in kilograms.',
    explanation:'A bag of sugar weighs 1 <b>kilogram (kg)</b>.' }),

  makeMCQ({ id:'g2mth-msr-022', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'Which is heavier: 3 kg of rice or 2 kg of rice?',
    options:['3 kg','2 kg','same','cannot tell'],
    answer:'3 kg',
    hint:'Compare the numbers. Which is more: 3 or 2?',
    explanation:'<b>3 kg</b> is heavier than 2 kg.' }),

  makeMCQ({ id:'g2mth-msr-023', chapterId:'g2mth-measurement', difficulty:2, subsection:'mass_kg',
    question:'Raj\'s bag weighs 5 kg. Dev\'s bag weighs 3 kg. How much more does Raj\'s bag weigh?',
    options:['2 kg','8 kg','1 kg','3 kg'],
    answer:'2 kg',
    hint:'5 − 3 = ?',
    explanation:'5 kg − 3 kg = <b>2 kg</b> more.' }),

  makeMCQ({ id:'g2mth-msr-024', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'What do we use to measure how heavy something is?',
    options:['a scale (balance)','a ruler','a clock','a measuring jug'],
    answer:'a scale (balance)',
    hint:'You put the object on one side to find its weight.',
    explanation:'We use <b>a scale (balance)</b> to measure mass in kilograms.' }),

  makeMCQ({ id:'g2mth-msr-025', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'A large watermelon weighs about 4 ___.',
    options:['kg','cm','L','g'],
    answer:'kg',
    hint:'A watermelon is very heavy. We measure it in kilograms.',
    explanation:'A large watermelon weighs about 4 <b>kilograms (kg)</b>.' }),

  makeMCQ({ id:'g2mth-msr-026', chapterId:'g2mth-measurement', difficulty:2, subsection:'mass_kg',
    question:'Rani buys 2 kg of flour and 3 kg of sugar. What is the total mass?',
    options:['5 kg','4 kg','6 kg','3 kg'],
    answer:'5 kg',
    hint:'2 + 3 = ?',
    explanation:'2 kg + 3 kg = <b>5 kg</b>.' }),

  makeMCQ({ id:'g2mth-msr-027', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'Which is lighter: 1 kg of feathers or 1 kg of rocks?',
    options:['they weigh the same','feathers','rocks','cannot tell'],
    answer:'they weigh the same',
    hint:'Both are 1 kg. The material does not change the weight.',
    explanation:'Both weigh <b>1 kg</b> — mass is the same no matter what the material is.' }),

  makeMCQ({ id:'g2mth-msr-028', chapterId:'g2mth-measurement', difficulty:2, subsection:'mass_kg',
    question:'Dev has a bag weighing 8 kg. He takes out 3 kg of books. How heavy is the bag now?',
    options:['5 kg','4 kg','6 kg','3 kg'],
    answer:'5 kg',
    hint:'8 − 3 = ?',
    explanation:'8 kg − 3 kg = <b>5 kg</b>.' }),

  makeMCQ({ id:'g2mth-msr-029', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'A baby weighs about 4 ___.',
    options:['kg','cm','L','m'],
    answer:'kg',
    hint:'A baby is heavier than a pencil but lighter than a grown-up.',
    explanation:'A baby weighs about 4 <b>kilograms (kg)</b>.' }),

  makeMCQ({ id:'g2mth-msr-030', chapterId:'g2mth-measurement', difficulty:2, subsection:'mass_kg',
    question:'Priya has 6 kg of fruit. She sells 4 kg. How many kg does she have left?',
    options:['2 kg','3 kg','1 kg','4 kg'],
    answer:'2 kg',
    hint:'6 − 4 = ?',
    explanation:'6 kg − 4 kg = <b>2 kg</b>.' }),

  makeMCQ({ id:'g2mth-msr-031', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'Which is the heaviest: 5 kg, 3 kg, or 7 kg?',
    options:['7 kg','5 kg','3 kg','they are all the same'],
    answer:'7 kg',
    hint:'Compare the numbers.',
    explanation:'<b>7 kg</b> is the greatest number, so it is the heaviest.' }),

  makeMCQ({ id:'g2mth-msr-032', chapterId:'g2mth-measurement', difficulty:2, subsection:'mass_kg',
    question:'Raj carries 4 kg of vegetables and 2 kg of rice. What is the total mass he carries?',
    options:['6 kg','5 kg','7 kg','4 kg'],
    answer:'6 kg',
    hint:'4 + 2 = ?',
    explanation:'4 kg + 2 kg = <b>6 kg</b>.' }),

  makeMCQ({ id:'g2mth-msr-033', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'Nadia\'s cat weighs 3 kg. A puppy weighs 5 kg. Which is lighter?',
    options:['the cat (3 kg)','the puppy (5 kg)','they are the same','cannot tell'],
    answer:'the cat (3 kg)',
    hint:'3 kg < 5 kg.',
    explanation:'3 kg < 5 kg, so <b>the cat</b> is lighter.' }),

  makeMCQ({ id:'g2mth-msr-034', chapterId:'g2mth-measurement', difficulty:2, subsection:'mass_kg',
    question:'Mia has a basket weighing 7 kg. She adds 2 kg of mangoes. How heavy is the basket now?',
    options:['9 kg','8 kg','10 kg','7 kg'],
    answer:'9 kg',
    hint:'7 + 2 = ?',
    explanation:'7 kg + 2 kg = <b>9 kg</b>.' }),

  makeMCQ({ id:'g2mth-msr-035', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'An apple weighs about ___ grams (g). 1000 g = 1 kg. Is one apple heavier than 1 kg?',
    options:['No — one apple is much less than 1 kg','Yes — one apple weighs more than 1 kg','Yes — one apple weighs exactly 1 kg','cannot tell'],
    answer:'No — one apple is much less than 1 kg',
    hint:'A typical apple weighs about 150 g, and 1000 g = 1 kg.',
    explanation:'One apple weighs about 150 g, which is <b>much less than 1 kg (1000 g)</b>.' }),

  makeMCQ({ id:'g2mth-msr-036', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'Which object would you weigh in kilograms?',
    options:['a bag of rice','a feather','a grain of sand','a pencil'],
    answer:'a bag of rice',
    hint:'Kilograms are used for heavier objects.',
    explanation:'We weigh <b>a bag of rice</b> in kilograms because it is heavy.' }),

  makeMCQ({ id:'g2mth-msr-037', chapterId:'g2mth-measurement', difficulty:2, subsection:'mass_kg',
    question:'Rani has 10 kg of potatoes. She uses 4 kg for cooking. How many kg are left?',
    options:['6 kg','5 kg','7 kg','4 kg'],
    answer:'6 kg',
    hint:'10 − 4 = ?',
    explanation:'10 kg − 4 kg = <b>6 kg</b>.' }),

  makeMCQ({ id:'g2mth-msr-038', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'Dev\'s school bag is ___ kg. What is the lightest sensible answer for a school bag?',
    options:['3 kg','300 kg','0.003 kg','3000 kg'],
    answer:'3 kg',
    hint:'A school bag is heavier than a feather but much lighter than a car.',
    explanation:'A school bag weighs about <b>3 kg</b>.' }),

  makeMCQ({ id:'g2mth-msr-039', chapterId:'g2mth-measurement', difficulty:2, subsection:'mass_kg',
    question:'Priya buys 3 kg of tomatoes and 5 kg of onions. What is the total mass?',
    options:['8 kg','7 kg','9 kg','6 kg'],
    answer:'8 kg',
    hint:'3 + 5 = ?',
    explanation:'3 kg + 5 kg = <b>8 kg</b>.' }),

  makeMCQ({ id:'g2mth-msr-040', chapterId:'g2mth-measurement', difficulty:1, subsection:'mass_kg',
    question:'Which sentence is true?',
    options:['9 kg > 7 kg','7 kg > 9 kg','7 kg = 9 kg','cannot tell'],
    answer:'9 kg > 7 kg',
    hint:'Is 9 greater than 7?',
    explanation:'<b>9 kg &gt; 7 kg</b> (9 is greater than 7).' }),

// ── capacity_litres (20 questions) ────────────────────────────────────────────

  makeMCQ({ id:'g2mth-msr-041', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'A large bottle holds 2 ___.',
    options:['L','kg','m','cm'],
    answer:'L',
    hint:'We measure liquids in litres.',
    explanation:'A large bottle holds 2 <b>litres (L)</b>.' }),

  makeMCQ({ id:'g2mth-msr-042', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'Which holds more: a 5 L bucket or a 1 L bottle?',
    options:['5 L bucket','1 L bottle','same','cannot tell'],
    answer:'5 L bucket',
    hint:'Compare the numbers of litres.',
    explanation:'5 L > 1 L, so the <b>5 L bucket</b> holds more.' }),

  makeMCQ({ id:'g2mth-msr-043', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Mia uses 3 L of water to wash her clothes. Priya uses 5 L. How much more does Priya use?',
    options:['2 L','8 L','1 L','3 L'],
    answer:'2 L',
    hint:'5 − 3 = ?',
    explanation:'5 L − 3 L = <b>2 L</b> more.' }),

  makeMCQ({ id:'g2mth-msr-044', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'What unit do we use to measure how much water is in a bucket?',
    options:['litres (L)','kilograms (kg)','centimetres (cm)','metres (m)'],
    answer:'litres (L)',
    hint:'Litres are used for liquids.',
    explanation:'We use <b>litres (L)</b> to measure liquids like water.' }),

  makeMCQ({ id:'g2mth-msr-045', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'A swimming pool holds ___ litres of water.',
    options:['thousands of litres','2 L','10 L','1 L'],
    answer:'thousands of litres',
    hint:'A swimming pool is very large.',
    explanation:'A swimming pool holds <b>thousands of litres</b> of water.' }),

  makeMCQ({ id:'g2mth-msr-046', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Dev fills a jug with 4 L of juice. He pours out 2 L. How much is left?',
    options:['2 L','3 L','1 L','4 L'],
    answer:'2 L',
    hint:'4 − 2 = ?',
    explanation:'4 L − 2 L = <b>2 L</b>.' }),

  makeMCQ({ id:'g2mth-msr-047', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Rani pours 3 L from one bottle and 4 L from another. How many litres in total?',
    options:['7 L','6 L','8 L','5 L'],
    answer:'7 L',
    hint:'3 + 4 = ?',
    explanation:'3 L + 4 L = <b>7 L</b>.' }),

  makeMCQ({ id:'g2mth-msr-048', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'A teacup holds about ___ of liquid.',
    options:['less than 1 L','5 L','10 L','20 L'],
    answer:'less than 1 L',
    hint:'A teacup is much smaller than a 1-litre bottle.',
    explanation:'A teacup holds <b>less than 1 litre</b>.' }),

  makeMCQ({ id:'g2mth-msr-049', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Priya has 10 L of water. She uses 6 L to water plants. How many litres are left?',
    options:['4 L','5 L','3 L','6 L'],
    answer:'4 L',
    hint:'10 − 6 = ?',
    explanation:'10 L − 6 L = <b>4 L</b>.' }),

  makeMCQ({ id:'g2mth-msr-050', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'Which holds more liquid: a bathtub or a teacup?',
    options:['a bathtub','a teacup','they hold the same','cannot tell'],
    answer:'a bathtub',
    hint:'A bathtub is much bigger than a teacup.',
    explanation:'<b>A bathtub</b> holds far more liquid than a teacup.' }),

  makeMCQ({ id:'g2mth-msr-051', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Raj fills 3 bottles, each holding 2 L. How many litres of water does he have?',
    options:['6 L','5 L','9 L','8 L'],
    answer:'6 L',
    hint:'3 × 2 = ?',
    explanation:'3 × 2 L = <b>6 L</b>.' }),

  makeMCQ({ id:'g2mth-msr-052', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'What tool do we use to measure litres?',
    options:['a measuring jug','a ruler','a scale','a thermometer'],
    answer:'a measuring jug',
    hint:'You pour liquid into this to see how many litres.',
    explanation:'We use <b>a measuring jug</b> to measure litres.' }),

  makeMCQ({ id:'g2mth-msr-053', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Nadia has 8 L of juice for a party. The children drink 5 L. How much is left?',
    options:['3 L','4 L','2 L','5 L'],
    answer:'3 L',
    hint:'8 − 5 = ?',
    explanation:'8 L − 5 L = <b>3 L</b>.' }),

  makeMCQ({ id:'g2mth-msr-054', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'A bottle of water at school is usually about ___ litre.',
    options:['1','10','100','0.001'],
    answer:'1',
    hint:'A typical drinking bottle is about 1 litre.',
    explanation:'A school drinking bottle is usually about <b>1 litre (L)</b>.' }),

  makeMCQ({ id:'g2mth-msr-055', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Mia has two jugs: one holds 3 L and the other holds 7 L. How much do they hold together?',
    options:['10 L','9 L','11 L','8 L'],
    answer:'10 L',
    hint:'3 + 7 = ?',
    explanation:'3 L + 7 L = <b>10 L</b>.' }),

  makeMCQ({ id:'g2mth-msr-056', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'Which holds the least: a 2 L bottle, a 5 L bucket, or a 1 L carton?',
    options:['1 L carton','2 L bottle','5 L bucket','they are all the same'],
    answer:'1 L carton',
    hint:'Compare 1, 2, and 5. Which is the smallest?',
    explanation:'<b>1 L</b> is the smallest number, so the 1 L carton holds the least.' }),

  makeMCQ({ id:'g2mth-msr-057', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Dev has 5 L. He pours 3 L into one container and the rest into another. How much is in the second container?',
    options:['2 L','3 L','1 L','4 L'],
    answer:'2 L',
    hint:'5 − 3 = ?',
    explanation:'5 L − 3 L = <b>2 L</b> in the second container.' }),

  makeMCQ({ id:'g2mth-msr-058', chapterId:'g2mth-measurement', difficulty:1, subsection:'capacity_litres',
    question:'We measure petrol (fuel) in ___.',
    options:['litres (L)','kilograms (kg)','metres (m)','centimetres (cm)'],
    answer:'litres (L)',
    hint:'Petrol is a liquid. Liquids are measured in litres.',
    explanation:'Petrol is a liquid, so we measure it in <b>litres (L)</b>.' }),

  makeMCQ({ id:'g2mth-msr-059', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Priya needs 9 L of water to fill a tank. She has poured in 4 L. How many litres more does she need?',
    options:['5 L','4 L','6 L','3 L'],
    answer:'5 L',
    hint:'9 − 4 = ?',
    explanation:'9 L − 4 L = <b>5 L</b> more needed.' }),

  makeMCQ({ id:'g2mth-msr-060', chapterId:'g2mth-measurement', difficulty:2, subsection:'capacity_litres',
    question:'Raj pours 2 L into 4 glasses equally. How many litres in each glass?',
    options:['½ L','1 L','¼ L','2 L'],
    answer:'½ L',
    hint:'2 L shared equally into 4 glasses. Half of 1 L.',
    explanation:'2 L ÷ 4 = <b>½ L</b> (half a litre) in each glass.' })
);

})();
