'use strict';
(function () {

// ── days_months (20 questions) ────────────────────────────────────────────────

STATIC_QUESTIONS.push(
  makeMCQ({ id:'g2mth-tim-001', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'How many days are in a week?',
    options:['7','6','8','5'],
    answer:'7',
    hint:'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.',
    explanation:'There are <b>7</b> days in a week.' }),

  makeMCQ({ id:'g2mth-tim-002', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which day comes after Wednesday?',
    options:['Thursday','Tuesday','Friday','Monday'],
    answer:'Thursday',
    hint:'The order is: Monday, Tuesday, Wednesday, ___.',
    explanation:'After Wednesday comes <b>Thursday</b>.' }),

  makeMCQ({ id:'g2mth-tim-003', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which month comes after March?',
    options:['April','February','May','January'],
    answer:'April',
    hint:'The order is: January, February, March, ___.',
    explanation:'After March comes <b>April</b>.' }),

  makeMCQ({ id:'g2mth-tim-004', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'How many months are in a year?',
    options:['12','10','11','13'],
    answer:'12',
    hint:'Count the months from January to December.',
    explanation:'There are <b>12</b> months in a year.' }),

  makeMCQ({ id:'g2mth-tim-005', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which is the 6th month of the year?',
    options:['June','May','July','April'],
    answer:'June',
    hint:'Jan(1), Feb(2), Mar(3), Apr(4), May(5), ___(6).',
    explanation:'The 6th month is <b>June</b>.' }),

  makeMCQ({ id:'g2mth-tim-006', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which day comes before Friday?',
    options:['Thursday','Saturday','Wednesday','Monday'],
    answer:'Thursday',
    hint:'The order is: Wednesday, Thursday, Friday.',
    explanation:'Before Friday comes <b>Thursday</b>.' }),

  makeMCQ({ id:'g2mth-tim-007', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which month comes before October?',
    options:['September','November','August','December'],
    answer:'September',
    hint:'The order is: ..., September, October, November, ...',
    explanation:'Before October comes <b>September</b>.' }),

  makeMCQ({ id:'g2mth-tim-008', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'What is the last day of the week?',
    options:['Sunday','Saturday','Friday','Monday'],
    answer:'Sunday',
    hint:'The week goes from Monday to Sunday.',
    explanation:'The last day of the week is <b>Sunday</b>.' }),

  makeMCQ({ id:'g2mth-tim-009', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'What is the first month of the year?',
    options:['January','February','December','March'],
    answer:'January',
    hint:'The year starts with this month.',
    explanation:'The first month of the year is <b>January</b>.' }),

  makeMCQ({ id:'g2mth-tim-010', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'What is the last month of the year?',
    options:['December','November','January','October'],
    answer:'December',
    hint:'The year ends with this month.',
    explanation:'The last month of the year is <b>December</b>.' }),

  makeMCQ({ id:'g2mth-tim-011', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which day comes after Sunday?',
    options:['Monday','Saturday','Friday','Tuesday'],
    answer:'Monday',
    hint:'After Sunday, the new week begins.',
    explanation:'After Sunday comes <b>Monday</b> — the start of the next week.' }),

  makeMCQ({ id:'g2mth-tim-012', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which month comes after December?',
    options:['January','November','February','March'],
    answer:'January',
    hint:'December is the last month. What comes next?',
    explanation:'After December comes <b>January</b> — the start of the new year.' }),

  makeMCQ({ id:'g2mth-tim-013', chapterId:'g2mth-time', difficulty:2, subsection:'days_months',
    question:'Rani goes to school Monday to Friday. How many days does she go to school in a week?',
    options:['5','6','7','4'],
    answer:'5',
    hint:'Count: Monday, Tuesday, Wednesday, Thursday, Friday.',
    explanation:'Monday, Tuesday, Wednesday, Thursday, Friday = <b>5</b> school days.' }),

  makeMCQ({ id:'g2mth-tim-014', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which is the 12th month of the year?',
    options:['December','November','October','January'],
    answer:'December',
    hint:'The 12th and last month of the year.',
    explanation:'The 12th month is <b>December</b>.' }),

  makeMCQ({ id:'g2mth-tim-015', chapterId:'g2mth-time', difficulty:2, subsection:'days_months',
    question:'Today is Tuesday. What day was yesterday?',
    options:['Monday','Wednesday','Sunday','Thursday'],
    answer:'Monday',
    hint:'The day before Tuesday.',
    explanation:'The day before Tuesday is <b>Monday</b>.' }),

  makeMCQ({ id:'g2mth-tim-016', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which month has only 28 (or 29) days?',
    options:['February','January','March','April'],
    answer:'February',
    hint:'It is the shortest month of the year.',
    explanation:'<b>February</b> has 28 days (or 29 days in a leap year).' }),

  makeMCQ({ id:'g2mth-tim-017', chapterId:'g2mth-time', difficulty:2, subsection:'days_months',
    question:'Dev\'s birthday is in the 3rd month. In which month is his birthday?',
    options:['March','February','April','January'],
    answer:'March',
    hint:'Jan(1), Feb(2), Mar(3).',
    explanation:'The 3rd month is <b>March</b>.' }),

  makeMCQ({ id:'g2mth-tim-018', chapterId:'g2mth-time', difficulty:2, subsection:'days_months',
    question:'Today is Friday. What day will it be in 2 days?',
    options:['Sunday','Saturday','Monday','Thursday'],
    answer:'Sunday',
    hint:'Friday → Saturday (1 day) → ___ (2 days).',
    explanation:'Friday + 1 day = Saturday, + 1 more = <b>Sunday</b>.' }),

  makeMCQ({ id:'g2mth-tim-019', chapterId:'g2mth-time', difficulty:1, subsection:'days_months',
    question:'Which month comes after July?',
    options:['August','June','September','October'],
    answer:'August',
    hint:'June, July, August...',
    explanation:'After July comes <b>August</b>.' }),

  makeMCQ({ id:'g2mth-tim-020', chapterId:'g2mth-time', difficulty:2, subsection:'days_months',
    question:'How many days are there from Monday to Friday (including both days)?',
    options:['5','4','6','3'],
    answer:'5',
    hint:'Count: Monday(1), Tuesday(2), Wednesday(3), Thursday(4), Friday(5).',
    explanation:'Monday to Friday inclusive = <b>5</b> days.' }),

// ── oclock_halfpast (20 questions) ────────────────────────────────────────────

  makeMCQ({ id:'g2mth-tim-021', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'When a clock shows 3 o\'clock, where does the minute hand point?',
    options:['12','3','6','9'],
    answer:'12',
    hint:'At every o\'clock time, the minute hand is always pointing up.',
    explanation:'At any o\'clock time, the minute hand points to <b>12</b>.' }),

  makeMCQ({ id:'g2mth-tim-022', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'The clock shows half past 4. The hour hand is between ___ and ___.',
    options:['4 and 5','3 and 4','5 and 6','2 and 3'],
    answer:'4 and 5',
    hint:'At half past, the hour hand is halfway between two numbers.',
    explanation:'At half past 4, the hour hand is halfway between <b>4 and 5</b>.' }),

  makeMCQ({ id:'g2mth-tim-023', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'How many minutes are in half an hour?',
    options:['30','60','15','45'],
    answer:'30',
    hint:'One hour = 60 minutes. Half of 60 = ?',
    explanation:'Half of 60 minutes = <b>30 minutes</b>.' }),

  makeMCQ({ id:'g2mth-tim-024', chapterId:'g2mth-time', difficulty:2, subsection:'oclock_halfpast',
    question:'School starts at 8 o\'clock. The clock now shows 7 o\'clock. How long until school starts?',
    options:['1 hour','2 hours','30 minutes','half an hour'],
    answer:'1 hour',
    hint:'From 7 o\'clock to 8 o\'clock is how long?',
    explanation:'From 7 o\'clock to 8 o\'clock is <b>1 hour</b>.' }),

  makeMCQ({ id:'g2mth-tim-025', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'At half past, where does the minute hand point?',
    options:['6','12','3','9'],
    answer:'6',
    hint:'At half past, the minute hand has gone halfway round the clock.',
    explanation:'At half past any hour, the minute hand points to <b>6</b>.' }),

  makeMCQ({ id:'g2mth-tim-026', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'How many minutes are in one hour?',
    options:['60','30','24','12'],
    answer:'60',
    hint:'A full hour has 60 minutes.',
    explanation:'There are <b>60 minutes</b> in one hour.' }),

  makeMCQ({ id:'g2mth-tim-027', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'The hour hand points to 7 and the minute hand points to 12. What time is it?',
    options:["7 o'clock","half past 7","7:30","half past 12"],
    answer:"7 o'clock",
    hint:'Minute hand at 12 = o\'clock.',
    explanation:'Hour hand at 7, minute hand at 12 = <b>7 o\'clock</b>.' }),

  makeMCQ({ id:'g2mth-tim-028', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'The hour hand is between 2 and 3, and the minute hand is at 6. What time is it?',
    options:["half past 2","2 o'clock","half past 3","3 o'clock"],
    answer:"half past 2",
    hint:'Minute hand at 6 = half past. Hour hand between 2 and 3.',
    explanation:'Minute hand at 6 means half past. Hour hand between 2 and 3 = <b>half past 2</b>.' }),

  makeMCQ({ id:'g2mth-tim-029', chapterId:'g2mth-time', difficulty:2, subsection:'oclock_halfpast',
    question:'Rani starts reading at 2 o\'clock and reads for 1 hour. What time does she finish?',
    options:["3 o'clock","half past 2","1 o'clock","4 o'clock"],
    answer:"3 o'clock",
    hint:'2 o\'clock + 1 hour = ?',
    explanation:'2 o\'clock + 1 hour = <b>3 o\'clock</b>.' }),

  makeMCQ({ id:'g2mth-tim-030', chapterId:'g2mth-time', difficulty:2, subsection:'oclock_halfpast',
    question:'Dev arrives at 4 o\'clock. He leaves at half past 4. How long did he stay?',
    options:['30 minutes','1 hour','15 minutes','45 minutes'],
    answer:'30 minutes',
    hint:'From 4 o\'clock to half past 4 is half an hour.',
    explanation:'From 4 o\'clock to half past 4 = <b>30 minutes</b>.' }),

  makeMCQ({ id:'g2mth-tim-031', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'Which hand is the minute hand on a clock?',
    options:['The long hand','The short hand','Both hands','Neither hand'],
    answer:'The long hand',
    hint:'The minute hand is the longer of the two main clock hands.',
    explanation:'The <b>long hand</b> is the minute hand.' }),

  makeMCQ({ id:'g2mth-tim-032', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'Which hand is the hour hand on a clock?',
    options:['The short hand','The long hand','Both hands','Neither hand'],
    answer:'The short hand',
    hint:'The hour hand is shorter than the minute hand.',
    explanation:'The <b>short hand</b> is the hour hand.' }),

  makeMCQ({ id:'g2mth-tim-033', chapterId:'g2mth-time', difficulty:2, subsection:'oclock_halfpast',
    question:'Mia eats breakfast at half past 7. What time does she eat breakfast?',
    options:['7:30','7:00','8:00','8:30'],
    answer:'7:30',
    hint:'Half past 7 in digital time is 7:30.',
    explanation:'Half past 7 = <b>7:30</b>.' }),

  makeMCQ({ id:'g2mth-tim-034', chapterId:'g2mth-time', difficulty:2, subsection:'oclock_halfpast',
    question:'School finishes at 3 o\'clock. Priya stays for half an hour extra for practice. What time does she leave?',
    options:["half past 3","4 o'clock","3 o'clock","half past 2"],
    answer:"half past 3",
    hint:'3 o\'clock + 30 minutes = ?',
    explanation:'3 o\'clock + 30 minutes = <b>half past 3</b>.' }),

  makeMCQ({ id:'g2mth-tim-035', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'How many o\'clock times are there in one full day?',
    options:['24','12','2','60'],
    answer:'24',
    hint:'There are 12 in the morning (am) and 12 in the afternoon/evening (pm).',
    explanation:'In a full day there are <b>24</b> o\'clock times (12 am + 12 pm).' }),

  makeMCQ({ id:'g2mth-tim-036', chapterId:'g2mth-time', difficulty:2, subsection:'oclock_halfpast',
    question:'Raj\'s lesson starts at 9 o\'clock. It lasts 1 hour. When does it finish?',
    options:["10 o'clock","half past 9","8 o'clock","11 o'clock"],
    answer:"10 o'clock",
    hint:'9 o\'clock + 1 hour = ?',
    explanation:'9 o\'clock + 1 hour = <b>10 o\'clock</b>.' }),

  makeMCQ({ id:'g2mth-tim-037', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'At 6 o\'clock, where does the hour hand point?',
    options:['6','12','3','9'],
    answer:'6',
    hint:'The hour hand points to the number that matches the hour.',
    explanation:'At 6 o\'clock, the hour hand points to <b>6</b>.' }),

  makeMCQ({ id:'g2mth-tim-038', chapterId:'g2mth-time', difficulty:2, subsection:'oclock_halfpast',
    question:'Nadia wakes up at 6 o\'clock and eats breakfast at half past 6. How many minutes later does she eat?',
    options:['30 minutes','1 hour','15 minutes','45 minutes'],
    answer:'30 minutes',
    hint:'Half past 6 is 30 minutes after 6 o\'clock.',
    explanation:'From 6 o\'clock to half past 6 = <b>30 minutes</b>.' }),

  makeMCQ({ id:'g2mth-tim-039', chapterId:'g2mth-time', difficulty:1, subsection:'oclock_halfpast',
    question:'In 12:30, what does the 30 tell us?',
    options:['30 minutes past 12','30 hours','the year','the day'],
    answer:'30 minutes past 12',
    hint:'In digital time, the number after the colon (:) is the minutes.',
    explanation:'12:30 means <b>30 minutes past 12</b> = half past 12.' }),

  makeMCQ({ id:'g2mth-tim-040', chapterId:'g2mth-time', difficulty:2, subsection:'oclock_halfpast',
    question:'Dev finishes lunch at half past 1. He plays outside for 30 minutes. At what time does he stop playing?',
    options:["2 o'clock","half past 2","1 o'clock","3 o'clock"],
    answer:"2 o'clock",
    hint:'Half past 1 = 1:30. Add 30 minutes.',
    explanation:'1:30 + 30 minutes = 2:00 = <b>2 o\'clock</b>.' }),

// ── calendar (20 questions) ───────────────────────────────────────────────────

  makeMCQ({ id:'g2mth-tim-041', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'How many days are in most months?',
    options:['30 or 31','28','7','12'],
    answer:'30 or 31',
    hint:'Most months have 30 or 31 days. Only February is different.',
    explanation:'Most months have <b>30 or 31 days</b>.' }),

  makeMCQ({ id:'g2mth-tim-042', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'February usually has ___ days.',
    options:['28','30','31','29'],
    answer:'28',
    hint:'February is the shortest month.',
    explanation:'February usually has <b>28 days</b> (29 in a leap year).' }),

  makeMCQ({ id:'g2mth-tim-043', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'If today is Monday the 5th, what is the date next Monday?',
    options:['12th','6th','11th','13th'],
    answer:'12th',
    hint:'A week has 7 days. 5 + 7 = ?',
    explanation:'5 + 7 = <b>12th</b>. One week later is the 12th.' }),

  makeMCQ({ id:'g2mth-tim-044', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'How many weeks are in a month?',
    options:['about 4','7','12','2'],
    answer:'about 4',
    hint:'A month has about 30 days. 30 ÷ 7 ≈ ?',
    explanation:'A month has about <b>4 weeks</b>.' }),

  makeMCQ({ id:'g2mth-tim-045', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'Which months have 31 days? Which of these is correct?',
    options:['January has 31 days','February has 31 days','April has 31 days','June has 31 days'],
    answer:'January has 31 days',
    hint:'January, March, May, July, August, October, December all have 31 days.',
    explanation:'<b>January</b> has 31 days.' }),

  makeMCQ({ id:'g2mth-tim-046', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'Rani\'s birthday is on the 20th of January. Today is the 10th of January. How many days until her birthday?',
    options:['10 days','20 days','5 days','15 days'],
    answer:'10 days',
    hint:'20 − 10 = ?',
    explanation:'20 − 10 = <b>10 days</b> until Rani\'s birthday.' }),

  makeMCQ({ id:'g2mth-tim-047', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'How many days are in one week?',
    options:['7','6','8','5'],
    answer:'7',
    hint:'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.',
    explanation:'There are <b>7</b> days in one week.' }),

  makeMCQ({ id:'g2mth-tim-048', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'Dev has a holiday starting on July 1st. It lasts 14 days. On what date does the holiday end?',
    options:['July 14th','July 15th','July 7th','June 30th'],
    answer:'July 14th',
    hint:'1 + 14 − 1 = 14 (the last day of a 14-day holiday starting on the 1st is the 14th).',
    explanation:'A 14-day holiday starting July 1st ends on <b>July 14th</b>.' }),

  makeMCQ({ id:'g2mth-tim-049', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'There are 4 Sundays in a month. How many days is that?',
    options:['28 days','7 days','4 days','21 days'],
    answer:'28 days',
    hint:'4 weeks × 7 days = ?',
    explanation:'4 Sundays means 4 weeks = 4 × 7 = <b>28 days</b>.' }),

  makeMCQ({ id:'g2mth-tim-050', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'Which month comes between August and October?',
    options:['September','July','November','June'],
    answer:'September',
    hint:'August, ___, October.',
    explanation:'Between August and October is <b>September</b>.' }),

  makeMCQ({ id:'g2mth-tim-051', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'Mia\'s school trip is on the 15th. Today is the 9th. How many days until the trip?',
    options:['6 days','5 days','7 days','4 days'],
    answer:'6 days',
    hint:'15 − 9 = ?',
    explanation:'15 − 9 = <b>6 days</b> until the trip.' }),

  makeMCQ({ id:'g2mth-tim-052', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'How many months are in half a year?',
    options:['6','3','4','12'],
    answer:'6',
    hint:'Half of 12 months = ?',
    explanation:'Half of 12 = <b>6 months</b>.' }),

  makeMCQ({ id:'g2mth-tim-053', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'Priya goes swimming every Saturday. How many times does she swim in 4 weeks?',
    options:['4','7','8','3'],
    answer:'4',
    hint:'1 Saturday per week × 4 weeks.',
    explanation:'1 × 4 = <b>4</b> times.' }),

  makeMCQ({ id:'g2mth-tim-054', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'Today is March 28th. What is the date in 5 days? (March has 31 days.)',
    options:['April 2nd','March 33rd','April 5th','March 23rd'],
    answer:'April 2nd',
    hint:'March 28 + 5 days: 28+3 = March 31, then 2 more days = April 2nd.',
    explanation:'March 28 + 3 days = March 31. + 2 more days = <b>April 2nd</b>.' }),

  makeMCQ({ id:'g2mth-tim-055', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'Which month is the 9th month of the year?',
    options:['September','August','October','November'],
    answer:'September',
    hint:'Jan(1), Feb(2), Mar(3), Apr(4), May(5), Jun(6), Jul(7), Aug(8), ___(9).',
    explanation:'The 9th month is <b>September</b>.' }),

  makeMCQ({ id:'g2mth-tim-056', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'Raj practises football 3 times a week. How many times does he practise in 3 weeks?',
    options:['9','6','12','3'],
    answer:'9',
    hint:'3 times × 3 weeks = ?',
    explanation:'3 × 3 = <b>9</b> times.' }),

  makeMCQ({ id:'g2mth-tim-057', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'How many days are in the month of April?',
    options:['30','31','28','29'],
    answer:'30',
    hint:'April, June, September, November all have 30 days.',
    explanation:'April has <b>30</b> days.' }),

  makeMCQ({ id:'g2mth-tim-058', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'Nadia visits her grandmother every month. How many visits does she make in 6 months?',
    options:['6','12','4','8'],
    answer:'6',
    hint:'1 visit per month × 6 months.',
    explanation:'1 × 6 = <b>6</b> visits.' }),

  makeMCQ({ id:'g2mth-tim-059', chapterId:'g2mth-time', difficulty:2, subsection:'calendar',
    question:'If today is Monday the 2nd, what day is the 9th?',
    options:['Monday','Tuesday','Sunday','Saturday'],
    answer:'Monday',
    hint:'9 − 2 = 7 days later. 7 days = 1 full week, so the same day.',
    explanation:'2nd is Monday. 9th = 2 + 7 days = same day = <b>Monday</b>.' }),

  makeMCQ({ id:'g2mth-tim-060', chapterId:'g2mth-time', difficulty:1, subsection:'calendar',
    question:'Which two months come after October?',
    options:['November and December','September and August','December and January','March and April'],
    answer:'November and December',
    hint:'October is the 10th month. What are the 11th and 12th?',
    explanation:'After October (10th) come <b>November (11th) and December (12th)</b>.' })
);

})();
