'use strict';
// Grade 6 English - evidence selection and language analysis in short extracts.
(function () {
  const add = (section, rows) => rows.forEach((r, i) => STATIC_QUESTIONS.push(makeMCQ({
    id: `g6eng-el-${section}-${String(i + 1).padStart(2, '0')}`,
    chapterId: 'g6eng-comprehension', subsection: section, difficulty: 3,
    question: r[0], options: r.slice(1, 5), answer: r[1],
    hint: section === 'evidence' ? 'Choose the detail that most directly proves the claim.' : 'Consider the image, sound, mood or pace created by the writer’s words.',
    explanation: r[5]
  })));

  add('evidence', [
    ['Read: “Amir checked the compass twice, compared the trail with his map and then led the group east.” Which detail best proves Amir was careful?','He checked the compass twice.','He walked east.','He was in a group.','He carried a map.','Checking twice is the strongest direct evidence of carefulness.'],
    ['Read: “Every chair was occupied and families stood along the back wall.” Which evidence shows the event was popular?','Every chair was occupied and people were standing.','The room had chairs.','Families attended together.','There was a back wall.','A full room with people standing strongly supports popularity.'],
    ['Read: “Lina whispered, avoided looking up and twisted the corner of her page.” Which detail best supports that Lina felt nervous?','She twisted the corner of her page.','She knew an answer.','She had a page.','She was indoors.','Fidgeting with the page is behavioural evidence of nervousness.'],
    ['Read: “The stream, once clear enough to reveal every pebble, now carried plastic bottles and brown foam.” What proves pollution increased?','The water now carries bottles and brown foam.','Pebbles lie below the water.','The stream is flowing.','The stream existed before.','Plastic and brown foam directly indicate worsening pollution.'],
    ['Read: “Noor arrived before the library opened and had already listed the books she needed.” What best proves she was prepared?','She had already listed the books she needed.','The library had opening hours.','She wanted books.','She arrived at a building.','The completed list is direct evidence of advance preparation.'],
    ['Read: “The puppy backed away, tucked its tail and hid behind Ravi.” Which detail most strongly shows fear?','It tucked its tail and hid.','It stood behind Ravi.','It was a puppy.','It moved backwards.','A tucked tail combined with hiding strongly signals fear.'],
    ['Read: “Although two designs collapsed, the team rebuilt the model and tested it again.” What proves perseverance?','They rebuilt and tested after failures.','They made two designs.','The object was a model.','They worked in a team.','Trying again after repeated failure directly demonstrates perseverance.'],
    ['Read: “The notice uses large red letters, a warning symbol and the words ‘Keep Away’.” What best shows urgency?','Large red letters and a warning symbol','The notice contains words.','The phrase has two words.','The notice is displayed.','Visual emphasis and a warning sign demand immediate attention.'],
    ['Read: “Maya divided her last sandwich equally and gave half to her brother.” What proves generosity?','She shared half of her last sandwich.','The sandwich was divided.','Her brother was present.','The food was a sandwich.','Willingly sharing her final sandwich directly shows generosity.'],
    ['Read: “Shutters rattled, branches bent low and loose bins rolled across the road.” What proves the wind was strong?','Branches bent and bins rolled across the road.','Houses had shutters.','Trees grew nearby.','The bins were loose.','Bent branches and moving bins are strong physical effects of wind.'],
    ['Read: “After the repair, the tap stayed dry and the water meter stopped rising overnight.” What suggests the leak was fixed?','The tap stayed dry and the meter stopped rising.','A repair happened.','The building had a meter.','Night passed.','Both observations show that water was no longer escaping.'],
    ['Read: “The article names sources, gives dates and links claims to survey data.” What best supports its reliability?','It identifies sources and provides data.','It is an article.','It contains dates.','It discusses a survey.','Traceable sources and evidence make factual claims easier to verify.'],
    ['Read: “Jai interrupted twice, ignored the chairperson and spoke over others.” What proves he was discourteous?','He continued speaking over others.','He attended the meeting.','There was a chairperson.','Other people spoke.','Speaking over others after a request to stop is directly discourteous.'],
    ['Read: “Within ten minutes, dark clouds covered the sky and the temperature dropped.” What proves the change was rapid?','The changes happened within ten minutes.','Clouds covered the sky.','Temperature was measured.','The sky became dark.','The short ten-minute interval directly establishes speed.'],
    ['Read: “The new route is two kilometres shorter and avoids the steep hill.” What best proves it is easier for walkers?','It avoids the steep hill.','It is two kilometres long.','It is called a route.','Walkers may use it.','Avoiding a steep climb most directly reduces physical effort.'],
    ['Read: “Seedlings by the window grew 6 cm; those in a cupboard grew 1 cm and looked pale.” What supports the importance of light?','The lit seedlings grew more and looked healthier.','Both groups were seedlings.','Growth was measured.','One group was in a cupboard.','The contrasting growth and colour link light with healthy development.'],
    ['Read: “Before answering, Sara reread the paragraph and underlined the sentence with the date.” What shows she used a reading strategy?','She reread and underlined relevant information.','The paragraph had a date.','She eventually answered.','The text used sentences.','Rereading and marking evidence are deliberate comprehension strategies.']
  ]);

  add('language', [
    ['Read: “The waves clawed at the sea wall.” What effect does “clawed” create?','It makes the waves seem aggressive and threatening.','It shows the wall has fur.','It proves the sea is calm.','It measures each wave.','The verb personifies the waves as a violent attacker.'],
    ['Read: “A ribbon of road curled through the hills.” What does the metaphor suggest?','The road is long, narrow and winding.','The road is made of cloth.','The hills are flat.','The road ends suddenly.','The shape of a loose ribbon conveys a narrow, winding road.'],
    ['Read: “Tick, tick, tick-the clock seemed louder every second.” What is the effect of repetition?','It builds tension and awareness of passing time.','It proves the clock is broken.','It describes a smell.','It explains clockmaking.','Repeated ticking slows the moment and increases suspense.'],
    ['Read: “The market burst into colour at sunrise.” What does “burst” suggest?','Colour appeared suddenly and vividly.','The market was destroyed.','Every stall closed.','Only one colour appeared.','“Burst” presents the change as quick, energetic and vivid.'],
    ['Read: “He carried a mountain of books.” Why is the hyperbole effective?','It emphasises a very large number of books.','It proves a mountain was carried.','It shows the books were weightless.','It names where books were printed.','The impossible exaggeration stresses the size of the load.'],
    ['Read: “The room fell silent; even the fan seemed to hold its breath.” What mood is created?','tense anticipation','cheerful celebration','careless boredom','peaceful sleep','The held-breath personification creates a tense pause.'],
    ['Read: “Golden light spilled across the floor.” What effect does “spilled” create?','It shows light spreading freely over a surface.','It means a bottle broke.','It makes the room darker.','It measures brightness.','The liquid metaphor makes the light appear to flow and spread.'],
    ['Read: “The door groaned open.” What does “groaned” suggest?','A long, strained creaking sound','Silent and rapid movement','A clear spoken sentence','A newly oiled hinge','The verb suggests slow movement with a low, strained sound.'],
    ['Read: “Unlike the noisy harbour, the cove whispered beneath the cliffs.” What does the contrast emphasise?','the cove’s quietness','both places being loud','the cliffs speaking','how harbours are built','Contrasting noise with a whisper makes the cove especially calm.'],
    ['Read: “One by one, the lights vanished.” Why use a short sentence?','To make the disappearance feel sudden and final.','To give a scientific explanation.','To introduce many characters.','To show increasing brightness.','The brief sentence gives the event sharp, decisive impact.'],
    ['Read: “The tiny boat bobbed on the enormous grey sea.” What does the size contrast emphasise?','the boat’s vulnerability','the boat’s speed','the sailor’s age','the sea’s temperature','“Tiny” against “enormous” makes the boat seem exposed and powerless.'],
    ['Read: “Fresh bread perfumed the narrow street.” What effect does “perfumed” create?','It presents the smell as pleasant and spreading.','It proves perfume covered the bread.','It makes the bread rotten.','It describes the bread’s shape.','“Perfumed” suggests an appealing scent filling the air.'],
    ['Read: “Run!” Why is the one-word sentence effective in an emergency?','It creates urgency and rapid pace.','It slows the scene.','It gives background history.','It makes danger unimportant.','The abrupt imperative demands immediate action.'],
    ['Read: “Hope flickered like a candle in the storm.” What does the simile suggest?','Hope is weak but still present.','Hope is a real candle.','The storm has ended.','The character is certain.','A fragile flame represents hope surviving despite danger.'],
    ['Read: “The path swallowed our footprints.” What does the personification suggest?','The footprints quickly disappeared.','The path ate the walkers.','Nobody touched the ground.','The path grew wider.','“Swallowed” vividly suggests the marks were covered or erased.']
  ]);
})();
