'use strict';
// Grade 1 French — top-up to reach 20 per subsection.
// ch01 (co): discrimination_sons +8 (039-046), comprehension_messages +7 (047-053), vocabulaire_oral +7 (054-060)
// ch02 (eo): comptines_chansons +7 (039-045), conversation_simple +7 (046-052), description_images +8 (053-060)
// ch03 (lec): conscience_phonique +7 (039-045), lettres_sons +8 (046-053), mots_simples +7 (054-060)
// ch04 (ecr): lettres_minuscules +7 (033-039), copie_mots +10 (040-049), phrases_simples +11 (050-060)
// ch05 (grm): noms_communs +7 (039-045), determinants_le_la_les +8 (046-053), phrases_simples_grm +7 (054-060)

(function () {

// ── ch01 compréhension orale ────────────────────────────────────────────────

STATIC_QUESTIONS.push(
  makeMCQ({ id:'g1fr-co-039', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'discrimination_sons',
    question:'Quel mot commence par le son /f/ ?',
    options:['feu','bol','sol','mer'],
    answer:'feu',
    hint:'Dis les mots doucement. Lequel commence par le son que fait une flamme ?',
    explanation:'<b>Feu</b> commence par le son /f/. C\'est le son que tu entends au début de "fille" et "forêt".' }),

  makeMCQ({ id:'g1fr-co-040', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'discrimination_sons',
    question:'Quel mot commence par le son /v/ ?',
    options:['voiture','maison','table','porte'],
    answer:'voiture',
    hint:'Le son /v/ est comme le bruit d\'un avion — /vvv/ !',
    explanation:'<b>Voiture</b> commence par /v/. D\'autres mots avec /v/ : vélo, vent, verre.' }),

  makeMCQ({ id:'g1fr-co-041', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'discrimination_sons',
    question:'Lequel de ces mots se termine par le son /n/ ?',
    options:['lune','table','pain','chat'],
    answer:'lune',
    hint:'Dis chaque mot lentement et écoute la fin.',
    explanation:'<b>Lune</b> se termine par le son /n/. Tu entends : lu-NE.' }),

  makeMCQ({ id:'g1fr-co-042', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'discrimination_sons',
    question:'Quel mot a le même son au début que "pomme" ?',
    options:['pied','balle','route','mer'],
    answer:'pied',
    hint:'Le mot "pomme" commence par /p/. Cherche un autre mot avec /p/.',
    explanation:'<b>Pied</b> et <b>pomme</b> commencent tous les deux par le son /p/.' }),

  makeMCQ({ id:'g1fr-co-043', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'discrimination_sons',
    question:'Quel mot contient le son /ou/ comme dans "loup" ?',
    options:['roue','chat','fleur','sel'],
    answer:'roue',
    hint:'Le son /ou/ est rond — fais la forme d\'un "o" avec ta bouche.',
    explanation:'<b>Roue</b> contient le son /ou/, comme dans loup, chou et genou.' }),

  makeMCQ({ id:'g1fr-co-044', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'discrimination_sons',
    question:'Quel mot commence par le son /ch/ ?',
    options:['chien','lapin','rouge','arbre'],
    answer:'chien',
    hint:'Le son /ch/ est comme quand on dit chut ! Chhhh !',
    explanation:'<b>Chien</b> commence par /ch/. D\'autres mots : chapeau, chameau, chocolat.' }),

  makeMCQ({ id:'g1fr-co-045', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'discrimination_sons',
    question:'Quel mot se termine par le son /eau/ comme dans "bateau" ?',
    options:['chapeau','maison','livre','porte'],
    answer:'chapeau',
    hint:'Le son /eau/ se prononce comme "o". Cherche le mot qui finit pareil.',
    explanation:'<b>Chapeau</b> se termine par /eau/, tout comme bateau, gâteau et cadeau.' }),

  makeMCQ({ id:'g1fr-co-046', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'discrimination_sons',
    question:'Quel mot contient le son /i/ comme dans "vie" ?',
    options:['nid','fleur','bras','cœur'],
    answer:'nid',
    hint:'Le son /i/ est aigu et court — comme dans "ici".',
    explanation:'<b>Nid</b> contient le son /i/. D\'autres mots : midi, lit, ami.' }),

  makeMCQ({ id:'g1fr-co-047', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'comprehension_messages',
    question:'Emma dit : "Je suis fatiguée." Qu\'est-ce qu\'Emma veut faire ?',
    options:['dormir','manger','jouer','chanter'],
    answer:'dormir',
    hint:'Quand on est fatigué, qu\'est-ce qu\'on a envie de faire ?',
    explanation:'Quand on est <b>fatigué</b>, on veut <b>dormir</b>. Emma a besoin de repos.' }),

  makeMCQ({ id:'g1fr-co-048', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'comprehension_messages',
    question:'Tom dit : "Il fait froid !" Que va-t-il faire ?',
    options:['mettre un manteau','enlever sa veste','aller nager','manger une glace'],
    answer:'mettre un manteau',
    hint:'Quand il fait froid, comment on se réchauffe ?',
    explanation:'Quand il fait froid, on met un <b>manteau</b> pour se tenir au chaud.' }),

  makeMCQ({ id:'g1fr-co-049', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'comprehension_messages',
    question:'La maîtresse dit : "Ouvrez vos livres !" Que font les élèves ?',
    options:['ils ouvrent leurs livres','ils ferment leurs livres','ils chantent','ils sortent de la classe'],
    answer:'ils ouvrent leurs livres',
    hint:'La maîtresse donne une instruction. Qu\'est-ce qu\'elle demande ?',
    explanation:'La maîtresse demande aux élèves d\'<b>ouvrir leurs livres</b>. C\'est une instruction.' }),

  makeMCQ({ id:'g1fr-co-050', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'comprehension_messages',
    question:'Papa dit : "Le dîner est prêt !" Où vont les enfants ?',
    options:['à la table','dans le jardin','au lit','à l\'école'],
    answer:'à la table',
    hint:'Quand le dîner est prêt, où est-ce qu\'on mange ?',
    explanation:'Quand le dîner est prêt, on va s\'asseoir <b>à la table</b> pour manger.' }),

  makeMCQ({ id:'g1fr-co-051', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'comprehension_messages',
    question:'Lola dit : "J\'ai soif !" Que veut-elle ?',
    options:['de l\'eau','du pain','un jouet','un crayon'],
    answer:'de l\'eau',
    hint:'Quand on a soif, qu\'est-ce qu\'on boit ?',
    explanation:'Quand on a <b>soif</b>, on veut boire quelque chose, comme de l\'<b>eau</b>.' }),

  makeMCQ({ id:'g1fr-co-052', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'comprehension_messages',
    question:'Max dit : "Mon chien s\'appelle Filou." Comment s\'appelle le chien ?',
    options:['Filou','Max','Loulou','Boubou'],
    answer:'Filou',
    hint:'Relis la phrase. Quel nom entends-tu pour le chien ?',
    explanation:'Max dit que son chien <b>s\'appelle Filou</b>. C\'est le nom du chien.' }),

  makeMCQ({ id:'g1fr-co-053', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'comprehension_messages',
    question:'La phrase dit : "Il pleut." Quel temps fait-il ?',
    options:['il pleut','il fait soleil','il fait chaud','il neige'],
    answer:'il pleut',
    hint:'La phrase te donne la réponse directement !',
    explanation:'La phrase <b>il pleut</b> nous dit qu\'il y a de la pluie dehors.' }),

  makeMCQ({ id:'g1fr-co-054', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'vocabulaire_oral',
    question:'Quel animal est un oiseau ?',
    options:['perroquet','chat','lapin','chien'],
    answer:'perroquet',
    hint:'Un oiseau a des plumes et des ailes. Lequel vole ?',
    explanation:'Le <b>perroquet</b> est un oiseau — il a des plumes et peut voler.' }),

  makeMCQ({ id:'g1fr-co-055', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'vocabulaire_oral',
    question:'Quelle couleur est le ciel par beau temps ?',
    options:['bleu','rouge','vert','noir'],
    answer:'bleu',
    hint:'Regarde par la fenêtre un jour de soleil !',
    explanation:'Par beau temps, le ciel est <b>bleu</b>.' }),

  makeMCQ({ id:'g1fr-co-056', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'vocabulaire_oral',
    question:'Quel fruit est jaune et long ?',
    options:['banane','pomme','orange','fraise'],
    answer:'banane',
    hint:'Ce fruit pousse dans les pays chauds et les singes l\'adorent !',
    explanation:'La <b>banane</b> est jaune et longue. Elle pousse à Maurice aussi !' }),

  makeMCQ({ id:'g1fr-co-057', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'vocabulaire_oral',
    question:'Où habite un poisson ?',
    options:['dans l\'eau','dans un arbre','sur la terre','dans le ciel'],
    answer:'dans l\'eau',
    hint:'Le poisson a des nageoires pour nager.',
    explanation:'Les poissons habitent <b>dans l\'eau</b> — dans la mer, les rivières ou les lacs.' }),

  makeMCQ({ id:'g1fr-co-058', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'vocabulaire_oral',
    question:'Comment s\'appelle la personne qui soigne les malades à l\'hôpital ?',
    options:['docteur','boulanger','coiffeur','mécanicien'],
    answer:'docteur',
    hint:'Cette personne nous donne des médicaments quand on est malade.',
    explanation:'Le <b>docteur</b> (ou médecin) soigne les malades à l\'hôpital ou dans son cabinet.' }),

  makeMCQ({ id:'g1fr-co-059', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'vocabulaire_oral',
    question:'Quelle saison est chaude et ensoleillée à Maurice ?',
    options:['l\'été','l\'hiver','le printemps','l\'automne'],
    answer:'l\'été',
    hint:'En quelle saison fait-il très chaud et le soleil brille beaucoup ?',
    explanation:'<b>L\'été</b> est la saison la plus chaude et ensoleillée. À Maurice, c\'est entre novembre et avril.' }),

  makeMCQ({ id:'g1fr-co-060', chapterId:'g1fr-comprehension-orale', difficulty:1, subsection:'vocabulaire_oral',
    question:'Quel est le contraire de "grand" ?',
    options:['petit','fort','vieux','beau'],
    answer:'petit',
    hint:'Si un éléphant est grand, une fourmi est... ?',
    explanation:'Le contraire de <b>grand</b> est <b>petit</b>. Ce sont des antonymes.' })
);

// ── ch02 expression orale ───────────────────────────────────────────────────

STATIC_QUESTIONS.push(
  makeMCQ({ id:'g1fr-eo-039', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'comptines_chansons',
    question:'Quel mot rime avec "lune" ?',
    options:['dune','soleil','pluie','nuit'],
    answer:'dune',
    hint:'Dis les deux mots à voix haute. Quelle paire sonne pareil à la fin ?',
    explanation:'<b>Lune</b> et <b>dune</b> riment — elles se terminent toutes les deux par le son "une".' }),

  makeMCQ({ id:'g1fr-eo-040', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'comptines_chansons',
    question:'Quel mot rime avec "maison" ?',
    options:['saison','livre','table','porte'],
    answer:'saison',
    hint:'Cherche le mot qui finit avec le même son que "mai-SON".',
    explanation:'<b>Maison</b> et <b>saison</b> riment — elles se terminent par "-aison".' }),

  makeMCQ({ id:'g1fr-eo-041', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'comptines_chansons',
    question:'Quel mot rime avec "fleur" ?',
    options:['cœur','mer','lac','bois'],
    answer:'cœur',
    hint:'Dis "fleur" et cherche le mot qui se termine pareil.',
    explanation:'<b>Fleur</b> et <b>cœur</b> riment — elles ont le même son "-eur" à la fin.' }),

  makeMCQ({ id:'g1fr-eo-042', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'comptines_chansons',
    question:'Quel mot rime avec "pain" ?',
    options:['main','bois','mer','sel'],
    answer:'main',
    hint:'Le son "ain" à la fin — cherche un autre mot avec ce son.',
    explanation:'<b>Pain</b> et <b>main</b> riment — elles ont toutes les deux le son "-ain".' }),

  makeMCQ({ id:'g1fr-eo-043', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'comptines_chansons',
    question:'Quel mot rime avec "mouton" ?',
    options:['bouton','chien','arbre','route'],
    answer:'bouton',
    hint:'Le son "on" à la fin — cherche le mot qui finit pareil.',
    explanation:'<b>Mouton</b> et <b>bouton</b> riment — elles ont le son "-ton" à la fin.' }),

  makeMCQ({ id:'g1fr-eo-044', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'comptines_chansons',
    question:'Laquelle de ces paires de mots rime ?',
    options:['étoile / toile','chat / chien','maison / arbre','lune / soleil'],
    answer:'étoile / toile',
    hint:'Dis chaque paire. Laquelle sonne pareil à la fin ?',
    explanation:'<b>Étoile</b> et <b>toile</b> riment — elles se terminent toutes les deux par le son "-oile".' }),

  makeMCQ({ id:'g1fr-eo-045', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'comptines_chansons',
    question:'Dans une comptine, les mots qui riment sont ___.',
    options:['à la fin des lignes','au début des lignes','au milieu','partout'],
    answer:'à la fin des lignes',
    hint:'Lis une comptine. Où entends-tu les rimes ?',
    explanation:'Dans une comptine, les mots qui <b>riment</b> se trouvent généralement <b>à la fin des lignes</b>.' }),

  makeMCQ({ id:'g1fr-eo-046', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'conversation_simple',
    question:'Comment dit-on "au revoir" le soir ?',
    options:['Bonne nuit','Bonjour','Salut','Merci'],
    answer:'Bonne nuit',
    hint:'Le soir, avant de dormir, on dit... ?',
    explanation:'Le soir, avant de dormir, on dit <b>Bonne nuit</b>. Le matin on dit Bonjour.' }),

  makeMCQ({ id:'g1fr-eo-047', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'conversation_simple',
    question:'Quelqu\'un t\'offre un cadeau. Que dis-tu ?',
    options:['Merci beaucoup !','Ce n\'est pas beau.','Je ne veux pas.','Donne-le-moi.'],
    answer:'Merci beaucoup !',
    hint:'On dit toujours merci quand on reçoit quelque chose.',
    explanation:'On dit <b>Merci beaucoup !</b> pour montrer qu\'on est content et poli.' }),

  makeMCQ({ id:'g1fr-eo-048', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'conversation_simple',
    question:'Tu veux un biscuit. Que demandes-tu poliment ?',
    options:['S\'il vous plaît, puis-je avoir un biscuit ?','Donne-moi un biscuit maintenant !','Je veux un biscuit.','Un biscuit !'],
    answer:'S\'il vous plaît, puis-je avoir un biscuit ?',
    hint:'N\'oublie pas les mots magiques de politesse !',
    explanation:'On demande poliment en disant <b>s\'il vous plaît</b>. C\'est un mot magique !' }),

  makeMCQ({ id:'g1fr-eo-049', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'conversation_simple',
    question:'Comment réponds-tu si quelqu\'un te demande ton prénom ?',
    options:['Je m\'appelle ...','Je suis ...','Mon prénom est ...','Les deux premières réponses'],
    answer:'Les deux premières réponses',
    hint:'Il y a plusieurs façons correctes de se présenter.',
    explanation:'On peut dire <b>Je m\'appelle...</b> ou <b>Je suis...</b> pour donner son prénom.' }),

  makeMCQ({ id:'g1fr-eo-050', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'conversation_simple',
    question:'Comment demandes-tu à un ami comment il va ?',
    options:['Comment vas-tu ?','Qu\'est-ce que tu manges ?','Où habites-tu ?','Quel âge as-tu ?'],
    answer:'Comment vas-tu ?',
    hint:'Pour savoir si ton ami va bien, quelle question poses-tu ?',
    explanation:'On demande <b>Comment vas-tu ?</b> pour savoir si quelqu\'un se porte bien.' }),

  makeMCQ({ id:'g1fr-eo-051', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'conversation_simple',
    question:'Un ami te dit "Comment vas-tu ?" Tu réponds :',
    options:['Je vais bien, merci !','Il fait beau.','J\'ai faim.','C\'est lundi.'],
    answer:'Je vais bien, merci !',
    hint:'Réponds à la question qu\'on te pose.',
    explanation:'Quand on vous demande comment vous allez, on répond <b>Je vais bien, merci !</b>' }),

  makeMCQ({ id:'g1fr-eo-052', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'conversation_simple',
    question:'Tu entres dans la classe le matin. Que dis-tu à la maîtresse ?',
    options:['Bonjour, Madame !','Bonsoir, Madame !','Au revoir, Madame !','Bonne nuit, Madame !'],
    answer:'Bonjour, Madame !',
    hint:'C\'est le matin — quelle salutation utilises-tu ?',
    explanation:'Le matin, on dit <b>Bonjour</b>. On dit bonsoir le soir et au revoir quand on part.' }),

  makeMCQ({ id:'g1fr-eo-053', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'description_images',
    question:'Comment décrit-on un ballon rouge et rond ?',
    options:['un ballon rouge et rond','un ballon bleu et carré','un ballon grand et vert','un ballon petit et jaune'],
    answer:'un ballon rouge et rond',
    hint:'Dis la couleur et la forme que tu vois.',
    explanation:'On décrit d\'abord la couleur, puis la forme : <b>rouge et rond</b>.' }),

  makeMCQ({ id:'g1fr-eo-054', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'description_images',
    question:'Tu vois un grand arbre vert. Comment le décris-tu ?',
    options:['un grand arbre vert','un petit arbre rouge','un arbre bleu','un arbre blanc'],
    answer:'un grand arbre vert',
    hint:'Dis la taille et la couleur de l\'arbre.',
    explanation:'On décrit en donnant la taille et la couleur : <b>un grand arbre vert</b>.' }),

  makeMCQ({ id:'g1fr-eo-055', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'description_images',
    question:'Quel mot décrit quelque chose de très grand ?',
    options:['énorme','minuscule','petit','léger'],
    answer:'énorme',
    hint:'Pense à un éléphant — comment est-il ?',
    explanation:'<b>Énorme</b> veut dire très grand. Un éléphant est énorme.' }),

  makeMCQ({ id:'g1fr-eo-056', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'description_images',
    question:'Pour décrire une image, on dit d\'abord ___.',
    options:['ce qu\'on voit','ce qu\'on imagine','ce qu\'on entend','ce qu\'on mange'],
    answer:'ce qu\'on voit',
    hint:'Pour décrire, utilise tes yeux !',
    explanation:'Pour décrire une image, on dit d\'abord <b>ce qu\'on voit</b> : les personnages, les objets, les couleurs.' }),

  makeMCQ({ id:'g1fr-eo-057', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'description_images',
    question:'Tu vois un chat noir sur un tapis rouge. Quelle est la description correcte ?',
    options:['Un chat noir est assis sur un tapis rouge.','Un chien blanc est sur une chaise.','Un lapin gris mange une carotte.','Un oiseau vole dans le ciel.'],
    answer:'Un chat noir est assis sur un tapis rouge.',
    hint:'La description doit correspondre à ce que tu vois.',
    explanation:'La bonne description dit exactement ce qu\'on voit : <b>un chat noir sur un tapis rouge</b>.' }),

  makeMCQ({ id:'g1fr-eo-058', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'description_images',
    question:'Quel mot décrit quelque chose qui fait du bruit ?',
    options:['bruyant','silencieux','doux','lent'],
    answer:'bruyant',
    hint:'L\'opposé de silencieux, c\'est... ?',
    explanation:'<b>Bruyant</b> décrit quelque chose qui fait beaucoup de bruit. L\'opposé est silencieux.' }),

  makeMCQ({ id:'g1fr-eo-059', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'description_images',
    question:'Pour décrire un fruit, on peut dire sa ___.',
    options:['couleur et sa taille','vitesse et sa hauteur','âge et son poids','son nom de famille'],
    answer:'couleur et sa taille',
    hint:'Quelles informations décrivent un fruit que tu vois ?',
    explanation:'Pour décrire un fruit, on dit sa <b>couleur</b> et sa <b>taille</b> : une grande mangue jaune.' }),

  makeMCQ({ id:'g1fr-eo-060', chapterId:'g1fr-expression-orale', difficulty:1, subsection:'description_images',
    question:'Qu\'est-ce qu\'un adjectif ?',
    options:['un mot qui décrit','un mot qui nomme','un mot d\'action','un mot de salutation'],
    answer:'un mot qui décrit',
    hint:'Les adjectifs comme "grand", "rouge" et "doux" font quoi ?',
    explanation:'Un <b>adjectif</b> est un mot qui décrit un nom. Ex : un <b>grand</b> arbre, une <b>belle</b> fleur.' })
);

// ── ch03 lecture ────────────────────────────────────────────────────────────

STATIC_QUESTIONS.push(
  makeMCQ({ id:'g1fr-lec-039', chapterId:'g1fr-lecture', difficulty:1, subsection:'conscience_phonique',
    question:'Combien de syllabes a le mot "ba-na-ne" ?',
    options:['3','2','4','1'],
    answer:'3',
    hint:'Frappe dans tes mains pour chaque partie du mot : ba - na - ne.',
    explanation:'"Banane" a <b>3 syllabes</b> : ba / na / ne. Frappe dans tes mains pour compter.' }),

  makeMCQ({ id:'g1fr-lec-040', chapterId:'g1fr-lecture', difficulty:1, subsection:'conscience_phonique',
    question:'Combien de syllabes a le mot "so-leil" ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'Frappe les syllabes : so - leil.',
    explanation:'"Soleil" a <b>2 syllabes</b> : so / leil.' }),

  makeMCQ({ id:'g1fr-lec-041', chapterId:'g1fr-lecture', difficulty:1, subsection:'conscience_phonique',
    question:'Combien de syllabes a le mot "pa-pi-llon" ?',
    options:['3','2','4','1'],
    answer:'3',
    hint:'Frappe dans tes mains : pa - pi - llon.',
    explanation:'"Papillon" a <b>3 syllabes</b> : pa / pi / llon.' }),

  makeMCQ({ id:'g1fr-lec-042', chapterId:'g1fr-lecture', difficulty:1, subsection:'conscience_phonique',
    question:'Quel mot a 1 seule syllabe ?',
    options:['chat','ma-man','ta-bleau','pa-pi-llon'],
    answer:'chat',
    hint:'Lequel se dit en un seul coup ?',
    explanation:'"<b>Chat</b>" a 1 seule syllabe. Tu le dis d\'un seul coup : CHAT.' }),

  makeMCQ({ id:'g1fr-lec-043', chapterId:'g1fr-lecture', difficulty:1, subsection:'conscience_phonique',
    question:'Quel mot a 2 syllabes ?',
    options:['ma-man','chat','pa-pi-llon','ca-ro-tte'],
    answer:'ma-man',
    hint:'Cherche le mot qui se dit en 2 parties.',
    explanation:'"<b>Maman</b>" a 2 syllabes : ma / man.' }),

  makeMCQ({ id:'g1fr-lec-044', chapterId:'g1fr-lecture', difficulty:1, subsection:'conscience_phonique',
    question:'Quel son entends-tu au début du mot "école" ?',
    options:['/é/',''/b/',''/p/',''/s/'],
    answer:'/é/',
    hint:'"École" commence par une voyelle. Quelle est-elle ?',
    explanation:'"<b>École</b>" commence par la voyelle <b>/é/</b>. C\'est un son de voyelle.' }),

  makeMCQ({ id:'g1fr-lec-045', chapterId:'g1fr-lecture', difficulty:1, subsection:'conscience_phonique',
    question:'Quelle voyelle entends-tu dans le mot "lune" ?',
    options:['u','a','i','o'],
    answer:'u',
    hint:'Dis "lune" lentement : l - u - n - e. Quelle voyelle entends-tu ?',
    explanation:'Dans "lune", la voyelle principale est le <b>/u/</b>.' }),

  makeMCQ({ id:'g1fr-lec-046', chapterId:'g1fr-lecture', difficulty:1, subsection:'lettres_sons',
    question:'Quelle lettre fait le son /r/ ?',
    options:['R','B','T','M'],
    answer:'R',
    hint:'Le son /r/ vient de la gorge — comme dans "rouge", "rue", "rose".',
    explanation:'La lettre <b>R</b> fait le son /r/, comme dans rouge, rat et rue.' }),

  makeMCQ({ id:'g1fr-lec-047', chapterId:'g1fr-lecture', difficulty:1, subsection:'lettres_sons',
    question:'Quelle lettre fait le son /j/ comme dans "jus" ?',
    options:['J','G','Y','I'],
    answer:'J',
    hint:'Le son /j/ est doux, comme un bourdonnement.',
    explanation:'La lettre <b>J</b> fait le son /j/, comme dans jus, jardin et jouet.' }),

  makeMCQ({ id:'g1fr-lec-048', chapterId:'g1fr-lecture', difficulty:1, subsection:'lettres_sons',
    question:'Quelle lettre fait le son /k/ comme dans "canard" ?',
    options:['C','B','D','F'],
    answer:'C',
    hint:'Devant les voyelles a, o, u, la lettre "c" fait le son /k/.',
    explanation:'La lettre <b>C</b> devant a, o, u fait le son /k/ : canard, coq, cube.' }),

  makeMCQ({ id:'g1fr-lec-049', chapterId:'g1fr-lecture', difficulty:1, subsection:'lettres_sons',
    question:'Le son /gn/ comme dans "agneau" est écrit avec quelles lettres ?',
    options:['gn','ng','gh','hn'],
    answer:'gn',
    hint:'Pense au mot "montagne" — quelles lettres font ce son ?',
    explanation:'Les lettres <b>gn</b> font le son /gn/ comme dans agneau, montagne, champignon.' }),

  makeMCQ({ id:'g1fr-lec-050', chapterId:'g1fr-lecture', difficulty:1, subsection:'lettres_sons',
    question:'La lettre "e" à la fin d\'un mot en français est souvent ___.',
    options:['muette (on ne la prononce pas)','toujours prononcée','toujours bruyante','toujours un son /é/'],
    answer:'muette (on ne la prononce pas)',
    hint:'Dis "table" — est-ce que tu prononces le "e" à la fin ?',
    explanation:'En français, le <b>e final</b> est souvent muet, comme dans table, maison, tête.' }),

  makeMCQ({ id:'g1fr-lec-051', chapterId:'g1fr-lecture', difficulty:1, subsection:'lettres_sons',
    question:'Combien de lettres y a-t-il dans l\'alphabet français ?',
    options:['26','24','28','20'],
    answer:'26',
    hint:'L\'alphabet français a le même nombre de lettres que l\'alphabet anglais.',
    explanation:'L\'alphabet français a <b>26 lettres</b>, de A à Z, comme l\'alphabet anglais.' }),

  makeMCQ({ id:'g1fr-lec-052', chapterId:'g1fr-lecture', difficulty:1, subsection:'lettres_sons',
    question:'Quelles lettres sont les voyelles en français ?',
    options:['a, e, i, o, u (et y)','b, c, d, f, g','a, b, c, d, e','m, n, p, r, s'],
    answer:'a, e, i, o, u (et y)',
    hint:'Les voyelles font un son ouvert — on peut les chanter !',
    explanation:'Les <b>voyelles</b> en français sont a, e, i, o, u (et parfois y).' }),

  makeMCQ({ id:'g1fr-lec-053', chapterId:'g1fr-lecture', difficulty:1, subsection:'lettres_sons',
    question:'Quel son font les lettres "ou" ensemble ?',
    options:['/ou/ comme dans "loup"','/o/ comme dans "beau"','/u/ comme dans "lune"','/au/ comme dans "eau"'],
    answer:'/ou/ comme dans "loup"',
    hint:'Dis "loup" — quel son entends-tu avec les lettres o-u ?',
    explanation:'Les lettres <b>ou</b> ensemble font le son /ou/ comme dans loup, chou, roue.' }),

  makeMCQ({ id:'g1fr-lec-054', chapterId:'g1fr-lecture', difficulty:1, subsection:'mots_simples',
    question:'Quel mot veut dire "maman" ?',
    options:['mère','sœur','fille','cousine'],
    answer:'mère',
    hint:'"Mère" est un autre mot pour maman.',
    explanation:'<b>Mère</b> est un autre mot pour maman. Père veut dire papa.' }),

  makeMCQ({ id:'g1fr-lec-055', chapterId:'g1fr-lecture', difficulty:1, subsection:'mots_simples',
    question:'Quel mot désigne l\'endroit où on va pour apprendre ?',
    options:['école','magasin','hôpital','gare'],
    answer:'école',
    hint:'Tu y vas chaque jour pour lire, écrire et apprendre.',
    explanation:'L\'<b>école</b> est l\'endroit où les enfants apprennent à lire, écrire et compter.' }),

  makeMCQ({ id:'g1fr-lec-056', chapterId:'g1fr-lecture', difficulty:1, subsection:'mots_simples',
    question:'Quel mot désigne quelque chose qu\'on mange ?',
    options:['aliment','vêtement','meuble','outil'],
    answer:'aliment',
    hint:'On mange des aliments pour avoir de l\'énergie.',
    explanation:'Un <b>aliment</b> est quelque chose qu\'on mange : une pomme, du riz, du pain.' }),

  makeMCQ({ id:'g1fr-lec-057', chapterId:'g1fr-lecture', difficulty:1, subsection:'mots_simples',
    question:'Quel mot veut dire le contraire de "nuit" ?',
    options:['jour','soir','matin','midi'],
    answer:'jour',
    hint:'Quand il fait soleil, c\'est... ?',
    explanation:'Le contraire de <b>nuit</b> est <b>jour</b>. Le jour, il fait clair ; la nuit, il fait sombre.' }),

  makeMCQ({ id:'g1fr-lec-058', chapterId:'g1fr-lecture', difficulty:1, subsection:'mots_simples',
    question:'Quel mot veut dire "content" ?',
    options:['heureux','triste','fatigué','malade'],
    answer:'heureux',
    hint:'Quand on reçoit un cadeau, on est... ?',
    explanation:'<b>Heureux</b> veut dire content, joyeux. Son contraire est triste.' }),

  makeMCQ({ id:'g1fr-lec-059', chapterId:'g1fr-lecture', difficulty:1, subsection:'mots_simples',
    question:'Quel mot désigne la personne qui enseigne à l\'école ?',
    options:['maître / maîtresse','docteur','boulanger','pompier'],
    answer:'maître / maîtresse',
    hint:'C\'est la personne devant la classe qui apprend aux élèves.',
    explanation:'Le <b>maître</b> (pour un homme) ou la <b>maîtresse</b> (pour une femme) enseigne à l\'école.' }),

  makeMCQ({ id:'g1fr-lec-060', chapterId:'g1fr-lecture', difficulty:1, subsection:'mots_simples',
    question:'Quel mot désigne l\'animal qui fait "cocorico" le matin ?',
    options:['coq','canard','poule','pigeon'],
    answer:'coq',
    hint:'Cet animal chante le matin pour réveiller tout le monde !',
    explanation:'Le <b>coq</b> est le mâle de la poule. Il chante "cocorico" le matin.' })
);

// ── ch04 écriture ───────────────────────────────────────────────────────────

STATIC_QUESTIONS.push(
  makeMCQ({ id:'g1fr-ecr-033', chapterId:'g1fr-ecriture', difficulty:1, subsection:'lettres_minuscules',
    question:'Quelle est la lettre minuscule de "A" ?',
    options:['a','A','@','α'],
    answer:'a',
    hint:'La majuscule est grande, la minuscule est petite.',
    explanation:'La lettre majuscule <b>A</b> a pour minuscule <b>a</b>.' }),

  makeMCQ({ id:'g1fr-ecr-034', chapterId:'g1fr-ecriture', difficulty:1, subsection:'lettres_minuscules',
    question:'Quelle est la lettre majuscule de "m" ?',
    options:['M','m','N','W'],
    answer:'M',
    hint:'La majuscule est la grande version de la lettre.',
    explanation:'La minuscule <b>m</b> a pour majuscule <b>M</b>.' }),

  makeMCQ({ id:'g1fr-ecr-035', chapterId:'g1fr-ecriture', difficulty:1, subsection:'lettres_minuscules',
    question:'Laquelle de ces lettres est une minuscule ?',
    options:['b','B','D','T'],
    answer:'b',
    hint:'Les minuscules sont les petites lettres.',
    explanation:'<b>b</b> est une lettre minuscule. Les majuscules correspondantes sont B.' }),

  makeMCQ({ id:'g1fr-ecr-036', chapterId:'g1fr-ecriture', difficulty:1, subsection:'lettres_minuscules',
    question:'Laquelle de ces lettres est une majuscule ?',
    options:['F','f','d','p'],
    answer:'F',
    hint:'Les majuscules sont les grandes lettres.',
    explanation:'<b>F</b> est une lettre majuscule. Sa minuscule est f.' }),

  makeMCQ({ id:'g1fr-ecr-037', chapterId:'g1fr-ecriture', difficulty:1, subsection:'lettres_minuscules',
    question:'Quelle lettre vient après "d" dans l\'alphabet ?',
    options:['e','c','b','f'],
    answer:'e',
    hint:'a, b, c, d, ___ ... Quelle est la lettre suivante ?',
    explanation:'Dans l\'alphabet, après <b>d</b> vient <b>e</b> : a, b, c, d, <b>e</b>, f...' }),

  makeMCQ({ id:'g1fr-ecr-038', chapterId:'g1fr-ecriture', difficulty:1, subsection:'lettres_minuscules',
    question:'Quelle lettre vient avant "h" dans l\'alphabet ?',
    options:['g','i','f','j'],
    answer:'g',
    hint:'...f, g, h... Quelle lettre est juste avant "h" ?',
    explanation:'Dans l\'alphabet, avant <b>h</b> vient <b>g</b> : ...f, <b>g</b>, h, i...' }),

  makeMCQ({ id:'g1fr-ecr-039', chapterId:'g1fr-ecriture', difficulty:1, subsection:'lettres_minuscules',
    question:'Comment s\'appelle la première lettre de l\'alphabet ?',
    options:['a (A)','b (B)','z (Z)','m (M)'],
    answer:'a (A)',
    hint:'L\'alphabet commence par... ?',
    explanation:'La première lettre de l\'alphabet est <b>a</b> (majuscule : <b>A</b>).' }),

  makeMCQ({ id:'g1fr-ecr-040', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Quelle est la bonne orthographe du mot qui désigne la couleur du ciel ?',
    options:['bleu','bleu','belu','bleue'],
    answer:'bleu',
    hint:'Ce mot a 4 lettres : b-l-e-u.',
    explanation:'Le ciel est <b>bleu</b>. On écrit b, l, e, u.' }),

  makeMCQ({ id:'g1fr-ecr-041', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour l\'animal qui fait "miaou" ?',
    options:['chat','chta','acht','cath'],
    answer:'chat',
    hint:'Cet animal vit dans les maisons et ronronne. C-H-A-T.',
    explanation:'L\'animal qui fait "miaou" s\'écrit <b>chat</b> : c, h, a, t.' }),

  makeMCQ({ id:'g1fr-ecr-042', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour "maison" ?',
    options:['maison','maisoon','maissen','mezon'],
    answer:'maison',
    hint:'C\'est l\'endroit où on habite. m-a-i-s-o-n.',
    explanation:'L\'endroit où on habite s\'écrit <b>maison</b> : m, a, i, s, o, n.' }),

  makeMCQ({ id:'g1fr-ecr-043', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour "table" ?',
    options:['table','talbe','tabble','tabel'],
    answer:'table',
    hint:'Le meuble sur lequel on pose nos affaires : t-a-b-l-e.',
    explanation:'La <b>table</b> s\'écrit t, a, b, l, e.' }),

  makeMCQ({ id:'g1fr-ecr-044', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour "livre" ?',
    options:['livre','livr','lievr','livrre'],
    answer:'livre',
    hint:'On le lit pour apprendre ou pour s\'amuser : l-i-v-r-e.',
    explanation:'On lit un <b>livre</b> : l, i, v, r, e.' }),

  makeMCQ({ id:'g1fr-ecr-045', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour "école" ?',
    options:['école','ecole','escole','échole'],
    answer:'école',
    hint:'Attention à l\'accent sur le premier "e" : é-c-o-l-e.',
    explanation:'"<b>École</b>" s\'écrit avec un accent aigu sur le é : é, c, o, l, e.' }),

  makeMCQ({ id:'g1fr-ecr-046', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour "arbre" ?',
    options:['arbre','abre','arabe','arbre'],
    answer:'arbre',
    hint:'Une plante très grande qui pousse dehors : a-r-b-r-e.',
    explanation:'Un grand végétal s\'appelle un <b>arbre</b> : a, r, b, r, e.' }),

  makeMCQ({ id:'g1fr-ecr-047', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour "soleil" ?',
    options:['soleil','soeil','solleil','solail'],
    answer:'soleil',
    hint:'L\'étoile qui brille le jour : s-o-l-e-i-l.',
    explanation:'L\'étoile qui nous donne de la lumière le jour s\'écrit <b>soleil</b> : s, o, l, e, i, l.' }),

  makeMCQ({ id:'g1fr-ecr-048', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour "rouge" ?',
    options:['rouge','rouje','rouche','roug'],
    answer:'rouge',
    hint:'La couleur des tomates et des fraises : r-o-u-g-e.',
    explanation:'La couleur des tomates s\'écrit <b>rouge</b> : r, o, u, g, e.' }),

  makeMCQ({ id:'g1fr-ecr-049', chapterId:'g1fr-ecriture', difficulty:1, subsection:'copie_mots',
    question:'Laquelle de ces écritures est correcte pour "fleur" ?',
    options:['fleur','fler','flleur','fleure'],
    answer:'fleur',
    hint:'Une plante colorée qui sent bon : f-l-e-u-r.',
    explanation:'Une <b>fleur</b> est une plante colorée et parfumée : f, l, e, u, r.' }),

  makeMCQ({ id:'g1fr-ecr-050', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Laquelle de ces phrases est correcte ?',
    options:['Le chat dort.','chat le dort.','dort chat le.','Le dort chat.'],
    answer:'Le chat dort.',
    hint:'Une phrase correcte commence par une majuscule et les mots sont dans le bon ordre.',
    explanation:'<b>Le chat dort.</b> est une phrase correcte — majuscule au début et point à la fin.' }),

  makeMCQ({ id:'g1fr-ecr-051', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Laquelle de ces phrases commence correctement ?',
    options:['La fleur est belle.','la fleur est belle.','LA fleur est belle.','La Fleur est belle.'],
    answer:'La fleur est belle.',
    hint:'Chaque phrase commence par une majuscule — mais seulement la première lettre.',
    explanation:'Une phrase commence par une <b>majuscule</b> : <b>L</b>a fleur est belle.' }),

  makeMCQ({ id:'g1fr-ecr-052', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Quel signe de ponctuation termine une phrase qui affirme quelque chose ?',
    options:['.','?','!',','],
    answer:'.',
    hint:'C\'est un petit point rond à la fin de la phrase.',
    explanation:'Une phrase déclarative (qui affirme) se termine par un <b>point</b> (.)' }),

  makeMCQ({ id:'g1fr-ecr-053', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Quel signe de ponctuation termine une question ?',
    options:['?','.','!',','],
    answer:'?',
    hint:'Quand on pose une question, on utilise ce signe à la fin.',
    explanation:'Une question se termine par un <b>point d\'interrogation</b> (?).' }),

  makeMCQ({ id:'g1fr-ecr-054', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Qu\'est-ce qu\'on laisse entre les mots dans une phrase ?',
    options:['un espace','une virgule','une ligne','rien'],
    answer:'un espace',
    hint:'Les mots doivent être séparés pour qu\'on puisse les lire.',
    explanation:'On laisse <b>un espace</b> entre chaque mot pour que la phrase soit lisible.' }),

  makeMCQ({ id:'g1fr-ecr-055', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Laquelle de ces phrases a le bon ordre des mots ?',
    options:['Le chien court vite.','Court le chien vite.','Vite le chien court.','Chien le court vite.'],
    answer:'Le chien court vite.',
    hint:'En français, le sujet vient en général avant le verbe.',
    explanation:'<b>Le chien court vite.</b> — sujet (le chien) + verbe (court) + adverbe (vite).' }),

  makeMCQ({ id:'g1fr-ecr-056', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Une phrase doit avoir au minimum ___.',
    options:['un sujet et un verbe','deux virgules','trois mots','une majuscule seulement'],
    answer:'un sujet et un verbe',
    hint:'Qui fait quoi ? C\'est la base d\'une phrase.',
    explanation:'Une phrase a au minimum un <b>sujet</b> (qui ?) et un <b>verbe</b> (quoi ?) : "Le soleil brille."' }),

  makeMCQ({ id:'g1fr-ecr-057', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Laquelle de ces phrases est complète ?',
    options:['Le lapin mange une carotte.','Le lapin.','Mange vite.','Une carotte verte.'],
    answer:'Le lapin mange une carotte.',
    hint:'Une phrase complète a un sujet et un verbe.',
    explanation:'<b>Le lapin mange une carotte.</b> est complète : sujet (le lapin) + verbe (mange) + complément.' }),

  makeMCQ({ id:'g1fr-ecr-058', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Quel signe met-on à la fin d\'une phrase exclamative (qui exprime un sentiment fort) ?',
    options:['!','.',',','?'],
    answer:'!',
    hint:'Ce signe montre la surprise ou la joie !',
    explanation:'Une phrase exclamative se termine par un <b>point d\'exclamation</b> (!) : "Quelle belle journée !"' }),

  makeMCQ({ id:'g1fr-ecr-059', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Laquelle de ces phrases est une question ?',
    options:['Où est mon cahier ?','Le cahier est sur la table.','Prends ton cahier !','Un joli cahier rouge.'],
    answer:'Où est mon cahier ?',
    hint:'Une question se termine par un point d\'interrogation.',
    explanation:'<b>Où est mon cahier ?</b> est une question — elle se termine par un point d\'interrogation.' }),

  makeMCQ({ id:'g1fr-ecr-060', chapterId:'g1fr-ecriture', difficulty:1, subsection:'phrases_simples',
    question:'Pour écrire une belle phrase, on doit ___.',
    options:['commencer par une majuscule et finir par un point','commencer par un point et finir par une majuscule','utiliser seulement des majuscules','écrire tout en minuscules'],
    answer:'commencer par une majuscule et finir par un point',
    hint:'La majuscule ouvre la phrase. Le point la ferme.',
    explanation:'Toute phrase commence par une <b>majuscule</b> et se termine par un <b>point</b>.' })
);

// ── ch05 grammaire ──────────────────────────────────────────────────────────

STATIC_QUESTIONS.push(
  makeMCQ({ id:'g1fr-grm-039', chapterId:'g1fr-grammaire', difficulty:1, subsection:'noms_communs',
    question:'Lequel est un nom commun d\'animal ?',
    options:['chien','courir','beau','vite'],
    answer:'chien',
    hint:'Un nom commun désigne une chose, une personne ou un animal.',
    explanation:'<b>Chien</b> est un nom commun — il désigne un animal. "Courir" est un verbe, "beau" un adjectif.' }),

  makeMCQ({ id:'g1fr-grm-040', chapterId:'g1fr-grammaire', difficulty:1, subsection:'noms_communs',
    question:'Lequel est un nom commun de lieu ?',
    options:['jardin','vert','sauter','très'],
    answer:'jardin',
    hint:'Les noms de lieux comme parc, forêt, jardin sont des noms communs.',
    explanation:'<b>Jardin</b> est un nom commun de lieu. D\'autres exemples : école, marché, ville.' }),

  makeMCQ({ id:'g1fr-grm-041', chapterId:'g1fr-grammaire', difficulty:1, subsection:'noms_communs',
    question:'Dans la phrase "Le soleil brille", quel est le nom ?',
    options:['soleil','le','brille','Le soleil brille'],
    answer:'soleil',
    hint:'Le nom est le mot qui désigne une chose ou un être.',
    explanation:'<b>Soleil</b> est le nom — il désigne une chose. "Brille" est le verbe.' }),

  makeMCQ({ id:'g1fr-grm-042', chapterId:'g1fr-grammaire', difficulty:1, subsection:'noms_communs',
    question:'Lequel de ces mots est un nom commun de personne ?',
    options:['enfant','courir','rouge','toujours'],
    answer:'enfant',
    hint:'Les noms de personnes désignent des êtres humains.',
    explanation:'<b>Enfant</b> est un nom commun de personne. D\'autres exemples : maîtresse, docteur, ami.' }),

  makeMCQ({ id:'g1fr-grm-043', chapterId:'g1fr-grammaire', difficulty:1, subsection:'noms_communs',
    question:'Combien de noms y a-t-il dans "Le chat mange un poisson" ?',
    options:['2','1','3','0'],
    answer:'2',
    hint:'Trouve les mots qui désignent des êtres ou des choses : chat et... ?',
    explanation:'Il y a <b>2 noms</b> : <b>chat</b> et <b>poisson</b>. "Le" et "un" sont des articles, "mange" est un verbe.' }),

  makeMCQ({ id:'g1fr-grm-044', chapterId:'g1fr-grammaire', difficulty:1, subsection:'noms_communs',
    question:'Un nom commun désigne ___.',
    options:['une chose, une personne ou un animal en général','une personne spécifique par son prénom','une couleur','une action'],
    answer:'une chose, une personne ou un animal en général',
    hint:'Pense à "chaise", "fille", "oiseau" — ce sont des noms communs.',
    explanation:'Un <b>nom commun</b> désigne une chose, une personne ou un animal en général : table, garçon, chien.' }),

  makeMCQ({ id:'g1fr-grm-045', chapterId:'g1fr-grammaire', difficulty:1, subsection:'noms_communs',
    question:'Lequel de ces mots n\'est PAS un nom commun ?',
    options:['sauter','école','chaise','crayon'],
    answer:'sauter',
    hint:'"Sauter" est ce qu\'on fait — ce n\'est pas une chose ou un être.',
    explanation:'"<b>Sauter</b>" est un verbe (une action), pas un nom commun. École, chaise et crayon sont des noms.' }),

  makeMCQ({ id:'g1fr-grm-046', chapterId:'g1fr-grammaire', difficulty:1, subsection:'determinants_le_la_les',
    question:'Quel déterminant utilise-t-on devant "garçon" (masculin singulier) ?',
    options:['le','la','les','l\''],
    answer:'le',
    hint:'"Garçon" est masculin et singulier. On dit "le garçon".',
    explanation:'Devant un nom masculin singulier qui commence par une consonne, on utilise <b>le</b> : le garçon, le chien.' }),

  makeMCQ({ id:'g1fr-grm-047', chapterId:'g1fr-grammaire', difficulty:1, subsection:'determinants_le_la_les',
    question:'Quel déterminant utilise-t-on devant "fille" (féminin singulier) ?',
    options:['la','le','les','l\''],
    answer:'la',
    hint:'"Fille" est féminin et singulier. On dit "la fille".',
    explanation:'Devant un nom féminin singulier, on utilise <b>la</b> : la fille, la maison.' }),

  makeMCQ({ id:'g1fr-grm-048', chapterId:'g1fr-grammaire', difficulty:1, subsection:'determinants_le_la_les',
    question:'Quel déterminant utilise-t-on devant "arbres" (pluriel) ?',
    options:['les','le','la','l\''],
    answer:'les',
    hint:'Pour les noms au pluriel, on utilise toujours "les".',
    explanation:'Devant un nom au pluriel, on utilise <b>les</b> : les arbres, les enfants, les fleurs.' }),

  makeMCQ({ id:'g1fr-grm-049', chapterId:'g1fr-grammaire', difficulty:1, subsection:'determinants_le_la_les',
    question:'Quel déterminant utilise-t-on devant "orange" (féminin, commence par une voyelle) ?',
    options:['l\'','la','le','les'],
    answer:'l\'',
    hint:'Devant les mots qui commencent par une voyelle, "le" et "la" deviennent "l\'".',
    explanation:'Devant un mot commençant par une voyelle, on utilise <b>l\'</b> : l\'orange, l\'école, l\'arbre.' }),

  makeMCQ({ id:'g1fr-grm-050', chapterId:'g1fr-grammaire', difficulty:1, subsection:'determinants_le_la_les',
    question:'Complète : "___ soleil brille."',
    options:['Le','La','Les','L\''],
    answer:'Le',
    hint:'"Soleil" est masculin singulier et commence par une consonne.',
    explanation:'On dit <b>le soleil</b> — masculin singulier, commence par "s" (consonne).' }),

  makeMCQ({ id:'g1fr-grm-051', chapterId:'g1fr-grammaire', difficulty:1, subsection:'determinants_le_la_les',
    question:'Complète : "___ enfants jouent."',
    options:['Les','Le','La','L\''],
    answer:'Les',
    hint:'"Enfants" est au pluriel.',
    explanation:'On dit <b>les enfants</b> — pluriel, donc on utilise "les".' }),

  makeMCQ({ id:'g1fr-grm-052', chapterId:'g1fr-grammaire', difficulty:1, subsection:'determinants_le_la_les',
    question:'Complète : "___ école est grande."',
    options:['L\'','Le','La','Les'],
    answer:'L\'',
    hint:'"École" commence par une voyelle.',
    explanation:'On dit <b>l\'école</b> — "école" commence par la voyelle "é", donc on élide : l\'.' }),

  makeMCQ({ id:'g1fr-grm-053', chapterId:'g1fr-grammaire', difficulty:1, subsection:'determinants_le_la_les',
    question:'Complète : "___ fleur est rouge."',
    options:['La','Le','Les','L\''],
    answer:'La',
    hint:'"Fleur" est féminin singulier et commence par une consonne.',
    explanation:'On dit <b>la fleur</b> — féminin singulier, commence par "f" (consonne).' }),

  makeMCQ({ id:'g1fr-grm-054', chapterId:'g1fr-grammaire', difficulty:1, subsection:'phrases_simples_grm',
    question:'Laquelle de ces phrases est correcte ?',
    options:['Le chien est noir.','Noir est le chien.','Est le chien noir.','Le noir chien est.'],
    answer:'Le chien est noir.',
    hint:'En français : sujet + verbe + adjectif.',
    explanation:'<b>Le chien est noir.</b> est correcte : sujet (le chien) + verbe (est) + adjectif (noir).' }),

  makeMCQ({ id:'g1fr-grm-055', chapterId:'g1fr-grammaire', difficulty:1, subsection:'phrases_simples_grm',
    question:'Trouve l\'ordre correct : "mangent / Les / des pommes / enfants"',
    options:['Les enfants mangent des pommes.','Mangent les enfants des pommes.','Des pommes mangent les enfants.','Les pommes des enfants mangent.'],
    answer:'Les enfants mangent des pommes.',
    hint:'Commence par le sujet, puis le verbe, puis le reste.',
    explanation:'L\'ordre correct est : <b>Les enfants mangent des pommes.</b> Sujet + verbe + complément.' }),

  makeMCQ({ id:'g1fr-grm-056', chapterId:'g1fr-grammaire', difficulty:1, subsection:'phrases_simples_grm',
    question:'Dans "Lola aime les fleurs", quel est le verbe ?',
    options:['aime','Lola','les','fleurs'],
    answer:'aime',
    hint:'Le verbe est le mot d\'action dans la phrase.',
    explanation:'<b>Aime</b> est le verbe — c\'est l\'action que Lola fait.' }),

  makeMCQ({ id:'g1fr-grm-057', chapterId:'g1fr-grammaire', difficulty:1, subsection:'phrases_simples_grm',
    question:'Dans "Le lapin saute", quel est le sujet ?',
    options:['Le lapin','saute','Le','lapin saute'],
    answer:'Le lapin',
    hint:'Le sujet dit QUI fait l\'action.',
    explanation:'<b>Le lapin</b> est le sujet — c\'est lui qui fait l\'action de sauter.' }),

  makeMCQ({ id:'g1fr-grm-058', chapterId:'g1fr-grammaire', difficulty:1, subsection:'phrases_simples_grm',
    question:'Complète la phrase : "Le chat ___ sur le canapé."',
    options:['dort','rouge','vite','un'],
    answer:'dort',
    hint:'Il manque un verbe (une action) dans la phrase.',
    explanation:'<b>Le chat dort sur le canapé.</b> — "dort" est le verbe qui complète la phrase.' }),

  makeMCQ({ id:'g1fr-grm-059', chapterId:'g1fr-grammaire', difficulty:1, subsection:'phrases_simples_grm',
    question:'Laquelle de ces phrases a un sujet et un verbe ?',
    options:['La pluie tombe.','Une belle fleur.','Très chaud.','Beaucoup de fruits.'],
    answer:'La pluie tombe.',
    hint:'Une phrase complète a un sujet (qui ?) et un verbe (quoi ?).',
    explanation:'<b>La pluie tombe.</b> a un sujet (la pluie) et un verbe (tombe). Les autres n\'ont pas de verbe.' }),

  makeMCQ({ id:'g1fr-grm-060', chapterId:'g1fr-grammaire', difficulty:1, subsection:'phrases_simples_grm',
    question:'Quel mot complète la phrase : "Les élèves ___ la maîtresse."',
    options:['écoutent','beau','vite','un'],
    answer:'écoutent',
    hint:'Il manque un verbe. Que font les élèves ?',
    explanation:'<b>Les élèves écoutent la maîtresse.</b> — "écoutent" est le verbe qui montre l\'action.' })
);

})();
