'use strict';
(function () {

// NOTE: Set texts for NCE G9 French may change year to year.
// These questions target Le Papa de Simon (Maupassant) and Topaze (Pagnol),
// which have been on recent syllabi. Verify against the current MIE syllabus
// before use and update subsections papa_simon_* / topaze_* accordingly.

STATIC_QUESTIONS.push(

  // ── papa_simon_personnages (001-019) ────────────────────────────────────

  makeMCQ({ id:'g9fr-oev-001', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i> de Maupassant, quel est le prénom de l\'enfant principal ?',
    options:['Simon','Philippe','Henri','Marcel'],
    answer:'Simon',
    hint:'Le titre de la nouvelle contient le prénom de l\'enfant.',
    explanation:'L\'enfant s\'appelle <b>Simon</b>. La nouvelle raconte comment cet enfant, né hors mariage, est moqué par ses camarades parce qu\'il n\'a pas de père.' }),

  makeMCQ({ id:'g9fr-oev-002', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, comment s\'appelle l\'ouvrier forgeron qui devient le père adoptif de Simon ?',
    options:['Philippe Remy','Henri Dumont','Marcel Leblanc','Pierre Bonin'],
    answer:'Philippe Remy',
    hint:'C\'est un homme de grande stature, au cœur bon, qui travaille dans la forge.',
    explanation:'Le forgeron s\'appelle <b>Philippe Remy</b>. Il est grand, fort et bon. Touché par la détresse de Simon, il accepte d\'être son père et finit par épouser la mère, Blanche.' }),

  makeMCQ({ id:'g9fr-oev-003', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, comment s\'appelle la mère de Simon ?',
    options:['La Blanche','La Louve','Marie','Jeannette'],
    answer:'La Blanche',
    hint:'Son nom évoque sa pâleur et sa pureté.',
    explanation:'La mère de Simon s\'appelle <b>La Blanche</b> (Blanche Teston). Couturière, elle élève seule Simon après avoir été abandonnée par son séducteur. Son surnom évoque sa beauté et sa douceur.' }),

  makeMCQ({ id:'g9fr-oev-004', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, quel trait de caractère distingue principalement Philippe Remy ?',
    options:['Sa bonté et sa générosité','Sa colère et son impatience','Sa richesse et son arrogance','Sa timidité et son indifférence'],
    answer:'Sa bonté et sa générosité',
    hint:'Maupassant le présente comme un homme du peuple au grand cœur.',
    explanation:'Philippe Remy se distingue par sa <b>bonté et sa générosité</b>. Homme simple du peuple, il est profondément touché par la détresse de Simon et décide spontanément de lui offrir un père, puis d\'épouser sa mère.' }),

  makeMCQ({ id:'g9fr-oev-005', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, pourquoi Simon est-il persécuté par ses camarades à l\'école ?',
    options:['Parce qu\'il n\'a pas de père et est né hors mariage','Parce qu\'il est mauvais en classe','Parce qu\'il est d\'une autre région','Parce qu\'il est trop riche'],
    answer:'Parce qu\'il n\'a pas de père et est né hors mariage',
    hint:'La condition d\'enfant illégitime était très stigmatisée au XIXe siècle.',
    explanation:'Simon est persécuté parce qu\'il est <b>né hors mariage</b> (fils naturel) et n\'a pas de père. Au XIXe siècle, cette condition exposait l\'enfant à la honte sociale et aux moqueries des camarades qui répètent « t\'as pas d\'papa ».' }),

  makeMCQ({ id:'g9fr-oev-006', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, que fait Simon quand ses camarades se moquent de lui en lui disant qu\'il n\'a pas de père ?',
    options:['Il pleure et veut se noyer dans la rivière','Il se bat contre eux','Il court se plaindre à sa mère','Il rit avec eux'],
    answer:'Il pleure et veut se noyer dans la rivière',
    hint:'La détresse de Simon est si profonde qu\'il envisage le pire.',
    explanation:'Simon, désespéré par les moqueries, s\'enfuit, pleure au bord d\'une rivière et envisage de <b>s\'y noyer</b>. C\'est à ce moment que Philippe Remy le découvre et le réconforte.' }),

  makeMCQ({ id:'g9fr-oev-007', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, quel lien social unit finalement Philippe et la famille de Simon ?',
    options:['Philippe épouse Blanche et adopte légalement Simon','Philippe reste juste un ami de la famille','Philippe part sans se marier','Philippe devient le parrain de Simon'],
    answer:'Philippe épouse Blanche et adopte légalement Simon',
    hint:'La fin de la nouvelle est heureuse : la famille est reconstituée.',
    explanation:'Philippe <b>épouse Blanche</b> et devient ainsi le père légal de Simon. Cette fin est le résultat de la bonté spontanée de Philippe et de la grâce que Simon lui a accordée en le choisissant comme père.' }),

  makeMCQ({ id:'g9fr-oev-008', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, quelle est la profession de Philippe Remy ?',
    options:['Forgeron','Charpentier','Maçon','Pêcheur'],
    answer:'Forgeron',
    hint:'Il travaille les métaux à la forge.',
    explanation:'Philippe Remy est <b>forgeron</b> : il travaille dans une forge et est décrit comme un homme grand et fort, aux mains calleuses, dont la vigueur physique contraste avec sa douceur de cœur.' }),

  makeMCQ({ id:'g9fr-oev-009', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, pourquoi Blanche a-t-elle eu un enfant sans être mariée ?',
    options:['Elle a été séduite et abandonnée par un homme','Elle a choisi d\'être mère seule','Elle était veuve','Elle était trop pauvre pour se marier'],
    answer:'Elle a été séduite et abandonnée par un homme',
    hint:'Son histoire est celle d\'une femme victime d\'une séduction sans lendemain.',
    explanation:'Blanche a été <b>séduite par un homme qui l\'a ensuite abandonnée</b>. Cette situation, fréquente dans les nouvelles réalistes de Maupassant, dénonce le double standard moral de l\'époque : la femme est blâmée, l\'homme rarement.' }),

  makeMCQ({ id:'g9fr-oev-010', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, comment réagit Simon quand Philippe lui dit qu\'il sera son papa ?',
    options:['Il est immédiatement soulagé et heureux','Il refuse car Philippe n\'est pas son vrai père','Il s\'en va sans rien dire','Il pleure de tristesse'],
    answer:'Il est immédiatement soulagé et heureux',
    hint:'La réponse de Simon est instinctive et sincère.',
    explanation:'Simon accepte immédiatement avec <b>soulagement et bonheur</b>. Pour lui, l\'essentiel est d\'avoir un nom de père à donner quand ses camarades l\'interrogent. Il court annoncer à sa mère que « M. Philippe Remy, le forgeron, est son papa ».' }),

  makeMCQ({ id:'g9fr-oev-011', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, quelle dimension sociale Maupassant souligne-t-il à travers les personnages ?',
    options:['La dignité des gens du peuple face aux préjugés bourgeois','La supériorité des classes riches','L\'indifférence de la société aux enfants','Le bonheur de la vie à la campagne'],
    answer:'La dignité des gens du peuple face aux préjugés bourgeois',
    hint:'Maupassant est souvent du côté des humbles dans ses nouvelles.',
    explanation:'Maupassant souligne la <b>dignité des gens simples et du peuple</b> (Blanche, Philippe) face aux préjugés de la société bourgeoise. Philippe et Blanche, des gens ordinaires, font preuve d\'une humanité et d\'une générosité que les gens « bien » n\'ont pas.' }),

  makeMCQ({ id:'g9fr-oev-012', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, quel sentiment éprouve principalement Simon tout au long de la nouvelle ?',
    options:['La honte et le désespoir liés à l\'absence de père','La joie et l\'insouciance','La jalousie envers ses camarades','La colère contre sa mère'],
    answer:'La honte et le désespoir liés à l\'absence de père',
    hint:'Simon souffre d\'une blessure sociale profonde.',
    explanation:'Simon éprouve principalement <b>la honte et le désespoir</b> liés au manque de père. Cette blessure sociale est si profonde qu\'elle le pousse jusqu\'aux pensées suicidaires. La rencontre avec Philippe va transformer ce désespoir en bonheur.' }),

  makeMCQ({ id:'g9fr-oev-013', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, comment les camarades de Simon réagissent-ils quand il annonce que son père est Philippe Remy, le forgeron ?',
    options:['Ils se taisent car Philippe est imposant et respecté','Ils se moquent encore plus','Ils deviennent amis avec Simon','Ils racontent l\'histoire à leurs parents'],
    answer:'Ils se taisent car Philippe est imposant et respecté',
    hint:'La stature physique et la réputation du forgeron imposent le respect.',
    explanation:'Quand Simon annonce que son père est <b>Philippe Remy, le forgeron</b> — homme grand, fort et respecté du village — ses camarades se taisent, impressionnés par la réputation de cet homme. La solution de Simon est à la fois naïve et efficace.' }),

  makeMCQ({ id:'g9fr-oev-014', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Quel genre littéraire est <i>Le Papa de Simon</i> ?',
    options:['Une nouvelle réaliste','Un roman','Un poème','Une pièce de théâtre'],
    answer:'Une nouvelle réaliste',
    hint:'C\'est un texte court qui dépeint la réalité sociale du XIXe siècle.',
    explanation:'<b>Le Papa de Simon</b> est une <b>nouvelle réaliste</b> : texte court, ancré dans une réalité sociale précise (la France du XIXe siècle), avec des personnages issus du peuple. Maupassant est l\'un des maîtres du genre.' }),

  makeMCQ({ id:'g9fr-oev-015', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, quel rôle joue la nature (la rivière, les champs) dans le récit ?',
    options:['Elle reflète l\'état émotionnel de Simon et accompagne sa détresse','Elle est simplement un décor neutre','Elle symbolise la richesse de la région','Elle est un obstacle à l\'intrigue'],
    answer:'Elle reflète l\'état émotionnel de Simon et accompagne sa détresse',
    hint:'Maupassant utilise le paysage comme miroir des émotions.',
    explanation:'La nature dans cette nouvelle joue un rôle de <b>miroir émotionnel</b> : la rivière calme attire Simon dans son désespoir suicidaire ; les herbes vertes et la lumière du soir accompagnent la rencontre apaisante avec Philippe. C\'est le procédé du paysage-état d\'âme.' }),

  makeMCQ({ id:'g9fr-oev-016', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, Maupassant décrit Philippe Remy comme « un grand gaillard fort ». Que signifie « gaillard » ?',
    options:['Un homme vigoureux et en bonne santé','Un homme vieux et fatigué','Un homme riche','Un homme méchant'],
    answer:'Un homme vigoureux et en bonne santé',
    hint:'Ce terme désigne un homme plein de vitalité et de force physique.',
    explanation:'<b>Gaillard</b> désigne un homme robuste, vigoureux et plein de vitalité. L\'expression « grand gaillard fort » souligne la stature imposante de Philippe Remy, ce qui contraste avec sa sensibilité et sa bonté.' }),

  makeMCQ({ id:'g9fr-oev-017', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, quelle valeur principale Maupassant défend-il ?',
    options:['La solidarité humaine face à la cruauté des préjugés sociaux','La supériorité de la classe noble','Le mariage comme seule voie honorable','La vengeance comme réponse à l\'injustice'],
    answer:'La solidarité humaine face à la cruauté des préjugés sociaux',
    hint:'La bonté spontanée de Philippe illustre cette valeur.',
    explanation:'Maupassant défend la valeur de la <b>solidarité humaine</b> : Philippe, homme simple et bon, aide Simon et Blanche sans calcul. Face à la cruauté des préjugés (le statut d\'enfant illégitime), c\'est l\'humanité des gens du peuple qui triomphe.' }),

  makeMCQ({ id:'g9fr-oev-018', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, quel auteur a écrit cette nouvelle ?',
    options:['Guy de Maupassant','Victor Hugo','Émile Zola','Gustave Flaubert'],
    answer:'Guy de Maupassant',
    hint:'C\'est l\'un des plus grands nouvellistes français du XIXe siècle.',
    explanation:'<b>Guy de Maupassant</b> (1850-1893) est l\'auteur du <i>Papa de Simon</i>. Maître de la nouvelle réaliste et naturaliste, il est aussi l\'auteur de <i>Boule de suif</i>, <i>La Parure</i> et du roman <i>Bel-Ami</i>.' }),

  makeMCQ({ id:'g9fr-oev-019', chapterId:'g9fr-oeuvres', subsection:'papa_simon_personnages', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, comment Maupassant montre-t-il que l\'enfance est vulnérable face aux préjugés des adultes ?',
    options:['Simon souffre d\'une situation qu\'il n\'a pas choisie et ne comprend pas totalement','Simon choisit volontairement de vivre sans père','Les adultes protègent toujours les enfants','Simon comprend dès le début comment résoudre son problème'],
    answer:'Simon souffre d\'une situation qu\'il n\'a pas choisie et ne comprend pas totalement',
    hint:'Simon est victime d\'une condition sociale imposée par les adultes.',
    explanation:'Maupassant montre la vulnérabilité de l\'enfance : Simon <b>souffre d\'une situation qu\'il n\'a pas choisie</b> (sa naissance hors mariage). Il ne comprend pas totalement les raisons de sa souffrance, mais il en ressent la douleur avec une intensité totale.' }),

  // ── papa_simon_themes (020-038) ────────────────────────────────────────

  makeMCQ({ id:'g9fr-oev-020', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:2,
    question:'Quel est le thème central de <i>Le Papa de Simon</i> de Maupassant ?',
    options:['La quête d\'un père et la stigmatisation des enfants illégitimes','La vie des forgerons au XIXe siècle','La jalousie entre frères','Les aventures d\'un enfant à la campagne'],
    answer:'La quête d\'un père et la stigmatisation des enfants illégitimes',
    hint:'Le titre lui-même annonce le thème.',
    explanation:'Le thème central est la <b>quête d\'un père</b> et la souffrance liée à la <b>stigmatisation de l\'illégitimité</b> au XIXe siècle. Simon souffre d\'une blessure sociale que seule la bonté de Philippe peut guérir.' }),

  makeMCQ({ id:'g9fr-oev-021', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:2,
    question:'Quel thème secondaire important apparaît dans <i>Le Papa de Simon</i> ?',
    options:['La bonté désintéressée et la solidarité','La vengeance sociale','L\'ambition des classes populaires','L\'aventure et le voyage'],
    answer:'La bonté désintéressée et la solidarité',
    hint:'Philippe aide Simon sans attendre de récompense.',
    explanation:'Le thème de la <b>bonté désintéressée</b> est central : Philippe aide Simon spontanément, sans calcul. La solidarité naturelle des gens simples face à la souffrance d\'un enfant est un thème récurrent chez Maupassant.' }),

  makeMCQ({ id:'g9fr-oev-022', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:3,
    question:'Comment Maupassant aborde-t-il le thème de la honte sociale dans <i>Le Papa de Simon</i> ?',
    options:['Il montre que la honte sociale infligée à un enfant innocent est cruelle et injuste','Il montre que Simon mérite cette honte','Il défend la morale bourgeoise de son époque','Il ignore la dimension sociale pour se concentrer sur l\'aventure'],
    answer:'Il montre que la honte sociale infligée à un enfant innocent est cruelle et injuste',
    hint:'Maupassant prend parti pour les victimes des préjugés.',
    explanation:'Maupassant dénonce la <b>cruauté de la honte sociale</b> infligée à un enfant innocent qui n\'est pas responsable de sa naissance. Cette critique sociale voilée est typique de son réalisme : il observe et dénonce sans moraliser ouvertement.' }),

  makeMCQ({ id:'g9fr-oev-023', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, le thème de la famille est traité de quelle façon ?',
    options:['Maupassant montre qu\'une famille peut se construire sur le choix et l\'amour, pas seulement sur la biologie','Il défend le modèle familial traditionnel uniquement','Il montre que la famille est inutile','Il ignore le thème de la famille'],
    answer:'Maupassant montre qu\'une famille peut se construire sur le choix et l\'amour, pas seulement sur la biologie',
    hint:'La famille Simon-Philippe-Blanche n\'est pas fondée sur le sang.',
    explanation:'Maupassant propose une vision moderne de la famille : elle se construit sur <b>le choix, l\'amour et la responsabilité</b>. Philippe n\'est pas le père biologique de Simon, mais il choisit d\'assumer ce rôle, ce qui fait de lui un vrai père.' }),

  makeMCQ({ id:'g9fr-oev-024', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, quel thème universel la nouvelle aborde-t-elle en dehors du contexte du XIXe siècle ?',
    options:['Le besoin d\'appartenance et d\'identité familiale','La supériorité de la France rurale','La vie industrielle','Les voyages d\'exploration'],
    answer:'Le besoin d\'appartenance et d\'identité familiale',
    hint:'Ce besoin est universel, quel que soit le siècle.',
    explanation:'Au-delà du contexte historique, la nouvelle touche au thème universel du <b>besoin d\'appartenance et d\'identité familiale</b>. Tout enfant a besoin de savoir qui il est et d\'où il vient pour se construire. Ce besoin transcende le XIXe siècle.' }),

  makeMCQ({ id:'g9fr-oev-025', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:2,
    question:'Quel aspect de la société du XIXe siècle <i>Le Papa de Simon</i> critique-t-il implicitement ?',
    options:['Le double standard moral qui condamne la mère célibataire mais pas le séducteur','La pauvreté de la classe ouvrière uniquement','La religion catholique','L\'éducation nationale'],
    answer:'Le double standard moral qui condamne la mère célibataire mais pas le séducteur',
    hint:'Blanche est blâmée alors que le père de Simon n\'est jamais mentionné.',
    explanation:'Maupassant critique le <b>double standard moral</b> de la société bourgeoise du XIXe siècle : Blanche est stigmatisée pour avoir eu un enfant hors mariage, tandis que l\'homme qui l\'a séduite puis abandonnée n\'est jamais nommé ni condamné.' }),

  makeMCQ({ id:'g9fr-oev-026', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, quel est le rapport entre le titre et le thème de l\'identité ?',
    options:['Le titre « Le Papa de Simon » signifie que trouver un père est trouver une identité sociale','Le titre n\'a aucun rapport avec l\'identité','Le titre parle uniquement de la profession du père','Le titre est ironique'],
    answer:'Le titre « Le Papa de Simon » signifie que trouver un père est trouver une identité sociale',
    hint:'Avoir un père, c\'est avoir un nom et une place dans la société.',
    explanation:'Le titre concentre le thème de l\'identité : <b>trouver un papa, c\'est trouver une identité sociale</b>. Au XIXe siècle, un enfant sans père n\'avait pas de nom légal ni de place définie dans la société. Philippe donne à Simon cette identité.' }),

  makeMCQ({ id:'g9fr-oev-027', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:2,
    question:'Dans <i>Le Papa de Simon</i>, quel thème est illustré par la réaction des camarades de Simon ?',
    options:['La cruauté des enfants qui répètent les préjugés des adultes','La générosité des enfants','L\'amitié enfantine','L\'ennui à l\'école'],
    answer:'La cruauté des enfants qui répètent les préjugés des adultes',
    hint:'Les enfants sont le miroir de la société des adultes.',
    explanation:'Les camarades de Simon illustrent le thème de la <b>cruauté des enfants</b> qui reproduisent les préjugés des adultes. Les enfants ne comprennent pas vraiment ce qu\'ils disent, mais ils font souffrir Simon en répétant les jugements de leurs parents.' }),

  makeMCQ({ id:'g9fr-oev-028', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:3,
    question:'Quel procédé narratif Maupassant utilise-t-il pour rendre les thèmes plus émouvants ?',
    options:['Le point de vue de l\'enfant, qui perçoit la réalité avec innocence','Un narrateur omniscient froid et distant','Des discours politiques','Des descriptions scientifiques'],
    answer:'Le point de vue de l\'enfant, qui perçoit la réalité avec innocence',
    hint:'Voir le monde à travers les yeux de Simon rend tout plus intense.',
    explanation:'Maupassant utilise le point de vue de l\'<b>enfant</b> pour rendre les thèmes plus émouvants : Simon perçoit le monde avec innocence et intensité. Sa réaction au désespoir (vouloir se noyer) et sa joie naïve (choisir un père) touchent le lecteur directement.' }),

  makeMCQ({ id:'g9fr-oev-029', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:2,
    question:'Comment se résout le conflit thématique entre honte sociale et dignité dans <i>Le Papa de Simon</i> ?',
    options:['La bonté de Philippe triomphe de la honte sociale et redonne à Simon sa dignité','La honte reste jusqu\'à la fin','Simon quitte le village pour fuir la honte','La mère change de comportement pour effacer la honte'],
    answer:'La bonté de Philippe triomphe de la honte sociale et redonne à Simon sa dignité',
    hint:'La nouvelle a une fin heureuse grâce à Philippe.',
    explanation:'Le conflit se résout par un dénouement heureux : la <b>bonté de Philippe</b> triomphe des préjugés. En devenant le père de Simon et en épousant Blanche, il redonne à la famille une place légitime dans la société, restaurant leur dignité.' }),

  makeMCQ({ id:'g9fr-oev-030', chapterId:'g9fr-oeuvres', subsection:'papa_simon_themes', difficulty:3,
    question:'Dans <i>Le Papa de Simon</i>, quel thème est suggéré par la phrase de Simon : « Je veux me noyer parce que je n\'ai pas de papa. » ?',
    options:['Le désespoir de l\'exclusion sociale peut être fatal même pour un enfant','L\'amour de la rivière','La peur de nager','La colère contre les adultes'],
    answer:'Le désespoir de l\'exclusion sociale peut être fatal même pour un enfant',
    hint:'Maupassant ne minimise pas la souffrance de Simon.',
    explanation:'Cette phrase choc révèle que l\'<b>exclusion sociale peut pousser même un enfant au désespoir absolu</b>. Maupassant ne minimise pas la souffrance : l\'exclusion peut avoir des conséquences mortelles, et seule la solidarité humaine peut y répondre.' }),

  // ── topaze_personnages (031-049) ───────────────────────────────────────

  makeMCQ({ id:'g9fr-oev-031', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:2,
    question:'Dans <i>Topaze</i> de Marcel Pagnol, quel est le métier initial du personnage principal Topaze ?',
    options:['Professeur','Médecin','Commerçant','Avocat'],
    answer:'Professeur',
    hint:'Il enseigne dans une école privée au début de la pièce.',
    explanation:'Topaze est <b>professeur</b> dans une école privée à Paris. Au début de la pièce, c\'est un homme honnête, idéaliste et naïf qui croit sincèrement aux valeurs morales qu\'il enseigne.' }),

  makeMCQ({ id:'g9fr-oev-032', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:2,
    question:'Dans <i>Topaze</i>, quel est le prénom complet du personnage principal ?',
    options:['Octave Topaze','Henri Topaze','Marcel Topaze','Pierre Topaze'],
    answer:'Octave Topaze',
    hint:'Pagnol n\'utilise que le nom de famille dans la plupart des scènes.',
    explanation:'Le personnage s\'appelle <b>Octave Topaze</b>. Il est présenté comme un professeur honnête mais trop naïf, qui sera transformé par le contact avec la corruption et les compromis du monde réel.' }),

  makeMCQ({ id:'g9fr-oev-033', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:3,
    question:'Dans <i>Topaze</i>, quel personnage symbolise la corruption et la manipulation politique ?',
    options:['Castel-Bénac','Tamise','M. Muche','Roger de Berville'],
    answer:'Castel-Bénac',
    hint:'C\'est un conseiller municipal qui tire les ficelles dans l\'ombre.',
    explanation:'<b>Castel-Bénac</b> est le conseiller municipal corrompu qui manipule les élections et les affaires publiques à son profit. Il représente la corruption du monde politique et initie indirectement Topaze à ses pratiques.' }),

  makeMCQ({ id:'g9fr-oev-034', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:2,
    question:'Dans <i>Topaze</i>, comment s\'appelle la maîtresse de Castel-Bénac qui joue un rôle important dans la transformation de Topaze ?',
    options:['Suzy Courtois','Marie Dupont','Hélène Martin','Blanche Remy'],
    answer:'Suzy Courtois',
    hint:'Cette femme élégante est l\'intermédiaire entre Castel-Bénac et Topaze.',
    explanation:'<b>Suzy Courtois</b> est la maîtresse de Castel-Bénac. Belle et pragmatique, elle joue un rôle d\'intermédiaire et contribue à la transformation de Topaze, qui finit par tomber amoureux d\'elle.' }),

  makeMCQ({ id:'g9fr-oev-035', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:3,
    question:'Dans <i>Topaze</i>, comment évolue le personnage principal tout au long de la pièce ?',
    options:['D\'un professeur honnête et naïf à un homme d\'affaires cynique et corrompu','D\'un homme corrompu à un homme vertueux','De la richesse à la pauvreté','D\'un professeur à un politicien idéaliste'],
    answer:'D\'un professeur honnête et naïf à un homme d\'affaires cynique et corrompu',
    hint:'La pièce retrace une désillusion progressive.',
    explanation:'Topaze évolue de façon tragique : il passe d\'un <b>professeur honnête et naïf</b> à un <b>homme d\'affaires cynique</b> qui utilise les mêmes méthodes corrompues qu\'il dénonçait. C\'est la grande ironie de la pièce.' }),

  makeMCQ({ id:'g9fr-oev-036', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:2,
    question:'Dans <i>Topaze</i>, pourquoi Topaze est-il renvoyé de son école au début de la pièce ?',
    options:['Parce qu\'il refuse de changer la note d\'un élève dont les parents sont influents','Parce qu\'il est mauvais professeur','Parce qu\'il est en retard trop souvent','Parce qu\'il a volé de l\'argent'],
    answer:'Parce qu\'il refuse de changer la note d\'un élève dont les parents sont influents',
    hint:'Son honnêteté cause sa perte dans un système corrompu.',
    explanation:'Topaze est renvoyé parce qu\'il <b>refuse de falsifier les notes</b> d\'un élève dont les parents sont riches et influents. Son directeur, M. Muche, lui demande d\'obéir aux pressions extérieures. L\'honnêteté de Topaze lui coûte son emploi.' }),

  makeMCQ({ id:'g9fr-oev-037', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:3,
    question:'Dans <i>Topaze</i>, quel rôle joue M. Muche dans la pièce ?',
    options:['Le directeur de l\'école, hypocrite et soumis aux pressions des riches parents','Le héros vertueux','L\'ami fidèle de Topaze','Le politicien honnête'],
    answer:'Le directeur de l\'école, hypocrite et soumis aux pressions des riches parents',
    hint:'Il représente la compromission institutionnelle.',
    explanation:'<b>M. Muche</b> est le directeur de l\'école privée. Il représente l\'<b>hypocrisie institutionnelle</b> : en apparence respectueux des valeurs morales, il se soumet en réalité aux pressions des parents riches et renvoie Topaze pour avoir été honnête.' }),

  makeMCQ({ id:'g9fr-oev-038', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:2,
    question:'Dans <i>Topaze</i>, quelle phrase symbolique Topaze dit-il à la fin pour illustrer sa transformation ?',
    options:['« J\'ai compris. »','« La morale, c\'est la vertu. »','« Je reste honnête. »','« L\'argent ne fait pas le bonheur. »'],
    answer:'« J\'ai compris. »',
    hint:'Cette phrase courte résume toute la désillusion du personnage.',
    explanation:'La phrase <b>« J\'ai compris »</b> (dans certaines versions de la pièce) symbolise la capitulation morale de Topaze. Il a « compris » que dans le monde réel, les honnêtes gens perdent et que la corruption paye. C\'est le moment où il bascule.' }),

  makeMCQ({ id:'g9fr-oev-039', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:3,
    question:'Dans <i>Topaze</i>, quel type de personnage Topaze représente-t-il au début de la pièce (type littéraire) ?',
    options:['Le naïf ou l\'idéaliste qui découvre la réalité du monde','Le héros tragique classique','Le méchant hypocrite','Le jeune ambitieux sans scrupules'],
    answer:'Le naïf ou l\'idéaliste qui découvre la réalité du monde',
    hint:'Topaze croit sincèrement aux valeurs qu\'il enseigne.',
    explanation:'Au début, Topaze est le type du <b>naïf ou de l\'idéaliste</b> : il croit sincèrement que la vertu est récompensée et que le monde fonctionne selon les principes moraux qu\'il enseigne. Sa transformation constitue la désillusion centrale de la pièce.' }),

  makeMCQ({ id:'g9fr-oev-040', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:2,
    question:'Dans <i>Topaze</i>, quel genre dramatique cette pièce représente-t-elle ?',
    options:['Une comédie satirique','Une tragédie classique','Un drame romantique','Un vaudeville'],
    answer:'Une comédie satirique',
    hint:'Elle fait rire mais dénonce des travers sociaux sérieux.',
    explanation:'<i>Topaze</i> est une <b>comédie satirique</b> : elle utilise l\'humour et le comique de situation pour dénoncer la corruption politique, le cynisme de la bourgeoisie et la naïveté des idéalistes. Le rire y est un outil critique.' }),

  makeMCQ({ id:'g9fr-oev-041', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:3,
    question:'Dans <i>Topaze</i>, quel est le paradoxe final de la situation de Topaze ?',
    options:['Il réussit matériellement en devenant corrompu, mais perd ses valeurs morales','Il échoue matériellement mais garde ses valeurs','Il réussit à la fois moralement et matériellement','Il ne change pas du tout'],
    answer:'Il réussit matériellement en devenant corrompu, mais perd ses valeurs morales',
    hint:'Le succès de Topaze a un prix moral.',
    explanation:'Le paradoxe de Topaze est qu\'il <b>réussit matériellement</b> (richesse, pouvoir, l\'amour de Suzy) en <b>abandonnant ses valeurs morales</b>. C\'est la critique centrale de Pagnol : dans la société du XXe siècle, la corruption paye mieux que la vertu.' }),

  makeMCQ({ id:'g9fr-oev-042', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:2,
    question:'Dans <i>Topaze</i>, quel auteur français a écrit cette pièce ?',
    options:['Marcel Pagnol','Albert Camus','Jean-Paul Sartre','Jean Anouilh'],
    answer:'Marcel Pagnol',
    hint:'Cet auteur est aussi célèbre pour ses films et sa trilogie marseillaise.',
    explanation:'<b>Marcel Pagnol</b> (1895-1974) a écrit <i>Topaze</i> en 1928. Écrivain, dramaturge et cinéaste, il est aussi l\'auteur de la trilogie marseillaise (<i>Marius, Fanny, César</i>) et de <i>La Gloire de mon père</i>.' }),

  makeMCQ({ id:'g9fr-oev-043', chapterId:'g9fr-oeuvres', subsection:'topaze_personnages', difficulty:3,
    question:'Dans <i>Topaze</i>, quel est le rapport entre Tamise et Topaze au début de la pièce ?',
    options:['Tamise est le collègue plus expérimenté qui conseille (mal) Topaze','Tamise est l\'ennemi de Topaze','Tamise est le directeur de l\'école','Tamise est l\'élève préféré de Topaze'],
    answer:'Tamise est le collègue plus expérimenté qui conseille (mal) Topaze',
    hint:'Ce collègue connaît les règles du jeu, mais pas toujours dans le bon sens.',
    explanation:'<b>Tamise</b> est le collègue de Topaze qui connaît mieux les réalités du monde. Il conseille Topaze (souvent dans le mauvais sens) et illustre les compromis que fait un homme ordinaire pour survivre dans un système corrompu.' }),

  // ── topaze_themes (044-062) ────────────────────────────────────────────

  makeMCQ({ id:'g9fr-oev-044', chapterId:'g9fr-oeuvres', subsection:'topaze_themes', difficulty:2,
    question:'Quel est le thème principal de <i>Topaze</i> de Marcel Pagnol ?',
    options:['La corruption et la désillusion morale dans la société','L\'amour romantique impossible','La vie à la campagne en Provence','Les aventures d\'un héros vertueux'],
    answer:'La corruption et la désillusion morale dans la société',
    hint:'La pièce montre comment un homme honnête devient corrompu.',
    explanation:'Le thème principal est la <b>corruption morale</b> et la <b>désillusion</b> : Topaze, professeur idéaliste, se transforme en homme d\'affaires cynique. Pagnol critique la société où la corruption est plus profitable que la vertu.' }),

  makeMCQ({ id:'g9fr-oev-045', chapterId:'g9fr-oeuvres', subsection:'topaze_themes', difficulty:2,
    question:'Dans <i>Topaze</i>, quel thème est illustré par le fait que Topaze est renvoyé pour avoir été honnête ?',
    options:['La vertu punie et le vice récompensé dans la société réelle','La paresse récompensée','Le mérite reconnu','La justice toujours victorieuse'],
    answer:'La vertu punie et le vice récompensé dans la société réelle',
    hint:'Le paradoxe central de la pièce.',
    explanation:'La pièce illustre le paradoxe amer : la <b>vertu est punie</b> (Topaze perd son emploi pour avoir été honnête) et le <b>vice est récompensé</b> (les corrompus réussissent). C\'est la critique sociale centrale de Pagnol.' }),

  makeMCQ({ id:'g9fr-oev-046', chapterId:'g9fr-oeuvres', subsection:'topaze_themes', difficulty:3,
    question:'Dans <i>Topaze</i>, quel rôle joue l\'argent comme thème ?',
    options:['L\'argent est présenté comme le moteur de la corruption et de la perte des valeurs','L\'argent est présenté comme indispensable et honorable','L\'argent est absent de la pièce','L\'argent est le symbole de la liberté'],
    answer:'L\'argent est présenté comme le moteur de la corruption et de la perte des valeurs',
    hint:'Tous les compromis de la pièce sont liés à l\'argent.',
    explanation:'L\'<b>argent</b> est le thème transversal de <i>Topaze</i> : c\'est la promesse d\'argent et de confort qui pousse Topaze à accepter les compromis. Pagnol montre que l\'argent corrompt les idéaux et transforme les hommes.' }),

  makeMCQ({ id:'g9fr-oev-047', chapterId:'g9fr-oeuvres', subsection:'topaze_themes', difficulty:2,
    question:'Dans <i>Topaze</i>, quel thème est lié à la critique du système éducatif ?',
    options:['L\'hypocrisie d\'une école qui enseigne la morale mais s\'y plie pas','La nécessité d\'une réforme pédagogique','L\'excellence des enseignants français','La valeur des diplômes'],
    answer:'L\'hypocrisie d\'une école qui enseigne la morale mais s\'y plie pas',
    hint:'L\'école de M. Muche prêche une chose et en fait une autre.',
    explanation:'Pagnol critique l\'<b>hypocrisie du système éducatif</b> : l\'école enseigne les valeurs morales mais se soumet aux pressions des riches parents. M. Muche incarne cette contradiction : il prêche la vertu mais la sacrifie aux intérêts matériels.' }),

  makeMCQ({ id:'g9fr-oev-048', chapterId:'g9fr-oeuvres', subsection:'topaze_themes', difficulty:3,
    question:'Dans <i>Topaze</i>, comment le thème de l\'apparence versus la réalité est-il développé ?',
    options:['Les personnages se donnent une apparence de respectabilité qui cache leur corruption réelle','Tous les personnages sont ce qu\'ils semblent être','L\'apparence est plus importante que la réalité','La réalité est toujours juste'],
    answer:'Les personnages se donnent une apparence de respectabilité qui cache leur corruption réelle',
    hint:'Pagnol dénonce le vernis de respectabilité de la bourgeoisie.',
    explanation:'Le thème de l\'<b>apparence versus la réalité</b> est central : Castel-Bénac paraît respectable mais est corrompu, M. Muche paraît vertueux mais est hypocrite. Pagnol dénonce le <b>vernis de respectabilité</b> de la bourgeoisie qui cache ses turpitudes.' }),

  makeMCQ({ id:'g9fr-oev-049', chapterId:'g9fr-oeuvres', subsection:'topaze_themes', difficulty:2,
    question:'Dans <i>Topaze</i>, quel thème la transformation finale de Topaze illustre-t-elle ?',
    options:['L\'adaptation cynique à un système corrompu comme condition de survie','Le triomphe de la vertu','La rédemption morale','L\'inutilité de l\'éducation'],
    answer:'L\'adaptation cynique à un système corrompu comme condition de survie',
    hint:'Topaze « réussit » en adoptant les méthodes qu\'il condamnait.',
    explanation:'La transformation de Topaze illustre le thème amer de l\'<b>adaptation cynique</b> : pour « survivre » et réussir dans la société, il adopte les méthodes corrompues qu\'il condamnait. C\'est une critique de la société plus qu\'un jugement sur Topaze lui-même.' }),

  // ── question_longue (063-095) ──────────────────────────────────────────

  makeMCQ({ id:'g9fr-oev-050', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Comment structurer une réponse longue à une question sur une œuvre littéraire au niveau NCE ?',
    options:['Introduction (présenter l\'œuvre et la question) → Développement (2-3 arguments avec citations) → Conclusion (synthèse)','Écrire le plus possible sans structure','Copier des extraits de l\'œuvre sans analyse','Répondre en une seule phrase longue'],
    answer:'Introduction (présenter l\'œuvre et la question) → Développement (2-3 arguments avec citations) → Conclusion (synthèse)',
    hint:'La structure d\'une réponse longue est celle d\'un mini-essai.',
    explanation:'Une réponse longue structurée comprend : une <b>introduction</b> (contextualiser l\'œuvre et reformuler la question), un <b>développement</b> (2-3 arguments illustrés par des citations ou des références précises), et une <b>conclusion</b> (synthèse et ouverture possible).' }),

  makeMCQ({ id:'g9fr-oev-051', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Pourquoi faut-il utiliser des citations du texte dans une réponse longue sur une œuvre littéraire ?',
    options:['Pour prouver son interprétation par des preuves textuelles directes','Pour montrer qu\'on a lu le livre','Pour augmenter la longueur de la réponse','Parce que c\'est une obligation réglementaire'],
    answer:'Pour prouver son interprétation par des preuves textuelles directes',
    hint:'Une citation est une preuve textuelle.',
    explanation:'Les citations servent de <b>preuves textuelles</b> : elles montrent que l\'interprétation est fondée sur le texte lui-même et non sur une impression vague. « Montrer » puis « analyser » la citation est la méthode idéale.' }),

  makeMCQ({ id:'g9fr-oev-052', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une question longue sur <i>Le Papa de Simon</i>, comment analyser le comportement de Philippe ?',
    options:['Identifier ses actions, les relier au thème de la générosité, et citer le texte','Décrire son apparence physique uniquement','Résumer l\'intrigue sans analyser','Comparer Philippe à un personnage de Harry Potter'],
    answer:'Identifier ses actions, les relier au thème de la générosité, et citer le texte',
    hint:'Analyse = actions + thème + preuve textuelle.',
    explanation:'Pour analyser le comportement de Philippe : 1) identifier ses <b>actions</b> (il réconforte Simon, propose d\'être son père, épouse Blanche) ; 2) les relier au <b>thème</b> (générosité, solidarité) ; 3) appuyer avec une <b>citation</b> du texte.' }),

  makeMCQ({ id:'g9fr-oev-053', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Quel temps verbal est correct pour parler d\'un personnage dans une réponse longue sur une œuvre littéraire ?',
    options:['Le présent de l\'indicatif (présent de narration)','Le futur','L\'imparfait uniquement','Le conditionnel'],
    answer:'Le présent de l\'indicatif (présent de narration)',
    hint:'On parle d\'un texte au présent car le texte existe toujours.',
    explanation:'Par convention littéraire, on utilise le <b>présent de narration</b> pour parler des œuvres et des personnages : « Simon <i>souffre</i>… », « Topaze <i>abandonne</i> ses valeurs… ». Le texte est considéré comme toujours vivant.' }),

  makeMCQ({ id:'g9fr-oev-054', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Quelle est la différence entre un résumé et une analyse littéraire dans une réponse longue ?',
    options:['Le résumé raconte ce qui se passe ; l\'analyse explique pourquoi et comment c\'est écrit','Le résumé est plus long que l\'analyse','L\'analyse est uniquement une liste de citations','Il n\'y a aucune différence'],
    answer:'Le résumé raconte ce qui se passe ; l\'analyse explique pourquoi et comment c\'est écrit',
    hint:'L\'analyse va au-delà des événements.',
    explanation:'Un <b>résumé</b> = raconter les événements (quoi). Une <b>analyse</b> = expliquer pourquoi les choses sont comme elles sont (pourquoi) et comment l\'auteur les exprime (comment). Dans une réponse longue, on doit analyser, pas résumer.' }),

  makeMCQ({ id:'g9fr-oev-055', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Quelle est la meilleure façon d\'introduire une citation dans une réponse longue ?',
    options:['Contextualiser la citation puis la citer entre guillemets : « Comme le dit l\'auteur : ‹ citation › »','La copier sans introduction','La paraphraser sans guillemets','La mettre en gras uniquement'],
    answer:'Contextualiser la citation puis la citer entre guillemets : « Comme le dit l\'auteur : ‹ citation › »',
    hint:'Une citation doit être introduite et commentée.',
    explanation:'La méthode correcte : 1) <b>contextualiser</b> (situer dans le texte), 2) <b>citer entre guillemets</b>, 3) <b>analyser</b> ce que la citation révèle. Une citation non analysée n\'apporte aucune valeur à la réponse.' }),

  makeMCQ({ id:'g9fr-oev-056', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une question longue sur <i>Topaze</i> demandant de « commenter l\'évolution du personnage principal », quelle erreur est la plus grave ?',
    options:['Décrire uniquement l\'aspect physique de Topaze sans parler de son évolution morale','Utiliser des exemples précis de la pièce','Structurer la réponse en introduction/développement/conclusion','Analyser les motivations de Topaze'],
    answer:'Décrire uniquement l\'aspect physique de Topaze sans parler de son évolution morale',
    hint:'La question porte sur l\'évolution du personnage, pas son apparence.',
    explanation:'L\'erreur la plus grave est de passer à côté de la question : décrire l\'<b>aspect physique</b> de Topaze ne répond pas à la question sur son <b>évolution morale</b>. Une réponse hors-sujet, même bien écrite, obtient peu de points.' }),

  makeMCQ({ id:'g9fr-oev-057', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Pourquoi est-il important de reformuler la question dans l\'introduction d\'une réponse longue ?',
    options:['Pour montrer qu\'on a compris la question et pour annoncer le plan','Pour augmenter la longueur','Parce que la question originale est mal formulée','Pour copier la consigne et gagner du temps'],
    answer:'Pour montrer qu\'on a compris la question et pour annoncer le plan',
    hint:'La reformulation prouve la compréhension.',
    explanation:'Reformuler la question dans l\'introduction permet de montrer qu\'on a <b>compris ce qui est demandé</b> et d\'annoncer la direction de la réponse. C\'est aussi l\'occasion d\'introduire l\'œuvre et l\'auteur.' }),

  makeMCQ({ id:'g9fr-oev-058', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Comment conclure efficacement une réponse longue sur une œuvre littéraire ?',
    options:['Synthétiser les arguments développés et éventuellement ouvrir sur un thème plus large','Répéter mot pour mot l\'introduction','Ajouter de nouveaux arguments non développés','Terminer par une citation non commentée'],
    answer:'Synthétiser les arguments développés et éventuellement ouvrir sur un thème plus large',
    hint:'La conclusion est une synthèse, pas une répétition.',
    explanation:'Une bonne conclusion : 1) <b>synthétise</b> les arguments développés (sans les répéter mot pour mot) ; 2) répond clairement à la question initiale ; 3) peut <b>ouvrir</b> sur un thème plus large ou une réflexion personnelle.' }),

  makeMCQ({ id:'g9fr-oev-059', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue sur <i>Le Papa de Simon</i>, quelle est la meilleure façon d\'analyser le thème de la solidarité ?',
    options:['Définir la solidarité, l\'illustrer par les actions de Philippe, et relier à la thèse de Maupassant','Simplement écrire « Philippe est solidaire »','Raconter toute l\'histoire','Chercher des exemples dans d\'autres œuvres uniquement'],
    answer:'Définir la solidarité, l\'illustrer par les actions de Philippe, et relier à la thèse de Maupassant',
    hint:'Définir → illustrer → interpréter.',
    explanation:'La méthode en trois temps : 1) <b>définir</b> le concept (qu\'est-ce que la solidarité ?), 2) <b>illustrer</b> par les actions de Philippe (avec citations), 3) <b>interpréter</b> en liant à la thèse de Maupassant sur la dignité du peuple.' }),

  makeMCQ({ id:'g9fr-oev-060', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Quel connecteur logique est le plus approprié pour introduire un deuxième argument dans une réponse longue ?',
    options:['De plus / En outre / Par ailleurs','Parce que','Premièrement','Enfin'],
    answer:'De plus / En outre / Par ailleurs',
    hint:'Ces connecteurs ajoutent un argument à ceux déjà développés.',
    explanation:'<b>De plus, En outre, Par ailleurs</b> sont des connecteurs d\'<b>addition</b> qui permettent d\'introduire un deuxième (ou troisième) argument en le reliant au précédent. « Premièrement » introduit le premier argument, « Enfin » le dernier.' }),

  makeMCQ({ id:'g9fr-oev-061', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, que signifie « analyser le style de l\'auteur » ?',
    options:['Commenter les procédés d\'écriture (vocabulaire, figures de style, ton) et leur effet','Décrire la mise en page du livre','Raconter la biographie de l\'auteur','Compter le nombre de pages'],
    answer:'Commenter les procédés d\'écriture (vocabulaire, figures de style, ton) et leur effet',
    hint:'Le style, c\'est comment l\'auteur écrit, pas ce qu\'il dit.',
    explanation:'Analyser le style consiste à examiner les <b>procédés d\'écriture</b> : vocabulaire choisi, figures de style (métaphore, comparaison), ton (ironique, tendre, dramatique) et leur <b>effet sur le lecteur</b>. C\'est une étape au-delà du simple résumé.' }),

  makeMCQ({ id:'g9fr-oev-062', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Comment prouver, dans une réponse longue, que Simon est un personnage attachant dans <i>Le Papa de Simon</i> ?',
    options:['Analyser ses émotions, ses actions naïves, et sa sincérité, en s\'appuyant sur des passages du texte','Dire simplement « Simon est sympathique »','Raconter toute la nouvelle','Comparer Simon à un personnage de manga'],
    answer:'Analyser ses émotions, ses actions naïves, et sa sincérité, en s\'appuyant sur des passages du texte',
    hint:'Prouver = analyser + exemples textuels.',
    explanation:'Pour prouver qu\'un personnage est attachant : analyser ses <b>émotions</b> (désespoir sincère, joie naïve), ses <b>actions</b> (il choisit un père spontanément), sa <b>sincérité</b> et appuyer avec des <b>passages du texte</b>. L\'assertion seule sans preuve ne suffit pas.' }),

  makeMCQ({ id:'g9fr-oev-063', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue sur <i>Topaze</i>, si la question demande « En quoi Topaze est-il une pièce satirique ? », quel plan est le plus approprié ?',
    options:['I. La cible de la satire (corruption politique) II. Les procédés satiriques (ironie, exagération) III. La portée critique de la pièce','I. La vie de Pagnol II. Le résumé de la pièce III. Les personnages','I. L\'amour dans la pièce II. La beauté du décor III. Les costumes','I. Le titre II. La date III. Le nombre d\'actes'],
    answer:'I. La cible de la satire (corruption politique) II. Les procédés satiriques (ironie, exagération) III. La portée critique de la pièce',
    hint:'Le plan doit répondre directement à la question sur la satire.',
    explanation:'Un plan pertinent sur la satire doit traiter : I. <b>La cible</b> (qu\'est-ce que Pagnol critique ?), II. <b>Les procédés</b> (comment ? ironie, comique, caricature), III. <b>La portée</b> (quel impact, quelle vision du monde ?). Ce plan répond directement à la question.' }),

  makeMCQ({ id:'g9fr-oev-064', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue, comment présenter l\'auteur et l\'œuvre en introduction ?',
    options:['Nom de l\'auteur, titre de l\'œuvre en italique, genre littéraire, époque/contexte, en une ou deux phrases','Une biographie complète de l\'auteur sur une page','Ne pas mentionner l\'auteur','Juste le titre et la date'],
    answer:'Nom de l\'auteur, titre de l\'œuvre en italique, genre littéraire, époque/contexte, en une ou deux phrases',
    hint:'L\'introduction contextualisante est brève mais précise.',
    explanation:'La présentation de l\'œuvre en introduction doit être <b>brève et précise</b> : nom de l\'auteur, titre en italique, genre (nouvelle, pièce), époque. Exemple : « Dans <i>Le Papa de Simon</i>, nouvelle réaliste de Guy de Maupassant (XIXe siècle)… »' }),

  makeMCQ({ id:'g9fr-oev-065', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Quelle est la fonction de l\'introduction dans une réponse longue sur une œuvre littéraire ?',
    options:['Contextualiser l\'œuvre, reformuler la problématique et annoncer le plan','Résumer toute l\'œuvre','Donner sa biographie de l\'auteur','Donner sa propre opinion personnelle immédiatement'],
    answer:'Contextualiser l\'œuvre, reformuler la problématique et annoncer le plan',
    hint:'L\'introduction prépare le lecteur à ce qui va suivre.',
    explanation:'L\'introduction a trois fonctions : 1) <b>contextualiser</b> l\'œuvre (auteur, titre, genre, époque), 2) <b>reformuler la problématique</b> (montrer qu\'on a compris la question), 3) <b>annoncer le plan</b> (les grandes parties de la réponse).' }),

  makeMCQ({ id:'g9fr-oev-066', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue, quelle différence y a-t-il entre une « thèse » et un « argument » ?',
    options:['La thèse est la réponse globale à la question ; l\'argument est une raison qui la soutient','La thèse et l\'argument sont identiques','La thèse est une citation ; l\'argument est une paraphrase','Il n\'y a aucune différence'],
    answer:'La thèse est la réponse globale à la question ; l\'argument est une raison qui la soutient',
    hint:'La thèse est affirmée en introduction ; les arguments la développent dans le corps.',
    explanation:'La <b>thèse</b> est la réponse globale à la problématique posée (ex. : « Maupassant dénonce les préjugés sociaux »). Les <b>arguments</b> sont les raisons qui prouvent cette thèse (ex. : « En montrant que Simon souffre d\'une condition qu\'il n\'a pas choisie… »).' }),

  makeMCQ({ id:'g9fr-oev-067', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, pourquoi faut-il éviter le résumé de l\'intrigue ?',
    options:['Parce que le lecteur (correcteur) connaît l\'œuvre ; il faut analyser, pas raconter','Parce que le résumé est toujours faux','Parce qu\'il faut uniquement citer des passages','Parce que le résumé est trop court'],
    answer:'Parce que le lecteur (correcteur) connaît l\'œuvre ; il faut analyser, pas raconter',
    hint:'Le correcteur veut voir de l\'analyse, pas un résumé qu\'il connaît déjà.',
    explanation:'Le correcteur connaît l\'œuvre. <b>Résumer l\'intrigue</b> ne montre pas de compétence analytique et fait perdre des points. Il faut <b>analyser</b> les enjeux, les thèmes, les procédés stylistiques.' }),

  makeMCQ({ id:'g9fr-oev-068', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Si la question longue demande de comparer les deux œuvres (<i>Le Papa de Simon</i> et <i>Topaze</i>), quel plan est le mieux adapté ?',
    options:['Un plan comparatif thématique : thème 1 (dans les deux œuvres) / thème 2 / thème 3','Traiter d\'abord toute l\'œuvre A puis toute l\'œuvre B, sans les relier','Citer des passages au hasard','Ne traiter qu\'une des deux œuvres'],
    answer:'Un plan comparatif thématique : thème 1 (dans les deux œuvres) / thème 2 / thème 3',
    hint:'La comparaison se fait thème par thème, non œuvre par œuvre.',
    explanation:'Pour une comparaison, le <b>plan thématique</b> est le plus efficace : on examine un thème dans les deux œuvres simultanément (ex. : le thème de la justice dans <i>Le Papa de Simon</i> et dans <i>Topaze</i>). Le plan « œuvre A puis œuvre B » produit deux textes parallèles qui ne se comparent pas vraiment.' }),

  makeMCQ({ id:'g9fr-oev-069', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, quelle est la longueur idéale de la conclusion ?',
    options:['Brève : 3 à 5 phrases (synthèse + ouverture)','Aussi longue que le développement','Une seule phrase','Aussi longue que l\'introduction'],
    answer:'Brève : 3 à 5 phrases (synthèse + ouverture)',
    hint:'La conclusion est concise : elle clôt sans répéter.',
    explanation:'La conclusion doit être <b>brève</b> (3 à 5 phrases) : elle synthétise les arguments (sans les répéter) et répond à la question. Elle peut s\'ouvrir sur une réflexion plus large. Une conclusion trop longue dilue l\'effet de clôture.' }),

  makeMCQ({ id:'g9fr-oev-070', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Quel conseil est le plus utile pour une réponse longue sur une œuvre littéraire au baccalauréat ou au niveau NCE ?',
    options:['Planifier avant d\'écrire : noter les arguments et les citations avant de rédiger','Écrire le plus vite possible sans relecture','Utiliser le dictionnaire pour chaque mot','Recopier des passages entiers de l\'œuvre'],
    answer:'Planifier avant d\'écrire : noter les arguments et les citations avant de rédiger',
    hint:'Un texte bien planifié est un texte cohérent.',
    explanation:'La stratégie la plus efficace est de <b>planifier avant d\'écrire</b> : noter les arguments, choisir les citations pertinentes, définir le plan. Cela garantit une réponse structurée et cohérente, sans oubli de points imposés ni hors-sujet.' }),

  makeMCQ({ id:'g9fr-oev-071', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, que signifie « analyser les procédés stylistiques » ?',
    options:['Identifier et commenter les techniques d\'écriture (métaphore, ironie, champ lexical…) et leur effet','Compter les phrases','Résumer les chapitres','Donner son avis personnel sur la beauté du style'],
    answer:'Identifier et commenter les techniques d\'écriture (métaphore, ironie, champ lexical…) et leur effet',
    hint:'Procédé = technique d\'écriture employée par l\'auteur.',
    explanation:'Analyser les <b>procédés stylistiques</b> = identifier les techniques (métaphore, comparaison, ironie, champ lexical, gradation…) et <b>commenter leur effet</b> sur le lecteur ou sur le sens. C\'est l\'analyse littéraire proprement dite.' }),

  makeMCQ({ id:'g9fr-oev-072', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Comment justifier son interprétation d\'une figure de style dans une réponse longue ?',
    options:['Nommer la figure, citer le passage, expliquer son effet sur le sens ou l\'émotion','Juste la nommer sans explication','La copier trois fois','Dire que c\'est « beau »'],
    answer:'Nommer la figure, citer le passage, expliquer son effet sur le sens ou l\'émotion',
    hint:'La méthode : nommer → citer → analyser.',
    explanation:'La méthode pour analyser une figure de style : 1) <b>nommer</b> la figure (comparaison, métaphore…), 2) <b>citer</b> le passage entre guillemets, 3) <b>analyser son effet</b> : que dit-elle ? Qu\'est-ce qu\'elle révèle ? Comment affecte-t-elle le lecteur ?' }),

  makeMCQ({ id:'g9fr-oev-073', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, quel connecteur sert à introduire un exemple concret du texte ?',
    options:['Ainsi / Par exemple / C\'est le cas quand…','En conclusion','De plus','Cependant'],
    answer:'Ainsi / Par exemple / C\'est le cas quand…',
    hint:'Ces expressions introduisent une illustration.',
    explanation:'Pour introduire un exemple concret : <b>Ainsi, Par exemple, C\'est le cas quand, On le voit lorsque…</b> Ces connecteurs signalent que l\'on passe de l\'affirmation générale à la preuve particulière.' }),

  makeMCQ({ id:'g9fr-oev-074', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue sur <i>Topaze</i>, si la question demande : « Quel jugement Pagnol porte-t-il sur la société de son époque ? », quelle approche est correcte ?',
    options:['Analyser comment les personnages et l\'intrigue révèlent la critique de Pagnol, avec exemples','Donner son opinion personnelle sur la société d\'aujourd\'hui','Résumer l\'intrigue de la pièce','Raconter la biographie de Pagnol'],
    answer:'Analyser comment les personnages et l\'intrigue révèlent la critique de Pagnol, avec exemples',
    hint:'La question porte sur le point de vue de l\'auteur, pas le tien.',
    explanation:'Il faut analyser comment Pagnol exprime sa critique à travers les <b>personnages</b> (Castel-Bénac = corruption, Topaze = victime naïve devenue complice) et l\'<b>intrigue</b> (la vertu punie, le vice récompensé). Ce sont les preuves de son jugement sur la société.' }),

  makeMCQ({ id:'g9fr-oev-075', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, que doit-on éviter absolument dans la conclusion ?',
    options:['Introduire un nouvel argument qui n\'a pas été développé dans le corps du texte','Synthétiser les arguments','Répondre à la question','Ouvrir sur une réflexion plus large'],
    answer:'Introduire un nouvel argument qui n\'a pas été développé dans le corps du texte',
    hint:'La conclusion clôt ; elle ne doit pas ouvrir de nouveaux développements.',
    explanation:'La conclusion ne doit <b>jamais introduire un nouvel argument</b> non développé dans le corps. Cela crée une frustration chez le lecteur et donne l\'impression que le plan était incomplet. La conclusion est une clôture, pas une ouverture supplémentaire.' }),

  makeMCQ({ id:'g9fr-oev-076', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse sur <i>Le Papa de Simon</i>, quel argument peut-on développer pour montrer que c\'est une œuvre humaniste ?',
    options:['Maupassant défend la dignité humaine en montrant que les gens simples ont autant de valeur que les riches','Maupassant défend la supériorité des classes nobles','Maupassant montre que les enfants sont inutiles','Maupassant critique la campagne française'],
    answer:'Maupassant défend la dignité humaine en montrant que les gens simples ont autant de valeur que les riches',
    hint:'L\'humanisme valorise la dignité de tout être humain.',
    explanation:'L\'humanisme de Maupassant dans cette nouvelle se manifeste par sa défense de la <b>dignité des gens simples</b> (Philippe le forgeron, Blanche la couturière). Ils font preuve d\'une humanité et d\'une générosité supérieures à celles des bourgeois.' }),

  makeMCQ({ id:'g9fr-oev-077', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, comment montrer qu\'un thème est développé dans toute l\'œuvre et pas seulement dans un passage ?',
    options:['Citer plusieurs passages de différentes parties de l\'œuvre pour illustrer le thème','Citer un seul passage très long','Ne pas citer du tout','Citer uniquement le début et la fin'],
    answer:'Citer plusieurs passages de différentes parties de l\'œuvre pour illustrer le thème',
    hint:'Un thème central traverse toute l\'œuvre.',
    explanation:'Pour montrer qu\'un thème est central et récurrent, il faut le <b>documenter avec plusieurs citations de différentes parties</b> de l\'œuvre (début, milieu, fin). Cela prouve que le thème n\'est pas anecdotique.' }),

  makeMCQ({ id:'g9fr-oev-078', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Pourquoi est-il important de connaître le contexte historique d\'une œuvre dans une réponse longue ?',
    options:['Le contexte aide à comprendre les enjeux et les choix de l\'auteur','Le contexte doit remplir toute la réponse','Le contexte remplace l\'analyse du texte','Le contexte est toujours hors-sujet'],
    answer:'Le contexte aide à comprendre les enjeux et les choix de l\'auteur',
    hint:'Une œuvre est ancrée dans son époque.',
    explanation:'Le contexte historique (époque, société, mouvements littéraires) aide à <b>comprendre pourquoi l\'auteur a fait certains choix</b>. Maupassant écrit à une époque où les enfants illégitimes sont stigmatisés : ce contexte éclaire la force de sa critique sociale.' }),

  makeMCQ({ id:'g9fr-oev-079', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue sur <i>Topaze</i>, quelle figure de style Pagnol utilise-t-il souvent pour critiquer ses personnages ?',
    options:['L\'ironie','La métaphore filée','L\'hyperbole lyrique','La personnification de la nature'],
    answer:'L\'ironie',
    hint:'L\'ironie consiste à dire le contraire de ce qu\'on pense pour faire rire ou critiquer.',
    explanation:'Pagnol utilise fréquemment l\'<b>ironie</b> pour critiquer ses personnages : un personnage dit une chose noble mais fait exactement le contraire, créant un décalage comique et critique. L\'ironie est l\'arme principale de la satire dans <i>Topaze</i>.' }),

  makeMCQ({ id:'g9fr-oev-080', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue, si la question porte sur « la valeur de l\'honnêteté dans les deux œuvres », quel point commun peut-on souligner ?',
    options:['Dans les deux œuvres, l\'honnêteté est mise à l\'épreuve et souvent punie par la société','Les deux œuvres défendent l\'honnêteté sans nuance','Les deux œuvres montrent que l\'honnêteté n\'existe pas','Les deux auteurs rejettent le thème de l\'honnêteté'],
    answer:'Dans les deux œuvres, l\'honnêteté est mise à l\'épreuve et souvent punie par la société',
    hint:'Dans les deux cas, le monde réel résiste aux idéaux.',
    explanation:'Le point commun est que, dans les deux œuvres, l\'honnêteté est <b>mise à l\'épreuve et sanctionnée</b> par la société : Blanche est stigmatisée pour sa « faute », Topaze est renvoyé pour son refus de tricher. Les deux auteurs critiquent une société qui punit les honnêtes gens.' }),

  makeMCQ({ id:'g9fr-oev-081', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Quel est le rôle de l\'ouverture (dernière phrase de la conclusion) dans une réponse longue ?',
    options:['Élargir la réflexion à une question plus générale ou à d\'autres œuvres','Répéter la thèse principale','Résumer l\'ensemble de la réponse','Poser une nouvelle question sans réponse'],
    answer:'Élargir la réflexion à une question plus générale ou à d\'autres œuvres',
    hint:'L\'ouverture donne une perspective plus large à la réflexion.',
    explanation:'L\'<b>ouverture</b> (ou « élargissement ») en fin de conclusion invite le lecteur à réfléchir au-delà du texte étudié : relier à d\'autres œuvres, à une question universelle, ou au monde contemporain. Elle montre la portée plus large de l\'analyse.' }),

  makeMCQ({ id:'g9fr-oev-082', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue, comment éviter de plagier l\'œuvre tout en s\'en servant ?',
    options:['Paraphraser les idées et citer les extraits entre guillemets avec des guillemets clairs','Copier de longs passages sans guillemets','Éviter toute référence au texte','N\'utiliser que ses propres idées sans référence au texte'],
    answer:'Paraphraser les idées et citer les extraits entre guillemets avec des guillemets clairs',
    hint:'Citer ≠ copier : la citation est délimitée et commentée.',
    explanation:'Pour éviter le plagiat : <b>paraphraser</b> les idées générales (reformuler avec ses propres mots) et <b>citer entre guillemets</b> les passages exacts du texte. La citation doit toujours être délimitée par des guillemets et commentée.' }),

  makeMCQ({ id:'g9fr-oev-083', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue sur une pièce de théâtre comme <i>Topaze</i>, que peut-on analyser en plus du texte ?',
    options:['Les indications scéniques (didascalies) qui révèlent les intentions de mise en scène','Uniquement les dialogues','La biographie de l\'auteur','La durée de la pièce'],
    answer:'Les indications scéniques (didascalies) qui révèlent les intentions de mise en scène',
    hint:'Les didascalies font partie du texte théâtral.',
    explanation:'Dans une pièce de théâtre, les <b>didascalies</b> (indications scéniques en italique) révèlent les intentions de l\'auteur sur les mouvements, les tons, les décors. Elles font partie intégrante du texte et peuvent enrichir l\'analyse.' }),

  makeMCQ({ id:'g9fr-oev-084', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Quel connecteur logique introduit une nuance ou une opposition dans une réponse longue ?',
    options:['Cependant / Toutefois / Néanmoins','De plus','En conclusion','Premièrement'],
    answer:'Cependant / Toutefois / Néanmoins',
    hint:'Ces mots signalent un contraste avec ce qui précède.',
    explanation:'<b>Cependant, Toutefois, Néanmoins</b> sont des connecteurs d\'<b>opposition ou de nuance</b>. Ils permettent d\'introduire un contre-argument ou de nuancer une affirmation. Indispensables dans une analyse équilibrée.' }),

  makeMCQ({ id:'g9fr-oev-085', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, quelle est la longueur idéale du développement par rapport à l\'ensemble ?',
    options:['Le développement représente environ 70-80 % de la réponse totale','Le développement représente 10 % de la réponse','Le développement doit être aussi long que l\'introduction','Il n\'y a pas de règle'],
    answer:'Le développement représente environ 70-80 % de la réponse totale',
    hint:'Le développement est la partie principale.',
    explanation:'Dans une réponse longue bien structurée : <b>introduction ≈ 10-15 %</b>, <b>développement ≈ 70-80 %</b> (la partie principale avec les arguments), <b>conclusion ≈ 10-15 %</b>. Le développement est le cœur de la réponse.' }),

  makeMCQ({ id:'g9fr-oev-086', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue, comment éviter la répétition des mêmes mots ?',
    options:['Utiliser des synonymes, des pronoms et des reformulations variées','Répéter délibérément pour insister','N\'utiliser qu\'un seul mot par concept','Écrire en abrégé'],
    answer:'Utiliser des synonymes, des pronoms et des reformulations variées',
    hint:'La richesse du vocabulaire est une marque de qualité stylistique.',
    explanation:'Pour éviter les répétitions : <b>synonymes</b> (dire la même chose avec des mots différents), <b>pronoms</b> (il, elle, ce personnage, cet auteur…), <b>reformulations</b> (exprimer la même idée différemment). Cela enrichit le style et montre l\'étendue du vocabulaire.' }),

  makeMCQ({ id:'g9fr-oev-087', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue sur <i>Le Papa de Simon</i>, pourquoi est-il pertinent de mentionner que c\'est une nouvelle réaliste ?',
    options:['Parce que le réalisme explique le choix de personnages ordinaires et de situations sociales réelles','Pour montrer qu\'on connaît le terme','Parce que le réalisme est le seul mouvement littéraire','Parce que Maupassant n\'est pas réaliste'],
    answer:'Parce que le réalisme explique le choix de personnages ordinaires et de situations sociales réelles',
    hint:'Le genre littéraire éclaire les choix de l\'auteur.',
    explanation:'Mentionner le <b>réalisme</b> est pertinent car il explique les choix de Maupassant : des personnages ordinaires (forgeron, couturière, enfant), une situation sociale réelle (la stigmatisation des enfants illégitimes), un ancrage dans la France du XIXe siècle.' }),

  makeMCQ({ id:'g9fr-oev-088', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue, quelle est la différence entre un plan analytique et un plan dialectique ?',
    options:['Plan analytique : analyse d\'aspects du sujet ; Plan dialectique (thèse/antithèse/synthèse) : confronte des points de vue opposés','Les deux sont identiques','Le plan dialectique ne s\'applique qu\'aux mathématiques','Le plan analytique est réservé aux sciences'],
    answer:'Plan analytique : analyse d\'aspects du sujet ; Plan dialectique (thèse/antithèse/synthèse) : confronte des points de vue opposés',
    hint:'Le plan dialectique est le plan « pour/contre/nuance ».',
    explanation:'<b>Plan analytique</b> : analyser différents aspects du sujet (aspect 1, aspect 2, aspect 3). <b>Plan dialectique</b> : thèse (arguments pour), antithèse (arguments contre), synthèse (nuance et position finale). Le plan dialectique convient aux questions ouvertes qui permettent deux points de vue.' }),

  makeMCQ({ id:'g9fr-oev-089', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, si on dit « Maupassant critique la société », cette affirmation est-elle suffisante seule ?',
    options:['Non, il faut l\'illustrer par des exemples précis du texte','Oui, cette affirmation seule suffit','Non, il faut répéter cette affirmation plusieurs fois','Oui, si elle est en gras'],
    answer:'Non, il faut l\'illustrer par des exemples précis du texte',
    hint:'Une affirmation sans preuve n\'est qu\'une opinion.',
    explanation:'Une affirmation comme « Maupassant critique la société » est une <b>thèse générale</b> qui doit être <b>illustrée par des exemples précis</b> tirés du texte. Sans preuve, ce n\'est qu\'une opinion sans valeur argumentative.' }),

  makeMCQ({ id:'g9fr-oev-090', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue, comment analyser le titre d\'une œuvre comme élément signifiant ?',
    options:['Identifier les mots clés du titre, leur sens, et leur lien avec les thèmes de l\'œuvre','Simplement répéter le titre','Dire que le titre est « beau » ou « bien choisi »','Ignorer le titre dans l\'analyse'],
    answer:'Identifier les mots clés du titre, leur sens, et leur lien avec les thèmes de l\'œuvre',
    hint:'Le titre est souvent une clé de lecture de l\'œuvre.',
    explanation:'Analyser un titre : 1) identifier les <b>mots clés</b> (« Papa », « Simon ») ; 2) en analyser le <b>sens</b> (« papa » = père choisi, pas nécessairement biologique) ; 3) relier au <b>thème central</b> (la quête d\'identité et d\'appartenance familiale).' }),

  makeMCQ({ id:'g9fr-oev-091', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue, pourquoi est-il important d\'utiliser le vocabulaire littéraire (thème, registre, figure de style…) ?',
    options:['Pour montrer sa maîtrise de l\'analyse littéraire et communiquer avec précision','Pour impressionner le correcteur sans comprendre','Parce que c\'est obligatoire légalement','Pour augmenter la longueur de la réponse'],
    answer:'Pour montrer sa maîtrise de l\'analyse littéraire et communiquer avec précision',
    hint:'Le vocabulaire technique est un outil de précision.',
    explanation:'Le vocabulaire littéraire (<b>thème, registre, figure de style, narrateur, ton, ironie</b>…) permet de <b>communiquer avec précision</b> et montre la maîtrise de l\'analyse. C\'est un signe de compétence littéraire que les correcteurs valorisent.' }),

  makeMCQ({ id:'g9fr-oev-092', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Quand on dit que <i>Topaze</i> est une œuvre « didactique » (qui enseigne), quelle dimension de la pièce cela souligne-t-il ?',
    options:['La pièce instruit le spectateur sur les mécanismes de la corruption et de la compromission','La pièce est utilisée dans les écoles uniquement','La pièce contient des leçons de mathématiques','La pièce n\'a aucun message moral'],
    answer:'La pièce instruit le spectateur sur les mécanismes de la corruption et de la compromission',
    hint:'Didactique = qui enseigne, qui transmet un savoir ou une leçon.',
    explanation:'Dire que <i>Topaze</i> est « didactique » signifie que la pièce <b>instruit le spectateur</b> sur les mécanismes de la corruption et de la compromission morale. Pagnol montre, à travers le cas de Topaze, comment un individu honnête peut être corrompu par son environnement.' }),

  makeMCQ({ id:'g9fr-oev-093', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue sur une œuvre littéraire, que signifie « prendre une distance critique » par rapport à l\'œuvre ?',
    options:['Analyser l\'œuvre objectivement, en soulignant ses forces ET ses limites éventuelles','Rejeter l\'œuvre entièrement','N\'exprimer que des compliments sur l\'œuvre','Refuser d\'analyser l\'œuvre'],
    answer:'Analyser l\'œuvre objectivement, en soulignant ses forces ET ses limites éventuelles',
    hint:'La distance critique, c\'est l\'objectivité et le recul analytique.',
    explanation:'<b>Prendre une distance critique</b> signifie analyser l\'œuvre avec <b>objectivité et recul</b> : souligner ses qualités (thèmes forts, style…) mais aussi, si pertinent, ses limites (vision simpliste, manichéisme…). C\'est la marque d\'un lecteur averti.' }),

  makeMCQ({ id:'g9fr-oev-094', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:3,
    question:'Dans une réponse longue, quel procédé stylistique Maupassant utilise-t-il dans <i>Le Papa de Simon</i> pour intensifier la détresse de Simon ?',
    options:['La gradation et les répétitions (« t\'as pas d\'papa »)','L\'humour et le burlesque','Les longues métaphores filées','Les descriptions de la nature exclusivement'],
    answer:'La gradation et les répétitions (« t\'as pas d\'papa »)',
    hint:'Les enfants répètent avec insistance leur moquerie.',
    explanation:'Maupassant utilise la <b>répétition</b> (« t\'as pas d\'papa » est répété par les camarades) et la <b>gradation</b> de la douleur de Simon pour intensifier la détresse. La répétition de l\'insulte martèle la blessure dans l\'esprit du lecteur.' }),

  makeMCQ({ id:'g9fr-oev-095', chapterId:'g9fr-oeuvres', subsection:'question_longue', difficulty:2,
    question:'Dans une réponse longue sur <i>Topaze</i> ou <i>Le Papa de Simon</i>, quel est l\'impact d\'une bonne relecture finale ?',
    options:['Elle permet de corriger les fautes, vérifier la cohérence et s\'assurer que tous les points sont traités','Elle augmente automatiquement la note','Elle n\'a aucun impact sur la note','Elle sert uniquement à corriger l\'orthographe'],
    answer:'Elle permet de corriger les fautes, vérifier la cohérence et s\'assurer que tous les points sont traités',
    hint:'La relecture finale est une étape indispensable.',
    explanation:'La <b>relecture finale</b> permet de : corriger les fautes (orthographe, grammaire), vérifier la cohérence des arguments, s\'assurer que tous les points imposés sont traités, et contrôler la longueur. C\'est une étape indispensable avant de rendre la copie.' })

);

})();
