'use strict';
// Grade 4 French - Chapitre : Vocabulaire de base
// IDs format: g4fr-voc-NNN

STATIC_QUESTIONS.push(

  makeMCQ({ id:'g4fr-voc-001', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:1,
    question:'Que signifie "Bonjour" en anglais ?',
    options:['Goodbye','Good evening','Hello / Good morning','Thank you'],
    answer:'Hello / Good morning',
    hint:'On dit "Bonjour" le matin ou l\'après-midi pour saluer quelqu\'un.',
    explanation:'"<b>Bonjour</b>" = Hello / Good morning. On utilise "Bonjour" pendant la journée. "Bonsoir" = Good evening (le soir). "Au revoir" = Goodbye. "Bonne nuit" = Good night (avant de dormir).' }),

  makeMCQ({ id:'g4fr-voc-002', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Rita reçoit un cadeau et elle dit : « ................ ! » »',
    options:['Merci','Pardon','Bonjour','Bonsoir'],
    answer:'Merci',
    hint:'Que dit-on quand on reçoit quelque chose ?',
    explanation:'On dit <b>merci</b> pour remercier quelqu\'un.' }),

  makeMCQ({ id:'g4fr-voc-003', chapterId:'g4fr-vocabulaire', subsection:'couleurs', difficulty:1,
    question:'Complète la phrase.<br>« Le sang et les tomates mûres sont de couleur ................ . »',
    options:['rouge','bleu','vert','jaune'],
    answer:'rouge',
    hint:'De quelle couleur ?',
    explanation:'La réponse est <b>rouge</b>. L\'adjectif de couleur s\'accorde avec le nom qu\'il décrit.' }),

  makeMCQ({ id:'g4fr-voc-004', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:1,
    question:'Quel jour vient après "lundi" ?',
    options:['mercredi','dimanche','mardi','jeudi'],
    answer:'mardi',
    hint:'Mémorise l\'ordre : lundi, ___, mercredi, jeudi, vendredi, samedi, dimanche.',
    explanation:'L\'ordre des jours : lundi, <b>mardi</b>, mercredi, jeudi, vendredi, samedi, dimanche. En français, les jours ne commencent pas par une majuscule (sauf en début de phrase). La semaine commence par "lundi".' }),

  makeMCQ({ id:'g4fr-voc-005', chapterId:'g4fr-vocabulaire', subsection:'nombres', difficulty:1,
    question:'Complète la phrase.<br>« Dans le panier il y a 8 mangues. On écrit : « ................ mangues ». »',
    options:['huit','sept','neuf','six'],
    answer:'huit',
    hint:'Écris 8 en toutes lettres.',
    explanation:'8 s\'écrit <b>huit</b>.' }),

  makeMCQ({ id:'g4fr-voc-006', chapterId:'g4fr-vocabulaire', subsection:'famille', difficulty:2,
    question:'Lis la phrase, puis réponds.<br>« Le soir, la mère de Sam l’aide à faire ses devoirs. »<br>Que veut dire « la mère » ?',
    options:['The mother','The sister','The daughter','The grandmother'],
    answer:'The mother',
    hint:'Qui aide l’enfant à faire ses devoirs dans cette phrase ?',
    explanation:'Dans cette phrase, « <b>la mère</b> » veut dire <b>the mother</b>.' }),

  makeMCQ({ id:'g4fr-voc-007', chapterId:'g4fr-vocabulaire', subsection:'nombres', difficulty:2,
    question:'Complète la phrase.<br>« Le bus part dans 15 minutes. On écrit : « ................ minutes ». »',
    options:['quinze','cinquante','vingt','treize'],
    answer:'quinze',
    hint:'Écris 15 en toutes lettres.',
    explanation:'15 s\'écrit <b>quinze</b>.' }),

  makeMCQ({ id:'g4fr-voc-008', chapterId:'g4fr-vocabulaire', subsection:'couleurs', difficulty:2,
    question:'Complète la phrase.<br>« Le citron et le soleil sont de couleur ................ . »',
    options:['jaune','rouge','noir','bleu'],
    answer:'jaune',
    hint:'De quelle couleur ?',
    explanation:'La réponse est <b>jaune</b>. L\'adjectif de couleur s\'accorde avec le nom qu\'il décrit.' }),

  makeMCQ({ id:'g4fr-voc-009', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:2,
    question:'Complète la phrase.<br>« La semaine finit par samedi, puis vient ................ . »',
    options:['dimanche','lundi','vendredi','jeudi'],
    answer:'dimanche',
    hint:'Quel jour vient juste après samedi ?',
    explanation:'Après samedi vient <b>dimanche</b>, le dernier jour de la semaine.' }),

  makeMCQ({ id:'g4fr-voc-010', chapterId:'g4fr-vocabulaire', subsection:'temps', difficulty:4,
    question:'Priya rencontre son professeur le matin. Elle dit : "___, Monsieur Sharma. Comment allez-vous ?" Quelle salutation doit-elle utiliser ?',
    options:['Au revoir','Bonne nuit','Bonjour','Bonsoir'],
    answer:'Bonjour',
    hint:'C\'est le matin. Quelle salutation est appropriée pour le matin ?',
    explanation:'"<b>Bonjour</b>" est correct - c\'est la salutation du matin et de l\'après-midi. "Bonsoir" s\'utilise le soir uniquement. "Au revoir" signifie goodbye. "Bonne nuit" s\'utilise avant de dormir. Il est aussi correct de dire "Bonjour" à un professeur car on le vouvoie (vous).' })

);

STATIC_QUESTIONS.push(

  makeMCQ({ id:'g4fr-voc-011', chapterId:'g4fr-vocabulaire', subsection:'couleurs', difficulty:1,
    question:'Complète la phrase.<br>« La nuit, le ciel devient tout ................ . »',
    options:['noir','blanc','vert','jaune'],
    answer:'noir',
    hint:'De quelle couleur ?',
    explanation:'La réponse est <b>noir</b>. L\'adjectif de couleur s\'accorde avec le nom qu\'il décrit.' }),

  makeMCQ({ id:'g4fr-voc-012', chapterId:'g4fr-vocabulaire', subsection:'nombres', difficulty:1,
    question:'Complète la phrase.<br>« Il y a 20 élèves dans la classe. On écrit : « ................ élèves ». »',
    options:['vingt','quinze','dix-neuf','douze'],
    answer:'vingt',
    hint:'Écris 20 en toutes lettres.',
    explanation:'20 s\'écrit <b>vingt</b>.' }),

  makeMCQ({ id:'g4fr-voc-013', chapterId:'g4fr-vocabulaire', subsection:'politesse', difficulty:1,
    question:'Complète la phrase.<br>« Pour demander poliment à un adulte, on dit : « ................ , madame. » »',
    options:['S\'il vous plaît','S\'il te plaît','Au revoir','Bonsoir'],
    answer:'S\'il vous plaît',
    hint:'On parle à un adulte, donc on emploie « vous ».',
    explanation:'À un adulte on dit <b>s\'il vous plaît</b>. Entre amis on dit « s\'il te plaît ».' }),

  makeMCQ({ id:'g4fr-voc-014', chapterId:'g4fr-vocabulaire', subsection:'famille', difficulty:1,
    question:'Lis la phrase, puis réponds.<br>« À la maison, le frère de Rita répare son vélo. »<br>Que veut dire « le frère » ?',
    options:['The brother','The father','The uncle','The son'],
    answer:'The brother',
    hint:'C’est un garçon de la même famille que Rita.',
    explanation:'Dans cette phrase, « <b>le frère</b> » veut dire <b>the brother</b>.' }),

  makeMCQ({ id:'g4fr-voc-015', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:2,
    question:'Quel mois vient après "mars" ?',
    options:['janvier','février','mai','avril'],
    answer:'avril',
    hint:'Les mois : janvier, février, mars, ___, mai...',
    explanation:'L\'ordre des mois : janvier, février, mars, <b>avril</b>, mai, juin, juillet, août, septembre, octobre, novembre, décembre. En français, les mois ne prennent pas de majuscule (sauf en début de phrase).' }),

  makeMCQ({ id:'g4fr-voc-016', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:2,
    question:'Comment dit-on "white" en français (forme masculine) ?',
    options:['noir','gris','beige','blanc'],
    answer:'blanc',
    hint:'C\'est la couleur de la neige et du lait.',
    explanation:'"<b>Blanc</b>" = white (masculin). Forme féminine : "<b>blanche</b>". Exemples : un mur blanc, une robe blanche. "Blanc" a une forme féminine irrégulière (-c → -che).' }),

  makeMCQ({ id:'g4fr-voc-017', chapterId:'g4fr-vocabulaire', subsection:'nombres', difficulty:2,
    question:'Lis la phrase, puis réponds.<br>« Il y a douze mois dans une année. »<br>Combien de mois y a-t-il ?',
    options:['12','13','10','11'],
    answer:'12',
    hint:'Le nombre est écrit en toutes lettres.',
    explanation:'« <b>douze</b> » est le nombre <b>12</b>, et une année compte bien 12 mois.' }),

  makeMCQ({ id:'g4fr-voc-018', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:3,
    question:'Quel jour de la semaine vient juste AVANT "vendredi" ?',
    options:['samedi','mercredi','jeudi','mardi'],
    answer:'jeudi',
    hint:'Rappelle l\'ordre des jours : ..., mercredi, jeudi, vendredi, ...',
    explanation:'L\'ordre des jours : lundi, mardi, mercredi, <b>jeudi</b>, vendredi, samedi, dimanche. "Jeudi" (Thursday) vient directement avant "vendredi" (Friday).' }),

  makeMCQ({ id:'g4fr-voc-019', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:4,
    question:'Riya arrive à l\'école. Elle a déjà dit bonjour au professeur. Elle ne trouve pas son stylo et veut en demander un. Quelle phrase est la plus CORRECTE et la plus POLIE ?',
    options:[
      'Merci, avez-vous un stylo ?',
      'Bonjour, avez-vous un stylo ?',
      'Excusez-moi, s\'il vous plaît, avez-vous un stylo ?',
      'Au revoir, avez-vous un stylo ?'
    ],
    answer:"Excusez-moi, s\'il vous plaît, avez-vous un stylo ?",
    hint:'Elle interrompt son professeur pour demander quelque chose. Quels mots de politesse utilise-t-on ?',
    explanation:'"<b>Excusez-moi, s\'il vous plaît</b>, avez-vous un stylo ?" est la phrase la plus polie. "Excusez-moi" (Excuse me) pour interrompre poliment + "s\'il vous plaît" (please, forme formelle). "Merci" se dit après avoir reçu quelque chose. "Bonjour" est une salutation, pas une demande.' }),

  makeMCQ({ id:'g4fr-voc-020', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Sam porte un chapeau sur la ................ . »',
    options:['tête','main','jambe','bouche'],
    answer:'tête',
    hint:'Où met-on un chapeau ?',
    explanation:'Un chapeau se porte sur la <b>tête</b>.' }),

  makeMCQ({ id:'g4fr-voc-021', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Le fils de mes parents est mon ................ . »',
    options:['frère','oncle','cousin','voisin'],
    answer:'frère',
    hint:'C\'est un garçon de la même famille que moi.',
    explanation:'Le fils de mes parents est mon <b>frère</b>.' }),

  makeMCQ({ id:'g4fr-voc-022', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'Complète la phrase.<br>« Le ................ garde la maison et aboie quand quelqu\'un arrive. »',
    options:['chien','chat','poisson','oiseau'],
    answer:'chien',
    hint:'Lis toute la phrase : elle décrit l\'animal.',
    explanation:'La phrase décrit <b>chien</b>.' }),

  makeMCQ({ id:'g4fr-voc-023', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Aujourd\'hui c\'est lundi, alors ................ ce sera mardi. »',
    options:['demain','hier','ce soir','maintenant'],
    answer:'demain',
    hint:'Le jour qui vient après aujourd\'hui.',
    explanation:'Le jour après aujourd\'hui est <b>demain</b>.' }),

  makeMCQ({ id:'g4fr-voc-024', chapterId:'g4fr-vocabulaire', subsection:'verbes_utiles', difficulty:1,
    question:'Complète la phrase.<br>« Quand j\'ai soif, j\'aime ................ de l\'eau fraîche. »',
    options:['boire','manger','dormir','courir'],
    answer:'boire',
    hint:'Que fait-on avec de l\'eau quand on a soif ?',
    explanation:'On dit <b>boire</b> de l\'eau. On mange un aliment, mais on boit un liquide.' }),

  makeMCQ({ id:'g4fr-voc-025', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:2,
    question:'Complète la phrase.<br>« Le père de mon père est mon ................ . »',
    options:['grand-père','grand-mère','oncle','cousin'],
    answer:'grand-père',
    hint:'C\'est le papa de mon papa.',
    explanation:'Le père de mon père est mon <b>grand-père</b>.' }),

  makeMCQ({ id:'g4fr-voc-026', chapterId:'g4fr-vocabulaire', subsection:'corps', difficulty:2,
    question:'Complète la phrase.<br>« Nita sent les fleurs avec son ................ . »',
    options:['nez','oeil','pied','bras'],
    answer:'nez',
    hint:'Avec quelle partie du corps sent-on une odeur ?',
    explanation:'On sent les odeurs avec le <b>nez</b>.' }),

  makeTF({ id:'g4fr-voc-027', chapterId:'g4fr-vocabulaire', subsection:'temps', difficulty:2,
    question:'"Hier" signifie "tomorrow" en anglais.',
    answer:false,
    hint:'"Hier" est l\'opposé de "demain".',
    explanation:'<b>Faux.</b> "Hier" = <b>yesterday</b> (pas "tomorrow"). "Tomorrow" = <b>demain</b>. Mémo : hier (before today), aujourd\'hui (today), demain (after today).' }),

  makeMCQ({ id:'g4fr-voc-028', chapterId:'g4fr-vocabulaire', subsection:'verbes_utiles', difficulty:2,
    question:'Quel verbe signifie "to run" ?',
    options:['sauter','courir','lire','écrire'],
    answer:'courir',
    hint:'Les athlètes font ça dans un stade.',
    explanation:'"To run" = <b>courir</b>. Verbes d\'action : <b>courir</b> (run), <b>sauter</b> (jump), <b>lire</b> (read), <b>écrire</b> (write). Astuce : "courir" ressemble à "course" (race).' }),

  makeMCQ({ id:'g4fr-voc-029', chapterId:'g4fr-vocabulaire', subsection:'temps', difficulty:2,
    question:'Quelle phrase utilise correctement "ce matin" ?',
    options:[
      'Je mange ce matin hier.',
      'Ce matin, je mange mon petit déjeuner.',
      'Demain ce matin je dors.',
      'Ce matin = après-midi.'
    ],
    answer:'Ce matin, je mange mon petit déjeuner.',
    hint:'"Ce matin" = this morning. Quelle phrase a du sens ?',
    explanation:'"<b>Ce matin, je mange mon petit déjeuner.</b>" - "Ce matin" (this morning) est une expression de temps qui se place souvent au début ou à la fin de la phrase. On ne peut pas dire "ce matin hier" (deux temps qui se contredisent).' }),

  makeMCQ({ id:'g4fr-voc-030', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:2,
    question:'Complète la phrase.<br>« Nisha écrit avec sa ................ droite. »',
    options:['main','tête','jambe','oreille'],
    answer:'main',
    hint:'Avec quelle partie du corps tient-on un stylo ?',
    explanation:'On écrit avec la <b>main</b>.' }),

  makeMCQ({ id:'g4fr-voc-031', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:3,
    question:'Associe : "poisson / oiseau / lapin" - quel animal NE VIT PAS normalement à la maison comme animal domestique ?',
    options:['poisson','oiseau','lapin','aucun - ils peuvent tous être des animaux domestiques'],
    answer:'aucun - ils peuvent tous être des animaux domestiques',
    hint:'Pense aux animaux qu\'on garde chez soi.',
    explanation:'<b>Les trois peuvent être des animaux domestiques !</b> Le <b>poisson</b> (aquarium), l\'<b>oiseau</b> (cage), le <b>lapin</b> (cage ou liberté dans la maison). En France et à Maurice, on garde souvent des poissons, des oiseaux et des lapins à la maison.' }),

  makeMCQ({ id:'g4fr-voc-032', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:3,
    question:'Quel mot est un verbe (action) ?',
    options:['tête','frère','dormir','chat'],
    answer:'dormir',
    hint:'Un verbe exprime une action ou un état.',
    explanation:'"<b>Dormir</b>" est un verbe (to sleep) - c\'est une action. <b>Tête</b> = nom (partie du corps), <b>frère</b> = nom (personne), <b>chat</b> = nom (animal). Les verbes répondent à la question "Que fait-on ?".' }),

  makeMCQ({ id:'g4fr-voc-033', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:3,
    question:'Quelle phrase est correcte pour décrire l\'heure de la journée ?',
    options:[
      'Je dors le matin et je me réveille le soir.',
      'Je me réveille le matin et je dors le soir.',
      'Le soir arrive avant le matin.',
      'L\'après-midi est avant le matin.'
    ],
    answer:'Je me réveille le matin et je dors le soir.',
    hint:'L\'ordre normal : matin → après-midi → soir → nuit.',
    explanation:'"<b>Je me réveille le matin et je dors le soir.</b>" - L\'ordre du jour : le <b>matin</b> (morning, on se réveille), l\'<b>après-midi</b> (afternoon), le <b>soir</b> (evening, on se couche). Le matin est avant le soir.' }),

  makeMCQ({ id:'g4fr-voc-034', chapterId:'g4fr-vocabulaire', subsection:'famille', difficulty:3,
    question:'Complète : "Mon ___ s\'appelle Jean et ma ___ s\'appelle Marie. Ensemble, ils sont mes grands-parents."',
    options:['père / mère','oncle / tante','grand-père / grand-mère','frère / sœur'],
    answer:'grand-père / grand-mère',
    hint:'Ils sont les parents de tes parents.',
    explanation:'"Mon <b>grand-père</b> s\'appelle Jean et ma <b>grand-mère</b> s\'appelle Marie." - Les grands-parents sont les parents de nos parents. Le <b>grand-père</b> (paternel ou maternel) + la <b>grand-mère</b> = les grands-parents.' }),

  makeMCQ({ id:'g4fr-voc-035', chapterId:'g4fr-vocabulaire', subsection:'temps', difficulty:4,
    question:'Priya écrit : "Ce matin, mon ___ (father) et ma ___ (mother) travaillent. Mon ___ (brother) et ma ___ (sister) sont à l\'école. Moi, je suis malade à la maison." Quelle série est correcte ?',
    options:[
      'père / mère / frère / sœur',
      'oncle / tante / frère / sœur',
      'grand-père / grand-mère / frère / sœur',
      'père / mère / oncle / tante'
    ],
    answer:'père / mère / frère / sœur',
    hint:'Father = ?, Mother = ?, Brother = ?, Sister = ?',
    explanation:'"Mon <b>père</b>" (father), "ma <b>mère</b>" (mother), "mon <b>frère</b>" (brother), "ma <b>sœur</b>" (sister). La famille proche : père, mère, frère, sœur. Note le genre : "mon" (masc.) devant père/frère, "ma" (fém.) devant mère/sœur.' }),

  makeMCQ({ id:'g4fr-voc-036', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Ce fruit rouge pousse sur un arbre et croque sous la dent : c\'est ................ . »',
    options:['une pomme','une banane','une orange','une fraise'],
    answer:'une pomme',
    hint:'Un fruit rouge et croquant.',
    explanation:'C\'est <b>une pomme</b>. Elle est souvent rouge ou verte, et elle croque.' }),

  makeMCQ({ id:'g4fr-voc-037', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Ce fruit long et jaune se pèle avant de se manger : c\'est ................ . »',
    options:['une banane','une pomme','une orange','un citron'],
    answer:'une banane',
    hint:'Long, jaune, et on enlève la peau.',
    explanation:'C\'est <b>une banane</b>. On la pèle avant de la manger.' }),

  makeMCQ({ id:'g4fr-voc-038', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'Complète la phrase.<br>« Le ................ miaule et se couche au soleil sur le mur. »',
    options:['chat','chien','canard','lapin'],
    answer:'chat',
    hint:'Lis toute la phrase : elle décrit l\'animal.',
    explanation:'La phrase décrit <b>chat</b>.' }),

  makeMCQ({ id:'g4fr-voc-039', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'Complète la phrase.<br>« Le ................ aboie fort quand le facteur arrive. »',
    options:['chien','chat','mouton','oiseau'],
    answer:'chien',
    hint:'Lis toute la phrase : elle décrit l\'animal.',
    explanation:'La phrase décrit <b>chien</b>.' }),

  makeMCQ({ id:'g4fr-voc-040', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Le soir, Aisha lit ................ avant de dormir. »',
    options:['un livre','un stylo','une règle','une gomme'],
    answer:'un livre',
    hint:'Qu\'est-ce qu\'on lit ?',
    explanation:'On lit <b>un livre</b>. Les autres mots sont des objets pour écrire.' }),

  makeMCQ({ id:'g4fr-voc-041', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:2,
    question:'Complète la phrase.<br>« Papa est fatigué : il s\'assoit sur ................ . »',
    options:['une chaise','une table','une porte','une fenêtre'],
    answer:'une chaise',
    hint:'Sur quel meuble s\'assoit-on ?',
    explanation:'On s\'assoit sur <b>une chaise</b>. On mange sur une table.' }),

  makeMCQ({ id:'g4fr-voc-042', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Ce fruit rond a la même couleur que son nom : c\'est ................ . »',
    options:['une orange','une pomme','une banane','un ananas'],
    answer:'une orange',
    hint:'Le fruit et la couleur portent le même nom.',
    explanation:'C\'est <b>une orange</b> : le fruit et la couleur ont le même nom en français.' }),

  makeMCQ({ id:'g4fr-voc-043', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Le matin, ................ se lève et il fait jour. »',
    options:['le soleil','la lune','la pluie','le vent'],
    answer:'le soleil',
    hint:'Qu\'est-ce qui apporte la lumière du jour ?',
    explanation:'<b>Le soleil</b> se lève le matin et éclaire la journée.' })

);

STATIC_QUESTIONS.push(

  makeMCQ({ id:'g4fr-voc-044', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« La famille habite dans ................ à Curepipe. »',
    options:['une maison','une voiture','une école','une boutique'],
    answer:'une maison',
    hint:'Où habite une famille ?',
    explanation:'Une famille habite dans <b>une maison</b>.' }),

  makeMCQ({ id:'g4fr-voc-045', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Il pleut, alors Yash ouvre ................ pour ne pas être mouillé. »',
    options:['un parapluie','un cartable','un chapeau','un cahier'],
    answer:'un parapluie',
    hint:'Qu\'ouvre-t-on quand il pleut ?',
    explanation:'On ouvre <b>un parapluie</b> pour se protéger de la pluie.' }),

  makeMCQ({ id:'g4fr-voc-046', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« La nuit, ................ brille dans le ciel noir. »',
    options:['la lune','le soleil','la mer','la pluie'],
    answer:'la lune',
    hint:'Qu\'est-ce qu\'on voit dans le ciel la nuit ?',
    explanation:'<b>La lune</b> brille la nuit ; le soleil brille le jour.' }),

  makeMCQ({ id:'g4fr-voc-047', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'Complète la phrase.<br>« Le ................ nage dans le lagon et respire par ses branchies. »',
    options:['poisson','lapin','chien','oiseau'],
    answer:'poisson',
    hint:'Lis toute la phrase : elle décrit l\'animal.',
    explanation:'La phrase décrit <b>poisson</b>.' }),

  makeMCQ({ id:'g4fr-voc-048', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Dans le jardin, Maya cueille ................ rouge pour sa maman. »',
    options:['une fleur','un arbre','une feuille','une pierre'],
    answer:'une fleur',
    hint:'Qu\'est-ce qu\'on cueille et qu\'on offre ?',
    explanation:'On cueille <b>une fleur</b> pour l\'offrir.' }),

  makeMCQ({ id:'g4fr-voc-049', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Complète la phrase.<br>« Le soir, on voit briller ................ dans le ciel. »',
    options:['une étoile','un nuage','un oiseau','un avion'],
    answer:'une étoile',
    hint:'Ce petit point de lumière est très loin de la Terre.',
    explanation:'<b>Une étoile</b> brille dans le ciel la nuit.' }),

  makeMCQ({ id:'g4fr-voc-050', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:2,
    question:'Complète la phrase.<br>« Le ................ nous donne la laine de nos pulls. »',
    options:['mouton','canard','chat','poisson'],
    answer:'mouton',
    hint:'Lis toute la phrase : elle décrit l\'animal.',
    explanation:'La phrase décrit <b>mouton</b>.' }),

  makeMCQ({ id:'g4fr-voc-051', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:2,
    question:'Complète la phrase.<br>« Le ................ nage sur l\'étang et fait « coin-coin ». »',
    options:['canard','mouton','lapin','chat'],
    answer:'canard',
    hint:'Lis toute la phrase : elle décrit l\'animal.',
    explanation:'La phrase décrit <b>canard</b>.' }),

  makeMCQ({ id:'g4fr-voc-052', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'Complète la phrase.<br>« Le ................ a de longues oreilles et mange des carottes. »',
    options:['lapin','mouton','poisson','canard'],
    answer:'lapin',
    hint:'Lis toute la phrase : elle décrit l\'animal.',
    explanation:'La phrase décrit <b>lapin</b>.' }),

  makeMCQ({ id:'g4fr-voc-053', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'Complète la phrase.<br>« L\'................ a des plumes et vole d\'un arbre à l\'autre. »',
    options:['oiseau','poisson','lapin','mouton'],
    answer:'oiseau',
    hint:'Lis toute la phrase : elle décrit l\'animal.',
    explanation:'La phrase décrit <b>oiseau</b>.' })

);
