'use strict';
// Grade 4 French - Chapitre : Vocabulaire de base
// IDs format: g4fr-voc-NNN

STATIC_QUESTIONS.push(

  makeMCQ({ id:'g4fr-voc-001', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:1,
    question:'Que signifie "Bonjour" en anglais ?',
    options:['Goodbye','Good evening','Hello / Good morning','Thank you'],
    answer:'Hello / Good morning',
    hint:'On dit "Bonjour" le matin ou l\'après-midi pour saluer quelqu\'un.',
    explanation:'"<b>Bonjour</b>" = Hello / Good morning. On utilise "Bonjour" pendant la journée. "Bonsoir" = Good evening (le soir). "Au revoir" = Goodbye. "Bonne nuit" = Good night (avant de dormir).' }),

  makeMCQ({ id:'g4fr-voc-002', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Comment dit-on "Thank you" en français ?',
    options:['S\'il vous plaît','Au revoir','Bonjour','Merci'],
    answer:'Merci',
    hint:'C\'est le mot poli que l\'on dit quand on reçoit quelque chose.',
    explanation:'"<b>Merci</b>" = Thank you. "S\'il vous plaît" = Please (formal) / "S\'il te plaît" (informal). "Au revoir" = Goodbye. "De rien" ou "Je vous en prie" = You\'re welcome (réponse à merci).' }),

  makeMCQ({ id:'g4fr-voc-003', chapterId:'g4fr-vocabulaire', subsection:'couleurs', difficulty:1,
    question:'Quelle est la couleur "red" en français ?',
    options:['bleu','vert','rouge','jaune'],
    answer:'rouge',
    hint:'C\'est la couleur du feu et des tomates.',
    explanation:'"<b>Rouge</b>" = red. Les couleurs : rouge (red), bleu/bleue (blue), vert/verte (green), jaune (yellow), noir/noire (black), blanc/blanche (white), orange (orange), rose (pink). Les couleurs s\'accordent avec le nom en genre et en nombre.' }),

  makeMCQ({ id:'g4fr-voc-004', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:1,
    question:'Quel jour vient après "lundi" ?',
    options:['mercredi','dimanche','mardi','jeudi'],
    answer:'mardi',
    hint:'Mémorise l\'ordre : lundi, ___, mercredi, jeudi, vendredi, samedi, dimanche.',
    explanation:'L\'ordre des jours : lundi, <b>mardi</b>, mercredi, jeudi, vendredi, samedi, dimanche. En français, les jours ne commencent pas par une majuscule (sauf en début de phrase). La semaine commence par "lundi".' }),

  makeMCQ({ id:'g4fr-voc-005', chapterId:'g4fr-vocabulaire', subsection:'nombres', difficulty:1,
    question:'Comment dit-on le nombre 8 en français ?',
    options:['six','sept','huit','neuf'],
    answer:'huit',
    hint:'6 = six, 7 = sept, 8 = ?, 9 = neuf.',
    explanation:'"<b>Huit</b>" = 8. Les nombres 1–10 : un, deux, trois, quatre, cinq, six, sept, <b>huit</b>, neuf, dix. Les nombres 11–20 : onze, douze, treize, quatorze, quinze, seize, dix-sept, dix-huit, dix-neuf, vingt.' }),

  makeMCQ({ id:'g4fr-voc-006', chapterId:'g4fr-vocabulaire', subsection:'famille', difficulty:2,
    question:'Que signifie "la mère" en anglais ?',
    options:['The sister','The grandmother','The mother','The daughter'],
    answer:'The mother',
    hint:'La famille : le père, la mère, le frère, la sœur...',
    explanation:'"<b>La mère</b>" = the mother. La famille : le père (father), la mère (mother), le frère (brother), la sœur (sister), le fils (son), la fille (daughter), le grand-père (grandfather), la grand-mère (grandmother).' }),

  makeMCQ({ id:'g4fr-voc-007', chapterId:'g4fr-vocabulaire', subsection:'nombres', difficulty:2,
    question:'Comment dit-on le nombre 15 en français ?',
    options:['cinquante','vingt','quinze','treize'],
    answer:'quinze',
    hint:'10 + 5 = ?',
    explanation:'"<b>Quinze</b>" = 15. Les nombres 11–20 : onze (11), douze (12), treize (13), quatorze (14), <b>quinze</b> (15), seize (16), dix-sept (17), dix-huit (18), dix-neuf (19), vingt (20).' }),

  makeMCQ({ id:'g4fr-voc-008', chapterId:'g4fr-vocabulaire', subsection:'couleurs', difficulty:2,
    question:'Quelle est la couleur "yellow" en français ?',
    options:['rose','jaune','vert','orange'],
    answer:'jaune',
    hint:'C\'est la couleur du soleil et des bananes.',
    explanation:'"<b>Jaune</b>" = yellow. "Jaune" does not change for feminine (une robe jaune, un pantalon jaune). Compare: rouge, vert/verte, bleu/bleue change for feminine. "Jaune" and "orange" are invariable (never add -e for feminine).' }),

  makeMCQ({ id:'g4fr-voc-009', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:2,
    question:'Quel est le jour du week-end après "samedi" ?',
    options:['lundi','vendredi','jeudi','dimanche'],
    answer:'dimanche',
    hint:'Le week-end = samedi et ___.',
    explanation:'"<b>Dimanche</b>" = Sunday. C\'est le dernier jour de la semaine en français. Le week-end comprend le samedi et le dimanche. Les jours de l\'école : lundi, mardi, mercredi, jeudi, vendredi.' }),

  makeMCQ({ id:'g4fr-voc-010', chapterId:'g4fr-vocabulaire', subsection:'temps', difficulty:4,
    question:'Priya rencontre son professeur le matin. Elle dit : "___, Monsieur Sharma. Comment allez-vous ?" Quelle salutation doit-elle utiliser ?',
    options:['Au revoir','Bonne nuit','Bonjour','Bonsoir'],
    answer:'Bonjour',
    hint:'C\'est le matin. Quelle salutation est appropriée pour le matin ?',
    explanation:'"<b>Bonjour</b>" est correct - c\'est la salutation du matin et de l\'après-midi. "Bonsoir" s\'utilise le soir uniquement. "Au revoir" signifie goodbye. "Bonne nuit" s\'utilise avant de dormir. Il est aussi correct de dire "Bonjour" à un professeur car on le vouvoie (vous).' })

);

STATIC_QUESTIONS.push(

  makeMCQ({ id:'g4fr-voc-011', chapterId:'g4fr-vocabulaire', subsection:'couleurs', difficulty:1,
    question:'Quelle est la couleur "black" en français ?',
    options:['blanc','rouge','noir','gris'],
    answer:'noir',
    hint:'C\'est la couleur de la nuit et du charbon.',
    explanation:'"<b>Noir</b>" = black. Les formes : noir (m.sg.), noire (f.sg.), noirs (m.pl.), noires (f.pl.). Blanc/blanche = white. Gris/grise = grey. Exemples : un chat noir (a black cat), une robe noire (a black dress).' }),

  makeMCQ({ id:'g4fr-voc-012', chapterId:'g4fr-vocabulaire', subsection:'nombres', difficulty:1,
    question:'Comment dit-on le nombre 20 en français ?',
    options:['douze','quinze','dix-neuf','vingt'],
    answer:'vingt',
    hint:'20 marque la fin de la série 1–20.',
    explanation:'"<b>Vingt</b>" = 20. Les dizaines : dix (10), vingt (20), trente (30), quarante (40), cinquante (50), soixante (60). Les nombres 21–29 : vingt et un (21), vingt-deux (22)... vingt-neuf (29).' }),

  makeMCQ({ id:'g4fr-voc-013', chapterId:'g4fr-vocabulaire', subsection:'politesse', difficulty:1,
    question:'Comment dit-on "please" en français (forme formelle, avec un adulte) ?',
    options:['Merci','Au revoir','S\'il vous plaît','De rien'],
    answer:"S'il vous plaît",
    hint:'"Please" en s\'adressant à un adulte - forme formelle (vous).',
    explanation:'"<b>S\'il vous plaît</b>" = please (formal - avec un adulte qu\'on vouvoie). "S\'il te plaît" = please (informal - avec un ami). "Merci" = thank you. "De rien" = you\'re welcome.' }),

  makeMCQ({ id:'g4fr-voc-014', chapterId:'g4fr-vocabulaire', subsection:'famille', difficulty:1,
    question:'Que signifie "le frère" en anglais ?',
    options:['The father','The son','The brother','The uncle'],
    answer:'The brother',
    hint:'La famille : le père, la mère, le frère, la sœur...',
    explanation:'"<b>Le frère</b>" = the brother. La famille : le père (father), la mère (mother), le frère (brother), la sœur (sister), le fils (son), la fille (daughter), le grand-père (grandfather), la grand-mère (grandmother).' }),

  makeMCQ({ id:'g4fr-voc-015', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:2,
    question:'Quel mois vient après "mars" ?',
    options:['janvier','février','mai','avril'],
    answer:'avril',
    hint:'Les mois : janvier, février, mars, ___, mai...',
    explanation:'L\'ordre des mois : janvier, février, mars, <b>avril</b>, mai, juin, juillet, août, septembre, octobre, novembre, décembre. En français, les mois ne prennent pas de majuscule (sauf en début de phrase).' }),

  makeMCQ({ id:'g4fr-voc-016', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:2,
    question:'Comment dit-on "white" en français (forme masculine) ?',
    options:['noir','gris','beige','blanc'],
    answer:'blanc',
    hint:'C\'est la couleur de la neige et du lait.',
    explanation:'"<b>Blanc</b>" = white (masculin). Forme féminine : "<b>blanche</b>". Exemples : un mur blanc, une robe blanche. "Blanc" a une forme féminine irrégulière (-c → -che).' }),

  makeMCQ({ id:'g4fr-voc-017', chapterId:'g4fr-vocabulaire', subsection:'nombres', difficulty:2,
    question:'Que signifie le nombre "douze" ?',
    options:['10','11','12','13'],
    answer:'12',
    hint:'Compte : onze (11), douze (?), treize (13).',
    explanation:'"<b>Douze</b>" = 12. Les nombres 11–20 : onze (11), <b>douze</b> (12), treize (13), quatorze (14), quinze (15), seize (16), dix-sept (17), dix-huit (18), dix-neuf (19), vingt (20).' }),

  makeMCQ({ id:'g4fr-voc-018', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:3,
    question:'Quel jour de la semaine vient juste AVANT "vendredi" ?',
    options:['samedi','mercredi','jeudi','mardi'],
    answer:'jeudi',
    hint:'Rappelle l\'ordre des jours : ..., mercredi, jeudi, vendredi, ...',
    explanation:'L\'ordre des jours : lundi, mardi, mercredi, <b>jeudi</b>, vendredi, samedi, dimanche. "Jeudi" (Thursday) vient directement avant "vendredi" (Friday).' }),

  makeMCQ({ id:'g4fr-voc-019', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:4,
    question:'Riya arrive à l\'école. Elle a déjà dit bonjour au professeur. Elle ne trouve pas son stylo et veut en demander un. Quelle phrase est la plus CORRECTE et la plus POLIE ?',
    options:[
      'Merci, avez-vous un stylo ?',
      'Bonjour, avez-vous un stylo ?',
      'Excusez-moi, s\'il vous plaît, avez-vous un stylo ?',
      'Au revoir, avez-vous un stylo ?'
    ],
    answer:"Excusez-moi, s'il vous plaît, avez-vous un stylo ?",
    hint:'Elle interrompt son professeur pour demander quelque chose. Quels mots de politesse utilise-t-on ?',
    explanation:'"<b>Excusez-moi, s\'il vous plaît</b>, avez-vous un stylo ?" est la phrase la plus polie. "Excusez-moi" (Excuse me) pour interrompre poliment + "s\'il vous plaît" (please, forme formelle). "Merci" se dit après avoir reçu quelque chose. "Bonjour" est une salutation, pas une demande.' }),

  makeMCQ({ id:'g4fr-voc-020', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Comment dit-on "head" en français ?',
    options:['bras','tête','jambe','pied'],
    answer:'tête',
    hint:'La tête est la partie du corps en haut.',
    explanation:'"Head" = <b>la tête</b>. Autres parties du corps : le <b>bras</b> (arm), la <b>jambe</b> (leg), le <b>pied</b> (foot).' }),

  makeMCQ({ id:'g4fr-voc-021', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Comment dit-on "brother" en français ?',
    options:['sœur','père','frère','oncle'],
    answer:'frère',
    hint:'Le frère est un garçon dans la famille.',
    explanation:'"Brother" = <b>le frère</b>. La famille proche : le <b>père</b> (father), la <b>mère</b> (mother), la <b>sœur</b> (sister), le <b>frère</b> (brother).' }),

  makeMCQ({ id:'g4fr-voc-022', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'Quel animal est un "dog" en français ?',
    options:['chat','chien','oiseau','lapin'],
    answer:'chien',
    hint:'Le chien est le meilleur ami de l\'homme.',
    explanation:'"Dog" = <b>le chien</b>. Autres animaux : le <b>chat</b> (cat), l\'<b>oiseau</b> (bird), le <b>lapin</b> (rabbit), le <b>poisson</b> (fish).' }),

  makeMCQ({ id:'g4fr-voc-023', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'Comment dit-on "tomorrow" en français ?',
    options:['hier','aujourd\'hui','demain','soir'],
    answer:'demain',
    hint:'Après "aujourd\'hui" vient "demain".',
    explanation:'"Tomorrow" = <b>demain</b>. Expressions de temps : <b>hier</b> (yesterday), <b>aujourd\'hui</b> (today), <b>demain</b> (tomorrow). Pour les moments : le <b>matin</b> (morning), l\'<b>après-midi</b> (afternoon), le <b>soir</b> (evening).' }),

  makeMCQ({ id:'g4fr-voc-024', chapterId:'g4fr-vocabulaire', subsection:'verbes_utiles', difficulty:1,
    question:'Comment dit-on "to drink" en français ?',
    options:['manger','dormir','boire','courir'],
    answer:'boire',
    hint:'On boit de l\'eau.',
    explanation:'"To drink" = <b>boire</b>. Autres verbes courants : <b>manger</b> (to eat), <b>dormir</b> (to sleep), <b>courir</b> (to run), <b>jouer</b> (to play), <b>lire</b> (to read), <b>écrire</b> (to write).' }),

  makeMCQ({ id:'g4fr-voc-025', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:2,
    question:'Comment dit-on "grandfather" en français ?',
    options:['oncle','grand-père','père','tante'],
    answer:'grand-père',
    hint:'Le père de ton père ou de ta mère.',
    explanation:'"Grandfather" = <b>grand-père</b>. La grande famille : <b>grand-père</b> (grandfather), <b>grand-mère</b> (grandmother), <b>oncle</b> (uncle), <b>tante</b> (aunt).' }),

  makeMCQ({ id:'g4fr-voc-026', chapterId:'g4fr-vocabulaire', subsection:'corps', difficulty:2,
    question:'Quelle partie du corps est le "nose" ?',
    options:['oreille','bouche','nez','dos'],
    answer:'nez',
    hint:'On sent les fleurs avec cette partie du visage.',
    explanation:'"Nose" = <b>le nez</b>. Autres parties du visage : l\'<b>oreille</b> (ear), la <b>bouche</b> (mouth), les <b>yeux</b> (eyes). Et le corps : le <b>dos</b> (back), le <b>ventre</b> (belly), la <b>main</b> (hand).' }),

  makeTF({ id:'g4fr-voc-027', chapterId:'g4fr-vocabulaire', subsection:'temps', difficulty:2,
    question:'"Hier" signifie "tomorrow" en anglais.',
    answer:false,
    hint:'"Hier" est l\'opposé de "demain".',
    explanation:'<b>Faux.</b> "Hier" = <b>yesterday</b> (pas "tomorrow"). "Tomorrow" = <b>demain</b>. Mémo : hier (before today), aujourd\'hui (today), demain (after today).' }),

  makeMCQ({ id:'g4fr-voc-028', chapterId:'g4fr-vocabulaire', subsection:'verbes_utiles', difficulty:2,
    question:'Quel verbe signifie "to run" ?',
    options:['sauter','courir','lire','écrire'],
    answer:'courir',
    hint:'Les athlètes font ça dans un stade.',
    explanation:'"To run" = <b>courir</b>. Verbes d\'action : <b>courir</b> (run), <b>sauter</b> (jump), <b>lire</b> (read), <b>écrire</b> (write). Astuce : "courir" ressemble à "course" (race).' }),

  makeMCQ({ id:'g4fr-voc-029', chapterId:'g4fr-vocabulaire', subsection:'temps', difficulty:2,
    question:'Quelle phrase utilise correctement "ce matin" ?',
    options:[
      'Je mange ce matin hier.',
      'Ce matin, je mange mon petit déjeuner.',
      'Demain ce matin je dors.',
      'Ce matin = après-midi.'
    ],
    answer:'Ce matin, je mange mon petit déjeuner.',
    hint:'"Ce matin" = this morning. Quelle phrase a du sens ?',
    explanation:'"<b>Ce matin, je mange mon petit déjeuner.</b>" - "Ce matin" (this morning) est une expression de temps qui se place souvent au début ou à la fin de la phrase. On ne peut pas dire "ce matin hier" (deux temps qui se contredisent).' }),

  makeMCQ({ id:'g4fr-voc-030', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:2,
    question:'Comment dit-on "hand" en français ?',
    options:['pied','jambe','main','bras'],
    answer:'main',
    hint:'On écrit avec cette partie du corps.',
    explanation:'"Hand" = <b>la main</b>. Astuce : "manicure" vient de "mani" (main en latin). Ne pas confondre : la <b>main</b> (hand) et le <b>bras</b> (arm) - le bras est plus long.' }),

  makeMCQ({ id:'g4fr-voc-031', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:3,
    question:'Associe : "poisson / oiseau / lapin" - quel animal NE VIT PAS normalement à la maison comme animal domestique ?',
    options:['poisson','oiseau','lapin','aucun - ils peuvent tous être des animaux domestiques'],
    answer:'aucun - ils peuvent tous être des animaux domestiques',
    hint:'Pense aux animaux qu\'on garde chez soi.',
    explanation:'<b>Les trois peuvent être des animaux domestiques !</b> Le <b>poisson</b> (aquarium), l\'<b>oiseau</b> (cage), le <b>lapin</b> (cage ou liberté dans la maison). En France et à Maurice, on garde souvent des poissons, des oiseaux et des lapins à la maison.' }),

  makeMCQ({ id:'g4fr-voc-032', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:3,
    question:'Quel mot est un verbe (action) ?',
    options:['tête','frère','dormir','chat'],
    answer:'dormir',
    hint:'Un verbe exprime une action ou un état.',
    explanation:'"<b>Dormir</b>" est un verbe (to sleep) - c\'est une action. <b>Tête</b> = nom (partie du corps), <b>frère</b> = nom (personne), <b>chat</b> = nom (animal). Les verbes répondent à la question "Que fait-on ?".' }),

  makeMCQ({ id:'g4fr-voc-033', chapterId:'g4fr-vocabulaire', subsection:'jours_mois', difficulty:3,
    question:'Quelle phrase est correcte pour décrire l\'heure de la journée ?',
    options:[
      'Je dors le matin et je me réveille le soir.',
      'Je me réveille le matin et je dors le soir.',
      'Le soir arrive avant le matin.',
      'L\'après-midi est avant le matin.'
    ],
    answer:'Je me réveille le matin et je dors le soir.',
    hint:'L\'ordre normal : matin → après-midi → soir → nuit.',
    explanation:'"<b>Je me réveille le matin et je dors le soir.</b>" - L\'ordre du jour : le <b>matin</b> (morning, on se réveille), l\'<b>après-midi</b> (afternoon), le <b>soir</b> (evening, on se couche). Le matin est avant le soir.' }),

  makeMCQ({ id:'g4fr-voc-034', chapterId:'g4fr-vocabulaire', subsection:'famille', difficulty:3,
    question:'Complète : "Mon ___ s\'appelle Jean et ma ___ s\'appelle Marie. Ensemble, ils sont mes grands-parents."',
    options:['père / mère','oncle / tante','grand-père / grand-mère','frère / sœur'],
    answer:'grand-père / grand-mère',
    hint:'Ils sont les parents de tes parents.',
    explanation:'"Mon <b>grand-père</b> s\'appelle Jean et ma <b>grand-mère</b> s\'appelle Marie." - Les grands-parents sont les parents de nos parents. Le <b>grand-père</b> (paternel ou maternel) + la <b>grand-mère</b> = les grands-parents.' }),

  makeMCQ({ id:'g4fr-voc-035', chapterId:'g4fr-vocabulaire', subsection:'temps', difficulty:4,
    question:'Priya écrit : "Ce matin, mon ___ (father) et ma ___ (mother) travaillent. Mon ___ (brother) et ma ___ (sister) sont à l\'école. Moi, je suis malade à la maison." Quelle série est correcte ?',
    options:[
      'père / mère / frère / sœur',
      'oncle / tante / frère / sœur',
      'grand-père / grand-mère / frère / sœur',
      'père / mère / oncle / tante'
    ],
    answer:'père / mère / frère / sœur',
    hint:'Father = ?, Mother = ?, Brother = ?, Sister = ?',
    explanation:'"Mon <b>père</b>" (father), "ma <b>mère</b>" (mother), "mon <b>frère</b>" (brother), "ma <b>sœur</b>" (sister). La famille proche : père, mère, frère, sœur. Note le genre : "mon" (masc.) devant père/frère, "ma" (fém.) devant mère/sœur.' }),

  makeMCQ({ id:'g4fr-voc-036', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Red_Apple.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['une pomme','une banane','une orange','une poire'],
    answer:'une pomme',
    hint:'C\'est un fruit rouge ou vert très commun.',
    explanation:'"<b>Une pomme</b>" = an apple. Les fruits : une pomme (apple), une banane (banana), une orange (orange), une poire (pear).' }),

  makeMCQ({ id:'g4fr-voc-037', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Banana.arp.750pix.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['une pomme','une banane','un citron','une mangue'],
    answer:'une banane',
    hint:'C\'est un fruit jaune et long.',
    explanation:'"<b>Une banane</b>" = a banana. Les fruits : une pomme (apple), une banane (banana), un citron (lemon), une mangue (mango).' }),

  makeMCQ({ id:'g4fr-voc-038', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Cat_domestic.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Quel est cet animal ?</b>',
    options:['un chien','un chat','un lapin','un oiseau'],
    answer:'un chat',
    hint:'Il ronronne et attrape des souris.',
    explanation:'"<b>Un chat</b>" = a cat. Les animaux domestiques : un chat (cat), un chien (dog), un lapin (rabbit), un oiseau (bird). Le chat dit "miaou" !' }),

  makeMCQ({ id:'g4fr-voc-039', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/YellowLabradorLooking_new.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Quel est cet animal ?</b>',
    options:['un chat','un chien','un renard','un loup'],
    answer:'un chien',
    hint:'C\'est le meilleur ami de l\'homme.',
    explanation:'"<b>Un chien</b>" = a dog. Le chien dit "ouaf" ! Les animaux domestiques : un chat (cat), un chien (dog), un poisson (fish), un hamster (hamster).' }),

  makeMCQ({ id:'g4fr-voc-040', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Old_book_bindings.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['un cahier','un livre','un stylo','un sac'],
    answer:'un livre',
    hint:'On le lit pour apprendre ou pour s\'amuser.',
    explanation:'"<b>Un livre</b>" = a book. Le matériel scolaire : un livre (book), un cahier (notebook), un stylo (pen), un crayon (pencil), une règle (ruler).' }),

  makeMCQ({ id:'g4fr-voc-041', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:2,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Chair.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['une table','une chaise','un bureau','un lit'],
    answer:'une chaise',
    hint:'On s\'assoit dessus.',
    explanation:'"<b>Une chaise</b>" = a chair. Le mobilier : une chaise (chair), une table (table), un bureau (desk), un lit (bed), une armoire (wardrobe).' }),

  makeMCQ({ id:'g4fr-voc-042', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Oranges.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Quel fruit est-ce ?</b>',
    options:['une pomme','une banane','une orange','une tomate'],
    answer:'une orange',
    hint:'C\'est un agrume rond et juteux.',
    explanation:'"<b>Une orange</b>" = an orange. Les agrumes : une orange (orange), un citron (lemon), une mandarine (tangerine). En français, "orange" est aussi une couleur !' }),

  makeMCQ({ id:'g4fr-voc-043', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Sun-in-the-sky.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['la lune','le soleil','une étoile','un nuage'],
    answer:'le soleil',
    hint:'Il brille pendant la journée et donne de la chaleur.',
    explanation:'"<b>Le soleil</b>" = the sun. Le ciel : le soleil (sun), la lune (moon), les étoiles (stars), un nuage (cloud). Le soleil se lève à l\'est et se couche à l\'ouest.' })

);

STATIC_QUESTIONS.push(

  makeMCQ({ id:'g4fr-voc-044', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/House.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['Une école','Une maison','Un magasin','Un hôpital'],
    answer:'Une maison',
    hint:'C\'est l\'endroit où une famille habite.',
    explanation:'"<b>Une maison</b>" = a house. Les bâtiments : une maison (house), une école (school), un magasin (shop), un hôpital (hospital).' }),

  makeMCQ({ id:'g4fr-voc-045', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Umbrella.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['Un chapeau','Un parapluie','Un sac','Un manteau'],
    answer:'Un parapluie',
    hint:'On l\'utilise pour se protéger de la pluie.',
    explanation:'"<b>Un parapluie</b>" = an umbrella. On l\'ouvre quand il pleut ! Les objets de pluie : un parapluie (umbrella), un manteau (coat), des bottes (boots).' }),

  makeMCQ({ id:'g4fr-voc-046', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Moon.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['Le soleil','La lune','Une étoile','Un nuage'],
    answer:'La lune',
    hint:'On la voit dans le ciel la nuit.',
    explanation:'"<b>La lune</b>" = the moon. Le ciel de nuit : la lune (moon), les étoiles (stars). Le ciel de jour : le soleil (sun), les nuages (clouds).' }),

  makeMCQ({ id:'g4fr-voc-047', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Fish.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Quel est cet animal ?</b>',
    options:['Un oiseau','Un poisson','Un lapin','Un chat'],
    answer:'Un poisson',
    hint:'Il vit dans l\'eau et respire avec des branchies.',
    explanation:'"<b>Un poisson</b>" = a fish. Les animaux aquatiques : un poisson (fish), une baleine (whale), un dauphin (dolphin).' }),

  makeMCQ({ id:'g4fr-voc-048', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Flower.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['Une fleur','Un arbre','Une feuille','Un fruit'],
    answer:'Une fleur',
    hint:'Elle pousse dans le jardin et sent souvent très bon.',
    explanation:'"<b>Une fleur</b>" = a flower. Le jardin : une fleur (flower), un arbre (tree), une feuille (leaf), l\'herbe (grass).' }),

  makeMCQ({ id:'g4fr-voc-049', chapterId:'g4fr-vocabulaire', subsection:'traduction', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Star.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Qu\'est-ce que c\'est ?</b>',
    options:['La lune','Le soleil','Une étoile','Un nuage'],
    answer:'Une étoile',
    hint:'On en voit beaucoup dans le ciel la nuit, elles brillent.',
    explanation:'"<b>Une étoile</b>" = a star. On dit "<b>l\'étoile</b>" (avec élision) devant une voyelle. Le ciel de nuit : la lune (moon), les étoiles (stars).' }),

  makeMCQ({ id:'g4fr-voc-050', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:2,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Sheep.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Quel est cet animal ?</b>',
    options:['Un mouton','Une vache','Un cheval','Une chèvre'],
    answer:'Un mouton',
    hint:'Il a une laine épaisse et fait "bêêê".',
    explanation:'"<b>Un mouton</b>" = a sheep. Les animaux de la ferme : un mouton (sheep), une vache (cow), un cheval (horse), une chèvre (goat).' }),

  makeMCQ({ id:'g4fr-voc-051', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:2,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Duck.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Quel est cet animal ?</b>',
    options:['Un canard','Une poule','Un oiseau','Un cygne'],
    answer:'Un canard',
    hint:'Il nage sur l\'eau et fait "coin coin".',
    explanation:'"<b>Un canard</b>" = a duck. Les oiseaux de la ferme : un canard (duck), une poule (hen), un coq (rooster), une oie (goose).' }),

  makeMCQ({ id:'g4fr-voc-052', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Rabbit.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Quel est cet animal ?</b>',
    options:['Un chat','Un lapin','Un hamster','Une souris'],
    answer:'Un lapin',
    hint:'Il a de longues oreilles et saute.',
    explanation:'"<b>Un lapin</b>" = a rabbit. Les petits animaux : un lapin (rabbit), un hamster (hamster), une souris (mouse).' }),

  makeMCQ({ id:'g4fr-voc-053', chapterId:'g4fr-vocabulaire', subsection:'animaux', difficulty:1,
    question:'<div style="text-align:center;margin-bottom:12px"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Bird.jpg" alt="une image" style="max-height:180px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15)"></div><b>Quel est cet animal ?</b>',
    options:['Un poisson','Un oiseau','Un papillon','Une abeille'],
    answer:'Un oiseau',
    hint:'Il a des ailes et peut voler dans le ciel.',
    explanation:'"<b>Un oiseau</b>" = a bird. On dit "<b>l\'oiseau</b>" (avec élision) devant une voyelle. Il vole dans le ciel avec ses ailes et chante souvent le matin.' })

);
