'use strict';
// Grade 4 French — local photographic observation activities.
// Multi-answer items deliberately use type:'multi': children must tick every
// statement supported by the picture, not guess one answer.
(function () {
  const photo = (file, alt) => `<figure style="margin:6px 0"><img src="assets/french-image-scenes/${file}" alt="${alt}" style="width:100%;max-width:620px;max-height:360px;object-fit:cover;border-radius:12px;box-shadow:0 2px 10px rgba(0,0,0,.18)"></figure>`;
  const add = (id, image, question, options, answer, hint, explanation) => STATIC_QUESTIONS.push({
    id, chapterId:'g4fr-images', subsection:'une_image', difficulty:2, type:'multi',
    question:`<div style="background:#eef2ff;border-left:4px solid #6366f1;border-radius:6px;padding:8px 12px;margin:6px 0"><b>Observe la photo. Plusieurs réponses sont possibles : coche toutes les bonnes réponses.</b></div>${image}${question}`,
    options, answer, hint, explanation
  });
  const paint = photo('children-playing.jpg','Une enfant à l’extérieur avec de la peinture colorée sur elle');
  const classPhoto = photo('classroom.jpg','Des élèves dans une salle de classe avec un enseignant');
  const market = photo('market.jpg','Des fruits et des légumes sur un étal de marché');

  add('g4fr-photo-001', paint, 'Que vois-tu sur la photo ?', ['Une enfant','De la peinture colorée','Un ruban jaune','Un bateau'], ['Une enfant','De la peinture colorée','Un ruban jaune'], 'Regarde le visage, les vêtements et les cheveux de l’enfant.', 'On voit <b>une enfant</b>, de la <b>peinture colorée</b> et un <b>ruban jaune</b>. On ne voit pas de bateau.');
  add('g4fr-photo-002', paint, 'Quelles phrases décrivent correctement l’enfant ?', ['Elle sourit.','Elle est dehors.','Elle a de la peinture sur le visage.','Elle est assise dans une classe.'], ['Elle sourit.','Elle est dehors.','Elle a de la peinture sur le visage.'], 'Observe l’expression de son visage et l’arrière-plan vert.', 'L’enfant <b>sourit</b>, elle est <b>dehors</b> et elle a de la <b>peinture sur le visage</b>.');
  add('g4fr-photo-003', paint, 'Quels mots peux-tu utiliser dans une description de cette photo ?', ['coloré','joyeux','vert','silencieux'], ['coloré','joyeux','vert'], 'Choisis des mots qui correspondent aux couleurs, au sourire et au jardin.', 'Les mots <b>coloré</b>, <b>joyeux</b> et <b>vert</b> conviennent. Une bonne description emploie des adjectifs précis.');
  add('g4fr-photo-004', paint, 'Quelles phrases sont au présent et correspondent à la photo ?', ['L’enfant regarde vers le haut.','Elle porte un ruban jaune.','Elle peint une maison.','Elle sourit.'], ['L’enfant regarde vers le haut.','Elle porte un ruban jaune.','Elle sourit.'], 'Regarde où va son regard, ses cheveux et son expression.', 'Elle <b>regarde vers le haut</b>, <b>porte un ruban jaune</b> et <b>sourit</b>. La photo ne montre pas une maison peinte.');

  add('g4fr-photo-005', classPhoto, 'Que vois-tu dans la salle de classe ?', ['Des élèves assis','Un enseignant debout','Des sacs à dos','Des vagues'], ['Des élèves assis','Un enseignant debout','Des sacs à dos'], 'Observe les personnes et les objets autour des tables.', 'On voit des <b>élèves assis</b>, un <b>enseignant debout</b> et des <b>sacs à dos</b>. Il n’y a pas de vagues.');
  add('g4fr-photo-006', classPhoto, 'Quelles actions ou situations sont visibles ?', ['Les élèves écoutent.','Le professeur parle devant la classe.','Les enfants nagent.','Les élèves travaillent à des tables.'], ['Les élèves écoutent.','Le professeur parle devant la classe.','Les élèves travaillent à des tables.'], 'Regarde l’enseignant devant le tableau et les enfants à leur place.', 'Les élèves sont à leurs tables et semblent écouter le professeur qui se tient devant la classe.');
  add('g4fr-photo-007', classPhoto, 'Quels mots de position sont utiles pour décrire cette image ?', ['devant le tableau','au premier plan','derrière les élèves','sous la mer'], ['devant le tableau','au premier plan','derrière les élèves'], 'Pense à la position du professeur, de l’élève proche de nous et des autres enfants.', 'Le professeur est <b>devant le tableau</b>. Certains élèves sont <b>au premier plan</b> et d’autres sont <b>derrière</b>.');
  add('g4fr-photo-008', classPhoto, 'Quelles phrases sont correctes ?', ['Il y a plusieurs élèves.','La scène se passe à l’école.','Un professeur est visible.','La classe est vide.'], ['Il y a plusieurs élèves.','La scène se passe à l’école.','Un professeur est visible.'], 'Compte les personnes et observe les tables, le tableau et les sacs.', 'Il y a plusieurs élèves et un professeur : la classe n’est pas vide.');

  add('g4fr-photo-009', market, 'Quels aliments vois-tu sur cet étal ?', ['Des oranges','Des poires','Des pommes ou grenades','Des crayons'], ['Des oranges','Des poires','Des pommes ou grenades'], 'Observe les couleurs et les formes des fruits.', 'On voit des <b>oranges</b>, des <b>poires</b> et des <b>pommes ou grenades</b>. Les crayons ne sont pas des aliments et ne sont pas visibles.');
  add('g4fr-photo-010', market, 'Quels adjectifs peuvent décrire cette photo ?', ['coloré','fruité','abondant','vide'], ['coloré','fruité','abondant'], 'Il y a beaucoup de fruits de plusieurs couleurs.', 'L’étal est <b>coloré</b>, <b>fruité</b> et <b>abondant</b>. Il n’est pas vide.');
  add('g4fr-photo-011', market, 'Quelles phrases décrivent correctement l’image ?', ['Les fruits sont rangés dans des caisses.','On voit plusieurs sortes de fruits.','Les fruits flottent dans l’eau.','Des étiquettes de prix sont visibles.'], ['Les fruits sont rangés dans des caisses.','On voit plusieurs sortes de fruits.','Des étiquettes de prix sont visibles.'], 'Regarde les boîtes et les petites ardoises noires.', 'Les fruits sont rangés dans des caisses; plusieurs variétés et des étiquettes de prix sont visibles.');
  add('g4fr-photo-012', market, 'Quels mots peux-tu employer pour situer les fruits ?', ['au centre','à gauche','à droite','dans le ciel'], ['au centre','à gauche','à droite'], 'La photo est prise du dessus : regarde les bords et le milieu.', 'Pour décrire cette photo, on peut dire qu’il y a des fruits <b>au centre</b>, <b>à gauche</b> et <b>à droite</b>.');
})();
