'use strict';
// Grade 8 Maths — expanded questions (ch02), continuing from ch01_core.js IDs

STATIC_QUESTIONS.push(

  // ── g8m-sequences ────────────────────────────────────────────────────────
  makeMCQ({ id:'g8m-sequences-006', chapterId:'g8m-sequences', difficulty:2,
    subsection:'continuing_sequences',
    question:'What is the next term in the sequence 2, 6, 18, 54, …?',
    options:['108','162','216','270'],
    answer:'162',
    hint:'Each term is multiplied by 3.',
    explanation:'The common ratio is 3. 54 × 3 = 162.' }),

  makeNum({ id:'g8m-sequences-007', chapterId:'g8m-sequences', difficulty:2,
    subsection:'continuing_sequences',
    question:'The sequence goes 100, 93, 86, 79, … What is the 6th term?',
    answer:65, tolerance:0,
    hint:'The sequence decreases by 7 each time.',
    explanation:'Terms: 100, 93, 86, 79, 72, 65. Subtract 7 each time; the 6th term is 65.' }),

  makeMCQ({ id:'g8m-sequences-008', chapterId:'g8m-sequences', difficulty:2,
    subsection:'sequence_rules',
    question:'A sequence has first term 5 and rule "add 4 each time". What is the 7th term?',
    options:['29','28','33','30'],
    answer:'29',
    hint:'Start at 5 and add 4 six more times.',
    explanation:'5, 9, 13, 17, 21, 25, 29. The 7th term is 29.' }),

  makeTF({ id:'g8m-sequences-009', chapterId:'g8m-sequences', difficulty:1,
    subsection:'sequence_rules',
    question:'The sequence 2, 4, 8, 16, … is an arithmetic sequence.',
    answer:false,
    explanation:'An arithmetic sequence has a constant DIFFERENCE between terms. Here the terms are multiplied by 2 each time (constant ratio) — this is a geometric, not arithmetic, sequence.' }),

  makeMCQ({ id:'g8m-sequences-010', chapterId:'g8m-sequences', difficulty:3,
    subsection:'nth_term',
    question:'The nth term of a sequence is 5n − 3. Which term has value 47?',
    options:['8th','9th','10th','11th'],
    answer:'10th',
    hint:'Set 5n − 3 = 47 and solve for n.',
    explanation:'5n − 3 = 47 → 5n = 50 → n = 10. The 10th term equals 47.' }),

  makeNum({ id:'g8m-sequences-011', chapterId:'g8m-sequences', difficulty:3,
    subsection:'nth_term',
    question:'Find the nth term of the arithmetic sequence 7, 10, 13, 16, … The nth term is 3n + ?. Type the constant.',
    answer:4, tolerance:0,
    hint:'Common difference = 3, so nth term = 3n + c. Test n=1: 3+c = 7.',
    explanation:'3(1) + c = 7 → c = 4. nth term = 3n + 4. Check n=2: 3(2)+4=10 ✓.' }),

  // ── g8m-indices ─────────────────────────────────────────────────────────
  makeMCQ({ id:'g8m-indices-006', chapterId:'g8m-indices', difficulty:1,
    subsection:'square_cube_roots',
    question:'What is the cube root of 125?',
    options:['4','5','6','25'],
    answer:'5',
    hint:'Find n where n × n × n = 125.',
    explanation:'5³ = 5 × 5 × 5 = 125. So ∛125 = 5.' }),

  makeNum({ id:'g8m-indices-007', chapterId:'g8m-indices', difficulty:2,
    subsection:'square_cube_roots',
    question:'What is √(4 × 9)?',
    answer:6, tolerance:0,
    hint:'Either multiply first and then take the square root, or use √4 × √9.',
    explanation:'√36 = 6. Or: √4 × √9 = 2 × 3 = 6.' }),

  makeMCQ({ id:'g8m-indices-008', chapterId:'g8m-indices', difficulty:2,
    subsection:'index_laws',
    question:'Simplify: (2³)²',
    options:['2⁵','2⁶','4⁶','2⁹'],
    answer:'2⁶',
    hint:'When raising a power to a power, MULTIPLY the indices.',
    explanation:'(2³)² = 2^(3×2) = 2⁶ = 64.' }),

  makeMCQ({ id:'g8m-indices-009', chapterId:'g8m-indices', difficulty:3,
    subsection:'index_laws',
    question:'Simplify: 5⁴ × 5³ ÷ 5²',
    options:['5⁵','5⁶','5⁷','5⁹'],
    answer:'5⁵',
    hint:'Multiply: add indices. Divide: subtract indices.',
    explanation:'5⁴ × 5³ = 5⁷. Then 5⁷ ÷ 5² = 5^(7−2) = 5⁵.' }),

  makeNum({ id:'g8m-indices-010', chapterId:'g8m-indices', difficulty:2,
    subsection:'evaluating_indices',
    question:'Evaluate: 4² + 3³',
    answer:43, tolerance:0,
    hint:'Calculate each power separately, then add.',
    explanation:'4² = 16; 3³ = 27. 16 + 27 = 43.' }),

  makeMCQ({ id:'g8m-indices-011', chapterId:'g8m-indices', difficulty:3,
    subsection:'evaluating_indices',
    question:'Which expression has the GREATEST value?',
    options:['3⁴','4³','2⁶','6²'],
    answer:'3⁴',
    hint:'Calculate each: 3⁴=81, 4³=64, 2⁶=64, 6²=36.',
    explanation:'3⁴=81, 4³=64, 2⁶=64, 6²=36. The greatest value is 3⁴=81.' }),

  // ── g8m-rate ─────────────────────────────────────────────────────────────
  makeNum({ id:'g8m-rate-006', chapterId:'g8m-rate', difficulty:1,
    subsection:'unit_rates',
    question:'A car travels 260 km using 20 litres of fuel. How many km per litre does it achieve?',
    answer:13, tolerance:0,
    hint:'Divide total distance by total fuel.',
    explanation:'260 ÷ 20 = 13 km per litre.' }),

  makeMCQ({ id:'g8m-rate-007', chapterId:'g8m-rate', difficulty:2,
    subsection:'unit_rates',
    question:'A worker earns Rs 480 for 6 hours. How much does she earn for 9 hours?',
    options:['Rs 640','Rs 700','Rs 720','Rs 800'],
    answer:'Rs 720',
    hint:'Find the hourly rate, then multiply by 9.',
    explanation:'Hourly rate = 480 ÷ 6 = Rs 80. For 9 hours: 80 × 9 = Rs 720.' }),

  makeMCQ({ id:'g8m-rate-008', chapterId:'g8m-rate', difficulty:2,
    subsection:'direct_proportion',
    question:'y is directly proportional to x. When x = 4, y = 20. What is y when x = 7?',
    options:['28','35','42','56'],
    answer:'35',
    hint:'Find the constant of proportionality k = y ÷ x.',
    explanation:'k = 20 ÷ 4 = 5. When x = 7: y = 5 × 7 = 35.' }),

  makeNum({ id:'g8m-rate-009', chapterId:'g8m-rate', difficulty:3,
    subsection:'direct_proportion',
    question:'3 kg of sugar costs Rs 135. How much do 7 kg cost?',
    answer:315, tolerance:0,
    hint:'Cost per kg = 135 ÷ 3. Multiply by 7.',
    explanation:'Per kg = Rs 45. For 7 kg: 45 × 7 = Rs 315.' }),

  makeMCQ({ id:'g8m-rate-010', chapterId:'g8m-rate', difficulty:4,
    subsection:'rate_problems',
    question:'A factory produces 240 units per hour working 8 hours a day. How many days to produce 11,520 units?',
    options:['4 days','5 days','6 days','8 days'],
    answer:'6 days',
    hint:'Daily production = 240 × 8. Days = total ÷ daily.',
    explanation:'Daily = 240 × 8 = 1,920. Days = 11,520 ÷ 1,920 = 6 days.' }),

  // ── g8m-finance ──────────────────────────────────────────────────────────
  makeNum({ id:'g8m-finance-006', chapterId:'g8m-finance', difficulty:2,
    subsection:'simple_interest',
    question:'Find the simple interest on Rs 5,000 at 4% per year for 2 years.',
    answer:400, tolerance:0,
    hint:'SI = (P × R × T) ÷ 100',
    explanation:'SI = (5,000 × 4 × 2) ÷ 100 = 40,000 ÷ 100 = Rs 400.' }),

  makeMCQ({ id:'g8m-finance-007', chapterId:'g8m-finance', difficulty:3,
    subsection:'simple_interest',
    question:'At what rate % per annum will Rs 3,000 earn Rs 360 simple interest in 2 years?',
    options:['5%','6%','8%','10%'],
    answer:'6%',
    hint:'Rate = (SI × 100) ÷ (P × T).',
    explanation:'Rate = (360 × 100) ÷ (3,000 × 2) = 36,000 ÷ 6,000 = 6%.' }),

  makeMCQ({ id:'g8m-finance-008', chapterId:'g8m-finance', difficulty:2,
    subsection:'profit_loss_discount',
    question:'An item costs Rs 250 to make and is sold for Rs 200. What is the loss percentage?',
    options:['10%','20%','25%','50%'],
    answer:'20%',
    hint:'Loss % = (Loss ÷ Cost price) × 100.',
    explanation:'Loss = 50. Loss % = (50 ÷ 250) × 100 = 20%.' }),

  makeNum({ id:'g8m-finance-009', chapterId:'g8m-finance', difficulty:3,
    subsection:'profit_loss_discount',
    question:'A jacket is marked at Rs 2,400 and sold at a 15% discount. What is the selling price in rupees?',
    answer:2040, tolerance:0,
    hint:'Discount = 15% of 2,400. Selling price = 2,400 − discount.',
    explanation:'Discount = 0.15 × 2,400 = 360. Selling price = 2,400 − 360 = Rs 2,040.' }),

  makeMCQ({ id:'g8m-finance-010', chapterId:'g8m-finance', difficulty:4,
    subsection:'bills_budgeting',
    question:'A family earns Rs 24,000 per month. They budget: 40% rent, 25% food, 15% transport, 10% savings. How much is left unbudgeted?',
    options:['Rs 2,200','Rs 2,400','Rs 2,600','Rs 3,000'],
    answer:'Rs 2,400',
    hint:'Total budgeted % = 40+25+15+10. Remaining % × 24,000.',
    explanation:'Budgeted: 90%. Remaining: 10%. 10% of 24,000 = Rs 2,400.' }),

  // ── g8m-polygons ─────────────────────────────────────────────────────────
  makeNum({ id:'g8m-polygons-006', chapterId:'g8m-polygons', difficulty:2,
    subsection:'interior_exterior_angles',
    question:'What is one exterior angle of a regular hexagon in degrees?',
    answer:60, tolerance:0,
    hint:'Exterior angle of a regular polygon = 360° ÷ number of sides.',
    explanation:'360 ÷ 6 = 60°. The six exterior angles of a regular hexagon each measure 60°.' }),

  makeMCQ({ id:'g8m-polygons-007', chapterId:'g8m-polygons', difficulty:2,
    subsection:'interior_exterior_angles',
    question:'An interior angle and its adjacent exterior angle at the same vertex are …',
    options:['Equal','Supplementary (add to 180°)','Complementary (add to 90°)','Vertically opposite'],
    answer:'Supplementary (add to 180°)',
    hint:'They form a straight line together.',
    explanation:'An interior and the adjacent exterior angle at the same vertex lie on a straight line, so they add to 180°.' }),

  makeNum({ id:'g8m-polygons-008', chapterId:'g8m-polygons', difficulty:2,
    subsection:'angle_sum',
    question:'What is the sum of interior angles of a heptagon (7 sides) in degrees?',
    answer:900, tolerance:0,
    hint:'(n − 2) × 180. Use n = 7.',
    explanation:'(7 − 2) × 180 = 5 × 180 = 900°.' }),

  makeMCQ({ id:'g8m-polygons-009', chapterId:'g8m-polygons', difficulty:3,
    subsection:'angle_sum',
    question:'A pentagon has four angles of 110° each. What is the fifth angle?',
    options:['100°','110°','120°','130°'],
    answer:'100°',
    hint:'Sum of pentagon interior angles = 540°. Subtract 4 × 110°.',
    explanation:'4 × 110 = 440. Fifth angle = 540 − 440 = 100°.' }),

  makeMCQ({ id:'g8m-polygons-010', chapterId:'g8m-polygons', difficulty:2,
    subsection:'regular_polygons',
    question:'A regular polygon has interior angles of 120° each. How many sides does it have?',
    options:['5','6','8','9'],
    answer:'6',
    hint:'Use: exterior angle = 180° − 120°. Then 360° ÷ exterior angle.',
    explanation:'Exterior angle = 60°. Number of sides = 360 ÷ 60 = 6. It is a regular hexagon.' }),

  makeTF({ id:'g8m-polygons-011', chapterId:'g8m-polygons', difficulty:1,
    subsection:'regular_polygons',
    question:'In any polygon, the sum of ALL exterior angles (one at each vertex) is always 360°.',
    answer:true,
    explanation:'For any convex polygon, the exterior angles sum to exactly 360°, regardless of the number of sides.' }),

  // ── g8m-coordinates ──────────────────────────────────────────────────────
  makeMCQ({ id:'g8m-coordinates-006', chapterId:'g8m-coordinates', difficulty:1,
    subsection:'four_quadrants',
    question:'Which quadrant contains the point (−2, 7)?',
    options:['Quadrant I','Quadrant II','Quadrant III','Quadrant IV'],
    answer:'Quadrant II',
    hint:'Q II: x negative, y positive.',
    explanation:'x = −2 (negative), y = 7 (positive). This is Quadrant II (top-left).' }),

  makeNum({ id:'g8m-coordinates-007', chapterId:'g8m-coordinates', difficulty:2,
    subsection:'midpoint',
    question:'Find the midpoint of the segment from (−4, 6) to (8, 2). What is the x-coordinate of the midpoint?',
    answer:2, tolerance:0,
    hint:'x-midpoint = (x₁ + x₂) ÷ 2.',
    explanation:'(−4 + 8) ÷ 2 = 4 ÷ 2 = 2. (y-midpoint = (6+2)÷2 = 4, so midpoint is (2, 4).)' }),

  makeMCQ({ id:'g8m-coordinates-008', chapterId:'g8m-coordinates', difficulty:3,
    subsection:'midpoint',
    question:'P is the midpoint of AB. B is at (9, 1) and P is at (4, 3). What is the y-coordinate of A?',
    options:['3','5','7','2'],
    answer:'5',
    hint:'(y_A + 1) ÷ 2 = 3. Solve for y_A.',
    explanation:'(y_A + 1) ÷ 2 = 3 → y_A + 1 = 6 → y_A = 5.' }),

  makeMCQ({ id:'g8m-coordinates-009', chapterId:'g8m-coordinates', difficulty:2,
    subsection:'linear_graphs',
    question:'The line y = 3x − 2 passes through which of these points?',
    options:['(1, 2)','(2, 4)','(2, 5)','(3, 6)'],
    answer:'(2, 4)',
    hint:'Substitute x = 2 into y = 3x − 2.',
    explanation:'y = 3(2) − 2 = 6 − 2 = 4. So (2, 4) lies on the line.' }),

  makeNum({ id:'g8m-coordinates-010', chapterId:'g8m-coordinates', difficulty:3,
    subsection:'linear_graphs',
    question:'A line has equation y = 2x + 1. What is the y-intercept?',
    answer:1, tolerance:0,
    hint:'The y-intercept is the value of y when x = 0.',
    explanation:'When x = 0: y = 2(0) + 1 = 1. The y-intercept is 1.' }),

  // ── g8m-circles ──────────────────────────────────────────────────────────
  makeMCQ({ id:'g8m-circles-006', chapterId:'g8m-circles', difficulty:1,
    subsection:'parts_circle',
    question:'A line segment joining two points on a circle (not passing through the centre) is called a …',
    options:['Radius','Diameter','Chord','Arc'],
    answer:'Chord',
    hint:'It connects two points on the circumference but does not pass through the centre.',
    explanation:'A chord connects two points on a circle. If it passes through the centre it is a diameter.' }),

  makeNum({ id:'g8m-circles-007', chapterId:'g8m-circles', difficulty:2,
    subsection:'circumference',
    question:'A circle has diameter 21 cm. Calculate its circumference. Use π = 22/7. Answer in cm.',
    answer:66, tolerance:0,
    hint:'Circumference = π × d.',
    explanation:'C = (22/7) × 21 = 22 × 3 = 66 cm.' }),

  makeNum({ id:'g8m-circles-008', chapterId:'g8m-circles', difficulty:2,
    subsection:'area_circle',
    question:'A circle has diameter 14 cm. Find its area using π = 22/7. Answer in cm².',
    answer:154, tolerance:0,
    hint:'Radius = 7 cm. Area = πr².',
    explanation:'r = 7. A = (22/7) × 7² = (22/7) × 49 = 154 cm².' }),

  makeMCQ({ id:'g8m-circles-009', chapterId:'g8m-circles', difficulty:3,
    subsection:'area_circle',
    question:'A circular lawn has radius 3.5 m. Using π = 22/7, what is its area?',
    options:['22 m²','38.5 m²','44 m²','77 m²'],
    answer:'38.5 m²',
    hint:'Area = πr². r = 3.5 m.',
    explanation:'A = (22/7) × 3.5² = (22/7) × 12.25 = 22 × 1.75 = 38.5 m².' }),

  makeMCQ({ id:'g8m-circles-010', chapterId:'g8m-circles', difficulty:4,
    subsection:'circumference',
    question:'A wheel of diameter 70 cm makes 200 complete rotations. What total distance does it travel in metres? (π = 22/7)',
    options:['220 m','440 m','880 m','44 m'],
    answer:'440 m',
    hint:'Distance per rotation = circumference. Total = circumference × 200.',
    explanation:'C = πd = (22/7)×70 = 220 cm. Total = 220 × 200 = 44,000 cm = 440 m.' }),

  // ── g8m-surface-area ─────────────────────────────────────────────────────
  makeMCQ({ id:'g8m-surface-area-006', chapterId:'g8m-surface-area', difficulty:1,
    subsection:'nets',
    question:'A net of a cuboid consists of how many rectangles?',
    options:['4','5','6','8'],
    answer:'6',
    hint:'A cuboid has 6 faces.',
    explanation:'A cuboid has 6 rectangular faces (opposite faces are equal). Its net therefore has 6 rectangles.' }),

  makeNum({ id:'g8m-surface-area-007', chapterId:'g8m-surface-area', difficulty:2,
    subsection:'cuboid_surface',
    question:'Find the surface area of a cube with side 6 cm (in cm²).',
    answer:216, tolerance:0,
    hint:'SA of cube = 6 × side².',
    explanation:'SA = 6 × 6² = 6 × 36 = 216 cm².' }),

  makeNum({ id:'g8m-surface-area-008', chapterId:'g8m-surface-area', difficulty:3,
    subsection:'cuboid_surface',
    question:'A cuboid has length 10 cm, width 4 cm and height 3 cm. What is its surface area in cm²?',
    answer:164, tolerance:0,
    hint:'SA = 2(lw + wh + lh).',
    explanation:'2(10×4 + 4×3 + 10×3) = 2(40 + 12 + 30) = 2 × 82 = 164 cm².' }),

  makeMCQ({ id:'g8m-surface-area-009', chapterId:'g8m-surface-area', difficulty:3,
    subsection:'prism_surface',
    question:'A triangular prism has two triangular ends each with area 24 cm² and three rectangular faces with areas 30, 40 and 50 cm². What is the total surface area?',
    options:['144 cm²','168 cm²','148 cm²','120 cm²'],
    answer:'168 cm²',
    hint:'Total = 2 × triangular face + sum of rectangular faces.',
    explanation:'2 × 24 + 30 + 40 + 50 = 48 + 120 = 168 cm².' }),

  makeMCQ({ id:'g8m-surface-area-010', chapterId:'g8m-surface-area', difficulty:4,
    subsection:'prism_surface',
    question:'A rectangular box (open-topped, no lid) measures 8 cm × 5 cm × 4 cm. What is its surface area in cm²?',
    options:['144 cm²','184 cm²','152 cm²','124 cm²'],
    answer:'144 cm²',
    hint:'SA = 1 base + 4 sides (no top). Base = 8×5. Two pairs of rectangular sides.',
    explanation:'Base = 40 cm². Two sides: 2×(8×4)=64; two ends: 2×(5×4)=40. Total = 40+64+40 = 144 cm².' }),

  // ── g8m-volume ───────────────────────────────────────────────────────────
  makeNum({ id:'g8m-volume-006', chapterId:'g8m-volume', difficulty:2,
    subsection:'cuboid_volume',
    question:'A swimming pool is 25 m long, 10 m wide and 2 m deep. What is its volume in m³?',
    answer:500, tolerance:0,
    hint:'Volume = length × width × height.',
    explanation:'V = 25 × 10 × 2 = 500 m³.' }),

  makeMCQ({ id:'g8m-volume-007', chapterId:'g8m-volume', difficulty:2,
    subsection:'unit_conversion',
    question:'A container holds 3.5 litres. How many cm³ is this?',
    options:['350','3,500','35,000','350,000'],
    answer:'3,500',
    hint:'1 litre = 1,000 cm³.',
    explanation:'3.5 × 1,000 = 3,500 cm³.' }),

  makeNum({ id:'g8m-volume-008', chapterId:'g8m-volume', difficulty:3,
    subsection:'prism_volume',
    question:'A prism has a cross-section that is a right-angled triangle with base 6 cm and height 4 cm. Its length is 12 cm. Find the volume in cm³.',
    answer:144, tolerance:0,
    hint:'Cross-section area = ½ × 6 × 4. Volume = area × length.',
    explanation:'Cross-section = ½ × 6 × 4 = 12 cm². Volume = 12 × 12 = 144 cm³.' }),

  makeMCQ({ id:'g8m-volume-009', chapterId:'g8m-volume', difficulty:3,
    subsection:'prism_volume',
    question:'Two cubes have sides 3 cm and 4 cm. What is the combined volume in cm³?',
    options:['55 cm³','91 cm³','91 cm³','108 cm³'],
    answer:'91 cm³',
    hint:'Volume of cube = side³. Add the two volumes.',
    explanation:'3³ = 27; 4³ = 64. Combined = 27 + 64 = 91 cm³.' }),

  makeNum({ id:'g8m-volume-010', chapterId:'g8m-volume', difficulty:4,
    subsection:'unit_conversion',
    question:'A rectangular tank is 60 cm × 40 cm × 50 cm. It is ⅜ full of water. How many litres of water does it contain?',
    answer:45, tolerance:0,
    hint:'Full volume in cm³ × ⅜ ÷ 1,000.',
    explanation:'Full = 60 × 40 × 50 = 120,000 cm³. ⅜ of 120,000 = 45,000 cm³ = 45 litres.' }),

  // ── g8m-algebra ──────────────────────────────────────────────────────────
  makeMCQ({ id:'g8m-algebra-006', chapterId:'g8m-algebra', difficulty:2,
    subsection:'expanding_brackets',
    question:'Expand: 4(3x − 2)',
    options:['12x − 2','12x − 8','7x − 8','12x + 8'],
    answer:'12x − 8',
    hint:'Multiply each term inside by 4.',
    explanation:'4 × 3x = 12x; 4 × (−2) = −8. Result: 12x − 8.' }),

  makeMCQ({ id:'g8m-algebra-007', chapterId:'g8m-algebra', difficulty:3,
    subsection:'expanding_brackets',
    question:'Expand and simplify: 3(2x + 5) − 2(x − 3)',
    options:['4x + 21','8x + 9','4x + 9','8x + 21'],
    answer:'4x + 21',
    hint:'Expand each bracket carefully, watching the signs.',
    explanation:'3(2x+5) = 6x+15; −2(x−3) = −2x+6. Sum: 4x+21.' }),

  makeMCQ({ id:'g8m-algebra-008', chapterId:'g8m-algebra', difficulty:2,
    subsection:'factorising',
    question:'Factorise: 6x + 9',
    options:['3(x + 3)','3(2x + 3)','6(x + 3)','9(x + 1)'],
    answer:'3(2x + 3)',
    hint:'HCF of 6x and 9 is 3.',
    explanation:'HCF = 3. 6x + 9 = 3(2x + 3).' }),

  makeMCQ({ id:'g8m-algebra-009', chapterId:'g8m-algebra', difficulty:3,
    subsection:'factorising',
    question:'Factorise completely: 12a² − 8a',
    options:['4a(3a − 2)','4(3a² − 2a)','8a(a − 1)','2a(6a − 4)'],
    answer:'4a(3a − 2)',
    hint:'HCF of 12a² and 8a is 4a.',
    explanation:'HCF = 4a. 12a² − 8a = 4a(3a − 2).' }),

  makeMCQ({ id:'g8m-algebra-010', chapterId:'g8m-algebra', difficulty:3,
    subsection:'algebraic_fractions',
    question:'Simplify: (10x²) ÷ (4x)',
    options:['5x/2','5x','2x/5','10x'],
    answer:'5x/2',
    hint:'Divide both numerator and denominator by 2x.',
    explanation:'10x² ÷ 4x = (10/4) × (x²/x) = (5/2)x = 5x/2.' }),

  makeMCQ({ id:'g8m-algebra-011', chapterId:'g8m-algebra', difficulty:4,
    subsection:'algebraic_fractions',
    question:'Simplify: (3x + 6) ÷ 3',
    options:['x + 6','x + 2','3x + 2','3(x + 2)'],
    answer:'x + 2',
    hint:'Divide each term in the numerator by 3.',
    explanation:'(3x + 6) ÷ 3 = 3x/3 + 6/3 = x + 2.' }),

  // ── g8m-statistics ───────────────────────────────────────────────────────
  makeNum({ id:'g8m-statistics-006', chapterId:'g8m-statistics', difficulty:2,
    subsection:'pie_charts',
    question:'A class of 40 students. 15 chose Art. What angle represents Art in a pie chart?',
    answer:135, tolerance:0,
    hint:'Angle = (frequency ÷ total) × 360°.',
    explanation:'(15 ÷ 40) × 360 = 0.375 × 360 = 135°.' }),

  makeMCQ({ id:'g8m-statistics-007', chapterId:'g8m-statistics', difficulty:3,
    subsection:'pie_charts',
    question:'In a pie chart, a sector representing 45 students has an angle of 90°. How many students are in the whole sample?',
    options:['90','180','360','405'],
    answer:'180',
    hint:'90° is ¼ of 360°, so 45 students = ¼ of the total.',
    explanation:'90° out of 360° = ¼ of the total. Total = 45 × 4 = 180.' }),

  makeNum({ id:'g8m-statistics-008', chapterId:'g8m-statistics', difficulty:2,
    subsection:'mean_median_mode',
    question:'Find the mean of: 12, 15, 9, 18, 11.',
    answer:13, tolerance:0,
    hint:'Mean = sum ÷ count.',
    explanation:'Sum = 12+15+9+18+11 = 65. Mean = 65 ÷ 5 = 13.' }),

  makeMCQ({ id:'g8m-statistics-009', chapterId:'g8m-statistics', difficulty:2,
    subsection:'mean_median_mode',
    question:'What is the median of: 8, 3, 6, 2, 9, 5, 7?',
    options:['5','6','7','8'],
    answer:'6',
    hint:'Arrange in order first, then find the middle value.',
    explanation:'Ordered: 2, 3, 5, 6, 7, 8, 9. Middle (4th) value = 6.' }),

  makeMCQ({ id:'g8m-statistics-010', chapterId:'g8m-statistics', difficulty:3,
    subsection:'comparing_data',
    question:'Set A: mean 65, range 30. Set B: mean 65, range 10. Which conclusion is correct?',
    options:['Set A is more consistent','Set B is more consistent','Both are equally consistent','Cannot compare'],
    answer:'Set B is more consistent',
    hint:'A smaller range means less spread — more consistent data.',
    explanation:'Both sets have the same mean, but Set B has a smaller range (10 vs 30), meaning its data values are closer together — more consistent.' }),

  makeNum({ id:'g8m-statistics-011', chapterId:'g8m-statistics', difficulty:3,
    subsection:'comparing_data',
    question:'Six students scored: 70, 74, 68, 80, 72, 76. What is the range?',
    answer:12, tolerance:0,
    hint:'Range = highest score − lowest score.',
    explanation:'Highest = 80; lowest = 68. Range = 80 − 68 = 12.' })

);
