'use strict';
// ══════════════════════════════════════════════════════════════════════════
//  Grade 9 Chemistry - C4 · Metals & Reactivity — Volume Bank
//  85 questions  ·  IDs g9s-c4-v001 … g9s-c4-v085
//  Subsections: metals_with_oxygen · metals_with_acids ·
//               metals_with_water_steam · reactivity_series ·
//               predicting_reactions · equations_for_metals
//  Source: NCE Science (Chemistry) 2021-2025; NCF Grades 7-9 §C4.
// ══════════════════════════════════════════════════════════════════════════
(function () {

const CH = 'g9s-c4-metals';

const MCQ = [

  // ── metals_with_oxygen ───────────────────────────────────────────────────
  ['g9s-c4-v001', 'metals_with_oxygen', 1,
   'What type of compound is formed when a metal reacts with oxygen?',
   ['Metal oxide', 'Metal hydroxide', 'Metal carbonate', 'Metal chloride'],
   'Metal oxide',
   'Oxygen is added to the metal.',
   'When a metal burns in oxygen the metal combines with oxygen to form a metal oxide: metal + oxygen → metal oxide.'],

  ['g9s-c4-v002', 'metals_with_oxygen', 1,
   'Which observation is seen when magnesium burns in air?',
   ['A dazzling white flame and a white powdery ash (magnesium oxide)',
    'A green flame and a brown solid residue',
    'A colourless flame and a grey powder',
    'A blue flame and a clear liquid residue'],
   'A dazzling white flame and a white powdery ash (magnesium oxide)',
   'Magnesium is a reactive metal that burns very brightly.',
   '2Mg + O₂ → 2MgO. Magnesium burns with an intense white flame (used in flares and fireworks) and the white powder is magnesium oxide.'],

  ['g9s-c4-v003', 'metals_with_oxygen', 2,
   'Copper reacts slowly with oxygen at high temperature to form a black coating. What is this coating?',
   ['Copper(II) oxide (CuO)', 'Copper(I) oxide (Cu₂O)', 'Copper carbonate', 'Copper chloride'],
   'Copper(II) oxide (CuO)',
   'Copper forms a black product with oxygen.',
   '2Cu + O₂ → 2CuO. Copper forms black copper(II) oxide on prolonged heating in air.'],

  ['g9s-c4-v004', 'metals_with_oxygen', 2,
   'Iron does not burn in air under normal conditions. Under what conditions does iron react with oxygen?',
   ['When iron wool is heated strongly in pure oxygen it burns with bright glowing sparks',
    'When iron is submerged in liquid oxygen it reacts instantly',
    'Iron always burns in air if the surface is polished',
    'Iron reacts with oxygen only at extremely low temperatures'],
   'When iron wool is heated strongly in pure oxygen it burns with bright glowing sparks',
   'Fine iron particles have a much larger surface area.',
   'Iron wool, with its large surface area, burns vigorously in pure oxygen: 3Fe + 2O₂ → Fe₃O₄, producing bright orange sparks.'],

  ['g9s-c4-v005', 'metals_with_oxygen', 2,
   'Why does the reaction of sodium with oxygen have to be done carefully in a laboratory?',
   ['Sodium is stored in oil because it reacts rapidly and violently with both air and moisture',
    'Sodium produces a toxic purple gas when it burns in oxygen',
    'The reaction is endothermic and causes the surrounding apparatus to freeze',
    'Sodium must be heated to 1000 °C before it will react with oxygen'],
   'Sodium is stored in oil because it reacts rapidly and violently with both air and moisture',
   'Sodium is one of the most reactive metals.',
   'Sodium reacts rapidly with O₂ and with water in the air; it is stored under oil to prevent contact. When it burns in oxygen it produces sodium peroxide (Na₂O₂) as well as Na₂O.'],

  ['g9s-c4-v006', 'metals_with_oxygen', 3,
   'Gold does not react with oxygen even at very high temperatures. What does this tell us about gold?',
   ['Gold is very unreactive, which is why it does not tarnish and is used for jewellery',
    'Gold is too light to hold the oxygen that reacts with it',
    'Gold already contains oxygen in its ore, so no further reaction occurs',
    'Gold reacts with nitrogen instead of oxygen when heated'],
   'Gold is very unreactive, which is why it does not tarnish and is used for jewellery',
   'Reactivity with oxygen is a measure of how reactive a metal is.',
   'Gold\'s extreme lack of reactivity means it does not oxidise; this makes it unreactive with air, acids and water — hence its use in jewellery, electronics and dentistry.'],

  ['g9s-c4-v007', 'metals_with_oxygen', 2,
   'The product of reacting potassium with oxygen is mainly potassium superoxide (KO₂). What does this suggest about potassium?',
   ['Potassium is so reactive it can oxidise beyond the normal K₂O to form higher oxides',
    'Potassium is less reactive than sodium because sodium only forms Na₂O',
    'Potassium reacts with the nitrogen in air rather than the oxygen',
    'Potassium is unique in that its oxide is a liquid at room temperature'],
   'Potassium is so reactive it can oxidise beyond the normal K₂O to form higher oxides',
   'More reactive metals can form more highly oxidised products.',
   'Potassium\'s high reactivity means it has enough energy to form KO₂ (superoxide) in air, not just the simple oxide K₂O; sodium gives Na₂O₂ (peroxide), and lithium gives the normal oxide Li₂O.'],

  ['g9s-c4-v008', 'metals_with_oxygen', 3,
   'When aluminium is exposed to air, a thin oxide layer forms rapidly. Why does aluminium then appear not to corrode further?',
   ['The thin, adherent Al₂O₃ layer acts as a barrier, preventing further oxygen from reaching the metal underneath',
    'Aluminium reacts with nitrogen in the air to form a protective nitride coating instead',
    'The Al₂O₃ layer dissolves in rain water and exposes fresh metal which then re-oxidises every day',
    'Aluminium has no further reactivity after the first atom layer has reacted'],
   'The thin, adherent Al₂O₃ layer acts as a barrier, preventing further oxygen from reaching the metal underneath',
   'Some oxides protect; some (like rust on iron) do not.',
   'Al₂O₃ is a hard, insoluble oxide that sticks firmly to the aluminium surface; unlike rust (which is porous and flaky), this layer seals the surface and prevents further oxidation.'],

  ['g9s-c4-v009', 'metals_with_oxygen', 1,
   'Which of these metals forms a red oxide (Fe₂O₃) that we commonly call rust?',
   ['Iron', 'Copper', 'Aluminium', 'Zinc'],
   'Iron',
   'This is the most common form of metal corrosion in everyday life.',
   'Iron rusts in the presence of both water and oxygen: 4Fe + 3O₂ + 2H₂O → 2Fe₂O₃·H₂O; the red-brown product is hydrated iron(III) oxide.'],

  ['g9s-c4-v010', 'metals_with_oxygen', 2,
   'When zinc is heated in air it forms zinc oxide. A student notes the white powder turns yellow when hot and white again when cold. This is an example of:',
   ['A thermochromic colour change — ZnO changes colour reversibly with temperature',
    'A chemical reaction that is reversed on cooling — ZnO decomposes back to Zn and O₂',
    'Contamination of the zinc oxide by the Bunsen burner gas',
    'The zinc melting and resolidifying in a different crystalline form'],
   'A thermochromic colour change — ZnO changes colour reversibly with temperature',
   'The composition does not change, only the colour.',
   'ZnO is white at room temperature but turns yellow on heating because thermal excitation changes the optical properties of the crystal; on cooling it reverts to white — a physical (thermochromic) change, not a chemical decomposition.'],

  ['g9s-c4-v011', 'metals_with_oxygen', 3,
   'Why is the combustion of magnesium used in photography and distress flares?',
   ['It produces an extremely bright white light because the reaction is highly exothermic and emits visible radiation',
    'It burns slowly and steadily, giving a controlled source of heat',
    'It produces a coloured flame (green) that can be seen at great distances',
    'It is the only metal that burns in air without producing any smoke'],
   'It produces an extremely bright white light because the reaction is highly exothermic and emits visible radiation',
   'The brightness comes from the energy released.',
   '2Mg + O₂ → 2MgO releases a large amount of energy as light and heat; the temperature is high enough to produce brilliant white emission in the visible spectrum.'],

  ['g9s-c4-v012', 'metals_with_oxygen', 2,
   'Which product is formed when lead burns in oxygen?',
   ['Lead(II) oxide (PbO), a yellow solid', 'Lead carbonate (PbCO₃)', 'Lead sulfate (PbSO₄)', 'Lead dioxide (PbO₂), a dark brown solid'],
   'Lead(II) oxide (PbO), a yellow solid',
   'Lead is below iron in the reactivity series and forms a simple oxide.',
   '2Pb + O₂ → 2PbO. Lead(II) oxide is a yellow solid (also known as litharge, historically used in pigments).'],

  ['g9s-c4-v013', 'metals_with_oxygen', 1,
   'What is the general rule for the vigour of the reaction of a metal with oxygen?',
   ['The more reactive the metal, the more vigorous its reaction with oxygen',
    'The less reactive the metal, the more vigorous its reaction with oxygen',
    'All metals react with oxygen at the same rate',
    'Only metals below iron in the reactivity series react with oxygen'],
   'The more reactive the metal, the more vigorous its reaction with oxygen',
   'Reactivity with oxygen is a direct measure of how reactive the metal is.',
   'Reactivity with oxygen is one of the key criteria used to rank metals in the reactivity series; sodium burns violently, iron rusts slowly, and gold does not react at all.'],

  ['g9s-c4-v014', 'metals_with_oxygen', 3,
   'Tin is used to coat steel cans (food tins). If the tin coating is scratched, which metal corrodes first?',
   ['The iron (steel) corrodes rapidly because tin is below iron in the reactivity series, offering no cathodic protection',
    'The tin corrodes first because it is on the outside and exposed to more oxygen',
    'Neither corrodes because tin\'s oxide layer protects the whole surface',
    'Both corrode at the same rate once the tin is scratched'],
   'The iron (steel) corrodes rapidly because tin is below iron in the reactivity series, offering no cathodic protection',
   'Think about which metal is more reactive when they are connected.',
   'Tin is less reactive than iron; when the coating is scratched, the more reactive iron acts as the anode in an electrochemical cell with the less reactive tin and corrodes preferentially — opposite to galvanising with zinc.'],

  // ── metals_with_acids ────────────────────────────────────────────────────
  ['g9s-c4-v015', 'metals_with_acids', 1,
   'What gas is produced when a metal reacts with a dilute acid?',
   ['Hydrogen', 'Oxygen', 'Carbon dioxide', 'Chlorine'],
   'Hydrogen',
   'Test for it with a lighted splint.',
   'Metal + dilute acid → salt + hydrogen. The hydrogen test: hold a lighted splint to the mouth of the tube — a "squeaky pop" confirms H₂.'],

  ['g9s-c4-v016', 'metals_with_acids', 1,
   'Which salt is produced when iron reacts with hydrochloric acid?',
   ['Iron(II) chloride', 'Iron(III) chloride', 'Iron sulfate', 'Iron carbonate'],
   'Iron(II) chloride',
   'Metal + HCl → metal chloride + H₂.',
   'Fe + 2HCl → FeCl₂ + H₂. With dilute HCl, iron forms iron(II) chloride because the Fe²⁺ ion is the stable product; concentrated acid can give Fe³⁺.'],

  ['g9s-c4-v017', 'metals_with_acids', 2,
   'Why does gold not react with dilute sulfuric acid?',
   ['Gold is below hydrogen in the reactivity series and cannot displace hydrogen from acids',
    'Gold dissolves too slowly in all liquids to react measurably',
    'Gold reacts only with concentrated acids, not dilute ones',
    'Gold reacts with water in the acid instead of the acid itself'],
   'Gold is below hydrogen in the reactivity series and cannot displace hydrogen from acids',
   'Only metals above hydrogen in the reactivity series react with dilute acids.',
   'Only metals more reactive than hydrogen can displace H⁺ from acids; gold (and platinum, copper, silver) are all below hydrogen in the series and do not react with dilute acids.'],

  ['g9s-c4-v018', 'metals_with_acids', 2,
   'Which observation shows that zinc reacts more vigorously with dilute sulfuric acid than iron?',
   ['Zinc produces bubbles of hydrogen more rapidly than iron under the same conditions',
    'Zinc forms a bright blue solution whereas iron forms a pale green one',
    'Zinc dissolves at the same rate as iron but produces a different gas',
    'Iron produces more bubbles than zinc but the total yield of hydrogen is the same'],
   'Zinc produces bubbles of hydrogen more rapidly than iron under the same conditions',
   'Rate of reaction is shown by rate of gas production.',
   'Zinc is above iron in the reactivity series; it reacts more vigorously, so the rate of hydrogen production (bubbling) is faster.'],

  ['g9s-c4-v019', 'metals_with_acids', 2,
   'What would you observe if you added calcium to dilute hydrochloric acid?',
   ['Very vigorous effervescence (hydrogen produced rapidly); the calcium disappears; the solution warms up',
    'The calcium sinks to the bottom and slowly dissolves with no visible gas',
    'A green gas is produced and the calcium melts',
    'Nothing — calcium does not react with acids'],
   'Very vigorous effervescence (hydrogen produced rapidly); the calcium disappears; the solution warms up',
   'Calcium is a reactive metal high in the reactivity series.',
   'Ca + 2HCl → CaCl₂ + H₂. Calcium is highly reactive, so the reaction is vigorous; the heat produced is measurable and the hydrogen produced rapidly.'],

  ['g9s-c4-v020', 'metals_with_acids', 3,
   'A student adds the same mass of three metals to equal volumes of the same concentration of hydrochloric acid: Mg, Fe, Cu. Rank them by rate of hydrogen production, fastest first.',
   ['Mg > Fe > Cu (copper produces none)',
    'Fe > Mg > Cu',
    'Cu > Fe > Mg',
    'All three produce the same amount at the same rate'],
   'Mg > Fe > Cu (copper produces none)',
   'Use the reactivity series to predict order.',
   'Mg is above Fe which is above H₂ in the reactivity series; Cu is below H₂. So Mg reacts fastest, Fe more slowly, and Cu not at all.'],

  ['g9s-c4-v021', 'metals_with_acids', 2,
   'Which salt is formed when zinc reacts with sulfuric acid?',
   ['Zinc sulfate', 'Zinc chloride', 'Zinc carbonate', 'Zinc oxide'],
   'Zinc sulfate',
   'The salt takes the metal and the anion of the acid.',
   'Zn + H₂SO₄ → ZnSO₄ + H₂. The salt is zinc sulfate, formed from zinc ions and sulfate ions from the acid.'],

  ['g9s-c4-v022', 'metals_with_acids', 3,
   'A student adds excess zinc to dilute sulfuric acid. What does "excess zinc" ensure?',
   ['All the acid is consumed, so maximum hydrogen yield is obtained',
    'The reaction continues indefinitely until all the zinc dissolves',
    'The concentration of the zinc sulfate solution is doubled',
    'The hydrogen produced is twice as pure as with the stoichiometric amount'],
   'All the acid is consumed, so maximum hydrogen yield is obtained',
   'Excess of one reactant ensures the other (the limiting reactant) is completely used up.',
   'Using excess zinc ensures the acid (the limiting reagent) is fully consumed; this maximises H₂ yield. Some zinc remains unreacted at the end.'],

  ['g9s-c4-v023', 'metals_with_acids', 2,
   'Why does iron react faster with concentrated hydrochloric acid than with dilute acid?',
   ['Higher concentration means more H⁺ ions per unit volume, increasing the collision frequency',
    'Concentrated acid is hotter, providing more activation energy',
    'Concentrated acid changes the type of salt formed, which is more soluble',
    'The iron dissolves better in concentrated acid because the oxide layer is thicker'],
   'Higher concentration means more H⁺ ions per unit volume, increasing the collision frequency',
   'Rate depends on the concentration of the reacting species.',
   'Reaction rate increases with concentration because there are more H⁺ ions in the same volume, leading to more frequent collisions between H⁺ and the metal surface.'],

  ['g9s-c4-v024', 'metals_with_acids', 3,
   'The graph of volume of hydrogen against time for Mg + HCl shows a steep initial gradient that levels off. What does the levelling off indicate?',
   ['The acid has been completely consumed and the reaction has stopped',
    'The magnesium has run out and there is excess acid remaining',
    'The hydrogen has reacted with oxygen in the air above the reaction',
    'The temperature has dropped and the reaction has slowed permanently'],
   'The acid has been completely consumed and the reaction has stopped',
   'The reaction stops when one of the reactants is used up.',
   'The gradient (rate) falls as acid is consumed; once all the acid has reacted the curve is flat — total H₂ evolved equals the theoretical maximum for the amount of acid used (assuming Mg is in excess).'],

  ['g9s-c4-v025', 'metals_with_acids', 2,
   'Lead reacts only very slowly with dilute sulfuric acid even though it is above hydrogen in the reactivity series. Why?',
   ['Lead sulfate (PbSO₄) is insoluble and coats the lead surface, blocking further reaction',
    'Lead is actually below hydrogen in the reactivity series and cannot displace H⁺',
    'Sulfuric acid is too concentrated for lead to dissolve in it',
    'The lead surface has no oxide layer to dissolve before the metal can react'],
   'Lead sulfate (PbSO₄) is insoluble and coats the lead surface, blocking further reaction',
   'The product of the reaction is the key here.',
   'PbSO₄ is almost insoluble; it coats the lead surface immediately, preventing further contact between the acid and the metal — a classic example of a passivating insoluble product.'],

  ['g9s-c4-v026', 'metals_with_acids', 1,
   'Which test confirms that the gas produced in a metal–acid reaction is hydrogen?',
   ['A lighted splint held near the gas causes a squeaky pop as it ignites',
    'The gas turns lime water milky',
    'The gas relights a glowing splint',
    'The gas turns damp red litmus paper blue'],
   'A lighted splint held near the gas causes a squeaky pop as it ignites',
   'Hydrogen is flammable — it burns with a small explosion.',
   'Hydrogen ignites with a distinctive squeaky pop when a lighted splint is applied; CO₂ turns lime water milky; O₂ relights a glowing splint; NH₃ turns litmus blue.'],

  ['g9s-c4-v027', 'metals_with_acids', 3,
   'Why does copper dissolve in concentrated nitric acid but not in dilute hydrochloric acid?',
   ['Concentrated nitric acid is an oxidising acid; it oxidises copper even though Cu is below H in the reactivity series',
    'Copper reacts with the concentrated nitrogen in the acid, not the hydrogen',
    'Dilute HCl dissolves copper oxide but not the copper metal itself',
    'Copper is above hydrogen in the reactivity series and displaces it only from hot concentrated acid'],
   'Concentrated nitric acid is an oxidising acid; it oxidises copper even though Cu is below H in the reactivity series',
   'Some acids react by oxidising rather than by releasing H₂.',
   'Cu is below H₂ in the reactivity series and does not displace H⁺ from non-oxidising acids; but HNO₃ (concentrated) uses NO₃⁻ as the oxidising agent, dissolving Cu to form Cu(NO₃)₂ and releasing brown NO₂ gas.'],

  ['g9s-c4-v028', 'metals_with_acids', 2,
   'Magnesium reacts with dilute nitric acid to form magnesium nitrate and hydrogen. Which statement about this reaction is true?',
   ['Mg + 2HNO₃ → Mg(NO₃)₂ + H₂ — the reaction follows the same pattern as with other dilute acids',
    'No hydrogen is produced because nitric acid always produces nitrogen dioxide',
    'Magnesium dissolves in nitric acid to give magnesium oxide and water',
    'Dilute nitric acid is too weak to react with magnesium'],
   'Mg + 2HNO₃ → Mg(NO₃)₂ + H₂ — the reaction follows the same pattern as with other dilute acids',
   'Dilute nitric acid behaves as a typical acid with very reactive metals.',
   'Very reactive metals (Mg, Zn) do release H₂ with dilute HNO₃; with less reactive metals or with concentrated HNO₃, nitrogen oxides are formed instead. Mg reacts vigorously with dilute HNO₃ to give H₂.'],

  // ── metals_with_water_steam ───────────────────────────────────────────────
  ['g9s-c4-v029', 'metals_with_water_steam', 1,
   'Which of these metals reacts vigorously with cold water?',
   ['Potassium', 'Iron', 'Copper', 'Zinc'],
   'Potassium',
   'Only the most reactive metals react with cold water.',
   'Potassium reacts explosively with cold water: 2K + 2H₂O → 2KOH + H₂. Sodium and calcium also react with cold water, but iron, copper and zinc do not.'],

  ['g9s-c4-v030', 'metals_with_water_steam', 2,
   'Sodium is added to water. The solution formed turns universal indicator purple. What does this show about the solution?',
   ['It is strongly alkaline — sodium hydroxide (NaOH) has dissolved in the water',
    'It is strongly acidic — the sodium released acid as it reacted',
    'It is neutral — the purple is due to dissolved sodium metal',
    'It is slightly acidic — sodium dissolves to form a weak acid'],
   'It is strongly alkaline — sodium hydroxide (NaOH) has dissolved in the water',
   'The product of sodium + water is a metal hydroxide.',
   '2Na + 2H₂O → 2NaOH + H₂. NaOH is a strong alkali; purple on universal indicator indicates high pH (strongly alkaline).'],

  ['g9s-c4-v031', 'metals_with_water_steam', 2,
   'Why does zinc react with steam but not with liquid cold water?',
   ['Steam provides enough energy to overcome the activation energy for the reaction with zinc',
    'Zinc is less reactive than hydrogen so it cannot react with any water',
    'Liquid water freezes around the zinc and stops the reaction',
    'Zinc reacts only with the oxygen dissolved in liquid water, not with the H₂O molecules'],
   'Steam provides enough energy to overcome the activation energy for the reaction with zinc',
   'Temperature (energy) determines whether a reaction proceeds at a useful rate.',
   'Zinc is in the middle of the reactivity series; it requires the higher temperature of steam to provide sufficient activation energy for the reaction: Zn + H₂O(steam) → ZnO + H₂.'],

  ['g9s-c4-v032', 'metals_with_water_steam', 1,
   'What products are formed when calcium reacts with water?',
   ['Calcium hydroxide and hydrogen', 'Calcium oxide and hydrogen', 'Calcium carbonate and hydrogen', 'Calcium chloride and oxygen'],
   'Calcium hydroxide and hydrogen',
   'Reactive metal + water → metal hydroxide + hydrogen.',
   'Ca + 2H₂O → Ca(OH)₂ + H₂. Calcium reacts steadily with cold water to form slightly soluble calcium hydroxide (limewater) and hydrogen gas.'],

  ['g9s-c4-v033', 'metals_with_water_steam', 2,
   'Which observation distinguishes the reaction of potassium with water from that of sodium with water?',
   ['Potassium ignites the hydrogen produced, giving a lilac-coloured flame, while sodium\'s flame is orange',
    'Potassium produces oxygen instead of hydrogen while sodium produces hydrogen',
    'Potassium sinks to the bottom of the water while sodium floats',
    'Sodium dissolves completely in cold water while potassium leaves an insoluble residue'],
   'Potassium ignites the hydrogen produced, giving a lilac-coloured flame, while sodium\'s flame is orange',
   'The greater reactivity of K provides more energy.',
   'K is more reactive than Na; the extra heat from the K reaction ignites the H₂ immediately, producing a lilac flame (characteristic of K); with Na, the hydrogen is released but does not usually ignite at room temperature.'],

  ['g9s-c4-v034', 'metals_with_water_steam', 2,
   'When iron reacts with steam, the product is Fe₃O₄. What is the common name of this compound?',
   ['Iron(II,III) oxide (magnetite)', 'Iron(III) oxide (haematite)', 'Iron(II) oxide', 'Iron hydroxide'],
   'Iron(II,III) oxide (magnetite)',
   'Steam reacts with iron at red heat to give a mixed oxide.',
   '3Fe + 4H₂O(steam) → Fe₃O₄ + 4H₂. Fe₃O₄ is a mixed oxide of Fe²⁺ and Fe³⁺, commonly called magnetite; haematite (Fe₂O₃) is the oxide in rust.'],

  ['g9s-c4-v035', 'metals_with_water_steam', 3,
   'A student passes steam over heated iron and collects the gas. She tests the gas with a lighted splint and gets a squeaky pop. What does this confirm, and why is the reaction reversible?',
   ['Hydrogen is produced; the reaction is reversible because the products (Fe₃O₄ and H₂) can react with each other at the same temperature',
    'Oxygen is produced; the iron is acting as a catalyst splitting water',
    'Steam itself ignites in the test; the reaction is not reversible',
    'Hydrogen is produced; the reaction is irreversible because Fe₃O₄ is a very stable compound'],
   'Hydrogen is produced; the reaction is reversible because the products (Fe₃O₄ and H₂) can react with each other at the same temperature',
   'The squeaky pop means H₂; think about equilibrium in a closed tube.',
   'The squeaky pop confirms H₂; the reaction 3Fe + 4H₂O ⇌ Fe₃O₄ + 4H₂ is reversible — this industrial fact is used in the steam-iron process for hydrogen production, where steam is continually removed to drive the equilibrium right.'],

  ['g9s-c4-v036', 'metals_with_water_steam', 2,
   'Which of these metals does NOT react with steam even at very high temperatures?',
   ['Copper', 'Zinc', 'Iron', 'Aluminium'],
   'Copper',
   'Use the reactivity series — only metals above copper react with steam.',
   'Copper is below hydrogen in the reactivity series; it cannot displace H₂ from steam or water. Zinc, iron and aluminium are all above hydrogen and can react with steam.'],

  ['g9s-c4-v037', 'metals_with_water_steam', 3,
   'Why is the reaction of very reactive metals like sodium with water described as "dangerous" in a laboratory context?',
   ['The hydrogen produced can be ignited by the heat of the exothermic reaction, and the alkali produced can cause severe chemical burns',
    'The metal dissolves too quickly, making the solution acidic and corrosive to laboratory bench surfaces',
    'The reaction releases a toxic gas (nitrogen dioxide) that must be captured in a fume cupboard',
    'The sodium liquefies and spatters, but this is only a burn hazard if the temperature exceeds 200 °C'],
   'The hydrogen produced can be ignited by the heat of the exothermic reaction, and the alkali produced can cause severe chemical burns',
   'Two hazards: the flammable gas and the corrosive product.',
   'Na + H₂O → NaOH + H₂. The reaction is highly exothermic; H₂ can ignite; molten Na can spatter; and NaOH is corrosive (pH > 13). Potassium is even more dangerous as the H₂ always ignites.'],

  ['g9s-c4-v038', 'metals_with_water_steam', 2,
   'A student compares the reactions of small pieces of Li, Na and K with water in a class demonstration. What trend does she observe?',
   ['Li reacts gently, Na more vigorously, K most vigorously — reactivity increases down Group 1',
    'K reacts most gently because it is heavier and denser than the others',
    'All three react identically because they are all alkali metals',
    'Li reacts most violently because it is the smallest and has the most concentrated charge'],
   'Li reacts gently, Na more vigorously, K most vigorously — reactivity increases down Group 1',
   'Reactivity increases going down Group 1 of the periodic table.',
   'Going down Group 1, the outer electron is farther from the nucleus and more easily lost, making each successive metal more reactive with water and all other reagents.'],

  ['g9s-c4-v039', 'metals_with_water_steam', 3,
   'Magnesium reacts very slowly with cold water but rapidly with steam. What does this show about activation energy?',
   ['The reaction of Mg with water has a high activation energy that steam (higher temperature) provides, while cold water does not',
    'Steam contains more water molecules per unit volume, giving more collisions',
    'Steam is purer water than cold water and purity affects the reaction rate',
    'Magnesium reacts with the oxygen in steam, not with the water molecules'],
   'The reaction of Mg with water has a high activation energy that steam (higher temperature) provides, while cold water does not',
   'High temperature means more particles have energy above the activation energy.',
   'At the higher temperature of steam, a much larger proportion of H₂O molecules have kinetic energy exceeding the activation energy for reacting with Mg; at room temperature, too few molecules overcome the barrier for the reaction to be observable.'],

  ['g9s-c4-v040', 'metals_with_water_steam', 1,
   'Which product of the reaction between potassium and water makes the resulting solution alkaline?',
   ['Potassium hydroxide (KOH)', 'Potassium oxide (K₂O)', 'Hydrogen gas', 'Potassium carbonate (K₂CO₃)'],
   'Potassium hydroxide (KOH)',
   'Hydroxides of Group 1 metals are strong bases.',
   '2K + 2H₂O → 2KOH + H₂. KOH is a strong alkali that fully dissociates in water, giving a high concentration of OH⁻ ions and a high pH.'],

  ['g9s-c4-v041', 'metals_with_water_steam', 2,
   'Aluminium is above zinc in the reactivity series, yet powdered aluminium reacts less vigorously than zinc with steam at first. Why?',
   ['A thin layer of aluminium oxide on the surface prevents immediate reaction; once breached the reaction is fast',
    'Aluminium is actually below zinc in the reactivity series for steam reactions',
    'Aluminium reacts with the nitrogen in steam rather than the oxygen in water',
    'Aluminium has a much higher melting point than zinc so the steam cannot heat it enough'],
   'A thin layer of aluminium oxide on the surface prevents immediate reaction; once breached the reaction is fast',
   'Think about the oxide layer on aluminium.',
   'The protective Al₂O₃ coating on aluminium surface slows initial reaction; once the surface is activated (e.g., in strongly acidic or alkaline conditions), aluminium reacts vigorously consistent with its position above zinc in the reactivity series.'],

  ['g9s-c4-v042', 'metals_with_water_steam', 3,
   'In which situation would you use the reaction of a metal with steam to produce hydrogen industrially?',
   ['The steam-iron process: passing steam over iron at ~750 °C, then using hydrogen to make ammonia',
    'Electrolysis of water: passing steam through an electric arc to split it',
    'The Haber process: reacting steam with nitrogen at 450 °C to give hydrogen and ammonia together',
    'Thermal decomposition: heating steam to above 2500 °C until it decomposes into H₂ and O₂'],
   'The steam-iron process: passing steam over iron at ~750 °C, then using hydrogen to make ammonia',
   'This was a historical industrial process for making hydrogen.',
   'The steam-iron (Messerschmitt) process: 3Fe + 4H₂O → Fe₃O₄ + 4H₂ at ~750 °C. The Fe₃O₄ is reduced back with more steam or with coal gas. It was used before steam reforming became dominant.'],

  // ── reactivity_series ─────────────────────────────────────────────────────
  ['g9s-c4-v043', 'reactivity_series', 1,
   'In the standard reactivity series, which metal is the MOST reactive?',
   ['Potassium (K)', 'Sodium (Na)', 'Magnesium (Mg)', 'Iron (Fe)'],
   'Potassium (K)',
   'The most reactive metal is at the top of the series.',
   'The reactivity series (most to least reactive) starts: K > Na > Li > Ca > Mg > Al > Zn > Fe > Sn > Pb > H > Cu > Hg > Ag > Au > Pt.'],

  ['g9s-c4-v044', 'reactivity_series', 1,
   'Where does hydrogen appear in the reactivity series?',
   ['Between lead and copper (below most common metals)',
    'At the top, above potassium',
    'Between magnesium and aluminium',
    'At the bottom, below platinum'],
   'Between lead and copper (below most common metals)',
   'Its position explains which metals can displace hydrogen from acids.',
   'Hydrogen is placed in the reactivity series between lead and copper; metals above hydrogen can displace it from acids, metals below (Cu, Ag, Au) cannot.'],

  ['g9s-c4-v045', 'reactivity_series', 2,
   'A student adds four metals — Cu, Zn, Ag, Mg — to separate test tubes of dilute sulfuric acid. Which two produce bubbles?',
   ['Zn and Mg (both above H in the reactivity series)',
    'Cu and Ag (as the most common metals)',
    'All four react with dilute sulfuric acid',
    'Only Mg reacts; Zn does not react with sulfuric acid'],
   'Zn and Mg (both above H in the reactivity series)',
   'Only metals above hydrogen in the reactivity series displace H₂ from acids.',
   'Mg and Zn are above H in the reactivity series; Cu and Ag are below it. Only Mg and Zn displace H⁺ from H₂SO₄ to give H₂.'],

  ['g9s-c4-v046', 'reactivity_series', 2,
   'Which observation is used to place metals in the reactivity series using displacement reactions?',
   ['Whether a metal displaces another metal from a solution of its salt',
    'Whether a metal floats on water',
    'Whether a metal has a high or low melting point',
    'Whether a metal reacts with oxygen more quickly than it dissolves in acid'],
   'Whether a metal displaces another metal from a solution of its salt',
   'A more reactive metal pushes a less reactive one out of its compound.',
   'If metal A displaces metal B from a solution of B\'s salt (A + BSO₄ → ASO₄ + B), then A is more reactive than B; this displacement experiment is a key method for ranking metals.'],

  ['g9s-c4-v047', 'reactivity_series', 2,
   'A piece of copper is placed in silver nitrate solution. A silvery deposit forms on the copper and the solution turns blue. What does this show?',
   ['Copper is more reactive than silver and displaces it from the solution',
    'Silver is more reactive and has displaced copper from the solid',
    'Copper and silver react to form a copper-silver alloy',
    'The blue colour is silver dissolving, making the solution blue'],
   'Copper is more reactive than silver and displaces it from the solution',
   'The more reactive metal displaces the less reactive one.',
   'Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag. Copper displaces silver (Ag) forming a silvery deposit; Cu²⁺ ions enter solution, turning it blue. This confirms Cu > Ag in reactivity.'],

  ['g9s-c4-v048', 'reactivity_series', 3,
   'A student performs four displacement reactions and records whether a reaction occurs (✓) or not (✗): Fe in CuSO₄ (✓), Cu in FeSO₄ (✗), Zn in FeSO₄ (✓), Fe in ZnSO₄ (✗). What is the order of reactivity, most reactive first?',
   ['Zn > Fe > Cu', 'Fe > Zn > Cu', 'Cu > Fe > Zn', 'Zn > Cu > Fe'],
   'Zn > Fe > Cu',
   'Which metal can displace which?',
   'Fe displaces Cu (Fe > Cu); Cu cannot displace Fe (Cu < Fe); Zn displaces Fe (Zn > Fe); Fe cannot displace Zn (Fe < Zn). Therefore Zn > Fe > Cu.'],

  ['g9s-c4-v049', 'reactivity_series', 3,
   'Why is sodium stored under oil rather than in water?',
   ['Sodium is so reactive it reacts vigorously and dangerously with water, but oil does not react with it',
    'Sodium dissolves in water very slowly and the oil prevents this',
    'Oil makes sodium more reactive, which is useful for starting the reaction when needed',
    'Water would rust the sodium; oil prevents oxidation of the metal surface'],
   'Sodium is so reactive it reacts vigorously and dangerously with water, but oil does not react with it',
   'Storage method reflects how reactive the metal is with common substances.',
   'Na + H₂O: the reaction is highly exothermic and can start fires; oil is non-reactive and provides an inert barrier. Reactivity series position (very high for Na) determines storage requirements.'],

  ['g9s-c4-v050', 'reactivity_series', 2,
   'Which of the following statements about the reactivity series is correct?',
   ['Metals higher in the series are more readily oxidised (lose electrons more easily)',
    'Metals lower in the series are easier to extract from their ores by heating alone',
    'Both A and B are correct',
    'Metals lower in the series are more reactive in all chemical reactions'],
   'Both A and B are correct',
   'The reactivity series tells us about two things simultaneously.',
   'Both statements are true: (A) higher metals lose electrons more readily (more reactive); (B) lower metals (Cu, Hg) can be extracted just by heating their oxides because the bond to oxygen is weak — e.g. 2HgO → 2Hg + O₂.'],

  ['g9s-c4-v051', 'reactivity_series', 1,
   'Why is platinum used in jewellery?',
   ['It is very unreactive and resists tarnishing, acids and corrosion',
    'It is the most reactive metal and therefore the purest and brightest',
    'It reacts with oxygen to form a thin protective layer that gives it a shine',
    'It is the hardest of all metals, making it the most durable'],
   'It is very unreactive and resists tarnishing, acids and corrosion',
   'Its position at the bottom of the reactivity series explains its use.',
   'Platinum is at the bottom of the reactivity series (along with gold) — it does not react with oxygen, water or dilute acids, making it ideal for jewellery and catalytic converters.'],

  ['g9s-c4-v052', 'reactivity_series', 3,
   'Iron can be extracted from iron ore (Fe₂O₃) by heating with carbon monoxide. Why can potassium not be extracted the same way?',
   ['Potassium is more reactive than carbon and carbon cannot displace it from its compounds',
    'Potassium ore does not contain any oxygen and carbon monoxide has no effect on it',
    'Carbon monoxide is toxic and would contaminate the potassium',
    'Potassium melts at too low a temperature for the reaction with CO to work'],
   'Potassium is more reactive than carbon and carbon cannot displace it from its compounds',
   'Carbon/CO can only displace metals that are less reactive than carbon.',
   'In the reactivity series, carbon sits between aluminium and zinc; it can reduce metals below it (Zn, Fe, Pb, Cu) but cannot reduce metals above it (K, Na, Ca, Mg, Al). Potassium must be extracted by electrolysis.'],

  ['g9s-c4-v053', 'reactivity_series', 2,
   'The reactivity series is sometimes called the electrochemical series. Why?',
   ['It reflects how easily each metal loses electrons (is oxidised), which also determines standard electrode potential',
    'It was determined entirely by electrical experiments in which metals were used as electrodes',
    'Each position in the series corresponds to the electrical resistance of the metal',
    'Reactivity determines how well a metal conducts electricity'],
   'It reflects how easily each metal loses electrons (is oxidised), which also determines standard electrode potential',
   'Reactivity = tendency to lose electrons = electrochemical potential.',
   'The more reactive a metal, the more readily it loses electrons (is oxidised); this is measured as a more negative standard electrode potential. The two series (reactivity and electrochemical) order metals in the same sequence.'],

  ['g9s-c4-v054', 'reactivity_series', 3,
   'Zinc is used to galvanise steel (iron). Why does zinc protect iron even when the zinc coating is scratched?',
   ['Zinc is more reactive than iron; when both are exposed, Zn corrodes preferentially, protecting Fe',
    'Zinc is less reactive than iron; it acts as a physical barrier only and so scratching destroys the protection',
    'Zinc and iron react together to form an alloy that is more resistant to corrosion than either alone',
    'Zinc forms a thick oxide layer that seals the scratch and prevents air reaching the iron'],
   'Zinc is more reactive than iron; when both are exposed, Zn corrodes preferentially, protecting Fe',
   'The more reactive metal sacrifices itself.',
   'Zn > Fe in the reactivity series; where both are exposed, Zn is oxidised (sacrificed) in preference to Fe. This sacrificial protection continues even through a scratch — unlike tin coating, which accelerates iron corrosion once scratched.'],

  ['g9s-c4-v055', 'reactivity_series', 2,
   'Which of these is the correct order of metals from LEAST reactive to MOST reactive?',
   ['Au < Cu < Fe < Zn < Na < K', 'K < Na < Zn < Fe < Cu < Au', 'Fe < Zn < Cu < Na < K < Au', 'Na < K < Zn < Fe < Au < Cu'],
   'Au < Cu < Fe < Zn < Na < K',
   'Learn the series from the bottom up: Au, Ag, Hg, Cu, Pb, Sn, Fe, Zn, Al, Mg, Ca, Na, K.',
   'The standard reactivity series (least to most reactive): Au, Ag, Hg, Cu, Pb, Sn, Fe, Zn, Al, Mg, Ca, Na, K. So Au < Cu < Fe < Zn < Na < K.'],

  ['g9s-c4-v056', 'reactivity_series', 3,
   'A student performs a thermite reaction: aluminium powder reacts with iron(III) oxide to give aluminium oxide and iron. What does this show?',
   ['Aluminium is more reactive than iron and can displace it from its oxide',
    'Iron is more reactive than aluminium and displaces aluminium from its oxide',
    'Both metals are equally reactive; the reaction is driven by the heat applied',
    'The reaction works only because Fe₂O₃ is soluble and aluminium is not'],
   'Aluminium is more reactive than iron and can displace it from its oxide',
   'The more reactive metal displaces the less reactive metal even from its oxide.',
   '2Al + Fe₂O₃ → Al₂O₃ + 2Fe. Al is above Fe in the reactivity series; it displaces Fe from Fe₂O₃ in a highly exothermic reaction (thermite) used for welding railway tracks.'],

  ['g9s-c4-v057', 'reactivity_series', 2,
   'Which metal is extracted by electrolysis because it is too reactive to be reduced by carbon or carbon monoxide?',
   ['Aluminium', 'Iron', 'Zinc', 'Tin'],
   'Aluminium',
   'Al is above carbon in the reactivity series.',
   'Aluminium is above carbon in the reactivity series; carbon cannot reduce Al₂O₃. Al is extracted industrially by electrolysis of molten aluminium oxide (the Hall-Héroult process).'],

  // ── predicting_reactions ──────────────────────────────────────────────────
  ['g9s-c4-v058', 'predicting_reactions', 1,
   'Will copper react with iron(II) sulfate solution? Explain why.',
   ['No — copper is less reactive than iron and cannot displace it from solution',
    'Yes — copper is more reactive than iron and displaces it',
    'Yes — copper always reacts with sulfate solutions regardless of reactivity',
    'No — copper only reacts with nitrate solutions'],
   'No — copper is less reactive than iron and cannot displace it from solution',
   'A less reactive metal cannot displace a more reactive one.',
   'Cu < Fe in the reactivity series; a metal can only displace a less reactive metal from solution. Cu cannot displace Fe²⁺, so no reaction occurs.'],

  ['g9s-c4-v059', 'predicting_reactions', 1,
   'Will zinc react with copper(II) sulfate solution?',
   ['Yes — zinc is more reactive than copper and displaces it from solution',
    'No — zinc cannot react with sulfate solutions',
    'No — copper is more reactive than zinc',
    'Yes — but only if the solution is heated'],
   'Yes — zinc is more reactive than copper and displaces it from solution',
   'Zn is above Cu in the reactivity series.',
   'Zn + CuSO₄ → ZnSO₄ + Cu. Zinc displaces copper, depositing a reddish-brown layer of copper on the zinc surface and the blue colour of the copper solution fades.'],

  ['g9s-c4-v060', 'predicting_reactions', 2,
   'Which of these reactions will NOT occur?',
   ['Fe + MgSO₄ → FeSO₄ + Mg', 'Fe + CuSO₄ → FeSO₄ + Cu', 'Zn + CuSO₄ → ZnSO₄ + Cu', 'Mg + FeSO₄ → MgSO₄ + Fe'],
   'Fe + MgSO₄ → FeSO₄ + Mg',
   'Can Fe displace Mg? Use the reactivity series.',
   'Mg > Fe in the reactivity series; iron cannot displace magnesium from its salt solution. The other three reactions are all possible because a more reactive metal displaces a less reactive one.'],

  ['g9s-c4-v061', 'predicting_reactions', 2,
   'A student places an iron nail in copper sulfate solution. After 20 minutes, what does she observe?',
   ['A reddish-brown deposit forms on the nail and the blue solution becomes paler',
    'The nail dissolves completely and the solution turns green',
    'The solution turns orange and the nail remains shiny',
    'No change — iron and copper sulfate do not react'],
   'A reddish-brown deposit forms on the nail and the blue solution becomes paler',
   'Fe displaces Cu: the displaced copper deposits on the nail.',
   'Fe + CuSO₄ → FeSO₄ + Cu. Copper (reddish-brown) deposits on the iron nail; the blue Cu²⁺ solution becomes paler as Cu²⁺ is removed and replaced by pale green Fe²⁺.'],

  ['g9s-c4-v062', 'predicting_reactions', 3,
   'Metal X reacts with dilute acid but not with cold water; metal Y reacts with neither acid nor cold water; metal Z reacts with cold water and with dilute acid. Rank X, Y, Z in order of reactivity (most reactive first).',
   ['Z > X > Y', 'X > Z > Y', 'Y > X > Z', 'Z > Y > X'],
   'Z > X > Y',
   'Use the observations to place each in the reactivity series.',
   'Z reacts with cold water → above Ca level (or at least above Fe level that reacts with steam/acid). X reacts with acid but not cold water → between Mg and Cu (e.g. Zn, Fe level). Y does not react with acid → below H in the series (e.g. Cu, Ag). Order: Z > X > Y.'],

  ['g9s-c4-v063', 'predicting_reactions', 2,
   'Predict the product when lead is added to silver nitrate solution. (Pb > Ag in reactivity series)',
   ['Lead displaces silver: Pb + 2AgNO₃ → Pb(NO₃)₂ + 2Ag (silver crystals form)',
    'Silver displaces lead: Ag + Pb(NO₃)₂ → AgNO₃ + Pb',
    'No reaction occurs because lead and silver are adjacent in the reactivity series',
    'Lead reacts with the nitrate ion only, forming lead nitrate and releasing nitrogen gas'],
   'Lead displaces silver: Pb + 2AgNO₃ → Pb(NO₃)₂ + 2Ag (silver crystals form)',
   'The more reactive metal (Pb) displaces the less reactive (Ag).',
   'Pb > Ag in the reactivity series; Pb displaces Ag from AgNO₃ solution, forming silvery Ag crystals and dissolving to give colourless Pb(NO₃)₂.'],

  ['g9s-c4-v064', 'predicting_reactions', 3,
   'A strip of magnesium is placed in a solution containing both copper sulfate and zinc sulfate at the same concentration. Which metal, if any, deposits on the magnesium first?',
   ['Both Cu and Zn deposit, but Cu deposits faster because the greater the difference in reactivity, the faster the displacement',
    'Only Zn deposits because Mg is only just more reactive than Zn',
    'Neither deposits because Mg dissolves before any displacement can occur',
    'Only Cu deposits because Mg displaces only the least reactive metal present'],
   'Both Cu and Zn deposit, but Cu deposits faster because the greater the difference in reactivity, the faster the displacement',
   'Mg displaces both Zn and Cu; the one with greater reactivity difference displaces faster.',
   'Mg > Zn > Cu in reactivity. Mg displaces both; the Cu²⁺ displacement is more exothermic (greater ΔEᵣ) and proceeds faster. A mixed deposit of Zn and Cu would form, with Cu depositing more rapidly.'],

  ['g9s-c4-v065', 'predicting_reactions', 2,
   'Will iron(III) oxide be reduced by carbon monoxide at high temperature? Why?',
   ['Yes — CO (like C) can act as a reducing agent for metals below aluminium in the reactivity series',
    'No — only carbon (not CO) can reduce metal oxides',
    'No — iron is more reactive than carbon, so CO cannot reduce iron oxide',
    'Yes — CO reduces all metal oxides regardless of their position in the reactivity series'],
   'Yes — CO (like C) can act as a reducing agent for metals below aluminium in the reactivity series',
   'This is how iron is extracted in a blast furnace.',
   'Fe₂O₃ + 3CO → 2Fe + 3CO₂. Fe is below C in the reactivity series, so C (and CO, which is produced from C in the furnace) can reduce iron oxide — the basis of the blast furnace process.'],

  ['g9s-c4-v066', 'predicting_reactions', 3,
   'A student mixes silver powder with copper sulfate solution. She observes no reaction. Then she mixes copper powder with silver nitrate solution and observes a deposit. What can she conclude?',
   ['Copper is more reactive than silver: Cu > Ag in the reactivity series',
    'Silver is more reactive than copper: Ag > Cu',
    'Silver and copper have equal reactivity',
    'The observations are contradictory and do not allow a conclusion'],
   'Copper is more reactive than silver: Cu > Ag in the reactivity series',
   'Which metal displaces which?',
   'Ag cannot displace Cu from CuSO₄ → Ag < Cu. Cu displaces Ag from AgNO₃ → Cu > Ag. Both observations are consistent: Cu > Ag.'],

  ['g9s-c4-v067', 'predicting_reactions', 2,
   'Predict whether calcium will react with cold water, steam only, dilute acid only, or none of these.',
   ['Calcium reacts vigorously with cold water and also with dilute acid',
    'Calcium reacts with steam only and not with cold water',
    'Calcium reacts only with dilute acid and not with water',
    'Calcium does not react with water, steam or dilute acid'],
   'Calcium reacts vigorously with cold water and also with dilute acid',
   'Calcium is a reactive metal above magnesium in the reactivity series.',
   'Ca is high in the reactivity series (K > Na > Ca > Mg). Metals above Mg react with cold water; Ca + 2H₂O → Ca(OH)₂ + H₂. It also reacts with dilute acids.'],

  ['g9s-c4-v068', 'predicting_reactions', 3,
   'Tin is used inside food cans (tinplate). If exposed to an electrolyte (e.g. fruit juice), does the tin-iron couple corrode the iron or the tin first?',
   ['Iron corrodes first because tin is below iron in the reactivity series and acts as the cathode',
    'Tin corrodes first because it is on the outside and exposed to more electrolyte',
    'Neither corrodes because the tin seals the iron completely',
    'Both corrode at the same rate because they are in electrical contact'],
   'Iron corrodes first because tin is below iron in the reactivity series and acts as the cathode',
   'In a galvanic cell, the less reactive metal is the cathode (protected) and the more reactive is the anode (corroded).',
   'Sn < Fe is wrong — actually Sn is just below Fe in the reactivity series (Fe > Sn). When the tin coating is scratched, iron is the more reactive metal and acts as anode, corroding preferentially. This is why tinned cans should not be used once opened and scraped.'],

  ['g9s-c4-v069', 'predicting_reactions', 2,
   'Which of these statements correctly uses the reactivity series to predict behaviour?',
   ['A metal high in the reactivity series will react more vigorously with oxygen, water and acids',
    'A metal low in the reactivity series is harder to extract from its ore',
    'A metal in the middle of the series will not react with anything',
    'A metal high in the reactivity series is the most useful because it reacts with everything'],
   'A metal high in the reactivity series will react more vigorously with oxygen, water and acids',
   'Reactivity series = vigour of reactions.',
   'A high position in the reactivity series means the metal is more easily oxidised, reacting more vigorously with all common reagents; metals low in the series are less reactive but actually more useful in their elemental form (e.g. Au for jewellery).'],

  ['g9s-c4-v070', 'predicting_reactions', 3,
   'Why does calcium react with cold water but magnesium reacts only with steam?',
   ['Calcium is more reactive than magnesium; it has a lower activation energy for the reaction with water and reacts at room temperature',
    'Calcium reacts with the oxygen dissolved in cold water; magnesium reacts only with pure H₂O in steam',
    'Both metals react equally with cold water; the difference is in their product solubility',
    'Magnesium reacts with cold water at the same rate as calcium but produces a different gas'],
   'Calcium is more reactive than magnesium; it has a lower activation energy for the reaction with water and reacts at room temperature',
   'Position in reactivity series: Ca > Mg.',
   'Ca > Mg in reactivity; the reaction Ca + 2H₂O → Ca(OH)₂ + H₂ proceeds at room temperature because the lower activation energy is met by the thermal energy at 25 °C. Mg requires the higher temperature of steam to supply sufficient activation energy.'],

  ['g9s-c4-v071', 'predicting_reactions', 2,
   'An unknown metal M reacts slowly with dilute acid but not with cold water. Which position does it most likely occupy in the reactivity series?',
   ['Between hydrogen and calcium — it reacts with acid but not water, placing it in the middle (e.g. Zn, Fe, Sn level)',
    'Above potassium — it is so reactive it skips water reactions',
    'Below copper — it cannot react with dilute acid',
    'At exactly the position of hydrogen because it does not react with water'],
   'Between hydrogen and calcium — it reacts with acid but not water, placing it in the middle (e.g. Zn, Fe, Sn level)',
   'Divide the series by what each metal can and cannot react with.',
   'Metals that react with acid but not cold water are in the middle band: below Ca (which reacts with cold water) but above H (below which metals do not react with dilute acid). Examples: Mg (steam only), Zn, Fe, Sn, Pb.'],

  // ── equations_for_metals ──────────────────────────────────────────────────
  ['g9s-c4-v072', 'equations_for_metals', 1,
   'Write the balanced equation for magnesium burning in oxygen.',
   ['2Mg + O₂ → 2MgO', 'Mg + O₂ → MgO', 'Mg + O → MgO', '2Mg + O → Mg₂O'],
   '2Mg + O₂ → 2MgO',
   'Oxygen exists as diatomic O₂; balance Mg on both sides.',
   'One mole of O₂ provides 2 O atoms; 2 Mg atoms react to give 2 MgO: 2Mg + O₂ → 2MgO.'],

  ['g9s-c4-v073', 'equations_for_metals', 2,
   'Which equation correctly represents the reaction of sodium with water?',
   ['2Na + 2H₂O → 2NaOH + H₂', 'Na + H₂O → NaOH + H₂', '2Na + H₂O → Na₂O + H₂', 'Na + 2H₂O → Na(OH)₂ + H₂'],
   '2Na + 2H₂O → 2NaOH + H₂',
   'Balance Na, O and H carefully.',
   'Left: 2 Na, 4 H, 2 O. Right: 2 Na, 2 O, 2 H (in 2NaOH) + 2 H (in H₂) = 4 H total, 2 O. Balanced.'],

  ['g9s-c4-v074', 'equations_for_metals', 2,
   'Which is the correct balanced equation for the displacement of copper by iron from copper sulfate solution?',
   ['Fe + CuSO₄ → FeSO₄ + Cu', 'Fe + Cu(SO₄)₂ → Fe(SO₄)₂ + Cu', '2Fe + CuSO₄ → 2FeSO₄ + Cu', 'Fe₂ + CuSO₄ → Fe₂SO₄ + Cu'],
   'Fe + CuSO₄ → FeSO₄ + Cu',
   'Fe forms Fe²⁺, so one Fe replaces one Cu²⁺.',
   'Fe²⁺ (from Fe) replaces Cu²⁺ (from CuSO₄): one Fe replaces one Cu, giving FeSO₄. Atoms: 1 Fe, 1 Cu, 1 S, 4 O both sides. Balanced.'],

  ['g9s-c4-v075', 'equations_for_metals', 2,
   'Balance the equation for zinc reacting with hydrochloric acid: Zn + _HCl → ZnCl₂ + H₂',
   ['Zn + 2HCl → ZnCl₂ + H₂', 'Zn + HCl → ZnCl + H', 'Zn + 3HCl → ZnCl₂ + H₂ + HCl', '2Zn + HCl → Zn₂Cl + H₂'],
   'Zn + 2HCl → ZnCl₂ + H₂',
   'ZnCl₂ needs 2 Cl atoms from 2 HCl; those 2 H become H₂.',
   'Zn + 2HCl → ZnCl₂ + H₂. 2 HCl provide 2 Cl (for ZnCl₂) and 2 H (for H₂). Balanced: 1 Zn, 2 H, 2 Cl each side.'],

  ['g9s-c4-v076', 'equations_for_metals', 3,
   'Write the balanced equation for aluminium reacting with dilute sulfuric acid.',
   ['2Al + 3H₂SO₄ → Al₂(SO₄)₃ + 3H₂', 'Al + H₂SO₄ → AlSO₄ + H₂', '2Al + H₂SO₄ → Al₂SO₄ + H₂', 'Al + 3H₂SO₄ → Al(SO₄)₃ + H₂'],
   '2Al + 3H₂SO₄ → Al₂(SO₄)₃ + 3H₂',
   'Al³⁺ reacts with SO₄²⁻; find the formula of aluminium sulfate first.',
   'Al³⁺ and SO₄²⁻ give Al₂(SO₄)₃. 2 Al react with 3 H₂SO₄: left 4 H, right 3H₂ = 6H. Wait — 2Al + 3H₂SO₄ → Al₂(SO₄)₃ + 3H₂: left 6H, right 6H. Left: 2Al, 3S, 12O; right: 2Al, 3S, 12O. Balanced.'],

  ['g9s-c4-v077', 'equations_for_metals', 2,
   'What is the balanced equation for calcium reacting with water?',
   ['Ca + 2H₂O → Ca(OH)₂ + H₂', 'Ca + H₂O → CaO + H₂', '2Ca + 2H₂O → 2CaO + 2H₂', 'Ca + H₂O → Ca(OH)₂'],
   'Ca + 2H₂O → Ca(OH)₂ + H₂',
   'Ca forms Ca²⁺, so Ca(OH)₂ needs 2 OH groups from 2 H₂O.',
   'Left: 1 Ca, 4 H, 2 O. Right: 1 Ca, 2 OH (2 O, 2 H) + H₂ (2 H) = 4 H, 2 O. Balanced.'],

  ['g9s-c4-v078', 'equations_for_metals', 3,
   'Write the balanced equation for the reaction of iron with steam.',
   ['3Fe + 4H₂O → Fe₃O₄ + 4H₂', '2Fe + 3H₂O → Fe₂O₃ + 3H₂', 'Fe + H₂O → FeO + H₂', '3Fe + 2H₂O → Fe₃O₂ + 2H₂'],
   '3Fe + 4H₂O → Fe₃O₄ + 4H₂',
   'The product with steam is Fe₃O₄, not Fe₂O₃.',
   'Left: 3 Fe, 8 H, 4 O. Right: 3 Fe (in Fe₃O₄), 4 O (in Fe₃O₄), 8 H (in 4H₂). Balanced.'],

  ['g9s-c4-v079', 'equations_for_metals', 2,
   'Which equation correctly shows copper reacting with oxygen?',
   ['2Cu + O₂ → 2CuO', 'Cu + O → CuO', 'Cu + O₂ → CuO₂', '4Cu + O₂ → 2Cu₂O'],
   '2Cu + O₂ → 2CuO',
   'Copper(II) oxide formula is CuO; oxygen is diatomic.',
   '2Cu + O₂ → 2CuO. Two Cu atoms react with one O₂ to give two CuO units. Balanced: 2 Cu, 2 O each side.'],

  ['g9s-c4-v080', 'equations_for_metals', 3,
   'The thermite reaction: Al + Fe₂O₃ → Al₂O₃ + Fe. Balance this equation.',
   ['2Al + Fe₂O₃ → Al₂O₃ + 2Fe', 'Al + Fe₂O₃ → AlO₃ + 2Fe', '3Al + Fe₂O₃ → Al₃O₃ + 2Fe', '2Al + 2Fe₂O₃ → 2Al₂O₃ + 4Fe'],
   '2Al + Fe₂O₃ → Al₂O₃ + 2Fe',
   'Balance Al first (Al₂O₃ needs 2 Al), then check Fe and O.',
   'Left: 2 Al, 2 Fe, 3 O. Right: 2 Al (in Al₂O₃), 3 O (in Al₂O₃), 2 Fe. Balanced.'],

  ['g9s-c4-v081', 'equations_for_metals', 3,
   'Write the balanced equation for the reaction of potassium with water.',
   ['2K + 2H₂O → 2KOH + H₂', 'K + H₂O → KOH + H', '2K + H₂O → K₂O + H₂', 'K + 2H₂O → K(OH)₂ + H₂'],
   '2K + 2H₂O → 2KOH + H₂',
   'This has the same pattern as the sodium–water equation.',
   'Left: 2 K, 4 H, 2 O. Right: 2 K, 2 O, 2 H (in 2KOH) + 2 H (in H₂) = 4 H total. Balanced.'],

  ['g9s-c4-v082', 'equations_for_metals', 2,
   'Which equation represents the reaction of iron(III) oxide with carbon monoxide in a blast furnace?',
   ['Fe₂O₃ + 3CO → 2Fe + 3CO₂', 'Fe₂O₃ + CO → Fe + CO₂', '2Fe₂O₃ + 3C → 4Fe + 3CO₂', 'Fe₂O₃ + 2CO → Fe₂O + 2CO₂'],
   'Fe₂O₃ + 3CO → 2Fe + 3CO₂',
   'Balance O atoms: Fe₂O₃ has 3 O; each CO needs one extra O to become CO₂.',
   'Fe₂O₃ has 3 O; 3 CO molecules each gain one O to form 3 CO₂; 2 Fe are released. Left: 2 Fe, 3 O + 3 C + 3 O = 6 O. Right: 3 CO₂ = 6 O, 3 C; 2 Fe. Balanced.'],

  ['g9s-c4-v083', 'equations_for_metals', 3,
   'Write the balanced ionic equation for the displacement of copper by zinc from copper sulfate solution.',
   ['Zn + Cu²⁺ → Zn²⁺ + Cu', 'Zn²⁺ + Cu → Zn + Cu²⁺', 'Zn + CuSO₄ → ZnSO₄ + Cu', 'Zn²⁺ + Cu²⁺ → ZnCu⁴⁺'],
   'Zn + Cu²⁺ → Zn²⁺ + Cu',
   'Spectator ions (SO₄²⁻) are not included in the ionic equation.',
   'The ionic equation shows only the species that change: Zn loses 2 electrons (is oxidised) to form Zn²⁺; Cu²⁺ gains 2 electrons (is reduced) to form Cu. SO₄²⁻ is a spectator ion.'],

  ['g9s-c4-v084', 'equations_for_metals', 2,
   'Lead oxide (PbO) is reduced by hydrogen gas. What is the balanced equation?',
   ['PbO + H₂ → Pb + H₂O', 'PbO + 2H → Pb + H₂O', '2PbO + H₂ → Pb₂ + 2H₂O', 'PbO + H₂O → Pb + H₂O₂'],
   'PbO + H₂ → Pb + H₂O',
   'H₂ removes the oxygen from PbO; this is a reduction.',
   'Left: 1 Pb, 1 O, 2 H. Right: 1 Pb, 1 H₂O (1 O, 2 H). Balanced. H₂ reduces PbO by combining with its oxygen to form water.'],

  ['g9s-c4-v085', 'equations_for_metals', 3,
   'Write the balanced equation for magnesium reacting with steam.',
   ['Mg + H₂O → MgO + H₂', 'Mg + 2H₂O → Mg(OH)₂ + H₂', '2Mg + H₂O → Mg₂O + H₂', 'Mg + H₂O → MgH₂ + O'],
   'Mg + H₂O → MgO + H₂',
   'With steam, Mg forms the oxide, not the hydroxide.',
   'Mg + H₂O(g) → MgO + H₂. Left: 1 Mg, 2 H, 1 O. Right: 1 Mg, 1 O (MgO), 2 H (H₂). Balanced. With liquid water, Mg(OH)₂ may also form.'],

];

MCQ.forEach(([id, ss, diff, q, opts, ans, hint, expl]) => {
  STATIC_QUESTIONS.push(makeMCQ({
    id, chapterId: CH, subsection: ss, difficulty: diff,
    question: q, options: opts, answer: ans, hint, explanation: expl
  }));
});

})();
