'use strict';
// ══════════════════════════════════════════════════════════════════════════
//  Grade 9 Chemistry - C5 · Salts — Volume Bank
//  45 questions  ·  IDs g9s-c5-v001 … g9s-c5-v045
//  Subsections: neutralisation · soluble_insoluble ·
//               neutralisation_in_daily_life · uses_of_salts
//  Source: NCE Science (Chemistry) 2021-2025; NCF Grades 7-9 §C5.
// ══════════════════════════════════════════════════════════════════════════
(function () {

const CH = 'g9s-c5-salts';

const MCQ = [

  // ── neutralisation ───────────────────────────────────────────────────────
  ['g9s-c5-v001', 'neutralisation', 1,
   'What is neutralisation?',
   ['The reaction between an acid and a base (or alkali) to form a salt and water',
    'The reaction between two acids to form a neutral solution',
    'The dissolving of a salt in water to give a neutral pH',
    'The process of evaporating an alkali until it reaches pH 7'],
   'The reaction between an acid and a base (or alkali) to form a salt and water',
   'Acid + base is the general definition.',
   'Neutralisation: acid + base → salt + water. The H⁺ ions from the acid are neutralised by the OH⁻ ions from the base, forming water; the remaining ions form the salt.'],

  ['g9s-c5-v002', 'neutralisation', 1,
   'What is the pH at the equivalence point of a strong acid–strong base neutralisation?',
   ['7 (neutral)', 'Below 7 (acidic)', 'Above 7 (basic)', 'The pH depends on the colour of the indicator used'],
   '7 (neutral)',
   'Strong acid and strong base in equal amounts neutralise each other completely.',
   'Strong acid fully neutralised by a strong base gives a salt solution with pH 7 (e.g. NaCl from HCl + NaOH); neither ion hydrolyses to change the pH.'],

  ['g9s-c5-v003', 'neutralisation', 2,
   'Which equation represents a neutralisation reaction?',
   ['HCl + NaOH → NaCl + H₂O', 'NaCl + H₂O → HCl + NaOH', '2Na + 2H₂O → 2NaOH + H₂', 'CaCO₃ → CaO + CO₂'],
   'HCl + NaOH → NaCl + H₂O',
   'Acid + alkali → salt + water.',
   'HCl + NaOH → NaCl + H₂O is the classic neutralisation: hydrochloric acid (strong acid) + sodium hydroxide (strong alkali) → sodium chloride (salt) + water.'],

  ['g9s-c5-v004', 'neutralisation', 2,
   'A student titrates 25 cm³ of sodium hydroxide with hydrochloric acid using phenolphthalein indicator. The indicator is pink at the start. What colour change signals the end point?',
   ['Pink to colourless', 'Colourless to pink', 'Yellow to orange', 'Blue to red'],
   'Pink to colourless',
   'Phenolphthalein is pink in alkali and colourless in acid or neutral solution.',
   'Phenolphthalein: pink above pH ~8.2, colourless below. During acid into alkali titration, the solution is pink initially; at the equivalence point it turns permanently colourless.'],

  ['g9s-c5-v005', 'neutralisation', 2,
   'When hydrochloric acid is added drop by drop to sodium hydroxide solution with phenolphthalein, the student notices the pink disappears and returns. Why?',
   ['Each drop of acid creates a temporary local excess that fades when the acid mixes with excess alkali; at the end point the colour disappears permanently',
    'The indicator is decomposing and switching colour at random',
    'The acid is reacting with the indicator itself, changing its structure',
    'The pH is oscillating around 7 throughout the titration'],
   'Each drop of acid creates a temporary local excess that fades when the acid mixes with excess alkali; at the end point the colour disappears permanently',
   'Before the end point, there is still excess alkali to restore the colour.',
   'Before the equivalence point, excess NaOH is present; acid added in one spot locally lowers pH, decolouring the indicator, but mixing restores the alkaline pH and the pink returns. At the end point, no excess NaOH remains.'],

  ['g9s-c5-v006', 'neutralisation', 3,
   'In a titration, 22.5 cm³ of 0.1 mol/dm³ HCl neutralises 25 cm³ of NaOH. What is the concentration of the NaOH?',
   ['0.09 mol/dm³', '0.1 mol/dm³', '0.25 mol/dm³', '0.45 mol/dm³'],
   '0.09 mol/dm³',
   'Moles of HCl = moles of NaOH (1:1 ratio). Concentration = moles ÷ volume.',
   'n(HCl) = 0.0225 × 0.1 = 0.00225 mol. n(NaOH) = 0.00225 mol. c(NaOH) = 0.00225 ÷ 0.025 = 0.09 mol/dm³.'],

  ['g9s-c5-v007', 'neutralisation', 2,
   'Which of the following is the ionic equation for any strong acid–strong alkali neutralisation?',
   ['H⁺(aq) + OH⁻(aq) → H₂O(l)', 'H₂ + O → H₂O', 'HCl + NaOH → NaCl + H₂O', 'Na⁺ + Cl⁻ → NaCl'],
   'H⁺(aq) + OH⁻(aq) → H₂O(l)',
   'The spectator ions cancel out in the ionic equation.',
   'For any strong acid + strong alkali reaction, the ionic equation is always H⁺ + OH⁻ → H₂O; the cation of the alkali and anion of the acid are spectator ions.'],

  ['g9s-c5-v008', 'neutralisation', 3,
   'Ethanoic acid (a weak acid) is neutralised by sodium hydroxide. Is the pH at the equivalence point exactly 7, below 7, or above 7?',
   ['Above 7, because the ethanoate ion (CH₃COO⁻) hydrolyses slightly in water to produce a basic solution',
    'Exactly 7, because neutralisation always gives a neutral product',
    'Below 7, because ethanoic acid is weak and some remains unneutralised',
    'Exactly 7, because sodium hydroxide is a strong base that overrides the weakness of the acid'],
   'Above 7, because the ethanoate ion (CH₃COO⁻) hydrolyses slightly in water to produce a basic solution',
   'Weak acid + strong base → salt of a weak acid; that salt is slightly alkaline.',
   'CH₃COO⁻ + H₂O ⇌ CH₃COOH + OH⁻; the equilibrium lies slightly right, giving a small excess of OH⁻ and pH > 7 at the equivalence point.'],

  ['g9s-c5-v009', 'neutralisation', 2,
   'Which salt is formed when sulfuric acid reacts with potassium hydroxide?',
   ['Potassium sulfate (K₂SO₄)', 'Potassium sulfite (K₂SO₃)', 'Potassium chloride (KCl)', 'Potassium hydroxide (no reaction)'],
   'Potassium sulfate (K₂SO₄)',
   'The salt takes the metal from the alkali and the anion from the acid.',
   'H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O. The salt is potassium sulfate, formed from K⁺ (from KOH) and SO₄²⁻ (from H₂SO₄).'],

  ['g9s-c5-v010', 'neutralisation', 3,
   'A student wishes to prepare a pure dry sample of copper sulfate by neutralisation. She cannot use copper hydroxide because it is insoluble. What method should she use?',
   ['Add excess copper oxide (a base) to warm dilute sulfuric acid, filter off the excess solid, then crystallise the filtrate',
    'Add excess copper metal to dilute sulfuric acid, filter, then crystallise',
    'Add sodium hydroxide to copper sulfate solution and filter the copper sulfate that precipitates',
    'Electrolyse copper sulfate solution and collect the salt from the electrodes'],
   'Add excess copper oxide (a base) to warm dilute sulfuric acid, filter off the excess solid, then crystallise the filtrate',
   'Base + acid → salt + water; excess solid base can be filtered off, unlike excess liquid alkali.',
   'CuO + H₂SO₄ → CuSO₄ + H₂O. Using excess CuO ensures all the acid is neutralised; the excess CuO is filtered off as a solid; the CuSO₄ solution is crystallised to give pure blue crystals.'],

  ['g9s-c5-v011', 'neutralisation', 2,
   'Why is excess acid (or excess base) a problem in the preparation of a pure salt by neutralisation?',
   ['Excess reactant will contaminate the final salt product and make it impure',
    'Excess reactant speeds up crystallisation and makes the crystals too small',
    'Excess reactant reacts with the salt product and destroys it',
    'Excess reactant makes the solution too concentrated to crystallise'],
   'Excess acid (or excess base) will contaminate the final salt product and make it impure',
   'The product must be pure, so neither reactant should be left over.',
   'Any remaining acid or alkali will be present in the filtrate and will contaminate the crystals when the solution is evaporated; to get a pure salt, the reactants must be used in exactly the stoichiometric ratio, or excess solid base is added and filtered off.'],

  // ── soluble_insoluble ─────────────────────────────────────────────────────
  ['g9s-c5-v012', 'soluble_insoluble', 1,
   'Which of these salts is INSOLUBLE in water?',
   ['Barium sulfate (BaSO₄)', 'Sodium chloride (NaCl)', 'Potassium nitrate (KNO₃)', 'Ammonium sulfate ((NH₄)₂SO₄)'],
   'Barium sulfate (BaSO₄)',
   'Most sulfates are soluble, but barium sulfate is a notable exception.',
   'BaSO₄ is insoluble in water; this is used in medicine as a barium meal for X-ray imaging of the gut because it is opaque to X-rays and does not dissolve to release toxic Ba²⁺ ions.'],

  ['g9s-c5-v013', 'soluble_insoluble', 1,
   'Which of these is a general solubility rule for nitrate salts?',
   ['All nitrate salts are soluble in water', 'All nitrate salts are insoluble in water', 'Only sodium nitrate is soluble; all others are insoluble', 'Nitrate salts dissolve only in hot water'],
   'All nitrate salts are soluble in water',
   'Nitrates are always soluble — this is a rule to memorise.',
   'All nitrates (salts of nitric acid) are soluble in water; this is one of the basic solubility rules in GCSE/NCE Chemistry.'],

  ['g9s-c5-v014', 'soluble_insoluble', 2,
   'Which of these silver salts is soluble in water?',
   ['Silver nitrate (AgNO₃)', 'Silver chloride (AgCl)', 'Silver bromide (AgBr)', 'Silver iodide (AgI)'],
   'Silver nitrate (AgNO₃)',
   'Silver halides are insoluble, but all nitrates are soluble.',
   'AgCl, AgBr and AgI are all insoluble (used in photography); AgNO₃ is soluble because all nitrates are soluble.'],

  ['g9s-c5-v015', 'soluble_insoluble', 2,
   'How is lead(II) iodide (PbI₂) prepared in the laboratory?',
   ['Mixing solutions of lead nitrate and potassium iodide, then filtering off the yellow precipitate',
    'Reacting lead metal with hydriodic acid',
    'Dissolving lead iodide in hot water and crystallising on cooling',
    'Electrolyzing a lead solution with an iodine electrode'],
   'Mixing solutions of lead nitrate and potassium iodide, then filtering off the yellow precipitate',
   'Two soluble salts react to form an insoluble precipitate.',
   'Pb(NO₃)₂(aq) + 2KI(aq) → PbI₂(s) + 2KNO₃(aq). PbI₂ is an insoluble yellow solid (precipitate); it is made by mixing two soluble salts that contain the required ions, then filtering.'],

  ['g9s-c5-v016', 'soluble_insoluble', 2,
   'Which of these carbonates is soluble in water?',
   ['Sodium carbonate (Na₂CO₃)', 'Calcium carbonate (CaCO₃)', 'Copper carbonate (CuCO₃)', 'Barium carbonate (BaCO₃)'],
   'Sodium carbonate (Na₂CO₃)',
   'Group 1 (sodium, potassium) carbonates are soluble; most others are not.',
   'Most carbonates are insoluble except those of Group 1 metals and ammonium. Na₂CO₃ (washing soda) is a notable soluble carbonate.'],

  ['g9s-c5-v017', 'soluble_insoluble', 3,
   'A test for sulfate ions involves adding barium chloride solution acidified with dilute hydrochloric acid. Why is HCl added?',
   ['To prevent false positives from other anions (e.g. carbonate or sulfite) that would also precipitate with Ba²⁺',
    'To dissolve BaSO₄ so that it can be filtered more easily',
    'To increase the concentration of Ba²⁺ ions in solution',
    'To lower the pH below 1, which is needed for BaSO₄ to precipitate'],
   'To prevent false positives from other anions (e.g. carbonate or sulfite) that would also precipitate with Ba²⁺',
   'HCl acidifies the solution, dissolving other insoluble barium compounds.',
   'BaCO₃ and BaSO₃ are also insoluble and white; HCl dissolves them (carbonates release CO₂; sulfites dissolve) but does not dissolve BaSO₄, which is acid-stable. This ensures only SO₄²⁻ gives the white precipitate.'],

  ['g9s-c5-v018', 'soluble_insoluble', 2,
   'The test for chloride ions uses silver nitrate solution. What observation confirms chloride ions are present?',
   ['A white precipitate of silver chloride that is insoluble in dilute nitric acid but dissolves in dilute ammonia solution',
    'A yellow precipitate that dissolves in ammonia',
    'A blue precipitate that turns white in sunlight',
    'A bright orange precipitate that does not dissolve in any reagent'],
   'A white precipitate of silver chloride that is insoluble in dilute nitric acid but dissolves in dilute ammonia solution',
   'AgCl is white and soluble in ammonia — use this to distinguish it from AgBr (cream) and AgI (yellow).',
   'AgCl is a white precipitate; AgBr is cream; AgI is yellow. All three are insoluble in dilute HNO₃, but AgCl dissolves readily in dilute NH₃, AgBr in concentrated NH₃, and AgI does not dissolve. This cascade distinguishes the three halides.'],

  ['g9s-c5-v019', 'soluble_insoluble', 3,
   'Why must the chloride test with AgNO₃ be carried out in the presence of dilute nitric acid rather than dilute sulfuric acid?',
   ['Sulfate ions would form the insoluble AgSO₄ precipitate, giving a false positive for chloride',
    'Nitric acid makes AgCl precipitate faster than sulfuric acid does',
    'Sulfuric acid dissolves AgCl, which would prevent the test from working',
    'Nitric acid provides silver ions; sulfuric acid does not'],
   'Sulfate ions would form the insoluble AgSO₄ precipitate, giving a false positive for chloride',
   'The anion of the acid used must not itself precipitate with silver.',
   'Ag₂SO₄ is slightly insoluble and could precipitate, giving a false result. Dilute HNO₃ is used because AgNO₃ is soluble and NO₃⁻ does not interfere.'],

  ['g9s-c5-v020', 'soluble_insoluble', 2,
   'Which of the following pairs would react to form a precipitate?',
   ['Pb(NO₃)₂(aq) and KI(aq)', 'NaNO₃(aq) and KCl(aq)', 'CaCl₂(aq) and NaNO₃(aq)', 'K₂SO₄(aq) and NaCl(aq)'],
   'Pb(NO₃)₂(aq) and KI(aq)',
   'A precipitate forms when the combination of ions produces an insoluble salt.',
   'Pb²⁺ + 2I⁻ → PbI₂ (yellow precipitate). The other combinations: NaNO₃ + KCl gives NaCl (soluble) and KNO₃ (soluble); CaCl₂ + NaNO₃ gives Ca(NO₃)₂ (soluble) and NaCl (soluble); K₂SO₄ + NaCl gives KCl and Na₂SO₄ (both soluble).'],

  ['g9s-c5-v021', 'soluble_insoluble', 2,
   'Which of these is a correct rule for the solubility of chloride salts?',
   ['All chlorides are soluble except silver chloride (AgCl), lead(II) chloride (PbCl₂) and mercury(I) chloride (Hg₂Cl₂)',
    'All chlorides are insoluble in water',
    'Only sodium chloride is soluble; all other chlorides are insoluble',
    'Chlorides are soluble only if the metal has a valency of 1'],
   'All chlorides are soluble except silver chloride (AgCl), lead(II) chloride (PbCl₂) and mercury(I) chloride (Hg₂Cl₂)',
   'The exceptions to the "all chlorides are soluble" rule.',
   'The general rule: chlorides are soluble; the key exceptions are AgCl (white ppt), PbCl₂ (white ppt, soluble in hot water) and Hg₂Cl₂. All other common chlorides are soluble.'],

  ['g9s-c5-v022', 'soluble_insoluble', 3,
   'A student mixes two clear solutions and gets a white precipitate. She then adds excess dilute nitric acid and the precipitate dissolves with fizzing. What is the precipitate most likely to be?',
   ['A carbonate (e.g. CaCO₃) — it dissolves in acid with CO₂ released',
    'Barium sulfate — it dissolves in dilute nitric acid',
    'Silver chloride — it fizzes when acid is added',
    'Lead iodide — it dissolves in dilute acid with iodine gas'],
   'A carbonate (e.g. CaCO₃) — it dissolves in acid with CO₂ released',
   'Which insoluble white compound dissolves in acid with gas production?',
   'CaCO₃ + 2HNO₃ → Ca(NO₃)₂ + H₂O + CO₂. The CO₂ causes fizzing. BaSO₄ does NOT dissolve in dilute acids; AgCl does not fizz; PbI₂ is yellow.'],

  // ── neutralisation_in_daily_life ──────────────────────────────────────────
  ['g9s-c5-v023', 'neutralisation_in_daily_life', 1,
   'Farmers add powdered limestone (CaCO₃) to acidic soil. What is the purpose of this?',
   ['To neutralise the acidity of the soil and raise the pH to allow crops to grow',
    'To add phosphate nutrients that crops need to grow',
    'To kill pests and weeds by dissolving them with the alkali',
    'To make the soil more porous so that air can reach the roots'],
   'To neutralise the acidity of the soil and raise the pH to allow crops to grow',
   'Limestone is a base that reacts with acid.',
   'Acidic soil (low pH) inhibits crop growth; limestone, slaked lime (Ca(OH)₂) or agricultural lime neutralises the excess acid, raising the pH to the optimal range (around 6–7) for most crops.'],

  ['g9s-c5-v024', 'neutralisation_in_daily_life', 1,
   'Indigestion tablets contain magnesium hydroxide or calcium carbonate. How do they relieve indigestion?',
   ['They neutralise excess hydrochloric acid in the stomach',
    'They absorb water from the stomach, diluting the acid',
    'They coat the stomach lining and prevent acid from forming',
    'They react with the food to break it down faster'],
   'They neutralise excess hydrochloric acid in the stomach',
   'The stomach produces HCl; the tablet is a base.',
   'Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O; CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. Both bases neutralise excess HCl, raising the pH and relieving the pain of acid indigestion.'],

  ['g9s-c5-v025', 'neutralisation_in_daily_life', 2,
   'A bee sting injects methanoic (formic) acid into the skin. How can the pain be relieved using chemistry?',
   ['Apply a weak base such as baking soda (sodium hydrogen carbonate) to neutralise the acid',
    'Apply a weak acid such as vinegar to neutralise the acid',
    'Apply pure water to dilute the acid until it is harmless',
    'Apply toothpaste containing fluoride to neutralise the acid'],
   'Apply a weak base such as baking soda (sodium hydrogen carbonate) to neutralise the acid',
   'An acid sting is treated with a base.',
   'Methanoic acid (formic acid) is acidic; applying NaHCO₃ solution (basic, pH ~8) to the sting neutralises the acid and reduces the pain and swelling.'],

  ['g9s-c5-v026', 'neutralisation_in_daily_life', 2,
   'A wasp sting is alkaline (contains a base). What domestic product can be used to treat it?',
   ['Vinegar (ethanoic acid) to neutralise the alkali',
    'Baking soda (sodium hydrogen carbonate) to neutralise the alkali',
    'Lemon juice, which is an alkali, to dilute the sting',
    'Toothpaste, which contains a strong acid'],
   'Vinegar (ethanoic acid) to neutralise the alkali',
   'An alkaline sting needs an acidic treatment.',
   'Wasp venom is alkaline (contains amines and ammonium compounds); dilute acid (vinegar, pH ≈ 3) neutralises it. Bee venom is acidic; the remedies are reversed.'],

  ['g9s-c5-v027', 'neutralisation_in_daily_life', 2,
   'Why is acid rain particularly damaging to crops on calcium-poor soils?',
   ['Calcium-poor soils have less natural buffering and become acidic more quickly when acid rain falls',
    'Calcium-poor soils are less porous and hold the acid rain in contact with roots longer',
    'Calcium reacts with crops to make them grow faster, so its absence slows growth on its own',
    'Acid rain dissolves the calcium in the soil, making the soil calcium-poor in the first place'],
   'Calcium-poor soils have less natural buffering and become acidic more quickly when acid rain falls',
   'Calcium carbonate in soil neutralises acid rain naturally.',
   'CaCO₃ in the soil reacts with H₂SO₄ and HNO₃ in acid rain, neutralising the acidity (buffering). Soils poor in calcium carbonate (e.g. sandy soils on granite) have little natural buffering capacity and their pH drops more rapidly.'],

  ['g9s-c5-v028', 'neutralisation_in_daily_life', 3,
   'Toothpaste often contains a mild abrasive and sodium fluoride. How does the fluoride ion help protect teeth from acid decay?',
   ['Fluoride replaces hydroxide in tooth enamel (hydroxyapatite), making it harder and more resistant to acid attack',
    'Fluoride neutralises the acid produced by bacteria directly, preventing pH drop in the mouth',
    'Fluoride coats the tooth surface with an insoluble film that prevents acid from reaching the enamel',
    'Fluoride kills all the bacteria in the mouth, preventing acid production entirely'],
   'Fluoride replaces hydroxide in tooth enamel (hydroxyapatite), making it harder and more resistant to acid attack',
   'Fluoride is incorporated into the enamel structure.',
   'Fluoride ions replace OH⁻ in Ca₁₀(PO₄)₆(OH)₂ (hydroxyapatite) to form fluorapatite Ca₁₀(PO₄)₆F₂, which is more resistant to acid dissolution because the F⁻ ion is less basic than OH⁻.'],

  ['g9s-c5-v029', 'neutralisation_in_daily_life', 2,
   'Which substance is applied to lakes affected by acid rain to neutralise the acidity?',
   ['Powdered limestone (calcium carbonate) or quicklime (calcium oxide)',
    'Sodium chloride (table salt)',
    'Sodium hydroxide pellets',
    'Carbon dioxide gas dissolved in the lake water'],
   'Powdered limestone (calcium carbonate) or quicklime (calcium oxide)',
   'A base is used to neutralise the acid.',
   'Powdered CaCO₃ (limestone) or Ca(OH)₂ (slaked lime) is spread over acidified lakes: CaCO₃ + H₂SO₄ → CaSO₄ + H₂O + CO₂, raising the pH and allowing fish to survive.'],

  ['g9s-c5-v030', 'neutralisation_in_daily_life', 3,
   'A student adds baking soda (NaHCO₃) to vinegar (ethanoic acid, CH₃COOH). She observes vigorous fizzing. What is happening and why is this different from a simple acid–alkali neutralisation?',
   ['CO₂ gas is produced because NaHCO₃ is a bicarbonate, not a simple hydroxide; the reaction gives a salt, water and CO₂ rather than just salt and water',
    'H₂ gas is produced because the sodium displaces hydrogen from the acid',
    'The fizzing is simply the mixing of two liquids of different viscosity',
    'O₂ gas is released because the NaHCO₃ decomposes in the acid'],
   'CO₂ gas is produced because NaHCO₃ is a bicarbonate, not a simple hydroxide; the reaction gives a salt, water and CO₂ rather than just salt and water',
   'Bicarbonates react with acids differently from hydroxides.',
   'CH₃COOH + NaHCO₃ → CH₃COONa + H₂O + CO₂. The HCO₃⁻ ion reacts with H⁺: HCO₃⁻ + H⁺ → H₂O + CO₂. Unlike OH⁻, the bicarbonate releases CO₂, causing vigorous fizzing.'],

  ['g9s-c5-v031', 'neutralisation_in_daily_life', 2,
   'Why might a farmer choose slaked lime (Ca(OH)₂) rather than powdered limestone (CaCO₃) to treat an acidic field quickly?',
   ['Slaked lime reacts faster with soil acid because it is a soluble hydroxide; limestone reacts more slowly as it must dissolve first',
    'Slaked lime is cheaper to produce than limestone',
    'Slaked lime adds more calcium per tonne than limestone does',
    'Limestone causes the soil pH to rise too high, while slaked lime gives a more controlled increase'],
   'Slaked lime reacts faster with soil acid because it is a soluble hydroxide; limestone reacts more slowly as it must dissolve first',
   'Solubility determines how fast the base reaches the acid.',
   'Ca(OH)₂ is slightly soluble, giving OH⁻ ions immediately; CaCO₃ is insoluble and must be dissolved by the soil acid before neutralisation can proceed, so limestone acts more slowly. Quicklime (CaO) acts fastest but is more expensive and dangerous.'],

  ['g9s-c5-v032', 'neutralisation_in_daily_life', 3,
   'An industrial chimney scrubber sprays calcium hydroxide solution into the exhaust gases to remove acid gases. Write the equation for SO₂ removal.',
   ['SO₂ + Ca(OH)₂ → CaSO₃ + H₂O', 'SO₂ + CaO → CaCO₃', 'SO₂ + 2Ca(OH)₂ → Ca₂SO₄ + 2H₂O', 'SO₂ + Ca(OH)₂ → CaSO₄ + H₂'],
   'SO₂ + Ca(OH)₂ → CaSO₃ + H₂O',
   'Acidic oxide + base → salt + water.',
   'SO₂ (acid oxide) + Ca(OH)₂ (base) → CaSO₃ (calcium sulfite) + H₂O. Further oxidation gives CaSO₄ (gypsum). This is the flue-gas desulfurisation reaction, a wet scrubbing process.'],

  ['g9s-c5-v033', 'neutralisation_in_daily_life', 2,
   'Antacid tablets are made from calcium carbonate. The reaction with HCl produces a gas. Which gas is produced?',
   ['Carbon dioxide (CO₂)', 'Hydrogen (H₂)', 'Oxygen (O₂)', 'Chlorine (Cl₂)'],
   'Carbon dioxide (CO₂)',
   'Acid + carbonate → salt + water + CO₂.',
   'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. The CO₂ is the fizz you experience when you take a calcium carbonate antacid tablet with stomach acid.'],

  ['g9s-c5-v034', 'neutralisation_in_daily_life', 3,
   'A student argues: "Lemon juice (pH 2) would cure a wasp sting (alkaline) better than vinegar (pH 3) because it is more acidic." Evaluate this claim.',
   ['It is partly correct — a lower pH means more H⁺ to neutralise the alkali; but lemon juice is a food acid and both concentrations are orders of magnitude above what is needed for a small alkaline sting',
    'It is completely correct — pH 2 always neutralises an alkaline sting more effectively than pH 3',
    'It is completely incorrect — lemon juice is itself alkaline and would worsen a wasp sting',
    'It is incorrect — the type of acid matters, not the pH; only vinegar acid works on wasp venom'],
   'It is partly correct — a lower pH means more H⁺ to neutralise the alkali; but lemon juice is a food acid and both concentrations are orders of magnitude above what is needed for a small alkaline sting',
   'Think about what pH actually means and how much acid is actually needed.',
   'pH 2 has ten times more H⁺ than pH 3, so lemon juice is more potent; however, the amount of alkali in a wasp sting is tiny and either acid provides far more than enough H⁺. The practical difference for a sting is negligible, and applying very concentrated acid could irritate the skin.'],

  // ── uses_of_salts ─────────────────────────────────────────────────────────
  ['g9s-c5-v035', 'uses_of_salts', 1,
   'Which salt is used as common table salt and for food preservation?',
   ['Sodium chloride (NaCl)', 'Sodium carbonate (Na₂CO₃)', 'Potassium nitrate (KNO₃)', 'Magnesium sulfate (MgSO₄)'],
   'Sodium chloride (NaCl)',
   'It is the most commonly used salt in cooking.',
   'NaCl (sodium chloride) is used to season food, preserve fish and meat, and in the chemical industry to make chlorine and sodium hydroxide by electrolysis (the chlor-alkali process).'],

  ['g9s-c5-v036', 'uses_of_salts', 1,
   'Which salt is used in medicine as a laxative and is also known as Epsom salt?',
   ['Magnesium sulfate (MgSO₄·7H₂O)', 'Sodium chloride (NaCl)', 'Barium sulfate (BaSO₄)', 'Potassium chloride (KCl)'],
   'Magnesium sulfate (MgSO₄·7H₂O)',
   'Epsom salt is named after Epsom in England where it was first found.',
   'Magnesium sulfate heptahydrate (MgSO₄·7H₂O, Epsom salt) is used as a laxative, in muscle relaxation baths, and as a magnesium supplement in horticulture.'],

  ['g9s-c5-v037', 'uses_of_salts', 2,
   'Potassium nitrate (KNO₃) is used as a fertiliser. Which two elements does it supply to plants?',
   ['Potassium (K) and nitrogen (N)', 'Potassium (K) and oxygen (O)', 'Nitrogen (N) and sulfur (S)', 'Potassium (K) and phosphorus (P)'],
   'Potassium (K) and nitrogen (N)',
   'Read the formula: which elements are present?',
   'KNO₃ contains K (potassium) and N (nitrogen); both are macronutrients for plant growth. K promotes flowering and fruiting; N promotes leaf and stem growth.'],

  ['g9s-c5-v038', 'uses_of_salts', 2,
   'Barium sulfate is used as a "barium meal" in medical imaging. Why is its insolubility important for this use?',
   ['Insolubility means no Ba²⁺ ions dissolve — Ba²⁺ is toxic, so an insoluble form is safe to swallow',
    'Insolubility means it can be filtered from the body quickly after the scan',
    'Insolubility makes it harder to X-ray through, increasing its contrast',
    'Insolubility means it stays in the stomach and does not pass to the bowel'],
   'Insolubility means no Ba²⁺ ions dissolve — Ba²⁺ is toxic, so an insoluble form is safe to swallow',
   'Barium ions are highly toxic; insolubility prevents them from entering the bloodstream.',
   'Ba²⁺ ions are poisonous; BaSO₄ is so insoluble (Ksp ≈ 10⁻¹⁰) that essentially no Ba²⁺ dissolves in the gut. It is also opaque to X-rays, providing contrast for imaging the gastrointestinal tract.'],

  ['g9s-c5-v039', 'uses_of_salts', 2,
   'Which salt is used in the manufacture of glass and as a water softener?',
   ['Sodium carbonate (Na₂CO₃)', 'Sodium chloride (NaCl)', 'Calcium sulfate (CaSO₄)', 'Potassium nitrate (KNO₃)'],
   'Sodium carbonate (Na₂CO₃)',
   'Washing soda has two key industrial uses.',
   'Na₂CO₃ (washing soda / soda ash) is used in glassmaking (mixed with SiO₂ and CaCO₃), in water softening (Na₂CO₃ + CaCl₂ → CaCO₃↓ + 2NaCl, removing Ca²⁺ from hard water), and in the manufacture of paper and soap.'],

  ['g9s-c5-v040', 'uses_of_salts', 3,
   'Why is calcium sulfate (CaSO₄·½H₂O, plaster of Paris) used to make casts for broken bones?',
   ['It sets hard on adding water and can be moulded before setting, making it ideal for immobilising limbs',
    'It slowly dissolves, releasing calcium which helps the broken bone heal faster',
    'It is very flexible once set, allowing some movement while protecting the fracture',
    'It is transparent to X-rays so the fracture can be monitored without removing the cast'],
   'It sets hard on adding water and can be moulded before setting, making it ideal for immobilising limbs',
   'Plaster of Paris undergoes a setting reaction.',
   '(CaSO₄)₂·H₂O + 3H₂O → 2CaSO₄·2H₂O (gypsum). The expansion on setting locks the mould in place; the resulting gypsum is hard, rigid and holds the fracture firmly in position during healing.'],

  ['g9s-c5-v041', 'uses_of_salts', 2,
   'Silver bromide (AgBr) is used in traditional photographic film. What property makes it suitable?',
   ['It decomposes on exposure to light, forming metallic silver which darkens the film',
    'It dissolves in light to produce a coloured dye that records the image',
    'It reflects light perfectly, producing a mirror image of the scene',
    'It is transparent and allows all wavelengths of light through equally'],
   'It decomposes on exposure to light, forming metallic silver which darkens the film',
   'Photographic chemicals are light-sensitive.',
   'AgBr(s) + light → Ag(s) + Br. Metallic silver forms a dark deposit wherever light hits the film; after chemical development and fixing (dissolving unreacted AgBr), the image is permanent.'],

  ['g9s-c5-v042', 'uses_of_salts', 2,
   'Ammonium nitrate (NH₄NO₃) is used as a fertiliser. What nutrient does it supply?',
   ['Nitrogen — provided by both the ammonium ion and the nitrate ion',
    'Phosphorus and nitrogen — it is a complete fertiliser',
    'Potassium — the ammonium ion releases potassium when it decomposes',
    'Carbon — the nitrate decomposes to CO₂ which feeds the plants'],
   'Nitrogen — provided by both the ammonium ion and the nitrate ion',
   'Both NH₄⁺ and NO₃⁻ contain nitrogen.',
   'NH₄NO₃ contains 35% nitrogen by mass — one of the highest of any common fertiliser. Both NH₄⁺ (taken up directly by roots or nitrified by soil bacteria) and NO₃⁻ (immediately available) supply nitrogen.'],

  ['g9s-c5-v043', 'uses_of_salts', 3,
   'Potassium permanganate (KMnO₄) is used as an antiseptic. What makes it effective?',
   ['It is a strong oxidising agent that destroys bacteria by oxidising their cell components',
    'It dissolves bacteria directly because it is highly soluble',
    'It forms an insoluble coating on wounds that prevents bacteria from entering',
    'It reacts with water to form hydrogen peroxide, which kills bacteria'],
   'It is a strong oxidising agent that destroys bacteria by oxidising their cell components',
   'MnO₄⁻ is a very powerful oxidiser.',
   'KMnO₄ releases oxygen (as MnO₄⁻ is reduced to MnO₂) and acts as a biocide by oxidising bacterial proteins and cell walls. Dilute solutions (1:10,000) are used for skin infections and wound cleaning.'],

  ['g9s-c5-v044', 'uses_of_salts', 2,
   'Calcium chloride (CaCl₂) is spread on icy roads. Why does it work?',
   ['It dissolves in any surface water and lowers the freezing point of the solution, preventing ice from forming',
    'It reacts with water exothermically, generating heat that melts the ice',
    'It absorbs moisture from the air and forms a dry layer that prevents cars from skidding',
    'It reacts with ice to form calcium oxide and hydrogen chloride gas, breaking the ice down chemically'],
   'It dissolves in any surface water and lowers the freezing point of the solution, preventing ice from forming',
   'Dissolving a solute lowers the freezing point of the solvent.',
   'Dissolving CaCl₂ (or NaCl) in water lowers the freezing point below 0 °C (freezing-point depression); this prevents ice from forming or melts existing ice at temperatures below 0 °C.'],

  ['g9s-c5-v045', 'uses_of_salts', 3,
   'A student wants to make potassium chloride (KCl) in the laboratory. She has potassium hydroxide solution and hydrochloric acid. Describe the steps.',
   ['Titrate KOH with HCl to find the exact volume for neutralisation, then mix those exact volumes, evaporate the solution and crystallise the KCl',
    'Add excess KOH to HCl, filter off the excess, and crystallise',
    'Mix KOH and HCl in any ratio, evaporate to dryness — any excess will decompose',
    'Electrolyse a KOH solution with a carbon anode and iron cathode to form KCl'],
   'Titrate KOH with HCl to find the exact volume for neutralisation, then mix those exact volumes, evaporate the solution and crystallise the KCl',
   'Both KOH and HCl are soluble — neither excess can be filtered off.',
   'KOH + HCl → KCl + H₂O. Since both reactants are soluble, excess cannot be removed by filtration. A prior titration determines the exact volumes needed; combining those volumes gives a pure KCl solution; evaporation and crystallisation give the solid salt.'],

];

MCQ.forEach(([id, ss, diff, q, opts, ans, hint, expl]) => {
  STATIC_QUESTIONS.push(makeMCQ({
    id, chapterId: CH, subsection: ss, difficulty: diff,
    question: q, options: opts, answer: ans, hint, explanation: expl
  }));
});

})();
