'use strict';
// Grade 4 English coverage batch: practical text types.
(function(){
 const add=(id,subsection,question,options,answer,hint,explanation)=>STATIC_QUESTIONS.push(makeMCQ({id,chapterId:'g4eng-passages',subsection,difficulty:2,question,options,answer,hint,explanation}));
 const letters=[['Dear Grandma,\n\nThank you for the birthday book.\n\nLove, Asha','Asha','the writer’s name'],['Dear Ravi,\n\nPlease come to my party on Saturday at 2 p.m.\n\nFrom, Neel','Saturday at 2 p.m.','when the party is'],['Dear Teacher,\n\nI was absent because I had a fever.\n\nYours sincerely, Maya','to explain an absence','why Maya wrote'],['Dear Mum,\n\nWe arrived safely at the camp.\n\nLove, Sam','Sam is safe at camp','what the letter tells us'],['Dear Auntie,\n\nI enjoyed the delicious meal yesterday.\n\nLove, Leila','to say thank you','the purpose'],['Dear Principal,\n\nCould we have more books in the library?\n\nYours faithfully, Class 4','more library books','what is requested'],['Dear Dad,\n\nThe match starts at 4 p.m.\n\nLove, Iqbal','4 p.m.','the match time'],['Dear Friend,\n\nI miss playing with you.\n\nFrom, Tara','Tara','the sender'],['Dear Mrs Wong,\n\nThank you for helping our class plant trees.\n\nYours sincerely, Grade 4','to thank Mrs Wong','the purpose'],['Dear Cousin,\n\nWe are visiting Rodrigues next week.\n\nLove, Nisha','next week','when the visit is'],['Dear Coach,\n\nI cannot come to practice because I am unwell.\n\nYours, Ali','Ali is unwell','why Ali cannot come'],['Dear Library,\n\nMay I renew my book, please?\n\nFrom, Ravi','to renew a book','the request'],['Dear Mum,\n\nPlease pack my swimming costume tomorrow.\n\nLove, Tina','a swimming costume','what Tina needs'],['Dear Neighbour,\n\nYour lost cat is in our garden.\n\nFrom, Jay','the cat is in Jay’s garden','the message'],['Dear Grandma,\n\nCongratulations on your birthday!\n\nLove, Ben','to congratulate Grandma','the purpose'],['Dear Teacher,\n\nMay I borrow a ruler, please?\n\nYours, Kim','a ruler','what Kim wants']];
 letters.forEach(([text,answer,ask],i)=>add(`g4eng-cover-letter-${String(i+1).padStart(2,'0')}`,'letter',`Read this letter:<br><br>${text.replace(/\n/g,'<br>')}<br><br>What does it tell you about ${ask}?`,[answer,'nothing','a different event','a colour'],answer,'Read the letter carefully and find the detail asked for.',`The letter tells us <b>${answer}</b>.`));
 const adverts=[['BAKE SALE — Friday, 10 a.m., school yard. Cakes Rs 10.','Friday','when it happens'],['LOST DOG — small brown dog near the market. Call 5555 1111.','call 5555 1111','what to do'],['BOOK FAIR — Saturday, library hall. Free entry.','the library hall','where it is'],['FOOTBALL TRY-OUTS — Monday after school. Bring trainers.','trainers','what to bring'],['BEACH CLEAN-UP — 8 a.m. at Blue Bay. Gloves provided.','Blue Bay','where to go'],['ART CLUB — every Wednesday. Room 6.','Wednesday','the day'],['SCHOOL CONCERT — tickets Rs 30.','Rs 30','the ticket price'],['FARMERS’ MARKET — fresh fruit and vegetables. Sunday.','fresh fruit and vegetables','what is sold'],['SWIM LESSONS — beginners welcome. Call 5000 2222.','beginners','who can join'],['NO PARKING — keep this gate clear.','not park there','what the notice says'],['SCIENCE SHOW — 3 p.m. in the hall.','3 p.m.','the time'],['PICNIC DAY — bring a hat and water bottle.','a hat and water bottle','what to bring'],['MUSEUM OPEN — 9 a.m. to 4 p.m.','9 a.m. to 4 p.m.','opening hours'],['DANCE CLASS — register by 5 June.','5 June','the deadline'],['RAINY DAY SALE — umbrellas half price.','umbrellas','what is on sale']];
 adverts.forEach(([text,answer,ask],i)=>add(`g4eng-cover-advert-${String(i+1).padStart(2,'0')}`,'advert',`Read this notice: <b>${text}</b><br>What is ${ask}?`,[answer,'a different answer','not stated','tomorrow'],answer,'Notices give short, important details.',`The notice says <b>${answer}</b>.`));
 [['Raj found a kite in a tree and returned it to its owner.','Raj was honest'],['A class worked together to build a garden and felt proud.','Teamwork helped the class']].forEach(([text,answer],i)=>add(`g4eng-cover-story-${String(i+1).padStart(2,'0')}`,'story',`Read: “${text}” What is a good lesson from the story?`,[answer,'Never help anyone','Gardens cannot grow','Kites are always lost'],answer,'Think about what the character’s actions teach us.',`The story shows that <b>${answer.toLowerCase()}</b>.`));
 const instructions=[['Wash your hands. Mix flour and water. Bake for 20 minutes.','Wash your hands','the first step'],['1. Open the book. 2. Read the title. 3. Answer the questions.','Open the book','what to do first'],['Put on your helmet before riding your bicycle.','put on a helmet','the safety instruction'],['Water the seed, then place it in sunlight.','water the seed','what happens first'],['First collect litter. Next sort it into bins.','sort it into bins','what happens next'],['Use a ruler to draw a straight line.','a ruler','what tool to use'],['Turn off the tap after brushing your teeth.','turn off the tap','what to do after brushing'],['Add soap, rub your hands, then rinse with water.','rinse with water','the final step'],['Read all the questions before you begin.','read all the questions','what to do before beginning'],['Cross the road only at the pedestrian crossing.','at the pedestrian crossing','where to cross'],['First pack your bag. Then check you have your homework.','check for homework','what to do second'],['Stir the paint slowly to mix the colours.','stir the paint slowly','how to mix colours'],['Wear gloves before touching cleaning products.','wear gloves','the safety step'],['Plant the seed 2 cm deep in soil.','2 cm','how deep'],['Save your work before closing the computer.','save your work','what to do before closing'],['Follow the arrows to reach the exit.','follow the arrows','what to do']];
 instructions.forEach(([text,answer,ask],i)=>add(`g4eng-cover-instruction-${String(i+1).padStart(2,'0')}`,'instructions',`Read these instructions: “${text}” What is ${ask}?`,[answer,'skip every step','a different tool','never important'],answer,'Instructions must be followed in the correct order.',`The instruction says <b>${answer}</b>.`));
})();
