'use strict';
// Grade 3 History & Geography — Chapter: My Locality
// IDs: g3hi-loc-001 … g3hi-loc-075

(function () {

const CH = 'g3hi-my-locality';

STATIC_QUESTIONS.push(

  // ── buildings_places ───────────────────────────────────────────────────────

  makeMCQ({ id:'g3hi-loc-001', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A place where people go to pray is called a ___.',
    options:['Place of worship','Market','Hospital','Library'],
    answer:'Place of worship',
    hint:'Think of temples, mosques, churches and pagodas.',
    explanation:'A <b>place of worship</b> is where people go to pray. In Mauritius, these include temples, mosques, churches and pagodas.' }),

  makeMCQ({ id:'g3hi-loc-002', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'Which building would you go to if you were sick?',
    options:['Hospital','Temple','School','Supermarket'],
    answer:'Hospital',
    hint:'Doctors and nurses work in this building.',
    explanation:'A <b>hospital</b> is where you go when you are sick. Doctors and nurses take care of patients there.' }),

  makeMCQ({ id:'g3hi-loc-003', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A monument is built to ___.',
    options:['Remember an important person or event','Sell things','Cook food','Play sport'],
    answer:'Remember an important person or event',
    hint:'Monuments are put in public places so people never forget.',
    explanation:'A <b>monument</b> is built to remember and honour an important person or historical event.' }),

  makeMCQ({ id:'g3hi-loc-004', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'Where do children go to learn every day?',
    options:['School','Hospital','Market','Library'],
    answer:'School',
    hint:'This building has classrooms, teachers and pupils.',
    explanation:'Children go to <b>school</b> every day to learn with their teachers.' }),

  makeMCQ({ id:'g3hi-loc-005', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A library is a place where you can ___.',
    options:['Borrow and read books','Buy food','See a doctor','Play football'],
    answer:'Borrow and read books',
    hint:'Libraries have shelves and shelves of books.',
    explanation:'A <b>library</b> is a place where people can borrow and read books for free.' }),

  makeMCQ({ id:'g3hi-loc-006', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A market is a place where people go to ___.',
    options:['Buy and sell food and goods','Pray','Study','Get medicine'],
    answer:'Buy and sell food and goods',
    hint:'Markets are busy places with stalls full of things to buy.',
    explanation:'A <b>market</b> is where people buy and sell food and other goods. Port Louis Central Market is famous in Mauritius.' }),

  makeMCQ({ id:'g3hi-loc-007', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A Hindu temple in Mauritius is called a ___.',
    options:['Kovil or mandir','Mosque','Church','Pagoda'],
    answer:'Kovil or mandir',
    hint:'Hindu places of worship have special names.',
    explanation:'Hindu temples are called <b>kovils or mandirs</b>. Muslims pray in mosques; Christians in churches; Chinese in pagodas.' }),

  makeMCQ({ id:'g3hi-loc-008', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'Which building in your locality helps keep people safe?',
    options:['Police station','Temple','Cinema','Restaurant'],
    answer:'Police station',
    hint:'Police officers work here to protect the community.',
    explanation:'A <b>police station</b> is where police officers work to keep the community safe.' }),

  makeMCQ({ id:'g3hi-loc-009', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'Where would you go to post a letter or parcel in Mauritius?',
    options:['Post office','Hospital','Library','School'],
    answer:'Post office',
    hint:'This building handles letters and packages.',
    explanation:'A <b>post office</b> is where you post letters and parcels. Mauritius has post offices in every town.' }),

  makeMCQ({ id:'g3hi-loc-010', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A mosque is a place of worship for ___ people.',
    options:['Muslim','Hindu','Christian','Buddhist'],
    answer:'Muslim',
    hint:'Muslims pray five times a day and visit this building.',
    explanation:'A <b>mosque</b> is a place of worship for Muslim people. Mauritius has many beautiful mosques.' }),

  makeMCQ({ id:'g3hi-loc-011', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'Which of these buildings is found in EVERY locality in Mauritius?',
    options:['A school','A cinema','An airport','A stadium'],
    answer:'A school',
    hint:'Every community needs a place for children to learn.',
    explanation:'Every locality in Mauritius has a <b>school</b> so all children can get an education nearby.' }),

  makeMCQ({ id:'g3hi-loc-012', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A pharmacy is a shop where you can get ___.',
    options:['Medicine','Books','Food','Clothes'],
    answer:'Medicine',
    hint:'This shop is run by a pharmacist.',
    explanation:'A <b>pharmacy</b> is where you buy medicine. A pharmacist works there to help people.' }),

  makeMCQ({ id:'g3hi-loc-013', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'Which Mauritian building is an important historical monument?',
    options:['Aapravasi Ghat in Port Louis','A new shopping mall','A petrol station','A modern flat'],
    answer:'Aapravasi Ghat in Port Louis',
    hint:'This UNESCO World Heritage Site is connected to indentured labourers.',
    explanation:'<b>Aapravasi Ghat</b> in Port Louis is a UNESCO World Heritage Site where indentured labourers first arrived in Mauritius.' }),

  makeMCQ({ id:'g3hi-loc-014', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A church is a place of worship for ___ people.',
    options:['Christian','Muslim','Hindu','Buddhist'],
    answer:'Christian',
    hint:'Christians celebrate Christmas and Easter here.',
    explanation:'A <b>church</b> is where Christian people worship. There are many churches across Mauritius.' }),

  makeMCQ({ id:'g3hi-loc-015', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A town hall is an important building in a locality because ___.',
    options:['It is where local government works and meetings are held','It is where children play','It sells food','It is a hospital'],
    answer:'It is where local government works and meetings are held',
    hint:'The town hall is the centre of local government.',
    explanation:'A <b>town hall</b> is an important public building where local government meets and community events are held.' }),

  makeMCQ({ id:'g3hi-loc-016', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'Which building would a sick animal be taken to?',
    options:['Veterinary clinic','Hospital','School','Library'],
    answer:'Veterinary clinic',
    hint:'A vet is the doctor for animals.',
    explanation:'A <b>veterinary clinic</b> (vet) is where sick animals are taken for treatment.' }),

  makeMCQ({ id:'g3hi-loc-017', chapterId:CH, difficulty:1, subsection:'buildings_places',
    question:'A pagoda is a place of worship for ___ people in Mauritius.',
    options:['Chinese','Muslim','Christian','Hindu'],
    answer:'Chinese',
    hint:'Pagodas are found in Chinese communities in Mauritius.',
    explanation:'A <b>pagoda</b> is a Chinese place of worship. Chinese Mauritians celebrate their religion and culture there.' }),

  // ── changes_locality ───────────────────────────────────────────────────────

  makeMCQ({ id:'g3hi-loc-018', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Long ago, people used ___ to travel around Mauritius.',
    options:['Horses and carts','Aeroplanes','Electric cars','Motorbikes'],
    answer:'Horses and carts',
    hint:'Before engines were invented, animals helped people travel.',
    explanation:'In the past, Mauritians used <b>horses and carts</b> to travel. Cars and buses came later.' }),

  makeMCQ({ id:'g3hi-loc-019', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Which of these is a NEW way of doing things that did NOT exist long ago?',
    options:['Using a smartphone','Carrying water in clay pots','Riding a horse','Cooking on a wood fire'],
    answer:'Using a smartphone',
    hint:'Smartphones were only invented in recent years.',
    explanation:'<b>Smartphones</b> are a modern invention. Long ago, people had no phones at all.' }),

  makeMCQ({ id:'g3hi-loc-020', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Long ago, houses in Mauritius were mostly built from ___.',
    options:['Wood and straw','Concrete and glass','Plastic and metal','Bricks and tiles only'],
    answer:'Wood and straw',
    hint:'Before modern building materials, people used what nature provided.',
    explanation:'In the past, most Mauritian homes were built from <b>wood and straw (thatch)</b>. Modern concrete houses came later.' }),

  makeMCQ({ id:'g3hi-loc-021', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Which of these means of transport is MODERN?',
    options:['A bus','A horse and cart','A bullock cart','A canoe only'],
    answer:'A bus',
    hint:'Buses use engines and fuel — they are modern machines.',
    explanation:'A <b>bus</b> is a modern form of transport using an engine. Horse carts and bullock carts were used in the past.' }),

  makeMCQ({ id:'g3hi-loc-022', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Long ago, children played with ___ toys.',
    options:['Handmade wooden toys','Electronic game consoles','Plastic action figures','Battery-powered toys'],
    answer:'Handmade wooden toys',
    hint:'Before factories made plastic toys, people made them by hand.',
    explanation:'In the past, children played with <b>handmade wooden toys</b>. Electronic and plastic toys are modern inventions.' }),

  makeMCQ({ id:'g3hi-loc-023', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'What has changed about the way we light our homes?',
    options:['We use electric lights now instead of oil lamps','Nothing has changed','We use fire now instead of candles','We use candles now instead of electric lights'],
    answer:'We use electric lights now instead of oil lamps',
    hint:'Think about how homes were lit before electricity.',
    explanation:'In the past, homes used oil lamps and candles. Today we use <b>electric lights</b>.' }),

  makeMCQ({ id:'g3hi-loc-024', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Long ago, sugar cane was cut in Mauritius by ___.',
    options:['Workers using machetes by hand','Machines','Robots','Computers'],
    answer:'Workers using machetes by hand',
    hint:'Before machines, all farm work was done by people.',
    explanation:'In the past, sugar cane in Mauritius was cut <b>by hand using machetes</b>. Today machines do much of this work.' }),

  makeMCQ({ id:'g3hi-loc-025', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'How has communication changed from the past to the present?',
    options:['We now use phones and the internet instead of only letters','We now use letters instead of phones','Nothing has changed','People stopped communicating'],
    answer:'We now use phones and the internet instead of only letters',
    hint:'Think about how people sent messages long ago.',
    explanation:'In the past, people sent <b>handwritten letters</b>. Today we use phones, email and social media.' }),

  makeMCQ({ id:'g3hi-loc-026', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Long ago, Mauritians fetched water from ___.',
    options:['Rivers and wells','Supermarkets','Plastic bottles','Taps and pipes'],
    answer:'Rivers and wells',
    hint:'Before water pipes were put in, people got water from natural sources.',
    explanation:'In the past, Mauritians collected water from <b>rivers and wells</b>. Today we have pipes and taps at home.' }),

  makeMCQ({ id:'g3hi-loc-027', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Which of these was NOT found in a Mauritian locality long ago?',
    options:['A shopping mall','A market','A temple','A school'],
    answer:'A shopping mall',
    hint:'Shopping malls are modern buildings that appeared recently.',
    explanation:'<b>Shopping malls</b> are a modern invention. In the past, people bought things at local markets.' }),

  makeMCQ({ id:'g3hi-loc-028', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Long ago, fishing boats in Mauritius were powered by ___.',
    options:['Wind and sails or oars','Petrol engines','Electricity','Steam'],
    answer:'Wind and sails or oars',
    hint:'Before engines, the sea and wind helped fishers move their boats.',
    explanation:'In the past, fishing boats used <b>wind and sails or oars</b>. Modern boats have petrol engines.' }),

  makeMCQ({ id:'g3hi-loc-029', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'How has schooling changed from long ago to today?',
    options:['Children now have books, computers and better schools','Schools have become worse','Children no longer go to school','Nothing has changed'],
    answer:'Children now have books, computers and better schools',
    hint:'Think about what schools look like today compared to the past.',
    explanation:'Today Mauritian schools have <b>books, computers and modern facilities</b>. Long ago, many children had very few resources.' }),

  makeMCQ({ id:'g3hi-loc-030', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Which is an example of a CHANGE in leisure activities from the past to the present?',
    options:['Children now play video games instead of only outdoor games','Children no longer play any games','Sports were invented recently','Nothing has changed'],
    answer:'Children now play video games instead of only outdoor games',
    hint:'Think about what children do in their free time today versus long ago.',
    explanation:'In the past, children only played outdoor games. Today, many children also play <b>video games</b> — a modern leisure activity.' }),

  makeMCQ({ id:'g3hi-loc-031', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Which type of transport helped Mauritius grow sugarcane long ago by moving it across fields?',
    options:['Ox carts and mule trains','Lorries and trucks','Electric trains','Aeroplanes'],
    answer:'Ox carts and mule trains',
    hint:'Oxen and mules are animals that pulled heavy loads.',
    explanation:'<b>Ox carts and mule trains</b> were used on Mauritian sugar estates to move sugar cane. Lorries replaced them later.' }),

  makeMCQ({ id:'g3hi-loc-032', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Long ago, Mauritian women washed clothes at ___.',
    options:['Riverside washing spots or by hand at home','Laundromats with machines','Modern washing machines','Dry-cleaning shops'],
    answer:'Riverside washing spots or by hand at home',
    hint:'Before washing machines, people washed clothes by hand near water.',
    explanation:'In the past, clothes were washed <b>by hand at riverside washing spots</b>. Washing machines are modern inventions.' }),

  makeMCQ({ id:'g3hi-loc-033', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'Which of these is an example of how roads have changed in Mauritius?',
    options:['Roads are now paved with tar and have traffic lights','Roads are now made of sand only','Roads have become smaller','Roads no longer exist'],
    answer:'Roads are now paved with tar and have traffic lights',
    hint:'Think about how roads look today compared to long ago.',
    explanation:'Modern roads in Mauritius are <b>paved with tar and have traffic lights</b>. Long ago, many roads were just dirt tracks.' }),

  makeMCQ({ id:'g3hi-loc-034', chapterId:CH, difficulty:1, subsection:'changes_locality',
    question:'What do we call changes that happen in a locality over time?',
    options:['Development','Destruction','Disaster','Nothing'],
    answer:'Development',
    hint:'When a place grows and improves, we call it this.',
    explanation:'<b>Development</b> means positive changes over time — new buildings, roads and services appearing in a locality.' }),

  // ── preserving_heritage ────────────────────────────────────────────────────

  makeMCQ({ id:'g3hi-loc-035', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'We should protect old buildings because ___.',
    options:['They are part of our history and heritage','They are new','They are cheap to build','They are made of plastic'],
    answer:'They are part of our history and heritage',
    hint:'Old buildings tell the story of our past.',
    explanation:'Old buildings are <b>part of our history and heritage</b>. They tell us how people lived in the past.' }),

  makeMCQ({ id:'g3hi-loc-036', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'A museum helps us to ___.',
    options:['Learn about the past by seeing old objects','Buy new things','Play games','Grow plants'],
    answer:'Learn about the past by seeing old objects',
    hint:'Museums display old objects and tell their stories.',
    explanation:'A <b>museum</b> displays old objects and artworks so people can learn about the past.' }),

  makeMCQ({ id:'g3hi-loc-037', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'The word "heritage" means ___.',
    options:['Things from the past that we pass on to the future','New buildings and roads','Rubbish and waste','School subjects'],
    answer:'Things from the past that we pass on to the future',
    hint:'Heritage is something we inherit from those who came before us.',
    explanation:'<b>Heritage</b> includes the traditions, buildings and history we receive from the past and pass on to future generations.' }),

  makeMCQ({ id:'g3hi-loc-038', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Aapravasi Ghat is important because ___.',
    options:['It is where indentured labourers first arrived in Mauritius','It is a new shopping centre','It is a modern school','It is a sports stadium'],
    answer:'It is where indentured labourers first arrived in Mauritius',
    hint:'Aapravasi Ghat is a UNESCO World Heritage Site.',
    explanation:'<b>Aapravasi Ghat</b> is where thousands of indentured labourers arrived to work in Mauritius — a very important part of our history.' }),

  makeMCQ({ id:'g3hi-loc-039', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Le Morne Cultural Landscape is important because ___.',
    options:['It is linked to the history of enslaved people who sought freedom','It is a new holiday resort','It is a modern building','It is a shopping centre'],
    answer:'It is linked to the history of enslaved people who sought freedom',
    hint:'Le Morne is a UNESCO World Heritage Site with a powerful history.',
    explanation:'<b>Le Morne</b> is a UNESCO World Heritage Site connected to the history of enslaved people who sought refuge there.' }),

  makeMCQ({ id:'g3hi-loc-040', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'What does UNESCO do for important historical sites?',
    options:['It gives them World Heritage status to protect them','It builds new roads over them','It pulls them down','It sells them'],
    answer:'It gives them World Heritage status to protect them',
    hint:'UNESCO is a world organisation that helps protect important places.',
    explanation:'<b>UNESCO</b> gives World Heritage status to important sites to protect them for future generations.' }),

  makeMCQ({ id:'g3hi-loc-041', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Why should we NOT pull down old historical buildings?',
    options:['We would lose important parts of our history forever','They are not useful','They are too big','They are too expensive to keep'],
    answer:'We would lose important parts of our history forever',
    hint:'Once a building is destroyed, it cannot be rebuilt exactly.',
    explanation:'If we destroy old buildings, we lose <b>important parts of our history forever</b>. They cannot be perfectly replaced.' }),

  makeMCQ({ id:'g3hi-loc-042', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Who has the job of looking after historical buildings in Mauritius?',
    options:['The government and local communities','Nobody','Only tourists','Only children'],
    answer:'The government and local communities',
    hint:'Protecting heritage is a shared responsibility.',
    explanation:'The <b>government and local communities</b> share the responsibility of protecting and maintaining historical buildings.' }),

  makeMCQ({ id:'g3hi-loc-043', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Visiting a historical site helps children to ___.',
    options:['Understand and appreciate their history','Get bored','Learn nothing','Waste time'],
    answer:'Understand and appreciate their history',
    hint:'Seeing the real place brings history to life.',
    explanation:'Visiting historical sites helps children <b>understand and appreciate their history</b> in a real and meaningful way.' }),

  makeMCQ({ id:'g3hi-loc-044', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Which of these is an example of cultural heritage in Mauritius?',
    options:['The sega dance and music','A new fast-food restaurant','A modern car park','A plastic bag'],
    answer:'The sega dance and music',
    hint:'Cultural heritage includes traditional music, dance and customs.',
    explanation:'<b>Sega</b> is a traditional Mauritian dance and music form — an important part of our cultural heritage.' }),

  makeMCQ({ id:'g3hi-loc-045', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Preserving old objects in a museum means ___.',
    options:['Keeping them safe so future generations can see them','Throwing them away','Selling them abroad','Breaking them apart'],
    answer:'Keeping them safe so future generations can see them',
    hint:'The purpose of preservation is to protect something for the future.',
    explanation:'Preserving objects means <b>keeping them safe</b> so that future children and adults can learn from them.' }),

  makeMCQ({ id:'g3hi-loc-046', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Which action DESTROYS our heritage?',
    options:['Painting graffiti on a historical monument','Visiting a museum','Cleaning a monument','Photographing an old building'],
    answer:'Painting graffiti on a historical monument',
    hint:'Damaging monuments removes their historical value.',
    explanation:'<b>Painting graffiti</b> on historical monuments damages and destroys our shared heritage.' }),

  makeMCQ({ id:'g3hi-loc-047', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Old traditional Mauritian crafts like basket-weaving are part of our ___.',
    options:['Cultural heritage','Modern inventions','School curriculum','Science experiments'],
    answer:'Cultural heritage',
    hint:'Traditional crafts passed down through generations are cultural treasure.',
    explanation:'Traditional crafts like <b>basket-weaving</b> are part of Mauritius\'s cultural heritage — skills passed from generation to generation.' }),

  makeMCQ({ id:'g3hi-loc-048', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'A story passed down from grandparents to grandchildren is called an ___.',
    options:['Oral tradition','Exam question','Shopping list','Science experiment'],
    answer:'Oral tradition',
    hint:'"Oral" means spoken. This tradition is passed on by speaking, not writing.',
    explanation:'<b>Oral traditions</b> are stories, songs and knowledge passed down by speaking from one generation to the next.' }),

  makeMCQ({ id:'g3hi-loc-049', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'The Blue Penny Museum in Port Louis preserves ___.',
    options:['Rare stamps and historical artefacts of Mauritius','New smartphones','Modern art only','Sports trophies'],
    answer:'Rare stamps and historical artefacts of Mauritius',
    hint:'This museum has one of Mauritius\'s most valuable treasures.',
    explanation:'The <b>Blue Penny Museum</b> in Port Louis displays rare Mauritian stamps and important historical artefacts.' }),

  makeMCQ({ id:'g3hi-loc-050', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Why is it important for children to learn about their community\'s history?',
    options:['So they understand where they come from and can protect their heritage','It is not important','History is boring','It is only for adults'],
    answer:'So they understand where they come from and can protect their heritage',
    hint:'Knowing your history helps you appreciate who you are.',
    explanation:'Learning about history helps children <b>understand their identity and take pride in protecting their heritage</b>.' }),

  makeMCQ({ id:'g3hi-loc-051', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'The story of Robert Edward Hart is an example of someone from ___.',
    options:['The past who contributed to Mauritius','The future','Another country','A foreign history'],
    answer:'The past who contributed to Mauritius',
    hint:'Robert Edward Hart was an important Mauritian poet.',
    explanation:'<b>Robert Edward Hart</b> was a famous Mauritian poet from the past whose home is preserved as a museum in Souillac.' }),

  makeMCQ({ id:'g3hi-loc-052', chapterId:CH, difficulty:1, subsection:'preserving_heritage',
    question:'Which is an example of a NATURAL heritage site in Mauritius?',
    options:['Black River Gorges National Park','A shopping mall','A block of flats','A petrol station'],
    answer:'Black River Gorges National Park',
    hint:'This is a protected forest with endemic animals and plants.',
    explanation:'<b>Black River Gorges National Park</b> is a natural heritage site protecting Mauritius\'s endemic species and forests.' })

);
})();
