'use strict';
// Grade 3 History & Geography — Chapter: Map Skills
// IDs: g3hi-map-001 … g3hi-map-075

(function () {

const CH = 'g3hi-map-skills';

STATIC_QUESTIONS.push(

  // ── map_features ───────────────────────────────────────────────────────────

  makeMCQ({ id:'g3hi-map-001', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'A map shows us ___.',
    options:['Where places are and what they look like from above','What the weather is today','Who lives in each house','When events happened'],
    answer:'Where places are and what they look like from above',
    hint:'Imagine looking down at the land from high up in the sky.',
    explanation:'A <b>map</b> is a flat picture showing where places are, seen from directly above.' }),

  makeMCQ({ id:'g3hi-map-002', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'On a map, a blue shape or line often shows ___.',
    options:['Water — a river, lake or sea','A road','A forest','A building'],
    answer:'Water — a river, lake or sea',
    hint:'Blue is the colour of water.',
    explanation:'On maps, <b>blue</b> shows water — rivers, lakes, lagoons and the sea.' }),

  makeMCQ({ id:'g3hi-map-003', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'The TITLE of a map tells us ___.',
    options:['What area or place the map shows','How far away places are','The weather','Who drew the map'],
    answer:'What area or place the map shows',
    hint:'A title is a name that tells you what something is about.',
    explanation:'The <b>title</b> of a map tells us what place or area is shown on that map.' }),

  makeMCQ({ id:'g3hi-map-004', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'A KEY or LEGEND on a map tells us ___.',
    options:['What each symbol or colour means','The name of the map maker','The weather','The date the map was made'],
    answer:'What each symbol or colour means',
    hint:'A key is like a code-breaker for the map.',
    explanation:'A map <b>key (or legend)</b> explains what each symbol, colour and line means on the map.' }),

  makeMCQ({ id:'g3hi-map-005', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'On a map, green areas usually show ___.',
    options:['Forests, parks or low land','Water','Roads','Buildings'],
    answer:'Forests, parks or low land',
    hint:'Green is the colour of trees and grass.',
    explanation:'On maps, <b>green</b> usually shows forests, parks, fields or lower land areas.' }),

  makeMCQ({ id:'g3hi-map-006', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'What does a COMPASS ROSE on a map show?',
    options:['The four directions — North, South, East and West','The names of towns','The scale of the map','The colours used'],
    answer:'The four directions — North, South, East and West',
    hint:'It looks like a star pointing in four directions.',
    explanation:'A <b>compass rose</b> shows the four main directions: North (N), South (S), East (E) and West (W).' }),

  makeMCQ({ id:'g3hi-map-007', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'On a compass, NORTH is usually at the ___.',
    options:['Top','Bottom','Left','Right'],
    answer:'Top',
    hint:'Maps are usually drawn with north pointing upward.',
    explanation:'By convention, maps are drawn with <b>North at the top</b> and South at the bottom.' }),

  makeMCQ({ id:'g3hi-map-008', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'A SCALE on a map helps us understand ___.',
    options:['The real distance between places','The colours used','The names of rivers','The weather'],
    answer:'The real distance between places',
    hint:'A scale tells you how many kilometres one centimetre on the map represents.',
    explanation:'A map <b>scale</b> tells us how real distances on the ground compare to distances on the map.' }),

  makeMCQ({ id:'g3hi-map-009', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'A SYMBOL on a map is ___.',
    options:['A small picture or shape that stands for a real place or feature','A decorative drawing','A weather forecast','A number'],
    answer:'A small picture or shape that stands for a real place or feature',
    hint:'Symbols save space by standing for something real.',
    explanation:'Map <b>symbols</b> are small pictures or shapes that represent real features — like a small tree symbol for a forest.' }),

  makeMCQ({ id:'g3hi-map-010', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'On a map of Mauritius, a small square or dot usually shows ___.',
    options:['A town or village','A river','A mountain','The sea'],
    answer:'A town or village',
    hint:'Settlements are usually marked with a dot or small square.',
    explanation:'Towns and villages on maps are usually shown with a <b>dot or small square symbol</b>.' }),

  makeMCQ({ id:'g3hi-map-011', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'What is a PLAN in geography?',
    options:['A map that shows a small area from above, like a room or a school','A timetable for the day','A list of what to buy','A story about a place'],
    answer:'A map that shows a small area from above, like a room or a school',
    hint:'A plan is like a very detailed, close-up map of one small place.',
    explanation:'A <b>plan</b> is a detailed drawing of a small area seen from above — like a school plan or a room plan.' }),

  makeMCQ({ id:'g3hi-map-012', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'On a map, a line of brown triangles or shaded area usually shows ___.',
    options:['Mountains or hills','The sea','A river','A road'],
    answer:'Mountains or hills',
    hint:'Brown shading or triangles on maps represent raised land.',
    explanation:'<b>Brown triangles or shading</b> on maps show mountains and high hills.' }),

  makeMCQ({ id:'g3hi-map-013', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'Which of these would you look for FIRST when you open a new map?',
    options:['The title and the key','The colour of the paper','The back of the map','The price of the map'],
    answer:'The title and the key',
    hint:'The title tells you what the map is and the key tells you what the symbols mean.',
    explanation:'Always read the <b>title and key</b> first — they tell you what the map shows and what the symbols mean.' }),

  makeMCQ({ id:'g3hi-map-014', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'If you are standing facing north, which direction is to your RIGHT?',
    options:['East','West','South','Up'],
    answer:'East',
    hint:'If north is in front of you, east is always to your right.',
    explanation:'When facing <b>North</b>, East is to your right, West is to your left, and South is behind you.' }),

  makeMCQ({ id:'g3hi-map-015', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'On a map of Mauritius, the capital city Port Louis is located on the ___.',
    options:['North-west coast','South coast','East coast','Centre of the island'],
    answer:'North-west coast',
    hint:'Port Louis has a harbour on the western side of Mauritius.',
    explanation:'<b>Port Louis</b>, the capital of Mauritius, is located on the north-west coast, on the western side of the island.' }),

  makeMCQ({ id:'g3hi-map-016', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'A photograph taken from an aeroplane looking straight down is called an ___.',
    options:['Aerial photograph','Portrait photograph','Holiday photo','Postcard'],
    answer:'Aerial photograph',
    hint:'"Aerial" means from the air.',
    explanation:'An <b>aerial photograph</b> is taken from above — from a plane, drone or satellite looking straight down.' }),

  makeMCQ({ id:'g3hi-map-017', chapterId:CH, difficulty:1, subsection:'map_features',
    question:'On a map, a thick black or grey line usually represents ___.',
    options:['A main road or motorway','A river','The sea','A forest'],
    answer:'A main road or motorway',
    hint:'Important roads are shown with bold, clear lines on maps.',
    explanation:'<b>Thick black or grey lines</b> on maps usually show main roads or motorways.' }),

  // ── natural_landmarks ──────────────────────────────────────────────────────

  makeMCQ({ id:'g3hi-map-018', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Le Morne Brabant is a famous ___ in Mauritius.',
    options:['Mountain and UNESCO World Heritage Site','River','Beach','Forest'],
    answer:'Mountain and UNESCO World Heritage Site',
    hint:'Le Morne is a striking rocky peak visible from the south-west coast.',
    explanation:'<b>Le Morne Brabant</b> is a dramatic mountain on the south-west coast of Mauritius and a UNESCO World Heritage Site.' }),

  makeMCQ({ id:'g3hi-map-019', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Black River Gorges National Park is a natural landmark found in the ___ of Mauritius.',
    options:['South-west','North','East','Centre of Port Louis'],
    answer:'South-west',
    hint:'The national park is near the Black River district.',
    explanation:'<b>Black River Gorges National Park</b> is in the south-west of Mauritius, protecting forests and endemic wildlife.' }),

  makeMCQ({ id:'g3hi-map-020', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Chamarel Waterfall is the tallest waterfall in Mauritius. It is found in the ___ district.',
    options:['Black River (Rivière Noire)','Pamplemousses','Grand Port','Flacq'],
    answer:'Black River (Rivière Noire)',
    hint:'Chamarel village is in the Black River region.',
    explanation:'<b>Chamarel Waterfall</b> is in the Black River district — it is the tallest waterfall in Mauritius at about 100 metres.' }),

  makeMCQ({ id:'g3hi-map-021', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Blue Bay Marine Park is a protected natural landmark on the ___ coast of Mauritius.',
    options:['South-east','North-west','West','North'],
    answer:'South-east',
    hint:'Blue Bay is near Mahébourg in the south-east.',
    explanation:'<b>Blue Bay Marine Park</b> is on the south-east coast of Mauritius, near Mahébourg — famous for its coral reef.' }),

  makeMCQ({ id:'g3hi-map-022', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Grand Bassin (Ganga Talao) is a natural crater lake that is a sacred site for ___ in Mauritius.',
    options:['Hindu Mauritians','Muslim Mauritians','Christian Mauritians','Chinese Mauritians'],
    answer:'Hindu Mauritians',
    hint:'Thousands of pilgrims walk to Grand Bassin during Maha Shivaratri.',
    explanation:'<b>Grand Bassin</b> is a sacred natural lake for Hindu Mauritians. Pilgrims carry water from it during Maha Shivaratri.' }),

  makeMCQ({ id:'g3hi-map-023', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'The Seven Coloured Earths at Chamarel are located near ___.',
    options:['Chamarel Waterfall in the Black River district','Port Louis harbour','Blue Bay beach','Mahébourg market'],
    answer:'Chamarel Waterfall in the Black River district',
    hint:'Both the waterfall and the coloured earths are in the same area.',
    explanation:'The <b>Seven Coloured Earths</b> are close to Chamarel Waterfall in the Black River district — a unique geological wonder.' }),

  makeMCQ({ id:'g3hi-map-024', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Rodrigues Island is a dependency of Mauritius found to the ___ of the main island.',
    options:['East (about 560 km away)','North','South','West'],
    answer:'East (about 560 km away)',
    hint:'Rodrigues is in the same ocean but far to the east.',
    explanation:'<b>Rodrigues</b> is about 560 km east of the main island of Mauritius, in the Indian Ocean.' }),

  makeMCQ({ id:'g3hi-map-025', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Piton de la Petite Rivière Noire is the highest natural landmark in Mauritius at ___.',
    options:['828 metres','200 metres','1,500 metres','500 metres'],
    answer:'828 metres',
    hint:'This mountain is about 828 metres high.',
    explanation:'<b>Piton de la Petite Rivière Noire</b> is the highest point in Mauritius at <b>828 metres</b> above sea level.' }),

  makeMCQ({ id:'g3hi-map-026', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Mahébourg is a coastal town famous for its ___.',
    options:['Historical museum and beautiful lagoon','High mountains','Dense forest','Industrial factories'],
    answer:'Historical museum and beautiful lagoon',
    hint:'Mahébourg is a quiet, historic town by the sea.',
    explanation:'<b>Mahébourg</b> is known for its Historical Museum (linked to the 1810 Battle of Grand Port) and its stunning lagoon.' }),

  makeMCQ({ id:'g3hi-map-027', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'The Pamplemousses Botanical Garden is a famous natural and historical landmark in ___.',
    options:['The north of Mauritius','The south coast','The east coast','Rodrigues'],
    answer:'The north of Mauritius',
    hint:'Pamplemousses is in the northern part of Mauritius.',
    explanation:'<b>Pamplemousses Botanical Garden</b> is in the north of Mauritius — one of the oldest botanical gardens in the southern hemisphere.' }),

  makeMCQ({ id:'g3hi-map-028', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Corps de Garde, Trois Mamelles and Le Pouce are all ___.',
    options:['Mountain peaks in the centre of Mauritius','Beaches on the coast','Rivers in the east','Towns in the north'],
    answer:'Mountain peaks in the centre of Mauritius',
    hint:'These are well-known mountain shapes seen from Port Louis.',
    explanation:'<b>Corps de Garde, Trois Mamelles and Le Pouce</b> are mountain peaks visible from Port Louis and the central Mauritius area.' }),

  makeMCQ({ id:'g3hi-map-029', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'The coral reef that surrounds most of Mauritius creates a sheltered area of water called a ___.',
    options:['Lagoon','Mountain lake','River delta','Waterfall pool'],
    answer:'Lagoon',
    hint:'The reef acts like a barrier, protecting the shallow water inside.',
    explanation:'The coral reef around Mauritius creates a sheltered <b>lagoon</b> — calm, shallow water between the reef and the beach.' }),

  makeMCQ({ id:'g3hi-map-030', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Île aux Cerfs is a famous ___ in Mauritius.',
    options:['Island off the east coast with a beautiful beach','Mountain in the south','Waterfall in the west','Forest park in the north'],
    answer:'Island off the east coast with a beautiful beach',
    hint:'"Île" means island in French.',
    explanation:'<b>Île aux Cerfs</b> is a small island off the east coast of Mauritius with a famous beach and clear water.' }),

  makeMCQ({ id:'g3hi-map-031', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'La Vanille Nature Park in Rivière des Anguilles is famous for its ___.',
    options:['Giant Aldabra tortoises and other wildlife','High mountains','Coloured earths','Famous waterfall'],
    answer:'Giant Aldabra tortoises and other wildlife',
    hint:'This wildlife park in the south has very large reptiles.',
    explanation:'<b>La Vanille Nature Park</b> is famous for its giant Aldabra tortoises, crocodiles and other wildlife.' }),

  makeMCQ({ id:'g3hi-map-032', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Which natural landmark was used as a hiding place by enslaved people seeking freedom and is now a UNESCO site?',
    options:['Le Morne Brabant mountain','Black River Gorges','Chamarel Waterfall','Grand Bassin'],
    answer:'Le Morne Brabant mountain',
    hint:'This mountain has a very important and sad history linked to freedom.',
    explanation:'<b>Le Morne Brabant</b> was used as a refuge by enslaved people. Its history of resistance and freedom is why it is a UNESCO World Heritage Site.' }),

  makeMCQ({ id:'g3hi-map-033', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'On a map of Mauritius, Port Louis is marked with a STAR symbol because ___.',
    options:['It is the capital city','It is the tallest mountain','It is a beach','It is a river'],
    answer:'It is the capital city',
    hint:'Capital cities are often shown with a star or a special symbol.',
    explanation:'<b>Port Louis</b> has a star symbol on maps because it is the capital city of Mauritius.' }),

  makeMCQ({ id:'g3hi-map-034', chapterId:CH, difficulty:1, subsection:'natural_landmarks',
    question:'Flic en Flac is a well-known ___ on the west coast of Mauritius.',
    options:['Beach resort town','Mountain','Waterfall','Forest park'],
    answer:'Beach resort town',
    hint:'This town is known for its long white sandy beach.',
    explanation:'<b>Flic en Flac</b> is a popular beach resort town on the west coast of Mauritius, famous for its white sandy beach.' }),

  // ── safety_outdoors ────────────────────────────────────────────────────────

  makeMCQ({ id:'g3hi-map-035', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'If you are near a waterfall, you should ___.',
    options:['Stay away from the edge and behind safety barriers','Jump in for fun','Run towards the edge to see better','Ignore warning signs'],
    answer:'Stay away from the edge and behind safety barriers',
    hint:'Waterfall edges are wet and slippery — very dangerous.',
    explanation:'Near a waterfall, always <b>stay behind barriers and away from the edge</b>. Wet rocks are extremely slippery and falls are fatal.' }),

  makeMCQ({ id:'g3hi-map-036', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'Why should we NOT swim in rivers or waterfalls in Mauritius?',
    options:['The water can be fast-moving and dangerous, with hidden rocks and strong currents','The water is too cold','There are no fish','It is not allowed on weekdays only'],
    answer:'The water can be fast-moving and dangerous, with hidden rocks and strong currents',
    hint:'Rivers look calm on the surface but can have strong currents below.',
    explanation:'Rivers and waterfalls in Mauritius have <b>fast currents, hidden rocks and sudden depth changes</b> — swimming in them is very dangerous.' }),

  makeMCQ({ id:'g3hi-map-037', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'Which of these is a warning sign you might see near a beach or waterfall?',
    options:['A red flag or "No Swimming" sign','A green flag','A yellow smiley face','A blue star'],
    answer:'A red flag or "No Swimming" sign',
    hint:'Red means danger or stop.',
    explanation:'A <b>red flag or "No Swimming" sign</b> warns that the water is dangerous. Always obey these signs.' }),

  makeMCQ({ id:'g3hi-map-038', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'Before going to a forest or nature park, you should ___.',
    options:['Tell an adult where you are going and stay on marked paths','Go alone without telling anyone','Run off the path into the forest','Leave all safety information at home'],
    answer:'Tell an adult where you are going and stay on marked paths',
    hint:'Always let someone know where you are when exploring nature.',
    explanation:'Always <b>tell an adult your plans and stay on marked paths</b> in forests. Getting lost in dense forest can be very dangerous.' }),

  makeMCQ({ id:'g3hi-map-039', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'At the seaside, why should you swim in designated swimming areas?',
    options:['They are safe zones with lifeguards and no dangerous currents','They are deeper and more exciting','They are further from the beach','They have no other swimmers'],
    answer:'They are safe zones with lifeguards and no dangerous currents',
    hint:'Lifeguards watch over designated swimming areas.',
    explanation:'<b>Designated swimming areas</b> at Mauritian beaches are monitored by lifeguards and chosen for their safe conditions.' }),

  makeMCQ({ id:'g3hi-map-040', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'A rip current is ___.',
    options:['A powerful, fast-moving channel of water that pulls swimmers away from shore','A gentle wave','A type of fish','A calm area of sea'],
    answer:'A powerful, fast-moving channel of water that pulls swimmers away from shore',
    hint:'Rip currents are invisible channels of water that rush out to sea.',
    explanation:'A <b>rip current</b> is a dangerous channel of fast-moving water that can pull swimmers rapidly away from the beach.' }),

  makeMCQ({ id:'g3hi-map-041', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'When hiking in Black River Gorges, you should always ___.',
    options:['Carry water, wear proper shoes and stay on marked trails','Walk barefoot for better grip','Drop litter to mark your path','Go alone without a map'],
    answer:'Carry water, wear proper shoes and stay on marked trails',
    hint:'Prepared hikers are safe hikers.',
    explanation:'Safe hiking requires <b>carrying water, wearing proper footwear and staying on marked trails</b> to avoid getting lost.' }),

  makeMCQ({ id:'g3hi-map-042', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'Which colour flag at a Mauritian beach means it is SAFE to swim?',
    options:['Green','Red','Black','Orange'],
    answer:'Green',
    hint:'Green means go — it is safe.',
    explanation:'A <b>green flag</b> on a Mauritian beach means conditions are safe for swimming. Red means danger — do not enter the water.' }),

  makeMCQ({ id:'g3hi-map-043', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'Why is it dangerous to stand too close to a waterfall in the rain?',
    options:['The ground around the falls becomes very slippery and flooding can occur suddenly','The water is too cold','There are sharks in waterfalls','It is not dangerous at all'],
    answer:'The ground around the falls becomes very slippery and flooding can occur suddenly',
    hint:'Rain makes wet rocks even more slippery and raises water levels quickly.',
    explanation:'In rain, the ground near waterfalls becomes <b>extremely slippery</b> and water levels can rise suddenly, sweeping people in.' }),

  makeMCQ({ id:'g3hi-map-044', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'If you get lost in a forest or on a trail, you should ___.',
    options:['Stay calm, stay in one place and shout for help','Run in all directions to find your way','Climb a tree','Keep walking deeper into the forest'],
    answer:'Stay calm, stay in one place and shout for help',
    hint:'Moving around when lost makes it harder for rescuers to find you.',
    explanation:'If lost, <b>stay calm, stay put and call for help</b>. It is much easier for rescuers to find someone who has stayed in one place.' }),

  makeMCQ({ id:'g3hi-map-045', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'Why should you never climb on rocks at the edge of cliffs in Mauritius?',
    options:['Rocks can be loose and crumble, and a fall from a cliff is fatal','Rocks are always safe to climb','Cliffs are not high in Mauritius','There are no cliffs in Mauritius'],
    answer:'Rocks can be loose and crumble, and a fall from a cliff is fatal',
    hint:'Cliff edges are very dangerous — one slip can be fatal.',
    explanation:'<b>Cliff-edge rocks can be loose and crumbly</b>. A fall from a cliff is extremely serious and often fatal.' }),

  makeMCQ({ id:'g3hi-map-046', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'What should you do if you see someone else in danger in the sea?',
    options:['Call for a lifeguard or adult immediately and do NOT jump in yourself','Jump in immediately to save them yourself','Watch and do nothing','Walk away'],
    answer:'Call for a lifeguard or adult immediately and do NOT jump in yourself',
    hint:'Untrained swimmers who jump in often become victims themselves.',
    explanation:'If someone is in danger in the sea, <b>call a lifeguard or adult immediately</b>. Do not jump in — you could become a victim too.' }),

  makeMCQ({ id:'g3hi-map-047', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'Which piece of safety equipment should be worn when going on a boat in Mauritius?',
    options:['A life jacket','A sun hat only','Sunglasses only','Nothing — boats are always safe'],
    answer:'A life jacket',
    hint:'A life jacket keeps you floating if you fall into the water.',
    explanation:'A <b>life jacket</b> is essential on a boat — it keeps you afloat if you fall overboard, even if you cannot swim.' }),

  makeMCQ({ id:'g3hi-map-048', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'In Mauritius, coral reefs should be protected by swimmers who ___.',
    options:['Do not stand on or touch the coral','Break off pieces as souvenirs','Walk across the reef in shoes','Drag anchors over the reef'],
    answer:'Do not stand on or touch the coral',
    hint:'Coral is alive and very fragile.',
    explanation:'Coral is a <b>living organism</b> that takes decades to grow. Standing on or touching it kills it — always swim above, never on, the reef.' }),

  makeMCQ({ id:'g3hi-map-049', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'What should you always carry when exploring outdoor areas in Mauritius?',
    options:['Drinking water, a phone and sunscreen','Only a snack','A television','Nothing extra'],
    answer:'Drinking water, a phone and sunscreen',
    hint:'You need to stay hydrated, connected and protected from the sun.',
    explanation:'Always carry <b>drinking water, a phone (for emergencies) and sunscreen</b> when exploring outdoor areas in Mauritius\'s tropical heat.' }),

  makeMCQ({ id:'g3hi-map-050', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'Warning signs in nature areas are there to ___.',
    options:['Keep you safe by warning you of dangers','Make the place look pretty','Tell you where to buy things','Give directions to the beach'],
    answer:'Keep you safe by warning you of dangers',
    hint:'Signs warn us before we reach a danger.',
    explanation:'<b>Warning signs</b> in nature areas alert visitors to real dangers — always read and follow them for your own safety.' }),

  makeMCQ({ id:'g3hi-map-051', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'When exploring natural areas, why should you stay on the PATH?',
    options:['To avoid getting lost, damaging plants and disturbing wildlife','Because it is easier to run on','Because it is the shortest route','Paths are compulsory by law only'],
    answer:'To avoid getting lost, damaging plants and disturbing wildlife',
    hint:'Paths protect both you and the environment.',
    explanation:'Staying on paths <b>prevents you from getting lost</b>, protects fragile plants from being trampled and avoids disturbing wildlife.' }),

  makeMCQ({ id:'g3hi-map-052', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'In Mauritius, the sea can be rough and dangerous on the WINDWARD side of the island, which is the ___ side.',
    options:['East','West','North','South'],
    answer:'East',
    hint:'The south-east trade winds blow onto the east coast of Mauritius.',
    explanation:'The <b>east coast</b> of Mauritius faces the prevailing trade winds and often has rougher seas than the calmer west coast.' }),

  makeMCQ({ id:'g3hi-map-053', chapterId:CH, difficulty:1, subsection:'safety_outdoors',
    question:'A good outdoor explorer in Mauritius always ___.',
    options:['Plans ahead, tells someone where they are going and respects nature','Goes alone with no preparation','Leaves rubbish in the forest','Ignores warning signs'],
    answer:'Plans ahead, tells someone where they are going and respects nature',
    hint:'Planning ahead keeps you safe and protects the environment.',
    explanation:'A <b>responsible and safe outdoor explorer</b> plans their trip, informs someone, follows signs and respects the natural environment.' })

);
})();
