'use strict';
(function () {
STATIC_QUESTIONS.push(

  makeMCQ({ id:'g7sms-hd-001', chapterId:'g7sms-islands', subsection:'islands_republic', difficulty:4,
    question:'A pupil draws a map for a project, shows only the main island, and labels it \'The Republic of Mauritius\'.<br>What is the main problem with that label?',
    options:['Rodrigues, Agalega and St Brandon are also part of the Republic','The Republic is made up of the main island alone, so the map is complete','The main island should have been drawn much larger than it really is','A republic cannot be shown on a map, only on a flag'],
    answer:'Rodrigues, Agalega and St Brandon are also part of the Republic',
    hint:'Count the islands the Republic is made of, not the one most people live on.',
    explanation:'The Republic is a group of islands spread across hundreds of kilometres, so a map showing only the main island is missing <b>Rodrigues, Agalega and St Brandon</b>. Saying the main island alone is the whole Republic is exactly the error being made.' }),

  makeMCQ({ id:'g7sms-hd-002', chapterId:'g7sms-islands', subsection:'islands_republic', difficulty:4,
    question:'Rodrigues lies about 560 km east of the main island. A patient there cannot be sent to Port Louis within the hour, and a load of building sand cannot arrive the same afternoon.<br>What does that distance mean for how the Republic must be run?',
    options:['Rodrigues needs services of its own rather than daily links to the main island','Rodrigues can rely on the main island, because 560 km is a short sea crossing','Distance makes no difference once two places share the same government','Rodrigues should be governed by whichever country lies nearest to it'],
    answer:'Rodrigues needs services of its own rather than daily links to the main island',
    hint:'Ask what cannot be delivered in a day, then ask who must supply it instead.',
    explanation:'560 km of open sea rules out same-day supply, so hospitals, stores and workshops must exist <b>on Rodrigues itself</b>. Treating the crossing as short ignores the very problem in the question.' }),

  makeMCQ({ id:'g7sms-hd-003', chapterId:'g7sms-islands', subsection:'islands_republic', difficulty:3,
    question:'The Republic has a small land area, yet controls one of the largest areas of sea in the region.<br>Which fact best explains that?',
    options:['Its islands are scattered widely, and each one extends the sea zone','Its islands lie close together, which concentrates the sea zone around them','A country\'s sea zone is fixed by its population, not by its islands','The sea is very deep around the islands, which makes the zone larger'],
    answer:'Its islands are scattered widely, and each one extends the sea zone',
    hint:'The zone is measured outwards from land — so count how much land there is to measure from.',
    explanation:'A sea zone is drawn outwards from each island. Because Rodrigues, Agalega and St Brandon lie far apart, the zones add up to a <b>huge maritime area</b>. Islands packed close together would overlap and give far less.' }),

  makeMCQ({ id:'g7sms-hd-004', chapterId:'g7sms-islands', subsection:'islands_republic', difficulty:4,
    question:'Ashvin says the Republic is a very small country. Neha says it controls an enormous territory.<br>Who is right?',
    options:['Both are: the land is small, while the sea zone it controls is vast','Only Neha, because the sea counts and land area is never worth measuring','Only Ashvin, because a country is measured by its land area alone','Neither, because a country cannot be measured in area at all'],
    answer:'Both are: the land is small, while the sea zone it controls is vast',
    hint:'Two people can both be right if they are measuring two different things.',
    explanation:'They are measuring different things. The land is tiny, the <b>maritime zone</b> is one of the largest in the region — so both statements hold. Saying land area is never worth measuring goes too far the other way.' }),

  makeMCQ({ id:'g7sms-hd-005', chapterId:'g7sms-islands', subsection:'island_types', difficulty:4,
    question:'A survey team lands on an island of the Republic. They find white coral sand, no rock hills, a highest point a few metres above the sea, and no springs or streams anywhere.<br>What can they safely conclude?',
    options:['It is a low coral island, so fresh water must be caught or shipped in','It is a volcanic island whose mountains have simply not formed yet, so rock will appear later','It is a coral island, and so it must have deep and fertile volcanic soils','It is too small for any conclusion about its rocks to be drawn'],
    answer:'It is a low coral island, so fresh water must be caught or shipped in',
    hint:'Two clues: what the ground is made of, and what is missing from it.',
    explanation:'Coral sand with no high rock and no streams describes a <b>low coral island</b>. Rain sinks straight through coral sand, so water has to be collected in tanks or brought by ship. Volcanic mountains do not appear later — they are there from the start or not at all.' }),

  makeMCQ({ id:'g7sms-hd-006', chapterId:'g7sms-islands', subsection:'island_types', difficulty:3,
    question:'Rodrigues is volcanic in origin, yet a raised platform of old coral rock rings much of it.<br>What does that two-part structure tell us?',
    options:['A volcano formed first, coral grew round it, and the platform was later lifted','Coral built the entire island, and the volcanic rock beneath it was brought there by currents','The island was made in a single event, so both kinds of rock formed together','Volcanic rock always turns into coral rock as an island grows older'],
    answer:'A volcano formed first, coral grew round it, and the platform was later lifted',
    hint:'Coral grows on something. Ask what it grew on, and how it got above the waves.',
    explanation:'Coral needs a shallow platform to grow on, so the <b>volcano came first</b>; the reef built around it and was afterwards raised above sea level. Currents cannot carry a mass of volcanic rock, and one rock type does not turn into the other.' }),

  makeMCQ({ id:'g7sms-hd-007', chapterId:'g7sms-islands', subsection:'island_types', difficulty:4,
    question:'Farmers on a volcanic island grow cane, tea and vegetables on deep soils. On a nearby coral island, farmers struggle to grow much beyond coconut.<br>Why is the difference so sharp?',
    options:['Weathered volcanic rock makes deep soil; coral sand holds little water or nutrient','Coral islands lie further from the equator, so their crops receive far less sunshine','Volcanic islands are always larger, and size alone decides what will grow there','The farmers on the coral island are simply planting at the wrong time of year'],
    answer:'Weathered volcanic rock makes deep soil; coral sand holds little water or nutrient',
    hint:'Follow the soil back to the rock it came from.',
    explanation:'Volcanic rock breaks down into <b>deep, mineral-rich soil</b>. Coral sand drains almost instantly and carries few nutrients, which is why the crop list is so short. Sunshine and planting dates are not what separates the two.' }),

  makeMCQ({ id:'g7sms-hd-008', chapterId:'g7sms-islands', subsection:'island_types', difficulty:3,
    question:'Two islands are the same size. One is volcanic, with hills and streams; the other is a flat coral atoll.<br>Which is likely to support the larger population, and why?',
    options:['The volcanic one, because it offers soil, fresh water and building stone','The coral one, because flat land is easier to build on than anything else','Neither, since population depends only on how far the island is from a port','The volcanic one, because volcanoes keep the whole island warm all year'],
    answer:'The volcanic one, because it offers soil, fresh water and building stone',
    hint:'List what a village needs every single day, then see which island supplies it.',
    explanation:'People need food, water and materials. A volcanic island supplies all three; a flat atoll gives level ground but <b>little soil and no surface water</b>. Warmth from the volcano itself plays no part.' }),

  makeMCQ({ id:'g7sms-hd-009', chapterId:'g7sms-islands', subsection:'landforms', difficulty:4,
    question:'Trou aux Cerfs still shows a clear, round crater with an almost unbroken rim, while mountains elsewhere on the island are jagged, broken ridges.<br>What does that contrast suggest?',
    options:['Trou aux Cerfs formed much more recently, so erosion has done less to it','The mountains are the younger ones, and a broken shape is what a new volcano looks like','Craters keep their shape for ever, so age cannot be judged from them','The rim was rebuilt by people to protect the town lying below it'],
    answer:'Trou aux Cerfs formed much more recently, so erosion has done less to it',
    hint:'Rain and wind wear rock down. The more worn the shape, the longer it has been exposed.',
    explanation:'A crisp, complete rim means <b>less time under rain and wind</b>. The broken ridges elsewhere are older volcanic rock that has been worn for far longer. A new volcano builds a neat cone, not a shattered ridge.' }),

  makeMCQ({ id:'g7sms-hd-010', chapterId:'g7sms-islands', subsection:'landforms', difficulty:4,
    question:'Seen from above, many of the island\'s mountains stand in a rough, broken ring around the central plateau.<br>What is the best explanation of that pattern?',
    options:['They are the worn remains of the rim of a much larger, older volcano','They were each pushed up separately by the sea and happen to lie in a circle','They are coral reefs that were lifted and then hardened into hard rock','They mark the edge of the island as it was before the lagoon formed'],
    answer:'They are the worn remains of the rim of a much larger, older volcano',
    hint:'What natural shape is a ring with a hollow in the middle?',
    explanation:'A ring of peaks around lower ground is the eroded <b>rim of an old volcano</b>, the middle having collapsed and worn down. Separate uplifts landing by chance in a circle is not a serious explanation.' }),

  makeMCQ({ id:'g7sms-hd-011', chapterId:'g7sms-islands', subsection:'landforms', difficulty:4,
    question:'A coral reef runs round much of the coast, a short way offshore. Inside it the water is shallow and calm; outside it the waves break heavily.<br>Why did fishing villages grow along the lagoon shore rather than on open coasts?',
    options:['The reef breaks the waves, so small boats can land and work in safety','Fish live only inside lagoons and are never found in the open sea beyond','Lagoon water is deeper, which lets far larger boats be moored close in','Open coasts were kept empty by law so that ships could pass freely'],
    answer:'The reef breaks the waves, so small boats can land and work in safety',
    hint:'Think about launching a small wooden boat, twice a day, all year.',
    explanation:'The reef takes the force of the swell, leaving <b>calm water for launching and landing</b>. Lagoons are shallower, not deeper, and the open sea is full of fish — it is simply dangerous for a small boat.' }),

  makeMCQ({ id:'g7sms-hd-012', chapterId:'g7sms-islands', subsection:'landforms', difficulty:4,
    question:'Two weather stations report a full year. One sits on the coast at 20 m; the other on the central plateau at 550 m. The plateau station is cooler and records about twice the rainfall.<br>Which conclusion is best supported?',
    options:['Height above sea level strongly affects both temperature and rainfall here','The plateau is colder only because it lies further south than the coastal station','Temperature falls with height, but rainfall is unrelated to relief on an island','Rainfall is the same everywhere, so the plateau rain gauge must be faulty'],
    answer:'Height above sea level strongly affects both temperature and rainfall here',
    hint:'Only one thing has been changed between the two stations. What is it?',
    explanation:'The stations differ mainly in <b>altitude</b>, and both readings change together — air cools as it is forced upwards and drops its moisture as rain. Dismissing the gauge as faulty ignores a pattern seen across the island.' }),

  makeMCQ({ id:'g7sms-hd-013', chapterId:'g7sms-origins', subsection:'historical_significance', difficulty:4,
    question:'Historians agree that no people lived on these islands before ships began to arrive.<br>What follows from that for the story of the country?',
    options:['Every community here descends from people who came from somewhere else','One community must have been here first and so has the oldest claim to the land','The first arrivals must have found villages already built and simply taken them','The islands have no history worth studying before the first settlers came'],
    answer:'Every community here descends from people who came from somewhere else',
    hint:'If nobody was here, where did everybody come from?',
    explanation:'An empty island means <b>every family line began with an arrival</b>, whether from Africa, Madagascar, India, China or Europe. There were no villages to take over, and the geology and wildlife of the islands are history worth studying in themselves.' }),

  makeMCQ({ id:'g7sms-hd-014', chapterId:'g7sms-origins', subsection:'historical_significance', difficulty:4,
    question:'For centuries, ships sailing between Europe and Asia rounded southern Africa and then crossed the Indian Ocean with no port for weeks.<br>Why did European powers compete so hard for these islands?',
    options:['They offered a safe halt for water, food and repairs on a very long route','They were rich in gold and silver, which was the whole reason for the contest','They already had large ports and populations that could be taxed heavily','They lay directly on the shortest possible line between the two continents'],
    answer:'They offered a safe halt for water, food and repairs on a very long route',
    hint:'What does a wooden ship run out of after two months at sea?',
    explanation:'Crews needed <b>water, fresh food and a sheltered place to repair</b> halfway along the route, and whoever held the islands controlled that halt. The islands held no gold, and before settlement there was nobody to tax.' }),

  makeMCQ({ id:'g7sms-hd-015', chapterId:'g7sms-origins', subsection:'historical_significance', difficulty:4,
    question:'The country marks the end of colonial rule and, later, its becoming a republic as two separate steps.<br>Why are these not the same event?',
    options:['The first ended colonial rule; the second changed the head of State','They are in fact the same event, given two different names by later historians','The first changed the head of State; the second ended colonial rule','The first was about the flag, and the second about the national anthem'],
    answer:'The first ended colonial rule; the second changed the head of State',
    hint:'Ask what each step actually changed — who governs, or who stands at the top?',
    explanation:'Independence transferred <b>the power to govern</b> to the country itself. Becoming a republic came later and changed who holds the office of head of State. Reversing the two, or reducing them to flags and anthems, misses what each did.' }),

  makeMCQ({ id:'g7sms-hd-016', chapterId:'g7sms-origins', subsection:'historical_significance', difficulty:4,
    question:'A guide tells visitors that the island\'s harbour \'made its history\'.<br>Which piece of evidence would best support that claim?',
    options:['Rival powers fought to hold the harbour because it commanded the sea route','The harbour is the deepest in the Indian Ocean and has never silted up at all','The harbour is where most visitors now take their photographs of the waterfront','The harbour lies close to the mountains that stand around the capital'],
    answer:'Rival powers fought to hold the harbour because it commanded the sea route',
    hint:'Evidence for a claim about history has to be about consequences, not scenery.',
    explanation:'If powerful states fought over it, the harbour clearly <b>shaped who ruled the island and when</b> — that is the claim being tested. Photographs and nearby mountains say nothing about historical importance.' }),

  makeMCQ({ id:'g7sms-hd-017', chapterId:'g7sms-origins', subsection:'settlers_origins', difficulty:4,
    question:'Sugar estates needed a very large workforce all year round. When slavery was abolished, the estates did not shrink.<br>What does that combination best explain?',
    options:['Why indentured workers were recruited in large numbers from India','Why the estates closed and the island turned to trading instead of farming','Why sugar was replaced by tea within a very few years of abolition','Why the estates moved to Rodrigues, where more land was available'],
    answer:'Why indentured workers were recruited in large numbers from India',
    hint:'The demand for labour did not disappear. So where was it met from?',
    explanation:'The estates still needed thousands of workers, so labour was brought in under <b>indenture</b>, chiefly from India — which is why so many Mauritian families trace their roots there. Sugar did not stop, and Rodrigues has neither the land nor the soil for it.' }),

  makeMCQ({ id:'g7sms-hd-018', chapterId:'g7sms-origins', subsection:'settlers_origins', difficulty:4,
    question:'Chinese arrivals largely opened shops in towns and villages rather than working in the cane fields.<br>What settlement pattern would you expect as a result?',
    options:['Families spread through trading centres rather than clustering on the estates','Families living only on the estates, because every newcomer went to the fields','Families settling only in Rodrigues, where there were no cane fields at all','Families living far from towns, so that their trade could stay private'],
    answer:'Families spread through trading centres rather than clustering on the estates',
    hint:'A shop has to be where the customers are. Where were they?',
    explanation:'Trade follows customers, so shopkeeping families settled in <b>towns and village centres</b> across the island rather than in estate camps. Living away from towns would defeat the purpose of a shop.' }),

  makeMCQ({ id:'g7sms-hd-019', chapterId:'g7sms-origins', subsection:'settlers_origins', difficulty:3,
    question:'In a school debate, one speaker says his community is \'more Mauritian\' than the others because it arrived first.<br>How should that claim be judged?',
    options:['It fails, since the islands were empty and every community arrived','It holds only for communities that came before the first harbour was built','It holds, because the earliest arrivals have the strongest claim of all','It cannot be judged, because no records of any arrival survive today'],
    answer:'It fails, since the islands were empty and every community arrived',
    hint:'Check the starting point of the argument before checking the argument.',
    explanation:'Nobody was here first in the sense the speaker means — <b>every community came from overseas</b>, and arrival dates do not rank people. Records of arrivals do in fact survive in ship lists and registers.' }),

  makeMCQ({ id:'g7sms-hd-020', chapterId:'g7sms-origins', subsection:'cultural_diversity', difficulty:4,
    question:'People arriving from Africa, Madagascar, India, China and Europe spoke many different languages, yet had to work, trade and live side by side every day.<br>What does that best explain?',
    options:['Why a shared everyday language grew up and is spoken across communities','Why each community kept its own language completely separate from all others','Why only one language from overseas survived and all the rest disappeared','Why written records were kept in a language that nobody actually spoke'],
    answer:'Why a shared everyday language grew up and is spoken across communities',
    hint:'People who must understand one another daily will find a way to do it.',
    explanation:'Daily contact in fields, markets and yards forced a <b>common spoken language</b> to develop, drawing on many origins — which is why it crosses every community today. Complete separation was never possible for people working together.' }),

  makeMCQ({ id:'g7sms-hd-021', chapterId:'g7sms-origins', subsection:'cultural_diversity', difficulty:4,
    question:'The calendar of public holidays includes days that are important to several different faiths.<br>What does that show about the country, rather than about religion?',
    options:['That the State recognises the many origins of its people','That the State has chosen one faith and gives the others a courtesy day','That holidays are handed out to reduce the number of working days','That every citizen is expected to take part in each celebration'],
    answer:'That the State recognises the many origins of its people',
    hint:'The question is about what the calendar says, not about belief.',
    explanation:'Marking several faiths in the official calendar is the State <b>acknowledging its own diversity</b>. It is not a courtesy from one favoured faith, and nobody is required to celebrate anything.' }),

  makeMCQ({ id:'g7sms-hd-022', chapterId:'g7sms-origins', subsection:'cultural_diversity', difficulty:4,
    question:'One writer calls the country\'s diversity \'its greatest strength\'; another warns that it \'could divide it\'.<br>Which response weighs both fairly?',
    options:['Diversity brings strength when shared, and risk when used to set groups apart','Diversity is always a strength, and so the second writer has nothing at all to add','Diversity is always a danger and should be reduced wherever that is possible','Neither view matters, because culture has no effect on how a country works'],
    answer:'Diversity brings strength when shared, and risk when used to set groups apart',
    hint:'Both writers describe something real. What decides which one comes true?',
    explanation:'Diversity is not automatically good or bad — <b>what people do with it</b> decides. Shared festivals, food and language build a common identity; the same differences turned into walls divide. Dismissing culture entirely ignores both writers.' }),

  makeMCQ({ id:'g7sms-hd-023', chapterId:'g7sms-people', subsection:'individuals_country', difficulty:4,
    question:'A class must decide whether a person deserves a place in a display about people who shaped the country.<br>Which test is the most useful?',
    options:['Did their work change how people live long after they stopped working?','Were they widely talked about and photographed while they were still alive?','Did they hold the most senior job that was available at the time?','Were they born on the island rather than arriving from abroad?'],
    answer:'Did their work change how people live long after they stopped working?',
    hint:'Fame fades quickly. What is left behind twenty years later?',
    explanation:'Significance is measured by <b>lasting change</b> — a school system, a law, an industry that outlives the person. Fame at the time and a senior job title are common but prove nothing on their own.' }),

  makeMCQ({ id:'g7sms-hd-024', chapterId:'g7sms-people', subsection:'individuals_country', difficulty:4,
    question:'A reformer was strongly opposed throughout her lifetime, yet the change she argued for is now taken for granted.<br>What does that suggest about judging significance?',
    options:['Significance is judged by lasting effects, not by support at the time','A person opposed in their own lifetime can never be counted as significant','Only people who were popular while alive changed anything that lasted','Significance depends on how long a person held office in government'],
    answer:'Significance is judged by lasting effects, not by support at the time',
    hint:'She lost the argument then and won it since. Which result counts?',
    explanation:'The measure is <b>what endured</b>. Opposition at the time is common for people proposing something new, and it does not disqualify them; nor does holding office qualify anyone by itself.' }),

  makeMCQ({ id:'g7sms-hd-025', chapterId:'g7sms-people', subsection:'individuals_country', difficulty:3,
    question:'A caption in an exhibition reads: \'This man built the country\'s road network.\'<br>Why should a historian be careful with that sentence?',
    options:['Large works are built by many people; one name hides all the rest','Captions are never accurate, so no sentence in a display can be trusted','The sentence is fine, since a leader is responsible for all of the work','Roads are not important enough to be counted as a contribution'],
    answer:'Large works are built by many people; one name hides all the rest',
    hint:'Picture the actual work. How many pairs of hands does a road take?',
    explanation:'Engineers, surveyors and thousands of labourers built those roads. Crediting one name gives a <b>false picture of how the work was done</b>, though it does not make every caption untrustworthy.' }),

  makeMCQ({ id:'g7sms-hd-026', chapterId:'g7sms-people', subsection:'individuals_country', difficulty:4,
    question:'Two contributions are compared: a doctor who treated patients for thirty years in one district, and an official whose decision opened schooling to every child.<br>How is their significance best compared?',
    options:['By how many lives were changed, and for how long, in each case','By which of the two people was better known to the public at the time','By which of the two earned the higher salary during their career','They cannot be compared, since health and schooling are different'],
    answer:'By how many lives were changed, and for how long, in each case',
    hint:'You need one measure that works for both, not one that suits only one of them.',
    explanation:'<b>Reach and duration</b> can be applied to a doctor and to an official alike, which makes a fair comparison possible. Fame and salary measure something else entirely, and refusing to compare avoids the question.' }),

  makeMCQ({ id:'g7sms-hd-027', chapterId:'g7sms-people', subsection:'contributions_mauritians', difficulty:4,
    question:'When fees for secondary schooling were removed, many more children from poor families stayed on at school.<br>Which longer-term effect on the country would you expect?',
    options:['A larger pool of trained workers for new kinds of industry later on','An immediate fall in the number of children attending primary school','A fall in the number of teachers needed across the whole island','No effect, since schooling and the economy are quite unconnected'],
    answer:'A larger pool of trained workers for new kinds of industry later on',
    hint:'Follow those children forward ten years. What are they able to do?',
    explanation:'Children who stay at school become <b>a workforce able to take on skilled jobs</b> — which is what textiles, tourism and financial services later needed. More pupils staying on means more teachers required, not fewer.' }),

  makeMCQ({ id:'g7sms-hd-028', chapterId:'g7sms-people', subsection:'contributions_mauritians', difficulty:4,
    question:'A display honours one famous individual. A pupil suggests adding a panel on nurses, teachers and cane cutters.<br>What is the strongest argument for the panel?',
    options:['Much of what a country achieves is the work of groups, not individuals','Famous individuals are not real contributors and should be left out entirely','Panels look better when they contain more photographs of ordinary people','Groups are easier to research than individuals with long careers'],
    answer:'Much of what a country achieves is the work of groups, not individuals',
    hint:'Who actually did the daily work that kept the country going?',
    explanation:'Hospitals, schools and the sugar economy ran on <b>the collective work of thousands</b>, and a display of single names leaves that invisible. Adding them does not mean removing the famous individual.' }),

  makeMCQ({ id:'g7sms-hd-029', chapterId:'g7sms-people', subsection:'contributions_mauritians', difficulty:3,
    question:'A scientist spends years recording the island\'s endemic plants, many of which grow nowhere else on earth.<br>Why is that work valuable beyond science itself?',
    options:['It records a heritage that cannot be replaced if the plants are lost','It proves the island is larger than its neighbours in the same ocean','It allows the plants to be exported and sold in far greater numbers','It shows that endemic plants grow faster than imported ones do'],
    answer:'It records a heritage that cannot be replaced if the plants are lost',
    hint:'Endemic means found here and nowhere else. What happens if it disappears?',
    explanation:'An endemic species lost here is <b>lost everywhere</b>, so the record itself becomes part of the country\'s heritage. The work says nothing about island size or growth rates.' }),

  makeMCQ({ id:'g7sms-hd-030', chapterId:'g7sms-people', subsection:'contributions_mauritians', difficulty:4,
    question:'In years when the economy depended on sugar alone, some Mauritians set up textile factories that came to employ thousands.<br>Why did that matter to the whole country?',
    options:['It spread the risk, so a bad year for sugar no longer sank everything','It ended sugar growing completely, which removed the risk from farming','It made the island the largest producer of cloth anywhere in the world','It reduced the need for schooling, because factory work is unskilled'],
    answer:'It spread the risk, so a bad year for sugar no longer sank everything',
    hint:'What happens to a one-crop economy after a cyclone or a price crash?',
    explanation:'A single crop leaves a country exposed to weather and world prices. Adding textiles — and later tourism and financial services — gave the economy <b>more than one leg to stand on</b>. Sugar continued alongside them.' }),

  makeMCQ({ id:'g7sms-hd-031', chapterId:'g7sms-people', subsection:'achievements_arts_sport', difficulty:4,
    question:'A Mauritian athlete wins a medal at a major international games.<br>Beyond the sport itself, what is the strongest reason this matters to the country?',
    options:['It shows young people here that such a level is within reach','It proves that a small country produces better athletes than large ones','It guarantees that the country will win again at the next games','It replaces the need for sports facilities in schools and villages'],
    answer:'It shows young people here that such a level is within reach',
    hint:'Think about the child watching at home, not the scoreboard.',
    explanation:'The lasting effect is on <b>who now believes they could do it</b>, which feeds clubs and school teams for years. One medal proves nothing about the next games and removes no need for facilities.' }),

  makeMCQ({ id:'g7sms-hd-032', chapterId:'g7sms-people', subsection:'achievements_arts_sport', difficulty:4,
    question:'Sega, born on the island and carried on for generations, is recognised internationally as living heritage.<br>Why does recognition of that kind matter for a small country?',
    options:['It protects a tradition that only a small community keeps alive','It turns the tradition into a fixed performance that must never change','It allows the country to claim the music of its neighbours as well','It means the tradition no longer needs to be taught to children'],
    answer:'It protects a tradition that only a small community keeps alive',
    hint:'How many people in the world can pass this tradition on?',
    explanation:'A tradition held by a small population is <b>easily lost in one generation</b>, so recognition brings support for teaching and performing it. Recognition is meant to keep it living and taught, not frozen.' }),

  makeMCQ({ id:'g7sms-hd-033', chapterId:'g7sms-people', subsection:'achievements_arts_sport', difficulty:3,
    question:'Two artists are compared. One sold the most records in a single year; the other changed the way a whole generation of musicians played.<br>Which is the better measure of achievement in the arts?',
    options:['Lasting influence on others, because sales rise and fall quickly','Record sales, because a number can be checked and influence cannot be','Neither, since achievement in the arts cannot be discussed at all','The number of countries in which the artist has performed live'],
    answer:'Lasting influence on others, because sales rise and fall quickly',
    hint:'One of these two artists can still be heard in music made today.',
    explanation:'<b>Influence</b> keeps working after the artist stops, while a year of sales is a snapshot of fashion. Influence is harder to count, but harder to measure is not the same as impossible to judge.' }),

  makeMCQ({ id:'g7sms-hd-034', chapterId:'g7sms-people', subsection:'achievements_arts_sport', difficulty:4,
    question:'A regional Indian Ocean games brings athletes from several neighbouring islands to compete here.<br>Apart from medals, what does hosting an event of that kind bring?',
    options:['Closer links with neighbours, plus facilities that outlast the games','A permanent guarantee of victory for the island that hosts the event','An end to the need for local athletes to travel abroad ever again','A larger population, since visiting athletes tend to settle here'],
    answer:'Closer links with neighbours, plus facilities that outlast the games',
    hint:'What is still standing, and still true, the year after the closing ceremony?',
    explanation:'Hosting builds <b>tracks, pools and halls that stay</b>, and strengthens ties with island neighbours who share the same ocean. Hosting does not guarantee medals, and athletes go home afterwards.' }),

  makeMCQ({ id:'g7sms-hd-035', chapterId:'g7sms-settlement', subsection:'settlement_evolution', difficulty:4,
    question:'Villages once grew around sugar estates because the work was there. Many estates have since closed or been mechanised, yet those villages have kept growing.<br>What best explains that?',
    options:['People stayed and now travel out to work in towns and factories','The estates reopened quietly, so the original reason for the village returned','The closures brought new farmland that needed even more workers than before','Villages always grow, whatever happens to the work nearby'],
    answer:'People stayed and now travel out to work in towns and factories',
    hint:'A village is homes and families, not only a place of work.',
    explanation:'Houses, schools and family ties hold people in place even when the estate work goes; roads and buses then let them <b>commute to work elsewhere</b>. Mechanisation reduces the labour needed, it does not increase it.' }),

  makeMCQ({ id:'g7sms-hd-036', chapterId:'g7sms-settlement', subsection:'settlement_evolution', difficulty:4,
    question:'A quiet coastal village of fishers now has hotels, restaurants and a road three times as wide.<br>Which pair of changes would you expect to come with that?',
    options:['More jobs in services, and higher land prices for local families','Fewer visitors each year, and a fall in the price of land near the sea','Less traffic, because the hotels keep their guests off the village roads','More fishing boats, because tourism increases the size of the catch'],
    answer:'More jobs in services, and higher land prices for local families',
    hint:'Two effects, and one of them is good news while the other is not.',
    explanation:'Tourism brings <b>work in hotels and restaurants</b>, but competition for coastal land pushes prices beyond what local families can pay. Tourism does not reduce traffic, nor does it make more fish.' }),

  makeMCQ({ id:'g7sms-hd-037', chapterId:'g7sms-settlement', subsection:'settlement_evolution', difficulty:3,
    question:'A table shows a village of 1,200 people in 1970 and about 9,000 today, while the number working in agriculture there has fallen by half.<br>What does the table best show?',
    options:['The village has grown while its original work has shrunk','The village grew because farming there expanded over the same period','The population figures must be wrong, since both cannot change at once','Farming now employs more people there than it did back in 1970'],
    answer:'The village has grown while its original work has shrunk',
    hint:'Two columns, moving in opposite directions. Say what each one does.',
    explanation:'Population rose sharply and farm work fell, so the village <b>grew for reasons other than farming</b> — commuting, services and housing. The two figures move in opposite directions, which is perfectly possible.' }),

  makeMCQ({ id:'g7sms-hd-038', chapterId:'g7sms-settlement', subsection:'settlement_evolution', difficulty:4,
    question:'A landowner wants to turn 40 hectares of cane into housing near a growing town.<br>Which pair of consequences should the decision weigh against each other?',
    options:['Homes for families now, against farmland that cannot be remade','Nothing needs weighing, since land can always be turned back into cane later','More cane for the mill, against a fall in the number of new houses','Cheaper sugar, against a rise in the number of people farming'],
    answer:'Homes for families now, against farmland that cannot be remade',
    hint:'One of these is easy to reverse and one is not.',
    explanation:'Housing meets a real need, but once soil is built over it is <b>effectively lost to farming for good</b> — that irreversibility is the heart of the trade-off. The other pairings describe the opposite of what the change would do.' }),

  makeMCQ({ id:'g7sms-hd-039', chapterId:'g7sms-settlement', subsection:'settlement_factors', difficulty:4,
    question:'Towns on the central plateau grew quickly once a railway linked them to the port, even though the coast was warmer and nearer the sea.<br>Why did people choose the higher ground?',
    options:['Cooler, wetter conditions and level land, once travel had been solved','The plateau was closer to the harbour than the coast was, so travel was shorter','Building on a plateau is cheaper, because no foundations are needed there','The coast had no drinking water of any kind at that time'],
    answer:'Cooler, wetter conditions and level land, once travel had been solved',
    hint:'Two facts must be put together: what the plateau offers, and what the railway removed.',
    explanation:'The plateau always had a <b>cooler climate, more rain and room to build</b>; what it lacked was easy access, and the railway supplied that. It is further from the harbour, not nearer.' }),

  makeMCQ({ id:'g7sms-hd-040', chapterId:'g7sms-settlement', subsection:'settlement_factors', difficulty:4,
    question:'Steep mountain slopes on the island stay largely empty, although the views are fine and the air is cool.<br>Which combination best explains that?',
    options:['Building and farming are hard there, and services are costly to bring','The slopes are colder than anywhere else and nothing at all will grow','The slopes are all owned by hotels that refuse to sell any of the land','People dislike views and prefer to live where nothing can be seen'],
    answer:'Building and farming are hard there, and services are costly to bring',
    hint:'Imagine laying a water pipe, a road and a power line up a steep slope.',
    explanation:'Slope makes foundations, ploughing, roads, pipes and cables <b>expensive and difficult</b>, which outweighs the view. Plenty grows on the slopes, and ownership is not the obstacle.' }),

  makeMCQ({ id:'g7sms-hd-041', chapterId:'g7sms-settlement', subsection:'settlement_factors', difficulty:3,
    question:'Most of the island\'s piped water is held in reservoirs such as Mare aux Vacoas, high on the wetter uplands.<br>Why is storing it necessary at all?',
    options:['Rain arrives unevenly through the year, but taps are used every day','Reservoirs are needed because the island receives almost no rainfall at all','Rivers on the island flow only at night, so water must be held by day','Water stored high up becomes cleaner than water taken from a river'],
    answer:'Rain arrives unevenly through the year, but taps are used every day',
    hint:'Compare when the rain comes with when the water is wanted.',
    explanation:'Rainfall is <b>seasonal, demand is constant</b>, so wet-season water must be held for the dry months. The island is well watered in the uplands, and rivers do not run only at night.' }),

  makeMCQ({ id:'g7sms-hd-042', chapterId:'g7sms-settlement', subsection:'physical_historical', difficulty:4,
    question:'A flat, fertile plain stayed almost empty for a century, then filled with villages within twenty years of a new road being cut through to the port.<br>What does that show about settlement?',
    options:['Good land is not enough; people also need a way to reach a market','Roads create fertile soil, which is why the plain became useful at last','Settlement depends on soil alone, and the road was simply a coincidence','People avoid flat land until it has been ploughed for many years'],
    answer:'Good land is not enough; people also need a way to reach a market',
    hint:'The soil did not change. Something else did.',
    explanation:'Fertility was there all along; what was missing was <b>access to buyers</b>, and the road supplied it. Two conditions had to be met at once, so soil alone cannot be the explanation.' }),

  makeMCQ({ id:'g7sms-hd-043', chapterId:'g7sms-settlement', subsection:'physical_historical', difficulty:4,
    question:'Cyclones strike the island, and the coast is its most exposed part. Yet the coast is heavily built up.<br>How can both of those be true at once?',
    options:['The pull of work, trade and the sea outweighs a risk faced now and then','Cyclones never actually reach the coast, and so the risk there is imaginary','Coastal buildings cannot be damaged, because they are all built of stone','People living on the coast are unaware that cyclones happen at all'],
    answer:'The pull of work, trade and the sea outweighs a risk faced now and then',
    hint:'People weigh a daily benefit against an occasional danger.',
    explanation:'Ports, fishing, tourism and flat land are advantages available <b>every single day</b>; a cyclone is a serious but occasional risk, managed by building codes and warnings. The danger is real and well known.' }),

  makeMCQ({ id:'g7sms-hd-044', chapterId:'g7sms-settlement', subsection:'physical_historical', difficulty:3,
    question:'The prevailing winds come from the south-east, and the island\'s main harbour lies on the north-west coast.<br>What is the connection between those two facts?',
    options:['The north-west lies in the shelter of the island, so the water is calmer','The north-west faces the wind head-on, which conveniently pushes ships into port','The wind direction has no bearing at all on where a harbour can be built','Harbours must always be built on whichever coast faces towards the north'],
    answer:'The north-west lies in the shelter of the island, so the water is calmer',
    hint:'Stand the island between the wind and the harbour. Which side is quiet?',
    explanation:'With the wind out of the south-east, the island shields its <b>north-west, leeward coast</b>, giving the calm anchorage a sailing ship needed. Facing the wind head-on would make a harbour dangerous, not convenient.' }),

  makeMCQ({ id:'g7sms-hd-045', chapterId:'g7sms-resources', subsection:'natural_resources', difficulty:4,
    question:'A pupil lists the island\'s natural resources as: sunshine, the lagoon, basalt rock, and a textile factory.<br>Which item does not belong, and why?',
    options:['The factory, because it is made by people rather than found in nature','The lagoon, because salt water can never be counted as useful to anybody','Basalt rock, because rock is not used for anything at all on the island','Sunshine, because a resource has to be something you can hold'],
    answer:'The factory, because it is made by people rather than found in nature',
    hint:'Apply the definition word by word: natural, and a resource.',
    explanation:'A natural resource is <b>supplied by nature and useful to people</b>. Sunshine, the lagoon and basalt all qualify; a factory is built, so it is capital, not a natural resource. A resource need not be solid.' }),

  makeMCQ({ id:'g7sms-hd-046', chapterId:'g7sms-resources', subsection:'natural_resources', difficulty:4,
    question:'The Republic controls a very large area of sea compared with its land area.<br>Which resources does that mainly give it access to?',
    options:['Fish stocks, the seabed beneath, and space for marine farming','Coal and oil fields, which is where the island gets its own fuel from','Farmland and forest, which extend under the water beyond the reef','Nothing, since a sea area cannot contain resources of any kind'],
    answer:'Fish stocks, the seabed beneath, and space for marine farming',
    hint:'Ask what a nation can actually harvest from water it controls.',
    explanation:'A maritime zone carries rights over <b>fish, the seabed and the use of the water itself</b> — a real advantage for a country short of land. The islands have no oil or coal, and farmland does not continue under the sea.' }),

  makeMCQ({ id:'g7sms-hd-047', chapterId:'g7sms-resources', subsection:'natural_resources', difficulty:3,
    question:'The uplands receive far more rain than the coast, and the main reservoirs are built up there.<br>Why does that siting make sense?',
    options:['Water is collected where most rain falls, then flows down to users','Water stored high up evaporates faster, which keeps the reservoir clean','The uplands are the only place with enough people to need the water','Rain that falls on the coast is too salty to be stored and used'],
    answer:'Water is collected where most rain falls, then flows down to users',
    hint:'Two advantages: where the water arrives, and which way it then travels.',
    explanation:'Building where rainfall is heaviest catches the most water, and height lets it <b>travel down to towns by gravity</b> instead of being pumped. Most people live below, not on, the uplands.' }),

  makeMCQ({ id:'g7sms-hd-048', chapterId:'g7sms-resources', subsection:'natural_resources', difficulty:4,
    question:'The islands have no coal, oil or gas of their own, and in one year world fuel prices rose sharply.<br>What effect on the country would you expect?',
    options:['Electricity and transport costs rise, pushing up prices in the shops','No effect at all, because the country produces all of its own fuel already','Electricity becomes cheaper, since imported fuel is no longer needed','Only the sugar industry is affected, and nothing else in the country'],
    answer:'Electricity and transport costs rise, pushing up prices in the shops',
    hint:'Everything on a shelf arrived by lorry, and every lorry burns imported fuel.',
    explanation:'With no fossil fuels of its own, the country buys them at world prices, so a rise <b>spreads through power, transport and then every price</b>. Bagasse from cane helps at harvest time but does not cover the whole demand.' }),

  makeMCQ({ id:'g7sms-hd-049', chapterId:'g7sms-resources', subsection:'resource_types', difficulty:4,
    question:'Resources can be grouped by where they come from: the atmosphere, the hydrosphere, the lithosphere or the biosphere.<br>Where do bagasse from cane and basalt for building belong?',
    options:['Bagasse in the biosphere; basalt in the lithosphere','Bagasse in the lithosphere, because it is burned in the way that coal is burned','Both belong in the biosphere, since both are dug out of the ground','Bagasse in the hydrosphere; basalt in the atmosphere'],
    answer:'Bagasse in the biosphere; basalt in the lithosphere',
    hint:'Ask what each one actually is before asking what it is used for.',
    explanation:'Bagasse is the fibre left after cane is crushed, so it comes from <b>living matter</b>; basalt is volcanic rock from the solid Earth. How a thing is used does not change which sphere it came from.' }),

  makeMCQ({ id:'g7sms-hd-050', chapterId:'g7sms-resources', subsection:'resource_types', difficulty:4,
    question:'A quarry sells crushed basalt for building. A sugar mill burns the bagasse left over after the cane is crushed.<br>How should each be classified?',
    options:['Bagasse renewable while cane is replanted; basalt is not renewable','Neither is renewable, since anything that is used up cannot be replaced','Both are renewable, because both are produced on the island every year','Basalt renewable, because more rock forms whenever it rains hard'],
    answer:'Bagasse renewable while cane is replanted; basalt is not renewable',
    hint:'One of them grows back in a season. How long would the other take?',
    explanation:'Cane regrows each season, so <b>bagasse renews with the crop</b>; basalt took volcanic eruptions to form and is not replaced on any human timescale. Rain does not make rock.' }),

  makeMCQ({ id:'g7sms-hd-051', chapterId:'g7sms-resources', subsection:'resource_types', difficulty:4,
    question:'Sunshine here is strong for most of the year, and the trade winds blow steadily.<br>Why does that matter to a country that imports all of its fuel?',
    options:['Sun and wind are resources it already has and need not buy','Sun and wind are pleasant but cannot be turned into any useful energy','Sun and wind matter only to farmers, and not to the energy supply','Sun and wind reduce the amount of rain that the reservoirs receive'],
    answer:'Sun and wind are resources it already has and need not buy',
    hint:'Put two facts together: no fuel of its own, and two things arriving free every day.',
    explanation:'Every unit of energy taken from sun or wind is <b>fuel that does not have to be imported and paid for</b>, which matters most to a country with no fossil fuels of its own.' }),

  makeMCQ({ id:'g7sms-hd-052', chapterId:'g7sms-resources', subsection:'resource_types', difficulty:4,
    question:'A fisherman argues that fish can never run out, because new fish are born every year.<br>How should his claim be judged?',
    options:['Renewable stocks still fail if they are taken faster than they breed','He is quite right, since a resource that renews itself can never be exhausted','The claim cannot be judged, since fish stocks are impossible to count','He is wrong, because fish are a non-renewable resource, like rock'],
    answer:'Renewable stocks still fail if they are taken faster than they breed',
    hint:'Renewable describes how it is replaced, not how fast.',
    explanation:'Fish are renewable, but renewal has a <b>rate</b>: catch beyond it and the stock shrinks year on year until it collapses. That is why catches are limited and seasons closed. Stocks can be estimated by survey.' }),

  makeMCQ({ id:'g7sms-hd-053', chapterId:'g7sms-resources', subsection:'resources_settlement', difficulty:4,
    question:'Early settlements on the island clustered along rivers and near springs rather than spreading evenly across it.<br>Which pair of reasons best explains that?',
    options:['Drinking water was needed daily, and moving it far was hard work','Rivers were the only flat land, and springs kept the ground from flooding','Settlers were required by law to live within sight of running water','Rivers were warmer, and springs provided most of the island\'s food'],
    answer:'Drinking water was needed daily, and moving it far was hard work',
    hint:'Before pipes, how did a household get twenty litres of water?',
    explanation:'Water was carried by hand or cart, so people settled <b>within a short walk of a river or spring</b> — cooking, washing and animals all depended on it. River valleys are not the only flat land, and no law was involved.' }),

  makeMCQ({ id:'g7sms-hd-054', chapterId:'g7sms-resources', subsection:'resources_settlement', difficulty:4,
    question:'A map shows villages forming a chain across the fertile lowlands, with almost none on the thin soils of the highest slopes.<br>What does that pattern show?',
    options:['Where a resource is good, people settle; where it is poor, they do not','People settle wherever the view is finest, whatever the soil beneath may be','Soils have no effect, and the chain of villages is simply a coincidence','The highest slopes are empty because they receive no rainfall at all'],
    answer:'Where a resource is good, people settle; where it is poor, they do not',
    hint:'Lay the settlement map over the soil map and see where they agree.',
    explanation:'The villages follow the good soil because <b>the resource decided where a living could be made</b>. A pattern that matches the soil map so closely is not coincidence, and the high slopes are wet, not dry.' }),

  makeMCQ({ id:'g7sms-hd-055', chapterId:'g7sms-resources', subsection:'resources_settlement', difficulty:3,
    question:'Fishing villages on the island sit on the lagoon side of the coast rather than facing the open ocean.<br>What links the resource to the settlement here?',
    options:['The lagoon gives sheltered water where boats and fish can be worked','The open ocean has no fish, so a village there would have no purpose','Lagoon villages are closer to the towns where the fish is later sold','Facing the ocean is forbidden, so the villages had to turn inwards'],
    answer:'The lagoon gives sheltered water where boats and fish can be worked',
    hint:'The resource is not only the fish — it is the water you must work in.',
    explanation:'Calm lagoon water lets small boats launch, land and set nets <b>safely nearly every day</b>, which is what makes a fishing village viable. The open sea holds plenty of fish; it is simply harder and riskier to work.' }),

  makeMCQ({ id:'g7sms-hd-056', chapterId:'g7sms-resources', subsection:'resources_settlement', difficulty:4,
    question:'Power stations that burn bagasse are built beside sugar mills, and the mills themselves stand in the middle of the cane fields.<br>Why does that chain of locations make sense?',
    options:['Bagasse is bulky and wet, so it is cheapest to burn where it is made','Cane grows better next to a power station, because of the extra warmth','Mills must be built near the coast, and the power stations follow them there','Bagasse is easy to carry, so distance never affects where it is burned'],
    answer:'Bagasse is bulky and wet, so it is cheapest to burn where it is made',
    hint:'Compare the cost of moving heavy wet fibre with the cost of moving electricity.',
    explanation:'Cane is heavy, so mills sit among the fields; the bagasse they produce is bulkier still, so it is burned <b>on the spot and the electricity sent out along wires</b> instead. Moving power is far cheaper than moving fibre.' })

);
})();
