'use strict';
// Grade 6 French - Textes à Trous, deuxième série (ids 021+). DEUX PARTIES.
//
// ⚠ Partie A : cinq trous remplis avec les mots de la banque.
//   Partie B : cinq trous SANS banque — l'enfant écrit lui-même. C'est là que
//   vivent les mots grammaticaux (qui, dont, parce que, jusqu'à ce que) et on ne
//   peut pas les proposer dans un cadre sans donner la grammaire.
//
// ⚠ CHAQUE TROU DE LA PARTIE B PREND UNE LISTE de réponses acceptées, la
//   première étant le modèle. makeCloze passe answersB par gapAlts exactement
//   pour cela : « mais » et « pourtant » sont tous les deux justes, et refuser
//   le meilleur mot est la seule faute que cet exercice ne peut pas se
//   permettre. Une chaîne seule là où il faut une liste refuse du bon français
//   sans que personne ne s'en aperçoive.
(function () {
  const CH = 'g6fr-textes-trous';
  const add = (n, title, text, bank, answers, notes, textB, answersB, notesB, introB, difficulty) =>
    STATIC_QUESTIONS.push(makeCloze({
      id: `g6fr-clz-${String(n).padStart(3, '0')}`,
      chapterId: CH, subsection: 'texte_a_trous', difficulty: difficulty || 3,
      title, text, bank, answers, notes, textB, answersB, notesB, introB,
    }));

  add(21, 'L\'homme qui comptait les oiseaux',
    'Pendant trente et un ans, monsieur Bhugeerathee a parcouru le même {1} dans les gorges de Rivière Noire, chaque dimanche matin. Il emportait un carnet, un crayon et une vieille paire de {2}. Il n\'était pas {3} et personne ne le payait. Il comptait simplement les oiseaux. Quand la crécerelle de Maurice est tombée à quatre individus connus, ses carnets se sont révélés l\'un des rares {4} continus dont on {5} pour savoir où les oiseaux se nourrissaient encore.',
    ['chemin', 'jumelles', 'scientifique', 'relevés', 'disposait', 'tambour'],
    ['chemin', 'jumelles', 'scientifique', 'relevés', 'disposait'],
    ['Le même ___ chaque dimanche : le trajet qu\'il suivait.',
      'Ce avec quoi on observe des oiseaux de loin.',
      'Il n\'était pas ___ : ce n\'était pas son métier.',
      'Des ___ continus : des notes prises régulièrement.',
      'Dont on ___ : dont on disposait, qu\'on avait.'],
    'L\'équipe de conservation est venue le voir en 1979, {6} elle avait appris qu\'il observait la même vallée depuis des années. Il leur a tout donné {7} rien demander en retour. La crécerelle s\'est lentement rétablie, {8} elle reste l\'un des oiseaux les plus rares du monde. Monsieur Bhugeerathee a continué à marcher {9} l\'âge de quatre-vingt-quatre ans. Il disait que pour être utile, il suffit de faire la même chose, soigneusement, pendant très {10}.',
    [['parce qu\'', 'car', 'puisqu\'', 'comme'],
      ['sans'],
      ['mais', 'pourtant', 'même si', 'bien qu\''],
      ['jusqu\'à'],
      ['longtemps']],
    ['Introduit la raison de leur visite.',
      '___ rien demander : la préposition qui exprime l\'absence.',
      'Oppose le rétablissement à la rareté qui demeure.',
      'Il a marché ___ l\'âge de quatre-vingt-quatre ans.',
      'Pendant très ___ : la durée.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  add(22, 'Les tortues de Rodrigues',
    'Il y a quatre cents ans, les tortues géantes {1} Rodrigues par milliers. Les marins qui s\'arrêtaient sur l\'île en emportaient des centaines : la {2} se conservait vivante à bord pendant des mois, ce qui était précieux avant l\'invention du {3}. En moins de deux siècles, l\'espèce locale avait {4}. Aujourd\'hui, une réserve de l\'île élève des tortues venues d\'Aldabra, une espèce {5}.',
    ['couvraient', 'viande', 'froid', 'disparu', 'cousine', 'échelle'],
    ['couvraient', 'viande', 'froid', 'disparu', 'cousine'],
    ['Les tortues ___ l\'île : imparfait, elles étaient partout.',
      'Ce que les marins emportaient pour manger.',
      'Avant l\'invention du ___ : du réfrigérateur.',
      'L\'espèce locale avait ___ : elle n\'existait plus.',
      'Une espèce ___ : proche parente.'],
    'Ces tortues ne remplacent pas celles {6} on a perdues, {7} elles mangent les mêmes plantes et dispersent les mêmes graines. La forêt retrouve donc une partie de ce {8} lui manquait. Les gardiens de la réserve expliquent {9} il faudra encore des dizaines d\'années avant de savoir si cela a vraiment marché. En attendant, ils comptent, ils notent, et ils {10}.',
    [['qu\''],
      ['mais', 'pourtant', 'cependant'],
      ['qui'],
      ['qu\''],
      ['attendent', 'patientent', 'continuent']],
    ['Pronom relatif complément d\'objet : celles ___ on a perdues.',
      'Oppose « ne remplacent pas » à « mangent les mêmes plantes ».',
      'Ce ___ lui manquait : pronom relatif sujet.',
      'Introduit ce qu\'ils expliquent.',
      'Ce qu\'ils font, en plus de compter et de noter.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  add(23, 'La bagasse',
    'Quand on écrase la canne à sucre, le jus s\'écoule et il reste une {1} sèche qu\'on appelle la bagasse. Pendant longtemps, ce n\'était qu\'un {2} : on l\'entassait à côté de l\'usine. Puis quelqu\'un a remarqué qu\'elle brûlait très {3}. Aujourd\'hui, plusieurs usines de Maurice brûlent la bagasse pour produire de la {4}, et la vapeur fait tourner des turbines qui produisent de l\'{5}.',
    ['fibre', 'déchet', 'bien', 'vapeur', 'électricité', 'boussole'],
    ['fibre', 'déchet', 'bien', 'vapeur', 'électricité'],
    ['Ce qui reste de la canne après l\'écrasement.',
      'Ce n\'était qu\'un ___ : quelque chose dont on veut se débarrasser.',
      'Elle brûlait très ___ : adverbe.',
      'Ce qu\'on produit en chauffant de l\'eau.',
      'Ce que produisent les turbines.'],
    'La canne repousse chaque année, {6} le combustible repousse avec elle. Une chose {7} posait problème aide maintenant à éclairer l\'île. Il vaut la peine de se rappeler {8} personne n\'a inventé la bagasse : elle était là depuis toujours, à côté de l\'usine, en attendant {9} quelqu\'un la regarde autrement. Les meilleures idées ne sont pas toujours des choses nouvelles ; ce sont parfois des choses anciennes {10} on finit par comprendre.',
    [['donc', 'et', 'si bien que', 'alors'],
      ['qui'],
      ['que'],
      ['que'],
      ['qu\'']],
    ['Exprime la conséquence : la canne repousse, ___ le combustible aussi.',
      'Une chose ___ posait problème : pronom relatif sujet.',
      'Se rappeler ___ personne n\'a inventé : introduit la subordonnée.',
      'En attendant ___ quelqu\'un la regarde : suivi du subjonctif.',
      'Des choses anciennes ___ on finit par comprendre : complément d\'objet.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  add(24, 'Le train qui n\'existe plus',
    'Jusqu\'en 1964, une ligne de {1} traversait Maurice de Port-Louis à Mahébourg. Elle transportait surtout la canne à sucre, mais les gens y montaient aussi : c\'était le moyen le plus {2} d\'aller d\'un bout de l\'île à l\'autre. Puis les camions sont devenus moins {3}, la ligne a été fermée et les rails ont été {4}. Aujourd\'hui, il ne reste presque rien, sauf quelques ponts et le nom de certains {5}.',
    ['chemin', 'simple', 'chers', 'enlevés', 'quartiers', 'casserole'],
    ['chemin', 'simple', 'chers', 'enlevés', 'quartiers'],
    ['Une ligne de ___ de fer.',
      'Le moyen le plus ___ de traverser l\'île.',
      'Les camions sont devenus moins ___ : moins coûteux.',
      'Les rails ont été ___ : on les a retirés.',
      'Le nom de certains ___ garde le souvenir de la gare.'],
    'Mon grand-père se souvient encore du bruit {6} faisait le train le soir. Il dit que sa mère savait l\'heure {7} regarder la pendule, simplement en l\'écoutant passer. Beaucoup de pays ont fermé leurs petites lignes à la même époque, {8} plusieurs les regrettent aujourd\'hui. Reconstruire coûterait bien plus cher {9} entretenir n\'aurait coûté. C\'est souvent ainsi : on ne mesure ce qu\'une chose valait {10} le jour où elle a disparu.',
    [['que'],
      ['sans'],
      ['et', 'mais'],
      ['qu\''],
      ['que']],
    ['Le bruit ___ faisait le train : pronom relatif complément.',
      'Savait l\'heure ___ regarder la pendule : sans le faire.',
      'Relie la fermeture au regret d\'aujourd\'hui.',
      'Coûterait plus cher ___ entretenir n\'aurait coûté : comparaison.',
      '« ne… ___ » : on ne le mesure qu\'à ce moment-là.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  add(25, 'Le pigeon rose',
    'Dans les années 1970, il ne restait qu\'une dizaine de pigeons roses dans toute la {1}. L\'espèce ne vit nulle part ailleurs qu\'à Maurice. Des biologistes ont commencé à en élever en {2}, puis à relâcher les jeunes oiseaux dans les forêts protégées du sud-ouest. Ils ont aussi installé des {3} de nourriture, parce que les arbres indigènes dont l\'oiseau dépend étaient devenus trop {4}. Aujourd\'hui la population dépasse les cinq {5}.',
    ['nature', 'captivité', 'points', 'rares', 'cents', 'échelle'],
    ['nature', 'captivité', 'points', 'rares', 'cents'],
    ['Une dizaine d\'oiseaux dans toute la ___.',
      'Élever en ___ : le contraire de en liberté.',
      'Des ___ de nourriture installés en forêt.',
      'Les arbres indigènes étaient devenus trop ___.',
      'La population dépasse les cinq ___.'],
    'Ce n\'est pas une victoire complète, {6} l\'oiseau reste dépendant de l\'aide humaine : si les points de nourriture disparaissaient, personne ne sait {7} la population résisterait. Les biologistes {8} travaillent sur ce projet le disent eux-mêmes. Ils expliquent aussi {9} sauver une espèce prend beaucoup plus de temps que la perdre, et qu\'on ne sait jamais à l\'avance {10} cela va marcher.',
    [['car', 'parce que', 'puisque'],
      ['si'],
      ['qui'],
      ['que'],
      ['si']],
    ['Introduit la raison pour laquelle ce n\'est pas complet.',
      'Personne ne sait ___ la population résisterait : condition.',
      'Les biologistes ___ travaillent : pronom relatif sujet.',
      'Ils expliquent ___ sauver prend du temps.',
      'On ne sait jamais ___ cela va marcher.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  add(26, 'Le cyclone Carol',
    'Le cyclone Carol a traversé Maurice en février 1960. Les vents ont dépassé deux cent cinquante kilomètres à l\'{1}. Des dizaines de milliers de maisons, construites en {2} et en paille, n\'ont pas résisté. C\'est après Carol que l\'on a commencé à construire en {3} presque partout dans l\'île, et que le système d\'alerte par classes a pris la forme qu\'on lui connaît {4}. Mes grands-parents en parlent encore comme d\'une {5} qui a coupé leur vie en deux.',
    ['heure', 'bois', 'béton', 'aujourd\'hui', 'date', 'boussole'],
    ['heure', 'bois', 'béton', 'aujourd\'hui', 'date'],
    ['Kilomètres à l\'___ : l\'unité de vitesse.',
      'Les maisons étaient en ___ et en paille.',
      'On a commencé à construire en ___ : le matériau solide.',
      'La forme qu\'on lui connaît ___.',
      'Une ___ qui a coupé leur vie en deux.'],
    'On raconte souvent Carol comme une catastrophe, {6} est exact. On oublie plus facilement ce {7} est venu après : des maisons plus solides, des alertes plus claires, et une génération {8} a appris à préparer l\'eau et les bougies avant que le vent ne se {9}. Un pays n\'oublie pas un cyclone pareil. Il change simplement sa façon de {10}.',
    [['ce qui'],
      ['qui'],
      ['qui'],
      ['lève'],
      ['construire', 'bâtir']],
    ['Reprend toute la phrase précédente : « ___ est exact ».',
      'Ce ___ est venu après : pronom relatif sujet.',
      'Une génération ___ a appris : pronom relatif sujet.',
      'Avant que le vent ne se ___ : subjonctif.',
      'Sa façon de ___ : ce que le pays change.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  add(27, 'La marée du matin',
    'Monsieur Louis pousse sa barque à l\'eau avant que le soleil ne se {1}. Il pêche dans le lagon de Mahébourg depuis plus de trente ans et il dit que le poisson s\'approche du bord tant que l\'eau est encore {2}. Il lit la mer comme d\'autres lisent le {3} : un changement dans la couleur de l\'eau lui indique où le sable s\'arrête et où le corail {4}. Les plus jeunes achètent de gros moteurs et vont plus {5}, au-delà du récif.',
    ['lève', 'fraîche', 'journal', 'commence', 'loin', 'lanterne'],
    ['lève', 'fraîche', 'journal', 'commence', 'loin'],
    ['Avant que le soleil ne se ___ : subjonctif.',
      'Tant que l\'eau est encore ___ : pas encore chaude.',
      'Ce que d\'autres lisent tous les jours.',
      'Là où le corail ___ : où il débute.',
      'Ils vont plus ___ : au-delà du récif.'],
    'Monsieur Louis, lui, reste où il est. « Un homme {6} connaît bien un seul endroit, dit-il, mangera toujours. » Certains matins il rentre avec très {7}. Cela ne semble pas le déranger : il répare son filet sur le sable, salue tous ceux {8} passent, et repart le lendemain. Son petit-fils veut devenir médecin, et monsieur Louis en parle à {9} le monde avec une fierté {10} il ne cherche même pas à cacher.',
    [['qui'],
      ['peu'],
      ['qui'],
      ['tout'],
      ['qu\'']],
    ['Un homme ___ connaît bien un endroit : pronom relatif sujet.',
      'Il rentre avec très ___ : presque rien.',
      'Tous ceux ___ passent : pronom relatif sujet.',
      'À ___ le monde : l\'expression figée.',
      'Une fierté ___ il ne cherche pas à cacher : complément d\'objet.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  add(28, 'La carte de bibliothèque',
    'La bibliothèque municipale donne une carte à qui la {1}, et cela ne coûte {2}. Il faut une adresse, et rien de plus. Ma mère m\'y a emmenée un samedi matin, quand j\'avais sept ans. La bibliothécaire a écrit mon nom sur la carte à l\'{3} bleue, très soigneusement, et m\'a dit que je pouvais emporter trois livres à la {4}. Je me souviens d\'avoir été étonnée que personne ne demande d\'{5}.',
    ['demande', 'rien', 'encre', 'fois', 'argent', 'ancre'],
    ['demande', 'rien', 'encre', 'fois', 'argent'],
    ['À qui la ___ : à toute personne qui en fait la demande.',
      'Cela ne coûte ___ : la négation, c\'est gratuit.',
      'Écrit à l\'___ bleue.',
      'Trois livres à la ___ : l\'expression figée.',
      'Personne ne demande d\'___.'],
    'J\'ai eu une carte dans chaque ville {6} j\'ai habité depuis. Les bibliothèques de quartier ne sont pas des endroits très élégants, {7} elles sont l\'un des rares bâtiments où l\'on peut entrer sans {8} rien acheter. C\'est plus rare qu\'on ne le croit. Un enfant {9} la famille n\'a pas les moyens d\'acheter des livres peut tout lire, et personne dans le bâtiment n\'a besoin de savoir {10} il est.',
    [['où'],
      ['mais', 'pourtant', 'cependant'],
      ['devoir'],
      ['dont'],
      ['qui']],
    ['Chaque ville ___ j\'ai habité : pronom relatif de lieu.',
      'Oppose « pas élégants » à ce qui suit.',
      'Entrer sans ___ rien acheter : l\'infinitif après « sans ».',
      'Un enfant ___ la famille n\'a pas les moyens : possession.',
      'Savoir ___ il est : pronom interrogatif pour une personne.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  add(29, 'L\'usine de thé',
    'Sur la route de Bois Chéri, les champs de thé couvrent les collines comme un tapis {1}. La plante aime la pluie et la fraîcheur, ce qui explique pourquoi on la cultive sur les {2} du centre et non sur la côte. On ne cueille que le bourgeon et les deux premières {3}, toujours à la main, parce qu\'une machine ne sait pas faire la {4} entre une jeune feuille et une vieille. Le reste se passe à l\'usine : flétrissage, roulage, {5} et séchage.',
    ['vert', 'hauteurs', 'feuilles', 'différence', 'fermentation', 'bateau'],
    ['vert', 'hauteurs', 'feuilles', 'différence', 'fermentation'],
    ['Un tapis ___ : la couleur du thé en champ.',
      'Les ___ du centre : les endroits élevés.',
      'On cueille le bourgeon et les deux premières ___.',
      'Faire la ___ entre une jeune et une vieille feuille.',
      'L\'étape entre le roulage et le séchage.'],
    'Les visiteurs sont souvent surpris d\'apprendre {6} tout cela se fait encore en grande partie à la main. Ils le sont davantage quand on leur dit {7} une cueilleuse expérimentée reconnaît la bonne feuille sans la {8}. Elle le fait des milliers de fois par jour, {9} elle ne se trompe presque jamais. Il y a des savoir-faire {10} aucune machine n\'a encore remplacés.',
    [['que'],
      ['qu\''],
      ['regarder'],
      ['et', 'mais', 'pourtant'],
      ['qu\'']],
    ['Surpris d\'apprendre ___ tout se fait à la main.',
      'Quand on leur dit ___ une cueilleuse reconnaît.',
      'Sans la ___ : l\'infinitif après « sans ».',
      'Des milliers de fois par jour, ___ elle ne se trompe pas.',
      'Des savoir-faire ___ aucune machine n\'a remplacés : complément.'],
    'écris UN mot qui convient dans chaque trou. Il n\'y a pas de cadre pour cette partie.');

  console.log('[g6fr-textes-trous] série B loaded');
})();
