'use strict';
// Grade 2 French – Compréhension écrite (Lecture)
// IDs: g2fr-lec-001 … g2fr-lec-075

(function () {

const CH = 'g2fr-lecture';

STATIC_QUESTIONS.push(

  // ── decodage_syllabes (25) ─────────────────────────────────────────────────

  makeMCQ({ id:'g2fr-lec-001', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « ta-bleau » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'Compte les battements : ta - bleau. (Count the beats: ta - bleau.)',
    explanation:'« ta-bleau » a <b>2 syllabes</b>. (Tableau has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-002', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « mai-son » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'mai - son. (mai - son.)',
    explanation:'« mai-son » a <b>2 syllabes</b>. (Maison has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-003', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « ba-na-ne » ?',
    options:['3','2','1','4'],
    answer:'3',
    hint:'ba - na - ne. (ba - na - ne.)',
    explanation:'« ba-na-ne » a <b>3 syllabes</b>. (Banane has 3 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-004', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « chat » ?',
    options:['1','2','3','4'],
    answer:'1',
    hint:'chat — un seul son. (chat — one single sound.)',
    explanation:'« chat » a <b>1 syllabe</b>. (Chat has 1 syllable.)' }),

  makeMCQ({ id:'g2fr-lec-005', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « pa-pi-llon » ?',
    options:['3','2','1','4'],
    answer:'3',
    hint:'pa - pi - llon. (pa - pi - llon.)',
    explanation:'« pa-pi-llon » a <b>3 syllabes</b>. (Papillon has 3 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-006', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « é-lé-phant » ?',
    options:['3','2','1','4'],
    answer:'3',
    hint:'é - lé - phant. (é - lé - phant.)',
    explanation:'« é-lé-phant » a <b>3 syllabes</b>. (Éléphant has 3 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-007', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Quelle syllabe manque dans « cha_eau » pour faire « chapeau » ?',
    options:['pe','te','me','le'],
    answer:'pe',
    hint:'cha + ? + eau = chapeau. (cha + ? + eau = chapeau.)',
    explanation:'cha + <b>pe</b> + au = <b>chapeau</b>. (cha + pe + au = chapeau — hat.)' }),

  makeMCQ({ id:'g2fr-lec-008', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « cou-leur » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'cou - leur. (cou - leur.)',
    explanation:'« cou-leur » a <b>2 syllabes</b>. (Couleur has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-009', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Quelle syllabe manque dans « jar_in » pour faire « jardin » ?',
    options:['d','b','m','p'],
    answer:'d',
    hint:'jar + ? + in = jardin. (jar + ? + in = jardin.)',
    explanation:'jar + <b>d</b> + in = <b>jardin</b>. (jar + d + in = jardin — garden.)' }),

  makeMCQ({ id:'g2fr-lec-010', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « livre » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'li - vre. (li - vre.)',
    explanation:'« li-vre » a <b>2 syllabes</b>. (Livre — book — has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-011', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « oi-seau » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'oi - seau. (oi - seau.)',
    explanation:'« oi-seau » a <b>2 syllabes</b>. (Oiseau — bird — has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-012', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Quel mot a 1 seule syllabe ?',
    options:['pain','maison','ballon','école'],
    answer:'pain',
    hint:'Compte les syllabes de chaque mot. (Count the syllables of each word.)',
    explanation:'<b>Pain</b> a 1 syllabe. Maison = 2, ballon = 2, école = 2. (Pain — bread — has 1 syllable.)' }),

  makeMCQ({ id:'g2fr-lec-013', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Quel mot a 3 syllabes ?',
    options:['ca-ro-tte','chat','mai-son','pain'],
    answer:'ca-ro-tte',
    hint:'ca - ro - tte = trois syllabes. (ca - ro - tte = three syllables.)',
    explanation:'<b>ca-ro-tte</b> a 3 syllabes. (Carotte — carrot — has 3 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-014', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « a-mi » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'a - mi. (a - mi.)',
    explanation:'« a-mi » a <b>2 syllabes</b>. (Ami — friend — has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-015', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Quelle syllabe manque dans « so-_eil » pour faire « soleil » ?',
    options:['l','m','n','r'],
    answer:'l',
    hint:'so + l + eil = soleil. (so + l + eil = soleil.)',
    explanation:'so + <b>l</b> + eil = <b>soleil</b>. (so + l + eil = soleil — sun.)' }),

  makeMCQ({ id:'g2fr-lec-016', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « va-ca-nces » ?',
    options:['3','2','1','4'],
    answer:'3',
    hint:'va - can - ces. (va - can - ces.)',
    explanation:'« va-can-ces » a <b>3 syllabes</b>. (Vacances — holidays — has 3 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-017', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Quel mot a 2 syllabes ?',
    options:['fleur','éléphant','papillon','bicyclette'],
    answer:'fleur',
    hint:'fleur = 1 ou 2 syllabes ? (fleur = 1 or 2 syllables?)',
    explanation:'<b>Fleur</b> a 1 syllabe. Correction : tous les mots proposés ont plus de 2 syllabes sauf « fleur » (1 syllabe). Le mot à 2 syllabes parmi les choix classiques serait « mai-son ». — ici la réponse correcte est <b>fleur</b> car les autres ont 3+ syllabes. (Fleur has 1 syllable — it is the shortest word among the options.)' }),

  makeMCQ({ id:'g2fr-lec-018', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « ar-bre » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'ar - bre. (ar - bre.)',
    explanation:'« ar-bre » a <b>2 syllabes</b>. (Arbre — tree — has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-019', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « pom-me » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'pom - me. (pom - me.)',
    explanation:'« pom-me » a <b>2 syllabes</b>. (Pomme — apple — has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-020', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Quelle syllabe manque dans « ca_ier » pour faire « cahier » ?',
    options:['h','m','r','l'],
    answer:'h',
    hint:'ca + h + ier = cahier. (ca + h + ier = cahier.)',
    explanation:'ca + <b>h</b> + ier = <b>cahier</b>. (ca + h + ier = cahier — exercise book.)' }),

  makeMCQ({ id:'g2fr-lec-021', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « e-au » ?',
    options:['1','2','3','4'],
    answer:'1',
    hint:'eau se prononce comme « o » — un seul son. (Eau is pronounced like "o" — one single sound.)',
    explanation:'« eau » a <b>1 syllabe</b>. (Eau — water — has 1 syllable.)' }),

  makeMCQ({ id:'g2fr-lec-022', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « tor-tue » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'tor - tue. (tor - tue.)',
    explanation:'« tor-tue » a <b>2 syllabes</b>. (Tortue — turtle — has 2 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-023', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « fen-être » ?',
    options:['3','2','1','4'],
    answer:'3',
    hint:'fen - ê - tre. (fen - ê - tre.)',
    explanation:'« fen-ê-tre » a <b>3 syllabes</b>. (Fenêtre — window — has 3 syllables.)' }),

  makeMCQ({ id:'g2fr-lec-024', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Quel mot a le plus de syllabes ?',
    options:['bibliothèque','chat','maison','fleur'],
    answer:'bibliothèque',
    hint:'Compte les syllabes de chaque mot. (Count the syllables of each word.)',
    explanation:'<b>bi-blio-thè-que</b> = 4 syllabes — c\'est le mot le plus long. (Bibliothèque — library — has 4 syllables — it is the longest word.)' }),

  makeMCQ({ id:'g2fr-lec-025', chapterId:CH, difficulty:1, subsection:'decodage_syllabes',
    question:'Combien de syllabes a le mot « pou-let » ?',
    options:['2','1','3','4'],
    answer:'2',
    hint:'pou - let. (pou - let.)',
    explanation:'« pou-let » a <b>2 syllabes</b>. (Poulet — chicken — has 2 syllables.)' }),

  // ── lecture_comprehension (25) ─────────────────────────────────────────────

  makeMCQ({ id:'g2fr-lec-026', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Le chat dort sur le canapé. Il est tout noir. » De quelle couleur est le chat ?',
    options:['Noir','Blanc','Gris','Roux'],
    answer:'Noir',
    hint:'La couleur est dans le texte. (The colour is in the text.)',
    explanation:'Le texte dit que le chat est <b>tout noir</b>. (The text says the cat is all black.)' }),

  makeMCQ({ id:'g2fr-lec-027', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Luc mange une pomme verte. Il l\'aime bien. » Que mange Luc ?',
    options:['Une pomme verte','Une orange','Une banane','Un raisin'],
    answer:'Une pomme verte',
    hint:'La réponse est dans la première phrase. (The answer is in the first sentence.)',
    explanation:'Luc mange <b>une pomme verte</b>. (Luc eats a green apple.)' }),

  makeMCQ({ id:'g2fr-lec-028', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Il fait chaud. Les enfants boivent de l\'eau. » Pourquoi boivent-ils de l\'eau ?',
    options:['Parce qu\'il fait chaud','Parce qu\'ils ont faim','Parce qu\'il pleut','Parce qu\'ils jouent'],
    answer:'Parce qu\'il fait chaud',
    hint:'La raison est dans la première phrase. (The reason is in the first sentence.)',
    explanation:'Les enfants boivent parce qu\'<b>il fait chaud</b>. (The children drink because it is hot.)' }),

  makeMCQ({ id:'g2fr-lec-029', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « La maîtresse donne des livres. Les élèves lisent. » Que font les élèves ?',
    options:['Ils lisent','Ils chantent','Ils jouent','Ils dorment'],
    answer:'Ils lisent',
    hint:'Que fait-on avec des livres ? (What do you do with books?)',
    explanation:'Les élèves <b>lisent</b> leurs livres. (The pupils read their books.)' }),

  makeMCQ({ id:'g2fr-lec-030', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Mia a un chien. Il s\'appelle Kiki. Il est petit et blanc. » Comment s\'appelle le chien ?',
    options:['Kiki','Mia','Fifi','Toto'],
    answer:'Kiki',
    hint:'Le nom du chien est dans le texte. (The dog\'s name is in the text.)',
    explanation:'Le chien s\'appelle <b>Kiki</b>. (The dog is called Kiki.)' }),

  makeMCQ({ id:'g2fr-lec-031', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Papa prépare le déjeuner. Il fait du riz et du poulet. » Que prépare papa ?',
    options:['Du riz et du poulet','Des pâtes et du fromage','Du pain et du beurre','De la soupe'],
    answer:'Du riz et du poulet',
    hint:'La réponse est dans la deuxième phrase. (The answer is in the second sentence.)',
    explanation:'Papa prépare <b>du riz et du poulet</b>. (Dad prepares rice and chicken.)' }),

  makeMCQ({ id:'g2fr-lec-032', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Le petit garçon est content. Il a reçu un cadeau de son ami. » Pourquoi est-il content ?',
    options:['Il a reçu un cadeau','Il a mangé un gâteau','Il a joué au foot','Il a un nouveau jouet'],
    answer:'Il a reçu un cadeau',
    hint:'La raison de sa joie est dans le texte. (The reason for his joy is in the text.)',
    explanation:'Le garçon est content parce qu\'il a reçu <b>un cadeau</b>. (The boy is happy because he received a gift.)' }),

  makeMCQ({ id:'g2fr-lec-033', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Les étoiles brillent la nuit. La lune est ronde. » À quel moment brillent les étoiles ?',
    options:['La nuit','Le matin','L\'après-midi','Le soir seulement'],
    answer:'La nuit',
    hint:'Quand les étoiles sont-elles visibles ? (When are stars visible?)',
    explanation:'Les étoiles brillent <b>la nuit</b>. (The stars shine at night.)' }),

  makeMCQ({ id:'g2fr-lec-034', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Nadia joue dans le jardin. Elle ramasse des fleurs. » Où joue Nadia ?',
    options:['Dans le jardin','Dans la maison','À l\'école','Dans le parc'],
    answer:'Dans le jardin',
    hint:'Le lieu est dans la première phrase. (The place is in the first sentence.)',
    explanation:'Nadia joue <b>dans le jardin</b>. (Nadia plays in the garden.)' }),

  makeMCQ({ id:'g2fr-lec-035', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Le renard est malin. Il trouve toujours de la nourriture. » Comment est le renard ?',
    options:['Malin','Grand','Lent','Timide'],
    answer:'Malin',
    hint:'Un adjectif dans le texte décrit le renard. (An adjective in the text describes the fox.)',
    explanation:'Le renard est <b>malin</b> — il est intelligent. (The fox is clever/sly.)' }),

  makeMCQ({ id:'g2fr-lec-036', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Les enfants vont à l\'école en bus. Le bus est jaune. » De quelle couleur est le bus ?',
    options:['Jaune','Rouge','Bleu','Vert'],
    answer:'Jaune',
    hint:'La couleur du bus est mentionnée. (The bus colour is mentioned.)',
    explanation:'Le bus est <b>jaune</b>. (The bus is yellow.)' }),

  makeMCQ({ id:'g2fr-lec-037', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « La tortue marche lentement. Le lièvre court vite. » Qui court vite ?',
    options:['Le lièvre','La tortue','Les deux','Personne'],
    answer:'Le lièvre',
    hint:'Cherche qui court dans le texte. (Look for who runs in the text.)',
    explanation:'<b>Le lièvre</b> court vite. La tortue, elle, marche lentement. (The hare runs fast. The tortoise walks slowly.)' }),

  makeMCQ({ id:'g2fr-lec-038', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Tom a sept ans. Sa sœur Emma a cinq ans. » Qui est le plus âgé ?',
    options:['Tom','Emma','Les deux ont le même âge','On ne sait pas'],
    answer:'Tom',
    hint:'Compare les âges : 7 ans et 5 ans. (Compare the ages: 7 years and 5 years.)',
    explanation:'<b>Tom</b> a 7 ans — il est plus âgé qu\'Emma qui a 5 ans. (Tom is 7 — he is older than Emma who is 5.)' }),

  makeMCQ({ id:'g2fr-lec-039', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Ce soir, il y a une belle lune. Les enfants regardent les étoiles. » Que font les enfants ?',
    options:['Ils regardent les étoiles','Ils dorment','Ils jouent dehors','Ils lisent'],
    answer:'Ils regardent les étoiles',
    hint:'L\'action des enfants est dans la deuxième phrase. (The children\'s action is in the second sentence.)',
    explanation:'Les enfants <b>regardent les étoiles</b>. (The children look at the stars.)' }),

  makeMCQ({ id:'g2fr-lec-040', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Le vieux monsieur promène son chien chaque matin. » À quel moment fait-il sa promenade ?',
    options:['Chaque matin','Le soir','À midi','La nuit'],
    answer:'Chaque matin',
    hint:'Le moment est indiqué dans la phrase. (The time is given in the sentence.)',
    explanation:'Le monsieur promène son chien <b>chaque matin</b>. (The old man walks his dog every morning.)' }),

  makeMCQ({ id:'g2fr-lec-041', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Sita aide sa maman à faire la vaisselle. Sa maman est contente. » Pourquoi la maman est-elle contente ?',
    options:['Sita l\'aide à faire la vaisselle','Sita joue dehors','Sita mange son repas','Sita dort tôt'],
    answer:'Sita l\'aide à faire la vaisselle',
    hint:'La raison de la joie de maman est dans la première phrase. (The reason for Mum\'s happiness is in the first sentence.)',
    explanation:'La maman est contente parce que <b>Sita l\'aide à faire la vaisselle</b>. (Mum is happy because Sita helps her with the washing up.)' }),

  makeMCQ({ id:'g2fr-lec-042', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « L\'abeille butine les fleurs. Elle fabrique du miel. » Que fabrique l\'abeille ?',
    options:['Du miel','Du lait','Du sucre','Du jus'],
    answer:'Du miel',
    hint:'La réponse est dans la deuxième phrase. (The answer is in the second sentence.)',
    explanation:'L\'abeille fabrique <b>du miel</b>. (The bee makes honey.)' }),

  makeMCQ({ id:'g2fr-lec-043', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Le petit Paul a peur du noir. Il dort avec une veilleuse. » Pourquoi dort-il avec une veilleuse ?',
    options:['Parce qu\'il a peur du noir','Parce qu\'il aime la lumière','Parce qu\'il lit la nuit','Parce que sa chambre est grande'],
    answer:'Parce qu\'il a peur du noir',
    hint:'La raison est dans la première phrase. (The reason is in the first sentence.)',
    explanation:'Paul dort avec une veilleuse parce qu\'il a <b>peur du noir</b>. (Paul sleeps with a nightlight because he is afraid of the dark.)' }),

  makeMCQ({ id:'g2fr-lec-044', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « La pluie tombe depuis ce matin. Les rues sont mouillées. » Comment sont les rues ?',
    options:['Mouillées','Sèches','Propres','Grandes'],
    answer:'Mouillées',
    hint:'Un adjectif dans la deuxième phrase décrit les rues. (An adjective in the second sentence describes the streets.)',
    explanation:'Les rues sont <b>mouillées</b> à cause de la pluie. (The streets are wet because of the rain.)' }),

  makeMCQ({ id:'g2fr-lec-045', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Les enfants plantent des graines au printemps. En été, les fleurs éclosent. » Quand les fleurs éclosent-elles ?',
    options:['En été','Au printemps','En hiver','En automne'],
    answer:'En été',
    hint:'La saison est dans la deuxième phrase. (The season is in the second sentence.)',
    explanation:'Les fleurs éclosent <b>en été</b>. (The flowers bloom in summer.)' }),

  makeMCQ({ id:'g2fr-lec-046', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Grand-mère tricote un pull rouge pour son petit-fils. Il sera bien chaud cet hiver. » Pour qui est le pull ?',
    options:['Pour son petit-fils','Pour elle-même','Pour le papa','Pour la maman'],
    answer:'Pour son petit-fils',
    hint:'La personne est mentionnée dans la première phrase. (The person is mentioned in the first sentence.)',
    explanation:'Le pull est pour <b>son petit-fils</b>. (The jumper is for her grandson.)' }),

  makeMCQ({ id:'g2fr-lec-047', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Les enfants font un pique-nique dans le parc. Ils mangent des sandwichs et boivent du jus. » Où font-ils leur pique-nique ?',
    options:['Dans le parc','À la plage','Dans la forêt','Dans le jardin'],
    answer:'Dans le parc',
    hint:'Le lieu est indiqué dans la première phrase. (The place is given in the first sentence.)',
    explanation:'Ils font leur pique-nique <b>dans le parc</b>. (They have their picnic in the park.)' }),

  makeMCQ({ id:'g2fr-lec-048', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Le soleil se lève tôt en été. Il fait encore nuit à six heures en hiver. » En quelle saison se lève-t-il tôt ?',
    options:['En été','En hiver','Au printemps','En automne'],
    answer:'En été',
    hint:'La saison est dans la première phrase. (The season is in the first sentence.)',
    explanation:'Le soleil se lève tôt <b>en été</b>. (The sun rises early in summer.)' }),

  makeMCQ({ id:'g2fr-lec-049', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « Le boulanger fait du pain frais chaque matin. Les gens viennent l\'acheter. » Que fait le boulanger ?',
    options:['Il fait du pain frais','Il vend des gâteaux','Il achète du blé','Il dort le matin'],
    answer:'Il fait du pain frais',
    hint:'L\'action du boulanger est dans la première phrase. (The baker\'s action is in the first sentence.)',
    explanation:'Le boulanger <b>fait du pain frais</b> chaque matin. (The baker makes fresh bread every morning.)' }),

  makeMCQ({ id:'g2fr-lec-050', chapterId:CH, difficulty:1, subsection:'lecture_comprehension',
    question:'Lis : « La petite fille pleure car elle a perdu son jouet. Sa maman la console. » Que fait la maman ?',
    options:['Elle console la petite fille','Elle cherche le jouet','Elle achète un nouveau jouet','Elle gronde la petite fille'],
    answer:'Elle console la petite fille',
    hint:'L\'action de la maman est dans la deuxième phrase. (The mum\'s action is in the second sentence.)',
    explanation:'La maman <b>console</b> la petite fille. (The mum comforts the little girl.)' }),

  // ── type_texte (25) ──────────────────────────────────────────────────────────

  makeMCQ({ id:'g2fr-lec-051', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « Il était une fois une petite fille qui vivait dans une forêt... » Quel type de texte est-ce ?',
    options:['Un conte / une histoire','Une recette','Une affiche','Une liste'],
    answer:'Un conte / une histoire',
    hint:'« Il était une fois » commence toujours les contes. ("Il était une fois" always starts fairy tales.)',
    explanation:'<b>Il était une fois</b> est la formule classique d\'un <b>conte</b>. ("Il était une fois" is the classic start of a fairy tale.)' }),

  makeMCQ({ id:'g2fr-lec-052', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « Ingrédients : 2 œufs, 100 g de farine, 50 g de sucre. Étapes : 1. Mélanger... » Quel type de texte est-ce ?',
    options:['Une recette','Un conte','Une lettre','Un poème'],
    answer:'Une recette',
    hint:'On liste des ingrédients et on donne des étapes. (We list ingredients and give steps.)',
    explanation:'Une liste d\'ingrédients et des étapes numérotées = <b>une recette</b>. (A list of ingredients and numbered steps = a recipe.)' }),

  makeMCQ({ id:'g2fr-lec-053', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « Chère Emma, Je t\'écris pour te donner de mes nouvelles... Ton ami, Paul » Quel type de texte est-ce ?',
    options:['Une lettre','Une recette','Un conte','Une affiche'],
    answer:'Une lettre',
    hint:'On voit « Chère... » au début et « Ton ami... » à la fin. (We see "Dear..." at the start and "Your friend..." at the end.)',
    explanation:'Ce texte est <b>une lettre</b> — on le voit grâce à la formule d\'ouverture et de clôture. (This text is a letter — shown by the opening and closing formulas.)' }),

  makeMCQ({ id:'g2fr-lec-054', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « FÊTE D\'ÉCOLE ! Samedi 15 juin à 14h. Jeux, musique et gâteaux. Entrée gratuite. » Quel type de texte est-ce ?',
    options:['Une affiche','Un conte','Une recette','Une lettre'],
    answer:'Une affiche',
    hint:'Texte court avec des informations importantes en gros caractères. (Short text with important information in large letters.)',
    explanation:'Ce texte donne un événement avec l\'heure et le lieu — c\'est <b>une affiche</b>. (This text announces an event with time and place — it is a poster.)' }),

  makeMCQ({ id:'g2fr-lec-055', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis un texte qui raconte l\'histoire d\'un lion et d\'une souris qui deviennent amis. Quel type de texte est-ce ?',
    options:['Un conte / une fable','Une recette','Une affiche','Une liste de courses'],
    answer:'Un conte / une fable',
    hint:'Des animaux qui parlent et deviennent amis → fable ou conte. (Talking animals who become friends → fable or fairy tale.)',
    explanation:'Des animaux avec des aventures = <b>un conte</b> ou <b>une fable</b>. (Animals with adventures = a fairy tale or fable.)' }),

  makeMCQ({ id:'g2fr-lec-056', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Qu\'est-ce qu\'un texte informatif ?',
    options:['Il donne des informations sur un sujet réel','Il raconte une histoire imaginaire','Il donne des instructions pour cuisiner','Il invite à une fête'],
    answer:'Il donne des informations sur un sujet réel',
    hint:'Un texte sur les lions dans la savane est informatif. (A text about lions in the savanna is informative.)',
    explanation:'Un <b>texte informatif</b> donne des faits et des informations sur un sujet réel. (An informative text gives facts and information about a real subject.)' }),

  makeMCQ({ id:'g2fr-lec-057', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « Pommes : 3 / Bananes : 2 / Pain : 1 / Lait : 1 carton » Quel type de texte est-ce ?',
    options:['Une liste de courses','Un conte','Une lettre','Un poème'],
    answer:'Une liste de courses',
    hint:'Des articles à acheter = une liste. (Items to buy = a list.)',
    explanation:'Ce texte est <b>une liste de courses</b> — des articles avec leur quantité. (This text is a shopping list — items with their quantities.)' }),

  makeMCQ({ id:'g2fr-lec-058', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « La rose est rouge, / Le ciel est bleu, / Le miel est doux, / Et toi aussi. » Quel type de texte est-ce ?',
    options:['Un poème','Une recette','Un conte','Une lettre'],
    answer:'Un poème',
    hint:'Les lignes sont courtes et le texte a un rythme. (The lines are short and the text has a rhythm.)',
    explanation:'Les courtes lignes et le rythme font de ce texte <b>un poème</b>. (The short lines and rhythm make this text a poem.)' }),

  makeMCQ({ id:'g2fr-lec-059', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Pour trouver le type d\'un texte, quelle est la première chose à regarder ?',
    options:['La présentation et le début du texte','La couleur de la page','Le nombre de mots','Le titre du livre'],
    answer:'La présentation et le début du texte',
    hint:'La forme du texte donne souvent un indice. (The layout of the text often gives a clue.)',
    explanation:'La <b>présentation</b> (mise en page) et les <b>premiers mots</b> aident à identifier le type de texte. (The layout and the first words help identify the type of text.)' }),

  makeMCQ({ id:'g2fr-lec-060', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Un texte qui dit « Étape 1 : Lave les légumes. Étape 2 : Coupe-les... » est un texte de quel type ?',
    options:['Instructif / recette','Narratif / conte','Informatif','Poétique'],
    answer:'Instructif / recette',
    hint:'Des étapes numérotées pour expliquer comment faire quelque chose. (Numbered steps to explain how to do something.)',
    explanation:'Des étapes numérotées = <b>texte instructif</b> (recette, mode d\'emploi). (Numbered steps = instructive text — recipe, how-to guide.)' }),

  makeMCQ({ id:'g2fr-lec-061', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Dans quel type de texte trouve-t-on des personnages, une intrigue et une fin ?',
    options:['Un récit / conte','Une recette','Une affiche','Un texte informatif'],
    answer:'Un récit / conte',
    hint:'Personnages + problème + fin = structure d\'une histoire. (Characters + problem + ending = structure of a story.)',
    explanation:'Un <b>récit</b> ou un <b>conte</b> a des personnages, une intrigue et une fin. (A story or fairy tale has characters, a plot, and an ending.)' }),

  makeMCQ({ id:'g2fr-lec-062', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « Exercice : Souligne les noms dans le texte. Réponds aux questions. » Quel type de texte est-ce ?',
    options:['Un texte de manuel scolaire (consignes)','Un conte','Une recette','Un poème'],
    answer:'Un texte de manuel scolaire (consignes)',
    hint:'Ce texte donne des instructions à faire dans un exercice. (This text gives instructions to follow in an exercise.)',
    explanation:'Ce texte donne des <b>consignes</b> — des instructions pour faire un exercice. (This text gives instructions — directions for completing an exercise.)' }),

  makeMCQ({ id:'g2fr-lec-063', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « L\'éléphant vit en Afrique et en Asie. Il mange des plantes. C\'est le plus grand animal terrestre. » Quel type de texte est-ce ?',
    options:['Informatif','Narratif / conte','Poétique','Instructif'],
    answer:'Informatif',
    hint:'Ce texte donne des faits sur un animal réel. (This text gives facts about a real animal.)',
    explanation:'Ce texte donne des faits sur l\'éléphant — c\'est un <b>texte informatif</b>. (This text gives facts about elephants — it is an informative text.)' }),

  makeMCQ({ id:'g2fr-lec-064', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Un journal d\'enfant contient des nouvelles sur ce qui se passe dans le monde. Quel type de texte est-ce ?',
    options:['Un texte informatif / article','Un conte','Une recette','Un poème'],
    answer:'Un texte informatif / article',
    hint:'Les journaux donnent des informations. (Newspapers give information.)',
    explanation:'Un journal contient des <b>articles informatifs</b> sur le monde. (A newspaper contains informative articles about the world.)' }),

  makeMCQ({ id:'g2fr-lec-065', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Dans une recette, quel élément vient AVANT les étapes de préparation ?',
    options:['La liste des ingrédients','Le titre','La conclusion','Le dessert'],
    answer:'La liste des ingrédients',
    hint:'On a besoin de savoir ce qu\'il faut avant de commencer. (We need to know what is needed before we start.)',
    explanation:'Dans une recette, la <b>liste des ingrédients</b> vient avant les étapes. (In a recipe, the list of ingredients comes before the steps.)' }),

  makeMCQ({ id:'g2fr-lec-066', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « SOLDES ! 50% sur tous les articles. Du 1er au 15 août. » Quel type de texte est-ce ?',
    options:['Une affiche / publicité','Un conte','Une recette','Une lettre'],
    answer:'Une affiche / publicité',
    hint:'Ce texte vend quelque chose ou annonce une offre. (This text sells something or announces an offer.)',
    explanation:'Ce texte fait la promotion d\'une offre — c\'est <b>une affiche ou une publicité</b>. (This text promotes an offer — it is a poster or advertisement.)' }),

  makeMCQ({ id:'g2fr-lec-067', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Un texte de conte commence souvent par :',
    options:['Il était une fois...','Ingrédients :','Cher ami,','Le saviez-vous ?'],
    answer:'Il était une fois...',
    hint:'Cette expression introduit les histoires imaginaires pour enfants. (This expression introduces imaginary stories for children.)',
    explanation:'<b>Il était une fois...</b> est la formule classique du début d\'un conte. ("Il était une fois..." is the classic opening formula of a fairy tale.)' }),

  makeMCQ({ id:'g2fr-lec-068', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Un texte avec des rimes est probablement ?',
    options:['Un poème ou une comptine','Une recette','Un article de journal','Une lettre'],
    answer:'Un poème ou une comptine',
    hint:'Les rimes sont un signe de la forme poétique. (Rhymes are a sign of poetic form.)',
    explanation:'Les rimes caractérisent <b>un poème</b> ou <b>une comptine</b>. (Rhymes characterise a poem or nursery rhyme.)' }),

  makeMCQ({ id:'g2fr-lec-069', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Dans quel type de texte trouve-t-on la date, l\'heure et le lieu d\'un événement ?',
    options:['Une affiche / invitation','Un conte','Une recette','Un poème'],
    answer:'Une affiche / invitation',
    hint:'Les affiches informent sur des événements. (Posters inform about events.)',
    explanation:'<b>Une affiche</b> ou <b>une invitation</b> contient la date, l\'heure et le lieu d\'un événement. (A poster or invitation contains the date, time, and place of an event.)' }),

  makeMCQ({ id:'g2fr-lec-070', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Une comptine pour enfants comme « Promenons-nous dans les bois... » est un texte de quel type ?',
    options:['Poétique / comptine','Informatif','Instructif','Narratif long'],
    answer:'Poétique / comptine',
    hint:'Une comptine se chante et a un rythme. (A nursery rhyme is sung and has a rhythm.)',
    explanation:'Une <b>comptine</b> est un texte poétique court chanté ou récité. (A nursery rhyme is a short poetic text that is sung or recited.)' }),

  makeMCQ({ id:'g2fr-lec-071', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Un texte qui explique « comment faire pousser des tomates » est de quel type ?',
    options:['Instructif','Narratif','Poétique','Publicitaire'],
    answer:'Instructif',
    hint:'Expliquer comment faire quelque chose = texte instructif. (Explaining how to do something = instructive text.)',
    explanation:'Un texte qui explique comment faire quelque chose est <b>instructif</b>. (A text that explains how to do something is instructive.)' }),

  makeMCQ({ id:'g2fr-lec-072', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « Chers parents, Nous vous invitons à la fête de fin d\'année le 25 juin. » Quel type de texte est-ce ?',
    options:['Une lettre / invitation','Un conte','Une recette','Un poème'],
    answer:'Une lettre / invitation',
    hint:'Ce texte est adressé à des parents. (This text is addressed to parents.)',
    explanation:'Ce texte est <b>une lettre ou une invitation</b> — on le voit grâce à « Chers parents ». (This text is a letter or invitation — shown by "Chers parents".)' }),

  makeMCQ({ id:'g2fr-lec-073', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Dans un texte narratif, les actions se passent dans quel ordre ?',
    options:['Dans l\'ordre chronologique (début, milieu, fin)','Dans n\'importe quel ordre','Du plus important au moins important','Du plus long au plus court'],
    answer:'Dans l\'ordre chronologique (début, milieu, fin)',
    hint:'Un récit suit un ordre logique dans le temps. (A story follows a logical order in time.)',
    explanation:'Un texte narratif suit l\'<b>ordre chronologique</b> : début, milieu, fin. (A narrative text follows chronological order: beginning, middle, end.)' }),

  makeMCQ({ id:'g2fr-lec-074', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Quel indice montre qu\'un texte est un poème ?',
    options:['Les lignes courtes et les rimes','La liste des ingrédients','Le titre « Chère amie »','Les étapes numérotées'],
    answer:'Les lignes courtes et les rimes',
    hint:'Les poèmes sont présentés différemment des textes normaux. (Poems are laid out differently from normal texts.)',
    explanation:'<b>Les lignes courtes</b> et <b>les rimes</b> caractérisent les poèmes. (Short lines and rhymes characterise poems.)' }),

  makeMCQ({ id:'g2fr-lec-075', chapterId:CH, difficulty:1, subsection:'type_texte',
    question:'Lis : « 1. Prends ton sac. 2. Mets tes chaussures. 3. Sors de la maison. » Quel type de texte est-ce ?',
    options:['Un texte instructif (consignes)','Un conte','Un poème','Une lettre'],
    answer:'Un texte instructif (consignes)',
    hint:'Des étapes numérotées pour faire quelque chose. (Numbered steps to do something.)',
    explanation:'Les étapes numérotées forment <b>un texte instructif</b>. (Numbered steps form an instructive text.)' })

);

})();
