'use strict';
// Grade 7 English — Core questions, all 14 chapters
// IDs: g7eng-<chapter-suffix>-NNN

STATIC_QUESTIONS.push(

  // ── Listening & Comprehension ────────────────────────────────────────────

  makeMCQ({ id:'g7eng-listening-001', chapterId:'g7eng-listening', difficulty:1,
    subsection:'identifying_message',
    question:'A speaker says: "Please remember to bring your permission slips tomorrow. Without them you cannot join the trip." What is the main MESSAGE of this announcement?',
    options:['The trip will be cancelled.','Students must bring permission slips to go on the trip.','Students should arrive early tomorrow.','The trip costs money.'],
    answer:'Students must bring permission slips to go on the trip.',
    hint:'Focus on what the speaker wants the listeners to DO.',
    explanation:'The speaker\'s purpose is to remind students that they <b>need permission slips</b> to join the trip. Identifying the speaker\'s intention — what they want the audience to remember or do — is the key skill in Listening comprehension.' }),

  makeMCQ({ id:'g7eng-listening-002', chapterId:'g7eng-listening', difficulty:2,
    subsection:'identifying_message',
    question:'You hear: "Good morning, passengers. This is your captain speaking. We will shortly be landing at Sir Seewoosagur Ramgoolam International Airport." Who is the AUDIENCE for this message?',
    options:['Airport staff','The air traffic controller','Passengers on the plane','Ground crew'],
    answer:'Passengers on the plane',
    hint:'The speaker addresses the people who are listening directly. Who is on the plane?',
    explanation:'A <b>captain</b> addresses the <b>passengers</b> on the plane. Identifying the audience means asking: "Who is the speaker talking TO?" Clues include the words used (e.g. "passengers") and the setting.' }),

  makeMCQ({ id:'g7eng-listening-003', chapterId:'g7eng-listening', difficulty:2,
    subsection:'vocabulary_context',
    question:'The teacher says: "We will now proceed to the hall." From the context, what does <b>proceed</b> mean?',
    options:['wait','go','run','return'],
    answer:'go',
    hint:'The sentence describes moving from one place to another.',
    explanation:'"<b>Proceed</b>" means to move forward or go. Context clues — the hall as a destination — help you work out the meaning without a dictionary. Learning vocabulary from context is an important listening skill.' }),

  makeMCQ({ id:'g7eng-listening-004', chapterId:'g7eng-listening', difficulty:3,
    subsection:'vocabulary_context',
    question:'You hear a news report: "The authorities have urged residents in low-lying areas to <b>evacuate</b> due to the approaching storm." What does <b>evacuate</b> mean?',
    options:['stay inside and lock doors','leave a dangerous place for safety','prepare food and water','call the authorities'],
    answer:'leave a dangerous place for safety',
    hint:'Think about what you would do if a storm was approaching your home.',
    explanation:'"<b>Evacuate</b>" means to leave a place because it is dangerous. Context clues: "approaching storm" and "low-lying areas" suggest danger, so leaving for safety is the logical meaning.' }),

  makeMCQ({ id:'g7eng-listening-005', chapterId:'g7eng-listening', difficulty:3,
    subsection:'identifying_message',
    question:'You hear: "This film contains scenes that some viewers may find disturbing. Viewer discretion is advised." What does this announcement tell you?',
    options:['The film is only for children.','The film has already started.','Some people may be upset by parts of the film.','The film is not in English.'],
    answer:'Some people may be upset by parts of the film.',
    hint:'"Disturbing" means upsetting or shocking. "Viewer discretion" means viewers should decide for themselves.',
    explanation:'The announcement warns that the film may upset some viewers. Understanding formal warnings and advisories is a key listening skill. "Discretion" means good judgement about what is appropriate.' }),

  makeMCQ({ id:'g7eng-listening-006', chapterId:'g7eng-listening', difficulty:4,
    subsection:'identifying_message',
    question:'Two students have a discussion. Priya says: "I think school uniforms are important because they create equality." Rajan replies: "But they stop students from expressing themselves." What is the topic of their discussion?',
    options:['School rules about behaviour','Whether school uniforms are a good idea','The cost of school supplies','How to dress for a special event'],
    answer:'Whether school uniforms are a good idea',
    hint:'Both speakers talk about school uniforms — one for and one against.',
    explanation:'Priya and Rajan are having a <b>debate about school uniforms</b> — one gives a reason for, the other against. When following a discussion between several speakers, identifying the shared topic is the first step.' }),

  // ── Speaking & Oral Interaction ──────────────────────────────────────────

  makeMCQ({ id:'g7eng-speaking-001', chapterId:'g7eng-speaking', difficulty:1,
    subsection:'oral_interaction',
    question:'You are asked to introduce yourself to a new classmate. Which is the BEST opening?',
    options:['"What do you want?"','"Hi, my name is Maya. I\'m in Form 2."','"Go away, I\'m busy."','"I don\'t know."'],
    answer:'"Hi, my name is Maya. I\'m in Form 2."',
    hint:'A good introduction is polite, clear and gives key information.',
    explanation:'A polite, clear self-introduction includes a greeting, your name and relevant information (e.g. your class). Using a friendly tone and complete sentences is important in oral interaction.' }),

  makeMCQ({ id:'g7eng-speaking-002', chapterId:'g7eng-speaking', difficulty:2,
    subsection:'oral_interaction',
    question:'During a class discussion, your partner says something you disagree with. Which is the MOST appropriate response?',
    options:['"That\'s wrong and you don\'t know anything."','"I see your point, but I think we should also consider…"','"I\'m not listening to you."','"Whatever, it doesn\'t matter."'],
    answer:'"I see your point, but I think we should also consider…"',
    hint:'Good discussants acknowledge other opinions before sharing their own.',
    explanation:'Acknowledging another speaker\'s view before presenting your own ("I see your point, but…") shows respectful interaction. Good oral skills include listening, acknowledging and adding ideas politely.' }),

  makeMCQ({ id:'g7eng-speaking-003', chapterId:'g7eng-speaking', difficulty:2,
    subsection:'intonation_register',
    question:'You need to ask your headteacher for permission to leave school early. Which REGISTER should you use?',
    options:['Very casual, as if talking to a friend','Formal and polite, using complete sentences','Slang and abbreviations','Whispering so no one else hears'],
    answer:'Formal and polite, using complete sentences',
    hint:'Register means the level of formality. Who are you speaking to?',
    explanation:'When speaking to a <b>headteacher</b>, you use a <b>formal register</b>: polite language, complete sentences and a respectful tone. Register changes depending on the audience (e.g. friends = informal; teachers = formal).' }),

  makeMCQ({ id:'g7eng-speaking-004', chapterId:'g7eng-speaking', difficulty:1,
    subsection:'intonation_register',
    question:'Which sentence uses RISING intonation in everyday English?',
    options:['Thank you very much.','Please sit down.','Are you ready for the test?','We finished the project.'],
    answer:'Are you ready for the test?',
    hint:'Rising intonation is used when asking a question — your voice goes up at the end.',
    explanation:'Questions in English typically end with <b>rising intonation</b> — your voice goes up at the end of "Are you ready?" Statements (like "We finished.") use falling intonation. Correct intonation makes speech natural and easy to understand.' }),

  makeMCQ({ id:'g7eng-speaking-005', chapterId:'g7eng-speaking', difficulty:3,
    subsection:'oral_interaction',
    question:'You are presenting a project to your class. Which is the BEST advice?',
    options:['Read every word from your paper without looking up.','Speak quietly so only the front row hears.','Make eye contact, speak clearly, and use your own words.','Use as many long words as possible to impress.'],
    answer:'Make eye contact, speak clearly, and use your own words.',
    hint:'Good presenters connect with their audience and communicate naturally.',
    explanation:'An effective oral presentation involves <b>eye contact</b> (to connect with the audience), <b>clear speech</b> (not too fast or too quiet), and <b>natural language</b>. Reading a script word-for-word lacks engagement and eye contact.' }),

  makeMCQ({ id:'g7eng-speaking-006', chapterId:'g7eng-speaking', difficulty:3,
    subsection:'intonation_register',
    question:'A friend texts you: "U coming 2day? Plz b on time lol." This message uses _____ register.',
    options:['formal','academic','technical','informal'],
    answer:'informal',
    hint:'Text messages between friends use shortcuts and casual language.',
    explanation:'Text abbreviations ("U", "2day", "Plz", "lol") are features of <b>informal register</b>. In formal writing or speaking (e.g. essays, presentations, speaking to teachers), you would use full words and standard grammar.' }),

  // ── Reading & Comprehension ──────────────────────────────────────────────

  makeMCQ({ id:'g7eng-reading-001', chapterId:'g7eng-reading', difficulty:1,
    subsection:'main_idea_details',
    question:'Read: "Every morning, Mrs. Boodhna waters her vegetable garden before cooking breakfast. She grows tomatoes, spinach and herbs. Her neighbours often come to buy fresh vegetables from her." What is the MAIN IDEA of this passage?',
    options:['Mrs. Boodhna cooks breakfast every morning.','Mrs. Boodhna grows and shares vegetables from her garden.','The neighbours enjoy buying food.','Tomatoes and spinach are easy to grow.'],
    answer:'Mrs. Boodhna grows and shares vegetables from her garden.',
    hint:'The main idea covers what the WHOLE passage is about, not just one detail.',
    explanation:'The main idea of the passage is that Mrs. Boodhna <b>grows vegetables in her garden</b> and the community benefits from it. Details (morning routine, types of plants, neighbours buying) all support this central idea.' }),

  makeMCQ({ id:'g7eng-reading-002', chapterId:'g7eng-reading', difficulty:2,
    subsection:'main_idea_details',
    question:'Read: "The blue whale is the largest animal ever known to have lived on Earth. It can grow up to 30 metres long and weigh as much as 200 tonnes. Its heart alone is the size of a small car." Which detail BEST supports the main idea that blue whales are enormous?',
    options:['Blue whales live in the ocean.','A blue whale\'s heart is the size of a small car.','Blue whales eat tiny shrimp called krill.','Blue whales can be heard underwater.'],
    answer:'A blue whale\'s heart is the size of a small car.',
    hint:'The main idea is about the size of the blue whale. Which detail tells you something about its size?',
    explanation:'The main idea is the <b>enormous size</b> of the blue whale. The detail about the heart being the size of a <b>small car</b> directly supports this by giving a vivid comparison. Supporting details give evidence, examples or explanations for the main idea.' }),

  makeMCQ({ id:'g7eng-reading-003', chapterId:'g7eng-reading', difficulty:2,
    subsection:'inferring_vocabulary',
    question:'Read: "The hiker was <b>exhausted</b> after the long climb. She sank into her sleeping bag without even eating." From the context, what does <b>exhausted</b> mean?',
    options:['very hungry','extremely tired','very happy','slightly cold'],
    answer:'extremely tired',
    hint:'"Sank into her sleeping bag without eating" — what would make someone do this?',
    explanation:'"<b>Exhausted</b>" means extremely tired. Context clues: the hiker climbed a long way and went straight to sleep without eating — both suggest extreme tiredness, not hunger or happiness.' }),

  makeMCQ({ id:'g7eng-reading-004', chapterId:'g7eng-reading', difficulty:3,
    subsection:'inferring_vocabulary',
    question:'Read: "The shop was <b>thriving</b> — every day was busy, customers queued outside, and the owner had to hire two more staff." From the context, what does <b>thriving</b> mean?',
    options:['closing down','barely surviving','doing very well','just opening'],
    answer:'doing very well',
    hint:'What do busy queues and extra staff tell you about how well the shop is doing?',
    explanation:'"<b>Thriving</b>" means doing very well or being very successful. Context clues: busy days, queues of customers, need for more staff — all point to great success.' }),

  makeMCQ({ id:'g7eng-reading-005', chapterId:'g7eng-reading', difficulty:3,
    subsection:'main_idea_details',
    question:'Read: "Plastic pollution is a growing problem in our oceans. Every year, millions of tonnes of plastic enter the sea. Marine animals mistake plastic bags for jellyfish and swallow them. Scientists warn that if we do not act now, the damage will be irreversible." What is the writer\'s PURPOSE in this passage?',
    options:['To entertain readers with a story about the ocean.','To give a recipe for reducing plastic use at home.','To warn about the serious problem of plastic in the oceans.','To explain how jellyfish live.'],
    answer:'To warn about the serious problem of plastic in the oceans.',
    hint:'What is the writer trying to make the reader think or do?',
    explanation:'The writer uses facts and a warning to <b>inform and persuade</b> the reader about ocean plastic pollution. The final sentence ("if we do not act now…") clearly shows the purpose is to warn and urge action.' }),

  makeMCQ({ id:'g7eng-reading-006', chapterId:'g7eng-reading', difficulty:4,
    subsection:'inferring_vocabulary',
    question:'Read: "Despite the rain and muddy paths, the children were <b>undaunted</b> — they kept walking, laughing all the way to the top." From the context, what does <b>undaunted</b> mean?',
    options:['frightened and cautious','not discouraged; carrying on bravely','very wet and tired','uncertain which path to take'],
    answer:'not discouraged; carrying on bravely',
    hint:'"Despite the difficulties, they kept going" — what word describes continuing confidently despite problems?',
    explanation:'"<b>Undaunted</b>" means not frightened or discouraged — continuing bravely in spite of difficulties. "Despite" introduces the obstacles, but the children laughed and carried on, which shows they were not put off.' }),

  // ── Writing ──────────────────────────────────────────────────────────────

  makeMCQ({ id:'g7eng-writing-001', chapterId:'g7eng-writing', difficulty:1,
    subsection:'organising_ideas',
    question:'When writing a paragraph, where does the TOPIC SENTENCE usually go?',
    options:['At the end of the paragraph','In the middle of the paragraph','At the beginning of the paragraph','In a separate paragraph'],
    answer:'At the beginning of the paragraph',
    hint:'The topic sentence introduces what the paragraph is about.',
    explanation:'A <b>topic sentence</b> usually comes <b>at the beginning</b> of a paragraph. It states the main idea and tells the reader what the rest of the paragraph will be about. Supporting sentences then provide details, examples and explanations.' }),

  makeMCQ({ id:'g7eng-writing-002', chapterId:'g7eng-writing', difficulty:2,
    subsection:'organising_ideas',
    question:'Which of these is the BEST topic sentence for a paragraph about recycling?',
    options:['Recycling is very interesting.','Recycling paper, plastic and glass can significantly reduce waste and help protect our environment.','Many people recycle.','I once recycled a bottle.'],
    answer:'Recycling paper, plastic and glass can significantly reduce waste and help protect our environment.',
    hint:'A good topic sentence is specific and tells the reader the main point clearly.',
    explanation:'The best topic sentence is <b>specific</b> and gives a clear main point. "Recycling paper, plastic and glass can significantly reduce waste and help protect our environment" names what is being recycled and why it matters — it gives direction to the whole paragraph.' }),

  makeMCQ({ id:'g7eng-writing-003', chapterId:'g7eng-writing', difficulty:2,
    subsection:'vocabulary_register',
    question:'You are writing a formal letter to a company. Which opening is MOST appropriate?',
    options:['"Hey, I\'m writing because…"','"Dear Sir/Madam, I am writing to…"','"Yo, just wanted to say…"','"Hi there! So basically…"'],
    answer:'"Dear Sir/Madam, I am writing to…"',
    hint:'Formal letters use specific greetings and full, polite language.',
    explanation:'A formal letter begins with "<b>Dear Sir/Madam</b>" (or the person\'s name if known). Formal register uses complete sentences, polite language and no slang. "Hey", "Yo" and "Hi there!" are informal and inappropriate in a formal letter.' }),

  makeMCQ({ id:'g7eng-writing-004', chapterId:'g7eng-writing', difficulty:3,
    subsection:'vocabulary_register',
    question:'Which word would be MORE APPROPRIATE in a formal essay than its informal equivalent?',
    options:['kids (instead of children)','commence (instead of start)','lots of (instead of many)','gonna (instead of going to)'],
    answer:'commence (instead of start)',
    hint:'Formal writing uses precise, complete words rather than contractions or slang.',
    explanation:'"<b>Commence</b>" is formal and appropriate in essays; "start" is more informal. In formal writing: use "children" (not kids), "many" (not lots of), "going to" (not gonna). Choosing formal vocabulary improves the register of essays.' }),

  makeMCQ({ id:'g7eng-writing-005', chapterId:'g7eng-writing', difficulty:3,
    subsection:'organising_ideas',
    question:'Which of the following LINKING WORDS shows CONTRAST between two ideas?',
    options:['furthermore','therefore','however','in addition'],
    answer:'however',
    hint:'You need a word that introduces an idea that is different from or opposite to the previous one.',
    explanation:'"<b>However</b>" signals contrast — the opposite of what was just said. "Furthermore" and "in addition" add more similar information. "Therefore" shows result. Linking words guide the reader through your ideas and show how they connect.' }),

  makeMCQ({ id:'g7eng-writing-006', chapterId:'g7eng-writing', difficulty:4,
    subsection:'organising_ideas',
    question:'A student writes: "Dogs are good pets. They are loyal. They need walks. I like dogs." What is the MAIN WEAKNESS of this paragraph?',
    options:['It has too many sentences.','The sentences are short and not linked — it reads like a list.','The topic is not interesting.','It uses the word "I" which is not allowed.'],
    answer:'The sentences are short and not linked — it reads like a list.',
    hint:'Think about how the sentences flow. Is there a sense of connection between the ideas?',
    explanation:'Good paragraphs have <b>linked, varied sentences</b>. Short, disconnected sentences make writing feel choppy. The student should connect ideas using linking words (e.g. "Dogs are loyal pets that also need regular exercise.") and vary sentence length.' }),

  // ── Grammar · Nouns ──────────────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-nouns-001', chapterId:'g7eng-gr-nouns', difficulty:1,
    subsection:'countable_uncountable',
    question:'Which of the following is an UNCOUNTABLE noun?',
    options:['chair','water','book','idea'],
    answer:'water',
    hint:'An uncountable noun cannot be counted individually or made plural.',
    explanation:'"<b>Water</b>" is uncountable — we cannot say "one water, two waters". We say "some water" or "a glass of water". Chairs, books and ideas are all countable: one chair, two books.' }),

  makeMCQ({ id:'g7eng-gr-nouns-002', chapterId:'g7eng-gr-nouns', difficulty:1,
    subsection:'countable_uncountable',
    question:'Which quantifier is correct with the noun "information"?',
    options:['many information','a few information','much information','several information'],
    answer:'much information',
    hint:'"Information" is uncountable. Use "much" with uncountable nouns.',
    explanation:'"<b>Much information</b>" is correct because "information" is uncountable. Use <b>much/little</b> with uncountable nouns (much water, little time) and <b>many/few</b> with countable nouns (many books, few chairs).' }),

  makeMCQ({ id:'g7eng-gr-nouns-003', chapterId:'g7eng-gr-nouns', difficulty:2,
    subsection:'subject_verb_agreement',
    question:'Choose the correct verb: "The news _____ very surprising today."',
    options:['are','were','is','have been'],
    answer:'is',
    hint:'"News" looks plural because it ends in -s, but it is an uncountable singular noun.',
    explanation:'"<b>The news is</b> very surprising" — "news" is treated as singular in English (like "information", "advice", "furniture"). Despite ending in -s, it takes a singular verb. This is a common mistake.' }),

  makeMCQ({ id:'g7eng-gr-nouns-004', chapterId:'g7eng-gr-nouns', difficulty:2,
    subsection:'subject_verb_agreement',
    question:'Choose the correct verb: "A group of students _____ working on the project."',
    options:['are','is','were','have'],
    answer:'is',
    hint:'The subject is "a group" (singular collective noun), not "students".',
    explanation:'"<b>A group</b> is working" — the subject is the collective noun "group" (singular), so we use "is". The phrase "of students" is just a modifier. Collective nouns (team, class, group, family) take singular verbs in British English.' }),

  makeMCQ({ id:'g7eng-gr-nouns-005', chapterId:'g7eng-gr-nouns', difficulty:3,
    subsection:'countable_uncountable',
    question:'Which sentence is CORRECT?',
    options:['She gave me an advice.','She gave me some advice.','She gave me advices.','She gave me few advice.'],
    answer:'She gave me some advice.',
    hint:'"Advice" is uncountable — it cannot have "a/an" or a plural form.',
    explanation:'"<b>Some advice</b>" is correct. "Advice" is uncountable: we never say "an advice" or "advices". For uncountable nouns, use "some", "a piece of", or "much" instead of "a/an" or plurals.' }),

  makeMCQ({ id:'g7eng-gr-nouns-006', chapterId:'g7eng-gr-nouns', difficulty:3,
    subsection:'subject_verb_agreement',
    question:'Choose the correct verb: "Mathematics _____ my favourite subject."',
    options:['are','were','is','have been'],
    answer:'is',
    hint:'Subject names ending in -s (Mathematics, Physics, Economics) are singular.',
    explanation:'"<b>Mathematics is</b>" — names of subjects ending in -s (Mathematics, Physics, Economics, Statistics) are treated as singular and take singular verbs.' }),

  // ── Grammar · Pronouns ───────────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-pronouns-001', chapterId:'g7eng-gr-pronouns', difficulty:1,
    subsection:'personal_possessive',
    question:'Choose the correct pronoun: "My sister and _____ went to the market."',
    options:['me','I','myself','mine'],
    answer:'I',
    hint:'Remove "my sister and" — would you say "me went" or "I went"?',
    explanation:'"My sister and <b>I</b> went" is correct. "I" is the subject pronoun used when the pronoun is the subject of the verb. Test: remove the other person — "I went" is correct; "me went" is wrong.' }),

  makeMCQ({ id:'g7eng-gr-pronouns-002', chapterId:'g7eng-gr-pronouns', difficulty:1,
    subsection:'personal_possessive',
    question:'Which sentence uses a POSSESSIVE PRONOUN correctly?',
    options:['That bag is her.','The decision is our.','This book is mine.','The idea was their.'],
    answer:'This book is mine.',
    hint:'Possessive pronouns (mine, yours, his, hers, ours, theirs) stand alone — they do not need a noun after them.',
    explanation:'"This book is <b>mine</b>" is correct. "Mine" is a possessive pronoun that stands alone. Incorrect forms: "her bag" (adjective) vs "it is hers" (pronoun). Correct possessive pronouns: mine, yours, his, hers, ours, theirs.' }),

  makeMCQ({ id:'g7eng-gr-pronouns-003', chapterId:'g7eng-gr-pronouns', difficulty:2,
    subsection:'relative_pronouns',
    question:'Choose the correct relative pronoun: "The girl _____ won the prize is my classmate."',
    options:['which','what','whom','who'],
    answer:'who',
    hint:'Use "who" when the relative pronoun refers to a person and is the subject of the relative clause.',
    explanation:'"The girl <b>who</b> won the prize" — use <b>who</b> for people (subject). Use <b>which</b> for things. Use <b>whom</b> for people (object, e.g. "the girl whom I met"). Use <b>whose</b> for possession.' }),

  makeMCQ({ id:'g7eng-gr-pronouns-004', chapterId:'g7eng-gr-pronouns', difficulty:2,
    subsection:'relative_pronouns',
    question:'Choose the correct relative pronoun: "The book _____ I borrowed was very interesting."',
    options:['who','whom','which','whose'],
    answer:'which',
    hint:'"The book" is a thing, not a person.',
    explanation:'"The book <b>which</b> I borrowed" — use <b>which</b> for things and animals (in a defining relative clause, "that" also works: "the book that I borrowed"). "Who" and "whom" are only for people.' }),

  makeMCQ({ id:'g7eng-gr-pronouns-005', chapterId:'g7eng-gr-pronouns', difficulty:3,
    subsection:'personal_possessive',
    question:'Choose the correct pronoun: "The teacher asked Sara and _____ to present first."',
    options:['I','she','we','her'],
    answer:'her',
    hint:'The pronoun follows the verb "asked" — it is the object of the sentence. Remove "Sara and" to test.',
    explanation:'"The teacher asked Sara and <b>her</b>" — "her" is the object pronoun (after a verb). Test: "The teacher asked her" is correct; "The teacher asked she" is wrong. Object pronouns: me, you, him, her, us, them.' }),

  makeMCQ({ id:'g7eng-gr-pronouns-006', chapterId:'g7eng-gr-pronouns', difficulty:3,
    subsection:'relative_pronouns',
    question:'Choose the correct word: "The student _____ backpack was stolen reported it to the principal."',
    options:['who','which','that','whose'],
    answer:'whose',
    hint:'Which relative pronoun shows POSSESSION (the backpack belonged to the student)?',
    explanation:'"The student <b>whose</b> backpack was stolen" — <b>whose</b> shows possession/belonging. It replaces "the student\'s" in a relative clause. "Whose" can refer to people and things.' }),

  // ── Grammar · Adjectives ─────────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-adjectives-001', chapterId:'g7eng-gr-adjectives', difficulty:1,
    subsection:'types_adjectives',
    question:'Which word in this sentence is an ADJECTIVE: "The tall boy carried a heavy bag."',
    options:['carried','boy','tall','bag'],
    answer:'tall',
    hint:'An adjective describes a noun. Which word describes the boy?',
    explanation:'"<b>Tall</b>" is an adjective describing the noun "boy". "Heavy" is also an adjective (describing "bag"). Adjectives answer the question "What kind?" or "How many?" about nouns.' }),

  makeMCQ({ id:'g7eng-gr-adjectives-002', chapterId:'g7eng-gr-adjectives', difficulty:1,
    subsection:'types_adjectives',
    question:'Which is the correct COMPARATIVE form of the adjective "good"?',
    options:['gooder','more good','best','better'],
    answer:'better',
    hint:'"Good" is an irregular adjective — it does not follow the normal rule of adding -er.',
    explanation:'"<b>Better</b>" is the comparative of "good" (irregular). Superlative: "best". Irregular adjectives: good→better→best; bad→worse→worst; far→farther→farthest. Regular adjectives: tall→taller→tallest.' }),

  makeMCQ({ id:'g7eng-gr-adjectives-003', chapterId:'g7eng-gr-adjectives', difficulty:2,
    subsection:'adjective_placement',
    question:'Which sentence places the adjectives in the CORRECT order?',
    options:['a red big round ball','a big round red ball','a round red big ball','a big red round ball'],
    answer:'a big round red ball',
    hint:'English adjective order: size → shape → colour. Remember: "a big round red ball."',
    explanation:'Standard English adjective order: <b>size → shape → colour</b>. So: "a <b>big</b> (size) <b>round</b> (shape) <b>red</b> (colour) ball". Breaking this order sounds unnatural to native speakers.' }),

  makeMCQ({ id:'g7eng-gr-adjectives-004', chapterId:'g7eng-gr-adjectives', difficulty:2,
    subsection:'types_adjectives',
    question:'Which adjective is formed from the NOUN "comfort"?',
    options:['comforting','comfortable','comforted','comfortably'],
    answer:'comfortable',
    hint:'The suffix -able added to a noun or verb creates an adjective meaning "able to be" or "giving".',
    explanation:'"<b>Comfortable</b>" is an adjective formed from the noun "comfort" by adding the suffix <b>-able</b>. Other examples: reason→reasonable, fashion→fashionable, agree→agreeable. "Comforting" is also an adjective (from the verb), but "comfortable" fits the noun root best.' }),

  makeMCQ({ id:'g7eng-gr-adjectives-005', chapterId:'g7eng-gr-adjectives', difficulty:3,
    subsection:'adjective_placement',
    question:'In the sentence "She is beautiful", the adjective is in what position?',
    options:['Before the noun (attributive)','After the noun','After the verb (predicative)','At the beginning of the sentence'],
    answer:'After the verb (predicative)',
    hint:'Is "beautiful" directly before a noun, or does it come after the verb "is"?',
    explanation:'"Beautiful" follows the verb "is" — this is the <b>predicative</b> position (after a linking verb like is/was/seems/looks). When an adjective comes directly before a noun ("the beautiful girl"), it is in the <b>attributive</b> position.' }),

  makeMCQ({ id:'g7eng-gr-adjectives-006', chapterId:'g7eng-gr-adjectives', difficulty:3,
    subsection:'types_adjectives',
    question:'Which adjective correctly completes: "The test was _____ than I expected."',
    options:['more easy','more easier','easier','easiest'],
    answer:'easier',
    hint:'Short adjectives (one syllable, or two syllables ending in -y) form comparatives with -er.',
    explanation:'"<b>Easier</b>" is the comparative of "easy" (y → ier). Short adjectives add -er: tall→taller, fast→faster. Adjectives ending in -y change y to i before -er: easy→easier, happy→happier. Do NOT add "more" as well ("more easier" is wrong).' }),

  // ── Grammar · Verbs & Tenses ─────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-verbs-001', chapterId:'g7eng-gr-verbs', difficulty:1,
    subsection:'verb_tenses',
    question:'She _____ to school every day.',
    options:['go','goes','went','is going'],
    answer:'goes',
    hint:'The sentence describes a regular habit. The subject is "she" (third person singular).',
    explanation:'"She <b>goes</b>" — simple present tense for regular habits/routines. Third person singular (he/she/it) adds -s or -es to the base verb: go→goes, watch→watches, study→studies.' }),

  makeMCQ({ id:'g7eng-gr-verbs-002', chapterId:'g7eng-gr-verbs', difficulty:1,
    subsection:'verb_tenses',
    question:'What TENSE is used in: "They were playing football when it started to rain."',
    options:['Simple past','Past continuous','Present continuous','Past perfect'],
    answer:'Past continuous',
    hint:'The form "were + verb-ing" is used for an action that was in progress in the past.',
    explanation:'"Were playing" is the <b>past continuous</b> tense (was/were + verb-ing). It describes an action in progress at a specific moment in the past — here, interrupted by "it started to rain" (simple past).' }),

  makeMCQ({ id:'g7eng-gr-verbs-003', chapterId:'g7eng-gr-verbs', difficulty:2,
    subsection:'verb_tenses',
    question:'Choose the correct tense: "By the time she arrived, the bus _____."',
    options:['already left','has already left','had already left','is already leaving'],
    answer:'had already left',
    hint:'One action happened BEFORE another past action. Use the past perfect for the earlier one.',
    explanation:'"<b>Had already left</b>" is the past perfect — used for an action completed BEFORE another past action. "She arrived" (simple past) → bus "had left" (even earlier). Past perfect = had + past participle.' }),

  makeMCQ({ id:'g7eng-gr-verbs-004', chapterId:'g7eng-gr-verbs', difficulty:2,
    subsection:'verb_formation',
    question:'Which is the correct verb formed from the adjective "wide"?',
    options:['widen','widely','widening','wider'],
    answer:'widen',
    hint:'Adding -en to some adjectives creates a verb meaning "to make more ___".',
    explanation:'"<b>Widen</b>" is a verb formed from the adjective "wide" by adding the suffix <b>-en</b> (meaning "to make wide"). Other examples: length→lengthen, short→shorten, bright→brighten, dark→darken.' }),

  makeMCQ({ id:'g7eng-gr-verbs-005', chapterId:'g7eng-gr-verbs', difficulty:3,
    subsection:'verb_tenses',
    question:'Choose the correct form: "Look! The children _____ in the rain."',
    options:['dance','danced','are dancing','will dance'],
    answer:'are dancing',
    hint:'"Look!" signals something happening RIGHT NOW.',
    explanation:'"<b>Are dancing</b>" — the present continuous (am/is/are + verb-ing) describes an action happening at this very moment. Signal words: look, listen, right now, at the moment.' }),

  makeMCQ({ id:'g7eng-gr-verbs-006', chapterId:'g7eng-gr-verbs', difficulty:3,
    subsection:'verb_formation',
    question:'What verb can be formed by adding the prefix "re-" to "write"?',
    options:['unwrite','dewrite','rewrite','overwrite'],
    answer:'rewrite',
    hint:'The prefix re- means "again".',
    explanation:'"<b>Rewrite</b>" means to write again. The prefix <b>re-</b> means "again" or "back": rewrite, redo, return, replace, rebuild. Prefixes change the meaning of verbs without changing their basic form.' }),

  // ── Grammar · Determiners ────────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-determiners-001', chapterId:'g7eng-gr-determiners', difficulty:1,
    subsection:'definite_article',
    question:'Choose the correct article: "_____ elephant is the largest land animal."',
    options:['A','An','The','Some'],
    answer:'The',
    hint:'"The elephant" refers to elephants as a species — a general truth about a unique category.',
    explanation:'"<b>The</b> elephant" — we use <b>the</b> when referring to a species or category in a general statement, and for things that are unique (the sun, the moon). "An elephant" would refer to one specific elephant.' }),

  makeMCQ({ id:'g7eng-gr-determiners-002', chapterId:'g7eng-gr-determiners', difficulty:1,
    subsection:'definite_article',
    question:'Which noun takes NO article in English?',
    options:['the Nile','the Maldives','Mauritius','the Amazon'],
    answer:'Mauritius',
    hint:'Most countries use no article, but island groups, rivers and mountain ranges do.',
    explanation:'<b>Mauritius</b> (a single country/island) takes no article. We say "the Maldives" (island group), "the Nile" (river), "the Amazon" (river). Most single-country names: France, India, Japan — no article.' }),

  makeMCQ({ id:'g7eng-gr-determiners-003', chapterId:'g7eng-gr-determiners', difficulty:2,
    subsection:'quantifiers',
    question:'Choose the correct quantifier: "I have _____ money left — only a few coins."',
    options:['many','few','little','a few'],
    answer:'little',
    hint:'"Money" is uncountable. Which quantifier is used with uncountable nouns to mean "not much"?',
    explanation:'"<b>Little</b> money" is correct — "little" means "not much" and is used with <b>uncountable</b> nouns. "Few" means "not many" and is used with <b>countable</b> nouns. "A little" and "a few" have a more positive meaning ("some").' }),

  makeMCQ({ id:'g7eng-gr-determiners-004', chapterId:'g7eng-gr-determiners', difficulty:2,
    subsection:'quantifiers',
    question:'Which sentence is CORRECT?',
    options:['"There are much students in the hall."','"There are many students in the hall."','"There are much student in the hall."','"There are many student in the hall."'],
    answer:'"There are many students in the hall."',
    hint:'"Students" is a countable plural noun. Which quantifier is correct?',
    explanation:'"<b>Many</b> students" is correct. Use <b>many</b> with countable plural nouns. Use <b>much</b> with uncountable nouns. "Students" is countable, so "many" is correct and it must be plural.' }),

  makeMCQ({ id:'g7eng-gr-determiners-005', chapterId:'g7eng-gr-determiners', difficulty:3,
    subsection:'definite_article',
    question:'Which sentence uses the article CORRECTLY?',
    options:['"She plays the piano very well."','"She plays a piano very well."','"She plays piano very well."','"She plays an piano very well."'],
    answer:'"She plays the piano very well."',
    hint:'Instruments are usually preceded by "the" when we talk about playing them.',
    explanation:'"She plays <b>the</b> piano" — when talking about playing musical instruments, we use <b>the</b>: play the guitar, the violin, the drums. This is a fixed rule for instruments in English.' }),

  makeMCQ({ id:'g7eng-gr-determiners-006', chapterId:'g7eng-gr-determiners', difficulty:3,
    subsection:'quantifiers',
    question:'"_____ of the students passed the exam" — which quantifier means almost all of them?',
    options:['A few','Several','The majority','Much'],
    answer:'The majority',
    hint:'Which phrase implies more than half — in fact, most?',
    explanation:'"<b>The majority</b> of the students" suggests most of them — more than half. "A few" = not many. "Several" = more than two but not very many. "Much" is for uncountable nouns and cannot be used here.' }),

  // ── Grammar · Adverbs ────────────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-adverbs-001', chapterId:'g7eng-gr-adverbs', difficulty:1,
    subsection:'types_adverbs',
    question:'What TYPE of adverb is the underlined word: "She sings <u>beautifully</u>."',
    options:['Adverb of time','Adverb of place','Adverb of frequency','Adverb of manner'],
    answer:'Adverb of manner',
    hint:'The adverb describes HOW she sings.',
    explanation:'"<b>Beautifully</b>" is an adverb of <b>manner</b> — it tells us HOW she sings. Adverbs of manner often end in -ly: slowly, carefully, quickly, loudly.' }),

  makeMCQ({ id:'g7eng-gr-adverbs-002', chapterId:'g7eng-gr-adverbs', difficulty:1,
    subsection:'types_adverbs',
    question:'Which word in this sentence is an ADVERB OF FREQUENCY: "He always finishes his work on time."',
    options:['finishes','always','work','time'],
    answer:'always',
    hint:'Adverbs of frequency tell you HOW OFTEN something happens.',
    explanation:'"<b>Always</b>" is an adverb of frequency — it tells us how often he finishes his work. Adverbs of frequency: always, usually, often, sometimes, rarely, never. They normally go before the main verb but after "be".' }),

  makeMCQ({ id:'g7eng-gr-adverbs-003', chapterId:'g7eng-gr-adverbs', difficulty:2,
    subsection:'adverb_position',
    question:'Where does an adverb of FREQUENCY usually go in a sentence?',
    options:['At the beginning of the sentence','Before the main verb (or after "be")','After the object of the sentence','At the very end of the sentence'],
    answer:'Before the main verb (or after "be")',
    hint:'Think: "She always eats breakfast" vs "She is always cheerful."',
    explanation:'Adverbs of frequency go <b>before the main verb</b>: "She <b>always</b> eats breakfast." With the verb "be", they go after: "She is <b>always</b> cheerful." They can also go at the beginning or end for emphasis, but the mid-position rule is standard.' }),

  makeMCQ({ id:'g7eng-gr-adverbs-004', chapterId:'g7eng-gr-adverbs', difficulty:2,
    subsection:'types_adverbs',
    question:'Which adverb is an ADVERB OF DEGREE?',
    options:['yesterday','outside','never','extremely'],
    answer:'extremely',
    hint:'An adverb of degree tells you HOW MUCH or HOW INTENSELY.',
    explanation:'"<b>Extremely</b>" is an adverb of degree — it intensifies the adjective it modifies (e.g. "extremely hot"). Other degree adverbs: very, quite, rather, almost, fairly, too, enough. "Yesterday" = time; "outside" = place; "never" = frequency.' }),

  makeMCQ({ id:'g7eng-gr-adverbs-005', chapterId:'g7eng-gr-adverbs', difficulty:3,
    subsection:'adverb_position',
    question:'Which sentence places the adverb of manner in the CORRECT position?',
    options:['She quickly ran to the bus stop.','She ran quickly to the bus stop.','Quickly she ran to the bus stop.','She ran to the quickly bus stop.'],
    answer:'She ran quickly to the bus stop.',
    hint:'Adverbs of manner usually go after the verb (and its direct object if there is one).',
    explanation:'"She ran <b>quickly</b> to the bus stop" — adverbs of manner typically follow the main verb and its object. Placing them before the verb ("quickly ran") is possible but less common in everyday English. Placing them inside a noun phrase ("the quickly bus stop") is wrong.' }),

  makeMCQ({ id:'g7eng-gr-adverbs-006', chapterId:'g7eng-gr-adverbs', difficulty:3,
    subsection:'types_adverbs',
    question:'Identify the adverb type in: "Put your bag <u>there</u>."',
    options:['Adverb of manner','Adverb of time','Adverb of place','Adverb of degree'],
    answer:'Adverb of place',
    hint:'"There" tells you WHERE to put the bag.',
    explanation:'"<b>There</b>" is an adverb of <b>place</b> — it tells us WHERE the bag should go. Adverbs of place: here, there, outside, inside, above, below, nearby, everywhere.' }),

  // ── Grammar · Modals ─────────────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-modals-001', chapterId:'g7eng-gr-modals', difficulty:1,
    subsection:'ability_permission',
    question:'Which modal verb expresses ABILITY?',
    options:['must','should','can','would'],
    answer:'can',
    hint:'"Can" means you are able to do something.',
    explanation:'"<b>Can</b>" expresses ability (present) — "I can swim." "Could" expresses past ability — "I could swim when I was five." "Must" and "should" express obligation/advice.' }),

  makeMCQ({ id:'g7eng-gr-modals-002', chapterId:'g7eng-gr-modals', difficulty:1,
    subsection:'ability_permission',
    question:'Choose the correct modal: "_____ I use your pen, please?"',
    options:['Must','Should','May','Will'],
    answer:'May',
    hint:'This is a polite request for permission.',
    explanation:'"<b>May</b> I use your pen?" — "may" is used for polite requests for permission. "Can" is also used informally for permission, but "may" is more formal and polite.' }),

  makeMCQ({ id:'g7eng-gr-modals-003', chapterId:'g7eng-gr-modals', difficulty:2,
    subsection:'obligation',
    question:'Which sentence expresses a STRONG OBLIGATION or necessity?',
    options:['You should eat more vegetables.','You could try a new sport.','You must wear a seatbelt.','You might enjoy the film.'],
    answer:'You must wear a seatbelt.',
    hint:'"Must" expresses something that is necessary or compulsory.',
    explanation:'"You <b>must</b> wear a seatbelt" — "must" expresses strong obligation (it is required/necessary). "Should" is weaker advice. "Could" and "might" express possibility, not obligation.' }),

  makeMCQ({ id:'g7eng-gr-modals-004', chapterId:'g7eng-gr-modals', difficulty:2,
    subsection:'obligation',
    question:'Which modal expresses ADVICE (not a strong rule)?',
    options:['must','have to','should','can'],
    answer:'should',
    hint:'"Should" suggests it is a good idea, but not absolutely required.',
    explanation:'"<b>Should</b>" expresses advice or recommendation — "You should study regularly." It is softer than "must" or "have to" (which express strong obligation). "Should" implies it is a good idea, not a rule.' }),

  makeMCQ({ id:'g7eng-gr-modals-005', chapterId:'g7eng-gr-modals', difficulty:3,
    subsection:'ability_permission',
    question:'"You _____ not enter the laboratory without protective goggles." Which modal is correct?',
    options:['should','could','must','might'],
    answer:'must',
    hint:'This is a safety rule — a strong prohibition.',
    explanation:'"You <b>must not</b> enter…" — "must not" (mustn\'t) expresses strong prohibition (it is forbidden/not allowed). "Should not" is a softer warning. "Could not" and "might not" do not fit here.' }),

  makeMCQ({ id:'g7eng-gr-modals-006', chapterId:'g7eng-gr-modals', difficulty:3,
    subsection:'obligation',
    question:'Which pair of modals are CLOSEST in meaning?',
    options:['can and must','should and have to','must and have to','may and must'],
    answer:'must and have to',
    hint:'Both express necessity or obligation.',
    explanation:'"<b>Must</b>" and "<b>have to</b>" are closest in meaning — both express obligation/necessity. "Must" often comes from the speaker\'s own feeling ("I must exercise more"); "have to" often refers to an external rule ("I have to wear a uniform").' }),

  // ── Grammar · Prepositions ───────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-prepositions-001', chapterId:'g7eng-gr-prepositions', difficulty:1,
    subsection:'place_time',
    question:'Choose the correct preposition: "The meeting is _____ 10 o\'clock."',
    options:['in','on','at','by'],
    answer:'at',
    hint:'Use "at" for exact times.',
    explanation:'"<b>At</b> 10 o\'clock" — use <b>at</b> for exact times (at 3 pm, at midnight, at noon). Use <b>in</b> for months/years/centuries (in January, in 2024). Use <b>on</b> for days and dates (on Monday, on 12 March).' }),

  makeMCQ({ id:'g7eng-gr-prepositions-002', chapterId:'g7eng-gr-prepositions', difficulty:1,
    subsection:'place_time',
    question:'Choose the correct preposition: "She was born _____ March."',
    options:['at','on','in','by'],
    answer:'in',
    hint:'Use "in" for months and years.',
    explanation:'"Born <b>in</b> March" — use <b>in</b> for months (in March), years (in 2010) and seasons (in summer). Use <b>on</b> for specific dates (on 5 March). Use <b>at</b> for times (at 3 pm).' }),

  makeMCQ({ id:'g7eng-gr-prepositions-003', chapterId:'g7eng-gr-prepositions', difficulty:2,
    subsection:'place_time',
    question:'Choose the correct preposition: "The cat is sitting _____ the table."',
    options:['in','between','under','beside'],
    answer:'under',
    hint:'The cat is below the table surface.',
    explanation:'"<b>Under</b> the table" — under = directly below something. "Beside" = next to. "Between" = in the middle of two things. "In" = inside. Choose based on the physical relationship described.' }),

  makeMCQ({ id:'g7eng-gr-prepositions-004', chapterId:'g7eng-gr-prepositions', difficulty:2,
    subsection:'direction',
    question:'Choose the correct preposition: "She walked _____ the bridge to the other side of the river."',
    options:['into','towards','across','along'],
    answer:'across',
    hint:'"Across" means from one side to the other.',
    explanation:'"Walked <b>across</b> the bridge" — across = from one side to the other. "Along" = following the length of something (along the river). "Into" = entering. "Towards" = in the direction of (but not necessarily reaching).' }),

  makeMCQ({ id:'g7eng-gr-prepositions-005', chapterId:'g7eng-gr-prepositions', difficulty:3,
    subsection:'direction',
    question:'Which preposition is correct: "The boys ran _____ the building to escape the rain."',
    options:['across','into','along','out of'],
    answer:'into',
    hint:'They entered the building.',
    explanation:'"Ran <b>into</b> the building" — "into" expresses movement from outside to inside. "Out of" = moving from inside to outside. "Across" = from one side to the other. "Along" = following a path.' }),

  makeMCQ({ id:'g7eng-gr-prepositions-006', chapterId:'g7eng-gr-prepositions', difficulty:3,
    subsection:'place_time',
    question:'Choose the correct preposition: "I have been waiting _____ two hours."',
    options:['since','during','for','from'],
    answer:'for',
    hint:'"For" is used with a period or length of time.',
    explanation:'"Waiting <b>for</b> two hours" — use <b>for</b> with a period/duration of time (for two hours, for a week, for a long time). Use <b>since</b> with a starting point in time (since 9 am, since Monday).' }),

  // ── Grammar · Sentence Structure ─────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-sentence-001', chapterId:'g7eng-gr-sentence', difficulty:1,
    subsection:'simple_compound',
    question:'Which is a SIMPLE SENTENCE?',
    options:['She sings and he plays the guitar.','Although it was raining, they went out.','The dog barked loudly.','I stayed home because I was ill.'],
    answer:'The dog barked loudly.',
    hint:'A simple sentence has one independent clause — one subject and one verb (plus any additions).',
    explanation:'"The dog barked loudly" is a <b>simple sentence</b> — one subject (the dog), one verb (barked), one clause. "She sings and he plays" = compound (two clauses joined by "and"). Sentences with "although" and "because" are complex.' }),

  makeMCQ({ id:'g7eng-gr-sentence-002', chapterId:'g7eng-gr-sentence', difficulty:1,
    subsection:'simple_compound',
    question:'Which COORDINATING CONJUNCTION joins two independent clauses to make a COMPOUND sentence?',
    options:['because','although','but','when'],
    answer:'but',
    hint:'Coordinating conjunctions join two equal clauses. Remember: FANBOYS (For, And, Nor, But, Or, Yet, So).',
    explanation:'"<b>But</b>" is a coordinating conjunction (part of FANBOYS: For, And, Nor, But, Or, Yet, So). It joins two independent clauses: "She studied hard, <b>but</b> she failed the test." "Because", "although" and "when" are subordinating conjunctions (used in complex sentences).' }),

  makeMCQ({ id:'g7eng-gr-sentence-003', chapterId:'g7eng-gr-sentence', difficulty:2,
    subsection:'complex_sentences',
    question:'Which is a COMPLEX SENTENCE?',
    options:['I went to the market and bought some fruit.','The teacher explained the lesson.','She left early because she had a doctor\'s appointment.','He is tall and she is short.'],
    answer:'She left early because she had a doctor\'s appointment.',
    hint:'A complex sentence has a main clause and a subordinate clause joined by a subordinating conjunction.',
    explanation:'"She left early <b>because</b> she had a doctor\'s appointment" is complex — it has a main clause ("She left early") and a subordinate clause ("because she had a…") joined by the subordinating conjunction "because". "And" creates compound sentences.' }),

  makeMCQ({ id:'g7eng-gr-sentence-004', chapterId:'g7eng-gr-sentence', difficulty:2,
    subsection:'complex_sentences',
    question:'Complete with the correct subordinating conjunction: "_____ I was walking home, I found a wallet on the road."',
    options:['But','And','While','So'],
    answer:'While',
    hint:'One action was happening at the same time as another. Which conjunction shows this?',
    explanation:'"<b>While</b> I was walking home, I found a wallet" — "while" introduces a subordinate clause showing that two actions happened at the same time. "But" and "and" are coordinating; "so" shows result.' }),

  makeMCQ({ id:'g7eng-gr-sentence-005', chapterId:'g7eng-gr-sentence', difficulty:3,
    subsection:'complex_sentences',
    question:'Which sentence correctly uses a RELATIVE CLAUSE with "who"?',
    options:['The man who is tall lives next door.','The man who is tall lives next door, who.','Who lives next door the man is tall.','The man is tall who next door lives.'],
    answer:'The man who is tall lives next door.',
    hint:'The relative clause "who is tall" should come right after the noun it describes.',
    explanation:'"The man <b>who is tall</b> lives next door" — the relative clause "who is tall" directly follows "the man" (the noun it describes). Relative clauses must attach directly to their noun.' }),

  makeMCQ({ id:'g7eng-gr-sentence-006', chapterId:'g7eng-gr-sentence', difficulty:3,
    subsection:'simple_compound',
    question:'Combine these two simple sentences into a COMPOUND sentence: "It was hot. We went swimming."',
    options:['It was hot when we went swimming.','It was hot, so we went swimming.','Although it was hot, we went swimming.','We went swimming because it was hot.'],
    answer:'It was hot, so we went swimming.',
    hint:'A compound sentence joins two equal clauses with a coordinating conjunction. "So" shows result.',
    explanation:'"It was hot, <b>so</b> we went swimming" — a compound sentence uses a coordinating conjunction (so, and, but, or). "When" and "although" create complex sentences (subordinating conjunctions). "Because" also creates a complex sentence.' }),

  // ── Grammar · Punctuation ────────────────────────────────────────────────

  makeMCQ({ id:'g7eng-gr-punctuation-001', chapterId:'g7eng-gr-punctuation', difficulty:1,
    subsection:'full_stop_comma',
    question:'Which sentence uses a COMMA correctly?',
    options:['She loves, reading music and dancing.','She loves reading, music and dancing.','She, loves reading music and dancing.','She loves reading music, and, dancing.'],
    answer:'She loves reading, music and dancing.',
    hint:'Commas separate items in a list.',
    explanation:'"She loves reading<b>,</b> music and dancing" — commas separate items in a list. In a list of three or more items, commas go between the items (and is often used before the last one without a comma: reading, music and dancing).' }),

  makeMCQ({ id:'g7eng-gr-punctuation-002', chapterId:'g7eng-gr-punctuation', difficulty:1,
    subsection:'full_stop_comma',
    question:'Which sentence is punctuated CORRECTLY?',
    options:['what time does the bus leave','What time does the bus leave','What time does the bus leave.','What time does the bus leave?'],
    answer:'What time does the bus leave?',
    hint:'A direct question ends with a question mark.',
    explanation:'Direct questions always end with a <b>question mark (?)</b>. The first word of a sentence always begins with a <b>capital letter</b>. "What time does the bus leave?" has both correct capital and question mark.' }),

  makeMCQ({ id:'g7eng-gr-punctuation-003', chapterId:'g7eng-gr-punctuation', difficulty:2,
    subsection:'colon_direct_speech',
    question:'Which sentence uses a COLON correctly to introduce a list?',
    options:['She bought: apples oranges and mangoes.','She bought apples, oranges and mangoes:','She bought the following fruits: apples, oranges and mangoes.','She: bought apples, oranges and mangoes.'],
    answer:'She bought the following fruits: apples, oranges and mangoes.',
    hint:'A colon introduces a list. It usually follows a complete clause.',
    explanation:'"She bought the following fruits<b>:</b> apples, oranges and mangoes" — a <b>colon</b> follows a complete sentence and introduces a list or explanation. Do not put a colon directly after a verb (not "She bought: apples…").' }),

  makeMCQ({ id:'g7eng-gr-punctuation-004', chapterId:'g7eng-gr-punctuation', difficulty:2,
    subsection:'colon_direct_speech',
    question:'Which sentence punctuates DIRECT SPEECH correctly?',
    options:['"Come here" said the teacher.','The teacher said, "Come here."','"come here," said the teacher.','"Come here." said the teacher.'],
    answer:'The teacher said, "Come here."',
    hint:'Direct speech uses inverted commas. A comma separates the reporting clause from the speech.',
    explanation:'"The teacher said, <b>"Come here."</b>" — Direct speech rules: (1) use inverted commas around the spoken words, (2) begin with a capital letter inside the inverted commas, (3) use a comma after the reporting verb before the speech opens, (4) put the full stop inside the closing inverted commas.' }),

  makeMCQ({ id:'g7eng-gr-punctuation-005', chapterId:'g7eng-gr-punctuation', difficulty:3,
    subsection:'full_stop_comma',
    question:'Which sentence uses a comma in APPOSITION correctly?',
    options:['Mr. Ramdin, our headteacher, won the award.','Mr. Ramdin our headteacher, won the award.','Mr. Ramdin our headteacher won, the award.','Mr. Ramdin, our headteacher won the award.'],
    answer:'Mr. Ramdin, our headteacher, won the award.',
    hint:'A noun in apposition renames the previous noun. It is enclosed in commas on BOTH sides.',
    explanation:'"Mr. Ramdin<b>,</b> our headteacher<b>,</b> won the award." — "our headteacher" is a noun phrase in apposition (it renames Mr. Ramdin). It is set off by commas on <b>both sides</b>. Removing it leaves a complete sentence: "Mr. Ramdin won the award."' }),

  makeMCQ({ id:'g7eng-gr-punctuation-006', chapterId:'g7eng-gr-punctuation', difficulty:3,
    subsection:'colon_direct_speech',
    question:'Where does the COMMA go when direct speech comes FIRST?',
    options:['"I am tired." she said.','I am tired, she said.', '"I am tired," she said.','"I am tired", she said.'],
    answer:'"I am tired," she said.',
    hint:'The comma goes inside the inverted commas, before the closing quotation mark.',
    explanation:'"<b>"I am tired,"</b> she said." — when the reporting clause ("she said") comes after the direct speech, a comma goes inside the closing inverted commas. The reporting clause begins with a lowercase letter. Full stop only if speech is at the end of the whole sentence.' })

);
