'use strict';
// Grade 5 French - Le Passé Simple
// IDs format: g5fr-passe-simple-NNN

STATIC_QUESTIONS.push(

  makeMCQ({ id:'g5fr-passe-simple-001', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:1,
    question:'Le passé simple est utilisé principalement dans…',
    options:['la langue parlée quotidienne','les textes littéraires, les contes et les récits formels','les conversations téléphoniques','les messages entre amis'],
    answer:'les textes littéraires, les contes et les récits formels',
    hint:'Le passé simple = temps du récit écrit et littéraire.',
    explanation:'Le <b>passé simple</b> est le temps du <b>récit écrit</b> : livres, contes, romans, articles formels. À l\'oral et dans les conversations, on utilise le passé composé à la place. Exemple de conte : "Il était une fois un roi qui <b>régna</b> longtemps…"' }),

  makeMCQ({ id:'g5fr-passe-simple-002', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:1,
    question:'Quelle est la terminaison du passé simple pour "il" avec un verbe en -ER ?',
    options:['-a','-it','-ut','-ait'],
    answer:'-a',
    hint:'Verbes en -ER au passé simple : je -ai, tu -as, il -a, nous -âmes, vous -âtes, ils -èrent.',
    explanation:'Pour les verbes en <b>-ER</b>, les terminaisons du passé simple sont : je -ai, tu -as, il/elle <b>-a</b>, nous -âmes, vous -âtes, ils/elles -èrent. Parler → il <b>parla</b>, manger → il <b>mangea</b>.' }),

  makeMCQ({ id:'g5fr-passe-simple-003', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:1,
    question:'Conjugue PARLER au passé simple pour "il" : Il ___ à voix basse.',
    options:['parla','parlait','a parlé','parlera'],
    answer:'parla',
    hint:'Parler (verbe en -ER) → passé simple il = radical + -a.',
    explanation:'"Il <b>parla</b>" - parler → radical parl- + terminaison -a → parla. C\'est le passé simple d\'un verbe en -ER.' }),

  makeTF({ id:'g5fr-passe-simple-004', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:1,
    question:'Le passé simple d\'"aller" pour "il" est "alla".',
    answer:true,
    hint:'Aller est un verbe en -ER → terminaisons en -a/-as/-a…',
    explanation:'<b>Vrai.</b> Aller → passé simple : j\'allai, tu allas, il/elle <b>alla</b>, nous allâmes, vous allâtes, ils/elles allèrent. "Alla" est correct.' }),

  makeMCQ({ id:'g5fr-passe-simple-005', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:1,
    question:'Quel est le passé simple d\'ÊTRE pour "il" ?',
    options:['était','a été','fut','serait'],
    answer:'fut',
    hint:'Être est irrégulier au passé simple. Radical = f-.',
    explanation:'Être → passé simple : je fus, tu fus, il/elle <b>fut</b>, nous fûmes, vous fûtes, ils/elles furent. "Fut" est le passé simple de "il est".' }),

  makeMCQ({ id:'g5fr-passe-simple-006', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:2,
    question:'Conjugue MANGER au passé simple pour "ils" : Ils ___ en silence.',
    options:['mangeaient','mangèrent','mangeront','ont mangé'],
    answer:'mangèrent',
    hint:'Verbes en -ER, terminaison "ils" = -èrent. Manger → ils mang-èrent.',
    explanation:'"Ils <b>mangèrent</b>" - verbe en -ER, terminaison pour ils/elles = <b>-èrent</b>. Attention : manger → ils mang<b>è</b>rent (accent grave). Autres exemples : parler → ils parlèrent, aimer → ils aimèrent.' }),

  makeMCQ({ id:'g5fr-passe-simple-007', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Quel est le passé simple d\'AVOIR pour "elle" ?',
    options:['avait','a eu','eut','aurait'],
    answer:'eut',
    hint:'Avoir est irrégulier. Radical = e- : j\'eus, tu eus, il/elle eut…',
    explanation:'Avoir → passé simple : j\'eus, tu eus, il/elle <b>eut</b>, nous eûmes, vous eûtes, ils/elles eurent. "Eut" est le passé simple de "il/elle a".' }),

  makeMCQ({ id:'g5fr-passe-simple-008', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:2,
    question:'Dans le texte : "Le prince <u>traversa</u> la forêt et <u>arriva</u> au château." Ces verbes sont…',
    options:['à l\'imparfait','au présent','au passé composé','au passé simple'],
    answer:'au passé simple',
    hint:'Terminaisons -a et -a dans un récit → passé simple des verbes en -ER.',
    explanation:'"Traversa" et "arriva" sont au <b>passé simple</b> (terminaisons -a des verbes en -ER). Ce temps est typique des <b>contes et récits littéraires</b>.' }),

  makeMCQ({ id:'g5fr-passe-simple-009', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Conjugue VENIR au passé simple pour "il" : Il ___ me voir.',
    options:['venait','est venu','vint','viendra'],
    answer:'vint',
    hint:'Venir est irrégulier au passé simple. Radical = v- : il vint.',
    explanation:'Venir → passé simple : je vins, tu vins, il/elle <b>vint</b>, nous vînmes, vous vîntes, ils/elles vinrent. "Vint" est irrégulier - à apprendre par cœur.' }),

  makeTF({ id:'g5fr-passe-simple-010', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:2,
    question:'"Ils parlèrent" est la forme correcte de parler au passé simple pour "ils".',
    answer:true,
    hint:'Verbes en -ER, ils/elles : -èrent.',
    explanation:'<b>Vrai.</b> Parler → ils/elles <b>parlèrent</b>. Terminaison correcte pour ils/elles avec les verbes en -ER = <b>-èrent</b>.' }),

  makeMCQ({ id:'g5fr-passe-simple-011', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Quel est le passé simple de FAIRE pour "il" ?',
    options:['faisait','a fait','fit','ferait'],
    answer:'fit',
    hint:'Faire est irrégulier. Radical = f- : je fis, tu fis, il fit…',
    explanation:'Faire → passé simple : je fis, tu fis, il/elle <b>fit</b>, nous fîmes, vous fîtes, ils/elles firent. Mémorisez : être → fut, avoir → eut, faire → fit.' }),

  makeMCQ({ id:'g5fr-passe-simple-012', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:3,
    question:'Laquelle de ces phrases est au passé simple ?',
    options:[
      'Il marchait lentement.',
      'Il a marché lentement.',
      'Il marcha lentement.',
      'Il marchera lentement.'
    ],
    answer:'Il marcha lentement.',
    hint:'Passé simple d\'un verbe en -ER pour "il" : terminaison -a.',
    explanation:'"Il <b>marcha</b>" - terminaison -a → passé simple. "Marchait" = imparfait. "A marché" = passé composé. "Marchera" = futur simple.' }),

  makeMCQ({ id:'g5fr-passe-simple-013', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:3,
    question:'Conjugue TROUVER au passé simple pour "nous" : Nous ___ un trésor.',
    options:['trouvâmes','trouvions','avons trouvé','trouvèrent'],
    answer:'trouvâmes',
    hint:'Verbes en -ER, terminaison "nous" = -âmes (avec accent circonflexe).',
    explanation:'"Nous <b>trouvâmes</b>" - verbe en -ER, terminaison pour nous = <b>-âmes</b>. Trouver → nous trouv-<b>âmes</b>. Attention à l\'accent circonflexe sur le â.' }),

  makeMCQ({ id:'g5fr-passe-simple-014', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:3,
    question:'Identifie le passé simple dans ce passage de conte : "Il était une fois un roi qui régnait sur un beau royaume. Un jour, un dragon apparut et détruisit le village."',
    options:['était, régnait','apparut, détruisit','est apparu, a détruit','apparaît, détruit'],
    answer:'apparut, détruisit',
    hint:'"Apparut" et "détruisit" - terminaisons -ut et -it = passé simple irrégulier.',
    explanation:'"<b>Apparut</b>" et "<b>détruisit</b>" sont au passé simple. "Était" et "régnait" sont à l\'imparfait (description/état). Les événements du récit (actions principales) sont au passé simple dans les textes littéraires.' }),

  makeMCQ({ id:'g5fr-passe-simple-015', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:3,
    question:'Conjugue CHANTER au passé simple pour "vous" : Vous ___ une belle chanson.',
    options:['chantâtes','chantiez','avez chanté','chantèrent'],
    answer:'chantâtes',
    hint:'Verbes en -ER, terminaison "vous" = -âtes (avec accent circonflexe).',
    explanation:'"Vous <b>chantâtes</b>" - terminaison pour vous = <b>-âtes</b>. Chanter → vous chant-<b>âtes</b>. Note : cette forme est rare à l\'oral mais apparaît dans les textes littéraires.' }),

  makeMCQ({ id:'g5fr-passe-simple-016', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:3,
    question:'Quelle différence y a-t-il entre "il parla" (passé simple) et "il a parlé" (passé composé) ?',
    options:[
      'Aucune différence de sens.',
      'Le passé simple s\'utilise à l\'oral ; le passé composé dans les écrits.',
      'Le passé simple s\'utilise dans les écrits littéraires ; le passé composé à l\'oral.',
      'Le passé simple désigne le futur.'
    ],
    answer:'Le passé simple s\'utilise dans les écrits littéraires ; le passé composé à l\'oral.',
    hint:'Les deux expriment une action passée terminée - la différence est stylistique et de registre.',
    explanation:'<b>Passé simple</b> = registre écrit/littéraire (livres, contes, journaux). <b>Passé composé</b> = registre parlé et écrit courant. Le sens est identique, mais le style diffère.' }),

  makeMCQ({ id:'g5fr-passe-simple-017', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:3,
    question:'Complète ce début de conte : "Il était une fois une jeune fille qui ___ (vivre) dans une forêt. Un matin, elle ___ (partir) chercher des baies."',
    options:['vécut / partit','vivait / est partie','vivait / partit','vécut / partait'],
    answer:'vivait / partit',
    hint:'"Vivait" = description (imparfait). "Partit" = action principale du récit (passé simple).',
    explanation:'"Elle <b>vivait</b>" - description d\'un état habituel → imparfait. "Elle <b>partit</b>" - action principale du récit → passé simple. Dans les contes, on alterne imparfait (décor, état) et passé simple (événements).' }),

  makeMCQ({ id:'g5fr-passe-simple-018', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:4,
    question:'Quel est le passé simple de NAÎTRE pour "il" dans la phrase : "Le prince ___ dans un château au bord de la mer."',
    options:['naissait','est né','naquit','naîtra'],
    answer:'naquit',
    hint:'Naître est irrégulier au passé simple. Radical = naqu-.',
    explanation:'Naître → passé simple : je naquis, tu naquis, il/elle <b>naquit</b>, nous naquîmes, ils naquirent. Irrégulier - à apprendre.' }),

  makeMCQ({ id:'g5fr-passe-simple-019', chapterId:'g5fr-passe-simple', subsection:'usage', difficulty:4,
    question:'Complète ce récit en choisissant les bons temps : "Le soleil ___ (briller). Soudain, le héros ___ (entendre) un cri, ___ (sortir) de sa maison et ___ (courir) vers la rivière."',
    options:[
      'brillait / entendit / sortit / courut',
      'brilla / entendait / sortait / courait',
      'brillait / a entendu / est sorti / a couru',
      'brille / entendit / sortit / courut'
    ],
    answer:'brillait / entendit / sortit / courut',
    hint:'"Le soleil brillait" = description (imparfait). "Soudain" = événements successifs (passé simple).',
    explanation:'"Le soleil <b>brillait</b>" - description de fond → imparfait. "Soudain, il <b>entendit / sortit / courut</b>" - actions soudaines et successives → passé simple. Structure classique du récit : imparfait + passé simple.' }),

  makeMCQ({ id:'g5fr-passe-simple-020', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Conjuguez "venir" au passé simple pour "je" :',
    options:['je venais','je vins','je suis venu','je vendrais'],
    answer:'je vins',
    hint:'Venir est irrégulier au passé simple : vins, vins, vint, vînmes, vîntes, vinrent.',
    explanation:'"<b>je vins</b>" - venir (irrégulier) : je <b>vins</b>, tu vins, il vint, nous vînmes, vous vîntes, ils vinrent. Même conjugaison pour "tenir" : je tins, tu tins, il tint.' }),

  makeMCQ({ id:'g5fr-passe-simple-021', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Conjuguez "voir" au passé simple pour "il" :',
    options:['il voyait','il verra','il vit','il voit'],
    answer:'il vit',
    hint:'Voir est irrégulier : je vis, il vit.',
    explanation:'"<b>il vit</b>" - voir (irrégulier) : je vis, tu vis, il/elle <b>vit</b>, nous vîmes, vous vîtes, ils virent. Exemple classique : "Il vit la princesse et tomba amoureux."' }),

  makeMCQ({ id:'g5fr-passe-simple-022', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Conjuguez "faire" au passé simple pour "ils" :',
    options:['ils faisaient','ils feront','ils firent','ils faisèrent'],
    answer:'ils firent',
    hint:'Faire est irrégulier : je fis, il fit, ils firent.',
    explanation:'"<b>ils firent</b>" - faire (irrégulier) : je fis, tu fis, il fit, nous fîmes, vous fîtes, ils/elles <b>firent</b>. Exemple : "Ils firent le tour du monde en 80 jours."' }),

  makeTF({ id:'g5fr-passe-simple-023', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Le passé simple d\'"avoir" pour "il" est "il eut".',
    answer:true,
    hint:'Avoir est irrégulier : j\'eus, tu eus, il eut.',
    explanation:'<b>Vrai.</b> avoir (passé simple) : j\'eus, tu eus, il/elle <b>eut</b>, nous eûmes, vous eûtes, ils/elles eurent. Exemple littéraire : "Le roi eut une brillante idée."' }),

  makeMCQ({ id:'g5fr-passe-simple-024', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:3,
    question:'Conjuguez "prendre" au passé simple pour "nous" :',
    options:['nous prenions','nous prîmes','nous prissions','nous avons pris'],
    answer:'nous prîmes',
    hint:'Prendre est irrégulier : je pris, il prit, nous prîmes (accent circonflexe).',
    explanation:'"<b>nous prîmes</b>" - prendre (irrégulier) : je pris, tu pris, il prit, nous <b>prîmes</b>, vous prîtes, ils prirent. Note l\'accent circonflexe sur le i de prîmes/prîtes. Même conjugaison : apprendre → nous apprîmes, comprendre → nous comprîmes.' }),

  makeMCQ({ id:'g5fr-passe-simple-025', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:2,
    question:'Identifiez le verbe au passé simple : "Hier, le roi mangea une pomme dorée."',
    options:['Hier','le roi','mangea','une pomme dorée'],
    answer:'mangea',
    hint:'Cherchez la terminaison caractéristique des verbes en -ER au passé simple (3ème pers. sing. = -a).',
    explanation:'"<b>mangea</b>" - terminaison -a = passé simple, 3ème personne singulière, verbe en -ER. Manger → il mang<b>a</b>. Autres terminaisons des -ER au passé simple : je parla<b>i</b>, tu parla<b>s</b>, nous parlâm<b>es</b>.' }),

  makeTF({ id:'g5fr-passe-simple-026', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:3,
    question:'"Il finit" peut être soit le présent soit le passé simple du verbe "finir".',
    answer:true,
    hint:'Les verbes en -IR ont des terminaisons identiques au présent et au passé simple pour "il" : il finit.',
    explanation:'<b>Vrai.</b> Pour les verbes en -IR, la 3ème personne singulière est identique au présent et au passé simple : "il <b>finit</b>" (présent) = he finishes / "il <b>finit</b>" (passé simple) = he finished. Le contexte (temps de la narration) permet de distinguer.' }),

  makeMCQ({ id:'g5fr-passe-simple-027', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Conjuguez "pouvoir" au passé simple pour "je" :',
    options:['je pouvais','je pourrai','je pus','je pusse'],
    answer:'je pus',
    hint:'Pouvoir est irrégulier : je pus, tu pus, il put.',
    explanation:'"<b>je pus</b>" - pouvoir (irrégulier) : je pus, tu pus, il/elle put, nous pûmes, vous pûtes, ils/elles purent. Exemple : "Il ne put pas ouvrir la porte."' }),

  makeMCQ({ id:'g5fr-passe-simple-028', chapterId:'g5fr-passe-simple', subsection:'irreguliers', difficulty:2,
    question:'Conjuguez "savoir" au passé simple pour "elle" :',
    options:['elle savait','elle saura','elle sut','elle sûte'],
    answer:'elle sut',
    hint:'Savoir est irrégulier : je sus, tu sus, il/elle sut.',
    explanation:'"<b>elle sut</b>" - savoir (irrégulier) : je sus, tu sus, il/elle <b>sut</b>, nous sûmes, vous sûtes, ils surent. Exemple : "Elle sut immédiatement que quelque chose clochait."' }),

  makeMCQ({ id:'g5fr-passe-simple-029', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:3,
    question:'Complétez le conte : "La sorcière ___ (tendre) la main et ___ (offrir) une pomme à la princesse."',
    options:['tendit / offrit','tendait / offrait','tendu / offert','tendra / offrira'],
    answer:'tendit / offrit',
    hint:'Actions dans un récit littéraire = passé simple. Tendre → tendit ; offrir → offrit.',
    explanation:'"La sorcière <b>tendit</b> la main et <b>offrit</b> une pomme." - tendre (-RE) passé simple : je tendis, il tendit. Offrir (-IR irrégulier) : j\'offris, il offrit. Dans les contes, les actions principales = passé simple.' }),

  makeMCQ({ id:'g5fr-passe-simple-030', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:2,
    question:'Passé simple des verbes en -RE : "attendre" pour "ils" ?',
    options:['ils attendèrent','ils attendirent','ils attendront','ils attendaient'],
    answer:'ils attendirent',
    hint:'Verbes en -RE : terminaisons -is, -is, -it, -îmes, -îtes, -irent.',
    explanation:'"<b>ils attendirent</b>" - attendre (-RE) au passé simple : j\'attendis, tu attendis, il attendit, nous attendîmes, vous attendîtes, ils/elles <b>attendirent</b>. Même terminaison pour : répondre → ils répondirent, vendre → ils vendirent.' }),

  makeTF({ id:'g5fr-passe-simple-031', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:2,
    question:'Pour les verbes en -IR réguliers, les terminaisons du passé simple sont : -is, -is, -it, -îmes, -îtes, -irent.',
    answer:true,
    hint:'Finir → je finis, tu finis, il finit, nous finîmes, vous finîtes, ils finirent.',
    explanation:'<b>Vrai.</b> Verbes en -IR réguliers : finir → je finis, tu finis, il <b>finit</b>, nous <b>finîmes</b>, vous <b>finîtes</b>, ils <b>finirent</b>. Attention aux accents circonflexes : finîmes/finîtes. Même conjugaison : choisir → il choisit, nous choisîmes.' }),

  makeMCQ({ id:'g5fr-passe-simple-032', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:2,
    question:'Conjuguez "tenir" au passé simple pour "il" :',
    options:['il tenait','il tiendra','il tint','il tendit'],
    answer:'il tint',
    hint:'Tenir est irrégulier : même schéma que "venir" (vins → tins).',
    explanation:'"<b>il tint</b>" - tenir (irrégulier) : je tins, tu tins, il/elle <b>tint</b>, nous tînmes, vous tîntes, ils tinrent. Exemple : "Il tint sa promesse jusqu\'au bout."' }),

  makeMCQ({ id:'g5fr-passe-simple-033', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:3,
    question:'Dans ce texte, quel verbe est au passé simple ? "Les nuages envahissaient le ciel. Soudain, l\'éclair jaillit."',
    options:['envahissaient','le ciel','jaillit','soudain'],
    answer:'jaillit',
    hint:'"Soudain" annonce souvent une action soudaine au passé simple.',
    explanation:'"<b>jaillit</b>" = passé simple (3ème pers. sing. de jaillir). "Envahissaient" = imparfait (action progressive, description de fond). Dans les récits, l\'imparfait décrit le contexte et le passé simple exprime les actions soudaines/ponctuelles.' }),

  makeMCQ({ id:'g5fr-passe-simple-034', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:2,
    question:'Conjuguez "vouloir" au passé simple pour "tu" :',
    options:['tu voulais','tu voudrais','tu voulus','tu voulûtes'],
    answer:'tu voulus',
    hint:'Vouloir est irrégulier : je voulus, tu voulus.',
    explanation:'"<b>tu voulus</b>" - vouloir (irrégulier) : je voulus, tu <b>voulus</b>, il voulut, nous voulûmes, vous voulûtes, ils voulurent. Exemple : "Tu voulus partir mais il était trop tard."' }),

  makeMCQ({ id:'g5fr-passe-simple-035', chapterId:'g5fr-passe-simple', subsection:'formation', difficulty:4,
    question:'Quel temps est utilisé pour "régnait" et pour "reçut" dans : "Il était une fois un roi qui régnait sur un grand royaume. Un jour, il reçut une lettre mystérieuse." ?',
    options:[
      'régnait = passé simple ; reçut = imparfait',
      'régnait = imparfait ; reçut = passé simple',
      'régnait = passé composé ; reçut = passé simple',
      'tous les deux = passé simple'
    ],
    answer:'régnait = imparfait ; reçut = passé simple',
    hint:'"Régnait" = état habituel (fond) ; "reçut" = action ponctuelle (événement).',
    explanation:'"<b>régnait</b>" = imparfait (état habituel/description : le roi régnait depuis longtemps). "<b>reçut</b>" = passé simple (événement soudain/ponctuel : il reçut une lettre ce jour-là). Structure classique du récit : imparfait pour le décor, passé simple pour les événements.' })

);
